DEPS = deps
SHELL = bash
MPIRUN ?= mpirun # srun in Slurm, aprun in Cray-land, etc.

# GFDL build toolchain
MKMF_URL ?= https://github.com/NOAA-GFDL/mkmf.git
MKMF_COMMIT ?= master

LIST_PATHS = $(abspath $(DEPS)/mkmf/bin/list_paths)
MKMF = $(abspath $(DEPS)/mkmf/bin/mkmf)

# FMS framework
FMS_URL ?= https://github.com/NOAA-GFDL/FMS.git
FMS_COMMIT ?= f2e2c86f6c0eb6d389a20509a8a60fa22924e16b
FMS := $(DEPS)/fms

# Function to get list of files
# TODO: .h and .c files
#FMS_FILES = $(sort $(shell find $(FMS)/src -name '*.F90'))
#MOM_FILES = $(sort $(shell find src config_src/solo_driver -name '*.F90'))

# Build settings
MKMF_CPP = "-Duse_libMPI -Duse_netCDF -DSPMD"

# Environment
# TODO: This info ought to be determined by CMake, automake, etc.
MKMF_TEMPLATE ?= "linux-ubuntu-xenial-gnu.mk"
#MKMF_TEMPLATE ?= "ncrc-gnu.mk"
#MKMF_TEMPLATE ?= "ncrc-intel.mk"

# Reference codebase
MOM_TARGET_URL ?= https://github.com/NOAA-GFDL/MOM6.git
MOM_TARGET_REMOTE ?= target
MOM_TARGET_BRANCH ?= $(MOM_TARGET_REMOTE)/dev/gfdl

# Grid types
GRIDS = symmetric asymmetric

# Executables
# TODO: REPRO, coverage, ??
BUILDS = target $(GRIDS)

# Test experiments
TESTS = benchmark unit_tests


#-------------------
# Executable

.PHONY: all
all: $(foreach b,$(BUILDS),build/$(b)/MOM6)

build/target/MOM6: BRANCH=$(MOM_TARGET_BRANCH)
build/target/Makefile: BRANCH=$(MOM_TARGET_BRANCH)
build/target/path_names: BRANCH=$(MOM_TARGET_BRANCH)

build/%/MOM6: build/%/Makefile $(FMS)/lib/libfms.a
	if [ $(BRANCH) ]; then git checkout $(BRANCH); fi
	make -C $(@D) NETCDF=3 DEBUG=1 COVERAGE=1 $(@F)
	if [ $(BRANCH) ]; then git checkout @{-1}; fi

build/%/Makefile: build/%/path_names
	if [ $(BRANCH) ]; then git checkout $(BRANCH); fi
	cp .testing/$(MKMF_TEMPLATE) $(@D)
	cd $(@D) && $(MKMF) \
		-t $(MKMF_TEMPLATE) \
		-o '-I ../../$(FMS)/build' \
		-p MOM6 \
		-l '../../$(FMS)/lib/libfms.a' \
		-c $(MKMF_CPP) \
		path_names
	if [ $(BRANCH) ]; then git checkout @{-1}; fi

# TODO: Merge path_names rules?
build/symmetric/path_names: $(LIST_PATHS)
	mkdir -p $(@D)
	cd $(@D) && $(LIST_PATHS) -l \
		../../src \
		../../config_src/solo_driver \
		../../config_src/dynamic_symmetric

build/asymmetric/path_names: $(LIST_PATHS)
	mkdir -p $(@D)
	cd $(@D) && $(LIST_PATHS) -l \
		../../src \
		../../config_src/solo_driver \
		../../config_src/dynamic

build/target/path_names: $(LIST_PATHS) .git/refs/remotes/$(MOM_TARGET_BRANCH)
	git checkout $(MOM_TARGET_BRANCH)
	mkdir -p $(@D)
	cd $(@D) && $(LIST_PATHS) -l \
		../../src \
		../../config_src/solo_driver \
		../../config_src/dynamic_symmetric
	git checkout @{-1}

# XXX: ls-remote is probably redundant here; no file means ls-remote is nonzero!
# 	   Maybe move this into path_names rule?
.git/refs/remotes/$(MOM_TARGET_BRANCH):
	git ls-remote $(MOM_TARGET_REMOTE) \
		|| git remote add $(MOM_TARGET_REMOTE) $(MOM_TARGET_URL)
	git fetch --no-recurse-submodules $(MOM_TARGET_REMOTE)


#----
# FMS build

$(FMS)/lib/libfms.a: $(FMS)/build/Makefile
	mkdir -p $(FMS)/lib
	cd $(FMS)/build && make NETCDF=3 DEBUG=1 ../lib/libfms.a

$(FMS)/build/Makefile: $(FMS)/build/path_names
	cp .testing/$(MKMF_TEMPLATE) $(@D)
	cd $(@D) && $(MKMF) \
		-t $(MKMF_TEMPLATE) \
		-p ../lib/libfms.a \
		-c $(MKMF_CPP) \
		path_names

$(FMS)/build/path_names: $(FMS)/src $(FMS_FILES) $(LIST_PATHS)
	mkdir -p $(@D)
	cd $(@D) && $(LIST_PATHS) -l ../src

$(FMS)/src:
	git clone $(FMS_URL) $@
	cd $@; git checkout $(FMS_COMMIT)


#----
# Build Toolchain

$(LIST_PATHS) $(MKMF):
	git clone $(MKMF_URL) $(DEPS)/mkmf
	cd $(DEPS)/mkmf; git checkout $(MKMF_COMMIT)


#----
# Testing

# TODO: Add test.grid, test.layout, test.dimension, etc
.PHONY: test
test: test.regressions test.grids

.PHONY: test.regressions test.grids
test.regressions: $(foreach t,$(TESTS),$(t).regression)
test.grids: $(foreach t,$(TESTS),$(t).grid)

%.regression: $(foreach b,target symmetric,.testing/results/%/ocean.stats.$(b))
	cmp $^

%.grid: $(foreach g,$(GRIDS),.testing/results/%/ocean.stats.$(g))
	cmp $^

expt = $(word 3,$(subst /, ,$@))

#.testing/results/%/ocean.stats.target: EXEC=build/target/MOM6
#.testing/results/%/ocean.stats.symmetric: EXEC=build/symmetric/MOM6
#
#$(foreach b,$(BUILDS),.testing/results/%/ocean.stats.$(b)):
#	mkdir -p .testing/$(expt)/RESTART
#	cd .testing/$(expt) && $(MPIRUN) -n 1 ../../$(EXEC)
#	mkdir -p $(@D)
#	cp .testing/$(expt)/ocean.stats $@

.testing/results/%/ocean.stats.symmetric: build/symmetric/MOM6
	# Apply code coverage on symmetric tests
	find build -name *.gcda -exec rm -f '{}' \;
	mkdir -p .testing/$(expt)/RESTART
	cd .testing/$(expt) && $(MPIRUN) -n 1 ../../$<
	mkdir -p $(@D)
	cp .testing/$(expt)/ocean.stats $@
	bash <(curl -s https://codecov.io/bash) -n $@

.testing/results/%/ocean.stats.asymmetric: build/asymmetric/MOM6
	mkdir -p .testing/$(expt)/RESTART
	cd .testing/$(expt) && $(MPIRUN) -n 1 ../../$<
	mkdir -p $(@D)
	cp .testing/$(expt)/ocean.stats $@

.testing/results/%/ocean.stats.target: build/target/MOM6
	mkdir -p .testing/$(expt)/RESTART
	cd .testing/$(expt) && $(MPIRUN) -n 1 ../../$<
	mkdir -p $(@D)
	cp .testing/$(expt)/ocean.stats $@


#----
.PHONY: clean
clean:
	rm -rf build
