DEPS = deps
SHELL = bash
MPIRUN ?= mpirun # srun in Slurm, aprun in Cray-land, etc.

# GFDL build toolchain
MKMF_URL ?= https://github.com/NOAA-GFDL/mkmf.git
MKMF_COMMIT ?= master

LIST_PATHS = $(abspath $(DEPS)/mkmf/bin/list_paths)
MKMF = $(abspath $(DEPS)/mkmf/bin/mkmf)

# FMS framework
FMS_URL ?= https://github.com/NOAA-GFDL/FMS.git
FMS_COMMIT ?= f2e2c86f6c0eb6d389a20509a8a60fa22924e16b
FMS := $(DEPS)/fms

# Function to get list of files
# TODO: .h and .c files
#FMS_FILES = $(sort $(shell find $(FMS)/src -name '*.F90'))
#MOM_FILES = $(sort $(shell find src config_src/solo_driver -name '*.F90'))

# Build settings
MKMF_CPP = "-Duse_libMPI -Duse_netCDF -DSPMD"

# Environment
# TODO: This info ought to be determined by CMake, automake, etc.
MKMF_TEMPLATE ?= "linux-ubuntu-xenial-gnu.mk"
#MKMF_TEMPLATE ?= "ncrc-gnu.mk"
#MKMF_TEMPLATE ?= "ncrc-intel.mk"

# Reference codebase
MOM_TARGET_URL ?= https://github.com/NOAA-GFDL/MOM6.git
MOM_TARGET_REMOTE ?= target
MOM_TARGET_BRANCH ?= $(MOM_TARGET_REMOTE)/dev/gfdl

MOM_MERGED_BRANCH := mergetest

# Grid types
GRIDS = symmetric asymmetric

# Executables
# TODO: REPRO, coverage, ??
BUILDS = target $(GRIDS)

# Test experiments
CONFIGS = benchmark unit_tests
# regressions is currently broken (deliberately)
TESTS = regressions grids nans layouts dims


.PHONY: all
all: $(foreach b,$(BUILDS),build/$(b)/MOM6)


#-------------------
# Executable

build/target/MOM6: build/target/Makefile $(FMS)/lib/libfms.a
	git checkout $(MOM_TARGET_BRANCH)
	make -C $(@D) NETCDF=3 DEBUG=1 $(@F)
	git checkout @{-1}

build/symmetric/MOM6: build/symmetric/Makefile $(FMS)/lib/libfms.a
	git checkout $(MOM_MERGED_BRANCH)
	make -C $(@D) NETCDF=3 DEBUG=1 COVERAGE=1 $(@F)
	git checkout @{-1}

build/asymmetric/MOM6: build/asymmetric/Makefile $(FMS)/lib/libfms.a
	git checkout $(MOM_MERGED_BRANCH)
	make -C $(@D) NETCDF=3 DEBUG=1 $(@F)
	git checkout @{-1}

# Makefile

build/target/Makefile: BRANCH=$(MOM_TARGET_BRANCH)
build/symmetric/Makefile: BRANCH=$(MOM_MERGED_BRANCH)
build/asymmetric/Makefile: BRANCH=$(MOM_MERGED_BRANCH)

build/%/Makefile: build/%/path_names
	if [ $(BRANCH) ]; then git checkout $(BRANCH); fi
	cp .testing/$(MKMF_TEMPLATE) $(@D)
	cd $(@D) && $(MKMF) \
		-t $(MKMF_TEMPLATE) \
		-o '-I ../../$(FMS)/build' \
		-p MOM6 \
		-l '../../$(FMS)/lib/libfms.a' \
		-c $(MKMF_CPP) \
		path_names
	if [ $(BRANCH) ]; then git checkout @{-1}; fi

# path_names

build/symmetric/path_names: $(LIST_PATHS) .git/refs/heads/$(MOM_MERGED_BRANCH)
	git checkout $(MOM_MERGED_BRANCH)
	mkdir -p $(@D)
	cd $(@D) && $(LIST_PATHS) -l \
		../../src \
		../../config_src/solo_driver \
		../../config_src/dynamic_symmetric
	git checkout @{-1}

build/asymmetric/path_names: $(LIST_PATHS) .git/refs/heads/$(MOM_MERGED_BRANCH)
	git checkout $(MOM_MERGED_BRANCH)
	mkdir -p $(@D)
	cd $(@D) && $(LIST_PATHS) -l \
		../../src \
		../../config_src/solo_driver \
		../../config_src/dynamic
	git checkout @{-1}

build/target/path_names: $(LIST_PATHS) .git/refs/remotes/$(MOM_TARGET_BRANCH)
	git checkout $(MOM_TARGET_BRANCH)
	mkdir -p $(@D)
	cd $(@D) && $(LIST_PATHS) -l \
		../../src \
		../../config_src/solo_driver \
		../../config_src/dynamic_symmetric
	git checkout @{-1}

# Target remote configuration

# XXX: ls-remote is probably redundant here; no file means ls-remote is nonzero!
# 	   Maybe move this into path_names rule?
.git/refs/remotes/$(MOM_TARGET_BRANCH):
	git ls-remote $(MOM_TARGET_REMOTE) \
		|| git remote add $(MOM_TARGET_REMOTE) $(MOM_TARGET_URL)
	git fetch --no-recurse-submodules $(MOM_TARGET_REMOTE)

.git/refs/heads/$(MOM_MERGED_BRANCH): .git/refs/remotes/$(MOM_TARGET_BRANCH)
	git checkout -b $(MOM_MERGED_BRANCH)
	git merge --no-edit $(MOM_TARGET_BRANCH)
	git checkout @{-1}

#----
# FMS build

$(FMS)/lib/libfms.a: $(FMS)/build/Makefile
	mkdir -p $(FMS)/lib
	cd $(FMS)/build && make NETCDF=3 DEBUG=1 ../lib/libfms.a

$(FMS)/build/Makefile: $(FMS)/build/path_names
	cp .testing/$(MKMF_TEMPLATE) $(@D)
	cd $(@D) && $(MKMF) \
		-t $(MKMF_TEMPLATE) \
		-p ../lib/libfms.a \
		-c $(MKMF_CPP) \
		path_names

$(FMS)/build/path_names: $(FMS)/src $(FMS_FILES) $(LIST_PATHS)
	mkdir -p $(@D)
	cd $(@D) && $(LIST_PATHS) -l ../src

$(FMS)/src:
	git clone $(FMS_URL) $@
	cd $@; git checkout $(FMS_COMMIT)


#----
# Build Toolchain

$(LIST_PATHS) $(MKMF):
	git clone $(MKMF_URL) $(DEPS)/mkmf
	cd $(DEPS)/mkmf; git checkout $(MKMF_COMMIT)


#----
# Testing

## Keep results (not sure if I want this on all the time...)
#.PRECIOUS: $(foreach c,$(CONFIGS),$(foreach t,$(BUILDS) grid nan dim.z dim.t,.testing/$(c)/ocean.stats.$(t)))

.PHONY: test
test: $(foreach t,$(TESTS),test.$(t))

.PHONY: $(foreach t,$(TESTS),test.$(t))
test.regressions: $(foreach c,$(CONFIGS),$(c).regression)
test.grids: $(foreach c,$(CONFIGS),$(c).grid)
test.layouts: $(foreach c,$(CONFIGS),$(c).layout)
test.nans: $(foreach c,$(CONFIGS),$(c).nan)
test.dims: $(foreach c,$(CONFIGS),$(foreach d,t l h z,$(c).dim.$(d)))

%.regression: $(foreach b,target symmetric,.testing/%/ocean.stats.$(b))
	cmp $^

%.grid: $(foreach g,$(GRIDS),.testing/%/ocean.stats.$(g))
	cmp $^

%.layout: $(foreach b,symmetric layout,.testing/%/ocean.stats.$(b))
	cmp $^

%.nan: $(foreach b,symmetric nan,.testing/%/ocean.stats.$(b))
	cmp $^

%.dim.t: $(foreach b,symmetric dim.t,.testing/%/ocean.stats.$(b))
	cmp $^

%.dim.l: $(foreach b,symmetric dim.l,.testing/%/ocean.stats.$(b))
	cmp $^

%.dim.h: $(foreach b,symmetric dim.h,.testing/%/ocean.stats.$(b))
	cmp $^

%.dim.z: $(foreach b,symmetric dim.z,.testing/%/ocean.stats.$(b))
	cmp $^

.testing/%/ocean.stats.symmetric: build/symmetric/MOM6
	# Report code coverage for symmetric tests
	find build -name *.gcda -exec rm -f '{}' \;
	mkdir -p $(@D)/RESTART
	> $(@D)/MOM_override
	cd $(@D) && $(MPIRUN) -n 1 ../../$<
	cp $(@D)/ocean.stats $@
	bash <(curl -s https://codecov.io/bash) -n $@

.testing/%/ocean.stats.asymmetric: build/asymmetric/MOM6
	mkdir -p $(@D)/RESTART
	> $(@D)/MOM_override
	cd $(@D) && $(MPIRUN) -n 1 ../../$<
	cp $(@D)/ocean.stats $@

.testing/%/ocean.stats.target: build/target/MOM6
	mkdir -p $(@D)/RESTART
	> $(@D)/MOM_override
	cd $(@D) && $(MPIRUN) -n 1 ../../$<
	cp $(@D)/ocean.stats $@

.testing/%/ocean.stats.layout: build/symmetric/MOM6
	mkdir -p $(@D)/RESTART
	echo "LAYOUT=2,1" > $(@D)/MOM_override
	cd $(@D) && $(MPIRUN) -n 2 ../../$<
	cp $(@D)/ocean.stats $@
	> $(@D)/MOM_override

.testing/%/ocean.stats.nan: build/symmetric/MOM6
	> $(@D)/MOM_override
	mkdir -p $(@D)/RESTART
	cd $(@D) && MALLOC_PERTURB_=256 $(MPIRUN) -n 1 ../../$<
	cp $(@D)/ocean.stats $@

.testing/%/ocean.stats.dim.t: build/symmetric/MOM6
	mkdir -p $(@D)/RESTART
	echo "T_RESCALE_POWER=9" > $(@D)/MOM_override
	cd $(@D) && $(MPIRUN) -n 1 ../../$<
	cp $(@D)/ocean.stats $@
	> $(@D)/MOM_override

.testing/%/ocean.stats.dim.l: build/symmetric/MOM6
	mkdir -p $(@D)/RESTART
	echo "L_RESCALE_POWER=9" > $(@D)/MOM_override
	cd $(@D) && $(MPIRUN) -n 1 ../../$<
	cp $(@D)/ocean.stats $@
	> $(@D)/MOM_override

.testing/%/ocean.stats.dim.h: build/symmetric/MOM6
	mkdir -p $(@D)/RESTART
	echo "H_RESCALE_POWER=9" > $(@D)/MOM_override
	cd $(@D) && $(MPIRUN) -n 1 ../../$<
	cp $(@D)/ocean.stats $@
	> $(@D)/MOM_override

.testing/%/ocean.stats.dim.z: build/symmetric/MOM6
	mkdir -p $(@D)/RESTART
	echo "Z_RESCALE_POWER=9" > $(@D)/MOM_override
	cd $(@D) && $(MPIRUN) -n 1 ../../$<
	cp $(@D)/ocean.stats $@
	> $(@D)/MOM_override


#----
.PHONY: clean
clean: clean.stats
	rm -rf build

clean.stats:
	find .testing -name ocean.stats* -exec rm {} \;
