name: 'Build-.testing-prerequisites'
description: 'Build pre-requisites for .testing including FMS and a symmetric MOM6 executable'
inputs:
  build_symmetric:
    description: 'If true, will build the symmetric MOM6 executable'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Git info
      shell: bash
      run: |
        echo "::group::Git commit info"
        echo "git log:"
        git log | head -60
        echo "::endgroup::"

    - name: Env
      shell: bash
      run: |
        echo "::group::Environment"
        env
        echo "::endgroup::"

    - name: Compile FMS library
      shell: bash
      run: |
        echo "::group::Compile FMS library"
        cd .testing
        REPORT_ERROR_LOGS=true make build/deps/lib/libFMS.a -s -j
        echo "::endgroup::"

    - name: Compile MOM6 in symmetric memory mode
      shell: bash
      run: |
        echo "::group::Compile MOM6 in symmetric memory mode"
        cd .testing
        test ${{ inputs.build_symmetric }} == true && make build/symmetric/MOM6 -j
        echo "::endgroup::"

    - name: Set flags
      shell: bash
      run: |
        echo "TIMEFORMAT=... completed in %lR  (user: %lU, sys: %lS)" >> $GITHUB_ENV
