MOM6: supercritical_initialization Module Reference
supercritical_initialization Module Reference
Detailed Description
The module configures the model for the "supercritical" experiment. https://marine.rutgers.edu/po/index.php?model=test-problems&title=supercritical.
Functions/Subroutines
subroutine, public supercritical_set_obc_data (OBC, G, param_file)
This subroutine sets the properties of flow at open boundary conditions.
subroutine, public supercritical_initialize_topography (D, G, param_file, max_depth)
This subroutine sets up the supercritical topography and land mask. We were not able to get the shock wave to behave this way and are now using an external file.
Function/Subroutine Documentation
supercritical_initialize_topography()
subroutine, public supercritical_initialization::supercritical_initialize_topography (real, dimension(g %isd: g %ied, g %jsd: g %jed), intent(out) D, type(dyn_horgrid_type), intent(in) G, type(param_file_type), intent(in) param_file, real, intent(in) max_depth)
This subroutine sets up the supercritical topography and land mask. We were not able to get the shock wave to behave this way and are now using an external file.
Parameters
[in] g The dynamic horizontal grid type
[out] d Ocean bottom depth in m
[in] param_file Parameter file structure
[in] max_depth Maximum depth of model in m
Definition at line 88 of file supercritical_initialization.F90.
References mom_error_handler::mom_mesg().
Referenced by mom_fixed_initialization::mom_initialize_topography().
   type(dyn_horgrid_type),           intent(in)  :: g !< The dynamic horizontal grid type
   real, dimension(SZI_(G),SZJ_(G)), intent(out) :: d !< Ocean bottom depth in m
   type(param_file_type),            intent(in)  :: param_file !< Parameter file structure
   real,                             intent(in)  :: max_depth  !< Maximum depth of model in m
   ! Local variables
   character(len=40)  :: mdl = "supercritical_initialize_topography" ! This subroutine's name.
   real :: min_depth ! The minimum and maximum depths in m.
   real :: pi ! 3.1415...
   real :: coast_offset, coast_angle
   integer :: i, j
   call mom_mesg("  supercritical_initialization.F90, supercritical_initialize_topography: setting topography", 5)
   call log_version(param_file, mdl, version, "")
   call get_param(param_file, mdl, "MINIMUM_DEPTH", min_depth, &
                  "The minimum depth of the ocean.", units="m", default=0.0)
   call get_param(param_file, mdl, "SUPERCRITICAL_COAST_OFFSET", coast_offset, &
                  "The distance along the southern boundary at which the coasts angles in.", &
                  units="km", default=10.0)
   call get_param(param_file, mdl, "SUPERCRITICAL_COAST_ANGLE", coast_angle, &
                  "The angle of the southern bondary beyond X=SUPERCRITICAL_COAST_OFFSET.", &
                  units="degrees", default=8.95)
   coast_angle = coast_angle * (atan(1.0)/45.) ! Convert to radians
   do j=g%jsc,g%jec ; do i=g%isc,g%iec
     d(i,j)=max_depth
     if ((g%geoLonT(i,j) > coast_offset).AND. &
         (atan2(g%geoLatT(i,j),g%geoLonT(i,j) - coast_offset) < coast_angle)) then
       d(i,j)=0.5*min_depth
     endif
     if (d(i,j) > max_depth) d(i,j) = max_depth
     if (d(i,j) < min_depth) d(i,j) = 0.5*min_depth
   enddo ; enddo
supercritical_set_obc_data()
subroutine, public supercritical_initialization::supercritical_set_obc_data (type(ocean_obc_type), pointer OBC, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file)
This subroutine sets the properties of flow at open boundary conditions.
Parameters
obc This open boundary condition type specifies whether, where, and what open boundary conditions are used.
[in] g The ocean's grid structure.
[in] param_file Parameter file structure
Definition at line 27 of file supercritical_initialization.F90.
References mom_error_handler::mom_error().
Referenced by mom_state_initialization::mom_initialize_state().
   type(ocean_obc_type),   pointer    :: obc  !< This open boundary condition type specifies
                                              !! whether, where, and what open boundary
                                              !! conditions are used.
   type(ocean_grid_type),  intent(in) :: g    !< The ocean's grid structure.
   type(param_file_type),  intent(in) :: param_file !< Parameter file structure
   ! Local variables
   character(len=40)  :: mdl = "supercritical_set_OBC_data" ! This subroutine's name.
   real :: zonal_flow
   integer :: i, j, k, l
   integer :: isd, ied, jsd, jed, isdb, iedb, jsdb, jedb
   type(obc_segment_type), pointer :: segment ! pointer to segment type list
   if (.not.associated(obc)) call mom_error(fatal, 'supercritical_initialization.F90: '// &
         'supercritical_set_OBC_data() was called but OBC type was not initialized!')
   call get_param(param_file, mdl, "SUPERCRITICAL_ZONAL_FLOW", zonal_flow, &
                  "Constant zonal flow imposed at upstream open boundary.", &
                  units="m/s", default=8.57)
   do l=1, obc%number_of_segments
     segment => obc%segment(l)
     if (.not. segment%on_pe) cycle
     if (segment%gradient) cycle
     if (segment%oblique .and. .not. segment%nudged .and. .not. segment%Flather) cycle
     if (segment%is_E_or_W) then
       jsd = segment%HI%jsd ; jed = segment%HI%jed
       isdb = segment%HI%IsdB ; iedb = segment%HI%IedB
       do k=1,g%ke
         do j=jsd,jed ; do i=isdb,iedb
           if (segment%specified .or. segment%nudged) then
             segment%normal_vel(i,j,k) = zonal_flow
           endif
           if (segment%specified) then
             segment%normal_trans(i,j,k) = zonal_flow * g%dyCu(i,j)
           endif
         enddo ; enddo
       enddo
       do j=jsd,jed ; do i=isdb,iedb
         segment%normal_vel_bt(i,j) = zonal_flow
       enddo ; enddo
     else
       isd = segment%HI%isd ; ied = segment%HI%ied
       jsdb = segment%HI%JsdB ; jedb = segment%HI%JedB
 !     do k=1,G%ke
 !       do J=JsdB,JedB ; do i=isd,ied
 !         segment%normal_vel(i,J,k) = 0.0
 !       enddo ; enddo
 !     enddo
       do j=jsdb,jedb ; do i=isd,ied
         segment%normal_vel_bt(i,j) = 0.0
       enddo ; enddo
     endif
   enddo