MOM6: mom_unit_tests Module Reference
mom_unit_tests Module Reference
Detailed Description
Invokes unit tests in all modules that have them.
Functions/Subroutines
subroutine unit_tests (verbosity)
Calls unit tests for other modules. Note that if a unit test returns true, a FATAL error is triggered.
Function/Subroutine Documentation
unit_tests()
subroutine mom_unit_tests::unit_tests (integer, intent(in) verbosity)
Calls unit tests for other modules. Note that if a unit test returns true, a FATAL error is triggered.
Parameters
[in] verbosity The verbosity level
Definition at line 16 of file MOM_unit_tests.F90.
References mom_diag_vkernels::diag_vkernels_unit_tests(), mom_error_handler::is_root_pe(), mom_error_handler::mom_error(), mom_neutral_diffusion::neutral_diffusion_unit_tests(), mom_remapping::remapping_unit_tests(), and mom_string_functions::string_functions_unit_tests().
Referenced by mom::initialize_mom().
   ! Arguments
   integer, intent(in) :: verbosity !< The verbosity level
   ! Local variables
   logical :: verbose
   verbose = verbosity>=5
   if (is_root_pe()) then ! The following need only be tested on 1 PE
     if (string_functions_unit_tests(verbose)) call mom_error(fatal, &
        "MOM_unit_tests: string_functions_unit_tests FAILED")
     if (remapping_unit_tests(verbose)) call mom_error(fatal, &
        "MOM_unit_tests: remapping_unit_tests FAILED")
     if (neutral_diffusion_unit_tests(verbose)) call mom_error(fatal, &
        "MOM_unit_tests: neutralDiffusionUnitTests FAILED")
     if (diag_vkernels_unit_tests(verbose)) call mom_error(fatal, &
        "MOM_unit_tests: diag_vkernels_unit_tests FAILED")
   endif