MOM6: mom_obsolete_diagnostics Module Reference
mom_obsolete_diagnostics Module Reference
Detailed Description
Provides a mechanism for recording diagnostic variables that are no longer valid, along with their replacement name if appropriate.
Functions/Subroutines
subroutine, public register_obsolete_diagnostics (param_file, diag)
Scan through the diag_table searching for obsolete parameters and issue informational messages and optionallly a FATAL error.
logical function found_in_diagtable (diag, varName, newVarName)
Fakes a register of a diagnostic to find out if an obsolete parameter appears in the diag_table.
Function/Subroutine Documentation
found_in_diagtable()
logical function mom_obsolete_diagnostics::found_in_diagtable (type(diag_ctrl), intent(in) diag, character(len=*), intent(in) varName, character(len=*), intent(in), optional newVarName) private
Fakes a register of a diagnostic to find out if an obsolete parameter appears in the diag_table.
Definition at line 67 of file MOM_obsolete_diagnostics.F90.
References mom_error_handler::is_root_pe(), and mom_error_handler::mom_error().
Referenced by register_obsolete_diagnostics().
   type(diag_ctrl),            intent(in) :: diag
   character(len=*),            intent(in) :: varname
   character(len=*), optional, intent(in) :: newvarname
   ! Local
   integer :: handle ! Integer handle returned from diag_manager
   ! We use register_static_field_fms() instead of register_static_field() so
   ! that the diagnostic does not appear in the available diagnostics list.
   handle = register_static_field_fms('ocean_model', varname, &
             diag%axesT1%handles, 'Obsolete parameter', 'N/A')
   found_in_diagtable = (handle>0)
   if (handle>0 .and. is_root_pe()) then
     if (present(newvarname)) then
       call mom_error(warning, 'MOM_obsolete_params: '//                        &
           'diag_table entry "'//trim(varname)//'" found. Use '// &
           '"'//trim(newvarname)//'" instead.' )
     else
       call mom_error(warning, 'MOM_obsolete_params: '//                        &
           'diag_table entry "'//trim(varname)//'" is obsolete.' )
     endif
   endif
register_obsolete_diagnostics()
subroutine, public mom_obsolete_diagnostics::register_obsolete_diagnostics (type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(in) diag)
Scan through the diag_table searching for obsolete parameters and issue informational messages and optionallly a FATAL error.
Parameters
[in] param_file The parameter file handle.
[in] diag A structure used to control diagnostics.
Definition at line 23 of file MOM_obsolete_diagnostics.F90.
References found_in_diagtable(), mom_error_handler::is_root_pe(), and mom_error_handler::mom_error().
Referenced by mom::initialize_mom().
   type(param_file_type),       intent(in)    :: param_file !< The parameter file handle.
   type(diag_ctrl),             intent(in)    :: diag       !< A structure used to control diagnostics.
 ! This include declares and sets the variable "version".
 #include "version_variable.h"
   ! Local variables
   character(len=40)  :: mdl = "MOM_obsolete_diagnostics"  !< This module's name.
   logical :: foundentry, causefatal
   integer :: errtype
   call log_version(param_file, mdl, version)
   call get_param(param_file, mdl, "OBSOLETE_DIAGNOSTIC_IS_FATAL", causefatal,              &
                  "If an obsolete diagnostic variable appears in the diag_table\n"//        &
                  "then cause a FATAL error rather than issue a WARNING.", default=.true.)
   foundentry = .false.
   ! Each obsolete entry, with replacement name is available.
   if (found_in_diagtable(diag, 'Net_Heat', 'net_heat_surface or net_heat_coupler')) foundentry = .true.
   if (found_in_diagtable(diag, 'PmE', 'PRCmE'))                                     foundentry = .true.
   if (found_in_diagtable(diag, 'froz_precip', 'fprec'))                             foundentry = .true.
   if (found_in_diagtable(diag, 'liq_precip', 'lprec'))                              foundentry = .true.
   if (found_in_diagtable(diag, 'virt_precip', 'vprec'))                             foundentry = .true.
   if (found_in_diagtable(diag, 'froz_runoff', 'frunoff'))                           foundentry = .true.
   if (found_in_diagtable(diag, 'liq_runoff', 'lrunoff'))                            foundentry = .true.
   if (found_in_diagtable(diag, 'calving_heat_content', 'heat_content_frunoff'))     foundentry = .true.
   if (found_in_diagtable(diag, 'precip_heat_content', 'heat_content_lprec'))        foundentry = .true.
   if (found_in_diagtable(diag, 'evap_heat_content', 'heat_content_massout'))        foundentry = .true.
   if (found_in_diagtable(diag, 'runoff_heat_content', 'heat_content_lrunoff'))      foundentry = .true.
   if (found_in_diagtable(diag, 'latent_fprec'))                                     foundentry = .true.
   if (found_in_diagtable(diag, 'latent_calve'))                                     foundentry = .true.
   if (found_in_diagtable(diag, 'heat_rest', 'heat_restore'))                        foundentry = .true.
   if (found_in_diagtable(diag, 'KPP_dTdt', 'KPP_NLT_dTdt'))                         foundentry = .true.
   if (found_in_diagtable(diag, 'KPP_dSdt', 'KPP_NLT_dSdt'))                         foundentry = .true.
   if (causefatal) then; errtype = fatal
   else ; errtype = warning ; endif
   if (foundentry .and. is_root_pe()) &
     call mom_error(errtype, 'MOM_obsolete_diagnostics: '//&
                             'Obsolete diagnostics found in diag_table')