MOM6: mom_cvmix_shear Module Reference
mom_cvmix_shear Module Reference
Detailed Description
Interface to CVMix interior shear schemes.
Data Types
type cvmix_shear_cs
Control structure including parameters for CVMix interior shear schemes.
Functions/Subroutines
subroutine, public calculate_cvmix_shear (u_H, v_H, h, tv, KH, KM, G, GV, CS)
Subroutine for calculating (internal) diffusivity.
logical function, public cvmix_shear_init (Time, G, GV, param_file, diag, CS)
Initialized the cvmix internal shear mixing routine.
logical function, public cvmix_shear_is_used (param_file)
Reads the parameters "LMD94" and "PP81" and returns state. This function allows other modules to know whether this parameterization will be used without needing to duplicate the log entry.
Variables
character(len=40) mdl = "MOM_CVMix_shear"
This module's name.
Function/Subroutine Documentation
calculate_cvmix_shear()
subroutine, public mom_cvmix_shear::calculate_cvmix_shear (real, dimension(szi_(g),szj_(g),szk_(g)), intent(in) u_H, real, dimension(szi_(g),szj_(g),szk_(g)), intent(in) v_H, real, dimension(szi_(g),szj_(g),szk_(g)), intent(in) h, type(thermo_var_ptrs), intent(in) tv, real, dimension(szi_(g),szj_(g),szk_(g)+1), intent(out) KH, real, dimension(szi_(g),szj_(g),szk_(g)+1), intent(out) KM, type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, type(cvmix_shear_cs), pointer CS)
Subroutine for calculating (internal) diffusivity.
Parameters
[in] g Grid structure.
[in] gv Vertical grid structure.
[in] u_h Initial zonal velocity on T points, in m s-1.
[in] v_h Initial meridional velocity on T points, in m s-1.
[in] h Layer thickness, in m or kg m-2.
[in] tv Thermodynamics structure.
[out] kh The vertical viscosity at each interface (not layer!) in m2 s-1.
[out] km The vertical viscosity at each interface (not layer!) in m2 s-1.
cs The control structure returned by a previous call to CVMix_shear_init.
Definition at line 48 of file MOM_cvmix_shear.F90.
Referenced by mom_set_diffusivity::set_diffusivity().
   type(ocean_grid_type),                      intent(in)  :: g !< Grid structure.
   type(verticalgrid_type),                    intent(in)  :: gv !< Vertical grid structure.
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)),   intent(in)  :: u_h !< Initial zonal velocity on T points, in m s-1.
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)),   intent(in)  :: v_h !< Initial meridional velocity on T points, in m s-1.
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)),   intent(in)  :: h !< Layer thickness, in m or kg m-2.
   type(thermo_var_ptrs),                      intent(in)  :: tv !< Thermodynamics structure.
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)+1), intent(out) :: kh !< The vertical viscosity at each interface
                                                                 !! (not layer!) in m2 s-1.
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)+1), intent(out) :: km !< The vertical viscosity at each interface
                                                                 !! (not layer!) in m2 s-1.
   type(cvmix_shear_cs),                       pointer     :: cs !< The control structure returned by a previous call to
                                                                 !! CVMix_shear_init.
   ! Local variables
   integer :: i, j, k, kk, km1
   real :: gorho
   real :: pref, du, dv, drho, dz, n2, s2
   real, dimension(2*(G%ke)) :: pres_1d, temp_1d, salt_1d, rho_1d
   real, dimension(G%ke+1) ::  ri_grad !< Gradient Richardson number
   ! some constants
   gorho = gv%g_Earth / gv%Rho0
   do j = g%jsc, g%jec
     do i = g%isc, g%iec
       ! skip calling for land points
       if (g%mask2dT(i,j)==0.) cycle
       ! Richardson number computed for each cell in a column.
       pref = 0.
       ri_grad(:)=1.e8 !Initialize w/ large Richardson value
       do k=1,g%ke
         ! pressure, temp, and saln for EOS
         ! kk+1 = k fields
         ! kk+2 = km1 fields
         km1  = max(1, k-1)
         kk   = 2*(k-1)
         pres_1d(kk+1) = pref
         pres_1d(kk+2) = pref
         temp_1d(kk+1) = tv%T(i,j,k)
         temp_1d(kk+2) = tv%T(i,j,km1)
         salt_1d(kk+1) = tv%S(i,j,k)
         salt_1d(kk+2) = tv%S(i,j,km1)
         ! pRef is pressure at interface between k and km1.
         ! iterate pRef for next pass through k-loop.
         pref = pref + gv%H_to_Pa * h(i,j,k)
       enddo ! k-loop finishes
       ! compute in-situ density
       call calculate_density(temp_1d, salt_1d, pres_1d, rho_1d, 1, 2*g%ke, tv%EQN_OF_STATE)
       ! N2 (can be negative) on interface
       do k = 1, g%ke
         km1 = max(1, k-1)
         kk = 2*(k-1)
         du = (u_h(i,j,k))-(u_h(i,j,km1))
         dv = (v_h(i,j,k))-(v_h(i,j,km1))
         drho = (gorho * (rho_1d(kk+1) - rho_1d(kk+2)) )
         dz = ((0.5*(h(i,j,km1) + h(i,j,k))+gv%H_subroundoff)*gv%H_to_m)
         n2 = drho/dz
         s2 = (du*du+dv*dv)/(dz*dz)
         ri_grad(k) = max(0.,n2)/max(s2,1.e-16)
       enddo
       ! Call to CVMix wrapper for computing interior mixing coefficients.
       call  cvmix_coeffs_shear(mdiff_out=km(i,j,:), &
                                    tdiff_out=kh(i,j,:), &
                                    rich=ri_grad, &
                                    nlev=g%ke,    &
                                    max_nlev=g%ke)
     enddo
   enddo
cvmix_shear_init()
logical function, public mom_cvmix_shear::cvmix_shear_init (type(time_type), intent(in) Time, type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(cvmix_shear_cs), pointer CS)
Initialized the cvmix internal shear mixing routine.
Note
*This is where we test to make sure multiple internal shear mixing routines (including JHL) are not enabled at the same time. (returns) cvmix_shear_init - True if module is to be used, False otherwise
Parameters
[in] time The current time.
[in] g Grid structure.
[in] gv Vertical grid structure.
[in] param_file Run-time parameter file handle
[in,out] diag Diagnostics control structure.
cs This module's control structure.
Definition at line 131 of file MOM_cvmix_shear.F90.
References mom_kappa_shear::kappa_shear_is_used(), mdl, and mom_error_handler::mom_error().
   type(time_type),         intent(in)    :: time !< The current time.
   type(ocean_grid_type),   intent(in)    :: g !< Grid structure.
   type(verticalgrid_type), intent(in)    :: gv !< Vertical grid structure.
   type(param_file_type),   intent(in)    :: param_file !< Run-time parameter file handle
   type(diag_ctrl), target, intent(inout) :: diag !< Diagnostics control structure.
   type(cvmix_shear_cs),    pointer       :: cs !< This module's control structure.
   ! Local variables
   integer :: numbertrue=0
   logical :: use_jhl
 ! This include declares and sets the variable "version".
 #include "version_variable.h"
   if (associated(cs)) then
     call mom_error(warning, "cvmix_shear_init called with an associated "// &
                             "control structure.")
     return
   endif
   allocate(cs)
 ! Set default, read and log parameters
   call log_version(param_file, mdl, version, &
     "Parameterization of shear-driven turbulence via CVMix (various options)")
   call get_param(param_file, mdl, "USE_LMD94", cs%use_LMD94, &
                  "If true, use the Large-McWilliams-Doney (JGR 1994) \n"//&
                  "shear mixing parameterization.", default=.false.)
   if (cs%use_LMD94) then
      numbertrue=numbertrue + 1
      cs%Mix_Scheme='KPP'
   endif
   call get_param(param_file, mdl, "USE_PP81", cs%use_PP81, &
                  "If true, use the Pacanowski and Philander (JPO 1981) \n"//&
                  "shear mixing parameterization.", default=.false.)
   if (cs%use_PP81) then
      numbertrue = numbertrue + 1
      cs%Mix_Scheme='PP'
   endif
   use_jhl=kappa_shear_is_used(param_file)
   if (use_jhl) numbertrue = numbertrue + 1
   ! After testing for interior schemes, make sure only 0 or 1 are enabled.
   ! Otherwise, warn user and kill job.
   if ((numbertrue).gt.1) then
      call mom_error(fatal, 'MOM_cvmix_shear_init: '// &
            'Multiple shear driven internal mixing schemes selected,'//&
            ' please disable all but one scheme to proceed.')
   endif
   cvmix_shear_init=(cs%use_PP81.or.cs%use_LMD94)
 ! Forego remainder of initialization if not using this scheme
   if (.not. cvmix_shear_init) return
   call get_param(param_file, mdl, "NU_ZERO", cs%Nu_Zero, &
                  "Leading coefficient in KPP shear mixing.", &
                  units="nondim", default=5.e-3)
   call get_param(param_file, mdl, "RI_ZERO", cs%Ri_Zero, &
                  "Critical Richardson for KPP shear mixing,"// &
                  " NOTE this the internal mixing and this is"// &
                  " not for setting the boundary layer depth." &
                  ,units="nondim", default=0.7)
   call get_param(param_file, mdl, "KPP_EXP", cs%KPP_exp, &
                  "Exponent of unitless factor of diffusivities,"// &
                  " for KPP internal shear mixing scheme." &
                  ,units="nondim", default=3.0)
   call cvmix_init_shear(mix_scheme=cs%mix_scheme, &
                         kpp_nu_zero=cs%Nu_Zero,   &
                         kpp_ri_zero=cs%Ri_zero,   &
                         kpp_exp=cs%KPP_exp)
   ! Allocation and initialization
   allocate( cs%N2( szi_(g), szj_(g), szk_(g)+1 ) );cs%N2(:,:,:) = 0.
   allocate( cs%S2( szi_(g), szj_(g), szk_(g)+1 ) );cs%S2(:,:,:) = 0.
cvmix_shear_is_used()
logical function, public mom_cvmix_shear::cvmix_shear_is_used (type(param_file_type), intent(in) param_file)
Reads the parameters "LMD94" and "PP81" and returns state. This function allows other modules to know whether this parameterization will be used without needing to duplicate the log entry.
Parameters
[in] param_file Run-time parameter files handle.
Definition at line 206 of file MOM_cvmix_shear.F90.
References mdl.
Referenced by mom_diabatic_driver::diabatic_driver_init(), and mom_set_visc::set_visc_register_restarts().
   type(param_file_type), intent(in) :: param_file !< Run-time parameter files handle.
   ! Local variables
   logical :: lmd94, pp81
   call get_param(param_file, mdl, "USE_LMD94", lmd94, &
        default=.false., do_not_log = .true.)
   call get_param(param_file, mdl, "Use_PP81", pp81, &
        default=.false., do_not_log = .true.)
   cvmix_shear_is_used = (lmd94 .or. pp81)
Variable Documentation
mdl
character(len=40) mom_cvmix_shear::mdl = "MOM_CVMix_shear"
This module's name.
Definition at line 41 of file MOM_cvmix_shear.F90.
Referenced by cvmix_shear_init(), and cvmix_shear_is_used().
 character(len=40)  :: mdl = "MOM_CVMix_shear"  !< This module's name.