MOM6: mom_neutral_diffusion Module Reference
mom_neutral_diffusion Module Reference
Detailed Description
A column-wise toolbox for implementing neutral diffusion.
Data Types
type neutral_diffusion_cs
Functions/Subroutines
logical function, public neutral_diffusion_init (Time, G, param_file, diag, CS)
Read parameters and allocate control structure for neutral_diffusion module.
subroutine, public neutral_diffusion_diag_init (Time, G, diag, C_p, Reg, CS)
Diagnostic handles for neutral diffusion tendencies.
subroutine, public neutral_diffusion_calc_coeffs (G, GV, h, T, S, EOS, CS)
Calculate remapping factors for u/v columns used to map adjoining columns to a shared coordinate space.
subroutine, public neutral_diffusion (G, GV, h, Coef_x, Coef_y, Tracer, m, dt, name, CS)
Update tracer concentration due to neutral diffusion; layer thickness unchanged by this update.
subroutine interface_scalar (nk, h, S, Si, i_method)
Returns interface scalar, Si, for a column of layer values, S.
real function ppm_edge (hkm1, hk, hkp1, hkp2, Ak, Akp1, Pk, Pkp1)
Returns the PPM quasi-fourth order edge value at k+1/2 following equation 1.6 in Colella & Woodward, 1984: JCP 54, 174-201.
real function ppm_ave (xL, xR, aL, aR, aMean)
Returns the average of a PPM reconstruction between two fractional positions.
real function signum (a, x)
A true signum function that returns either -abs(a), when x<0; or abs(a) when x>0; or 0 when x=0.
subroutine plm_diff (nk, h, S, c_method, b_method, diff)
Returns PLM slopes for a column where the slopes are the difference in value across each cell. The limiting follows equation 1.8 in Colella & Woodward, 1984: JCP 54, 174-201.
real function fv_diff (hkm1, hk, hkp1, Skm1, Sk, Skp1)
Returns the cell-centered second-order finite volume (unlimited PLM) slope using three consecutive cell widths and average values. Slope is returned as a difference across the central cell (i.e. units of scalar S). Discretization follows equation 1.7 in Colella & Woodward, 1984: JCP 54, 174-201.
real function fvlsq_slope (hkm1, hk, hkp1, Skm1, Sk, Skp1)
Returns the cell-centered second-order weighted least squares slope using three consecutive cell widths and average values. Slope is returned as a gradient (i.e. units of scalar S over width units).
subroutine find_neutral_surface_positions (nk, Pl, Tl, Sl, dRdTl, dRdSl, Pr, Tr, Sr, dRdTr, dRdSr, PoL, PoR, KoL, KoR, hEff)
Returns positions within left/right columns of combined interfaces.
real function absolute_position (n, Pint, Karr, NParr, k_surface)
Converts non-dimensional position within a layer to absolute position (for debugging)
real function, dimension(2 *n+2) absolute_positions (n, Pint, Karr, NParr)
Converts non-dimensional positions within layers to absolute positions (for debugging)
real function interpolate_for_nondim_position (dRhoNeg, Pneg, dRhoPos, Ppos)
Returns the non-dimensional position between Pneg and Ppos where the interpolated density difference equals zero. The result is always bounded to be between 0 and 1.
subroutine neutral_surface_flux (nk, hl, hr, Tl, Tr, PiL, PiR, KoL, KoR, hEff, Flx)
Returns a single column of neutral diffusion fluxes of a tracer.
logical function, public neutral_diffusion_unit_tests (verbose)
Returns true if unit tests of neutral_diffusion functions fail. Otherwise returns false.
logical function test_fv_diff (verbose, hkm1, hk, hkp1, Skm1, Sk, Skp1, Ptrue, title)
Returns true if a test of fv_diff() fails, and conditionally writes results to stream.
logical function test_fvlsq_slope (verbose, hkm1, hk, hkp1, Skm1, Sk, Skp1, Ptrue, title)
Returns true if a test of fvlsq_slope() fails, and conditionally writes results to stream.
logical function test_ifndp (verbose, rhoNeg, Pneg, rhoPos, Ppos, Ptrue, title)
Returns true if a test of interpolate_for_nondim_position() fails, and conditionally writes results to stream.
logical function test_data1d (verbose, nk, Po, Ptrue, title)
Returns true if comparison of Po and Ptrue fails, and conditionally writes results to stream.
logical function test_data1di (verbose, nk, Po, Ptrue, title)
Returns true if comparison of Po and Ptrue fails, and conditionally writes results to stream.
logical function test_nsp (verbose, nk, KoL, KoR, pL, pR, hEff, KoL0, KoR0, pL0, pR0, hEff0, title)
Returns true if output of find_neutral_surface_positions() does not match correct values, and conditionally writes results to stream.
logical function compare_nsp_row (KoL, KoR, pL, pR, KoL0, KoR0, pL0, pR0)
Compares a single row, k, of output from find_neutral_surface_positions()
subroutine, public neutral_diffusion_end (CS)
Deallocates neutral_diffusion control structure.
Variables
character(len=40) mdl = "MOM_neutral_diffusion"
logical, parameter debug_this_module = .false.
Function/Subroutine Documentation
absolute_position()
real function mom_neutral_diffusion::absolute_position (integer, intent(in) n, real, dimension(n+1), intent(in) Pint, integer, dimension(2*n+2), intent(in) Karr, real, dimension(2*n+2), intent(in) NParr, integer k_surface) private
Converts non-dimensional position within a layer to absolute position (for debugging)
Parameters
[in] n Number of levels
[in] pint Position of interfaces (Pa)
[in] karr Index of interface above position
[in] nparr Non-dimensional position within layer Karr(:)
Definition at line 892 of file MOM_neutral_diffusion.F90.
Referenced by absolute_positions(), and find_neutral_surface_positions().
   integer, intent(in) :: n            !< Number of levels
   real,    intent(in) :: pint(n+1)    !< Position of interfaces (Pa)
   integer, intent(in) :: karr(2*n+2)  !< Index of interface above position
   real,    intent(in) :: nparr(2*n+2) !< Non-dimensional position within layer Karr(:)
   ! Local variables
   integer :: k_surface, k
   k = karr(k_surface)
   if (k>n) stop 'absolute_position: k>nk is out of bounds!'
   absolute_position = pint(k) + nparr(k_surface) * ( pint(k+1) - pint(k) )
absolute_positions()
real function, dimension(2*n+2) mom_neutral_diffusion::absolute_positions (integer, intent(in) n, real, dimension(n+1), intent(in) Pint, integer, dimension(2*n+2), intent(in) Karr, real, dimension(2*n+2), intent(in) NParr) private
Converts non-dimensional positions within layers to absolute positions (for debugging)
Parameters
[in] n Number of levels
[in] pint Position of interface (Pa)
[in] karr Indexes of interfaces about positions
[in] nparr Non-dimensional positions within layers Karr(:)
Definition at line 908 of file MOM_neutral_diffusion.F90.
References absolute_position().
Referenced by neutral_diffusion_unit_tests().
   integer, intent(in) :: n            !< Number of levels
   real,    intent(in) :: pint(n+1)    !< Position of interface (Pa)
   integer, intent(in) :: karr(2*n+2)  !< Indexes of interfaces about positions
   real,    intent(in) :: nparr(2*n+2) !< Non-dimensional positions within layers Karr(:)
   real,  dimension(2*n+2) :: absolute_positions ! Absolute positions (Pa)
   ! Local variables
   integer :: k_surface, k
   do k_surface = 1, 2*n+2
     absolute_positions(k_surface) = absolute_position(n,pint,karr,nparr,k_surface)
   enddo
compare_nsp_row()
logical function mom_neutral_diffusion::compare_nsp_row (integer, intent(in) KoL, integer, intent(in) KoR, real, intent(in) pL, real, intent(in) pR, integer, intent(in) KoL0, integer, intent(in) KoR0, real, intent(in) pL0, real, intent(in) pR0) private
Compares a single row, k, of output from find_neutral_surface_positions()
Parameters
[in] kol Index of first left interface above neutral surface
[in] kor Index of first right interface above neutral surface
[in] pl Fractional position of neutral surface within layer KoL of left column
[in] pr Fractional position of neutral surface within layer KoR of right column
[in] kol0 Correct value for KoL
[in] kor0 Correct value for KoR
[in] pl0 Correct value for pL
[in] pr0 Correct value for pR
Definition at line 1495 of file MOM_neutral_diffusion.F90.
Referenced by test_nsp().
   integer,  intent(in) :: kol   !< Index of first left interface above neutral surface
   integer,  intent(in) :: kor   !< Index of first right interface above neutral surface
   real,     intent(in) :: pl    !< Fractional position of neutral surface within layer KoL of left column
   real,     intent(in) :: pr    !< Fractional position of neutral surface within layer KoR of right column
   integer,  intent(in) :: kol0  !< Correct value for KoL
   integer,  intent(in) :: kor0  !< Correct value for KoR
   real,     intent(in) :: pl0   !< Correct value for pL
   real,     intent(in) :: pr0   !< Correct value for pR
   compare_nsp_row = .false.
   if (kol /= kol0) compare_nsp_row = .true.
   if (kor /= kor0) compare_nsp_row = .true.
   if (pl /= pl0) compare_nsp_row = .true.
   if (pr /= pr0) compare_nsp_row = .true.
find_neutral_surface_positions()
subroutine mom_neutral_diffusion::find_neutral_surface_positions (integer, intent(in) nk, real, dimension(nk+1), intent(in) Pl, real, dimension(nk+1), intent(in) Tl, real, dimension(nk+1), intent(in) Sl, real, dimension(nk+1), intent(in) dRdTl, real, dimension(nk+1), intent(in) dRdSl, real, dimension(nk+1), intent(in) Pr, real, dimension(nk+1), intent(in) Tr, real, dimension(nk+1), intent(in) Sr, real, dimension(nk+1), intent(in) dRdTr, real, dimension(nk+1), intent(in) dRdSr, real, dimension(2*nk+2), intent(inout) PoL, real, dimension(2*nk+2), intent(inout) PoR, integer, dimension(2*nk+2), intent(inout) KoL, integer, dimension(2*nk+2), intent(inout) KoR, real, dimension(2*nk+1), intent(inout) hEff) private
Returns positions within left/right columns of combined interfaces.
Parameters
[in] nk Number of levels
[in] pl Left-column interface pressure (Pa)
[in] tl Left-column interface potential temperature (degC)
[in] sl Left-column interface salinity (ppt)
[in] drdtl Left-column dRho/dT (kg/m3/degC)
[in] drdsl Left-column dRho/dS (kg/m3/ppt)
[in] pr Right-column interface pressure (Pa)
[in] tr Right-column interface potential temperature (degC)
[in] sr Right-column interface salinity (ppt)
[in] drdtr Left-column dRho/dT (kg/m3/degC)
[in] drdsr Left-column dRho/dS (kg/m3/ppt)
[in,out] pol Fractional position of neutral surface within layer KoL of left column
[in,out] por Fractional position of neutral surface within layer KoR of right column
[in,out] kol Index of first left interface above neutral surface
[in,out] kor Index of first right interface above neutral surface
[in,out] heff Effective thickness between two neutral surfaces (Pa)
Definition at line 716 of file MOM_neutral_diffusion.F90.
References absolute_position(), and interpolate_for_nondim_position().
Referenced by neutral_diffusion_calc_coeffs(), and neutral_diffusion_unit_tests().
   integer,                    intent(in)    :: nk    !< Number of levels
   real, dimension(nk+1),      intent(in)    :: pl    !< Left-column interface pressure (Pa)
   real, dimension(nk+1),      intent(in)    :: tl    !< Left-column interface potential temperature (degC)
   real, dimension(nk+1),      intent(in)    :: sl    !< Left-column interface salinity (ppt)
   real, dimension(nk+1),      intent(in)    :: drdtl !< Left-column dRho/dT (kg/m3/degC)
   real, dimension(nk+1),      intent(in)    :: drdsl !< Left-column dRho/dS (kg/m3/ppt)
   real, dimension(nk+1),      intent(in)    :: pr    !< Right-column interface pressure (Pa)
   real, dimension(nk+1),      intent(in)    :: tr    !< Right-column interface potential temperature (degC)
   real, dimension(nk+1),      intent(in)    :: sr    !< Right-column interface salinity (ppt)
   real, dimension(nk+1),      intent(in)    :: drdtr !< Left-column dRho/dT (kg/m3/degC)
   real, dimension(nk+1),      intent(in)    :: drdsr !< Left-column dRho/dS (kg/m3/ppt)
   real, dimension(2*nk+2),    intent(inout) :: pol   !< Fractional position of neutral surface within layer KoL of left column
   real, dimension(2*nk+2),    intent(inout) :: por   !< Fractional position of neutral surface within layer KoR of right column
   integer, dimension(2*nk+2), intent(inout) :: kol   !< Index of first left interface above neutral surface
   integer, dimension(2*nk+2), intent(inout) :: kor   !< Index of first right interface above neutral surface
   real, dimension(2*nk+1),    intent(inout) :: heff  !< Effective thickness between two neutral surfaces (Pa)
   ! Local variables
   integer :: k_surface              ! Index of neutral surface
   integer :: kl                     ! Index of left interface
   integer :: kr                     ! Index of right interface
   real    :: drdt, drds             ! dRho/dT and dRho/dS for the neutral surface
   logical :: searching_left_column  ! True if searching for the position of a right interface in the left column
   logical :: searching_right_column ! True if searching for the position of a left interface in the right column
   logical :: reached_bottom         ! True if one of the bottom-most interfaces has been used as the target
   integer :: krm1, klm1
   real    :: drho, drhotop, drhobot, hl, hr
   integer :: lastk_left, lastk_right
   real    :: lastp_left, lastp_right
   ! Initialize variables for the search
   kr = 1 ; lastk_right = 1 ; lastp_right = 0.
   kl = 1 ; lastk_left = 1 ; lastp_left = 0.
   reached_bottom = .false.
   ! Loop over each neutral surface, working from top to bottom
   neutral_surfaces: do k_surface = 1, 2*nk+2
     klm1 = max(kl-1, 1)
     if (klm1>nk) stop 'find_neutral_surface_positions(): klm1 went out of bounds!'
     krm1 = max(kr-1, 1)
     if (krm1>nk) stop 'find_neutral_surface_positions(): krm1 went out of bounds!'
     ! Potential density difference, rho(kr) - rho(kl)
     drho = 0.5 * ( ( drdtr(kr) + drdtl(kl) ) * ( tr(kr) - tl(kl) ) &
                  + ( drdsr(kr) + drdsl(kl) ) * ( sr(kr) - sl(kl) ) )
     ! Which column has the lighter surface for the current indexes, kr and kl
     if (.not. reached_bottom) then
       if (drho < 0.) then
         searching_left_column = .true.
         searching_right_column = .false.
       elseif (drho > 0.) then
         searching_right_column = .true.
         searching_left_column = .false.
       else ! dRho == 0.
         if (kl + kr == 2) then ! Still at surface
           searching_left_column = .true.
           searching_right_column = .false.
         else ! Not the surface so we simply change direction
           searching_left_column = .not.  searching_left_column
           searching_right_column = .not.  searching_right_column
         endif
       endif
     endif
     if (searching_left_column) then
       ! Interpolate for the neutral surface position within the left column, layer klm1
       ! Potential density difference, rho(kl-1) - rho(kr) (should be negative)
       drhotop = 0.5 * ( ( drdtl(klm1) + drdtr(kr) ) * ( tl(klm1) - tr(kr) ) &
                      + ( drdsl(klm1) + drdsr(kr) ) * ( sl(klm1) - sr(kr) ) )
       ! Potential density difference, rho(kl) - rho(kr) (will be positive)
       drhobot = 0.5 * ( ( drdtl(klm1+1) + drdtr(kr) ) * ( tl(klm1+1) - tr(kr) ) &
                    + ( drdsl(klm1+1) + drdsr(kr) ) * ( sl(klm1+1) - sr(kr) ) )
       ! Because we are looking left, the right surface, kr, is lighter than klm1+1 and should be denser than klm1
       ! unless we are still at the top of the left column (kl=1)
       if (drhotop > 0. .or. kr+kl==2) then
         pol(k_surface) = 0. ! The right surface is lighter than anything in layer klm1
       elseif (drhotop >= drhobot) then ! Left layer is unstratified
         pol(k_surface) = 1.
       else
         ! Linearly interpolate for the position between Pl(kl-1) and Pl(kl) where the density difference
         ! between right and left is zero.
         pol(k_surface) = interpolate_for_nondim_position( drhotop, pl(klm1), drhobot, pl(klm1+1) )
       endif
       if (pol(k_surface)>=1. .and. klm1<nk) then ! >= is really ==, when PoL==1 we point to the bottom of the cell
         klm1 = klm1 + 1
         pol(k_surface) = pol(k_surface) - 1.
       endif
       if (real(klm1-lastk_left)+(pol(k_surface)-lastp_left)<0.) then
         pol(k_surface) = lastp_left
         klm1 = lastk_left
       endif
       kol(k_surface) = klm1
       if (kr <= nk) then
         por(k_surface) = 0.
         kor(k_surface) = kr
       else
         por(k_surface) = 1.
         kor(k_surface) = nk
       endif
       if (kr <= nk) then
         kr = kr + 1
       else
         reached_bottom = .true.
         searching_right_column = .true.
         searching_left_column = .false.
       endif
     elseif (searching_right_column) then
       ! Interpolate for the neutral surface position within the right column, layer krm1
       ! Potential density difference, rho(kr-1) - rho(kl) (should be negative)
       drhotop = 0.5 * ( ( drdtr(krm1) + drdtl(kl) ) * ( tr(krm1) - tl(kl) ) &
                      + ( drdsr(krm1) + drdsl(kl) ) * ( sr(krm1) - sl(kl) ) )
       ! Potential density difference, rho(kr) - rho(kl) (will be positive)
       drhobot = 0.5 * ( ( drdtr(krm1+1) + drdtl(kl) ) * ( tr(krm1+1) - tl(kl) ) &
                    + ( drdsr(krm1+1) + drdsl(kl) ) * ( sr(krm1+1) - sl(kl) ) )
       ! Because we are looking right, the left surface, kl, is lighter than krm1+1 and should be denser than krm1
       ! unless we are still at the top of the right column (kr=1)
       if (drhotop >= 0. .or. kr+kl==2) then
         por(k_surface) = 0. ! The left surface is lighter than anything in layer krm1
       elseif (drhotop >= drhobot) then ! Right layer is unstratified
         por(k_surface) = 1.
       else
         ! Linearly interpolate for the position between Pr(kr-1) and Pr(kr) where the density difference
         ! between right and left is zero.
         por(k_surface) = interpolate_for_nondim_position( drhotop, pr(krm1), drhobot, pr(krm1+1) )
       endif
       if (por(k_surface)>=1. .and. krm1<nk) then ! >= is really ==, when PoR==1 we point to the bottom of the cell
         krm1 = krm1 + 1
         por(k_surface) = por(k_surface) - 1.
       endif
       if (real(krm1-lastk_right)+(por(k_surface)-lastp_right)<0.) then
         por(k_surface) = lastp_right
         krm1 = lastk_right
       endif
       kor(k_surface) = krm1
       if (kl <= nk) then
         pol(k_surface) = 0.
         kol(k_surface) = kl
       else
         pol(k_surface) = 1.
         kol(k_surface) = nk
       endif
       if (kl <= nk) then
         kl = kl + 1
       else
         reached_bottom = .true.
         searching_right_column = .false.
         searching_left_column = .true.
       endif
     else
       stop 'Else what?'
     endif
     lastk_left = kol(k_surface) ; lastp_left = pol(k_surface)
     lastk_right = kor(k_surface) ; lastp_right = por(k_surface)
     ! Effective thickness
     ! NOTE: This would be better expressed in terms of the layers thicknesses rather
     ! than as differences of position - AJA
     if (k_surface>1) then
       hl = absolute_position(nk,pl,kol,pol,k_surface) - absolute_position(nk,pl,kol,pol,k_surface-1)
       hr = absolute_position(nk,pr,kor,por,k_surface) - absolute_position(nk,pr,kor,por,k_surface-1)
       if ( hl + hr > 0.) then
         heff(k_surface-1) = 2. * hl * hr / ( hl + hr )
       else
         heff(k_surface-1) = 0.
       endif
     endif
   enddo neutral_surfaces
fv_diff()
real function mom_neutral_diffusion::fv_diff (real, intent(in) hkm1, real, intent(in) hk, real, intent(in) hkp1, real, intent(in) Skm1, real, intent(in) Sk, real, intent(in) Skp1) private
Returns the cell-centered second-order finite volume (unlimited PLM) slope using three consecutive cell widths and average values. Slope is returned as a difference across the central cell (i.e. units of scalar S). Discretization follows equation 1.7 in Colella & Woodward, 1984: JCP 54, 174-201.
Parameters
[in] hkm1 Left cell width
[in] hk Center cell width
[in] hkp1 Right cell width
[in] skm1 Left cell average value
[in] sk Center cell average value
[in] skp1 Right cell average value
Definition at line 660 of file MOM_neutral_diffusion.F90.
Referenced by plm_diff(), and test_fv_diff().
   real, intent(in) :: hkm1 !< Left cell width
   real, intent(in) :: hk   !< Center cell width
   real, intent(in) :: hkp1 !< Right cell width
   real, intent(in) :: skm1 !< Left cell average value
   real, intent(in) :: sk   !< Center cell average value
   real, intent(in) :: skp1 !< Right cell average value
   ! Local variables
   real :: h_sum, hp, hm
   h_sum = ( hkm1 + hkp1 ) + hk
   if (h_sum /= 0.) h_sum = 1./ h_sum
   hm =  hkm1 + hk
   if (hm /= 0.) hm = 1./ hm
   hp =  hkp1 + hk
   if (hp /= 0.) hp = 1./ hp
   fv_diff = ( hk * h_sum ) * &
             (   ( 2. * hkm1 + hk ) * hp * ( skp1 - sk ) &
               + ( 2. * hkp1 + hk ) * hm * ( sk - skm1 ) )
fvlsq_slope()
real function mom_neutral_diffusion::fvlsq_slope (real, intent(in) hkm1, real, intent(in) hk, real, intent(in) hkp1, real, intent(in) Skm1, real, intent(in) Sk, real, intent(in) Skp1) private
Returns the cell-centered second-order weighted least squares slope using three consecutive cell widths and average values. Slope is returned as a gradient (i.e. units of scalar S over width units).
Parameters
[in] hkm1 Left cell width
[in] hk Center cell width
[in] hkp1 Right cell width
[in] skm1 Left cell average value
[in] sk Center cell average value
[in] skp1 Right cell average value
Definition at line 686 of file MOM_neutral_diffusion.F90.
Referenced by plm_diff(), and test_fvlsq_slope().
   real, intent(in) :: hkm1 !< Left cell width
   real, intent(in) :: hk   !< Center cell width
   real, intent(in) :: hkp1 !< Right cell width
   real, intent(in) :: skm1 !< Left cell average value
   real, intent(in) :: sk   !< Center cell average value
   real, intent(in) :: skp1 !< Right cell average value
   ! Local variables
   real :: xkm1, xkp1
   real :: h_sum, hx_sum, hxsq_sum, hxy_sum, hy_sum, det
   xkm1 = -0.5 * ( hk + hkm1 )
   xkp1 = 0.5 * ( hk + hkp1 )
   h_sum = ( hkm1 + hkp1 ) + hk
   hx_sum = hkm1*xkm1 + hkp1*xkp1
   hxsq_sum = hkm1*(xkm1**2) + hkp1*(xkp1**2)
   hxy_sum = hkm1*xkm1*skm1 + hkp1*xkp1*skp1
   hy_sum = ( hkm1*skm1 + hkp1*skp1 ) + hk*sk
   det = h_sum * hxsq_sum - hx_sum**2
   if (det /= 0.) then
     !a = ( hxsq_sum * hy_sum - hx_sum*hxy_sum ) / det ! a would be mean of straight line fit
     fvlsq_slope = ( h_sum * hxy_sum - hx_sum*hy_sum ) / det ! Gradient of straight line fit
   else
     fvlsq_slope = 0. ! Adcroft's reciprocal rule
   endif
interface_scalar()
subroutine mom_neutral_diffusion::interface_scalar (integer, intent(in) nk, real, dimension(nk), intent(in) h, real, dimension(nk), intent(in) S, real, dimension(nk+1), intent(inout) Si, integer, intent(in) i_method) private
Returns interface scalar, Si, for a column of layer values, S.
Parameters
[in] nk Number of levels
[in] h Layer thickness (H units)
[in] s Layer scalar (conc, e.g. ppt)
[in,out] si Interface scalar (conc, e.g. ppt)
[in] i_method =1 use average of PLM edges =2 use continuous PPM edge interpolation
Definition at line 477 of file MOM_neutral_diffusion.F90.
References plm_diff(), and ppm_edge().
Referenced by neutral_diffusion_calc_coeffs(), neutral_diffusion_unit_tests(), and neutral_surface_flux().
   integer,               intent(in)    :: nk       !< Number of levels
   real, dimension(nk),   intent(in)    :: h        !< Layer thickness (H units)
   real, dimension(nk),   intent(in)    :: s        !< Layer scalar (conc, e.g. ppt)
   real, dimension(nk+1), intent(inout) :: si       !< Interface scalar (conc, e.g. ppt)
   integer,               intent(in)    :: i_method !< =1 use average of PLM edges
                                                    !! =2 use continuous PPM edge interpolation
   ! Local variables
   integer :: k, km2, kp1
   real, dimension(nk) :: diff
   real :: sb, sa
   call plm_diff(nk, h, s, 2, 1, diff)
   si(1) = s(1) - 0.5 * diff(1)
   if (i_method==1) then
     do k = 2, nk
       ! Average of the two edge values (will be bounded and,
       ! when slopes are unlimited, notionally second-order accurate)
       sa = s(k-1) + 0.5 * diff(k-1) ! Lower edge value of a PLM reconstruction for layer above
       sb = s(k) - 0.5 * diff(k) ! Upper edge value of a PLM reconstruction for layer below
       si(k) = 0.5 * ( sa + sb )
     enddo
   elseif (i_method==2) then
     do k = 2, nk
       ! PPM quasi-fourth order interpolation for edge values following
       ! equation 1.6 in Colella & Woodward, 1984: JCP 54, 174-201.
       km2 = max(1, k-2)
       kp1 = min(nk, k+1)
       si(k) = ppm_edge(h(km2), h(k-1), h(k), h(kp1),  s(k-1), s(k), diff(k-1), diff(k))
     enddo
   endif
   si(nk+1) = s(nk) + 0.5 * diff(nk)
interpolate_for_nondim_position()
real function mom_neutral_diffusion::interpolate_for_nondim_position (real, intent(in) dRhoNeg, real, intent(in) Pneg, real, intent(in) dRhoPos, real, intent(in) Ppos) private
Returns the non-dimensional position between Pneg and Ppos where the interpolated density difference equals zero. The result is always bounded to be between 0 and 1.
Parameters
[in] drhoneg Negative density difference
[in] pneg Position of negative density difference
[in] drhopos Positive density difference
[in] ppos Position of positive density difference
Definition at line 928 of file MOM_neutral_diffusion.F90.
Referenced by find_neutral_surface_positions(), and test_ifndp().
   real, intent(in) :: drhoneg !< Negative density difference
   real, intent(in) :: pneg    !< Position of negative density difference
   real, intent(in) :: drhopos !< Positive density difference
   real, intent(in) :: ppos    !< Position of positive density difference
   if (ppos<pneg) stop 'interpolate_for_nondim_position: Houston, we have a problem! Ppos<Pneg'
   if (drhoneg>drhopos) write(0,*) 'dRhoNeg, Pneg, dRhoPos, Ppos=',drhoneg, pneg, drhopos, ppos
   if (drhoneg>drhopos) stop 'interpolate_for_nondim_position: Houston, we have a problem! dRhoNeg>dRhoPos'
   if (ppos<=pneg) then ! Handle vanished or inverted layers
     interpolate_for_nondim_position = 0.5
   elseif ( drhopos - drhoneg > 0. ) then
     interpolate_for_nondim_position = min( 1., max( 0., -drhoneg / ( drhopos - drhoneg ) ) )
   elseif ( drhopos - drhoneg == 0) then
     if (drhoneg>0.) then
       interpolate_for_nondim_position = 0.
     elseif (drhoneg<0.) then
       interpolate_for_nondim_position = 1.
     else ! dRhoPos = dRhoNeg = 0
       interpolate_for_nondim_position = 0.5
     endif
   else ! dRhoPos - dRhoNeg < 0
     interpolate_for_nondim_position = 0.5
   endif
   if ( interpolate_for_nondim_position < 0. ) stop 'interpolate_for_nondim_position: Houston, we have a problem! Pint < Pneg'
   if ( interpolate_for_nondim_position > 1. ) stop 'interpolate_for_nondim_position: Houston, we have a problem! Pint > Ppos'
neutral_diffusion()
subroutine, public mom_neutral_diffusion::neutral_diffusion (type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, real, dimension(g %isd: g %ied, g %jsd: g %jed, g %ke), intent(in) h, real, dimension(g %isdb: g %iedb, g %jsd: g %jed), intent(in) Coef_x, real, dimension(g %isd: g %ied, g %jsdb: g %jedb), intent(in) Coef_y, real, dimension(g %isd: g %ied, g %jsd: g %jed, g %ke), intent(inout) Tracer, integer, intent(in) m, real, intent(in) dt, character(len=32), intent(in) name, type(neutral_diffusion_cs), pointer CS)
Update tracer concentration due to neutral diffusion; layer thickness unchanged by this update.
Parameters
[in] g Ocean grid structure
[in] gv ocean vertical grid structure
[in] h Layer thickness (H units)
[in] coef_x dt * Kh * dy / dx at u-points (m^2)
[in] coef_y dt * Kh * dx / dy at u-points (m^2)
[in,out] tracer Tracer concentration
[in] m Tracer number
[in] dt Tracer time step * I_numitts (I_numitts in tracer_hordiff)
[in] name Tracer name
cs Neutral diffusion control structure
Definition at line 316 of file MOM_neutral_diffusion.F90.
References neutral_surface_flux().
Referenced by mom_tracer_hor_diff::tracer_hordiff().
   type(ocean_grid_type),                     intent(in)    :: g      !< Ocean grid structure
   type(verticalgrid_type),                   intent(in)    :: gv     !< ocean vertical grid structure
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)),  intent(in)    :: h      !< Layer thickness (H units)
   real, dimension(SZIB_(G),SZJ_(G)),         intent(in)    :: coef_x !< dt * Kh * dy / dx at u-points (m^2)
   real, dimension(SZI_(G),SZJB_(G)),         intent(in)    :: coef_y !< dt * Kh * dx / dy at u-points (m^2)
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)),  intent(inout) :: tracer !< Tracer concentration
   integer,                                   intent(in)    :: m      !< Tracer number
   real,                                      intent(in)    :: dt     !< Tracer time step * I_numitts (I_numitts in tracer_hordiff)
   character(len=32),                         intent(in)    :: name   !< Tracer name
   type(neutral_diffusion_cs),                pointer       :: cs     !< Neutral diffusion control structure
   ! Local variables
   real, dimension(SZIB_(G),SZJ_(G),2*G%ke+1) :: uflx        ! Zonal flux of tracer      (concentration * H)
   real, dimension(SZI_(G),SZJB_(G),2*G%ke+1) :: vflx        ! Meridional flux of tracer (concentration * H)
   real, dimension(SZI_(G),SZJ_(G),G%ke)      :: tendency    ! tendency array for diagn
   real, dimension(SZI_(G),SZJ_(G))           :: tendency_2d ! depth integrated content tendency for diagn
   real, dimension(SZIB_(G),SZJ_(G))          :: trans_x_2d  ! depth integrated diffusive tracer x-transport diagn
   real, dimension(SZI_(G),SZJB_(G))          :: trans_y_2d  ! depth integrated diffusive tracer y-transport diagn
   real, dimension(G%ke)                      :: dtracer     ! change in tracer concentration due to ndiffusion
   integer :: i, j, k, ks, nk
   real :: ppt2mks, idt, convert
   nk = gv%ke
   ! for diagnostics
   if(cs%id_neutral_diff_tracer_conc_tend(m)    > 0  .or.  &
      cs%id_neutral_diff_tracer_cont_tend(m)    > 0  .or.  &
      cs%id_neutral_diff_tracer_cont_tend_2d(m) > 0  .or.  &
      cs%id_neutral_diff_tracer_trans_x_2d(m)   > 0  .or.  &
      cs%id_neutral_diff_tracer_trans_y_2d(m)   > 0) then
      ppt2mks          = 0.001
      idt              = 1.0/dt
      tendency(:,:,:)  = 0.0
      tendency_2d(:,:) = 0.0
      trans_x_2d(:,:)  = 0.0
      trans_y_2d(:,:)  = 0.0
      convert          = 1.0
      if(trim(name) == 'T') convert = cs%C_p  * gv%H_to_kg_m2
      if(trim(name) == 'S') convert = ppt2mks * gv%H_to_kg_m2
   endif
   ! x-flux
   do j = g%jsc,g%jec ; do i = g%isc-1,g%iec
     if (g%mask2dCu(i,j)>0.) then
       call neutral_surface_flux(nk, h(i,j,:), h(i+1,j,:),       &
                                 tracer(i,j,:), tracer(i+1,j,:), &
                                 cs%uPoL(i,j,:), cs%uPoR(i,j,:), &
                                 cs%uKoL(i,j,:), cs%uKoR(i,j,:), &
                                 cs%uhEff(i,j,:), uflx(i,j,:))
     else
       uflx(i,j,:) = 0.
     endif
   enddo ; enddo
   ! y-flux
   do j = g%jsc-1,g%jec ; do i = g%isc,g%iec
     if (g%mask2dCv(i,j)>0.) then
       call neutral_surface_flux(nk, h(i,j,:), h(i,j+1,:),       &
                                 tracer(i,j,:), tracer(i,j+1,:), &
                                 cs%vPoL(i,j,:), cs%vPoR(i,j,:), &
                                 cs%vKoL(i,j,:), cs%vKoR(i,j,:), &
                                 cs%vhEff(i,j,:), vflx(i,j,:))
     else
       vflx(i,j,:) = 0.
     endif
   enddo ; enddo
   ! Update the tracer concentration from divergence of neutral diffusive flux components
   do j = g%jsc,g%jec ; do i = g%isc,g%iec
     if (g%mask2dT(i,j)>0.) then
       dtracer(:) = 0.
       do ks = 1,2*nk+1 ;
         k = cs%uKoL(i,j,ks)
         dtracer(k) = dtracer(k) + coef_x(i,j)   * uflx(i,j,ks)
         k = cs%uKoR(i-1,j,ks)
         dtracer(k) = dtracer(k) - coef_x(i-1,j) * uflx(i-1,j,ks)
         k = cs%vKoL(i,j,ks)
         dtracer(k) = dtracer(k) + coef_y(i,j)   * vflx(i,j,ks)
         k = cs%vKoR(i,j-1,ks)
         dtracer(k) = dtracer(k) - coef_y(i,j-1) * vflx(i,j-1,ks)
       enddo
       do k = 1, gv%ke
         tracer(i,j,k) = tracer(i,j,k) + dtracer(k) * &
                         ( g%IareaT(i,j) / ( h(i,j,k) + gv%H_subroundoff ) )
       enddo
       if(cs%id_neutral_diff_tracer_conc_tend(m)    > 0  .or.  &
          cs%id_neutral_diff_tracer_cont_tend(m)    > 0  .or.  &
          cs%id_neutral_diff_tracer_cont_tend_2d(m) > 0 ) then
         do k = 1, gv%ke
           tendency(i,j,k) = dtracer(k) * g%IareaT(i,j) * idt
         enddo
       endif
     endif
   enddo ; enddo
   ! Diagnose vertically summed zonal flux, giving zonal tracer transport from ndiff.
   ! Note sign corresponds to downgradient flux convention.
   if(cs%id_neutral_diff_tracer_trans_x_2d(m) > 0) then
     do j = g%jsc,g%jec ; do i = g%isc-1,g%iec
       trans_x_2d(i,j) = 0.
       if (g%mask2dCu(i,j)>0.) then
         do ks = 1,2*nk+1 ;
           trans_x_2d(i,j) = trans_x_2d(i,j) - coef_x(i,j) * uflx(i,j,ks)
         enddo
         trans_x_2d(i,j) = trans_x_2d(i,j) * idt * convert
       endif
     enddo ; enddo
     call post_data(cs%id_neutral_diff_tracer_trans_x_2d(m), trans_x_2d(:,:), cs%diag)
   endif
   ! Diagnose vertically summed merid flux, giving meridional tracer transport from ndiff.
   ! Note sign corresponds to downgradient flux convention.
   if(cs%id_neutral_diff_tracer_trans_y_2d(m) > 0) then
     do j = g%jsc-1,g%jec ; do i = g%isc,g%iec
       trans_y_2d(i,j) = 0.
       if (g%mask2dCv(i,j)>0.) then
         do ks = 1,2*nk+1 ;
           trans_y_2d(i,j) = trans_y_2d(i,j) - coef_y(i,j) * vflx(i,j,ks)
         enddo
         trans_y_2d(i,j) = trans_y_2d(i,j) * idt * convert
       endif
     enddo ; enddo
     call post_data(cs%id_neutral_diff_tracer_trans_y_2d(m), trans_y_2d(:,:), cs%diag)
   endif
   ! post tendency of tracer content
   if(cs%id_neutral_diff_tracer_cont_tend(m) > 0) then
     call post_data(cs%id_neutral_diff_tracer_cont_tend(m), tendency(:,:,:)*convert, cs%diag)
   endif
   ! post depth summed tendency for tracer content
   if(cs%id_neutral_diff_tracer_cont_tend_2d(m) > 0) then
     do j = g%jsc,g%jec ; do i = g%isc,g%iec
       do k = 1, gv%ke
         tendency_2d(i,j) = tendency_2d(i,j) + tendency(i,j,k)
       enddo
     enddo ; enddo
     call post_data(cs%id_neutral_diff_tracer_cont_tend_2d(m), tendency_2d(:,:)*convert, cs%diag)
   endif
   ! post tendency of tracer concentration; this step must be
   ! done after posting tracer content tendency, since we alter
   ! the tendency array.
   if(cs%id_neutral_diff_tracer_conc_tend(m) > 0) then
     do k = 1, gv%ke ; do j = g%jsc,g%jec ; do i = g%isc,g%iec
       tendency(i,j,k) =  tendency(i,j,k) / ( h(i,j,k) + gv%H_subroundoff )
     enddo ; enddo ; enddo
     call post_data(cs%id_neutral_diff_tracer_conc_tend(m), tendency, cs%diag)
   endif
neutral_diffusion_calc_coeffs()
subroutine, public mom_neutral_diffusion::neutral_diffusion_calc_coeffs (type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, real, dimension(g %isd: g %ied, g %jsd: g %jed, g %ke), intent(in) h, real, dimension(g %isd: g %ied, g %jsd: g %jed, g %ke), intent(in) T, real, dimension(g %isd: g %ied, g %jsd: g %jed, g %ke), intent(in) S, type(eos_type), pointer EOS, type(neutral_diffusion_cs), pointer CS)
Calculate remapping factors for u/v columns used to map adjoining columns to a shared coordinate space.
Parameters
[in] g Ocean grid structure
[in] gv ocean vertical grid structure
[in] h Layer thickness (H units)
[in] t Potential temperature (degC)
[in] s Salinity (ppt)
eos Equation of state structure
cs Neutral diffusion control structure
Definition at line 256 of file MOM_neutral_diffusion.F90.
References mom_eos::calculate_density_derivs(), find_neutral_surface_positions(), and interface_scalar().
Referenced by mom_tracer_hor_diff::tracer_hordiff().
   type(ocean_grid_type),                    intent(in) :: g   !< Ocean grid structure
   type(verticalgrid_type),                  intent(in) :: gv  !< ocean vertical grid structure
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)), intent(in) :: h   !< Layer thickness (H units)
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)), intent(in) :: t   !< Potential temperature (degC)
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)), intent(in) :: s   !< Salinity (ppt)
   type(eos_type),                           pointer    :: eos !< Equation of state structure
   type(neutral_diffusion_cs),               pointer    :: cs  !< Neutral diffusion control structure
   ! Local variables
   integer :: i, j, k
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)+1) :: tint ! Interface T (degC)
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)+1) :: sint ! Interface S (ppt)
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)+1) :: pint ! Interface pressure (Pa)
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)+1) :: drdt ! Interface thermal expansion coefficient (kg/m3/degC)
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)+1) :: drds ! Interface haline expansion coefficient (kg/m3/ppt)
   do j = g%jsc-1, g%jec+1
     ! Interpolate state to interface
     do i = g%isc-1, g%iec+1
       call interface_scalar(g%ke, h(i,j,:), t(i,j,:), tint(i,j,:), 2)
       call interface_scalar(g%ke, h(i,j,:), s(i,j,:), sint(i,j,:), 2)
     enddo
     ! Calculate interface properties
     pint(:,j,1) = 0. ! Assume P=0 (Pa) at surface - needs correcting for atmospheric and ice loading - AJA
     do k = 1, g%ke+1
       call calculate_density_derivs(tint(:,j,k), sint(:,j,k), pint(:,j,k), &
                                     drdt(:,j,k), drds(:,j,k), g%isc-1, g%iec-g%isc+3, eos)
       if (k<=g%ke) pint(:,j,k+1) = pint(:,j,k) + h(:,j,k) * gv%H_to_Pa ! Pressure at next interface, k+1 (Pa)
     enddo
   enddo
   ! Neutral surface factors at U points
   do j = g%jsc, g%jec
     do i = g%isc-1, g%iec
       call find_neutral_surface_positions(g%ke,                                          &
                pint(i,j,:), tint(i,j,:), sint(i,j,:), drdt(i,j,:), drds(i,j,:),          &
                pint(i+1,j,:), tint(i+1,j,:), sint(i+1,j,:), drdt(i+1,j,:), drds(i+1,j,:),&
                cs%uPoL(i,j,:), cs%uPoR(i,j,:), cs%uKoL(i,j,:), cs%uKoR(i,j,:), cs%uhEff(i,j,:) )
     enddo
   enddo
   ! Neutral surface factors at V points
   do j = g%jsc-1, g%jec
     do i = g%isc, g%iec
       call find_neutral_surface_positions(g%ke,                                          &
                pint(i,j,:), tint(i,j,:), sint(i,j,:), drdt(i,j,:), drds(i,j,:),          &
                pint(i,j+1,:), tint(i,j+1,:), sint(i,j+1,:), drdt(i,j+1,:), drds(i,j+1,:),&
                cs%vPoL(i,j,:), cs%vPoR(i,j,:), cs%vKoL(i,j,:), cs%vKoR(i,j,:), cs%vhEff(i,j,:) )
     enddo
   enddo
   cs%uhEff(:,:,:) = cs%uhEff(:,:,:) / gv%H_to_pa
   cs%vhEff(:,:,:) = cs%vhEff(:,:,:) / gv%H_to_pa
neutral_diffusion_diag_init()
subroutine, public mom_neutral_diffusion::neutral_diffusion_diag_init (type(time_type), intent(in), target Time, type(ocean_grid_type), intent(in) G, type(diag_ctrl), intent(in) diag, real, intent(in) C_p, type(tracer_registry_type), intent(in) Reg, type(neutral_diffusion_cs), pointer CS)
Diagnostic handles for neutral diffusion tendencies.
Parameters
[in] time Time structure
[in] g Grid structure
[in] diag Diagnostics control structure
[in] reg Tracer structure
[in] c_p Seawater heat capacity
cs Neutral diffusion control structure
Definition at line 119 of file MOM_neutral_diffusion.F90.
References mom_diag_mediator::register_diag_field().
Referenced by mom::initialize_mom().
   type(time_type),target,     intent(in)  :: time   !< Time structure
   type(ocean_grid_type),      intent(in)  :: g      !< Grid structure
   type(diag_ctrl),            intent(in)  :: diag   !< Diagnostics control structure
   type(tracer_registry_type), intent(in)  :: reg    !< Tracer structure
   real,                       intent(in)  :: c_p    !< Seawater heat capacity
   type(neutral_diffusion_cs), pointer     :: cs     !< Neutral diffusion control structure
   ! local
   integer :: n,ntr
   if(.not. associated(cs)) return
   ntr    = reg%ntr
   cs%C_p = c_p
   allocate(cs%id_neutral_diff_tracer_conc_tend(ntr))
   allocate(cs%id_neutral_diff_tracer_cont_tend(ntr))
   allocate(cs%id_neutral_diff_tracer_cont_tend_2d(ntr))
   allocate(cs%id_neutral_diff_tracer_trans_x_2d(ntr))
   allocate(cs%id_neutral_diff_tracer_trans_y_2d(ntr))
   cs%id_neutral_diff_tracer_conc_tend(:)    = -1
   cs%id_neutral_diff_tracer_cont_tend(:)    = -1
   cs%id_neutral_diff_tracer_cont_tend_2d(:) = -1
   cs%id_neutral_diff_tracer_trans_x_2d(:)   = -1
   cs%id_neutral_diff_tracer_trans_y_2d(:)   = -1
   do n=1,ntr
     if(trim(reg%Tr(n)%name) == 'T') then
       cs%id_neutral_diff_tracer_conc_tend(n) = register_diag_field('ocean_model',  &
       'ndiff_tracer_conc_tendency_'//trim(reg%Tr(n)%name), diag%axesTL, time,      &
       'Neutral diffusion tracer concentration tendency for '//trim(reg%Tr(n)%name),&
        'Degree C per second')
       cs%id_neutral_diff_tracer_cont_tend(n) = register_diag_field('ocean_model',                                      &
       'ndiff_tracer_cont_tendency_'//trim(reg%Tr(n)%name), diag%axesTL, time,                                          &
       'Neutral diffusion tracer content tendency for '//trim(reg%Tr(n)%name),                                          &
       'Watts/m2',cmor_field_name='opottemppmdiff', cmor_units='W m-2',                                                 &
       cmor_standard_name=                                                                                              &
       'tendency_of_sea_water_potential_temperature_expressed_as_heat_content_due_to_parameterized_mesocale_diffusion', &
       cmor_long_name =                                                                                                 &
       'Tendency of sea water potential temperature expressed as heat content due to parameterized mesocale diffusion', &
       v_extensive=.true.)
       cs%id_neutral_diff_tracer_cont_tend_2d(n) = register_diag_field('ocean_model',                                                   &
       'ndiff_tracer_cont_tendency_2d_'//trim(reg%Tr(n)%name), diag%axesT1, time,                                                       &
       'Depth integrated neutral diffusion tracer content tendency for '//trim(reg%Tr(n)%name),                                         &
       'Watts/m2',cmor_field_name='opottemppmdiff_2d', cmor_units='W m-2',                                                              &
       cmor_standard_name=                                                                                                              &
       'tendency_of_sea_water_potential_temperature_expressed_as_heat_content_due_to_parameterized_mesocale_diffusion_depth_integrated',&
       cmor_long_name =                                                                                                                 &
       'Tendency of sea water potential temperature expressed as heat content due to parameterized mesocale diffusion depth integrated')
       cs%id_neutral_diff_tracer_trans_x_2d(n) = register_diag_field('ocean_model',           &
       'ndiff_tracer_trans_x_2d_'//trim(reg%Tr(n)%name), diag%axesCu1, time,                  &
       'Depth integrated neutral diffusion zonal tracer transport for '//trim(reg%Tr(n)%name),&
       'Watts')
       cs%id_neutral_diff_tracer_trans_y_2d(n) = register_diag_field('ocean_model',           &
       'ndiff_tracer_trans_y_2d_'//trim(reg%Tr(n)%name), diag%axesCv1, time,                  &
       'Depth integrated neutral diffusion merid tracer transport for '//trim(reg%Tr(n)%name),&
       'Watts')
     elseif(trim(reg%Tr(n)%name) == 'S') then
       cs%id_neutral_diff_tracer_conc_tend(n) = register_diag_field('ocean_model',  &
       'ndiff_tracer_conc_tendency_'//trim(reg%Tr(n)%name), diag%axesTL, time,      &
       'Neutral diffusion tracer concentration tendency for '//trim(reg%Tr(n)%name),&
        'tracer concentration units per second')
       cs%id_neutral_diff_tracer_cont_tend(n) = register_diag_field('ocean_model',                         &
       'ndiff_tracer_cont_tendency_'//trim(reg%Tr(n)%name), diag%axesTL, time,                             &
       'Neutral diffusion tracer content tendency for '//trim(reg%Tr(n)%name),                             &
       'kg m-2 s-1',cmor_field_name='osaltpmdiff', cmor_units='kg m-2 s-1',                                &
       cmor_standard_name=                                                                                 &
       'tendency_of_sea_water_salinity_expressed_as_salt_content_due_to_parameterized_mesocale_diffusion', &
       cmor_long_name =                                                                                    &
       'Tendency of sea water salinity expressed as salt content due to parameterized mesocale diffusion', &
       v_extensive=.true.)
       cs%id_neutral_diff_tracer_cont_tend_2d(n) = register_diag_field('ocean_model',                                      &
       'ndiff_tracer_cont_tendency_2d_'//trim(reg%Tr(n)%name), diag%axesT1, time,                                          &
       'Depth integrated neutral diffusion tracer content tendency for '//trim(reg%Tr(n)%name),                            &
       'kg m-2 s-1',cmor_field_name='osaltpmdiff_2d', cmor_units='kg m-2 s-1',                                             &
       cmor_standard_name=                                                                                                 &
       'tendency_of_sea_water_salinity_expressed_as_salt_content_due_to_parameterized_mesocale_diffusion_depth_integrated',&
       cmor_long_name =                                                                                                    &
       'Tendency of sea water salinity expressed as salt content due to parameterized mesocale diffusion depth integrated')
       cs%id_neutral_diff_tracer_trans_x_2d(n) = register_diag_field('ocean_model',           &
       'ndiff_tracer_trans_x_2d_'//trim(reg%Tr(n)%name), diag%axesCu1, time,                  &
       'Depth integrated neutral diffusion zonal tracer transport for '//trim(reg%Tr(n)%name),&
       'kg/s')
       cs%id_neutral_diff_tracer_trans_y_2d(n) = register_diag_field('ocean_model',           &
       'ndiff_tracer_trans_y_2d_'//trim(reg%Tr(n)%name), diag%axesCv1, time,                  &
       'Depth integrated neutral diffusion merid tracer transport for '//trim(reg%Tr(n)%name),&
       'kg/s')
     else
       cs%id_neutral_diff_tracer_conc_tend(n) = register_diag_field('ocean_model',  &
       'ndiff_tracer_conc_tendency_'//trim(reg%Tr(n)%name), diag%axesTL, time,      &
       'Neutral diffusion tracer concentration tendency for '//trim(reg%Tr(n)%name),&
        'tracer concentration * m-2 s-1')
       cs%id_neutral_diff_tracer_cont_tend(n) = register_diag_field('ocean_model',&
       'ndiff_tracer_cont_tendency_'//trim(reg%Tr(n)%name), diag%axesTL, time,    &
       'Neutral diffusion tracer content tendency for '//trim(reg%Tr(n)%name),    &
       'tracer content * m-2 s-1', v_extensive=.true.)
       cs%id_neutral_diff_tracer_cont_tend_2d(n) = register_diag_field('ocean_model',          &
       'ndiff_tracer_cont_tendency_2d_'//trim(reg%Tr(n)%name), diag%axesTL, time,              &
       'Depth integrated neutral diffusion tracer content tendency for '//trim(reg%Tr(n)%name),&
       'tracer content * m-2 s-1')
       cs%id_neutral_diff_tracer_trans_x_2d(n) = register_diag_field('ocean_model',           &
       'ndiff_tracer_trans_x_2d_'//trim(reg%Tr(n)%name), diag%axesCu1, time,                  &
       'Depth integrated neutral diffusion zonal tracer transport for '//trim(reg%Tr(n)%name),&
       'kg/s')
       cs%id_neutral_diff_tracer_trans_y_2d(n) = register_diag_field('ocean_model',           &
       'ndiff_tracer_trans_y_2d_'//trim(reg%Tr(n)%name), diag%axesCv1, time,                  &
       'Depth integrated neutral diffusion merid tracer transport for '//trim(reg%Tr(n)%name),&
       'kg/s')
     endif
   enddo
neutral_diffusion_end()
subroutine, public mom_neutral_diffusion::neutral_diffusion_end (type(neutral_diffusion_cs), pointer CS)
Deallocates neutral_diffusion control structure.
Definition at line 1513 of file MOM_neutral_diffusion.F90.
   type(neutral_diffusion_cs), pointer :: cs
   if (associated(cs)) deallocate(cs)
neutral_diffusion_init()
logical function, public mom_neutral_diffusion::neutral_diffusion_init (type(time_type), intent(in), target Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(neutral_diffusion_cs), pointer CS)
Read parameters and allocate control structure for neutral_diffusion module.
Parameters
[in] time Time structure
[in] g Grid structure
[in,out] diag Diagnostics control structure
[in] param_file Parameter file structure
cs Neutral diffusion control structure
Definition at line 65 of file MOM_neutral_diffusion.F90.
References mdl, and mom_error_handler::mom_error().
   type(time_type), target,    intent(in)    :: time       !< Time structure
   type(ocean_grid_type),      intent(in)    :: g          !< Grid structure
   type(diag_ctrl), target,    intent(inout) :: diag       !< Diagnostics control structure
   type(param_file_type),      intent(in)    :: param_file !< Parameter file structure
   type(neutral_diffusion_cs), pointer       :: cs         !< Neutral diffusion control structure
   ! Local variables
   character(len=256) :: mesg    ! Message for error messages.
   if (associated(cs)) then
     call mom_error(fatal, "neutral_diffusion_init called with associated control structure.")
     return
   endif
   ! Log this module and master switch for turning it on/off
   call log_version(param_file, mdl, version, &
        "This module implements neutral diffusion of tracers")
   call get_param(param_file, mdl, "USE_NEUTRAL_DIFFUSION", neutral_diffusion_init, &
                  "If true, enables the neutral diffusion module.", &
                  default=.false.)
   if (.not.neutral_diffusion_init) then
     return
   endif
   allocate(cs)
   cs%diag => diag
   ! Read all relevant parameters and write them to the model log.
 ! call openParameterBlock(param_file,'NEUTRAL_DIFF')
 ! call get_param(param_file, mdl, "KHTR", CS%KhTr, &
 !                "The background along-isopycnal tracer diffusivity.", &
 !                units="m2 s-1", default=0.0)
 ! call closeParameterBlock(param_file)
   ! U-points
   allocate(cs%uPoL(g%isd:g%ied,g%jsd:g%jed,2*g%ke+2)); cs%uPoL(g%isc-1:g%iec,g%jsc:g%jec,:)   = 0.
   allocate(cs%uPoR(g%isd:g%ied,g%jsd:g%jed,2*g%ke+2)); cs%uPoR(g%isc-1:g%iec,g%jsc:g%jec,:)   = 0.
   allocate(cs%uKoL(g%isd:g%ied,g%jsd:g%jed,2*g%ke+2)); cs%uKoL(g%isc-1:g%iec,g%jsc:g%jec,:)   = 0
   allocate(cs%uKoR(g%isd:g%ied,g%jsd:g%jed,2*g%ke+2)); cs%uKoR(g%isc-1:g%iec,g%jsc:g%jec,:)   = 0
   allocate(cs%uHeff(g%isd:g%ied,g%jsd:g%jed,2*g%ke+1)); cs%uHeff(g%isc-1:g%iec,g%jsc:g%jec,:) = 0
   ! V-points
   allocate(cs%vPoL(g%isd:g%ied,g%jsd:g%jed,2*g%ke+2)); cs%vPoL(g%isc:g%iec,g%jsc-1:g%jec,:)   = 0.
   allocate(cs%vPoR(g%isd:g%ied,g%jsd:g%jed,2*g%ke+2)); cs%vPoR(g%isc:g%iec,g%jsc-1:g%jec,:)   = 0.
   allocate(cs%vKoL(g%isd:g%ied,g%jsd:g%jed,2*g%ke+2)); cs%vKoL(g%isc:g%iec,g%jsc-1:g%jec,:)   = 0
   allocate(cs%vKoR(g%isd:g%ied,g%jsd:g%jed,2*g%ke+2)); cs%vKoR(g%isc:g%iec,g%jsc-1:g%jec,:)   = 0
   allocate(cs%vHeff(g%isd:g%ied,g%jsd:g%jed,2*g%ke+1)); cs%vHeff(g%isc:g%iec,g%jsc-1:g%jec,:) = 0
neutral_diffusion_unit_tests()
logical function, public mom_neutral_diffusion::neutral_diffusion_unit_tests (logical, intent(in) verbose)
Returns true if unit tests of neutral_diffusion functions fail. Otherwise returns false.
Parameters
[in] verbose It true, write results to stdout
Definition at line 1049 of file MOM_neutral_diffusion.F90.
References absolute_positions(), find_neutral_surface_positions(), interface_scalar(), neutral_surface_flux(), test_data1d(), test_fv_diff(), test_fvlsq_slope(), test_ifndp(), and test_nsp().
Referenced by mom_unit_tests::unit_tests().
   logical, intent(in) :: verbose !< It true, write results to stdout
   ! Local variables
   integer, parameter         :: nk = 4
   real, dimension(nk+1)      :: til, tir1, tir2, tir4, tio ! Test interface temperatures
   real, dimension(nk)        :: tl                         ! Test layer temperatures
   real, dimension(nk+1)      :: sil                        ! Test interface salinities
   real, dimension(nk+1)      :: pil, pir4                  ! Test interface positions
   real, dimension(2*nk+2)    :: pilro, pirlo               ! Test positions
   integer, dimension(2*nk+2) :: kol, kor                   ! Test indexes
   real, dimension(2*nk+1)    :: heff                       ! Test positions
   real, dimension(2*nk+1)    :: flx                        ! Test flux
   integer :: k
   logical :: v
   v = verbose
   neutral_diffusion_unit_tests = .false. ! Normally return false
   write(*,*) '==== MOM_neutral_diffusion: neutral_diffusion_unit_tests ='
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_fv_diff(v,1.,1.,1., 0.,1.,2., 1., 'FV: Straight line on uniform grid')
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_fv_diff(v,1.,1.,0., 0.,4.,8., 7., 'FV: Vanished right cell')
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_fv_diff(v,0.,1.,1., 0.,4.,8., 7., 'FV: Vanished left cell')
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_fv_diff(v,1.,2.,4., 0.,3.,9., 4., 'FV: Stretched grid')
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_fv_diff(v,2.,0.,2., 0.,1.,2., 0., 'FV: Vanished middle cell')
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_fv_diff(v,0.,1.,0., 0.,1.,2., 2., 'FV: Vanished on both sides')
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_fv_diff(v,1.,0.,0., 0.,1.,2., 0., 'FV: Two vanished cell sides')
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_fv_diff(v,0.,0.,0., 0.,1.,2., 0., 'FV: All vanished cells')
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_fvlsq_slope(v,1.,1.,1., 0.,1.,2., 1., 'LSQ: Straight line on uniform grid')
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_fvlsq_slope(v,1.,1.,0., 0.,1.,2., 1., 'LSQ: Vanished right cell')
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_fvlsq_slope(v,0.,1.,1., 0.,1.,2., 1., 'LSQ: Vanished left cell')
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_fvlsq_slope(v,1.,2.,4., 0.,3.,9., 2., 'LSQ: Stretched grid')
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_fvlsq_slope(v,1.,0.,1., 0.,1.,2., 2., 'LSQ: Vanished middle cell')
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_fvlsq_slope(v,0.,1.,0., 0.,1.,2., 0., 'LSQ: Vanished on both sides')
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_fvlsq_slope(v,1.,0.,0., 0.,1.,2., 0., 'LSQ: Two vanished cell sides')
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_fvlsq_slope(v,0.,0.,0., 0.,1.,2., 0., 'LSQ: All vanished cells')
   call interface_scalar(4, (/10.,10.,10.,10./), (/24.,18.,12.,6./), tio, 1)
   !neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_data1d(5, Tio, (/27.,21.,15.,9.,3./), 'Linear profile, interface temperatures')
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_data1d(v,5, tio, (/24.,22.5,15.,7.5,6./), 'Linear profile, linear interface temperatures')
   call interface_scalar(4, (/10.,10.,10.,10./), (/24.,18.,12.,6./), tio, 2)
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_data1d(v,5, tio, (/24.,22.,15.,8.,6./), 'Linear profile, PPM interface temperatures')
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_ifndp(v,-1.0, 0.,  1.0, 1.0, 0.5, 'Check mid-point')
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_ifndp(v, 0.0, 0.,  1.0, 1.0, 0.0, 'Check bottom')
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_ifndp(v, 0.1, 0.,  1.1, 1.0, 0.0, 'Check below')
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_ifndp(v,-1.0, 0.,  0.0, 1.0, 1.0, 'Check top')
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_ifndp(v,-1.0, 0., -0.1, 1.0, 1.0, 'Check above')
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_ifndp(v,-1.0, 0.,  3.0, 1.0, 0.25, 'Check 1/4')
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_ifndp(v,-3.0, 0.,  1.0, 1.0, 0.75, 'Check 3/4')
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_ifndp(v, 1.0, 0.,  1.0, 1.0, 0.0, 'Check dRho=0 below')
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_ifndp(v,-1.0, 0., -1.0, 1.0, 1.0, 'Check dRho=0 above')
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_ifndp(v, 0.0, 0.,  0.0, 1.0, 0.5, 'Check dRho=0 mid')
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_ifndp(v,-2.0, .5,  5.0, 0.5, 0.5, 'Check dP=0')
   ! Identical columns
   call find_neutral_surface_positions(3, &
              (/0.,10.,20.,30./), (/22.,18.,14.,10./), (/0.,0.,0.,0./), & ! Left positions, T and S
              (/-1.,-1.,-1.,-1./), (/1.,1.,1.,1./), &! Left dRdT and dRdS
              (/0.,10.,20.,30./), (/22.,18.,14.,10./), (/0.,0.,0.,0./), & ! Right positions, T and S
              (/-1.,-1.,-1.,-1./), (/1.,1.,1.,1./), &! Right dRdT and dRdS
              pilro, pirlo, kol, kor, heff)
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or.  test_nsp(v, 3, kol, kor, pilro, pirlo, heff, &
                                    (/1,1,2,2,3,3,3,3/), & ! KoL
                                    (/1,1,2,2,3,3,3,3/), & ! KoR
                                    (/0.,0.,0.,0.,0.,0.,1.,1./), & ! pL
                                    (/0.,0.,0.,0.,0.,0.,1.,1./), & ! pR
                                    (/0.,10.,0.,10.,0.,10.,0./), & ! hEff
                                    'Identical columns')
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_data1d(v, 8, &
                                    absolute_positions(3, (/0.,10.,20.,30./), kol, pilro), &
                                    (/0.,0.,10.,10.,20.,20.,30.,30./), '... left positions')
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_data1d(v, 8, &
                                    absolute_positions(3, (/0.,10.,20.,30./), kor, pirlo), &
                                    (/0.,0.,10.,10.,20.,20.,30.,30./), '... right positions')
   call neutral_surface_flux(3, (/10.,10.,10./), (/10.,10.,10./), & ! nk, hL, hR
                                (/20.,16.,12./), (/20.,16.,12./), & ! Tl, Tr
                                pilro, pirlo, kol, kor, heff, flx)
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_data1d(v, 7, flx, &
               (/0.,0.,0.,0.,0.,0.,0./), 'Identical columns, rho flux (=0)')
   call neutral_surface_flux(3, (/10.,10.,10./), (/10.,10.,10./), & ! nk, hL, hR
                                (/-1.,-1.,-1./), (/1.,1.,1./), & ! Sl, Sr
                                pilro, pirlo, kol, kor, heff, flx)
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_data1d(v, 7, flx, &
               (/0.,20.,0.,20.,0.,20.,0./), 'Identical columns, S flux')
   ! Right column slightly cooler than left
   call find_neutral_surface_positions(3, &
              (/0.,10.,20.,30./), (/22.,18.,14.,10./), (/0.,0.,0.,0./), & ! Left positions, T and S
              (/-1.,-1.,-1.,-1./), (/1.,1.,1.,1./), &! Left dRdT and dRdS
              (/0.,10.,20.,30./), (/20.,16.,12.,8./), (/0.,0.,0.,0./), & ! Right positions, T and S
              (/-1.,-1.,-1.,-1./), (/1.,1.,1.,1./), &! Right dRdT and dRdS
              pilro, pirlo, kol, kor, heff)
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or.  test_nsp(v, 3, kol, kor, pilro, pirlo, heff, &
                                    (/1,1,2,2,3,3,3,3/), & ! kL
                                    (/1,1,1,2,2,3,3,3/), & ! kR
                                    (/0.,0.5,0.,0.5,0.,0.5,1.,1./), & ! pL
                                    (/0.,0.,0.5,0.,0.5,0.,0.5,1./), & ! pR
                                    (/0.,5.,5.,5.,5.,5.,0./), & ! hEff
                                    'Right column slightly cooler')
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_data1d(v, 8, &
                                    absolute_positions(3, (/0.,10.,20.,30./), kol, pilro), &
                                    (/0.,5.,10.,15.,20.,25.,30.,30./), '... left positions')
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or. test_data1d(v, 8, &
                                    absolute_positions(3, (/0.,10.,20.,30./), kor, pirlo), &
                                    (/0.,0.,5.,10.,15.,20.,25.,30./), '... right positions')
   ! Right column slightly warmer than left
   call find_neutral_surface_positions(3, &
              (/0.,10.,20.,30./), (/22.,18.,14.,10./), (/0.,0.,0.,0./), & ! Left positions, T and S
              (/-1.,-1.,-1.,-1./), (/1.,1.,1.,1./), &! Left dRdT and dRdS
              (/0.,10.,20.,30./), (/24.,20.,16.,12./), (/0.,0.,0.,0./), & ! Right positions, T and S
              (/-1.,-1.,-1.,-1./), (/1.,1.,1.,1./), &! Right dRdT and dRdS
              pilro, pirlo, kol, kor, heff)
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or.  test_nsp(v, 3, kol, kor, pilro, pirlo, heff, &
                                    (/1,1,1,2,2,3,3,3/), & ! kL
                                    (/1,1,2,2,3,3,3,3/), & ! kR
                                    (/0.,0.,0.5,0.,0.5,0.,0.5,1./), & ! pL
                                    (/0.,0.5,0.,0.5,0.,0.5,1.,1./), & ! pR
                                    (/0.,5.,5.,5.,5.,5.,0./), & ! hEff
                                    'Right column slightly warmer')
   ! Right column somewhat cooler than left
   call find_neutral_surface_positions(3, &
              (/0.,10.,20.,30./), (/22.,18.,14.,10./), (/0.,0.,0.,0./), & ! Left positions, T and S
              (/-1.,-1.,-1.,-1./), (/1.,1.,1.,1./), &! Left dRdT and dRdS
              (/0.,10.,20.,30./), (/16.,12.,8.,4./), (/0.,0.,0.,0./), & ! Right positions, T and S
              (/-1.,-1.,-1.,-1./), (/1.,1.,1.,1./), &! Right dRdT and dRdS
              pilro, pirlo, kol, kor, heff)
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or.  test_nsp(v, 3, kol, kor, pilro, pirlo, heff, &
                                    (/1,2,2,3,3,3,3,3/), & ! kL
                                    (/1,1,1,1,2,2,3,3/), & ! kR
                                    (/0.,0.,0.5,0.,0.5,1.,1.,1./), & ! pL
                                    (/0.,0.,0.,0.5,0.,0.5,0.,1./), & ! pR
                                    (/0.,0.,5.,5.,5.,0.,0./), & ! hEff
                                    'Right column somewhat cooler')
   ! Right column much colder than left with no overlap
   call find_neutral_surface_positions(3, &
              (/0.,10.,20.,30./), (/22.,18.,14.,10./), (/0.,0.,0.,0./), & ! Left positions, T and S
              (/-1.,-1.,-1.,-1./), (/1.,1.,1.,1./), &! Left dRdT and dRdS
              (/0.,10.,20.,30./), (/9.,7.,5.,3./), (/0.,0.,0.,0./), & ! Right positions, T and S
              (/-1.,-1.,-1.,-1./), (/1.,1.,1.,1./), &! Right dRdT and dRdS
              pilro, pirlo, kol, kor, heff)
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or.  test_nsp(v, 3, kol, kor, pilro, pirlo, heff, &
                                    (/1,2,3,3,3,3,3,3/), & ! kL
                                    (/1,1,1,1,1,2,3,3/), & ! kR
                                    (/0.,0.,0.,1.,1.,1.,1.,1./), & ! pL
                                    (/0.,0.,0.,0.,0.,0.,0.,1./), & ! pR
                                    (/0.,0.,0.,0.,0.,0.,0./), & ! hEff
                                    'Right column much cooler')
   ! Right column with mixed layer
   call find_neutral_surface_positions(3, &
              (/0.,10.,20.,30./), (/22.,18.,14.,10./), (/0.,0.,0.,0./), & ! Left positions, T and S
              (/-1.,-1.,-1.,-1./), (/1.,1.,1.,1./), &! Left dRdT and dRdS
              (/0.,10.,20.,30./), (/14.,14.,10.,2./), (/0.,0.,0.,0./), & ! Right positions, T and S
              (/-1.,-1.,-1.,-1./), (/1.,1.,1.,1./), &! Right dRdT and dRdS
              pilro, pirlo, kol, kor, heff)
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or.  test_nsp(v, 3, kol, kor, pilro, pirlo, heff, &
                                    (/1,2,3,3,3,3,3,3/), & ! kL
                                    (/1,1,1,1,2,3,3,3/), & ! kR
                                    (/0.,0.,0.,0.,0.,1.,1.,1./), & ! pL
                                    (/0.,0.,0.,0.,0.,0.,0.,1./), & ! pR
                                    (/0.,0.,0.,0.,10.,0.,0./), & ! hEff
                                    'Right column with mixed layer')
   ! Identical columns with mixed layer
   call find_neutral_surface_positions(3, &
              (/0.,10.,20.,30./), (/14.,14.,10.,2./), (/0.,0.,0.,0./), & ! Left positions, T and S
              (/-1.,-1.,-1.,-1./), (/1.,1.,1.,1./), &! Left dRdT and dRdS
              (/0.,10.,20.,30./), (/14.,14.,10.,2./), (/0.,0.,0.,0./), & ! Right positions, T and S
              (/-1.,-1.,-1.,-1./), (/1.,1.,1.,1./), &! Right dRdT and dRdS
              pilro, pirlo, kol, kor, heff)
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or.  test_nsp(v, 3, kol, kor, pilro, pirlo, heff, &
                                    (/1,1,2,2,3,3,3,3/), & ! kL
                                    (/1,1,2,2,3,3,3,3/), & ! kR
                                    (/0.,0.,0.,0.,0.,0.,1.,1./), & ! pL
                                    (/0.,0.,0.,0.,0.,0.,1.,1./), & ! pR
                                    (/0.,10.,0.,10.,0.,10.,0./), & ! hEff
                                    'Indentical columns with mixed layer')
   ! Right column with unstable mixed layer
   call find_neutral_surface_positions(3, &
              (/0.,10.,20.,30./), (/14.,14.,10.,2./), (/0.,0.,0.,0./), & ! Left positions, T and S
              (/-1.,-1.,-1.,-1./), (/1.,1.,1.,1./), &! Left dRdT and dRdS
              (/0.,10.,20.,30./), (/10.,14.,12.,4./), (/0.,0.,0.,0./), & ! Right positions, T and S
              (/-1.,-1.,-1.,-1./), (/1.,1.,1.,1./), &! Right dRdT and dRdS
              pilro, pirlo, kol, kor, heff)
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or.  test_nsp(v, 3, kol, kor, pilro, pirlo, heff, &
                                    (/1,2,3,3,3,3,3,3/), & ! kL
                                    (/1,1,1,2,3,3,3,3/), & ! kR
                                    (/0.,0.,0.,0.,0.,0.,.75,1./), & ! pL
                                    (/0.,0.,0.,0.,0.,0.25,1.,1./), & ! pR
                                    (/0.,0.,0.,0.,0.,7.5,0./), & ! hEff
                                    'Right column with unstable mixed layer')
   ! Left column with unstable mixed layer
   call find_neutral_surface_positions(3, &
              (/0.,10.,20.,30./), (/10.,14.,12.,4./), (/0.,0.,0.,0./), & ! Left positions, T and S
              (/-1.,-1.,-1.,-1./), (/1.,1.,1.,1./), &! Left dRdT and dRdS
              (/0.,10.,20.,30./), (/14.,14.,10.,2./), (/0.,0.,0.,0./), & ! Right positions, T and S
              (/-1.,-1.,-1.,-1./), (/1.,1.,1.,1./), &! Right dRdT and dRdS
              pilro, pirlo, kol, kor, heff)
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or.  test_nsp(v, 3, kol, kor, pilro, pirlo, heff, &
                                    (/1,1,1,2,3,3,3,3/), & ! kL
                                    (/1,2,3,3,3,3,3,3/), & ! kR
                                    (/0.,0.,0.,0.,0.,0.25,1.,1./), & ! pL
                                    (/0.,0.,0.,0.,0.,0.,.75,1./), & ! pR
                                    (/0.,0.,0.,0.,0.,7.5,0./), & ! hEff
                                    'Left column with unstable mixed layer')
   ! Two unstable mixed layers
   call find_neutral_surface_positions(3, &
              (/0.,10.,20.,30./), (/8.,12.,10.,2./), (/0.,0.,0.,0./), & ! Left positions, T and S
              (/-1.,-1.,-1.,-1./), (/1.,1.,1.,1./), &! Left dRdT and dRdS
              (/0.,10.,20.,30./), (/10.,14.,12.,4./), (/0.,0.,0.,0./), & ! Right positions, T and S
              (/-1.,-1.,-1.,-1./), (/1.,1.,1.,1./), &! Right dRdT and dRdS
              pilro, pirlo, kol, kor, heff)
   neutral_diffusion_unit_tests = neutral_diffusion_unit_tests .or.  test_nsp(v, 3, kol, kor, pilro, pirlo, heff, &
                                    (/1,1,1,1,2,3,3,3/), & ! kL
                                    (/1,2,3,3,3,3,3,3/), & ! kR
                                    (/0.,0.,0.,0.,0.,0.,0.75,1./), & ! pL
                                    (/0.,0.,0.,0.5,0.5,0.5,1.,1./), & ! pR
                                    (/0.,0.,0.,0.,0.,6.,0./), & ! hEff
                                    'Two unstable mixed layers')
   if (.not. neutral_diffusion_unit_tests) write(*,*) 'Pass'
neutral_surface_flux()
subroutine mom_neutral_diffusion::neutral_surface_flux (integer, intent(in) nk, real, dimension(nk), intent(in) hl, real, dimension(nk), intent(in) hr, real, dimension(nk), intent(in) Tl, real, dimension(nk), intent(in) Tr, real, dimension(2*nk+2), intent(in) PiL, real, dimension(2*nk+2), intent(in) PiR, integer, dimension(2*nk+2), intent(in) KoL, integer, dimension(2*nk+2), intent(in) KoR, real, dimension(2*nk+1), intent(in) hEff, real, dimension(2*nk+1), intent(inout) Flx) private
Returns a single column of neutral diffusion fluxes of a tracer.
Parameters
[in] nk Number of levels
[in] hl Left-column layer thickness (Pa)
[in] hr Right-column layer thickness (Pa)
[in] tl Left-column layer tracer (conc, e.g. degC)
[in] tr Right-column layer tracer (conc, e.g. degC)
[in] pil Fractional position of neutral surface within layer KoL of left column
[in] pir Fractional position of neutral surface within layer KoR of right column
[in] kol Index of first left interface above neutral surface
[in] kor Index of first right interface above neutral surface
[in] heff Effective thickness between two neutral surfaces (Pa)
[in,out] flx Flux of tracer between pairs of neutral layers (conc H)
Definition at line 958 of file MOM_neutral_diffusion.F90.
References interface_scalar(), ppm_ave(), and signum().
Referenced by neutral_diffusion(), and neutral_diffusion_unit_tests().
   integer,                    intent(in)    :: nk    !< Number of levels
   real, dimension(nk),        intent(in)    :: hl    !< Left-column layer thickness (Pa)
   real, dimension(nk),        intent(in)    :: hr    !< Right-column layer thickness (Pa)
   real, dimension(nk),        intent(in)    :: tl    !< Left-column layer tracer (conc, e.g. degC)
   real, dimension(nk),        intent(in)    :: tr    !< Right-column layer tracer (conc, e.g. degC)
   real, dimension(2*nk+2),    intent(in)    :: pil   !< Fractional position of neutral surface within layer KoL of left column
   real, dimension(2*nk+2),    intent(in)    :: pir   !< Fractional position of neutral surface within layer KoR of right column
   integer, dimension(2*nk+2), intent(in)    :: kol   !< Index of first left interface above neutral surface
   integer, dimension(2*nk+2), intent(in)    :: kor   !< Index of first right interface above neutral surface
   real, dimension(2*nk+1),    intent(in)    :: heff  !< Effective thickness between two neutral surfaces (Pa)
   real, dimension(2*nk+1),    intent(inout) :: flx   !< Flux of tracer between pairs of neutral layers (conc H)
   ! Local variables
   integer :: k_sublayer, klb, klt, krb, krt, k
   real :: t_right_top, t_right_bottom, t_right_layer
   real :: t_left_top, t_left_bottom, t_left_layer
   real :: dt_top, dt_bottom, dt_layer, dt_ave
   real, dimension(nk+1) :: til !< Left-column interface tracer (conc, e.g. degC)
   real, dimension(nk+1) :: tir !< Right-column interface tracer (conc, e.g. degC)
   real, dimension(nk) :: al_l !< Left-column left edge value of tracer (conc, e.g. degC)
   real, dimension(nk) :: ar_l !< Left-column right edge value of tracer (conc, e.g. degC)
   real, dimension(nk) :: al_r !< Right-column left edge value of tracer (conc, e.g. degC)
   real, dimension(nk) :: ar_r !< Right-column right edge value of tracer (conc, e.g. degC)
   call interface_scalar(nk, hl, tl, til, 2)
   call interface_scalar(nk, hr, tr, tir, 2)
   ! Setup reconstruction edge values
   do k = 1, nk
     al_l(k) = til(k)
     ar_l(k) = til(k+1)
     if ( signum(1., ar_l(k) - tl(k))*signum(1., tl(k) - al_l(k)) <= 0.0 ) then
       al_l(k) = tl(k)
       ar_l(k) = tl(k)
     elseif ( sign(3., ar_l(k) - al_l(k)) * ( (tl(k) - al_l(k)) + (tl(k) - ar_l(k))) > abs(ar_l(k) - al_l(k)) ) then
       al_l(k) = tl(k) + 2.0 * ( tl(k) - ar_l(k) )
     elseif ( sign(3., ar_l(k) - al_l(k)) * ( (tl(k) - al_l(k)) + (tl(k) - ar_l(k))) < -abs(ar_l(k) - al_l(k)) ) then
       ar_l(k) = tl(k) + 2.0 * ( tl(k) - al_l(k) )
     endif
     al_r(k) = tir(k)
     ar_r(k) = tir(k+1)
     if ( signum(1., ar_r(k) - tr(k))*signum(1., tr(k) - al_r(k)) <= 0.0 ) then
       al_r(k) = tr(k)
       ar_r(k) = tr(k)
     elseif ( sign(3., ar_r(k) - al_r(k)) * ( (tr(k) - al_r(k)) + (tr(k) - ar_r(k))) > abs(ar_r(k) - al_r(k)) ) then
       al_r(k) = tr(k) + 2.0 * ( tr(k) - ar_r(k) )
     elseif ( sign(3., ar_r(k) - al_r(k)) * ( (tr(k) - al_r(k)) + (tr(k) - ar_r(k))) < -abs(ar_r(k) - al_r(k)) ) then
       ar_r(k) = tr(k) + 2.0 * ( tr(k) - al_r(k) )
     endif
   enddo
   do k_sublayer = 1, 2*nk+1
     if (heff(k_sublayer) == 0.) then
       flx(k_sublayer) = 0.
     else
       klb = kol(k_sublayer+1)
       t_left_bottom = ( 1. - pil(k_sublayer+1) ) * til(klb) + pil(k_sublayer+1) * til(klb+1)
       klt = kol(k_sublayer)
       t_left_top = ( 1. - pil(k_sublayer) ) * til(klt) + pil(k_sublayer) * til(klt+1)
       t_left_layer = ppm_ave(pil(k_sublayer), pil(k_sublayer+1) + real(klb-klt), &
                              al_l(klt), ar_l(klt), tl(klt))
       krb = kor(k_sublayer+1)
       t_right_bottom = ( 1. - pir(k_sublayer+1) ) * tir(krb) + pir(k_sublayer+1) * tir(krb+1)
       krt = kor(k_sublayer)
       t_right_top = ( 1. - pir(k_sublayer) ) * tir(krt) + pir(k_sublayer) * tir(krt+1)
       t_right_layer = ppm_ave(pir(k_sublayer), pir(k_sublayer+1) + real(krb-krt), &
                               al_r(krt), ar_r(krt), tr(krt))
       dt_top = t_right_top - t_left_top
       dt_bottom = t_right_bottom - t_left_bottom
       dt_ave = 0.5 * ( dt_top + dt_bottom )
       dt_layer = t_right_layer - t_left_layer
       if (signum(1.,dt_top) * signum(1.,dt_bottom) <= 0. .or. signum(1.,dt_ave) * signum(1.,dt_layer) <= 0. ) then
         dt_ave = 0.
       else
         dt_ave = dt_layer
       endif
       flx(k_sublayer) = dt_ave * heff(k_sublayer)
     endif
   enddo
plm_diff()
subroutine mom_neutral_diffusion::plm_diff (integer, intent(in) nk, real, dimension(nk), intent(in) h, real, dimension(nk), intent(in) S, integer, intent(in) c_method, integer, intent(in) b_method, real, dimension(nk), intent(inout) diff) private
Returns PLM slopes for a column where the slopes are the difference in value across each cell. The limiting follows equation 1.8 in Colella & Woodward, 1984: JCP 54, 174-201.
Parameters
[in] nk Number of levels
[in] h Layer thickness (H units)
[in] s Layer salinity (conc, e.g. ppt)
[in] c_method Method to use for the centered difference
[in] b_method =1, use PCM in first/last cell, =2 uses linear extrapolation
[in,out] diff Scalar difference across layer (conc, e.g. ppt) determined by the following values for c_method:
Second order finite difference (not recommended)
Second order finite volume (used in original PPM)
Finite-volume weighted least squares linear fit
Todo:
The use of c_method to choose a scheme is inefficient and should eventually be moved up the call tree.
Definition at line 593 of file MOM_neutral_diffusion.F90.
References fv_diff(), fvlsq_slope(), and signum().
Referenced by interface_scalar().
   integer,             intent(in)    :: nk       !< Number of levels
   real, dimension(nk), intent(in)    :: h        !< Layer thickness (H units)
   real, dimension(nk), intent(in)    :: s        !< Layer salinity (conc, e.g. ppt)
   integer,             intent(in)    :: c_method !< Method to use for the centered difference
   integer,             intent(in)    :: b_method !< =1, use PCM in first/last cell, =2 uses linear extrapolation
   real, dimension(nk), intent(inout) :: diff     !< Scalar difference across layer (conc, e.g. ppt)
                                                  !! determined by the following values for c_method:
                                                  !!   1. Second order finite difference (not recommended)
                                                  !!   2. Second order finite volume (used in original PPM)
                                                  !!   3. Finite-volume weighted least squares linear fit
                                                  !! \todo  The use of c_method to choose a scheme is inefficient
                                                  !! and should eventually be moved up the call tree.
   ! Local variables
   integer :: k
   real :: hkm1, hk, hkp1, skm1, sk, skp1, diff_l, diff_r, diff_c
   do k = 2, nk-1
     hkm1 = h(k-1)
     hk = h(k)
     hkp1 = h(k+1)
     if ( ( hkp1 + hk ) * ( hkm1 + hk ) > 0.) then
       skm1 = s(k-1)
       sk = s(k)
       skp1 = s(k+1)
       if (c_method==1) then
         ! Simple centered diff (from White)
         if ( hk + 0.5 * (hkm1 + hkp1) /= 0. ) then
           diff_c = ( skp1 - skm1 ) * ( hk / ( hk + 0.5 * (hkm1 + hkp1) ) )
         else
           diff_c = 0.
         endif
       elseif (c_method==2) then
         ! Second order accurate centered FV slope (from Colella and Woodward, JCP 1984)
         diff_c = fv_diff(hkm1, hk, hkp1, skm1, sk, skp1)
       elseif (c_method==3) then
         ! Second order accurate finite-volume least squares slope
         diff_c = hk * fvlsq_slope(hkm1, hk, hkp1, skm1, sk, skp1)
       endif
       ! Limit centered slope by twice the side differenced slopes
       diff_l = 2. * ( sk - skm1 )
       diff_r = 2. * ( skp1 - sk )
       if ( signum(1., diff_l) * signum(1., diff_r) <= 0. ) then
         diff(k) = 0. ! PCM for local extrema
       else
         diff(k) = sign( min( abs(diff_l), abs(diff_c), abs(diff_r) ), diff_c )
       endif
     else
       diff(k) = 0. ! PCM next to vanished layers
     endif
   enddo
   if (b_method==1) then ! PCM for top and bottom layer
     diff(1) = 0.
     diff(nk) = 0.
   elseif (b_method==2) then ! Linear extrapolation for top and bottom interfaces
     diff(1) = ( s(2) - s(1) ) * 2. * ( h(1) / ( h(1) + h(2) ) )
     diff(nk) = s(nk) - s(nk-1) * 2. * ( h(nk) / ( h(nk-1) + h(nk) ) )
   endif
ppm_ave()
real function mom_neutral_diffusion::ppm_ave (real, intent(in) xL, real, intent(in) xR, real, intent(in) aL, real, intent(in) aR, real, intent(in) aMean) private
Returns the average of a PPM reconstruction between two fractional positions.
Parameters
[in] xl Fraction position of left bound (0,1)
[in] xr Fraction position of right bound (0,1)
[in] al Left edge scalar value, at x=0
[in] ar Right edge scalar value, at x=1
[in] amean Average scalar value of cell
Definition at line 554 of file MOM_neutral_diffusion.F90.
Referenced by neutral_surface_flux().
   real, intent(in) :: xl    !< Fraction position of left bound (0,1)
   real, intent(in) :: xr    !< Fraction position of right bound (0,1)
   real, intent(in) :: al    !< Left edge scalar value, at x=0
   real, intent(in) :: ar    !< Right edge scalar value, at x=1
   real, intent(in) :: amean !< Average scalar value of cell
   ! Local variables
   real :: dx, xave, a6, a6o3
   dx = xr - xl
   xave = 0.5 * ( xr + xl )
   a6o3 = 2. * amean - ( al + ar ) ! a6 / 3.
   a6 = 3. * a6o3
   if (dx<0.) then
     stop 'ppm_ave: dx<0 should not happend!'
   elseif (dx>1.) then
     stop 'ppm_ave: dx>1 should not happend!'
   elseif (dx==0.) then
     ppm_ave = al + ( ar - al ) * xr + a6 * xr * ( 1. - xr )
   else
     ppm_ave = ( al + xave * ( ( ar - al ) + a6 ) )  - a6o3 * ( xr**2 + xr * xl + xl**2 )
   endif
ppm_edge()
real function mom_neutral_diffusion::ppm_edge (real, intent(in) hkm1, real, intent(in) hk, real, intent(in) hkp1, real, intent(in) hkp2, real, intent(in) Ak, real, intent(in) Akp1, real, intent(in) Pk, real, intent(in) Pkp1) private
Returns the PPM quasi-fourth order edge value at k+1/2 following equation 1.6 in Colella & Woodward, 1984: JCP 54, 174-201.
Parameters
[in] hkm1 Width of cell k-1
[in] hk Width of cell k
[in] hkp1 Width of cell k+1
[in] hkp2 Width of cell k+2
[in] ak Average scalar value of cell k
[in] akp1 Average scalar value of cell k+1
[in] pk PLM slope for cell k
[in] pkp1 PLM slope for cell k+1
Definition at line 514 of file MOM_neutral_diffusion.F90.
Referenced by interface_scalar().
   real, intent(in) :: hkm1 !< Width of cell k-1
   real, intent(in) :: hk   !< Width of cell k
   real, intent(in) :: hkp1 !< Width of cell k+1
   real, intent(in) :: hkp2 !< Width of cell k+2
   real, intent(in) :: ak   !< Average scalar value of cell k
   real, intent(in) :: akp1 !< Average scalar value of cell k+1
   real, intent(in) :: pk   !< PLM slope for cell k
   real, intent(in) :: pkp1 !< PLM slope for cell k+1
   ! Local variables
   real :: r_hk_hkp1, r_2hk_hkp1, r_hk_2hkp1, f1, f2, f3, f4
   real, parameter :: h_neglect = 1.e-30
   r_hk_hkp1 = hk + hkp1
   if (r_hk_hkp1 <= 0.) then
     ppm_edge = 0.5 * ( ak + akp1 )
     return
   endif
   r_hk_hkp1 = 1. / r_hk_hkp1
   if (hk<hkp1) then
     ppm_edge = ak + ( hk * r_hk_hkp1 ) * ( akp1 - ak )
   else
     ppm_edge = akp1 + ( hkp1 * r_hk_hkp1 ) * ( ak - akp1 )
   endif
   r_2hk_hkp1 = 1. / ( ( 2. * hk + hkp1 ) + h_neglect )
   r_hk_2hkp1 = 1. / ( ( hk + 2. * hkp1 ) + h_neglect )
   f1 = 1./ ( ( hk + hkp1) + ( hkm1 + hkp2 ) )
   f2 = 2. * ( hkp1 * hk ) * r_hk_hkp1 * &
             ( ( hkm1 + hk ) * r_2hk_hkp1  - ( hkp2 + hkp1 ) * r_hk_2hkp1 )
   f3 = hk * ( hkm1 + hk ) * r_2hk_hkp1
   f4 = hkp1 * ( hkp1 + hkp2 ) * r_hk_2hkp1
   ppm_edge = ppm_edge + f1 * ( f2 * ( akp1 - ak ) - ( f3 * pkp1 - f4 * pk ) )
signum()
real function mom_neutral_diffusion::signum (real, intent(in) a, real, intent(in) x) private
A true signum function that returns either -abs(a), when x<0; or abs(a) when x>0; or 0 when x=0.
Parameters
[in] a The magnitude argument
[in] x The sign (or zero) argument
Definition at line 582 of file MOM_neutral_diffusion.F90.
Referenced by neutral_surface_flux(), and plm_diff().
   real, intent(in) :: a !< The magnitude argument
   real, intent(in) :: x !< The sign (or zero) argument
   signum = sign(a,x)
   if (x==0.) signum = 0.
test_data1d()
logical function mom_neutral_diffusion::test_data1d (logical, intent(in) verbose, integer, intent(in) nk, real, dimension(nk), intent(in) Po, real, dimension(nk), intent(in) Ptrue, character(len=*), intent(in) title) private
Returns true if comparison of Po and Ptrue fails, and conditionally writes results to stream.
Parameters
[in] verbose If true, write results to stdout
[in] nk Number of layers
[in] po Calculated answer
[in] ptrue True answer
[in] title Title for messages
Definition at line 1376 of file MOM_neutral_diffusion.F90.
Referenced by neutral_diffusion_unit_tests().
   logical,             intent(in) :: verbose !< If true, write results to stdout
   integer,             intent(in) :: nk    !< Number of layers
   real, dimension(nk), intent(in) :: po    !< Calculated answer
   real, dimension(nk), intent(in) :: ptrue !< True answer
   character(len=*),    intent(in) :: title !< Title for messages
   ! Local variables
   integer :: k, stdunit
   test_data1d = .false.
   do k = 1,nk
     if (po(k) /= ptrue(k)) test_data1d = .true.
   enddo
   if (test_data1d .or. verbose) then
     stdunit = 6
     if (test_data1d) stdunit = 0 ! In case of wrong results, write to error stream
     write(stdunit,'(a)') title
     do k = 1,nk
       if (po(k) /= ptrue(k)) then
         test_data1d = .true.
         write(stdunit,'(a,i2,2(x,a,f20.16),x,a,1pe22.15,x,a)') 'k=',k,'Po=',po(k),'Ptrue=',ptrue(k),'err=',po(k)-ptrue(k),'WRONG!'
       else
         if (verbose) &
           write(stdunit,'(a,i2,2(x,a,f20.16),x,a,1pe22.15)') 'k=',k,'Po=',po(k),'Ptrue=',ptrue(k),'err=',po(k)-ptrue(k)
       endif
     enddo
   endif
test_data1di()
logical function mom_neutral_diffusion::test_data1di (logical, intent(in) verbose, integer, intent(in) nk, integer, dimension(nk), intent(in) Po, integer, dimension(nk), intent(in) Ptrue, character(len=*), intent(in) title) private
Returns true if comparison of Po and Ptrue fails, and conditionally writes results to stream.
Parameters
[in] verbose If true, write results to stdout
[in] nk Number of layers
[in] po Calculated answer
[in] ptrue True answer
[in] title Title for messages
Definition at line 1409 of file MOM_neutral_diffusion.F90.
   logical,                intent(in) :: verbose !< If true, write results to stdout
   integer,                intent(in) :: nk    !< Number of layers
   integer, dimension(nk), intent(in) :: po    !< Calculated answer
   integer, dimension(nk), intent(in) :: ptrue !< True answer
   character(len=*),       intent(in) :: title !< Title for messages
   ! Local variables
   integer :: k, stdunit
   test_data1di = .false.
   do k = 1,nk
     if (po(k) /= ptrue(k)) test_data1di = .true.
   enddo
   if (test_data1di .or. verbose) then
     stdunit = 6
     if (test_data1di) stdunit = 0 ! In case of wrong results, write to error stream
     write(stdunit,'(a)') title
     do k = 1,nk
       if (po(k) /= ptrue(k)) then
         test_data1di = .true.
         write(stdunit,'(a,i2,2(x,a,i5),x,a)') 'k=',k,'Io=',po(k),'Itrue=',ptrue(k),'WRONG!'
       else
         if (verbose) &
           write(stdunit,'(a,i2,2(x,a,i5))') 'k=',k,'Io=',po(k),'Itrue=',ptrue(k)
       endif
     enddo
   endif
test_fv_diff()
logical function mom_neutral_diffusion::test_fv_diff (logical, intent(in) verbose, real, intent(in) hkm1, real, intent(in) hk, real, intent(in) hkp1, real, intent(in) Skm1, real, intent(in) Sk, real, intent(in) Skp1, real, intent(in) Ptrue, character(len=*), intent(in) title) private
Returns true if a test of fv_diff() fails, and conditionally writes results to stream.
Parameters
[in] verbose If true, write results to stdout
[in] hkm1 Left cell width
[in] hk Center cell width
[in] hkp1 Right cell width
[in] skm1 Left cell average value
[in] sk Center cell average value
[in] skp1 Right cell average value
[in] ptrue True answer (Pa)
[in] title Title for messages
Definition at line 1282 of file MOM_neutral_diffusion.F90.
References fv_diff().
Referenced by neutral_diffusion_unit_tests().
   logical,          intent(in) :: verbose !< If true, write results to stdout
   real,             intent(in) :: hkm1  !< Left cell width
   real,             intent(in) :: hk    !< Center cell width
   real,             intent(in) :: hkp1  !< Right cell width
   real,             intent(in) :: skm1  !< Left cell average value
   real,             intent(in) :: sk    !< Center cell average value
   real,             intent(in) :: skp1  !< Right cell average value
   real,             intent(in) :: ptrue !< True answer (Pa)
   character(len=*), intent(in) :: title !< Title for messages
   ! Local variables
   integer :: stdunit
   real :: pret
   pret = fv_diff(hkm1, hk, hkp1, skm1, sk, skp1)
   test_fv_diff = (pret /= ptrue)
   if (test_fv_diff .or. verbose) then
     stdunit = 6
     if (test_fv_diff) stdunit = 0 ! In case of wrong results, write to error stream
     write(stdunit,'(a)') title
     if (test_fv_diff) then
       write(stdunit,'(2(x,a,f20.16),x,a)') 'pRet=',pret,'pTrue=',ptrue,'WRONG!'
     else
       write(stdunit,'(2(x,a,f20.16))') 'pRet=',pret,'pTrue=',ptrue
     endif
   endif
test_fvlsq_slope()
logical function mom_neutral_diffusion::test_fvlsq_slope (logical, intent(in) verbose, real, intent(in) hkm1, real, intent(in) hk, real, intent(in) hkp1, real, intent(in) Skm1, real, intent(in) Sk, real, intent(in) Skp1, real, intent(in) Ptrue, character(len=*), intent(in) title) private
Returns true if a test of fvlsq_slope() fails, and conditionally writes results to stream.
Parameters
[in] verbose If true, write results to stdout
[in] hkm1 Left cell width
[in] hk Center cell width
[in] hkp1 Right cell width
[in] skm1 Left cell average value
[in] sk Center cell average value
[in] skp1 Right cell average value
[in] ptrue True answer (Pa)
[in] title Title for messages
Definition at line 1314 of file MOM_neutral_diffusion.F90.
References fvlsq_slope().
Referenced by neutral_diffusion_unit_tests().
   logical,          intent(in) :: verbose !< If true, write results to stdout
   real,             intent(in) :: hkm1  !< Left cell width
   real,             intent(in) :: hk    !< Center cell width
   real,             intent(in) :: hkp1  !< Right cell width
   real,             intent(in) :: skm1  !< Left cell average value
   real,             intent(in) :: sk    !< Center cell average value
   real,             intent(in) :: skp1  !< Right cell average value
   real,             intent(in) :: ptrue !< True answer (Pa)
   character(len=*), intent(in) :: title !< Title for messages
   ! Local variables
   integer :: stdunit
   real :: pret
   pret = fvlsq_slope(hkm1, hk, hkp1, skm1, sk, skp1)
   test_fvlsq_slope = (pret /= ptrue)
   if (test_fvlsq_slope .or. verbose) then
     stdunit = 6
     if (test_fvlsq_slope) stdunit = 0 ! In case of wrong results, write to error stream
     write(stdunit,'(a)') title
     if (test_fvlsq_slope) then
       write(stdunit,'(2(x,a,f20.16),x,a)') 'pRet=',pret,'pTrue=',ptrue,'WRONG!'
     else
       write(stdunit,'(2(x,a,f20.16))') 'pRet=',pret,'pTrue=',ptrue
     endif
   endif
test_ifndp()
logical function mom_neutral_diffusion::test_ifndp (logical, intent(in) verbose, real, intent(in) rhoNeg, real, intent(in) Pneg, real, intent(in) rhoPos, real, intent(in) Ppos, real, intent(in) Ptrue, character(len=*), intent(in) title) private
Returns true if a test of interpolate_for_nondim_position() fails, and conditionally writes results to stream.
Parameters
[in] verbose If true, write results to stdout
[in] rhoneg Lighter density (kg/m3)
[in] pneg Interface position of lighter density (Pa)
[in] rhopos Heavier density (kg/m3)
[in] ppos Interface position of heavier density (Pa)
[in] ptrue True answer (Pa)
[in] title Title for messages
Definition at line 1346 of file MOM_neutral_diffusion.F90.
References interpolate_for_nondim_position().
Referenced by neutral_diffusion_unit_tests().
   logical,          intent(in) :: verbose !< If true, write results to stdout
   real,             intent(in) :: rhoneg !< Lighter density (kg/m3)
   real,             intent(in) :: pneg   !< Interface position of lighter density (Pa)
   real,             intent(in) :: rhopos !< Heavier density (kg/m3)
   real,             intent(in) :: ppos   !< Interface position of heavier density (Pa)
   real,             intent(in) :: ptrue  !< True answer (Pa)
   character(len=*), intent(in) :: title  !< Title for messages
   ! Local variables
   integer :: stdunit
   real :: pret
   pret = interpolate_for_nondim_position(rhoneg, pneg, rhopos, ppos)
   test_ifndp = (pret /= ptrue)
   if (test_ifndp .or. verbose) then
     stdunit = 6
     if (test_ifndp) stdunit = 0 ! In case of wrong results, write to error stream
     write(stdunit,'(a)') title
     if (test_ifndp) then
       write(stdunit,'(4(x,a,f20.16),2(x,a,1pe22.15),x,a)') 'r1=',rhoneg,'p1=',pneg,'r2=',rhopos,'p2=',ppos,'pRet=',pret,'pTrue=',ptrue,'WRONG!'
     else
       write(stdunit,'(4(x,a,f20.16),2(x,a,1pe22.15))') 'r1=',rhoneg,'p1=',pneg,'r2=',rhopos,'p2=',ppos,'pRet=',pret,'pTrue=',ptrue
     endif
   endif
test_nsp()
logical function mom_neutral_diffusion::test_nsp (logical, intent(in) verbose, integer, intent(in) nk, integer, dimension(2*nk+2), intent(in) KoL, integer, dimension(2*nk+2), intent(in) KoR, real, dimension(2*nk+2), intent(in) pL, real, dimension(2*nk+2), intent(in) pR, real, dimension(2*nk+1), intent(in) hEff, integer, dimension(2*nk+2), intent(in) KoL0, integer, dimension(2*nk+2), intent(in) KoR0, real, dimension(2*nk+2), intent(in) pL0, real, dimension(2*nk+2), intent(in) pR0, real, dimension(2*nk+1), intent(in) hEff0, character(len=*), intent(in) title) private
Returns true if output of find_neutral_surface_positions() does not match correct values, and conditionally writes results to stream.
Parameters
[in] verbose If true, write results to stdout
[in] nk Number of layers
[in] kol Index of first left interface above neutral surface
[in] kor Index of first right interface above neutral surface
[in] pl Fractional position of neutral surface within layer KoL of left column
[in] pr Fractional position of neutral surface within layer KoR of right column
[in] heff Effective thickness between two neutral surfaces (Pa)
[in] kol0 Correct value for KoL
[in] kor0 Correct value for KoR
[in] pl0 Correct value for pL
[in] pr0 Correct value for pR
[in] heff0 Correct value for hEff
[in] title Title for messages
Definition at line 1442 of file MOM_neutral_diffusion.F90.
References compare_nsp_row().
Referenced by neutral_diffusion_unit_tests().
   logical,                    intent(in) :: verbose !< If true, write results to stdout
   integer,                    intent(in) :: nk    !< Number of layers
   integer, dimension(2*nk+2), intent(in) :: kol   !< Index of first left interface above neutral surface
   integer, dimension(2*nk+2), intent(in) :: kor   !< Index of first right interface above neutral surface
   real, dimension(2*nk+2),    intent(in) :: pl    !< Fractional position of neutral surface within layer KoL of left column
   real, dimension(2*nk+2),    intent(in) :: pr    !< Fractional position of neutral surface within layer KoR of right column
   real, dimension(2*nk+1),    intent(in) :: heff  !< Effective thickness between two neutral surfaces (Pa)
   integer, dimension(2*nk+2), intent(in) :: kol0  !< Correct value for KoL
   integer, dimension(2*nk+2), intent(in) :: kor0  !< Correct value for KoR
   real, dimension(2*nk+2),    intent(in) :: pl0   !< Correct value for pL
   real, dimension(2*nk+2),    intent(in) :: pr0   !< Correct value for pR
   real, dimension(2*nk+1),    intent(in) :: heff0 !< Correct value for hEff
   character(len=*),           intent(in) :: title !< Title for messages
   ! Local variables
   integer :: k, stdunit
   logical :: this_row_failed
   test_nsp = .false.
   do k = 1,2*nk+2
     test_nsp = test_nsp .or. compare_nsp_row(kol(k), kor(k), pl(k), pr(k), kol0(k), kor0(k), pl0(k), pr0(k))
     if (k < 2*nk+2) then
       if (heff(k) /= heff0(k)) test_nsp = .true.
     endif
   enddo
   if (test_nsp .or. verbose) then
     stdunit = 6
     if (test_nsp) stdunit = 0 ! In case of wrong results, write to error stream
     write(stdunit,'(a)') title
     do k = 1,2*nk+2
       this_row_failed = compare_nsp_row(kol(k), kor(k), pl(k), pr(k), kol0(k), kor0(k), pl0(k), pr0(k))
       if (this_row_failed) then
         write(stdunit,10) k,kol(k),pl(k),kor(k),pr(k),' <-- WRONG!'
         write(stdunit,10) k,kol0(k),pl0(k),kor0(k),pr0(k),' <-- should be this'
       else
         write(stdunit,10) k,kol(k),pl(k),kor(k),pr(k)
       endif
       if (k < 2*nk+2) then
         if (heff(k) /= heff0(k)) then
           write(stdunit,'(i3,8x,"layer hEff =",2(f20.16,a))') k,heff(k)," .neq. ",heff0(k),' <-- WRONG!'
         else
           write(stdunit,'(i3,8x,"layer hEff =",f20.16)') k,heff(k)
         endif
       endif
     enddo
   endif
 10 format("ks=",i3," kL=",i3," pL=",f20.16," kR=",i3," pR=",f20.16,a)
Variable Documentation
debug_this_module
logical, parameter mom_neutral_diffusion::debug_this_module = .false. private
Definition at line 59 of file MOM_neutral_diffusion.F90.
 logical, parameter :: debug_this_module = .false.
mdl
character(len=40) mom_neutral_diffusion::mdl = "MOM_neutral_diffusion"
Definition at line 57 of file MOM_neutral_diffusion.F90.
Referenced by neutral_diffusion_init().
 character(len=40)  :: mdl = "MOM_neutral_diffusion" ! module name