MOM6: coupler_util Module Reference
coupler_util Module Reference
Functions/Subroutines
subroutine, public extract_coupler_values (BC_struc, BC_index, BC_element, array_out, is, ie, js, je, conversion)
subroutine, public set_coupler_values (array_in, BC_struc, BC_index, BC_element, is, ie, js, je, conversion)
subroutine, public extract_coupler_values (BC_struc, BC_index, BC_element, array_out, is, ie, js, je, conversion)
Function/Subroutine Documentation
extract_coupler_values() [1/2]
subroutine, public coupler_util::extract_coupler_values (type(coupler_2d_bc_type), intent(in) BC_struc, integer, intent(in) BC_index, integer, intent(in) BC_element, real, dimension(:,:), intent(out) array_out, integer, intent(in), optional is, integer, intent(in), optional ie, integer, intent(in), optional js, integer, intent(in), optional je, real, intent(in), optional conversion)
Definition at line 37 of file coupler_util.F90.
References coupler_types_mod::ind_csurf, and mom_error_handler::mom_error().
   type(coupler_2d_bc_type), intent(in)  :: bc_struc
   integer,                  intent(in)  :: bc_index, bc_element
   real, dimension(:,:),     intent(out) :: array_out
   integer,        optional, intent(in)  :: is, ie, js, je
   real,           optional, intent(in)  :: conversion
 ! Arguments: BC_struc - The type from which the data is being extracted.
 !  (in)      BC_index - The boundary condition number being extracted.
 !  (in)      BC_element - The element of the boundary condition being extracted.
 !            This could be ind_csurf, ind_alpha, ind_flux or ind_deposition.
 !  (out)     array_out - The array being filled with the input values.
 !  (in, opt) is, ie, js, je - The i- and j- limits of array_out to be filled.
 !            These must match the size of the corresponding value array or an
 !            error message is issued.
 !  (in, opt) conversion - A number that every element is multiplied by, to
 !                         permit sign convention or unit conversion.
   real, pointer, dimension(:,:) :: array_in
   real :: conv
   integer :: i, j, is0, ie0, js0, je0, i_offset, j_offset
   if ((bc_element /= ind_flux) .and. (bc_element /= ind_alpha) .and. &
       (bc_element /= ind_csurf)) then
     call mom_error(fatal,"extract_coupler_values: Unrecognized BC_element.")
   endif
   ! These error messages should be made more explicit.
 !  if (.not.associated(BC_struc%bc(BC_index))) &
   if (.not.associated(bc_struc%bc)) &
     call mom_error(fatal,"extract_coupler_values: " // &
        "The requested boundary condition is not associated.")
 !  if (.not.associated(BC_struc%bc(BC_index)%field(BC_element))) &
   if (.not.associated(bc_struc%bc(bc_index)%field)) &
     call mom_error(fatal,"extract_coupler_values: " // &
        "The requested boundary condition element is not associated.")
   if (.not.associated(bc_struc%bc(bc_index)%field(bc_element)%values)) &
     call mom_error(fatal,"extract_coupler_values: " // &
        "The requested boundary condition value array is not associated.")
   array_in => bc_struc%bc(bc_index)%field(bc_element)%values
   if (present(is)) then ; is0 = is ; else ; is0 = lbound(array_out,1) ; endif
   if (present(ie)) then ; ie0 = ie ; else ; ie0 = ubound(array_out,1) ; endif
   if (present(js)) then ; js0 = js ; else ; js0 = lbound(array_out,2) ; endif
   if (present(je)) then ; je0 = je ; else ; je0 = ubound(array_out,2) ; endif
   conv = 1.0 ; if (present(conversion)) conv = conversion
   if (size(array_in,1) /= ie0 - is0 + 1) &
     call mom_error(fatal,"extract_coupler_values: Mismatch in i-size " // &
                    "between BC array and output array or computational domain.")
   if (size(array_in,2) /= je0 - js0 + 1) &
     call mom_error(fatal,"extract_coupler_values: Mismatch in i-size " // &
                    "between BC array and output array or computational domain.")
   i_offset = lbound(array_in,1) - is0
   j_offset = lbound(array_in,2) - js0
   do j=js0,je0 ; do i=is0,ie0
     array_out(i,j) = conv * array_in(i+i_offset,j+j_offset)
   enddo ; enddo
extract_coupler_values() [2/2]
subroutine, public coupler_util::extract_coupler_values (type(coupler_2d_bc_type), intent(in) BC_struc, integer, intent(in) BC_index, integer, intent(in) BC_element, real, dimension(:,:), intent(inout) array_out, integer, intent(in), optional is, integer, intent(in), optional ie, integer, intent(in), optional js, integer, intent(in), optional je, real, intent(in), optional conversion)
Definition at line 42 of file coupler_types.F90.
References mom_error_handler::mom_error().
   type(coupler_2d_bc_type), intent(in)    :: bc_struc
   integer,                  intent(in)    :: bc_index, bc_element
   real, dimension(:,:),     intent(inout) :: array_out
   integer,        optional, intent(in)    :: is, ie, js, je
   real,           optional, intent(in)    :: conversion
 ! Arguments: BC_struc - The type from which the data is being extracted.
 !  (in)      BC_index - The boundary condition number being extracted.
 !  (in)      BC_element - The element of the boundary condition being extracted.
 !            This could be ind_csurf, ind_alpha, ind_flux or ind_deposition.
 !  (out)     array_out - The array being filled with the input values.
 !  (in, opt) is, ie, js, je - The i- and j- limits of array_out to be filled.
 !            These must match the size of the corresponding value array or an
 !            error message is issued.
 !  (in, opt) conversion - A number that every element is multiplied by, to
 !                         permit sign convention or unit conversion.
   call mom_error(fatal,"The called version of extract_coupler_values does" // &
                  " nothing but issue this fatal error message.")
set_coupler_values()
subroutine public coupler_util::set_coupler_values (real, dimension(:,:), intent(in) array_in, type(coupler_2d_bc_type), intent(inout) BC_struc, integer, intent(in) BC_index, integer, intent(in) BC_element, integer, intent(in), optional is, integer, intent(in), optional ie, integer, intent(in), optional js, integer, intent(in), optional je, real, intent(in), optional conversion)
Definition at line 66 of file coupler_types.F90.
References mom_error_handler::mom_error().
Referenced by advection_test_tracer::advection_test_tracer_surface_state(), boundary_impulse_tracer::boundary_impulse_tracer_surface_state(), ideal_age_example::ideal_age_tracer_surface_state(), isomip_tracer::isomip_tracer_surface_state(), pseudo_salt_tracer::pseudo_salt_tracer_surface_state(), and user_tracer_example::user_tracer_surface_state().
   real, dimension(:,:),     intent(in)    :: array_in
   type(coupler_2d_bc_type), intent(inout) :: bc_struc
   integer,                  intent(in)    :: bc_index, bc_element
   integer,        optional, intent(in)    :: is, ie, js, je
   real,           optional, intent(in)    :: conversion
 ! Arguments: array_in - The array containing the values to load into the BC.
 !  (out)     BC_struc - The type into which the data is being loaded.
 !  (in)      BC_index - The boundary condition number being extracted.
 !  (in)      BC_element - The element of the boundary condition being extracted.
 !            This could be ind_csurf, ind_alpha, ind_flux or ind_deposition.
 !  (in, opt) is, ie, js, je - The i- and j- limits of array_out to be filled.
 !            These must match the size of the corresponding value array or an
 !            error message is issued.
 !  (in, opt) conversion - A number that every element is multiplied by, to
 !                         permit sign convention or unit conversion.
   call mom_error(fatal,"The called version of set_coupler_values does" // &
                  " nothing but issue this fatal error message.")