MOM6: regrid_consts Module Reference
regrid_consts Module Reference
Detailed Description
Contains constants for interpreting input parameters that control regridding.
Data Types
interface coordinateunits
interface state_dependent
Functions/Subroutines
integer function coordinatemode (string)
Parse a string parameter specifying the coordinate mode and return the appropriate enumerated integer.
character(len=16) function coordinateunitsi (coordMode)
Returns a string with the coordinate units associated with the enumerated integer,.
character(len=16) function coordinateunitss (string)
Returns a string with the coordinate units associated with the string defining the coordinate mode.
logical function state_dependent_char (string)
Returns true if the coordinate is dependent on the state density, returns false otherwise.
logical function state_dependent_int (mode)
Returns true if the coordinate is dependent on the state density, returns false otherwise.
Variables
integer, parameter regridding_num_types = 2
integer, parameter regridding_layer = 1
Layer mode.
integer, parameter regridding_zstar = 2
z* coordinates
integer, parameter regridding_rho = 3
Target interface densities.
integer, parameter regridding_sigma = 4
Sigma coordinates.
integer, parameter regridding_arbitrary = 5
Arbitrary coordinates.
integer, parameter regridding_hycom1 = 6
Simple HyCOM coordinates without BBL.
integer, parameter regridding_slight = 7
Stretched coordinates in the.
integer, parameter regridding_sigma_shelf_zstar = 8
z* coordinates at the bottom, sigma-near the top lightest water, isopycnal below
integer, parameter regridding_adaptive = 9
character(len= *), parameter regridding_layer_string = "LAYER"
Layer string.
character(len= *), parameter regridding_zstar_string_old = "Z*"
z* string (legacy name)
character(len= *), parameter regridding_zstar_string = "ZSTAR"
z* string
character(len= *), parameter regridding_rho_string = "RHO"
Rho string.
character(len= *), parameter regridding_sigma_string = "SIGMA"
Sigma string.
character(len= *), parameter regridding_arbitrary_string = "ARB"
Arbitrary coordinates.
character(len= *), parameter regridding_hycom1_string = "HYCOM1"
Hycom string.
character(len= *), parameter regridding_slight_string = "SLIGHT"
Hybrid S-rho string.
character(len= *), parameter regridding_sigma_shelf_zstar_string = "SIGMA_SHELF_ZSTAR"
Hybrid z*/sigma.
character(len= *), parameter regridding_adaptive_string = "ADAPTIVE"
character(len= *), parameter default_coordinate_mode = REGRIDDING_LAYER_STRING
Default coordinate mode.
integer, dimension(regridding_num_types), parameter vertical_coords = (/ REGRIDDING_LAYER, REGRIDDING_ZSTAR /)
character(len= *), dimension(regridding_num_types), parameter vertical_coord_strings = (/ REGRIDDING_LAYER_STRING, REGRIDDING_ZSTAR_STRING /)
Function/Subroutine Documentation
coordinatemode()
integer function regrid_consts::coordinatemode (character(len=*), intent(in) string)
Parse a string parameter specifying the coordinate mode and return the appropriate enumerated integer.
Returns
Enumerated integer indicating coordinate mode
Parameters
[in] string String to indicate coordinate mode
Definition at line 65 of file regrid_consts.F90.
References mom_error_handler::mom_error(), regridding_adaptive, regridding_adaptive_string, regridding_arbitrary, regridding_arbitrary_string, regridding_hycom1, regridding_hycom1_string, regridding_layer, regridding_layer_string, regridding_rho, regridding_rho_string, regridding_sigma, regridding_sigma_shelf_zstar, regridding_sigma_shelf_zstar_string, regridding_sigma_string, regridding_slight, regridding_slight_string, regridding_zstar, regridding_zstar_string, regridding_zstar_string_old, and mom_string_functions::uppercase().
Referenced by coordinateunitss(), mom_diag_remap::diag_remap_configure_axes(), mom_diag_remap::diag_remap_do_remap(), mom_diag_remap::diag_remap_init(), mom_diag_remap::diag_remap_update(), and state_dependent_char().
   integer :: coordinatemode !< Enumerated integer indicating coordinate mode
   character(len=*), intent(in) :: string !< String to indicate coordinate mode
   select case ( uppercase(trim(string)) )
     case (trim(regridding_layer_string)); coordinatemode = regridding_layer
     case (trim(regridding_zstar_string)); coordinatemode = regridding_zstar
     case (trim(regridding_zstar_string_old)); coordinatemode = regridding_zstar
     case (trim(regridding_rho_string));   coordinatemode = regridding_rho
     case (trim(regridding_sigma_string)); coordinatemode = regridding_sigma
     case (trim(regridding_hycom1_string)); coordinatemode = regridding_hycom1
     case (trim(regridding_slight_string)); coordinatemode = regridding_slight
     case (trim(regridding_arbitrary_string)); coordinatemode = regridding_arbitrary
     case (trim(regridding_sigma_shelf_zstar_string)); coordinatemode = regridding_sigma_shelf_zstar
     case (trim(regridding_adaptive_string)); coordinatemode = regridding_adaptive
     case default ; call mom_error(fatal, "coordinateMode: "//&
        "Unrecognized choice of coordinate ("//trim(string)//").")
   end select
coordinateunitsi()
character(len=16) function regrid_consts::coordinateunitsi (integer, intent(in) coordMode)
Returns a string with the coordinate units associated with the enumerated integer,.
Returns
Units of coordinate
Parameters
[in] coordmode Coordinate mode
Definition at line 86 of file regrid_consts.F90.
References mom_error_handler::mom_error(), regridding_adaptive, regridding_hycom1, regridding_layer, regridding_rho, regridding_sigma, regridding_sigma_shelf_zstar, regridding_slight, and regridding_zstar.
Referenced by coordinateunitss().
   character(len=16) :: coordinateunitsi !< Units of coordinate
   integer, intent(in) :: coordmode !< Coordinate mode
   select case ( coordmode )
     case (regridding_layer); coordinateunitsi = "kg m^-3"
     case (regridding_zstar); coordinateunitsi = "m"
     case (regridding_sigma_shelf_zstar); coordinateunitsi = "m"
     case (regridding_rho);   coordinateunitsi = "kg m^-3"
     case (regridding_sigma); coordinateunitsi = "Non-dimensional"
     case (regridding_hycom1); coordinateunitsi = "m"
     case (regridding_slight); coordinateunitsi = "m"
     case (regridding_adaptive); coordinateunitsi = "m"
     case default ; call mom_error(fatal, "coordinateUnts: "//&
        "Unrecognized coordinate mode.")
   end select
coordinateunitss()
character(len=16) function regrid_consts::coordinateunitss (character(len=*), intent(in) string)
Returns a string with the coordinate units associated with the string defining the coordinate mode.
Returns
Units of coordinate
Parameters
[in] string Coordinate mode
Definition at line 105 of file regrid_consts.F90.
References coordinatemode(), and coordinateunitsi().
   character(len=16) :: coordinateunitss !< Units of coordinate
   character(len=*), intent(in) :: string !< Coordinate mode
   integer :: coordmode
   coordmode = coordinatemode(string)
   coordinateunitss = coordinateunitsi(coordmode)
state_dependent_char()
logical function regrid_consts::state_dependent_char (character(len=*), intent(in) string)
Returns true if the coordinate is dependent on the state density, returns false otherwise.
Parameters
[in] string String to indicate coordinate mode
Definition at line 114 of file regrid_consts.F90.
References coordinatemode(), and state_dependent_int().
   character(len=*), intent(in) :: string !< String to indicate coordinate mode
   state_dependent_char = state_dependent_int( coordinatemode(string) )
state_dependent_int()
logical function regrid_consts::state_dependent_int (integer, intent(in) mode)
Returns true if the coordinate is dependent on the state density, returns false otherwise.
Parameters
[in] mode Coordinate mode
Definition at line 122 of file regrid_consts.F90.
References mom_error_handler::mom_error(), regridding_adaptive, regridding_hycom1, regridding_layer, regridding_rho, regridding_sigma, regridding_sigma_shelf_zstar, regridding_slight, and regridding_zstar.
Referenced by state_dependent_char().
   integer, intent(in) :: mode !< Coordinate mode
   select case ( mode )
     case (regridding_layer); state_dependent_int = .true.
     case (regridding_zstar); state_dependent_int = .false.
     case (regridding_sigma_shelf_zstar); state_dependent_int = .false.
     case (regridding_rho);   state_dependent_int = .true.
     case (regridding_sigma); state_dependent_int = .false.
     case (regridding_hycom1); state_dependent_int = .true.
     case (regridding_slight); state_dependent_int = .true.
     case (regridding_adaptive); state_dependent_int = .true.
     case default ; call mom_error(fatal, "state_dependent: "//&
        "Unrecognized choice of coordinate.")
   end select
Variable Documentation
default_coordinate_mode
character(len=*), parameter regrid_consts::default_coordinate_mode = REGRIDDING_LAYER_STRING
Default coordinate mode.
Definition at line 36 of file regrid_consts.F90.
 character(len=*), parameter :: DEFAULT_COORDINATE_MODE = REGRIDDING_LAYER_STRING !< Default coordinate mode
regridding_adaptive
integer, parameter regrid_consts::regridding_adaptive = 9
Definition at line 24 of file regrid_consts.F90.
Referenced by coordinatemode(), coordinateunitsi(), mom_regridding::initialize_regridding(), mom_regridding::regridding_main(), and state_dependent_int().
 integer, parameter :: regridding_adaptive = 9
regridding_adaptive_string
character(len=*), parameter regrid_consts::regridding_adaptive_string = "ADAPTIVE"
Definition at line 35 of file regrid_consts.F90.
Referenced by coordinatemode().
 character(len=*), parameter :: REGRIDDING_ADAPTIVE_STRING = "ADAPTIVE"
regridding_arbitrary
integer, parameter regrid_consts::regridding_arbitrary = 5
Arbitrary coordinates.
Definition at line 19 of file regrid_consts.F90.
Referenced by coordinatemode().
 integer, parameter :: regridding_arbitrary = 5      !< Arbitrary coordinates
regridding_arbitrary_string
character(len=*), parameter regrid_consts::regridding_arbitrary_string = "ARB"
Arbitrary coordinates.
Definition at line 31 of file regrid_consts.F90.
Referenced by coordinatemode().
 character(len=*), parameter :: REGRIDDING_ARBITRARY_STRING = "ARB" !< Arbitrary coordinates
regridding_hycom1
integer, parameter regrid_consts::regridding_hycom1 = 6
Simple HyCOM coordinates without BBL.
Definition at line 20 of file regrid_consts.F90.
Referenced by coordinatemode(), coordinateunitsi(), mom_regridding::initialize_regridding(), mom_regridding::regridding_main(), and state_dependent_int().
 integer, parameter :: regridding_hycom1    = 6      !< Simple HyCOM coordinates without BBL
regridding_hycom1_string
character(len=*), parameter regrid_consts::regridding_hycom1_string = "HYCOM1"
Hycom string.
Definition at line 32 of file regrid_consts.F90.
Referenced by coordinatemode().
 character(len=*), parameter :: REGRIDDING_HYCOM1_STRING = "HYCOM1" !< Hycom string
regridding_layer
integer, parameter regrid_consts::regridding_layer = 1
Layer mode.
Definition at line 15 of file regrid_consts.F90.
Referenced by coordinatemode(), coordinateunitsi(), and state_dependent_int().
 integer, parameter :: regridding_layer     = 1      !< Layer mode
regridding_layer_string
character(len=*), parameter regrid_consts::regridding_layer_string = "LAYER"
Layer string.
Definition at line 26 of file regrid_consts.F90.
Referenced by coordinatemode().
 character(len=*), parameter :: REGRIDDING_LAYER_STRING = "LAYER"   !< Layer string
regridding_num_types
integer, parameter regrid_consts::regridding_num_types = 2
Definition at line 11 of file regrid_consts.F90.
 integer, parameter :: regridding_num_types  = 2
regridding_rho
integer, parameter regrid_consts::regridding_rho = 3
Target interface densities.
Definition at line 17 of file regrid_consts.F90.
Referenced by adjustment_initialization::adjustment_initialize_temperature_salinity(), adjustment_initialization::adjustment_initialize_thickness(), coordinatemode(), coordinateunitsi(), dome2d_initialization::dome2d_initialize_temperature_salinity(), dome2d_initialization::dome2d_initialize_thickness(), rossby_front_2d_initialization::rossby_front_initialize_thickness(), seamount_initialization::seamount_initialize_temperature_salinity(), seamount_initialization::seamount_initialize_thickness(), and state_dependent_int().
 integer, parameter :: regridding_rho       = 3      !< Target interface densities
regridding_rho_string
character(len=*), parameter regrid_consts::regridding_rho_string = "RHO"
Rho string.
Definition at line 29 of file regrid_consts.F90.
Referenced by coordinatemode().
 character(len=*), parameter :: REGRIDDING_RHO_STRING   = "RHO"     !< Rho string
regridding_sigma
integer, parameter regrid_consts::regridding_sigma = 4
Sigma coordinates.
Definition at line 18 of file regrid_consts.F90.
Referenced by adjustment_initialization::adjustment_initialize_temperature_salinity(), adjustment_initialization::adjustment_initialize_thickness(), coordinatemode(), coordinateunitsi(), dome2d_initialization::dome2d_initialize_temperature_salinity(), dome2d_initialization::dome2d_initialize_thickness(), rossby_front_2d_initialization::rossby_front_initialize_thickness(), seamount_initialization::seamount_initialize_temperature_salinity(), seamount_initialization::seamount_initialize_thickness(), and state_dependent_int().
 integer, parameter :: regridding_sigma     = 4      !< Sigma coordinates
regridding_sigma_shelf_zstar
integer, parameter regrid_consts::regridding_sigma_shelf_zstar = 8
z* coordinates at the bottom, sigma-near the top lightest water, isopycnal below
Definition at line 22 of file regrid_consts.F90.
Referenced by coordinatemode(), coordinateunitsi(), isomip_initialization::isomip_initialize_sponges(), isomip_initialization::isomip_initialize_temperature_salinity(), isomip_initialization::isomip_initialize_thickness(), and state_dependent_int().
 integer, parameter :: regridding_sigma_shelf_zstar = 8   !< z* coordinates at the bottom, sigma-near the top
regridding_sigma_shelf_zstar_string
character(len=*), parameter regrid_consts::regridding_sigma_shelf_zstar_string = "SIGMA_SHELF_ZSTAR"
Hybrid z*/sigma.
Definition at line 34 of file regrid_consts.F90.
Referenced by coordinatemode().
 character(len=*), parameter :: REGRIDDING_SIGMA_SHELF_ZSTAR_STRING = "SIGMA_SHELF_ZSTAR" !< Hybrid z*/sigma
regridding_sigma_string
character(len=*), parameter regrid_consts::regridding_sigma_string = "SIGMA"
Sigma string.
Definition at line 30 of file regrid_consts.F90.
Referenced by coordinatemode().
 character(len=*), parameter :: REGRIDDING_SIGMA_STRING = "SIGMA"   !< Sigma string
regridding_slight
integer, parameter regrid_consts::regridding_slight = 7
Stretched coordinates in the.
Definition at line 21 of file regrid_consts.F90.
Referenced by coordinatemode(), coordinateunitsi(), mom_regridding::initialize_regridding(), mom_regridding::regridding_main(), and state_dependent_int().
 integer, parameter :: regridding_slight    = 7      !< Stretched coordinates in the
regridding_slight_string
character(len=*), parameter regrid_consts::regridding_slight_string = "SLIGHT"
Hybrid S-rho string.
Definition at line 33 of file regrid_consts.F90.
Referenced by coordinatemode().
 character(len=*), parameter :: REGRIDDING_SLIGHT_STRING = "SLIGHT" !< Hybrid S-rho string
regridding_zstar
integer, parameter regrid_consts::regridding_zstar = 2
z* coordinates
Definition at line 16 of file regrid_consts.F90.
Referenced by coordinatemode(), coordinateunitsi(), and state_dependent_int().
 integer, parameter :: regridding_zstar     = 2      !< z* coordinates
regridding_zstar_string
character(len=*), parameter regrid_consts::regridding_zstar_string = "ZSTAR"
z* string
Definition at line 28 of file regrid_consts.F90.
Referenced by coordinatemode().
 character(len=*), parameter :: REGRIDDING_ZSTAR_STRING = "ZSTAR"   !< z* string
regridding_zstar_string_old
character(len=*), parameter regrid_consts::regridding_zstar_string_old = "Z*"
z* string (legacy name)
Definition at line 27 of file regrid_consts.F90.
Referenced by coordinatemode().
 character(len=*), parameter :: REGRIDDING_ZSTAR_STRING_OLD = "Z*"  !< z* string (legacy name)
vertical_coord_strings
character(len=*), dimension(regridding_num_types), parameter regrid_consts::vertical_coord_strings = (/ REGRIDDING_LAYER_STRING, REGRIDDING_ZSTAR_STRING /)
Definition at line 44 of file regrid_consts.F90.
 character(len=*), dimension(REGRIDDING_NUM_TYPES), parameter :: vertical_coord_strings = &
   (/ regridding_layer_string, regridding_zstar_string /)
vertical_coords
integer, dimension(regridding_num_types), parameter regrid_consts::vertical_coords = (/ REGRIDDING_LAYER, REGRIDDING_ZSTAR /)
Definition at line 38 of file regrid_consts.F90.
 integer, dimension(REGRIDDING_NUM_TYPES), parameter :: vertical_coords = &
   (/ regridding_layer, regridding_zstar /)