MOM6: baroclinic_zone_initialization Module Reference
baroclinic_zone_initialization Module Reference
Detailed Description
Initial conditions for an idealized baroclinic zone.
Description of the baroclinic zone initial conditions
yada yada yada
Functions/Subroutines
subroutine bcz_params (G, param_file, S_ref, dSdz, delta_S, dSdx, T_ref, dTdz, delta_T, dTdx, L_zone, just_read_params)
Reads the parameters unique to this module.
subroutine, public baroclinic_zone_init_temperature_salinity (T, S, h, G, param_file, just_read_params)
Initialization of temperature and salinity with the baroclinic zone initial conditions.
Variables
character(len=40) mdl = "baroclinic_zone_initialization"
This module's name.
Function/Subroutine Documentation
baroclinic_zone_init_temperature_salinity()
subroutine, public baroclinic_zone_initialization::baroclinic_zone_init_temperature_salinity (real, dimension(szi_(g),szj_(g), szk_(g)), intent(out) T, real, dimension(szi_(g),szj_(g), szk_(g)), intent(out) S, real, dimension(szi_(g),szj_(g), szk_(g)), intent(in) h, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, logical, intent(in), optional just_read_params)
Initialization of temperature and salinity with the baroclinic zone initial conditions.
Parameters
[in] g Grid structure
[out] t Potential temperature [deg C]
[out] s Salinity [ppt]
[in] h Thickness
[in] param_file Parameter file handle
[in] just_read_params If present and true, this call will only read parameters without changing h.
Definition at line 70 of file baroclinic_zone_initialization.F90.
References bcz_params().
Referenced by mom_state_initialization::mom_initialize_state().
   type(ocean_grid_type),                     intent(in)  :: g  !< Grid structure
   real, dimension(SZI_(G),SZJ_(G), SZK_(G)), intent(out) :: t  !< Potential temperature [deg C]
   real, dimension(SZI_(G),SZJ_(G), SZK_(G)), intent(out) :: s  !< Salinity [ppt]
   real, dimension(SZI_(G),SZJ_(G), SZK_(G)), intent(in)  :: h  !< Thickness
   type(param_file_type),                     intent(in)  :: param_file  !< Parameter file handle
   logical,       optional, intent(in)  :: just_read_params !< If present and true, this call will
                                                       !! only read parameters without changing h.
   integer   :: i, j, k, is, ie, js, je, nz
   real      :: t_ref, dtdz, dtdx, delta_t ! Parameters describing temperature distribution
   real      :: s_ref, dsdz, dsdx, delta_s ! Parameters describing salinity distribution
   real      :: l_zone ! Width of baroclinic zone
   real      :: zc, zi, x, xd, xs, y, yd, fn
   real      :: pi                   ! 3.1415926... calculated as 4*atan(1)
   logical :: just_read    ! If true, just read parameters but set nothing.
   is = g%isc ; ie = g%iec ; js = g%jsc ; je = g%jec ; nz = g%ke
   just_read = .false. ; if (present(just_read_params)) just_read = just_read_params
   call bcz_params(g, param_file, s_ref, dsdz, delta_s, dsdx, t_ref, dtdz, delta_t, dtdx, l_zone, just_read_params)
   if (just_read) return ! All run-time parameters have been read, so return.
   t(:,:,:) = 0.
   s(:,:,:) = 0.
   pi = 4.*atan(1.)
   do j = g%jsc,g%jec ; do i = g%isc,g%iec
     zi = -g%bathyT(i,j)
     x = g%geoLonT(i,j) - (g%west_lon + 0.5*g%len_lon) ! Relative to center of domain
     xd = x / g%len_lon ! -1/2 < xd 1/2
     y = g%geoLatT(i,j) - (g%south_lat + 0.5*g%len_lat) ! Relative to center of domain
     yd = y / g%len_lat ! -1/2 < yd 1/2
     if (l_zone/=0.) then
       xs = min(1., max(-1., x/l_zone)) ! -1 < ys < 1
       fn = sin((0.5*pi)*xs)
     else
       xs = sign(1., x) ! +/- 1
       fn = xs
     endif
     do k = nz, 1, -1
       zc = zi + 0.5*h(i,j,k)          ! Position of middle of cell
       zi = zi + h(i,j,k)              ! Top interface position
       t(i,j,k) = t_ref + dtdz * zc  & ! Linear temperature stratification
                  + dtdx * x         & ! Linear gradient
                  + delta_t * fn       ! Smooth fn of width L_zone
       s(i,j,k) = s_ref + dsdz * zc  & ! Linear temperature stratification
                  + dsdx * x         & ! Linear gradient
                  + delta_s * fn       ! Smooth fn of width L_zone
     enddo
   end do ; end do
bcz_params()
subroutine baroclinic_zone_initialization::bcz_params (type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, real, intent(out) S_ref, real, intent(out) dSdz, real, intent(out) delta_S, real, intent(out) dSdx, real, intent(out) T_ref, real, intent(out) dTdz, real, intent(out) delta_T, real, intent(out) dTdx, real, intent(out) L_zone, logical, intent(in), optional just_read_params) private
Reads the parameters unique to this module.
Parameters
[in] g Grid structure
[in] param_file Parameter file handle
[out] s_ref Reference salinity (ppt)
[out] dsdz Salinity stratification (ppt/m)
[out] delta_s Salinity difference across baroclinic zone (ppt)
[out] dsdx Linear salinity gradient (ppt/m)
[out] t_ref Reference temperature (ppt)
[out] dtdz Temperature stratification (ppt/m)
[out] delta_t Temperature difference across baroclinic zone (ppt)
[out] dtdx Linear temperature gradient (ppt/m)
[out] l_zone Width of baroclinic zone (m)
[in] just_read_params If present and true, this call will only read parameters without changing h.
Definition at line 25 of file baroclinic_zone_initialization.F90.
References mom_file_parser::closeparameterblock(), mdl, and mom_file_parser::openparameterblock().
Referenced by baroclinic_zone_init_temperature_salinity().
   type(ocean_grid_type), intent(in)  :: g          !< Grid structure
   type(param_file_type), intent(in)  :: param_file !< Parameter file handle
   real,                  intent(out) :: s_ref      !< Reference salinity (ppt)
   real,                  intent(out) :: dsdz       !< Salinity stratification (ppt/m)
   real,                  intent(out) :: delta_s    !< Salinity difference across baroclinic zone (ppt)
   real,                  intent(out) :: dsdx       !< Linear salinity gradient (ppt/m)
   real,                  intent(out) :: t_ref      !< Reference temperature (ppt)
   real,                  intent(out) :: dtdz       !< Temperature stratification (ppt/m)
   real,                  intent(out) :: delta_t    !< Temperature difference across baroclinic zone (ppt)
   real,                  intent(out) :: dtdx       !< Linear temperature gradient (ppt/m)
   real,                  intent(out) :: l_zone     !< Width of baroclinic zone (m)
   logical,     optional, intent(in)  :: just_read_params !< If present and true, this call will
                                                       !! only read parameters without changing h.
   logical :: just_read    ! If true, just read parameters but set nothing.
   just_read = .false. ; if (present(just_read_params)) just_read = just_read_params
   if (.not.just_read) &
     call log_version(param_file, mdl, version, 'Initialization of an analytic baroclinic zone')
   call openparameterblock(param_file,'BCZIC')
   call get_param(param_file, mdl, "S_REF", s_ref, 'Reference salinity', units='ppt', &
                  default=35., do_not_log=just_read)
   call get_param(param_file, mdl,"DSDZ",dsdz,'Salinity stratification',units='ppt/m', &
                  default=0.0, do_not_log=just_read)
   call get_param(param_file, mdl,"DELTA_S",delta_s,'Salinity difference across baroclinic zone', &
                  units='ppt', default=0.0, do_not_log=just_read)
   call get_param(param_file, mdl,"DSDX",dsdx,'Meridional salinity difference', &
                  units='ppt/'//trim(g%x_axis_units), default=0.0, do_not_log=just_read)
   call get_param(param_file, mdl,"T_REF",t_ref,'Reference temperature',units='C', &
                  default=10., do_not_log=just_read)
   call get_param(param_file, mdl,"DTDZ",dtdz,'Temperature stratification',units='C/m', &
                  default=0.0, do_not_log=just_read)
   call get_param(param_file, mdl,"DELTA_T",delta_t,'Temperature difference across baroclinic zone', &
                  units='C', default=0.0, do_not_log=just_read)
   call get_param(param_file, mdl,"DTDX",dtdx,'Meridional temperature difference', &
                  units='C/'//trim(g%x_axis_units), default=0.0, do_not_log=just_read)
   call get_param(param_file, mdl,"L_ZONE",l_zone,'Width of baroclinic zone', &
                  units=g%x_axis_units, default=0.5*g%len_lat, do_not_log=just_read)
   call closeparameterblock(param_file)
Variable Documentation
mdl
character(len=40) baroclinic_zone_initialization::mdl = "baroclinic_zone_initialization" private
This module's name.
Definition at line 16 of file baroclinic_zone_initialization.F90.
Referenced by bcz_params().
 character(len=40) :: mdl = "baroclinic_zone_initialization" !< This module's name.