MOM6: user_tracer_example Module Reference
user_tracer_example Module Reference
Data Types
type p3d
type user_tracer_example_cs
Functions/Subroutines
logical function, public user_register_tracer_example (HI, GV, param_file, CS, tr_Reg, restart_CS)
subroutine, public user_initialize_tracer (restart, day, G, GV, h, diag, OBC, CS, sponge_CSp, diag_to_Z_CSp)
subroutine, public tracer_column_physics (h_old, h_new, ea, eb, fluxes, dt, G, GV, CS)
integer function, public user_tracer_stock (h, stocks, G, GV, CS, names, units, stock_index)
subroutine, public user_tracer_surface_state (state, h, G, CS)
subroutine, public user_tracer_example_end (CS)
Variables
integer, parameter ntr = 1
Function/Subroutine Documentation
tracer_column_physics()
subroutine, public user_tracer_example::tracer_column_physics (real, dimension(szi_(g),szj_(g),szk_(g)), intent(in) h_old, real, dimension(szi_(g),szj_(g),szk_(g)), intent(in) h_new, real, dimension(szi_(g),szj_(g),szk_(g)), intent(in) ea, real, dimension(szi_(g),szj_(g),szk_(g)), intent(in) eb, type(forcing), intent(in) fluxes, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, type(user_tracer_example_cs), pointer CS)
Parameters
[in] g The ocean's grid structure
[in] gv The ocean's vertical grid structure
[in] dt The amount of time covered by this call, in s
Definition at line 387 of file tracer_example.F90.
References ntr.
   type(ocean_grid_type),              intent(in) :: g    !< The ocean's grid structure
   type(verticalgrid_type),            intent(in) :: gv   !< The ocean's vertical grid structure
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)), intent(in) :: h_old, h_new, ea, eb
   type(forcing),                      intent(in) :: fluxes
   real,                               intent(in) :: dt   !< The amount of time covered by this call, in s
   type(user_tracer_example_cs),       pointer    :: cs
 !   This subroutine applies diapycnal diffusion and any other column
 ! tracer physics or chemistry to the tracers from this file.
 ! This is a simple example of a set of advected passive tracers.
 ! Arguments: h_old -  Layer thickness before entrainment, in m or kg m-2.
 !  (in)      h_new -  Layer thickness after entrainment, in m or kg m-2.
 !  (in)      ea - an array to which the amount of fluid entrained
 !                 from the layer above during this call will be
 !                 added, in m or kg m-2.
 !  (in)      eb - an array to which the amount of fluid entrained
 !                 from the layer below during this call will be
 !                 added, in m or kg m-2.
 !  (in)      fluxes - A structure containing pointers to any possible
 !                     forcing fields.  Unused fields have NULL ptrs.
 !  (in)      dt - The amount of time covered by this call, in s.
 !  (in)      G - The ocean's grid structure.
 !  (in)      GV - The ocean's vertical grid structure.
 !  (in)      CS - The control structure returned by a previous call to
 !                 USER_register_tracer_example.
 !
 ! The arguments to this subroutine are redundant in that
 !     h_new[k] = h_old[k] + ea[k] - eb[k-1] + eb[k] - ea[k+1]
   real :: hold0(szi_(g))       ! The original topmost layer thickness,
                                ! with surface mass fluxes added back, m.
   real :: b1(szi_(g))          ! b1 and c1 are variables used by the
   real :: c1(szi_(g),szk_(g))  ! tridiagonal solver.
   real :: d1(szi_(g))          ! d1=1-c1 is used by the tridiagonal solver.
   real :: h_neglect            ! A thickness that is so small it is usually lost
                                ! in roundoff and can be neglected, in m.
   real :: b_denom_1 ! The first term in the denominator of b1, in m or kg m-2.
   integer :: i, j, k, is, ie, js, je, nz, m
 ! The following array (trdc) determines the behavior of the tracer
 ! diapycnal advection.  The first element is 1 if tracers are
 ! passively advected.  The second and third are the concentrations
 ! to which downwelling and upwelling water are set, respectively.
 ! For most (normal) tracers, the appropriate vales are {1,0,0}.
   real :: trdc(3)
 !   Uncomment the following line to dye both upwelling and downwelling.
 ! data trdc / 0.0,1.0,1.0 /
 !   Uncomment the following line to dye downwelling.
 ! data trdc / 0.0,1.0,0.0 /
 !   Uncomment the following line to dye upwelling.
 ! data trdc / 0.0,0.0,1.0 /
 !   Uncomment the following line for tracer concentrations to be set
 ! to zero in any diapycnal motions.
 ! data trdc / 0.0,0.0,0.0 /
 !   Uncomment the following line for most "physical" tracers, which
 ! are advected diapycnally in the usual manner.
   data trdc / 1.0,0.0,0.0 /
   is = g%isc ; ie = g%iec ; js = g%jsc ; je = g%jec ; nz = gv%ke
   if (.not.associated(cs)) return
   h_neglect = gv%H_subroundoff
   do j=js,je
     do i=is,ie
 !   The following line is appropriate for quantities like salinity
 ! that are left behind by evaporation, and any surface fluxes would
 ! be explicitly included in the flux structure.
       hold0(i) = h_old(i,j,1)
 !   The following line is appropriate for quantities like temperature
 ! that can be assumed to have the same concentration in evaporation
 ! as they had in the water.  The explicit surface fluxes here would
 ! reflect differences in concentration from the ambient water, not
 ! the absolute fluxes.
   !   hold0(i) = h_old(i,j,1) + ea(i,j,1)
       b_denom_1 = h_old(i,j,1) + ea(i,j,1) + h_neglect
       b1(i) = 1.0 / (b_denom_1 + eb(i,j,1))
 !       d1(i) = b_denom_1 * b1(i)
       d1(i) = trdc(1) * (b_denom_1 * b1(i)) + (1.0 - trdc(1))
       do m=1,ntr
         cs%tr(i,j,1,m) = b1(i)*(hold0(i)*cs%tr(i,j,1,m) + trdc(3)*eb(i,j,1))
  !      Add any surface tracer fluxes to the preceding line.
       enddo
     enddo
     do k=2,nz ; do i=is,ie
       c1(i,k) = trdc(1) * eb(i,j,k-1) * b1(i)
       b_denom_1 = h_old(i,j,k) + d1(i)*ea(i,j,k) + h_neglect
       b1(i) = 1.0 / (b_denom_1 + eb(i,j,k))
       d1(i) = trdc(1) * (b_denom_1 * b1(i)) + (1.0 - trdc(1))
       do m=1,ntr
         cs%tr(i,j,k,m) = b1(i) * (h_old(i,j,k)*cs%tr(i,j,k,m) + &
                  ea(i,j,k)*(trdc(1)*cs%tr(i,j,k-1,m)+trdc(2)) + &
                  eb(i,j,k)*trdc(3))
       enddo
     enddo ; enddo
     do m=1,ntr ; do k=nz-1,1,-1 ; do i=is,ie
       cs%tr(i,j,k,m) = cs%tr(i,j,k,m) + c1(i,k+1)*cs%tr(i,j,k+1,m)
     enddo ; enddo ; enddo
   enddo
   if (cs%mask_tracers) then
     do m = 1,ntr ; if (cs%id_tracer(m) > 0) then
       do k=1,nz ; do j=js,je ; do i=is,ie
         if (h_new(i,j,k) < 1.1*gv%Angstrom) then
           cs%tr_aux(i,j,k,m) = cs%land_val(m)
         else
           cs%tr_aux(i,j,k,m) = cs%tr(i,j,k,m)
         endif
       enddo ; enddo ; enddo
     endif ; enddo
   endif
   do m=1,ntr
     if (cs%mask_tracers) then
       if (cs%id_tracer(m)>0) &
         call post_data(cs%id_tracer(m),cs%tr_aux(:,:,:,m),cs%diag)
     else
       if (cs%id_tracer(m)>0) &
         call post_data(cs%id_tracer(m),cs%tr(:,:,:,m),cs%diag)
     endif
     if (cs%id_tr_adx(m)>0) &
       call post_data(cs%id_tr_adx(m),cs%tr_adx(m)%p(:,:,:),cs%diag)
     if (cs%id_tr_ady(m)>0) &
       call post_data(cs%id_tr_ady(m),cs%tr_ady(m)%p(:,:,:),cs%diag)
     if (cs%id_tr_dfx(m)>0) &
       call post_data(cs%id_tr_dfx(m),cs%tr_dfx(m)%p(:,:,:),cs%diag)
     if (cs%id_tr_dfy(m)>0) &
       call post_data(cs%id_tr_dfy(m),cs%tr_dfy(m)%p(:,:,:),cs%diag)
   enddo
user_initialize_tracer()
subroutine, public user_tracer_example::user_initialize_tracer (logical, intent(in) restart, type(time_type), intent(in), target day, type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, real, dimension(g %isd: g %ied, g %jsd: g %jed, g %ke), intent(in) h, type(diag_ctrl), intent(in), target diag, type(ocean_obc_type), pointer OBC, type(user_tracer_example_cs), pointer CS, type(sponge_cs), pointer sponge_CSp, type(diag_to_z_cs), pointer diag_to_Z_CSp)
Parameters
[in] g The ocean's grid structure
[in] gv The ocean's vertical grid structure
[in] h Layer thicknesses, in H (usually m or kg m-2)
Definition at line 208 of file tracer_example.F90.
References mom_tracer_registry::add_tracer_diagnostics(), mom_tracer_registry::add_tracer_obc_values(), mom_error_handler::mom_error(), ntr, mom_io::query_vardesc(), mom_diag_to_z::register_z_tracer(), and mom_sponge::set_up_sponge_field().
   logical,                            intent(in) :: restart
   type(time_type), target,            intent(in) :: day
   type(ocean_grid_type),              intent(in) :: g    !< The ocean's grid structure
   type(verticalgrid_type),            intent(in) :: gv   !< The ocean's vertical grid structure
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)), &
                                       intent(in) :: h    !< Layer thicknesses, in H (usually m or kg m-2)
   type(diag_ctrl), target,            intent(in) :: diag
   type(ocean_obc_type),               pointer    :: obc
   type(user_tracer_example_cs),       pointer    :: cs
   type(sponge_cs),                    pointer    :: sponge_csp
   type(diag_to_z_cs),                 pointer    :: diag_to_z_csp
 !   This subroutine initializes the NTR tracer fields in tr(:,:,:,:)
 ! and it sets up the tracer output.
 ! Arguments: restart - .true. if the fields have already been read from
 !                     a restart file.
 !  (in)      day - Time of the start of the run.
 !  (in)      G - The ocean's grid structure.
 !  (in)      GV - The ocean's vertical grid structure.
 !  (in)      h - Layer thickness, in m or kg m-2.
 !  (in)      diag - A structure that is used to regulate diagnostic output.
 !  (in)      OBC - This open boundary condition type specifies whether, where,
 !                  and what open boundary conditions are used.
 !  (in/out)  CS - The control structure returned by a previous call to
 !                 USER_register_tracer_example.
 !  (in/out)  sponge_CSp - A pointer to the control structure for the sponges, if
 !                         they are in use.  Otherwise this may be unassociated.
 !  (in/out)  diag_to_Z_Csp - A pointer to the control structure for diagnostics
 !                            in depth space.
   real, allocatable :: temp(:,:,:)
   real, pointer, dimension(:,:,:) :: &
     obc_tr1_u => null(), & ! These arrays should be allocated and set to
     obc_tr1_v => null()    ! specify the values of tracer 1 that should come
                            ! in through u- and v- points through the open
                            ! boundary conditions, in the same units as tr.
   character(len=32) :: name     ! A variable's name in a NetCDF file.
   character(len=72) :: longname ! The long name of that variable.
   character(len=48) :: units    ! The dimensions of the variable.
   character(len=48) :: flux_units ! The units for tracer fluxes, usually
                             ! kg(tracer) kg(water)-1 m3 s-1 or kg(tracer) s-1.
   real, pointer :: tr_ptr(:,:,:) => null()
   real :: pi     ! 3.1415926... calculated as 4*atan(1)
   real :: tr_y   ! Initial zonally uniform tracer concentrations.
   real :: dist2  ! The distance squared from a line, in m2.
   integer :: i, j, k, is, ie, js, je, isd, ied, jsd, jed, nz, m
   integer :: isdb, iedb, jsdb, jedb, lntr
   if (.not.associated(cs)) return
   is = g%isc ; ie = g%iec ; js = g%jsc ; je = g%jec ; nz = gv%ke
   isd = g%isd ; ied = g%ied ; jsd = g%jsd ; jed = g%jed
   isdb = g%IsdB ; iedb = g%IedB ; jsdb = g%JsdB ; jedb = g%JedB
   lntr = ntr ! Avoids compile-time warning when NTR<2
   cs%Time => day
   cs%diag => diag
   if (.not.restart) then
     if (len_trim(cs%tracer_IC_file) >= 1) then
 !  Read the tracer concentrations from a netcdf file.
       if (.not.file_exists(cs%tracer_IC_file, g%Domain)) &
         call mom_error(fatal, "USER_initialize_tracer: Unable to open "// &
                         cs%tracer_IC_file)
       do m=1,ntr
         call query_vardesc(cs%tr_desc(m), name, caller="USER_initialize_tracer")
         call read_data(cs%tracer_IC_file, trim(name), &
                        cs%tr(:,:,:,m), domain=g%Domain%mpp_domain)
       enddo
     else
       do m=1,ntr
         do k=1,nz ; do j=js,je ; do i=is,ie
           cs%tr(i,j,k,m) = 1.0e-20 ! This could just as well be 0.
         enddo ; enddo ; enddo
       enddo
 !    This sets a stripe of tracer across the basin.
       pi = 4.0*atan(1.0)
       do j=js,je
         dist2 = (g%Rad_Earth * pi / 180.0)**2 * &
                (g%geoLatT(i,j) - 40.0) * (g%geoLatT(i,j) - 40.0)
         tr_y = 0.5*exp(-dist2/(1.0e5*1.0e5))
         do k=1,nz ; do i=is,ie
 !      This adds the stripes of tracer to every layer.
           cs%tr(i,j,k,1) = cs%tr(i,j,k,1) + tr_y
         enddo ; enddo
       enddo
     endif
   endif ! restart
   if ( cs%use_sponge ) then
 !   If sponges are used, this example damps tracers in sponges in the
 ! northern half of the domain to 1 and tracers in the southern half
 ! to 0.  For any tracers that are not damped in the sponge, the call
 ! to set_up_sponge_field can simply be omitted.
     if (.not.associated(sponge_csp)) &
       call mom_error(fatal, "USER_initialize_tracer: "// &
         "The pointer to sponge_CSp must be associated if SPONGE is defined.")
     allocate(temp(g%isd:g%ied,g%jsd:g%jed,nz))
     do k=1,nz ; do j=js,je ; do i=is,ie
       if (g%geoLatT(i,j) > 700.0 .and. (k > nz/2)) then
         temp(i,j,k) = 1.0
       else
         temp(i,j,k) = 0.0
       endif
     enddo ; enddo ; enddo
 !   do m=1,NTR
     do m=1,1
       ! This is needed to force the compiler not to do a copy in the sponge
       ! calls.  Curses on the designers and implementers of Fortran90.
       tr_ptr => cs%tr(:,:,:,m)
       call set_up_sponge_field(temp, tr_ptr, g, nz, sponge_csp)
     enddo
     deallocate(temp)
   endif
   if (associated(obc)) then
     call query_vardesc(cs%tr_desc(1), name, caller="USER_initialize_tracer")
     if (obc%specified_v_BCs_exist_globally) then
       allocate(obc_tr1_v(g%isd:g%ied,g%jsd:g%jed,nz))
       do k=1,nz ; do j=g%jsd,g%jed ; do i=g%isd,g%ied
         if (k < nz/2) then ; obc_tr1_v(i,j,k) = 0.0
         else ; obc_tr1_v(i,j,k) = 1.0 ; endif
       enddo ; enddo ; enddo
       call add_tracer_obc_values(trim(name), cs%tr_Reg, &
                                  0.0, obc_in_v=obc_tr1_v)
     else
       ! This is not expected in the DOME example.
       call add_tracer_obc_values(trim(name), cs%tr_Reg, 0.0)
     endif
     ! All tracers but the first have 0 concentration in their inflows. As this
     ! is the default value, the following calls are unnecessary.
     do m=2,lntr
       call query_vardesc(cs%tr_desc(m), name, caller="USER_initialize_tracer")
       call add_tracer_obc_values(trim(name), cs%tr_Reg, 0.0)
     enddo
   endif
   ! This needs to be changed if the units of tracer are changed above.
   if (gv%Boussinesq) then ; flux_units = "kg kg-1 m3 s-1"
   else ; flux_units = "kg s-1" ; endif
   do m=1,ntr
     ! Register the tracer for the restart file.
     call query_vardesc(cs%tr_desc(m), name, units=units, longname=longname, &
                        caller="USER_initialize_tracer")
     cs%id_tracer(m) = register_diag_field("ocean_model", trim(name), cs%diag%axesTL, &
         day, trim(longname) , trim(units))
     cs%id_tr_adx(m) = register_diag_field("ocean_model", trim(name)//"_adx", &
         cs%diag%axesCuL, day, trim(longname)//" advective zonal flux" , &
         trim(flux_units))
     cs%id_tr_ady(m) = register_diag_field("ocean_model", trim(name)//"_ady", &
         cs%diag%axesCvL, day, trim(longname)//" advective meridional flux" , &
         trim(flux_units))
     cs%id_tr_dfx(m) = register_diag_field("ocean_model", trim(name)//"_dfx", &
         cs%diag%axesCuL, day, trim(longname)//" diffusive zonal flux" , &
         trim(flux_units))
     cs%id_tr_dfy(m) = register_diag_field("ocean_model", trim(name)//"_dfy", &
         cs%diag%axesCvL, day, trim(longname)//" diffusive zonal flux" , &
         trim(flux_units))
     if (cs%id_tr_adx(m) > 0) call safe_alloc_ptr(cs%tr_adx(m)%p,isdb,iedb,jsd,jed,nz)
     if (cs%id_tr_ady(m) > 0) call safe_alloc_ptr(cs%tr_ady(m)%p,isd,ied,jsdb,jedb,nz)
     if (cs%id_tr_dfx(m) > 0) call safe_alloc_ptr(cs%tr_dfx(m)%p,isdb,iedb,jsd,jed,nz)
     if (cs%id_tr_dfy(m) > 0) call safe_alloc_ptr(cs%tr_dfy(m)%p,isd,ied,jsdb,jedb,nz)
 !    Register the tracer for horizontal advection & diffusion.
     if ((cs%id_tr_adx(m) > 0) .or. (cs%id_tr_ady(m) > 0) .or. &
         (cs%id_tr_dfx(m) > 0) .or. (cs%id_tr_dfy(m) > 0)) &
       call add_tracer_diagnostics(name, cs%tr_Reg, cs%tr_adx(m)%p, &
                                   cs%tr_ady(m)%p,cs%tr_dfx(m)%p,cs%tr_dfy(m)%p)
     call register_z_tracer(cs%tr(:,:,:,m), trim(name), longname, units, &
                            day, g, diag_to_z_csp)
   enddo
user_register_tracer_example()
logical function, public user_tracer_example::user_register_tracer_example (type(hor_index_type), intent(in) HI, type(verticalgrid_type), intent(in) GV, type(param_file_type), intent(in) param_file, type(user_tracer_example_cs), pointer CS, type(tracer_registry_type), pointer tr_Reg, type(mom_restart_cs), pointer restart_CS)
Parameters
[in] gv The ocean's vertical grid structure
[in] param_file A structure to parse for run-time parameters
Definition at line 123 of file tracer_example.F90.
References atmos_ocean_fluxes_mod::aof_set_coupler_flux(), mom_error_handler::mom_error(), ntr, and mom_io::var_desc().
   type(hor_index_type),    intent(in)   :: hi
   type(verticalgrid_type), intent(in)   :: gv   !< The ocean's vertical grid structure
   type(param_file_type),   intent(in)   :: param_file !< A structure to parse for run-time parameters
   type(user_tracer_example_cs), pointer :: cs
   type(tracer_registry_type), pointer   :: tr_reg
   type(mom_restart_cs),       pointer   :: restart_cs
 ! This subroutine is used to register tracer fields and subroutines
 ! to be used with MOM.
 ! Arguments: HI - A horizontal index type structure.
 !  (in)      GV - The ocean's vertical grid structure.
 !  (in)      param_file - A structure indicating the open file to parse for
 !                         model parameter values.
 !  (in/out)  CS - A pointer that is set to point to the control structure
 !                 for this module
 !  (in/out)  tr_Reg - A pointer that is set to point to the control structure
 !                  for the tracer advection and diffusion module.
 !  (in)      restart_CS - A pointer to the restart control structure.
   character(len=80)  :: name, longname
 ! This include declares and sets the variable "version".
 #include "version_variable.h"
   character(len=40)  :: mdl = "tracer_example" ! This module's name.
   character(len=200) :: inputdir
   real, pointer :: tr_ptr(:,:,:) => null()
   logical :: user_register_tracer_example
   integer :: isd, ied, jsd, jed, nz, m
   isd = hi%isd ; ied = hi%ied ; jsd = hi%jsd ; jed = hi%jed ; nz = gv%ke
   if (associated(cs)) then
     call mom_error(warning, "USER_register_tracer_example called with an "// &
                             "associated control structure.")
     return
   endif
   allocate(cs)
   ! Read all relevant parameters and write them to the model log.
   call log_version(param_file, mdl, version, "")
   call get_param(param_file, mdl, "TRACER_EXAMPLE_IC_FILE", cs%tracer_IC_file, &
                  "The name of a file from which to read the initial \n"//&
                  "conditions for the DOME tracers, or blank to initialize \n"//&
                  "them internally.", default=" ")
   if (len_trim(cs%tracer_IC_file) >= 1) then
     call get_param(param_file, mdl, "INPUTDIR", inputdir, default=".")
     cs%tracer_IC_file = trim(slasher(inputdir))//trim(cs%tracer_IC_file)
     call log_param(param_file, mdl, "INPUTDIR/TRACER_EXAMPLE_IC_FILE", &
                    cs%tracer_IC_file)
   endif
   call get_param(param_file, mdl, "SPONGE", cs%use_sponge, &
                  "If true, sponges may be applied anywhere in the domain. \n"//&
                  "The exact location and properties of those sponges are \n"//&
                  "specified from MOM_initialization.F90.", default=.false.)
   allocate(cs%tr(isd:ied,jsd:jed,nz,ntr)) ; cs%tr(:,:,:,:) = 0.0
   if (cs%mask_tracers) then
     allocate(cs%tr_aux(isd:ied,jsd:jed,nz,ntr)) ; cs%tr_aux(:,:,:,:) = 0.0
   endif
   do m=1,ntr
     if (m < 10) then ; write(name,'("tr",I1.1)') m
     else ; write(name,'("tr",I2.2)') m ; endif
     write(longname,'("Concentration of Tracer ",I2.2)') m
     cs%tr_desc(m) = var_desc(name, units="kg kg-1", longname=longname, caller=mdl)
     ! This is needed to force the compiler not to do a copy in the registration
     ! calls.  Curses on the designers and implementers of Fortran90.
     tr_ptr => cs%tr(:,:,:,m)
     ! Register the tracer for the restart file.
     call register_restart_field(tr_ptr, cs%tr_desc(m), .true., restart_cs)
     ! Register the tracer for horizontal advection & diffusion.
     call register_tracer(tr_ptr, cs%tr_desc(m), param_file, hi, gv, tr_reg, &
                          tr_desc_ptr=cs%tr_desc(m))
     !   Set coupled_tracers to be true (hard-coded above) to provide the surface
     ! values to the coupler (if any).  This is meta-code and its arguments will
     ! currently (deliberately) give fatal errors if it is used.
     if (cs%coupled_tracers) &
       cs%ind_tr(m) = aof_set_coupler_flux(trim(name)//'_flux', &
           flux_type=' ', implementation=' ', caller="USER_register_tracer_example")
   enddo
   cs%tr_Reg => tr_reg
   user_register_tracer_example = .true.
user_tracer_example_end()
subroutine, public user_tracer_example::user_tracer_example_end (type(user_tracer_example_cs), pointer CS)
Definition at line 603 of file tracer_example.F90.
References ntr.
Referenced by mom_tracer_flow_control::tracer_flow_control_end().
   type(user_tracer_example_cs), pointer :: cs
   integer :: m
   if (associated(cs)) then
     if (associated(cs%tr)) deallocate(cs%tr)
     if (associated(cs%tr_aux)) deallocate(cs%tr_aux)
     do m=1,ntr
       if (associated(cs%tr_adx(m)%p)) deallocate(cs%tr_adx(m)%p)
       if (associated(cs%tr_ady(m)%p)) deallocate(cs%tr_ady(m)%p)
       if (associated(cs%tr_dfx(m)%p)) deallocate(cs%tr_dfx(m)%p)
       if (associated(cs%tr_dfy(m)%p)) deallocate(cs%tr_dfy(m)%p)
     enddo
     deallocate(cs)
   endif
user_tracer_stock()
integer function, public user_tracer_example::user_tracer_stock (real, dimension(szi_(g),szj_(g),szk_(g)), intent(in) h, real, dimension(:), intent(out) stocks, type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, type(user_tracer_example_cs), pointer CS, character(len=*), dimension(:), intent(out) names, character(len=*), dimension(:), intent(out) units, integer, intent(in), optional stock_index)
Parameters
[in] g The ocean's grid structure
[in] gv The ocean's vertical grid structure
[in] h Layer thicknesses, in H (usually m or kg m-2)
Definition at line 520 of file tracer_example.F90.
References ntr, and mom_io::query_vardesc().
   type(ocean_grid_type),              intent(in)    :: g    !< The ocean's grid structure
   type(verticalgrid_type),            intent(in)    :: gv   !< The ocean's vertical grid structure
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)), &
                                       intent(in)    :: h    !< Layer thicknesses, in H (usually m or kg m-2)
   real, dimension(:),                 intent(out)   :: stocks
   type(user_tracer_example_cs),       pointer       :: cs
   character(len=*), dimension(:),     intent(out)   :: names
   character(len=*), dimension(:),     intent(out)   :: units
   integer, optional,                  intent(in)    :: stock_index
   integer                                           :: user_tracer_stock
 ! This function calculates the mass-weighted integral of all tracer stocks,
 ! returning the number of stocks it has calculated.  If the stock_index
 ! is present, only the stock corresponding to that coded index is returned.
 ! Arguments: h - Layer thickness, in m or kg m-2.
 !  (out)     stocks - the mass-weighted integrated amount of each tracer,
 !                     in kg times concentration units.
 !  (in)      G - The ocean's grid structure.
 !  (in)      GV - The ocean's vertical grid structure.
 !  (in)      CS - The control structure returned by a previous call to
 !                 register_USER_tracer.
 !  (out)     names - the names of the stocks calculated.
 !  (out)     units - the units of the stocks calculated.
 !  (in,opt)  stock_index - the coded index of a specific stock being sought.
 ! Return value: the number of stocks calculated here.
   integer :: i, j, k, is, ie, js, je, nz, m
   is = g%isc ; ie = g%iec ; js = g%jsc ; je = g%jec ; nz = gv%ke
   user_tracer_stock = 0
   if (.not.associated(cs)) return
   if (present(stock_index)) then ; if (stock_index > 0) then
     ! Check whether this stock is available from this routine.
     ! No stocks from this routine are being checked yet.  Return 0.
     return
   endif ; endif
   do m=1,ntr
     call query_vardesc(cs%tr_desc(m), name=names(m), units=units(m), caller="USER_tracer_stock")
     units(m) = trim(units(m))//" kg"
     stocks(m) = 0.0
     do k=1,nz ; do j=js,je ; do i=is,ie
       stocks(m) = stocks(m) + cs%tr(i,j,k,m) * &
                              (g%mask2dT(i,j) * g%areaT(i,j) * h(i,j,k))
     enddo ; enddo ; enddo
     stocks(m) = gv%H_to_kg_m2 * stocks(m)
   enddo
   user_tracer_stock = ntr
user_tracer_surface_state()
subroutine, public user_tracer_example::user_tracer_surface_state (type(surface), intent(inout) state, real, dimension(g %isd: g %ied, g %jsd: g %jed, g %ke), intent(in) h, type(ocean_grid_type), intent(in) G, type(user_tracer_example_cs), pointer CS)
Parameters
[in] g The ocean's grid structure
[in] h Layer thicknesses, in H (usually m or kg m-2)
Definition at line 574 of file tracer_example.F90.
References ntr, and coupler_util::set_coupler_values().
   type(ocean_grid_type),              intent(in)    :: g    !< The ocean's grid structure
   type(surface),                      intent(inout) :: state
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)), intent(in)    :: h    !< Layer thicknesses, in H (usually m or kg m-2)
   type(user_tracer_example_cs),       pointer       :: cs
 !   This particular tracer package does not report anything back to the coupler.
 ! The code that is here is just a rough guide for packages that would.
 ! Arguments: state - A structure containing fields that describe the
 !                    surface state of the ocean.
 !  (in)      h - Layer thickness, in m or kg m-2.
 !  (in)      G - The ocean's grid structure.
 !  (in)      CS - The control structure returned by a previous call to
 !                 register_USER_tracer.
   integer :: i, j, m, is, ie, js, je
   is = g%isc ; ie = g%iec ; js = g%jsc ; je = g%jec
   if (.not.associated(cs)) return
   if (cs%coupled_tracers) then
     do m=1,ntr
       !   This call loads the surface vlues into the appropriate array in the
       ! coupler-type structure.
       call set_coupler_values(cs%tr(:,:,1,1), state%tr_fields, cs%ind_tr(m), &
                               ind_csurf, is, ie, js, je)
     enddo
   endif
Variable Documentation
ntr
integer, parameter user_tracer_example::ntr = 1 private
Definition at line 82 of file tracer_example.F90.
Referenced by tracer_column_physics(), user_initialize_tracer(), user_register_tracer_example(), user_tracer_example_end(), user_tracer_stock(), and user_tracer_surface_state().
 integer, parameter :: ntr = 1