MOM6: atmos_ocean_fluxes_mod Module Reference
atmos_ocean_fluxes_mod Module Reference
Functions/Subroutines
integer function, public aof_set_coupler_flux (name, flux_type, implementation, atm_tr_index, param, flag, ice_restart_file, ocean_restart_file, units, caller)
Function/Subroutine Documentation
aof_set_coupler_flux()
integer function, public atmos_ocean_fluxes_mod::aof_set_coupler_flux (character(len=*), intent(in) name, character(len=*), intent(in) flux_type, character(len=*), intent(in) implementation, integer, intent(in), optional atm_tr_index, real, dimension(:), intent(in), optional param, logical, dimension(:), intent(in), optional flag, character(len=*), intent(in), optional ice_restart_file, character(len=*), intent(in), optional ocean_restart_file, character(len=*), intent(in), optional units, character(len=*), intent(in), optional caller)
Definition at line 20 of file atmos_ocean_fluxes.F90.
Referenced by ocean_model_mod::ocean_model_flux_init(), advection_test_tracer::register_advection_test_tracer(), boundary_impulse_tracer::register_boundary_impulse_tracer(), dome_tracer::register_dome_tracer(), regional_dyes::register_dye_tracer(), ideal_age_example::register_ideal_age_tracer(), isomip_tracer::register_isomip_tracer(), mom_ocmip2_cfc::register_ocmip2_cfc(), oil_tracer::register_oil_tracer(), pseudo_salt_tracer::register_pseudo_salt_tracer(), and user_tracer_example::user_register_tracer_example().
   character(len=*), intent(in)                          :: name
   character(len=*), intent(in)                          :: flux_type
   character(len=*), intent(in)                          :: implementation
   integer,          intent(in), optional                :: atm_tr_index
   real,             intent(in), dimension(:), optional  :: param
   logical,          intent(in), dimension(:), optional  :: flag
   character(len=*), intent(in), optional                :: ice_restart_file
   character(len=*), intent(in), optional                :: ocean_restart_file
   character(len=*), intent(in), optional                :: units
   character(len=*), intent(in), optional                :: caller
   ! None of these arguments are used for anything.
   integer :: coupler_index
   coupler_index = -1