MOM6: mom_verticalgrid Module Reference
mom_verticalgrid Module Reference
Data Types
type verticalgrid_type
Functions/Subroutines
subroutine, public verticalgridinit (param_file, GV)
Allocates and initializes the model's vertical grid structure.
character(len=48) function, public get_thickness_units (GV)
Returns the model's thickness units, usually m or kg/m^2.
character(len=48) function, public get_flux_units (GV)
Returns the model's thickness flux units, usually m^3/s or kg/s.
character(len=48) function, public get_tr_flux_units (GV, tr_units, tr_vol_conc_units, tr_mass_conc_units)
Returns the model's tracer flux units.
subroutine, public setverticalgridaxes (Rlay, GV)
This sets the coordinate data for the "layer mode" of the isopycnal model.
subroutine, public verticalgridend (GV)
Deallocates the model's vertical grid structure.
Function/Subroutine Documentation
get_flux_units()
character(len=48) function, public mom_verticalgrid::get_flux_units (type(verticalgrid_type), intent(in) GV)
Returns the model's thickness flux units, usually m^3/s or kg/s.
Parameters
[in] gv The ocean's vertical grid structure
Definition at line 186 of file MOM_verticalGrid.F90.
Referenced by mom::register_diags().
   character(len=48)                 :: get_flux_units
   type(verticalgrid_type), intent(in) :: gv   !< The ocean's vertical grid structure
 !   This subroutine returns the appropriate units for thickness fluxes,
 ! depending on whether the model is Boussinesq or not and the scaling for
 ! the vertical thickness.
 ! Arguments: G - The ocean's grid structure.
 !  (ret)     get_flux_units - The model's thickness flux units.
   if (gv%Boussinesq) then
     get_flux_units = "meter3 second-1"
   else
     get_flux_units = "kilogram second-1"
   endif
get_thickness_units()
character(len=48) function, public mom_verticalgrid::get_thickness_units (type(verticalgrid_type), intent(in) GV)
Returns the model's thickness units, usually m or kg/m^2.
Parameters
[in] gv The ocean's vertical grid structure
Definition at line 168 of file MOM_verticalGrid.F90.
Referenced by mom::register_diags().
   character(len=48)                 :: get_thickness_units
   type(verticalgrid_type), intent(in) :: gv   !< The ocean's vertical grid structure
 !   This subroutine returns the appropriate units for thicknesses,
 ! depending on whether the model is Boussinesq or not and the scaling for
 ! the vertical thickness.
 ! Arguments: G - The ocean's grid structure.
 !  (ret)     get_thickness_units - The model's vertical thickness units.
   if (gv%Boussinesq) then
     get_thickness_units = "meter"
   else
     get_thickness_units = "kilogram meter-2"
   endif
get_tr_flux_units()
character(len=48) function, public mom_verticalgrid::get_tr_flux_units (type(verticalgrid_type), intent(in) GV, character(len=*), intent(in), optional tr_units, character(len=*), intent(in), optional tr_vol_conc_units, character(len=*), intent(in), optional tr_mass_conc_units)
Returns the model's tracer flux units.
Returns
The model's flux units for a tracer.
Parameters
[in] gv The ocean's vertical grid structure.
[in] tr_units Units for a tracer, for example Celsius or PSU.
[in] tr_vol_conc_units The concentration units per unit volume, forexample if the units are umol m-3, tr_vol_conc_units would be umol.
[in] tr_mass_conc_units The concentration units per unit mass of sea water, for example if the units are mol kg-1, tr_vol_conc_units would be mol.
Definition at line 204 of file MOM_verticalGrid.F90.
References mom_error_handler::mom_error().
Referenced by mom::register_diags().
   character(len=48)                      :: get_tr_flux_units !< The model's flux units
                                                               !! for a tracer.
   type(verticalgrid_type),    intent(in) :: gv                !< The ocean's vertical
                                                               !! grid structure.
   character(len=*), optional, intent(in) :: tr_units          !< Units for a tracer, for example
                                                               !! Celsius or PSU.
   character(len=*), optional, intent(in) :: tr_vol_conc_units !< The concentration units per unit
                                                               !! volume, forexample if the units are
                                                               !! umol m-3, tr_vol_conc_units would
                                                               !! be umol.
   character(len=*), optional, intent(in) :: tr_mass_conc_units !< The concentration units per unit
                                                               !! mass of sea water, for example if
                                                               !! the units are mol kg-1,
                                                               !! tr_vol_conc_units would be mol.
 !   This subroutine returns the appropriate units for thicknesses and fluxes,
 ! depending on whether the model is Boussinesq or not and the scaling for
 ! the vertical thickness.
 ! Arguments: G - The ocean's grid structure.
 !      One of the following three arguments must be present.
 !  (in,opt)  tr_units - Units for a tracer, for example Celsius or PSU.
 !  (in,opt)  tr_vol_conc_units - The concentration units per unit volume, for
 !                                example if the units are umol m-3,
 !                                tr_vol_conc_units would be umol.
 !  (in,opt)  tr_mass_conc_units - The concentration units per unit mass of sea
 !                                water, for example if the units are mol kg-1,
 !                                tr_vol_conc_units would be mol.
 !  (ret)     get_tr_flux_units - The model's flux units for a tracer.
   integer :: cnt
   cnt = 0
   if (present(tr_units)) cnt = cnt+1
   if (present(tr_vol_conc_units)) cnt = cnt+1
   if (present(tr_mass_conc_units)) cnt = cnt+1
   if (cnt == 0) call mom_error(fatal, "get_tr_flux_units: One of the three "//&
     "arguments tr_units, tr_vol_conc_units, or tr_mass_conc_units "//&
     "must be present.")
   if (cnt > 1) call mom_error(fatal, "get_tr_flux_units: Only one of "//&
     "tr_units, tr_vol_conc_units, and tr_mass_conc_units may be present.")
   if (present(tr_units)) then
     if (gv%Boussinesq) then
       get_tr_flux_units = trim(tr_units)//" meter3 second-1"
     else
       get_tr_flux_units = trim(tr_units)//" kilogram second-1"
     endif
   endif
   if (present(tr_vol_conc_units)) then
     if (gv%Boussinesq) then
       get_tr_flux_units = trim(tr_vol_conc_units)//" second-1"
     else
       get_tr_flux_units = trim(tr_vol_conc_units)//" m-3 kg s-1"
     endif
   endif
   if (present(tr_mass_conc_units)) then
     if (gv%Boussinesq) then
       get_tr_flux_units = trim(tr_mass_conc_units)//" kg-1 m3 s-1"
     else
       get_tr_flux_units = trim(tr_mass_conc_units)//" second-1"
     endif
   endif
setverticalgridaxes()
subroutine, public mom_verticalgrid::setverticalgridaxes (real, dimension(gv%ke), intent(in) Rlay, type(verticalgrid_type), intent(inout) GV)
This sets the coordinate data for the "layer mode" of the isopycnal model.
Parameters
[in,out] gv The container for vertical grid data
[in] rlay The layer target density
Definition at line 271 of file MOM_verticalGrid.F90.
Referenced by mom_coord_initialization::mom_initialize_coord().
   ! Arguments
   type(verticalgrid_type), intent(inout) :: gv   !< The container for vertical grid data
   real, dimension(GV%ke),  intent(in)    :: rlay !< The layer target density
   ! Local variables
   integer :: k, nk
   nk = gv%ke
   gv%zAxisLongName = 'Target Potential Density'
   gv%zAxisUnits = 'kg m-3'
   do k=1,nk ; gv%sLayer(k) = rlay(k) ; enddo
   if (nk > 1) then
     gv%sInterface(1) = 1.5*rlay(1) - 0.5*rlay(2)
     do k=2,nk ; gv%sInterface(k) = 0.5*( rlay(k-1) + rlay(k) ) ; enddo
     gv%sInterface(nk+1) = 1.5*rlay(nk) - 0.5*rlay(nk-1)
   else
     gv%sInterface(1) = 0.0 ; gv%sInterface(nk+1) = 2.0*rlay(nk)
   endif
verticalgridend()
subroutine, public mom_verticalgrid::verticalgridend (type(verticalgrid_type), pointer GV)
Deallocates the model's vertical grid structure.
Parameters
gv The ocean's vertical grid structure
Definition at line 294 of file MOM_verticalGrid.F90.
 ! Arguments: G - The ocean's grid structure.
   type(verticalgrid_type), pointer :: gv   !< The ocean's vertical grid structure
   dealloc_(gv%g_prime) ; dealloc_(gv%Rlay)
   dealloc_( gv%sInterface )
   dealloc_( gv%sLayer )
   deallocate( gv )
verticalgridinit()
subroutine, public mom_verticalgrid::verticalgridinit (type(param_file_type), intent(in) param_file, type(verticalgrid_type), pointer GV)
Allocates and initializes the model's vertical grid structure.
Definition at line 87 of file MOM_verticalGrid.F90.
References mom_error_handler::mom_error().
 ! This routine initializes the verticalGrid_type structure (GV).
 ! All memory is allocated but not necessarily set to meaningful values until later.
   type(param_file_type),   intent(in) :: param_file ! Parameter file handle/type
   type(verticalgrid_type), pointer    :: gv         ! The container for vertical grid data
 ! This include declares and sets the variable "version".
 #include "version_variable.h"
   integer :: nk
   character(len=16) :: mdl = 'MOM_verticalGrid'
   if (associated(gv)) call mom_error(fatal, &
      'verticalGridInit: called with an associated GV pointer.')
   allocate(gv)
   ! Read all relevant parameters and write them to the model log.
   call log_version(param_file, mdl, version, &
                    "Parameters providing information about the vertical grid.")
   call get_param(param_file, mdl, "G_EARTH", gv%g_Earth, &
                  "The gravitational acceleration of the Earth.", &
                  units="m s-2", default = 9.80)
   call get_param(param_file, mdl, "RHO_0", gv%Rho0, &
                  "The mean ocean density used with BOUSSINESQ true to \n"//&
                  "calculate accelerations and the mass for conservation \n"//&
                  "properties, or with BOUSSINSEQ false to convert some \n"//&
                  "parameters from vertical units of m to kg m-2.", &
                  units="kg m-3", default=1035.0)
   call get_param(param_file, mdl, "BOUSSINESQ", gv%Boussinesq, &
                  "If true, make the Boussinesq approximation.", default=.true.)
   call get_param(param_file, mdl, "ANGSTROM", gv%Angstrom_z, &
                  "The minumum layer thickness, usually one-Angstrom.", &
                  units="m", default=1.0e-10)
   if (.not.gv%Boussinesq) then
     call get_param(param_file, mdl, "H_TO_KG_M2", gv%H_to_kg_m2,&
                  "A constant that translates thicknesses from the model's \n"//&
                  "internal units of thickness to kg m-2.", units="kg m-2 H-1", &
                  default=1.0)
   else
     call get_param(param_file, mdl, "H_TO_M", gv%H_to_m, &
                  "A constant that translates the model's internal \n"//&
                  "units of thickness into m.", units="m H-1", default=1.0)
   endif
 #ifdef STATIC_MEMORY_
   ! Here NK_ is a macro, while nk is a variable.
   call get_param(param_file, mdl, "NK", nk, &
                  "The number of model layers.", units="nondim", &
                  static_value=nk_)
   if (nk /= nk_) call mom_error(fatal, "verticalGridInit: " // &
        "Mismatched number of layers NK_ between MOM_memory.h and param_file")
 #else
   call get_param(param_file, mdl, "NK", nk, &
                  "The number of model layers.", units="nondim", fail_if_missing=.true.)
 #endif
   gv%ke = nk
   if (gv%Boussinesq) then
     gv%H_to_kg_m2 = gv%Rho0 * gv%H_to_m
     gv%kg_m2_to_H = 1.0 / gv%H_to_kg_m2
     gv%m_to_H = 1.0 / gv%H_to_m
     gv%Angstrom = gv%m_to_H * gv%Angstrom_z
   else
     gv%kg_m2_to_H = 1.0 / gv%H_to_kg_m2
     gv%m_to_H = gv%Rho0 * gv%kg_m2_to_H
     gv%H_to_m = gv%H_to_kg_m2 / gv%Rho0
     gv%Angstrom = gv%Angstrom_z*1000.0*gv%kg_m2_to_H
   endif
   gv%H_subroundoff = 1e-20 * max(gv%Angstrom,gv%m_to_H*1e-17)
   gv%H_to_Pa = gv%g_Earth * gv%H_to_kg_m2
 ! Log derivative values.
   call log_param(param_file, mdl, "M to THICKNESS", gv%m_to_H)
   alloc_( gv%sInterface(nk+1) )
   alloc_( gv%sLayer(nk) )
   alloc_( gv%g_prime(nk+1) ) ; gv%g_prime(:) = 0.0
   ! The extent of Rlay should be changed to nk?
   alloc_( gv%Rlay(nk+1) )    ; gv%Rlay(:) = 0.0