MOM6: mom_dyn_horgrid Module Reference
mom_dyn_horgrid Module Reference
Data Types
type dyn_horgrid_type
Functions/Subroutines
subroutine, public create_dyn_horgrid (G, HI, bathymetry_at_vel)
Allocate memory used by the dyn_horgrid_type and related structures.
subroutine, public set_derived_dyn_horgrid (G)
set_derived_dyn_horgrid calculates metric terms that are derived from other metrics.
real function adcroft_reciprocal (val)
Adcroft_reciprocal(x) = 1/x for |x|>0 or 0 for x=0.
subroutine, public destroy_dyn_horgrid (G)
Release memory used by the dyn_horgrid_type and related structures.
Function/Subroutine Documentation
adcroft_reciprocal()
real function mom_dyn_horgrid::adcroft_reciprocal (real, intent(in) val) private
Adcroft_reciprocal(x) = 1/x for |x|>0 or 0 for x=0.
Parameters
[in] val The value being inverted.
Returns
The Adcroft reciprocal of val.
Definition at line 305 of file MOM_dyn_horgrid.F90.
Referenced by set_derived_dyn_horgrid().
   real, intent(in) :: val  !< The value being inverted.
   real :: i_val            !< The Adcroft reciprocal of val.
   i_val = 0.0 ; if (val /= 0.0) i_val = 1.0/val
create_dyn_horgrid()
subroutine, public mom_dyn_horgrid::create_dyn_horgrid (type(dyn_horgrid_type), pointer G, type(hor_index_type), intent(in) HI, logical, intent(in), optional bathymetry_at_vel)
Allocate memory used by the dyn_horgrid_type and related structures.
Parameters
g A pointer to the dynamic horizontal grid type
[in] hi A hor_index_type for array extents
[in] bathymetry_at_vel If true, there are separate values for the basin depths at velocity points. Otherwise the effects of topography are entirely determined from thickness points.
Definition at line 149 of file MOM_dyn_horgrid.F90.
References mom_error_handler::mom_error().
Referenced by mom::initialize_mom().
   type(dyn_horgrid_type), pointer    :: g  !< A pointer to the dynamic horizontal grid type
   type(hor_index_type),   intent(in) :: hi !< A hor_index_type for array extents
   logical,        optional, intent(in) :: bathymetry_at_vel !< If true, there are
                              !! separate values for the basin depths at velocity
                              !! points.  Otherwise the effects of topography are
                              !! entirely determined from thickness points.
   integer :: isd, ied, jsd, jed, isdb, iedb, jsdb, jedb, isg, ieg, jsg, jeg
   ! This subroutine allocates the lateral elements of the dyn_horgrid_type that
   ! are always used and zeros them out.
   if (associated(g)) then
     call mom_error(warning, "create_dyn_horgrid called with an associated horgrid_type.")
   else
     allocate(g)
   endif
   g%HI = hi
   g%isc = hi%isc ; g%iec = hi%iec ; g%jsc = hi%jsc ; g%jec = hi%jec
   g%isd = hi%isd ; g%ied = hi%ied ; g%jsd = hi%jsd ; g%jed = hi%jed
   g%isg = hi%isg ; g%ieg = hi%ieg ; g%jsg = hi%jsg ; g%jeg = hi%jeg
   g%IscB = hi%IscB ; g%IecB = hi%IecB ; g%JscB = hi%JscB ; g%JecB = hi%JecB
   g%IsdB = hi%IsdB ; g%IedB = hi%IedB ; g%JsdB = hi%JsdB ; g%JedB = hi%JedB
   g%IsgB = hi%IsgB ; g%IegB = hi%IegB ; g%JsgB = hi%JsgB ; g%JegB = hi%JegB
   g%idg_offset = hi%idg_offset ; g%jdg_offset = hi%jdg_offset
   g%isd_global = g%isd + hi%idg_offset ; g%jsd_global = g%jsd + hi%jdg_offset
   g%symmetric = hi%symmetric
   g%bathymetry_at_vel = .false.
   if (present(bathymetry_at_vel)) g%bathymetry_at_vel = bathymetry_at_vel
   isd = g%isd ; ied = g%ied ; jsd = g%jsd ; jed = g%jed
   isdb = g%IsdB ; iedb = g%IedB ; jsdb = g%JsdB ; jedb = g%JedB
   isg = g%isg ; ieg = g%ieg ; jsg = g%jsg ; jeg = g%jeg
   allocate(g%dxT(isd:ied,jsd:jed))       ; g%dxT(:,:) = 0.0
   allocate(g%dxCu(isdb:iedb,jsd:jed))    ; g%dxCu(:,:) = 0.0
   allocate(g%dxCv(isd:ied,jsdb:jedb))    ; g%dxCv(:,:) = 0.0
   allocate(g%dxBu(isdb:iedb,jsdb:jedb))  ; g%dxBu(:,:) = 0.0
   allocate(g%IdxT(isd:ied,jsd:jed))      ; g%IdxT(:,:) = 0.0
   allocate(g%IdxCu(isdb:iedb,jsd:jed))   ; g%IdxCu(:,:) = 0.0
   allocate(g%IdxCv(isd:ied,jsdb:jedb))   ; g%IdxCv(:,:) = 0.0
   allocate(g%IdxBu(isdb:iedb,jsdb:jedb)) ; g%IdxBu(:,:) = 0.0
   allocate(g%dyT(isd:ied,jsd:jed))       ; g%dyT(:,:) = 0.0
   allocate(g%dyCu(isdb:iedb,jsd:jed))    ; g%dyCu(:,:) = 0.0
   allocate(g%dyCv(isd:ied,jsdb:jedb))    ; g%dyCv(:,:) = 0.0
   allocate(g%dyBu(isdb:iedb,jsdb:jedb))  ; g%dyBu(:,:) = 0.0
   allocate(g%IdyT(isd:ied,jsd:jed))      ; g%IdyT(:,:) = 0.0
   allocate(g%IdyCu(isdb:iedb,jsd:jed))   ; g%IdyCu(:,:) = 0.0
   allocate(g%IdyCv(isd:ied,jsdb:jedb))   ; g%IdyCv(:,:) = 0.0
   allocate(g%IdyBu(isdb:iedb,jsdb:jedb)) ; g%IdyBu(:,:) = 0.0
   allocate(g%areaT(isd:ied,jsd:jed))       ; g%areaT(:,:) = 0.0
   allocate(g%IareaT(isd:ied,jsd:jed))      ; g%IareaT(:,:) = 0.0
   allocate(g%areaBu(isdb:iedb,jsdb:jedb))  ; g%areaBu(:,:) = 0.0
   allocate(g%IareaBu(isdb:iedb,jsdb:jedb)) ; g%IareaBu(:,:) = 0.0
   allocate(g%mask2dT(isd:ied,jsd:jed))      ; g%mask2dT(:,:) = 0.0
   allocate(g%mask2dCu(isdb:iedb,jsd:jed))   ; g%mask2dCu(:,:) = 0.0
   allocate(g%mask2dCv(isd:ied,jsdb:jedb))   ; g%mask2dCv(:,:) = 0.0
   allocate(g%mask2dBu(isdb:iedb,jsdb:jedb)) ; g%mask2dBu(:,:) = 0.0
   allocate(g%geoLatT(isd:ied,jsd:jed))      ; g%geoLatT(:,:) = 0.0
   allocate(g%geoLatCu(isdb:iedb,jsd:jed))   ; g%geoLatCu(:,:) = 0.0
   allocate(g%geoLatCv(isd:ied,jsdb:jedb))   ; g%geoLatCv(:,:) = 0.0
   allocate(g%geoLatBu(isdb:iedb,jsdb:jedb)) ; g%geoLatBu(:,:) = 0.0
   allocate(g%geoLonT(isd:ied,jsd:jed))      ; g%geoLonT(:,:) = 0.0
   allocate(g%geoLonCu(isdb:iedb,jsd:jed))   ; g%geoLonCu(:,:) = 0.0
   allocate(g%geoLonCv(isd:ied,jsdb:jedb))   ; g%geoLonCv(:,:) = 0.0
   allocate(g%geoLonBu(isdb:iedb,jsdb:jedb)) ; g%geoLonBu(:,:) = 0.0
   allocate(g%dx_Cv(isd:ied,jsdb:jedb))     ; g%dx_Cv(:,:) = 0.0
   allocate(g%dy_Cu(isdb:iedb,jsd:jed))     ; g%dy_Cu(:,:) = 0.0
   allocate(g%dx_Cv_obc(isd:ied,jsdb:jedb)) ; g%dx_Cv_obc(:,:) = 0.0
   allocate(g%dy_Cu_obc(isdb:iedb,jsd:jed)) ; g%dy_Cu_obc(:,:) = 0.0
   allocate(g%areaCu(isdb:iedb,jsd:jed))  ; g%areaCu(:,:) = 0.0
   allocate(g%areaCv(isd:ied,jsdb:jedb))  ; g%areaCv(:,:) = 0.0
   allocate(g%IareaCu(isdb:iedb,jsd:jed)) ; g%IareaCu(:,:) = 0.0
   allocate(g%IareaCv(isd:ied,jsdb:jedb)) ; g%IareaCv(:,:) = 0.0
   allocate(g%bathyT(isd:ied, jsd:jed)) ; g%bathyT(:,:) = 0.0
   allocate(g%CoriolisBu(isdb:iedb, jsdb:jedb)) ; g%CoriolisBu(:,:) = 0.0
   allocate(g%dF_dx(isd:ied, jsd:jed)) ; g%dF_dx(:,:) = 0.0
   allocate(g%dF_dy(isd:ied, jsd:jed)) ; g%dF_dy(:,:) = 0.0
   allocate(g%sin_rot(isd:ied,jsd:jed)) ; g%sin_rot(:,:) = 0.0
   allocate(g%cos_rot(isd:ied,jsd:jed)) ; g%cos_rot(:,:) = 1.0
   if (g%bathymetry_at_vel) then
     allocate(g%Dblock_u(isdb:iedb, jsd:jed)) ; g%Dblock_u(:,:) = 0.0
     allocate(g%Dopen_u(isdb:iedb, jsd:jed))  ; g%Dopen_u(:,:) = 0.0
     allocate(g%Dblock_v(isd:ied, jsdb:jedb)) ; g%Dblock_v(:,:) = 0.0
     allocate(g%Dopen_v(isd:ied, jsdb:jedb))  ; g%Dopen_v(:,:) = 0.0
   endif
   ! gridLonB and gridLatB are used as edge values in some cases, so they
   ! always need to use symmetric memory allcoations.
   allocate(g%gridLonT(isg:ieg))   ; g%gridLonT(:) = 0.0
   allocate(g%gridLonB(isg-1:ieg)) ; g%gridLonB(:) = 0.0
   allocate(g%gridLatT(jsg:jeg))   ; g%gridLatT(:) = 0.0
   allocate(g%gridLatB(jsg-1:jeg)) ; g%gridLatB(:) = 0.0
destroy_dyn_horgrid()
subroutine, public mom_dyn_horgrid::destroy_dyn_horgrid (type(dyn_horgrid_type), pointer G)
Release memory used by the dyn_horgrid_type and related structures.
Parameters
g The dynamic horizontal grid type
Definition at line 314 of file MOM_dyn_horgrid.F90.
References mom_error_handler::mom_error().
Referenced by mom::initialize_mom().
   type(dyn_horgrid_type), pointer :: g !< The dynamic horizontal grid type
   if (.not.associated(g)) then
     call mom_error(fatal, "destroy_dyn_horgrid called with an unassociated horgrid_type.")
   endif
   deallocate(g%dxT)  ; deallocate(g%dxCu)  ; deallocate(g%dxCv)  ; deallocate(g%dxBu)
   deallocate(g%IdxT) ; deallocate(g%IdxCu) ; deallocate(g%IdxCv) ; deallocate(g%IdxBu)
   deallocate(g%dyT)  ; deallocate(g%dyCu)  ; deallocate(g%dyCv)  ; deallocate(g%dyBu)
   deallocate(g%IdyT) ; deallocate(g%IdyCu) ; deallocate(g%IdyCv) ; deallocate(g%IdyBu)
   deallocate(g%areaT)  ; deallocate(g%IareaT)
   deallocate(g%areaBu) ; deallocate(g%IareaBu)
   deallocate(g%areaCu) ; deallocate(g%IareaCu)
   deallocate(g%areaCv)  ; deallocate(g%IareaCv)
   deallocate(g%mask2dT)  ; deallocate(g%mask2dCu)
   deallocate(g%mask2dCv) ; deallocate(g%mask2dBu)
   deallocate(g%geoLatT)  ; deallocate(g%geoLatCu)
   deallocate(g%geoLatCv) ; deallocate(g%geoLatBu)
   deallocate(g%geoLonT)  ; deallocate(g%geoLonCu)
   deallocate(g%geoLonCv) ; deallocate(g%geoLonBu)
   deallocate(g%dx_Cv) ; deallocate(g%dy_Cu)
   deallocate(g%dx_Cv_obc) ; deallocate(g%dy_Cu_obc)
   deallocate(g%bathyT)  ; deallocate(g%CoriolisBu)
   deallocate(g%dF_dx)  ; deallocate(g%dF_dy)
   deallocate(g%sin_rot) ; deallocate(g%cos_rot)
   if (allocated(g%Dblock_u)) deallocate(g%Dblock_u)
   if (allocated(g%Dopen_u)) deallocate(g%Dopen_u)
   if (allocated(g%Dblock_v)) deallocate(g%Dblock_v)
   if (allocated(g%Dopen_v)) deallocate(g%Dopen_v)
   deallocate(g%gridLonT) ; deallocate(g%gridLatT)
   deallocate(g%gridLonB) ; deallocate(g%gridLatB)
   deallocate(g%Domain%mpp_domain)
   deallocate(g%Domain)
   deallocate(g)
set_derived_dyn_horgrid()
subroutine, public mom_dyn_horgrid::set_derived_dyn_horgrid (type(dyn_horgrid_type), intent(inout) G)
set_derived_dyn_horgrid calculates metric terms that are derived from other metrics.
Parameters
[in,out] g The dynamic horizontal grid type
Definition at line 259 of file MOM_dyn_horgrid.F90.
References adcroft_reciprocal().
Referenced by mom_transcribe_grid::copy_mom_grid_to_dyngrid(), and mom_grid_initialize::set_grid_metrics().
   type(dyn_horgrid_type), intent(inout) :: g !< The dynamic horizontal grid type
 !    Various inverse grid spacings and derived areas are calculated within this
 !  subroutine.
   integer :: i, j, isd, ied, jsd, jed
   integer :: isdb, iedb, jsdb, jedb
   isd = g%isd ; ied = g%ied ; jsd = g%jsd ; jed = g%jed
   isdb = g%IsdB ; iedb = g%IedB ; jsdb = g%JsdB ; jedb = g%JedB
   do j=jsd,jed ; do i=isd,ied
     if (g%dxT(i,j) < 0.0) g%dxT(i,j) = 0.0
     if (g%dyT(i,j) < 0.0) g%dyT(i,j) = 0.0
     g%IdxT(i,j) = adcroft_reciprocal(g%dxT(i,j))
     g%IdyT(i,j) = adcroft_reciprocal(g%dyT(i,j))
     g%IareaT(i,j) = adcroft_reciprocal(g%areaT(i,j))
   enddo ; enddo
   do j=jsd,jed ; do i=isdb,iedb
     if (g%dxCu(i,j) < 0.0) g%dxCu(i,j) = 0.0
     if (g%dyCu(i,j) < 0.0) g%dyCu(i,j) = 0.0
     g%IdxCu(i,j) = adcroft_reciprocal(g%dxCu(i,j))
     g%IdyCu(i,j) = adcroft_reciprocal(g%dyCu(i,j))
   enddo ; enddo
   do j=jsdb,jedb ; do i=isd,ied
     if (g%dxCv(i,j) < 0.0) g%dxCv(i,j) = 0.0
     if (g%dyCv(i,j) < 0.0) g%dyCv(i,j) = 0.0
     g%IdxCv(i,j) = adcroft_reciprocal(g%dxCv(i,j))
     g%IdyCv(i,j) = adcroft_reciprocal(g%dyCv(i,j))
   enddo ; enddo
   do j=jsdb,jedb ; do i=isdb,iedb
     if (g%dxBu(i,j) < 0.0) g%dxBu(i,j) = 0.0
     if (g%dyBu(i,j) < 0.0) g%dyBu(i,j) = 0.0
     g%IdxBu(i,j) = adcroft_reciprocal(g%dxBu(i,j))
     g%IdyBu(i,j) = adcroft_reciprocal(g%dyBu(i,j))
     ! areaBu has usually been set to a positive area elsewhere.
     if (g%areaBu(i,j) <= 0.0) g%areaBu(i,j) = g%dxBu(i,j) * g%dyBu(i,j)
     g%IareaBu(i,j) =  adcroft_reciprocal(g%areaBu(i,j))
   enddo ; enddo