MOM6: mom_tracer_advect Module Reference
mom_tracer_advect Module Reference
Detailed Description
This program contains the subroutines that advect tracers along coordinate surfaces.
This program contains the subroutines that advect tracers horizontally (i.e. along layers).
section_mom_advect_intro
advect_tracer advects tracer concentrations using a combination of the modified flux advection scheme from Easter (Mon. Wea. Rev., 1993) with tracer distributions given by the monotonic modified van Leer scheme proposed by Lin et al. (Mon. Wea. Rev., 1994). This scheme conserves the total amount of tracer while avoiding spurious maxima and minima of the tracer concentration. If a higher order accuracy scheme is needed, suggest monotonic piecewise parabolic method, as described in Carpenter et al. (MWR, 1990).
advect_tracer has 4 arguments, described below. This subroutine determines the volume of a layer in a grid cell at the previous instance when the tracer concentration was changed, so it is essential that the volume fluxes should be correct. It is also important that the tracer advection occurs before each calculation of the diabatic forcing.
Data Types
type tracer_advect_cs
Control structure for this module.
Functions/Subroutines
subroutine, public advect_tracer (h_end, uhtr, vhtr, OBC, dt, G, GV, CS, Reg, h_prev_opt, max_iter_in, x_first_in, uhr_out, vhr_out, h_out)
This routine time steps the tracer concentration using a monotonic, conservative, weakly diffusive scheme.
subroutine advect_x (Tr, hprev, uhr, uh_neglect, OBC, domore_u, ntr, Idt, is, ie, js, je, k, G, GV, usePPM, useHuynh)
This subroutine does 1-d flux-form advection in the zonal direction using a monotonic piecewise linear scheme.
subroutine advect_y (Tr, hprev, vhr, vh_neglect, OBC, domore_v, ntr, Idt, is, ie, js, je, k, G, GV, usePPM, useHuynh)
This subroutine does 1-d flux-form advection using a monotonic piecewise linear scheme.
subroutine, public tracer_advect_init (Time, G, param_file, diag, CS)
Initialize lateral tracer advection module.
subroutine, public tracer_advect_end (CS)
Close the tracer advection module.
Variables
integer id_clock_advect
integer id_clock_pass
integer id_clock_sync
Function/Subroutine Documentation
advect_tracer()
subroutine, public mom_tracer_advect::advect_tracer (real, dimension(g %isd: g %ied, g %jsd: g %jed, g %ke), intent(in) h_end, real, dimension(g %isdb: g %iedb, g %jsd: g %jed, g %ke), intent(in) uhtr, real, dimension(g %isd: g %ied, g %jsdb: g %jedb, g %ke), intent(in) vhtr, type(ocean_obc_type), pointer OBC, real, intent(in) dt, type(ocean_grid_type), intent(inout) G, type(verticalgrid_type), intent(in) GV, type(tracer_advect_cs), pointer CS, type(tracer_registry_type), pointer Reg, real, dimension(g %isd: g %ied, g %jsd: g %jed, g %ke), optional h_prev_opt, integer, optional max_iter_in, logical, optional x_first_in, real, dimension(g %isdb: g %iedb, g %jsd: g %jed, g %ke), intent(out), optional uhr_out, real, dimension(g %isd: g %ied, g %jsdb: g %jedb, g %ke), intent(out), optional vhr_out, real, dimension(g %isd: g %ied, g %jsd: g %jed, g %ke), optional h_out)
This routine time steps the tracer concentration using a monotonic, conservative, weakly diffusive scheme.
Parameters
[in,out] g ocean grid structure
[in] gv ocean vertical grid structure
[in] h_end layer thickness after advection (m or kg m-2)
[in] uhtr accumulated volume/mass flux through zonal face (m3 or kg)
[in] vhtr accumulated volume/mass flux through merid face (m3 or kg)
obc specifies whether, where, and what OBCs are used
[in] dt time increment (seconds)
cs control structure for module
reg pointer to tracer registry
h_prev_opt layer thickness before advection (m or kg m-2)
[out] uhr_out accumulated volume/mass flux through zonal face (m3 or kg)
[out] vhr_out accumulated volume/mass flux through merid face (m3 or kg)
h_out layer thickness before advection (m or kg m-2)
Definition at line 49 of file MOM_tracer_advect.F90.
References advect_x(), advect_y(), mom_domains::do_group_pass(), id_clock_advect, id_clock_pass, id_clock_sync, and mom_error_handler::mom_error().
Referenced by mom_offline_main::offline_advection_ale(), and mom_offline_main::offline_redistribute_residual().
   type(ocean_grid_type),                     intent(inout) :: g     !< ocean grid structure
   type(verticalgrid_type),                   intent(in)    :: gv    !< ocean vertical grid structure
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)),  intent(in)    :: h_end !< layer thickness after advection (m or kg m-2)
   real, dimension(SZIB_(G),SZJ_(G),SZK_(G)), intent(in)    :: uhtr  !< accumulated volume/mass flux through zonal face (m3 or kg)
   real, dimension(SZI_(G),SZJB_(G),SZK_(G)), intent(in)    :: vhtr  !< accumulated volume/mass flux through merid face (m3 or kg)
   type(ocean_obc_type),                      pointer       :: obc   !< specifies whether, where, and what OBCs are used
   real,                                      intent(in)    :: dt    !< time increment (seconds)
   type(tracer_advect_cs),                    pointer       :: cs    !< control structure for module
   type(tracer_registry_type),                pointer       :: reg   !< pointer to tracer registry
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)),  optional      :: h_prev_opt !< layer thickness before advection (m or kg m-2)
   integer,                                   optional      :: max_iter_in
   logical,                                   optional      :: x_first_in
   real, dimension(SZIB_(G),SZJ_(G),SZK_(G)), optional, intent(out)    :: uhr_out  !< accumulated volume/mass flux through zonal face (m3 or kg)
   real, dimension(SZI_(G),SZJB_(G),SZK_(G)), optional, intent(out)    :: vhr_out  !< accumulated volume/mass flux through merid face (m3 or kg)
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)),  optional      :: h_out !< layer thickness before advection (m or kg m-2)
   type(tracer_type) :: tr(max_fields_) ! The array of registered tracers
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)) :: &
     hprev           ! cell volume at the end of previous tracer change (m3)
   real, dimension(SZIB_(G),SZJ_(G),SZK_(G)) :: &
     uhr             ! The remaining zonal thickness flux (m3)
   real, dimension(SZI_(G),SZJB_(G),SZK_(G)) :: &
     vhr             ! The remaining meridional thickness fluxes (m3)
   real :: uh_neglect(szib_(g),szj_(g)) ! uh_neglect and vh_neglect are the
   real :: vh_neglect(szi_(g),szjb_(g)) ! magnitude of remaining transports that
                                        ! can be simply discarded (m3 or kg).
   real :: landvolfill                   ! An arbitrary? nonzero cell volume, m3.
   real :: idt                           ! 1/dt in s-1.
   logical :: domore_u(szj_(g),szk_(g))  ! domore__ indicate whether there is more
   logical :: domore_v(szjb_(g),szk_(g)) ! advection to be done in the corresponding
                                         ! row or column.
   logical :: x_first            ! If true, advect in the x-direction first.
   integer :: max_iter           ! maximum number of iterations in each layer
   integer :: domore_k(szk_(g))
   integer :: stencil            ! stencil of the advection scheme
   integer :: nsten_halo         ! number of stencils that fit in the halos
   integer :: i, j, k, m, is, ie, js, je, isd, ied, jsd, jed, nz, itt, ntr, do_any
   integer :: isv, iev, jsv, jev ! The valid range of the indices.
   integer :: isdb, iedb, jsdb, jedb
   domore_u(:,:) = .false.
   domore_v(:,:) = .false.
   is  = g%isc ; ie  = g%iec ; js  = g%jsc ; je  = g%jec ; nz = gv%ke
   isd = g%isd ; ied = g%ied ; jsd = g%jsd ; jed = g%jed
   isdb = g%IsdB ; iedb = g%IedB ; jsdb = g%JsdB ; jedb = g%JedB
   landvolfill = 1.0e-20         ! This is arbitrary, but must be positive.
   stencil = 2                   ! The scheme's stencil; 2 for PLM and PPM:H3
   if (.not. associated(cs)) call mom_error(fatal, "MOM_tracer_advect: "// &
        "tracer_advect_init must be called before advect_tracer.")
   if (.not. associated(reg)) call mom_error(fatal, "MOM_tracer_advect: "// &
        "register_tracer must be called before advect_tracer.")
   if (reg%ntr==0) return
   call cpu_clock_begin(id_clock_advect)
   x_first = (mod(g%first_direction,2) == 0)
   ! increase stencil size for Colella & Woodward PPM
   if (cs%usePPM .and. .not. cs%useHuynh) stencil = 3
   ntr = reg%ntr
   do m=1,ntr ; tr(m) = reg%Tr(m) ; enddo
   idt = 1.0/dt
   max_iter = 2*int(ceiling(dt/cs%dt)) + 1
   if(present(max_iter_in)) max_iter = max_iter_in
   if(present(x_first_in))  x_first = x_first_in
   call cpu_clock_begin(id_clock_pass)
   call create_group_pass(cs%pass_uhr_vhr_t_hprev, uhr, vhr, g%Domain)
   call create_group_pass(cs%pass_uhr_vhr_t_hprev, hprev, g%Domain)
   do m=1,ntr
     call create_group_pass(cs%pass_uhr_vhr_t_hprev, tr(m)%t, g%Domain)
   enddo
   call cpu_clock_end(id_clock_pass)
 !$OMP parallel default(none) shared(nz,jsd,jed,IsdB,IedB,uhr,jsdB,jedB,Isd,Ied,vhr, &
 !$OMP                               hprev,domore_k,js,je,is,ie,uhtr,vhtr,G,GV,h_end,&
 !$OMP                               uh_neglect,vh_neglect,ntr,Tr,h_prev_opt)
 ! This initializes the halos of uhr and vhr because pass_vector might do
 ! calculations on them, even though they are never used.
 !$OMP do
   do k = 1, nz
     do j = jsd,  jed;  do i = isdb, iedb; uhr(i,j,k) = 0.0; enddo ; enddo
     do j = jsdb, jedb; do i = isd,  ied;  vhr(i,j,k) = 0.0; enddo ; enddo
     do j = jsd,  jed;  do i = isd,  ied;  hprev(i,j,k) = 0.0; enddo ; enddo
     domore_k(k)=1
 !  Put the remaining (total) thickness fluxes into uhr and vhr.
     do j=js,je ; do i=is-1,ie ; uhr(i,j,k) = uhtr(i,j,k) ; enddo ; enddo
     do j=js-1,je ; do i=is,ie ; vhr(i,j,k) = vhtr(i,j,k) ; enddo ; enddo
     if (.not. present(h_prev_opt)) then
     !   This loop reconstructs the thickness field the last time that the
     ! tracers were updated, probably just after the diabatic forcing.  A useful
     ! diagnostic could be to compare this reconstruction with that older value.
         do i=is,ie ; do j=js,je
           hprev(i,j,k) = max(0.0, g%areaT(i,j)*h_end(i,j,k) + &
                ((uhr(i,j,k) - uhr(i-1,j,k)) + (vhr(i,j,k) - vhr(i,j-1,k))))
     ! In the case that the layer is now dramatically thinner than it was previously,
     ! add a bit of mass to avoid truncation errors.  This will lead to
     ! non-conservation of tracers
           hprev(i,j,k) = hprev(i,j,k) + &
                          max(0.0, 1.0e-13*hprev(i,j,k) - g%areaT(i,j)*h_end(i,j,k))
         enddo ; enddo
     else
       do i=is,ie ; do j=js,je
         hprev(i,j,k) = h_prev_opt(i,j,k);
       enddo ; enddo
     endif
   enddo
 !$OMP do
   do j=jsd,jed ; do i=isd,ied-1
     uh_neglect(i,j) = gv%H_subroundoff*min(g%areaT(i,j),g%areaT(i+1,j))
   enddo ; enddo
 !$OMP do
   do j=jsd,jed-1 ; do i=isd,ied
     vh_neglect(i,j) = gv%H_subroundoff*min(g%areaT(i,j),g%areaT(i,j+1))
   enddo ; enddo
 !$OMP do
   ! initialize diagnostic fluxes and tendencies
   do m=1,ntr
     if (associated(tr(m)%ad_x)) then
       do k=1,nz ; do j=jsd,jed ; do i=isd,ied
         tr(m)%ad_x(i,j,k) = 0.0
       enddo ; enddo ; enddo
     endif
     if (associated(tr(m)%ad_y)) then
       do k=1,nz ; do j=jsd,jed ; do i=isd,ied
         tr(m)%ad_y(i,j,k) = 0.0
       enddo ; enddo ; enddo
     endif
     if (associated(tr(m)%advection_xy)) then
       do k=1,nz ; do j=jsd,jed ; do i=isd,ied
         tr(m)%advection_xy(i,j,k) = 0.0
       enddo ; enddo ; enddo
     endif
     if (associated(tr(m)%ad2d_x)) then
       do j=jsd,jed ; do i=isd,ied ; tr(m)%ad2d_x(i,j) = 0.0 ; enddo ; enddo
     endif
     if (associated(tr(m)%ad2d_y)) then
       do j=jsd,jed ; do i=isd,ied ; tr(m)%ad2d_y(i,j) = 0.0 ; enddo ; enddo
     endif
   enddo
 !$OMP end parallel
   isv = is ; iev = ie ; jsv = js ; jev = je
   do itt=1,max_iter
     if (isv > is-stencil) then
       call cpu_clock_begin(id_clock_pass)
       call do_group_pass(cs%pass_uhr_vhr_t_hprev, g%Domain)
       call cpu_clock_end(id_clock_pass)
       nsten_halo = min(is-isd,ied-ie,js-jsd,jed-je)/stencil
       isv = is-nsten_halo*stencil ; jsv = js-nsten_halo*stencil
       iev = ie+nsten_halo*stencil ; jev = je+nsten_halo*stencil
       ! Reevaluate domore_u & domore_v unless the valid range is the same size as
       ! before.  Also, do this if there is Strang splitting.
       if ((nsten_halo > 1) .or. (itt==1)) then
 !$OMP parallel do default(none) shared(nz,domore_k,jsv,jev,domore_u,isv,iev,stencil, &
 !$OMP                                  uhr,domore_v,vhr)
         do k=1,nz ; if (domore_k(k) > 0) then
           do j=jsv,jev ; if (.not.domore_u(j,k)) then
             do i=isv+stencil-1,iev-stencil; if (uhr(i,j,k) /= 0.0) then
               domore_u(j,k) = .true. ; exit
             endif ; enddo ! i-loop
           endif ; enddo
           do j=jsv+stencil-1,jev-stencil ; if (.not.domore_v(j,k)) then
             do i=isv+stencil,iev-stencil; if (vhr(i,j,k) /= 0.0) then
               domore_v(j,k) = .true. ; exit
             endif ; enddo ! i-loop
           endif ; enddo
           !   At this point, domore_k is global.  Change it so that it indicates
           ! whether any work is needed on a layer on this processor.
           domore_k(k) = 0
           do j=jsv,jev ; if (domore_u(j,k)) domore_k(k) = 1 ; enddo
           do j=jsv+stencil-1,jev-stencil ; if (domore_v(j,k)) domore_k(k) = 1 ; enddo
         endif ; enddo ! k-loop
       endif
     endif
     ! Set the range of valid points after this iteration.
     isv = isv + stencil ; iev = iev - stencil
     jsv = jsv + stencil ; jev = jev - stencil
 !$OMP parallel do default(none) shared(nz,domore_k,x_first,Tr,hprev,uhr,uh_neglect,  &
 !$OMP                                  OBC,domore_u,ntr,Idt,isv,iev,jsv,jev,stencil, &
 !$OMP                                  G,GV,CS,vhr,vh_neglect,domore_v)
     !  To ensure positive definiteness of the thickness at each iteration, the
     !  mass fluxes out of each layer are checked each step, and limited to keep
     !  the thicknesses positive.  This means that several iterations may be required
     !  for all the transport to happen.  The sum over domore_k keeps the processors
     !  synchronized.  This may not be very efficient, but it should be reliable.
     do k=1,nz ; if (domore_k(k) > 0) then
       if (x_first) then
         ! First, advect zonally.
         call advect_x(tr, hprev, uhr, uh_neglect, obc, domore_u, ntr, idt, &
                       isv, iev, jsv-stencil, jev+stencil, k, g, gv, cs%usePPM, cs%useHuynh)
         !  Next, advect meridionally.
         call advect_y(tr, hprev, vhr, vh_neglect, obc, domore_v, ntr, idt, &
                       isv, iev, jsv, jev, k, g, gv, cs%usePPM, cs%useHuynh)
         domore_k(k) = 0
         do j=jsv-stencil,jev+stencil ; if (domore_u(j,k)) domore_k(k) = 1 ; enddo
         do j=jsv-1,jev ; if (domore_v(j,k)) domore_k(k) = 1 ; enddo
       else
         ! First, advect meridionally.
         call advect_y(tr, hprev, vhr, vh_neglect, obc, domore_v, ntr, idt, &
                       isv-stencil, iev+stencil, jsv, jev, k, g, gv, cs%usePPM, cs%useHuynh)
         ! Next, advect zonally.
         call advect_x(tr, hprev, uhr, uh_neglect, obc, domore_u, ntr, idt, &
                       isv, iev, jsv, jev, k, g, gv, cs%usePPM, cs%useHuynh)
         domore_k(k) = 0
         do j=jsv,jev ; if (domore_u(j,k)) domore_k(k) = 1 ; enddo
         do j=jsv-1,jev ; if (domore_v(j,k)) domore_k(k) = 1 ; enddo
       endif
     endif ; enddo ! End of k-loop
     ! If the advection just isn't finishing after max_iter, move on.
     if (itt >= max_iter) then
       exit
     endif
     ! Exit if there are no layers that need more iterations.
     if (isv > is-stencil) then
       do_any = 0
       call cpu_clock_begin(id_clock_sync)
       call sum_across_pes(domore_k(:), nz)
       call cpu_clock_end(id_clock_sync)
       do k=1,nz ; do_any = do_any + domore_k(k) ; enddo
       if (do_any == 0) then
         exit
       endif
     endif
   enddo ! Iterations loop
   if(present(uhr_out)) uhr_out(:,:,:) = uhr(:,:,:)
   if(present(vhr_out)) vhr_out(:,:,:) = vhr(:,:,:)
   if(present(h_out)) h_out(:,:,:) = hprev(:,:,:)
   call cpu_clock_end(id_clock_advect)
advect_x()
subroutine mom_tracer_advect::advect_x (type(tracer_type), dimension(ntr), intent(inout) Tr, real, dimension(g %isd: g %ied, g %jsd: g %jed, g %ke), intent(inout) hprev, real, dimension(g %isdb: g %iedb, g %jsd: g %jed, g %ke), intent(inout) uhr, real, dimension(g %isdb: g %iedb, g %jsd: g %jed), intent(inout) uh_neglect, type(ocean_obc_type), pointer OBC, logical, dimension(g %jsd: g %jed, g %ke), intent(inout) domore_u, integer, intent(in) ntr, real, intent(in) Idt, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) k, type(ocean_grid_type), intent(inout) G, type(verticalgrid_type), intent(in) GV, logical, intent(in) usePPM, logical, intent(in) useHuynh) private
This subroutine does 1-d flux-form advection in the zonal direction using a monotonic piecewise linear scheme.
Parameters
[in,out] g The ocean's grid structure
[in] gv The ocean's vertical grid structure
Definition at line 318 of file MOM_tracer_advect.F90.
Referenced by advect_tracer().
   type(ocean_grid_type),                     intent(inout) :: g    !< The ocean's grid structure
   type(verticalgrid_type),                   intent(in)    :: gv   !< The ocean's vertical grid structure
   type(tracer_type), dimension(ntr),         intent(inout) :: tr
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)),  intent(inout) :: hprev
   real, dimension(SZIB_(G),SZJ_(G),SZK_(G)), intent(inout) :: uhr
    real, dimension(SZIB_(G),SZJ_(G)),        intent(inout) :: uh_neglect
   type(ocean_obc_type),                      pointer       :: obc
   logical, dimension(SZJ_(G),SZK_(G)),       intent(inout) :: domore_u
   real,                                      intent(in)    :: idt
   integer,                                   intent(in)    :: ntr, is, ie, js, je,k
   logical,                                   intent(in)    :: useppm, usehuynh
   real, dimension(SZI_(G),ntr) :: &
     slope_x             ! The concentration slope per grid point in units of
                         ! concentration (nondim.).
   real, dimension(SZIB_(G),ntr) :: &
     flux_x              ! The tracer flux across a boundary in m3*conc or kg*conc.
   real :: maxslope      ! The maximum concentration slope per grid point
                         ! consistent with monotonicity, in conc. (nondim.).
   real :: hup, hlos     ! hup is the upwind volume, hlos is the
                         ! part of that volume that might be lost
                         ! due to advection out the other side of
                         ! the grid box, both in m3 or kg.
   real :: uhh(szib_(g)) ! The zonal flux that occurs during the
                         ! current iteration, in m3 or kg.
   real, dimension(SZIB_(G)) :: &
     hlst, ihnew, &      ! Work variables with units of m3 or kg and m-3 or kg-1.
     cfl                 ! A nondimensional work variable.
   real :: min_h         ! The minimum thickness that can be realized during
                         ! any of the passes, in m or kg m-2.
   real :: h_neglect     ! A thickness that is so small it is usually lost
                         ! in roundoff and can be neglected, in m.
   logical :: do_i(szib_(g))     ! If true, work on given points.
   logical :: do_any_i
   integer :: i, j, m, n, i_up, stencil
   real :: ar, al, dmx, dmn, tp, tc, tm, da, ma, a6
   logical :: useplmslope
   useplmslope = .not. (useppm .and. usehuynh)
   ! stencil for calculating slope values
   stencil = 1
   if (useppm .and. .not. usehuynh) stencil = 2
   min_h = 0.1*gv%Angstrom
   h_neglect = gv%H_subroundoff
 ! do I=is-1,ie ; ts2(I) = 0.0 ; enddo
   do i=is-1,ie ; cfl(i) = 0.0 ; enddo
   do j=js,je ; if (domore_u(j,k)) then
     domore_u(j,k) = .false.
     ! Calculate the i-direction profiles (slopes) of each tracer that
     ! is being advected.
     if (useplmslope) then
       do m=1,ntr ; do i=is-stencil,ie+stencil
        !if (ABS(Tr(m)%t(i+1,j,k)-Tr(m)%t(i,j,k)) < &
        !    ABS(Tr(m)%t(i,j,k)-Tr(m)%t(i-1,j,k))) then
        !  maxslope = 4.0*(Tr(m)%t(i+1,j,k)-Tr(m)%t(i,j,k))
        !else
        !  maxslope = 4.0*(Tr(m)%t(i,j,k)-Tr(m)%t(i-1,j,k))
        !endif
        !if ((Tr(m)%t(i+1,j,k)-Tr(m)%t(i,j,k)) * (Tr(m)%t(i,j,k)-Tr(m)%t(i-1,j,k)) < 0.0) then
        !  slope_x(i,m) = 0.0
        !elseif (ABS(Tr(m)%t(i+1,j,k)-Tr(m)%t(i-1,j,k))<ABS(maxslope)) then
        !  slope_x(i,m) = G%mask2dCu(I,j)*G%mask2dCu(I-1,j) * &
        !                 0.5*(Tr(m)%t(i+1,j,k)-Tr(m)%t(i-1,j,k))
        !else
        !  slope_x(i,m) = G%mask2dCu(I,j)*G%mask2dCu(I-1,j) * 0.5*maxslope
        !endif
         tp = tr(m)%t(i+1,j,k) ; tc = tr(m)%t(i,j,k) ; tm = tr(m)%t(i-1,j,k)
         dmx = max( tp, tc, tm ) - tc
         dmn= tc - min( tp, tc, tm )
         slope_x(i,m) = g%mask2dCu(i,j)*g%mask2dCu(i-1,j) * &
             sign( min(0.5*abs(tp-tm), 2.0*dmx, 2.0*dmn), tp-tm )
       enddo ; enddo
     endif ! usePLMslope
     ! Calculate the i-direction fluxes of each tracer, using as much
     ! the minimum of the remaining mass flux (uhr) and the half the mass
     ! in the cell plus whatever part of its half of the mass flux that
     ! the flux through the other side does not require.
     do i=is-1,ie
       if (uhr(i,j,k) == 0.0) then
         uhh(i) = 0.0
         cfl(i) = 0.0
       elseif (uhr(i,j,k) < 0.0) then
         hup = hprev(i+1,j,k) - g%areaT(i+1,j)*min_h
         hlos = max(0.0,uhr(i+1,j,k))
         if ((((hup - hlos) + uhr(i,j,k)) < 0.0) .and. &
             ((0.5*hup + uhr(i,j,k)) < 0.0)) then
           uhh(i) = min(-0.5*hup,-hup+hlos,0.0)
           domore_u(j,k) = .true.
         else
           uhh(i) = uhr(i,j,k)
         endif
        !ts2(I) = 0.5*(1.0 + uhh(I)/(hprev(i+1,j,k)+h_neglect))
         cfl(i) = - uhh(i)/(hprev(i+1,j,k)+h_neglect) ! CFL is positive
       else
         hup = hprev(i,j,k) - g%areaT(i,j)*min_h
         hlos = max(0.0,-uhr(i-1,j,k))
         if ((((hup - hlos) - uhr(i,j,k)) < 0.0) .and. &
             ((0.5*hup - uhr(i,j,k)) < 0.0)) then
           uhh(i) = max(0.5*hup,hup-hlos,0.0)
           domore_u(j,k) = .true.
         else
           uhh(i) = uhr(i,j,k)
         endif
        !ts2(I) = 0.5*(1.0 - uhh(I)/(hprev(i,j,k)+h_neglect))
         cfl(i) = uhh(i)/(hprev(i,j,k)+h_neglect) ! CFL is positive
       endif
     enddo
     if (useppm) then
       do m=1,ntr ; do i=is-1,ie
         ! centre cell depending on upstream direction
         if (uhh(i) >= 0.0) then
           i_up = i
         else
           i_up = i+1
         endif
         ! Implementation of PPM-H3
         tp = tr(m)%t(i_up+1,j,k) ; tc = tr(m)%t(i_up,j,k) ; tm = tr(m)%t(i_up-1,j,k)
         if (usehuynh) then
           al = ( 5.*tc + ( 2.*tm - tp ) )/6. ! H3 estimate
           al = max( min(tc,tm), al) ; al = min( max(tc,tm), al) ! Bound
           ar = ( 5.*tc + ( 2.*tp - tm ) )/6. ! H3 estimate
           ar = max( min(tc,tp), ar) ; ar = min( max(tc,tp), ar) ! Bound
         else
           al = 0.5 * ((tm + tc) + (slope_x(i_up-1,m) - slope_x(i_up,m)) / 3.)
           ar = 0.5 * ((tc + tp) + (slope_x(i_up,m) - slope_x(i_up+1,m)) / 3.)
         endif
         da = ar - al ; ma = 0.5*( ar + al )
         if (g%mask2dCu(i_up,j)*g%mask2dCu(i_up-1,j)*(tp-tc)*(tc-tm) <= 0.) then
            al = tc ; ar = tc ! PCM for local extremum and bounadry cells
         elseif ( da*(tc-ma) > (da*da)/6. ) then
            al = 3.*tc - 2.*ar
         elseif ( da*(tc-ma) < - (da*da)/6. ) then
            ar = 3.*tc - 2.*al
         endif
         a6 = 6.*tc - 3. * (ar + al) ! Curvature
         if (uhh(i) >= 0.0) then
           flux_x(i,m) = uhh(i)*( ar - 0.5 * cfl(i) * ( &
                ( ar - al ) - a6 * ( 1. - 2./3. * cfl(i) ) ) )
         else
           flux_x(i,m) = uhh(i)*( al + 0.5 * cfl(i) * ( &
                ( ar - al ) + a6 * ( 1. - 2./3. * cfl(i) ) ) )
         endif
       enddo ; enddo
     else ! PLM
       do m=1,ntr ; do i=is-1,ie
         if (uhh(i) >= 0.0) then
           ! Indirect implementation of PLM
          !aL = Tr(m)%t(i,j,k) - 0.5 * slope_x(i,m)
          !aR = Tr(m)%t(i,j,k) + 0.5 * slope_x(i,m)
          !flux_x(I,m) = uhh(I)*( aR - 0.5 * (aR-aL) * CFL(I) )
           ! Alternative implementation of PLM
          !aR = Tr(m)%t(i,j,k) + 0.5 * slope_x(i,m)
          !flux_x(I,m) = uhh(I)*( aR - 0.5 * slope_x(i,m) * CFL(I) )
           ! Alternative implementation of PLM
           tc = tr(m)%t(i,j,k)
           flux_x(i,m) = uhh(i)*( tc + 0.5 * slope_x(i,m) * ( 1. - cfl(i) ) )
           ! Original implementation of PLM
          !flux_x(I,m) = uhh(I)*(Tr(m)%t(i,j,k) + slope_x(i,m)*ts2(I))
         else
           ! Indirect implementation of PLM
          !aL = Tr(m)%t(i+1,j,k) - 0.5 * slope_x(i+1,m)
          !aR = Tr(m)%t(i+1,j,k) + 0.5 * slope_x(i+1,m)
          !flux_x(I,m) = uhh(I)*( aL + 0.5 * (aR-aL) * CFL(I) )
           ! Alternative implementation of PLM
          !aL = Tr(m)%t(i+1,j,k) - 0.5 * slope_x(i+1,m)
          !flux_x(I,m) = uhh(I)*( aL + 0.5 * slope_x(i+1,m) * CFL(I) )
           ! Alternative implementation of PLM
           tc = tr(m)%t(i+1,j,k)
           flux_x(i,m) = uhh(i)*( tc - 0.5 * slope_x(i+1,m) * ( 1. - cfl(i) ) )
           ! Original implementation of PLM
          !flux_x(I,m) = uhh(I)*(Tr(m)%t(i+1,j,k) - slope_x(i+1,m)*ts2(I))
         endif
        !ts2(I) = 0.5*(1.0 - uhh(I)/(hprev(i,j,k)+h_neglect))
       enddo ; enddo
     endif ! usePPM
     if (associated(obc)) then ; if (obc%OBC_pe) then ; if (obc%specified_u_BCs_exist_globally) then
       do n=1,obc%number_of_segments
         if (obc%segment(n)%is_E_or_W) then
           if (j >= obc%segment(n)%HI%jsd .and. j<= obc%segment(n)%HI%jed) then
             i = obc%segment(n)%HI%IsdB
             ! Tracer fluxes are set to prescribed values only for inflows from masked areas.
             if ((uhr(i,j,k) > 0.0) .and. (g%mask2dT(i,j) < 0.5) .or. &
                 (uhr(i,j,k) < 0.0) .and. (g%mask2dT(i+1,j) < 0.5)) then
               uhh(i) = uhr(i,j,k)
               do m=1,ntr
                 if (associated(tr(m)%OBC_in_u)) then
                   flux_x(i,m) = uhh(i)*tr(m)%OBC_in_u(i,j,k)
                 else ; flux_x(i,m) = uhh(i)*tr(m)%OBC_inflow_conc ; endif
               enddo
             endif
           endif
         endif
       enddo
     endif ; endif ; endif
     ! Calculate new tracer concentration in each cell after accounting
     ! for the i-direction fluxes.
     do i=is-1,ie
       uhr(i,j,k) = uhr(i,j,k) - uhh(i)
       if (abs(uhr(i,j,k)) < uh_neglect(i,j)) uhr(i,j,k) = 0.0
     enddo
     do i=is,ie
       if ((uhh(i) /= 0.0) .or. (uhh(i-1) /= 0.0)) then
         do_i(i) = .true.
         hlst(i) = hprev(i,j,k)
         hprev(i,j,k) = hprev(i,j,k) - (uhh(i) - uhh(i-1))
         if (hprev(i,j,k) <= 0.0) then ; do_i(i) = .false.
         elseif (hprev(i,j,k) < h_neglect*g%areaT(i,j)) then
           hlst(i) = hlst(i) + (h_neglect*g%areaT(i,j) - hprev(i,j,k))
           ihnew(i) = 1.0 / (h_neglect*g%areaT(i,j))
         else ;  ihnew(i) = 1.0 / hprev(i,j,k) ; endif
       else
         do_i(i) = .false.
       endif
     enddo
     ! update tracer concentration from i-flux and save some diagnostics
     do m=1,ntr
       ! update tracer
       do i=is,ie ; if ((do_i(i)) .and. (ihnew(i) > 0.0)) then
         tr(m)%t(i,j,k) = (tr(m)%t(i,j,k) * hlst(i) - &
                           (flux_x(i,m) - flux_x(i-1,m))) * ihnew(i)
       endif ; enddo
       ! diagnostics
       if (associated(tr(m)%ad_x)) then ; do i=is,ie ; if (do_i(i)) then
         tr(m)%ad_x(i,j,k) = tr(m)%ad_x(i,j,k) + flux_x(i,m)*idt
       endif ; enddo ; endif
       if (associated(tr(m)%ad2d_x)) then ; do i=is,ie ; if (do_i(i)) then
         tr(m)%ad2d_x(i,j) = tr(m)%ad2d_x(i,j) + flux_x(i,m)*idt
       endif ; enddo ; endif
       ! diagnose convergence of flux_x (do not use the Ihnew(i) part of the logic).
       ! division by areaT to get into W/m2 for heat and kg/(s*m2) for salt.
       if (associated(tr(m)%advection_xy)) then
         do i=is,ie ; if (do_i(i)) then
           tr(m)%advection_xy(i,j,k) = tr(m)%advection_xy(i,j,k) - (flux_x(i,m) - flux_x(i-1,m)) * idt * g%IareaT(i,j)
         endif ; enddo
       endif
     enddo
   endif ; enddo ! End of j-loop.
advect_y()
subroutine mom_tracer_advect::advect_y (type(tracer_type), dimension(ntr), intent(inout) Tr, real, dimension(g %isd: g %ied, g %jsd: g %jed, g %ke), intent(inout) hprev, real, dimension(g %isd: g %ied, g %jsdb: g %jedb, g %ke), intent(inout) vhr, real, dimension(g %isd: g %ied, g %jsdb: g %jedb), intent(inout) vh_neglect, type(ocean_obc_type), pointer OBC, logical, dimension(g %jsdb: g %jedb, g %ke), intent(inout) domore_v, integer, intent(in) ntr, real, intent(in) Idt, integer, intent(in) is, integer, intent(in) ie, integer, intent(in) js, integer, intent(in) je, integer, intent(in) k, type(ocean_grid_type), intent(inout) G, type(verticalgrid_type), intent(in) GV, logical, intent(in) usePPM, logical, intent(in) useHuynh) private
This subroutine does 1-d flux-form advection using a monotonic piecewise linear scheme.
Parameters
[in,out] g The ocean's grid structure
[in] gv The ocean's vertical grid structure
Definition at line 582 of file MOM_tracer_advect.F90.
Referenced by advect_tracer().
   type(ocean_grid_type),                     intent(inout) :: g    !< The ocean's grid structure
   type(verticalgrid_type),                   intent(in)    :: gv   !< The ocean's vertical grid structure
   type(tracer_type), dimension(ntr),         intent(inout) :: tr
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)),  intent(inout) :: hprev
   real, dimension(SZI_(G),SZJB_(G),SZK_(G)), intent(inout) :: vhr
   real, dimension(SZI_(G),SZJB_(G)),         intent(inout) :: vh_neglect
   type(ocean_obc_type),                      pointer       :: obc
   logical, dimension(SZJB_(G),SZK_(G)),      intent(inout) :: domore_v
   real,                                      intent(in)    :: idt
   integer,                                   intent(in)    :: ntr, is, ie, js, je,k
   logical,                                   intent(in)    :: useppm, usehuynh
   real, dimension(SZI_(G),ntr,SZJ_(G)) :: &
     slope_y                     ! The concentration slope per grid point in units of
                                 ! concentration (nondim.).
   real, dimension(SZI_(G),ntr,SZJB_(G)) :: &
     flux_y                      ! The tracer flux across a boundary in m3 * conc or kg*conc.
   real :: maxslope              ! The maximum concentration slope per grid point
                                 ! consistent with monotonicity, in conc. (nondim.).
   real :: vhh(szi_(g),szjb_(g)) ! The meridional flux that occurs during the
                                 ! current iteration, in m3 or kg.
   real :: hup, hlos             ! hup is the upwind volume, hlos is the
                                 ! part of that volume that might be lost
                                 ! due to advection out the other side of
                                 ! the grid box, both in m3 or kg.
   real, dimension(SZIB_(G)) :: &
     hlst, ihnew, &      ! Work variables with units of m3 or kg and m-3 or kg-1.
     cfl                 ! A nondimensional work variable.
   real :: min_h         ! The minimum thickness that can be realized during
                         ! any of the passes, in m or kg m-2.
   real :: h_neglect     ! A thickness that is so small it is usually lost
                         ! in roundoff and can be neglected, in m.
   logical :: do_j_tr(szj_(g))   ! If true, calculate the tracer profiles.
   logical :: do_i(szib_(g))     ! If true, work on given points.
   logical :: do_any_i
   integer :: i, j, j2, m, n, j_up, stencil
   real :: ar, al, dmx, dmn, tp, tc, tm, da, ma, a6
   logical :: useplmslope
   useplmslope = .not. (useppm .and. usehuynh)
   ! stencil for calculating slope values
   stencil = 1
   if (useppm .and. .not. usehuynh) stencil = 2
   min_h = 0.1*gv%Angstrom
   h_neglect = gv%H_subroundoff
   !do i=is,ie ; ts2(i) = 0.0 ; enddo
   ! We conditionally perform work on tracer points: calculating the PLM slope,
   ! and updating tracer concentration within a cell
   ! this depends on whether there is a flux which would affect this tracer point,
   ! as indicated by domore_v. In the case of PPM reconstruction, a flux requires
   ! slope calculations at the two tracer points on either side (as indicated by
   ! the stencil variable), so we account for this with the do_j_tr flag array
   !
   ! Note: this does lead to unnecessary work in updating tracer concentrations,
   ! since that doesn't need a wider stencil with the PPM advection scheme, but
   ! this would require an additional loop, etc.
   do_j_tr(:) = .false.
   do j=js-1,je ; if (domore_v(j,k)) then ; do j2=1-stencil,stencil ; do_j_tr(j+j2) = .true. ; enddo ; endif ; enddo
   ! Calculate the j-direction profiles (slopes) of each tracer that
   ! is being advected.
   if (useplmslope) then
     do j=js-stencil,je+stencil ; if (do_j_tr(j)) then ; do m=1,ntr ; do i=is,ie
       !if (ABS(Tr(m)%t(i,j+1,k)-Tr(m)%t(i,j,k)) < &
       !    ABS(Tr(m)%t(i,j,k)-Tr(m)%t(i,j-1,k))) then
       !  maxslope = 4.0*(Tr(m)%t(i,j+1,k)-Tr(m)%t(i,j,k))
       !else
       !  maxslope = 4.0*(Tr(m)%t(i,j,k)-Tr(m)%t(i,j-1,k))
       !endif
       !if ((Tr(m)%t(i,j+1,k)-Tr(m)%t(i,j,k))*(Tr(m)%t(i,j,k)-Tr(m)%t(i,j-1,k)) < 0.0) then
       !  slope_y(i,m,j) = 0.0
       !elseif (ABS(Tr(m)%t(i,j+1,k)-Tr(m)%t(i,j-1,k))<ABS(maxslope)) then
       !  slope_y(i,m,j) = G%mask2dCv(i,J) * G%mask2dCv(i,J-1) * &
       !                 0.5*(Tr(m)%t(i,j+1,k)-Tr(m)%t(i,j-1,k))
       !else
       !  slope_y(i,m,j) = G%mask2dCv(i,J) * G%mask2dCv(i,J-1) * 0.5*maxslope
       !endif
        tp = tr(m)%t(i,j+1,k) ; tc = tr(m)%t(i,j,k) ; tm = tr(m)%t(i,j-1,k)
        dmx = max( tp, tc, tm ) - tc
        dmn= tc - min( tp, tc, tm )
        slope_y(i,m,j) = g%mask2dCv(i,j)*g%mask2dCv(i,j-1) * &
            sign( min(0.5*abs(tp-tm), 2.0*dmx, 2.0*dmn), tp-tm )
     enddo ; enddo ; endif ; enddo ! End of i-, m-, & j- loops.
   endif ! usePLMslope
   ! Calculate the j-direction fluxes of each tracer, using as much
   ! the minimum of the remaining mass flux (vhr) and the half the mass
   ! in the cell plus whatever part of its half of the mass flux that
   ! the flux through the other side does not require.
   do j=js-1,je ; if (domore_v(j,k)) then
     domore_v(j,k) = .false.
     do i=is,ie
       if (vhr(i,j,k) == 0.0) then
         vhh(i,j) = 0.0
         cfl(i) = 0.0
       elseif (vhr(i,j,k) < 0.0) then
         hup = hprev(i,j+1,k) - g%areaT(i,j+1)*min_h
         hlos = max(0.0,vhr(i,j+1,k))
         if ((((hup - hlos) + vhr(i,j,k)) < 0.0) .and. &
             ((0.5*hup + vhr(i,j,k)) < 0.0)) then
           vhh(i,j) = min(-0.5*hup,-hup+hlos,0.0)
           domore_v(j,k) = .true.
         else
           vhh(i,j) = vhr(i,j,k)
         endif
        !ts2(i) = 0.5*(1.0 + vhh(i,J) / (hprev(i,j+1,k)+h_neglect))
         cfl(i) = - vhh(i,j) / (hprev(i,j+1,k)+h_neglect) ! CFL is positive
       else
         hup = hprev(i,j,k) - g%areaT(i,j)*min_h
         hlos = max(0.0,-vhr(i,j-1,k))
         if ((((hup - hlos) - vhr(i,j,k)) < 0.0) .and. &
             ((0.5*hup - vhr(i,j,k)) < 0.0)) then
           vhh(i,j) = max(0.5*hup,hup-hlos,0.0)
           domore_v(j,k) = .true.
         else
           vhh(i,j) = vhr(i,j,k)
         endif
        !ts2(i) = 0.5*(1.0 - vhh(i,J) / (hprev(i,j,k)+h_neglect))
         cfl(i) = vhh(i,j) / (hprev(i,j,k)+h_neglect) ! CFL is positive
       endif
     enddo
     if (useppm) then
       do m=1,ntr ; do i=is,ie
         ! centre cell depending on upstream direction
         if (vhh(i,j) >= 0.0) then
           j_up = j
         else
           j_up = j + 1
         endif
         ! Implementation of PPM-H3
         tp = tr(m)%t(i,j_up+1,k) ; tc = tr(m)%t(i,j_up,k) ; tm = tr(m)%t(i,j_up-1,k)
         if (usehuynh) then
           al = ( 5.*tc + ( 2.*tm - tp ) )/6. ! H3 estimate
           al = max( min(tc,tm), al) ; al = min( max(tc,tm), al) ! Bound
           ar = ( 5.*tc + ( 2.*tp - tm ) )/6. ! H3 estimate
           ar = max( min(tc,tp), ar) ; ar = min( max(tc,tp), ar) ! Bound
         else
           al = 0.5 * ((tm + tc) + (slope_y(i,m,j_up-1) - slope_y(i,m,j_up)) / 3.)
           ar = 0.5 * ((tc + tp) + (slope_y(i,m,j_up) - slope_y(i,m,j_up+1)) / 3.)
         endif
         da = ar - al ; ma = 0.5*( ar + al )
         if (g%mask2dCv(i,j_up)*g%mask2dCv(i,j_up-1)*(tp-tc)*(tc-tm) <= 0.) then
           al = tc ; ar = tc ! PCM for local extremum and bounadry cells
         elseif ( da*(tc-ma) > (da*da)/6. ) then
           al = 3.*tc - 2.*ar
         elseif ( da*(tc-ma) < - (da*da)/6. ) then
           ar = 3.*tc - 2.*al
         endif
         a6 = 6.*tc - 3. * (ar + al) ! Curvature
         if (vhh(i,j) >= 0.0) then
           flux_y(i,m,j) = vhh(i,j)*( ar - 0.5 * cfl(i) * ( &
                ( ar - al ) - a6 * ( 1. - 2./3. * cfl(i) ) ) )
         else
           flux_y(i,m,j) = vhh(i,j)*( al + 0.5 * cfl(i) * ( &
                ( ar - al ) + a6 * ( 1. - 2./3. * cfl(i) ) ) )
         endif
       enddo ; enddo
     else ! PLM
       do m=1,ntr ; do i=is,ie
         if (vhh(i,j) >= 0.0) then
           ! Indirect implementation of PLM
          !aL = Tr(m)%t(i,j,k) - 0.5 * slope_y(i,m,j)
          !aR = Tr(m)%t(i,j,k) + 0.5 * slope_y(i,m,j)
          !flux_y(i,m,J) = vhh(i,J)*( aR - 0.5 * (aR-aL) * CFL(i) )
           ! Alternative implementation of PLM
          !aR = Tr(m)%t(i,j,k) + 0.5 * slope_y(i,m,j)
          !flux_y(i,m,J) = vhh(i,J)*(aR - 0.5 * slope_y(i,m,j)*CFL(i))
           ! Alternative implementation of PLM
           tc = tr(m)%t(i,j,k)
           flux_y(i,m,j) = vhh(i,j)*( tc + 0.5 * slope_y(i,m,j) * ( 1. - cfl(i) ) )
           ! Original implementation of PLM
          !flux_y(i,m,J) = vhh(i,J)*(Tr(m)%t(i,j,k) + slope_y(i,m,j)*ts2(i))
         else
           ! Indirect implementation of PLM
          !aL = Tr(m)%t(i,j+1,k) - 0.5 * slope_y(i,m,j+1)
          !aR = Tr(m)%t(i,j+1,k) + 0.5 * slope_y(i,m,j+1)
          !flux_y(i,m,J) = vhh(i,J)*( aL + 0.5 * (aR-aL) * CFL(i) )
           ! Alternative implementation of PLM
          !aL = Tr(m)%t(i,j+1,k) - 0.5 * slope_y(i,m,j+1)
          !flux_y(i,m,J) = vhh(i,J)*( aL + 0.5 * slope_y(i,m,j+1)*CFL(i) )
           ! Alternative implementation of PLM
           tc = tr(m)%t(i,j+1,k)
           flux_y(i,m,j) = vhh(i,j)*( tc - 0.5 * slope_y(i,m,j+1) * ( 1. - cfl(i) ) )
           ! Original implementation of PLM
          !flux_y(i,m,J) = vhh(i,J)*(Tr(m)%t(i,j+1,k) - slope_y(i,m,j+1)*ts2(i))
         endif
       enddo ; enddo
     endif ! usePPM
     if (associated(obc)) then ; if (obc%OBC_pe) then ; if (obc%specified_v_BCs_exist_globally) then
       do n=1,obc%number_of_segments
         if (obc%segment(n)%is_N_or_S) then
           if (j >= obc%segment(n)%HI%JsdB .and. j<= obc%segment(n)%HI%JedB) then
             i = obc%segment(n)%HI%isd
             ! Tracer fluxes are set to prescribed values only for inflows from masked areas.
             if ((vhr(i,j,k) > 0.0) .and. (g%mask2dT(i,j) < 0.5) .or. &
                 (vhr(i,j,k) < 0.0) .and. (g%mask2dT(i,j+1) < 0.5)) then
               vhh(i,j) = vhr(i,j,k)
               do m=1,ntr
                 if (associated(tr(m)%OBC_in_v)) then
                   flux_y(i,m,j) = vhh(i,j)*tr(m)%OBC_in_v(i,j,k)
                 else ; flux_y(i,m,j) = vhh(i,j)*tr(m)%OBC_inflow_conc ; endif
               enddo
             endif
           endif
         endif
       enddo
     endif ; endif ; endif
   else ! not domore_v.
     do i=is,ie ; vhh(i,j) = 0.0 ; enddo
     do m=1,ntr ; do i=is,ie ; flux_y(i,m,j) = 0.0 ; enddo ; enddo
   endif ; enddo ! End of j-loop
   do j=js-1,je ; do i=is,ie
     vhr(i,j,k) = vhr(i,j,k) - vhh(i,j)
     if (abs(vhr(i,j,k)) < vh_neglect(i,j)) vhr(i,j,k) = 0.0
   enddo ; enddo
   ! Calculate new tracer concentration in each cell after accounting
   ! for the j-direction fluxes.
   do j=js,je ; if (do_j_tr(j)) then
     do i=is,ie
       if ((vhh(i,j) /= 0.0) .or. (vhh(i,j-1) /= 0.0)) then
         do_i(i) = .true.
         hlst(i) = hprev(i,j,k)
         hprev(i,j,k) = max(hprev(i,j,k) - (vhh(i,j) - vhh(i,j-1)), 0.0)
         if (hprev(i,j,k) <= 0.0) then ; do_i(i) = .false.
         elseif (hprev(i,j,k) < h_neglect*g%areaT(i,j)) then
           hlst(i) = hlst(i) + (h_neglect*g%areaT(i,j) - hprev(i,j,k))
           ihnew(i) = 1.0 / (h_neglect*g%areaT(i,j))
         else ;  ihnew(i) = 1.0 / hprev(i,j,k) ; endif
       else ; do_i(i) = .false. ; endif
     enddo
     ! update tracer and save some diagnostics
     do m=1,ntr
       do i=is,ie ; if (do_i(i)) then
         tr(m)%t(i,j,k) = (tr(m)%t(i,j,k) * hlst(i) - &
                           (flux_y(i,m,j) - flux_y(i,m,j-1))) * ihnew(i)
       endif ; enddo
       ! diagnostics
       if (associated(tr(m)%ad_y)) then ; do i=is,ie ; if (do_i(i)) then
         tr(m)%ad_y(i,j,k) = tr(m)%ad_y(i,j,k) + flux_y(i,m,j)*idt
       endif ; enddo ; endif
       if (associated(tr(m)%ad2d_y)) then ; do i=is,ie ; if (do_i(i)) then
         tr(m)%ad2d_y(i,j) = tr(m)%ad2d_y(i,j) + flux_y(i,m,j)*idt
       endif ; enddo ; endif
       ! diagnose convergence of flux_y and add to convergence of flux_x.
       ! division by areaT to get into W/m2 for heat and kg/(s*m2) for salt.
       if (associated(tr(m)%advection_xy)) then
         do i=is,ie ; if (do_i(i)) then
           tr(m)%advection_xy(i,j,k) = tr(m)%advection_xy(i,j,k) - (flux_y(i,m,j) - flux_y(i,m,j-1))* idt * g%IareaT(i,j)
         endif ; enddo
       endif
     enddo
   endif ; enddo ! End of j-loop.
tracer_advect_end()
subroutine, public mom_tracer_advect::tracer_advect_end (type(tracer_advect_cs), pointer CS)
Close the tracer advection module.
Definition at line 912 of file MOM_tracer_advect.F90.
   type(tracer_advect_cs), pointer :: cs
   if (associated(cs)) deallocate(cs)
tracer_advect_init()
subroutine, public mom_tracer_advect::tracer_advect_init (type(time_type), intent(in), target Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(tracer_advect_cs), pointer CS)
Initialize lateral tracer advection module.
Parameters
[in] time current model time
[in] g ocean grid structure
[in] param_file open file to parse for model parameters
[in,out] diag regulates diagnostic output
cs module control structure
Definition at line 858 of file MOM_tracer_advect.F90.
References id_clock_advect, id_clock_pass, id_clock_sync, and mom_error_handler::mom_error().
   type(time_type), target, intent(in)    :: time        !< current model time
   type(ocean_grid_type),   intent(in)    :: g           !< ocean grid structure
   type(param_file_type),   intent(in)    :: param_file  !< open file to parse for model parameters
   type(diag_ctrl), target, intent(inout) :: diag        !< regulates diagnostic output
   type(tracer_advect_cs),  pointer       :: cs          !< module control structure
   integer, save :: init_calls = 0
 ! This include declares and sets the variable "version".
 #include "version_variable.h"
   character(len=40)  :: mdl = "MOM_tracer_advect" ! This module's name.
   character(len=256) :: mesg    ! Message for error messages.
   if (associated(cs)) then
     call mom_error(warning, "tracer_advect_init called with associated control structure.")
     return
   endif
   allocate(cs)
   cs%diag => diag
   ! Read all relevant parameters and write them to the model log.
   call log_version(param_file, mdl, version, "")
   call get_param(param_file, mdl, "DT", cs%dt, fail_if_missing=.true., &
           desc="The (baroclinic) dynamics time step.", units="s")
   call get_param(param_file, mdl, "DEBUG", cs%debug, default=.false.)
   call get_param(param_file, mdl, "TRACER_ADVECTION_SCHEME", mesg, &
           desc="The horizontal transport scheme for tracers:\n"//&
           "  PLM    - Piecewise Linear Method\n"//&
           "  PPM:H3 - Piecewise Parabolic Method (Huyhn 3rd order)\n"// &
           "  PPM    - Piecewise Parabolic Method (Colella-Woodward)" &
           , default='PLM')
   select case (trim(mesg))
     case ("PLM")
       cs%usePPM = .false.
     case ("PPM:H3")
       cs%usePPM = .true.
       cs%useHuynh = .true.
     case ("PPM")
       cs%usePPM = .true.
       cs%useHuynh = .false.
     case default
       call mom_error(fatal, "MOM_tracer_advect, tracer_advect_init: "//&
            "Unknown TRACER_ADVECTION_SCHEME = "//trim(mesg))
   end select
   id_clock_advect = cpu_clock_id('(Ocean advect tracer)', grain=clock_module)
   id_clock_pass = cpu_clock_id('(Ocean tracer halo updates)', grain=clock_routine)
   id_clock_sync = cpu_clock_id('(Ocean tracer global synch)', grain=clock_routine)
Variable Documentation
id_clock_advect
integer mom_tracer_advect::id_clock_advect
Definition at line 39 of file MOM_tracer_advect.F90.
Referenced by advect_tracer(), and tracer_advect_init().
 integer :: id_clock_advect
id_clock_pass
integer mom_tracer_advect::id_clock_pass private
Definition at line 40 of file MOM_tracer_advect.F90.
Referenced by advect_tracer(), and tracer_advect_init().
 integer :: id_clock_pass
id_clock_sync
integer mom_tracer_advect::id_clock_sync private
Definition at line 41 of file MOM_tracer_advect.F90.
Referenced by advect_tracer(), and tracer_advect_init().
 integer :: id_clock_sync