MOM6: coord_sigma Module Reference
coord_sigma Module Reference
Detailed Description
Regrid columns for the sigma coordinate.
Data Types
type sigma_cs
Control structure containing required parameters for the sigma coordinate.
Functions/Subroutines
subroutine, public init_coord_sigma (CS, nk, coordinateResolution)
Initialise a sigma_CS with pointers to parameters.
subroutine, public end_coord_sigma (CS)
subroutine, public set_sigma_params (CS, min_thickness)
subroutine, public build_sigma_column (CS, nz, depth, totalThickness, zInterface)
Build a sigma coordinate column.
Function/Subroutine Documentation
build_sigma_column()
subroutine, public coord_sigma::build_sigma_column (type(sigma_cs), intent(in) CS, integer, intent(in) nz, real, intent(in) depth, real, intent(in) totalThickness, real, dimension(nz+1), intent(inout) zInterface)
Build a sigma coordinate column.
Parameters
[in] cs Coordinate control structure
[in] nz Number of levels
[in] depth Depth of ocean bottom (positive in m)
[in] totalthickness Column thickness (positive in m)
[in,out] zinterface Absolute positions of interfaces
Definition at line 61 of file coord_sigma.F90.
Referenced by mom_regridding::build_sigma_grid(), and mom_diag_remap::diag_remap_update().
   type(sigma_cs),        intent(in)    :: cs !< Coordinate control structure
   integer,               intent(in)    :: nz !< Number of levels
   real,                  intent(in)    :: depth !< Depth of ocean bottom (positive in m)
   real,                  intent(in)    :: totalthickness !< Column thickness (positive in m)
   real, dimension(nz+1), intent(inout) :: zinterface !< Absolute positions of interfaces
   ! Local variables
   integer :: k
   zinterface(nz+1) = -depth
   do k = nz,1,-1
     zinterface(k) = zinterface(k+1) + (totalthickness * cs%coordinateResolution(k))
     ! Adjust interface position to accomodate inflating layers
     ! without disturbing the interface above
     if (zinterface(k) < (zinterface(k+1) + cs%min_thickness)) then
       zinterface(k) = zinterface(k+1) + cs%min_thickness
     endif
   enddo
end_coord_sigma()
subroutine, public coord_sigma::end_coord_sigma (type(sigma_cs), pointer CS)
Definition at line 41 of file coord_sigma.F90.
Referenced by mom_regridding::end_regridding().
   type(sigma_cs), pointer :: cs
   ! nothing to do
   if (.not. associated(cs)) return
   deallocate(cs%coordinateResolution)
   deallocate(cs)
init_coord_sigma()
subroutine, public coord_sigma::init_coord_sigma (type(sigma_cs), pointer CS, integer, intent(in) nk, real, dimension(:), intent(in) coordinateResolution)
Initialise a sigma_CS with pointers to parameters.
Parameters
cs Unassociated pointer to hold the control structure
Definition at line 28 of file coord_sigma.F90.
References mom_error_handler::mom_error().
   type(sigma_cs),     pointer    :: cs !< Unassociated pointer to hold the control structure
   integer,            intent(in) :: nk
   real, dimension(:), intent(in) :: coordinateresolution
   if (associated(cs)) call mom_error(fatal, "init_coord_sigma: CS already associated!")
   allocate(cs)
   allocate(cs%coordinateResolution(nk))
   cs%nk                   = nk
   cs%coordinateResolution = coordinateresolution
set_sigma_params()
subroutine, public coord_sigma::set_sigma_params (type(sigma_cs), pointer CS, real, intent(in), optional min_thickness)
Definition at line 50 of file coord_sigma.F90.
References mom_error_handler::mom_error().
   type(sigma_cs), pointer    :: cs
   real, optional, intent(in) :: min_thickness
   if (.not. associated(cs)) call mom_error(fatal, "set_sigma_params: CS not associated")
   if (present(min_thickness)) cs%min_thickness = min_thickness