MOM6: mom_checksums Module Reference
mom_checksums Module Reference
Data Types
interface bchksum
interface bchksum_pair
interface chk_sum_msg
interface chksum
interface hchksum
interface hchksum_pair
interface is_nan
interface qchksum
interface uchksum
interface uvchksum
interface vchksum
Functions/Subroutines
subroutine chksum_pair_h_2d (mesg, arrayA, arrayB, HI, haloshift, omit_corners, scale)
subroutine chksum_pair_h_3d (mesg, arrayA, arrayB, HI, haloshift, omit_corners, scale)
subroutine chksum_h_2d (array, mesg, HI, haloshift, omit_corners, scale)
chksum_h_2d performs checksums on a 2d array staggered at tracer points.
subroutine chksum_pair_b_2d (mesg, arrayA, arrayB, HI, haloshift, symmetric, omit_corners, scale)
subroutine chksum_pair_b_3d (mesg, arrayA, arrayB, HI, haloshift, symmetric, omit_corners, scale)
subroutine chksum_b_2d (array, mesg, HI, haloshift, symmetric, omit_corners, scale)
chksum_B_2d performs checksums on a 2d array staggered at corner points.
subroutine chksum_uv_2d (mesg, arrayU, arrayV, HI, haloshift, symmetric, omit_corners, scale)
subroutine chksum_uv_3d (mesg, arrayU, arrayV, HI, haloshift, symmetric, omit_corners, scale)
subroutine chksum_u_2d (array, mesg, HI, haloshift, symmetric, omit_corners, scale)
chksum_u_2d performs checksums on a 2d array staggered at C-grid u points.
subroutine chksum_v_2d (array, mesg, HI, haloshift, symmetric, omit_corners, scale)
chksum_v_2d performs checksums on a 2d array staggered at C-grid v points.
subroutine chksum_h_3d (array, mesg, HI, haloshift, omit_corners, scale)
chksum_h_3d performs checksums on a 3d array staggered at tracer points.
subroutine chksum_b_3d (array, mesg, HI, haloshift, symmetric, omit_corners, scale)
chksum_B_3d performs checksums on a 3d array staggered at corner points.
subroutine chksum_u_3d (array, mesg, HI, haloshift, symmetric, omit_corners, scale)
chksum_u_3d performs checksums on a 3d array staggered at C-grid u points.
subroutine chksum_v_3d (array, mesg, HI, haloshift, symmetric, omit_corners, scale)
chksum_v_3d performs checksums on a 3d array staggered at C-grid v points.
subroutine chksum1d (array, mesg, start_i, end_i, compare_PEs)
chksum1d does a checksum of a 1-dimensional array.
subroutine chksum2d (array, mesg)
chksum2d does a checksum of all data in a 2-d array.
subroutine chksum3d (array, mesg)
chksum3d does a checksum of all data in a 2-d array.
logical function is_nan_0d (x)
This function returns .true. if x is a NaN, and .false. otherwise.
logical function is_nan_1d (x, skip_mpp)
This function returns .true. if any element of x is a NaN, and .false. otherwise.
logical function is_nan_2d (x)
This function returns .true. if any element of x is a NaN, and .false. otherwise.
logical function is_nan_3d (x)
This function returns .true. if any element of x is a NaN, and .false. otherwise.
subroutine chk_sum_msg1 (fmsg, bc0, mesg)
subroutine chk_sum_msg5 (fmsg, bc0, bcSW, bcSE, bcNW, bcNE, mesg)
subroutine chk_sum_msg_nsew (fmsg, bc0, bcN, bcS, bcE, bcW, mesg)
subroutine chk_sum_msg_s (fmsg, bc0, bcS, mesg)
subroutine chk_sum_msg_w (fmsg, bc0, bcW, mesg)
subroutine chk_sum_msg2 (fmsg, bc0, bcSW, mesg)
subroutine chk_sum_msg3 (fmsg, aMean, aMin, aMax, mesg)
subroutine, public mom_checksums_init (param_file)
MOM_checksums_init initializes the MOM_checksums module. As it happens, the only thing that it does is to log the version of this module.
subroutine chksum_error (signal, message)
Variables
integer, parameter default_shift =0
logical calculatestatistics =.true.
logical writechksums =.true.
logical checkfornans =.true.
Function/Subroutine Documentation
chk_sum_msg1()
subroutine mom_checksums::chk_sum_msg1 (character(len=*), intent(in) fmsg, integer, intent(in) bc0, character(len=*), intent(in) mesg) private
Definition at line 1403 of file MOM_checksums.F90.
   character(len=*), intent(in) :: fmsg, mesg
   integer,          intent(in) :: bc0
   if (is_root_pe()) write(0,'(A,1(A,I10,X),A)') fmsg," c=",bc0,trim(mesg)
chk_sum_msg2()
subroutine mom_checksums::chk_sum_msg2 (character(len=*), intent(in) fmsg, integer, intent(in) bc0, integer, intent(in) bcSW, character(len=*), intent(in) mesg) private
Definition at line 1447 of file MOM_checksums.F90.
   character(len=*), intent(in) :: fmsg, mesg
   integer,          intent(in) :: bc0,bcsw
   if (is_root_pe()) write(0,'(A,2(A,I9,1X),A)') &
      fmsg," c=",bc0,"s/w=",bcsw,trim(mesg)
chk_sum_msg3()
subroutine mom_checksums::chk_sum_msg3 (character(len=*), intent(in) fmsg, real, intent(in) aMean, real, intent(in) aMin, real, intent(in) aMax, character(len=*), intent(in) mesg) private
Definition at line 1456 of file MOM_checksums.F90.
   character(len=*), intent(in) :: fmsg, mesg
   real,             intent(in) :: amean,amin,amax
   if (is_root_pe()) write(0,'(A,3(A,ES25.16,1X),A)') &
      fmsg," mean=",amean,"min=",amin,"max=",amax,trim(mesg)
chk_sum_msg5()
subroutine mom_checksums::chk_sum_msg5 (character(len=*), intent(in) fmsg, integer, intent(in) bc0, integer, intent(in) bcSW, integer, intent(in) bcSE, integer, intent(in) bcNW, integer, intent(in) bcNE, character(len=*), intent(in) mesg) private
Definition at line 1411 of file MOM_checksums.F90.
   character(len=*), intent(in) :: fmsg, mesg
   integer,          intent(in) :: bc0,bcsw,bcse,bcnw,bcne
   if (is_root_pe()) write(0,'(A,5(A,I10,1X),A)') &
      fmsg," c=",bc0,"sw=",bcsw,"se=",bcse,"nw=",bcnw,"ne=",bcne,trim(mesg)
chk_sum_msg_nsew()
subroutine mom_checksums::chk_sum_msg_nsew (character(len=*), intent(in) fmsg, integer, intent(in) bc0, integer, intent(in) bcN, integer, intent(in) bcS, integer, intent(in) bcE, integer, intent(in) bcW, character(len=*), intent(in) mesg) private
Definition at line 1420 of file MOM_checksums.F90.
Referenced by chksum_b_2d(), chksum_b_3d(), chksum_h_2d(), chksum_h_3d(), chksum_u_2d(), chksum_u_3d(), chksum_v_2d(), and chksum_v_3d().
   character(len=*), intent(in) :: fmsg, mesg
   integer,          intent(in) :: bc0, bcn, bcs, bce, bcw
   if (is_root_pe()) write(0,'(A,5(A,I10,1X),A)') &
      fmsg," c=",bc0,"N=",bcn,"S=",bcs,"E=",bce,"W=",bcw,trim(mesg)
chk_sum_msg_s()
subroutine mom_checksums::chk_sum_msg_s (character(len=*), intent(in) fmsg, integer, intent(in) bc0, integer, intent(in) bcS, character(len=*), intent(in) mesg) private
Definition at line 1429 of file MOM_checksums.F90.
Referenced by chksum_v_2d(), and chksum_v_3d().
   character(len=*), intent(in) :: fmsg, mesg
   integer,          intent(in) :: bc0, bcs
   if (is_root_pe()) write(0,'(A,2(A,I10,1X),A)') &
      fmsg," c=",bc0,"S=",bcs,trim(mesg)
chk_sum_msg_w()
subroutine mom_checksums::chk_sum_msg_w (character(len=*), intent(in) fmsg, integer, intent(in) bc0, integer, intent(in) bcW, character(len=*), intent(in) mesg) private
Definition at line 1438 of file MOM_checksums.F90.
Referenced by chksum_u_2d(), and chksum_u_3d().
   character(len=*), intent(in) :: fmsg, mesg
   integer,          intent(in) :: bc0, bcw
   if (is_root_pe()) write(0,'(A,2(A,I10,1X),A)') &
      fmsg," c=",bc0,"W=",bcw,trim(mesg)
chksum1d()
subroutine mom_checksums::chksum1d (real, dimension(:), intent(in) array, character(len=*), intent(in) mesg, integer, intent(in), optional start_i, integer, intent(in), optional end_i, logical, intent(in), optional compare_PEs) private
chksum1d does a checksum of a 1-dimensional array.
Parameters
[in] array The array to be summed (index starts at 1).
[in] mesg An identifying message.
[in] start_i The starting index for the sum (default 1)
[in] end_i The ending index for the sum (default all)
[in] compare_pes If true, compare across PEs instead of summing and list the root_PE value (default true)
Definition at line 1201 of file MOM_checksums.F90.
   real, dimension(:), intent(in) :: array   !< The array to be summed (index starts at 1).
   character(len=*),   intent(in) :: mesg    !< An identifying message.
   integer, optional,  intent(in) :: start_i !< The starting index for the sum (default 1)
   integer, optional,  intent(in) :: end_i   !< The ending index for the sum (default all)
   logical, optional,  intent(in) :: compare_pes !< If true, compare across PEs instead of summing
                                                 !! and list the root_PE value (default true)
   integer :: is, ie, i, bc, sum1, sum_bc
   integer :: bitcount
   real :: sum
   real, allocatable :: sum_here(:)
   logical :: compare
   integer :: pe_num   ! pe number of the data
   integer :: npes     ! Total number of processsors
   is = lbound(array,1) ; ie = ubound(array,1)
   if (present(start_i)) is = start_i
   if (present(end_i)) ie = end_i
   compare = .true. ; if (present(compare_pes)) compare = compare_pes
   sum = 0.0 ; sum_bc = 0
   do i=is,ie
     sum = sum + array(i)
     bc = bitcount(abs(array(i)))
     sum_bc = sum_bc + bc
   enddo
   pe_num = pe_here() + 1 - root_pe() ; npes = num_pes()
   allocate(sum_here(npes)) ; sum_here(:) = 0.0 ; sum_here(pe_num) = sum
   call sum_across_pes(sum_here,npes)
   sum1 = sum_bc
   call sum_across_pes(sum1)
   if (.not.compare) then
     sum = 0.0
     do i=1,npes ; sum = sum + sum_here(i) ; enddo
     sum_bc = sum1
   elseif (is_root_pe()) then
     if (sum1 /= npes*sum_bc) &
       write(0, '(A40," bitcounts do not match across PEs: ",I12,1X,I12)') &
             mesg, sum1, npes*sum_bc
     do i=1,npes ; if (sum /= sum_here(i)) then
       write(0, '(A40," PE ",i4," sum mismatches root_PE: ",3(ES22.13,1X))') &
             mesg, i, sum_here(i), sum, sum_here(i)-sum
     endif ; enddo
   endif
   deallocate(sum_here)
   if (is_root_pe()) &
     write(0,'(A50,1X,ES25.16,1X,I12)') mesg, sum, sum_bc
chksum2d()
subroutine mom_checksums::chksum2d (real, dimension(:,:) array, character(len=*) mesg) private
chksum2d does a checksum of all data in a 2-d array.
Definition at line 1261 of file MOM_checksums.F90.
   real, dimension(:,:) :: array
   character(len=*) :: mesg
   integer :: bitcount
   integer :: xs,xe,ys,ye,i,j,sum1,bc
   real :: sum
   xs = lbound(array,1) ; xe = ubound(array,1)
   ys = lbound(array,2) ; ye = ubound(array,2)
   sum = 0.0 ; sum1 = 0
   do i=xs,xe ; do j=ys,ye
     bc = bitcount(abs(array(i,j)))
     sum1 = sum1 + bc
   enddo ; enddo
   call sum_across_pes(sum1)
   sum = reproducing_sum(array(:,:))
   if (is_root_pe()) &
     write(0,'(A50,1X,ES25.16,1X,I12)') mesg, sum, sum1
 !    write(0,'(A40,1X,Z16.16,1X,Z16.16,1X,ES25.16,1X,I12)') &
 !      mesg, sum, sum1, sum, sum1
chksum3d()
subroutine mom_checksums::chksum3d (real, dimension(:,:,:) array, character(len=*) mesg) private
chksum3d does a checksum of all data in a 2-d array.
Definition at line 1290 of file MOM_checksums.F90.
   real, dimension(:,:,:) :: array
   character(len=*) :: mesg
   integer :: bitcount
   integer :: xs,xe,ys,ye,zs,ze,i,j,k, bc,sum1
   real :: sum
   xs = lbound(array,1) ; xe = ubound(array,1)
   ys = lbound(array,2) ; ye = ubound(array,2)
   zs = lbound(array,3) ; ze = ubound(array,3)
   sum = 0.0 ; sum1 = 0
   do i=xs,xe ; do j=ys,ye ; do k=zs,ze
     bc = bitcount(abs(array(i,j,k)))
     sum1 = sum1 + bc
   enddo ; enddo ; enddo
   call sum_across_pes(sum1)
   sum = reproducing_sum(array(:,:,:))
   if (is_root_pe()) &
     write(0,'(A50,1X,ES25.16,1X,I12)') mesg, sum, sum1
 !    write(0,'(A40,1X,Z16.16,1X,Z16.16,1X,ES25.16,1X,I12)') &
 !      mesg, sum, sum1, sum, sum1
chksum_b_2d()
subroutine mom_checksums::chksum_b_2d (real, dimension(hi%isdb:,hi%jsdb:), intent(in) array, character(len=*), intent(in) mesg, type(hor_index_type), intent(in) HI, integer, intent(in), optional haloshift, logical, intent(in), optional symmetric, logical, intent(in), optional omit_corners, real, intent(in), optional scale) private
chksum_B_2d performs checksums on a 2d array staggered at corner points.
Parameters
[in] hi A horizontal index type
[in] array The array to be checksummed
[in] mesg An identifying message
[in] haloshift The width of halos to check (default 0)
[in] symmetric If true, do the checksums on the full symmetric computational domain.
[in] omit_corners If true, avoid checking diagonal shifts
[in] scale A scaling factor for this array.
Definition at line 285 of file MOM_checksums.F90.
References calculatestatistics, checkfornans, chk_sum_msg_nsew(), chksum_error(), default_shift, subchk(), substats(), and writechksums.
Referenced by chksum_pair_b_2d().
   type(hor_index_type), intent(in) :: hi     !< A horizontal index type
   real, dimension(HI%IsdB:,HI%JsdB:), &
                         intent(in) :: array !< The array to be checksummed
   character(len=*),     intent(in) :: mesg  !< An identifying message
   integer,    optional, intent(in) :: haloshift !< The width of halos to check (default 0)
   logical,    optional, intent(in) :: symmetric !< If true, do the checksums on the
                                                 !! full symmetric computational domain.
   logical,    optional, intent(in) :: omit_corners !< If true, avoid checking diagonal shifts
   real,       optional, intent(in) :: scale     !< A scaling factor for this array.
   real :: scaling
   integer :: bc0, bcsw, bcse, bcnw, bcne, hshift
   integer :: bcn, bcs, bce, bcw
   logical :: do_corners, sym, sym_stats
   if (checkfornans) then
     if (is_nan(array(hi%IscB:hi%IecB,hi%JscB:hi%JecB))) &
       call chksum_error(fatal, 'NaN detected: '//trim(mesg))
 !   if (is_NaN(array)) &
 !     call chksum_error(FATAL, 'NaN detected in halo: '//trim(mesg))
   endif
   scaling = 1.0 ; if (present(scale)) scaling = scale
   sym_stats = .false. ; if (present(symmetric)) sym_stats = symmetric
   if (present(haloshift)) then ; if (haloshift > 0) sym_stats = .true. ; endif
   if (calculatestatistics) call substats(hi, array, mesg, sym_stats, scaling)
   if (.not.writechksums) return
   hshift = default_shift
   if (present(haloshift)) hshift = haloshift
   if (hshift<0) hshift = hi%ied-hi%iec
   if ( hi%iscB-hshift<hi%isdB .or. hi%iecB+hshift>hi%iedB .or. &
        hi%jscB-hshift<hi%jsdB .or. hi%jecB+hshift>hi%jedB ) then
     write(0,*) 'chksum_B_2d: haloshift =',hshift
     write(0,*) 'chksum_B_2d: isd,isc,iec,ied=',hi%isdB,hi%iscB,hi%iecB,hi%iedB
     write(0,*) 'chksum_B_2d: jsd,jsc,jec,jed=',hi%jsdB,hi%jscB,hi%jecB,hi%jedB
     call chksum_error(fatal,'Error in chksum_B_2d '//trim(mesg))
   endif
   bc0 = subchk(array, hi, 0, 0, scaling)
   sym = .false. ; if (present(symmetric)) sym = symmetric
   if ((hshift==0) .and. .not.sym) then
     if (is_root_pe()) call chk_sum_msg("B-point:",bc0,mesg)
     return
   endif
   do_corners = .true. ; if (present(omit_corners)) do_corners = .not.omit_corners
   if (do_corners) then
     if (sym) then
       bcsw = subchk(array, hi, -hshift-1, -hshift-1, scaling)
       bcse = subchk(array, hi, hshift, -hshift-1, scaling)
       bcnw = subchk(array, hi, -hshift-1, hshift, scaling)
     else
       bcsw = subchk(array, hi, -hshift, -hshift, scaling)
       bcse = subchk(array, hi, hshift, -hshift, scaling)
       bcnw = subchk(array, hi, -hshift, hshift, scaling)
     endif
     bcne = subchk(array, hi, hshift, hshift, scaling)
     if (is_root_pe()) call chk_sum_msg("B-point:",bc0,bcsw,bcse,bcnw,bcne,mesg)
   else
     bcs = subchk(array, hi, 0, -hshift, scaling)
     bce = subchk(array, hi, hshift, 0, scaling)
     bcw = subchk(array, hi, -hshift, 0, scaling)
     bcn = subchk(array, hi, 0, hshift, scaling)
     if (is_root_pe()) call chk_sum_msg_nsew("B-point:",bc0,bcn,bcs,bce,bcw,mesg)
   endif
   contains
   integer function subchk(array, HI, di, dj, scale)
     type(hor_index_type), intent(in) :: hi
     real, dimension(HI%IsdB:,HI%JsdB:), intent(in) :: array
     integer, intent(in) :: di, dj
     real, intent(in) :: scale
     integer :: bitcount, i, j, bc
     subchk = 0
     ! This line deliberately uses the h-point computational domain.
     do j=hi%jsc+dj,hi%jec+dj; do i=hi%isc+di,hi%iec+di
       bc = bitcount(abs(scale*array(i,j)))
       subchk = subchk + bc
     enddo; enddo
     call sum_across_pes(subchk)
     subchk=mod(subchk,1000000000)
   end function subchk
   subroutine substats(HI, array, mesg, sym_stats, scale)
     type(hor_index_type), intent(in) :: hi
     real, dimension(HI%IsdB:,HI%JsdB:), intent(in) :: array
     character(len=*), intent(in) :: mesg
     logical, intent(in) :: sym_stats
     real, intent(in) :: scale
     integer :: i, j, n, isb, jsb
     real :: amean, amin, amax
     isb = hi%isc ; if (sym_stats) isb = hi%isc-1
     jsb = hi%jsc ; if (sym_stats) jsb = hi%jsc-1
     amin = array(hi%isc,hi%jsc) ; amax = amin
     do j=jsb,hi%JecB ; do i=isb,hi%IecB
       amin = min(amin, array(i,j))
       amax = max(amax, array(i,j))
     enddo ; enddo
     ! This line deliberately uses the h-point computational domain.
     amean = reproducing_sum(array(hi%isc:hi%iec,hi%jsc:hi%jec))
     n = (1 + hi%jec - hi%jsc) * (1 + hi%iec - hi%isc)
     call sum_across_pes(n)
     call min_across_pes(amin)
     call max_across_pes(amax)
     amean = amean / real(n)
     if (is_root_pe()) call chk_sum_msg("B-point:",amean*scale,amin*scale,amax*scale,mesg)
   end subroutine substats
chksum_b_3d()
subroutine mom_checksums::chksum_b_3d (real, dimension(hi%isdb:,hi%jsdb:,:), intent(in) array, character(len=*), intent(in) mesg, type(hor_index_type), intent(in) HI, integer, intent(in), optional haloshift, logical, intent(in), optional symmetric, logical, intent(in), optional omit_corners, real, intent(in), optional scale) private
chksum_B_3d performs checksums on a 3d array staggered at corner points.
Parameters
[in] hi A horizontal index type
[in] array The array to be checksummed
[in] mesg An identifying message
[in] haloshift The width of halos to check (default 0)
[in] symmetric If true, do the checksums on the full symmetric computational domain.
[in] omit_corners If true, avoid checking diagonal shifts
[in] scale A scaling factor for this array.
Definition at line 814 of file MOM_checksums.F90.
References calculatestatistics, checkfornans, chk_sum_msg_nsew(), chksum_error(), default_shift, subchk(), substats(), and writechksums.
Referenced by chksum_pair_b_3d().
   type(hor_index_type),              intent(in) :: hi !< A horizontal index type
   real, dimension(HI%IsdB:,HI%JsdB:,:), intent(in) :: array !< The array to be checksummed
   character(len=*),                   intent(in) :: mesg  !< An identifying message
   integer,                  optional, intent(in) :: haloshift !< The width of halos to check (default 0)
   logical,                  optional, intent(in) :: symmetric !< If true, do the checksums on the full symmetric computational domain.
   logical,                  optional, intent(in) :: omit_corners !< If true, avoid checking diagonal shifts
   real,                     optional, intent(in) :: scale     !< A scaling factor for this array.
   real :: scaling
   integer :: bc0, bcsw, bcse, bcnw, bcne, hshift
   integer :: bcn, bcs, bce, bcw
   logical :: do_corners, sym, sym_stats
   if (checkfornans) then
     if (is_nan(array(hi%IscB:hi%IecB,hi%JscB:hi%JecB,:))) &
       call chksum_error(fatal, 'NaN detected: '//trim(mesg))
 !   if (is_NaN(array)) &
 !     call chksum_error(FATAL, 'NaN detected in halo: '//trim(mesg))
   endif
   scaling = 1.0 ; if (present(scale)) scaling = scale
   sym_stats = .false. ; if (present(symmetric)) sym_stats = symmetric
   if (present(haloshift)) then ; if (haloshift > 0) sym_stats = .true. ; endif
   if (calculatestatistics) call substats(hi, array, mesg, sym_stats, scaling)
   if (.not.writechksums) return
   hshift = default_shift
   if (present(haloshift)) hshift = haloshift
   if (hshift<0) hshift = hi%ied-hi%iec
   if ( hi%isc-hshift<hi%isd .or. hi%iec+hshift>hi%ied .or. &
        hi%jsc-hshift<hi%jsd .or. hi%jec+hshift>hi%jed ) then
     write(0,*) 'chksum_B_3d: haloshift =',hshift
     write(0,*) 'chksum_B_3d: isd,isc,iec,ied=',hi%isd,hi%isc,hi%iec,hi%ied
     write(0,*) 'chksum_B_3d: jsd,jsc,jec,jed=',hi%jsd,hi%jsc,hi%jec,hi%jed
     call chksum_error(fatal,'Error in chksum_B_3d '//trim(mesg))
   endif
   bc0 = subchk(array, hi, 0, 0, scaling)
   sym = .false. ; if (present(symmetric)) sym = symmetric
   if ((hshift==0) .and. .not.sym) then
     if (is_root_pe()) call chk_sum_msg("B-point:",bc0,mesg)
     return
   endif
   do_corners = .true. ; if (present(omit_corners)) do_corners = .not.omit_corners
   if (do_corners) then
     if (sym) then
       bcsw = subchk(array, hi, -hshift-1, -hshift-1, scaling)
       bcse = subchk(array, hi, hshift, -hshift-1, scaling)
       bcnw = subchk(array, hi, -hshift-1, hshift, scaling)
     else
       bcsw = subchk(array, hi, -hshift-1, -hshift-1, scaling)
       bcse = subchk(array, hi, hshift, -hshift-1, scaling)
       bcnw = subchk(array, hi, -hshift-1, hshift, scaling)
     endif
     bcne = subchk(array, hi, hshift, hshift, scaling)
     if (is_root_pe()) call chk_sum_msg("B-point:",bc0,bcsw,bcse,bcnw,bcne,mesg)
   else
     if (sym) then
       bcs = subchk(array, hi, 0, -hshift-1, scaling)
       bcw = subchk(array, hi, -hshift-1, 0, scaling)
     else
       bcs = subchk(array, hi, 0, -hshift, scaling)
       bcw = subchk(array, hi, -hshift, 0, scaling)
     endif
     bce = subchk(array, hi, hshift, 0, scaling)
     bcn = subchk(array, hi, 0, hshift, scaling)
     if (is_root_pe()) call chk_sum_msg_nsew("B-point:",bc0,bcn,bcs,bce,bcw,mesg)
   endif
   contains
   integer function subchk(array, HI, di, dj, scale)
     type(hor_index_type), intent(in) :: hi
     real, dimension(HI%IsdB:,HI%JsdB:,:), intent(in) :: array
     integer, intent(in) :: di, dj
     real, intent(in) :: scale
     integer :: bitcount, i, j, k, bc
     subchk = 0
     ! This line deliberately uses the h-point computational domain.
     do k=lbound(array,3),ubound(array,3) ; do j=hi%jsc+dj,hi%jec+dj ; do i=hi%isc+di,hi%iec+di
       bc = bitcount(abs(scale*array(i,j,k)))
       subchk = subchk + bc
     enddo ; enddo ; enddo
     call sum_across_pes(subchk)
     subchk=mod(subchk,1000000000)
   end function subchk
   subroutine substats(HI, array, mesg, sym_stats, scale)
     type(hor_index_type), intent(in) :: hi
     real, dimension(HI%IsdB:,HI%JsdB:,:), intent(in) :: array
     character(len=*), intent(in) :: mesg
     logical, intent(in) :: sym_stats
     real, intent(in) :: scale
     integer :: i, j, k, n, isb, jsb
     real :: amean, amin, amax
     isb = hi%isc ; if (sym_stats) isb = hi%isc-1
     jsb = hi%jsc ; if (sym_stats) jsb = hi%jsc-1
     amin = array(hi%isc,hi%jsc,1) ; amax = amin
     do k=lbound(array,3),ubound(array,3) ; do j=jsb,hi%JecB ; do i=isb,hi%IecB
       amin = min(amin, array(i,j,k))
       amax = max(amax, array(i,j,k))
     enddo ; enddo ; enddo
     amean = reproducing_sum(array(hi%isc:hi%iec,hi%jsc:hi%jec,:))
     n = (1 + hi%jec - hi%jsc) * (1 + hi%iec - hi%isc) * size(array,3)
     call sum_across_pes(n)
     call min_across_pes(amin)
     call max_across_pes(amax)
     amean = amean / real(n)
     if (is_root_pe()) call chk_sum_msg("B-point:",amean*scale,amin*scale,amax*scale,mesg)
   end subroutine substats
chksum_error()
subroutine mom_checksums::chksum_error (integer, intent(in) signal, character(len=*), intent(in) message) private
Definition at line 1479 of file MOM_checksums.F90.
Referenced by chksum_b_2d(), chksum_b_3d(), chksum_h_2d(), chksum_h_3d(), chksum_u_2d(), chksum_u_3d(), chksum_v_2d(), and chksum_v_3d().
   ! Wrapper for MOM_error to help place specific break points in
   ! debuggers
   integer, intent(in) :: signal
   character(len=*), intent(in) :: message
   call mom_error(signal, message)
chksum_h_2d()
subroutine mom_checksums::chksum_h_2d (real, dimension(hi%isd:,hi%jsd:), intent(in) array, character(len=*), intent(in) mesg, type(hor_index_type), intent(in) HI, integer, intent(in), optional haloshift, logical, intent(in), optional omit_corners, real, intent(in), optional scale) private
chksum_h_2d performs checksums on a 2d array staggered at tracer points.
Parameters
[in] hi A horizontal index type
[in] array The array to be checksummed
[in] mesg An identifying message
[in] haloshift The width of halos to check (default 0)
[in] omit_corners If true, avoid checking diagonal shifts
[in] scale A scaling factor for this array.
Definition at line 129 of file MOM_checksums.F90.
References calculatestatistics, checkfornans, chk_sum_msg_nsew(), chksum_error(), default_shift, mom_error_handler::is_root_pe(), subchk(), substats(), and writechksums.
Referenced by chksum_pair_h_2d().
   type(hor_index_type),            intent(in) :: hi     !< A horizontal index type
   real, dimension(HI%isd:,HI%jsd:), intent(in) :: array !< The array to be checksummed
   character(len=*),                intent(in) :: mesg  !< An identifying message
   integer,               optional, intent(in) :: haloshift !< The width of halos to check (default 0)
   logical,               optional, intent(in) :: omit_corners !< If true, avoid checking diagonal shifts
   real,                  optional, intent(in) :: scale     !< A scaling factor for this array.
   real :: scaling
   integer :: bc0, bcsw, bcse, bcnw, bcne, hshift
   integer :: bcn, bcs, bce, bcw
   logical :: do_corners
   if (checkfornans) then
     if (is_nan(array(hi%isc:hi%iec,hi%jsc:hi%jec))) &
       call chksum_error(fatal, 'NaN detected: '//trim(mesg))
 !   if (is_NaN(array)) &
 !     call chksum_error(FATAL, 'NaN detected in halo: '//trim(mesg))
   endif
   scaling = 1.0 ; if (present(scale)) scaling = scale
   if (calculatestatistics) call substats(hi, array, mesg, scaling)
   if (.not.writechksums) return
   hshift = default_shift
   if (present(haloshift)) hshift = haloshift
   if (hshift<0) hshift = hi%ied-hi%iec
   if ( hi%isc-hshift<hi%isd .or. hi%iec+hshift>hi%ied .or. &
        hi%jsc-hshift<hi%jsd .or. hi%jec+hshift>hi%jed ) then
     write(0,*) 'chksum_h_2d: haloshift =',hshift
     write(0,*) 'chksum_h_2d: isd,isc,iec,ied=',hi%isd,hi%isc,hi%iec,hi%ied
     write(0,*) 'chksum_h_2d: jsd,jsc,jec,jed=',hi%jsd,hi%jsc,hi%jec,hi%jed
     call chksum_error(fatal,'Error in chksum_h_2d '//trim(mesg))
   endif
   bc0 = subchk(array, hi, 0, 0, scaling)
   if (hshift==0) then
     if (is_root_pe()) call chk_sum_msg("h-point:",bc0,mesg)
     return
   endif
   do_corners = .true. ; if (present(omit_corners)) do_corners = .not.omit_corners
   if (do_corners) then
     bcsw = subchk(array, hi, -hshift, -hshift, scaling)
     bcse = subchk(array, hi, hshift, -hshift, scaling)
     bcnw = subchk(array, hi, -hshift, hshift, scaling)
     bcne = subchk(array, hi, hshift, hshift, scaling)
     if (is_root_pe()) call chk_sum_msg("h-point:",bc0,bcsw,bcse,bcnw,bcne,mesg)
   else
     bcs = subchk(array, hi, 0, -hshift, scaling)
     bce = subchk(array, hi, hshift, 0, scaling)
     bcw = subchk(array, hi, -hshift, 0, scaling)
     bcn = subchk(array, hi, 0, hshift, scaling)
     if (is_root_pe()) call chk_sum_msg_nsew("h-point:",bc0,bcn,bcs,bce,bcw,mesg)
   endif
   contains
   integer function subchk(array, HI, di, dj, scale)
     type(hor_index_type), intent(in) :: hi
     real, dimension(HI%isd:,HI%jsd:), intent(in) :: array
     integer, intent(in) :: di, dj
     real, intent(in) :: scale
     integer :: bitcount, i, j, bc
     subchk = 0
     do j=hi%jsc+dj,hi%jec+dj; do i=hi%isc+di,hi%iec+di
       bc = bitcount(abs(scale*array(i,j)))
       subchk = subchk + bc
     enddo; enddo
     call sum_across_pes(subchk)
     subchk=mod(subchk,1000000000)
   end function subchk
   subroutine substats(HI, array, mesg, scale)
     type(hor_index_type), intent(in) :: hi
     real, dimension(HI%isd:,HI%jsd:), intent(in) :: array
     character(len=*), intent(in) :: mesg
     real, intent(in) :: scale
     integer :: i, j, n
     real :: amean, amin, amax
     amin = array(hi%isc,hi%jsc)
     amax = array(hi%isc,hi%jsc)
     n = 0
     do j=hi%jsc,hi%jec ; do i=hi%isc,hi%iec
       amin = min(amin, array(i,j))
       amax = max(amax, array(i,j))
       n = n + 1
     enddo ; enddo
     amean = reproducing_sum(array(hi%isc:hi%iec,hi%jsc:hi%jec))
     call sum_across_pes(n)
     call min_across_pes(amin)
     call max_across_pes(amax)
     amean = amean / real(n)
     if (is_root_pe()) call chk_sum_msg("h-point:",amean*scale,amin*scale,amax*scale,mesg)
   end subroutine substats
chksum_h_3d()
subroutine mom_checksums::chksum_h_3d (real, dimension(hi%isd:,hi%jsd:,:), intent(in) array, character(len=*), intent(in) mesg, type(hor_index_type), intent(in) HI, integer, intent(in), optional haloshift, logical, intent(in), optional omit_corners, real, intent(in), optional scale) private
chksum_h_3d performs checksums on a 3d array staggered at tracer points.
Parameters
[in] hi A horizontal index type
[in] array The array to be checksummed
[in] mesg An identifying message
[in] haloshift The width of halos to check (default 0)
[in] omit_corners If true, avoid checking diagonal shifts
[in] scale A scaling factor for this array.
Definition at line 706 of file MOM_checksums.F90.
References calculatestatistics, checkfornans, chk_sum_msg_nsew(), chksum_error(), default_shift, subchk(), substats(), and writechksums.
Referenced by chksum_pair_h_3d().
   type(hor_index_type),             intent(in) :: hi !< A horizontal index type
   real, dimension(HI%isd:,HI%jsd:,:),  intent(in) :: array !< The array to be checksummed
   character(len=*),                  intent(in) :: mesg  !< An identifying message
   integer,                 optional, intent(in) :: haloshift !< The width of halos to check (default 0)
   logical,                 optional, intent(in) :: omit_corners !< If true, avoid checking diagonal shifts
   real,                    optional, intent(in) :: scale     !< A scaling factor for this array.
   real :: scaling
   integer :: bc0, bcsw, bcse, bcnw, bcne, hshift
   integer :: bcn, bcs, bce, bcw
   logical :: do_corners
   if (checkfornans) then
     if (is_nan(array(hi%isc:hi%iec,hi%jsc:hi%jec,:))) &
       call chksum_error(fatal, 'NaN detected: '//trim(mesg))
 !   if (is_NaN(array)) &
 !     call chksum_error(FATAL, 'NaN detected in halo: '//trim(mesg))
   endif
   scaling = 1.0 ; if (present(scale)) scaling = scale
   if (calculatestatistics) call substats(hi, array, mesg, scaling)
   if (.not.writechksums) return
   hshift = default_shift
   if (present(haloshift)) hshift = haloshift
   if (hshift<0) hshift = hi%ied-hi%iec
   if ( hi%isc-hshift<hi%isd .or. hi%iec+hshift>hi%ied .or. &
        hi%jsc-hshift<hi%jsd .or. hi%jec+hshift>hi%jed ) then
     write(0,*) 'chksum_h_3d: haloshift =',hshift
     write(0,*) 'chksum_h_3d: isd,isc,iec,ied=',hi%isd,hi%isc,hi%iec,hi%ied
     write(0,*) 'chksum_h_3d: jsd,jsc,jec,jed=',hi%jsd,hi%jsc,hi%jec,hi%jed
     call chksum_error(fatal,'Error in chksum_h_3d '//trim(mesg))
   endif
   bc0 = subchk(array, hi, 0, 0, scaling)
   if (hshift==0) then
     if (is_root_pe()) call chk_sum_msg("h-point:",bc0,mesg)
     return
   endif
   do_corners = .true. ; if (present(omit_corners)) do_corners = .not.omit_corners
   if (do_corners) then
     bcsw = subchk(array, hi, -hshift, -hshift, scaling)
     bcse = subchk(array, hi, hshift, -hshift, scaling)
     bcnw = subchk(array, hi, -hshift, hshift, scaling)
     bcne = subchk(array, hi, hshift, hshift, scaling)
     if (is_root_pe()) call chk_sum_msg("h-point:",bc0,bcsw,bcse,bcnw,bcne,mesg)
   else
     bcs = subchk(array, hi, 0, -hshift, scaling)
     bce = subchk(array, hi, hshift, 0, scaling)
     bcw = subchk(array, hi, -hshift, 0, scaling)
     bcn = subchk(array, hi, 0, hshift, scaling)
     if (is_root_pe()) call chk_sum_msg_nsew("h-point:",bc0,bcn,bcs,bce,bcw,mesg)
   endif
   contains
   integer function subchk(array, HI, di, dj, scale)
     type(hor_index_type), intent(in) :: hi
     real, dimension(HI%isd:,HI%jsd:,:), intent(in) :: array
     integer, intent(in) :: di, dj
     real, intent(in) :: scale
     integer :: bitcount, i, j, k, bc
     subchk = 0
     do k=lbound(array,3),ubound(array,3) ; do j=hi%jsc+dj,hi%jec+dj ; do i=hi%isc+di,hi%iec+di
       bc = bitcount(abs(scale*array(i,j,k)))
       subchk = subchk + bc
     enddo ; enddo ; enddo
     call sum_across_pes(subchk)
     subchk=mod(subchk,1000000000)
   end function subchk
   subroutine substats(HI, array, mesg, scale)
     type(hor_index_type), intent(in) :: hi
     real, dimension(HI%isd:,HI%jsd:,:), intent(in) :: array
     character(len=*), intent(in) :: mesg
     real, intent(in) :: scale
     integer :: i, j, k, n
     real :: amean, amin, amax
     amin = array(hi%isc,hi%jsc,1)
     amax = array(hi%isc,hi%jsc,1)
     n = 0
     do k=lbound(array,3),ubound(array,3) ; do j=hi%jsc,hi%jec ; do i=hi%isc,hi%iec
       amin = min(amin, array(i,j,k))
       amax = max(amax, array(i,j,k))
       n = n + 1
     enddo ; enddo ; enddo
     amean = reproducing_sum(array(hi%isc:hi%iec,hi%jsc:hi%jec,:))
     call sum_across_pes(n)
     call min_across_pes(amin)
     call max_across_pes(amax)
     amean = amean / real(n)
     if (is_root_pe()) call chk_sum_msg("h-point:",amean*scale,amin*scale,amax*scale,mesg)
   end subroutine substats
chksum_pair_b_2d()
subroutine mom_checksums::chksum_pair_b_2d (character(len=*), intent(in) mesg, real, dimension(hi%isd:,hi%jsd:), intent(in) arrayA, real, dimension(hi%isd:,hi%jsd:), intent(in) arrayB, type(hor_index_type), intent(in) HI, integer, intent(in), optional haloshift, logical, intent(in), optional symmetric, logical, intent(in), optional omit_corners, real, intent(in), optional scale) private
Parameters
[in] mesg Identifying messages
[in] hi A horizontal index type
[in] arrayb The arrays to be checksummed
[in] symmetric If true, do the checksums on the full symmetric computational domain.
[in] haloshift The width of halos to check (default 0)
[in] omit_corners If true, avoid checking diagonal shifts
[in] scale A scaling factor for this array.
Definition at line 236 of file MOM_checksums.F90.
References chksum_b_2d().
   character(len=*),                 intent(in) :: mesg   !< Identifying messages
   type(hor_index_type),             intent(in) :: hi     !< A horizontal index type
   real, dimension(HI%isd:,HI%jsd:), intent(in) :: arraya, arrayb !< The arrays to be checksummed
   logical,                optional, intent(in) :: symmetric !< If true, do the checksums on the full symmetric computational domain.
   integer,                optional, intent(in) :: haloshift !< The width of halos to check (default 0)
   logical,                optional, intent(in) :: omit_corners !< If true, avoid checking diagonal shifts
   real,                   optional, intent(in) :: scale     !< A scaling factor for this array.
   logical :: sym
   sym = .false. ; if (present(symmetric)) sym = symmetric
   if (present(haloshift)) then
     call chksum_b_2d(arraya, 'x '//mesg, hi, haloshift, symmetric=sym, &
                      omit_corners=omit_corners, scale=scale)
     call chksum_b_2d(arrayb, 'y '//mesg, hi, haloshift, symmetric=sym, &
                      omit_corners=omit_corners, scale=scale)
   else
     call chksum_b_2d(arraya, 'x '//mesg, hi, symmetric=sym, scale=scale)
     call chksum_b_2d(arrayb, 'y '//mesg, hi, symmetric=sym, scale=scale)
   endif
chksum_pair_b_3d()
subroutine mom_checksums::chksum_pair_b_3d (character(len=*), intent(in) mesg, real, dimension(hi%isdb:,hi%jsdb:, :), intent(in) arrayA, real, dimension(hi%isdb:,hi%jsdb:, :), intent(in) arrayB, type(hor_index_type), intent(in) HI, integer, intent(in), optional haloshift, logical, intent(in), optional symmetric, logical, intent(in), optional omit_corners, real, intent(in), optional scale) private
Parameters
[in] mesg Identifying messages
[in] hi A horizontal index type
[in] arrayb The arrays to be checksummed
[in] haloshift The width of halos to check (default 0)
[in] symmetric If true, do the checksums on the full symmetric computational domain.
[in] omit_corners If true, avoid checking diagonal shifts
[in] scale A scaling factor for this array.
Definition at line 261 of file MOM_checksums.F90.
References chksum_b_3d().
   character(len=*),                    intent(in) :: mesg !< Identifying messages
   type(hor_index_type),                intent(in) :: hi     !< A horizontal index type
   real, dimension(HI%IsdB:,HI%JsdB:, :), intent(in) :: arraya, arrayb !< The arrays to be checksummed
   integer,                   optional, intent(in) :: haloshift !< The width of halos to check (default 0)
   logical,                   optional, intent(in) :: symmetric !< If true, do the checksums on the full symmetric computational domain.
   logical,                   optional, intent(in) :: omit_corners !< If true, avoid checking diagonal shifts
   real,                      optional, intent(in) :: scale     !< A scaling factor for this array.
   logical :: sym
   if (present(haloshift)) then
     call chksum_b_3d(arraya, 'x '//mesg, hi, haloshift, symmetric, &
                      omit_corners, scale=scale)
     call chksum_b_3d(arrayb, 'y '//mesg, hi, haloshift, symmetric, &
                      omit_corners, scale=scale)
   else
     call chksum_b_3d(arraya, 'x '//mesg, hi, symmetric=symmetric, scale=scale)
     call chksum_b_3d(arrayb, 'y '//mesg, hi, symmetric=symmetric, scale=scale)
   endif
chksum_pair_h_2d()
subroutine mom_checksums::chksum_pair_h_2d (character(len=*), intent(in) mesg, real, dimension(hi%isd:,hi%jsd:), intent(in) arrayA, real, dimension(hi%isd:,hi%jsd:), intent(in) arrayB, type(hor_index_type), intent(in) HI, integer, intent(in), optional haloshift, logical, intent(in), optional omit_corners, real, intent(in), optional scale) private
Parameters
[in] mesg Identifying messages
[in] hi A horizontal index type
[in] arrayb The arrays to be checksummed
[in] haloshift The width of halos to check (default 0)
[in] omit_corners If true, avoid checking diagonal shifts
[in] scale A scaling factor for this array.
Definition at line 92 of file MOM_checksums.F90.
References chksum_h_2d().
   character(len=*),                 intent(in) :: mesg !< Identifying messages
   type(hor_index_type),             intent(in) :: hi     !< A horizontal index type
   real, dimension(HI%isd:,HI%jsd:), intent(in) :: arraya, arrayb !< The arrays to be checksummed
   integer,                optional, intent(in) :: haloshift !< The width of halos to check (default 0)
   logical,                optional, intent(in) :: omit_corners !< If true, avoid checking diagonal shifts
   real,                   optional, intent(in) :: scale     !< A scaling factor for this array.
   if (present(haloshift)) then
     call chksum_h_2d(arraya, 'x '//mesg, hi, haloshift, omit_corners, scale=scale)
     call chksum_h_2d(arrayb, 'y '//mesg, hi, haloshift, omit_corners, scale=scale)
   else
     call chksum_h_2d(arraya, 'x '//mesg, hi, scale=scale)
     call chksum_h_2d(arrayb, 'y '//mesg, hi, scale=scale)
   endif
chksum_pair_h_3d()
subroutine mom_checksums::chksum_pair_h_3d (character(len=*), intent(in) mesg, real, dimension(hi%isd:,hi%jsd:, :), intent(in) arrayA, real, dimension(hi%isd:,hi%jsd:, :), intent(in) arrayB, type(hor_index_type), intent(in) HI, integer, intent(in), optional haloshift, logical, intent(in), optional omit_corners, real, intent(in), optional scale) private
Parameters
[in] mesg Identifying messages
[in] hi A horizontal index type
[in] arrayb The arrays to be checksummed
[in] haloshift The width of halos to check (default 0)
[in] omit_corners If true, avoid checking diagonal shifts
[in] scale A scaling factor for this array.
Definition at line 110 of file MOM_checksums.F90.
References chksum_h_3d().
   character(len=*),                    intent(in) :: mesg !< Identifying messages
   type(hor_index_type),                intent(in) :: hi   !< A horizontal index type
   real, dimension(HI%isd:,HI%jsd:, :), intent(in) :: arraya, arrayb !< The arrays to be checksummed
   integer,                   optional, intent(in) :: haloshift !< The width of halos to check (default 0)
   logical,                   optional, intent(in) :: omit_corners !< If true, avoid checking diagonal shifts
   real,                      optional, intent(in) :: scale     !< A scaling factor for this array.
   if (present(haloshift)) then
     call chksum_h_3d(arraya, 'x '//mesg, hi, haloshift, omit_corners, scale=scale)
     call chksum_h_3d(arrayb, 'y '//mesg, hi, haloshift, omit_corners, scale=scale)
   else
     call chksum_h_3d(arraya, 'x '//mesg, hi, scale=scale)
     call chksum_h_3d(arrayb, 'y '//mesg, hi, scale=scale)
   endif
chksum_u_2d()
subroutine mom_checksums::chksum_u_2d (real, dimension(hi%isdb:,hi%jsd:), intent(in) array, character(len=*), intent(in) mesg, type(hor_index_type), intent(in) HI, integer, intent(in), optional haloshift, logical, intent(in), optional symmetric, logical, intent(in), optional omit_corners, real, intent(in), optional scale) private
chksum_u_2d performs checksums on a 2d array staggered at C-grid u points.
Parameters
[in] hi A horizontal index type
[in] array The array to be checksummed
[in] mesg An identifying message
[in] haloshift The width of halos to check (default 0)
[in] symmetric If true, do the checksums on the full symmetric computational domain.
[in] omit_corners If true, avoid checking diagonal shifts
[in] scale A scaling factor for this array.
Definition at line 450 of file MOM_checksums.F90.
References calculatestatistics, checkfornans, chk_sum_msg_nsew(), chk_sum_msg_w(), chksum_error(), default_shift, subchk(), substats(), and writechksums.
Referenced by chksum_uv_2d().
   type(hor_index_type),           intent(in) :: hi     !< A horizontal index type
   real, dimension(HI%IsdB:,HI%jsd:), intent(in) :: array !< The array to be checksummed
   character(len=*),                intent(in) :: mesg  !< An identifying message
   integer,               optional, intent(in) :: haloshift !< The width of halos to check (default 0)
   logical,               optional, intent(in) :: symmetric !< If true, do the checksums on the full symmetric computational domain.
   logical,               optional, intent(in) :: omit_corners !< If true, avoid checking diagonal shifts
   real,                    optional, intent(in) :: scale     !< A scaling factor for this array.
   real :: scaling
   integer :: bc0, bcsw, bcse, bcnw, bcne, hshift
   integer :: bcn, bcs, bce, bcw
   logical :: do_corners, sym, sym_stats
   if (checkfornans) then
     if (is_nan(array(hi%IscB:hi%IecB,hi%jsc:hi%jec))) &
       call chksum_error(fatal, 'NaN detected: '//trim(mesg))
 !   if (is_NaN(array)) &
 !     call chksum_error(FATAL, 'NaN detected in halo: '//trim(mesg))
   endif
   scaling = 1.0 ; if (present(scale)) scaling = scale
   sym_stats = .false. ; if (present(symmetric)) sym_stats = symmetric
   if (present(haloshift)) then ; if (haloshift > 0) sym_stats = .true. ; endif
   if (calculatestatistics) call substats(hi, array, mesg, sym_stats, scaling)
   if (.not.writechksums) return
   hshift = default_shift
   if (present(haloshift)) hshift = haloshift
   if (hshift<0) hshift = hi%iedB-hi%iecB
   if ( hi%iscB-hshift<hi%isdB .or. hi%iecB+hshift>hi%iedB .or. &
        hi%jsc-hshift<hi%jsd .or. hi%jec+hshift>hi%jed ) then
     write(0,*) 'chksum_u_2d: haloshift =',hshift
     write(0,*) 'chksum_u_2d: isd,isc,iec,ied=',hi%isdB,hi%iscB,hi%iecB,hi%iedB
     write(0,*) 'chksum_u_2d: jsd,jsc,jec,jed=',hi%jsd,hi%jsc,hi%jec,hi%jed
     call chksum_error(fatal,'Error in chksum_u_2d '//trim(mesg))
   endif
   bc0 = subchk(array, hi, 0, 0, scaling)
   sym = .false. ; if (present(symmetric)) sym = symmetric
   if ((hshift==0) .and. .not.sym) then
     if (is_root_pe()) call chk_sum_msg("u-point:",bc0,mesg)
     return
   endif
   do_corners = .true. ; if (present(omit_corners)) do_corners = .not.omit_corners
   if (hshift==0) then
     bcw = subchk(array, hi, -hshift-1, 0, scaling)
     if (is_root_pe()) call chk_sum_msg_w("u-point:",bc0,bcw,mesg)
   elseif (do_corners) then
     if (sym) then
       bcsw = subchk(array, hi, -hshift-1, -hshift, scaling)
       bcnw = subchk(array, hi, -hshift-1, hshift, scaling)
     else
       bcsw = subchk(array, hi, -hshift, -hshift, scaling)
       bcnw = subchk(array, hi, -hshift, hshift, scaling)
     endif
     bcse = subchk(array, hi, hshift, -hshift, scaling)
     bcne = subchk(array, hi, hshift, hshift, scaling)
     if (is_root_pe()) call chk_sum_msg("u-point:",bc0,bcsw,bcse,bcnw,bcne,mesg)
   else
     bcs = subchk(array, hi, 0, -hshift, scaling)
     bce = subchk(array, hi, hshift, 0, scaling)
     if (sym) then
       bcw = subchk(array, hi, -hshift-1, 0, scaling)
     else
       bcw = subchk(array, hi, -hshift, 0, scaling)
     endif
     bcn = subchk(array, hi, 0, hshift, scaling)
     if (is_root_pe()) call chk_sum_msg_nsew("u-point:",bc0,bcn,bcs,bce,bcw,mesg)
   endif
   contains
   integer function subchk(array, HI, di, dj, scale)
     type(hor_index_type), intent(in) :: hi
     real, dimension(HI%IsdB:,HI%jsd:), intent(in) :: array
     integer, intent(in) :: di, dj
     real, intent(in) :: scale
     integer :: bitcount, i, j, bc
     subchk = 0
     ! This line deliberately uses the h-point computational domain.
     do j=hi%jsc+dj,hi%jec+dj; do i=hi%isc+di,hi%iec+di
       bc = bitcount(abs(scale*array(i,j)))
       subchk = subchk + bc
     enddo; enddo
     call sum_across_pes(subchk)
     subchk=mod(subchk,1000000000)
   end function subchk
   subroutine substats(HI, array, mesg, sym_stats, scale)
     type(hor_index_type), intent(in) :: hi
     real, dimension(HI%IsdB:,HI%jsd:), intent(in) :: array
     character(len=*), intent(in) :: mesg
     logical, intent(in) :: sym_stats
     real, intent(in) :: scale
     integer :: i, j, n, isb
     real :: amean, amin, amax
     isb = hi%isc ; if (sym_stats) isb = hi%isc-1
     amin = array(hi%isc,hi%jsc) ; amax = amin
     do j=hi%jsc,hi%jec ; do i=isb,hi%IecB
       amin = min(amin, array(i,j))
       amax = max(amax, array(i,j))
     enddo ; enddo
     ! This line deliberately uses the h-point computational domain.
     amean = reproducing_sum(array(hi%isc:hi%iec,hi%jsc:hi%jec))
     n = (1 + hi%jec - hi%jsc) * (1 + hi%iec - hi%isc)
     call sum_across_pes(n)
     call min_across_pes(amin)
     call max_across_pes(amax)
     amean = amean / real(n)
     if (is_root_pe()) call chk_sum_msg("u-point:",amean*scale,amin*scale,amax*scale,mesg)
   end subroutine substats
chksum_u_3d()
subroutine mom_checksums::chksum_u_3d (real, dimension(hi%isdb:,hi%jsd:,:), intent(in) array, character(len=*), intent(in) mesg, type(hor_index_type), intent(in) HI, integer, intent(in), optional haloshift, logical, intent(in), optional symmetric, logical, intent(in), optional omit_corners, real, intent(in), optional scale) private
chksum_u_3d performs checksums on a 3d array staggered at C-grid u points.
Parameters
[in] hi A horizontal index type
[in] array The array to be checksummed
[in] mesg An identifying message
[in] haloshift The width of halos to check (default 0)
[in] symmetric If true, do the checksums on the full symmetric computational domain.
[in] omit_corners If true, avoid checking diagonal shifts
[in] scale A scaling factor for this array.
Definition at line 941 of file MOM_checksums.F90.
References calculatestatistics, checkfornans, chk_sum_msg_nsew(), chk_sum_msg_w(), chksum_error(), default_shift, subchk(), substats(), and writechksums.
Referenced by chksum_uv_3d().
   type(hor_index_type),             intent(in) :: hi !< A horizontal index type
   real, dimension(HI%isdB:,HI%Jsd:,:), intent(in) :: array !< The array to be checksummed
   character(len=*),                  intent(in) :: mesg  !< An identifying message
   integer,                 optional, intent(in) :: haloshift !< The width of halos to check (default 0)
   logical,                 optional, intent(in) :: symmetric !< If true, do the checksums on the full symmetric computational domain.
   logical,                 optional, intent(in) :: omit_corners !< If true, avoid checking diagonal shifts
   real,                    optional, intent(in) :: scale     !< A scaling factor for this array.
   real :: scaling
   integer :: bc0, bcsw, bcse, bcnw, bcne, hshift
   integer :: bcn, bcs, bce, bcw
   logical :: do_corners, sym, sym_stats
   if (checkfornans) then
     if (is_nan(array(hi%IscB:hi%IecB,hi%jsc:hi%jec,:))) &
       call chksum_error(fatal, 'NaN detected: '//trim(mesg))
 !   if (is_NaN(array)) &
 !     call chksum_error(FATAL, 'NaN detected in halo: '//trim(mesg))
   endif
   scaling = 1.0 ; if (present(scale)) scaling = scale
   sym_stats = .false. ; if (present(symmetric)) sym_stats = symmetric
   if (present(haloshift)) then ; if (haloshift > 0) sym_stats = .true. ; endif
   if (calculatestatistics) call substats(hi, array, mesg, sym_stats, scaling)
   if (.not.writechksums) return
   hshift = default_shift
   if (present(haloshift)) hshift = haloshift
   if (hshift<0) hshift = hi%ied-hi%iec
   if ( hi%isc-hshift<hi%isd .or. hi%iec+hshift>hi%ied .or. &
        hi%jsc-hshift<hi%jsd .or. hi%jec+hshift>hi%jed ) then
     write(0,*) 'chksum_u_3d: haloshift =',hshift
     write(0,*) 'chksum_u_3d: isd,isc,iec,ied=',hi%isd,hi%isc,hi%iec,hi%ied
     write(0,*) 'chksum_u_3d: jsd,jsc,jec,jed=',hi%jsd,hi%jsc,hi%jec,hi%jed
     call chksum_error(fatal,'Error in chksum_u_3d '//trim(mesg))
   endif
   bc0 = subchk(array, hi, 0, 0, scaling)
   sym = .false. ; if (present(symmetric)) sym = symmetric
   if ((hshift==0) .and. .not.sym) then
     if (is_root_pe()) call chk_sum_msg("u-point:",bc0,mesg)
     return
   endif
   do_corners = .true. ; if (present(omit_corners)) do_corners = .not.omit_corners
   if (hshift==0) then
     bcw = subchk(array, hi, -hshift-1, 0, scaling)
     if (is_root_pe()) call chk_sum_msg_w("u-point:",bc0,bcw,mesg)
   elseif (do_corners) then
     if (sym) then
       bcsw = subchk(array, hi, -hshift-1, -hshift, scaling)
       bcnw = subchk(array, hi, -hshift-1, hshift, scaling)
     else
       bcsw = subchk(array, hi, -hshift, -hshift, scaling)
       bcnw = subchk(array, hi, -hshift, hshift, scaling)
     endif
     bcse = subchk(array, hi, hshift, -hshift, scaling)
     bcne = subchk(array, hi, hshift, hshift, scaling)
     if (is_root_pe()) call chk_sum_msg("u-point:",bc0,bcsw,bcse,bcnw,bcne,mesg)
   else
     bcs = subchk(array, hi, 0, -hshift, scaling)
     bce = subchk(array, hi, hshift, 0, scaling)
     if (sym) then
       bcw = subchk(array, hi, -hshift-1, 0, scaling)
     else
       bcw = subchk(array, hi, -hshift, 0, scaling)
     endif
     bcn = subchk(array, hi, 0, hshift, scaling)
     if (is_root_pe()) call chk_sum_msg_nsew("u-point:",bc0,bcn,bcs,bce,bcw,mesg)
   endif
   contains
   integer function subchk(array, HI, di, dj, scale)
     type(hor_index_type), intent(in) :: hi
     real, dimension(HI%IsdB:,HI%jsd:,:), intent(in) :: array
     integer, intent(in) :: di, dj
     real, intent(in) :: scale
     integer :: bitcount, i, j, k, bc
     subchk = 0
     ! This line deliberately uses the h-point computational domain.
     do k=lbound(array,3),ubound(array,3) ; do j=hi%jsc+dj,hi%jec+dj ; do i=hi%isc+di,hi%iec+di
       bc = bitcount(abs(scale*array(i,j,k)))
       subchk = subchk + bc
     enddo ; enddo ; enddo
     call sum_across_pes(subchk)
     subchk=mod(subchk,1000000000)
   end function subchk
   subroutine substats(HI, array, mesg, sym_stats, scale)
     type(hor_index_type), intent(in) :: hi
     real, dimension(HI%IsdB:,HI%jsd:,:), intent(in) :: array
     character(len=*), intent(in) :: mesg
     logical, intent(in) :: sym_stats
     real, intent(in) :: scale
     integer :: i, j, k, n, isb
     real :: amean, amin, amax
     isb = hi%isc ; if (sym_stats) isb = hi%isc-1
     amin = array(hi%isc,hi%jsc,1) ; amax = amin
     do k=lbound(array,3),ubound(array,3) ; do j=hi%jsc,hi%jec ; do i=isb,hi%IecB
       amin = min(amin, array(i,j,k))
       amax = max(amax, array(i,j,k))
     enddo ; enddo ; enddo
     ! This line deliberately uses the h-point computational domain.
     amean = reproducing_sum(array(hi%isc:hi%iec,hi%jsc:hi%jec,:))
     n = (1 + hi%jec - hi%jsc) * (1 + hi%iec - hi%isc) * size(array,3)
     call sum_across_pes(n)
     call min_across_pes(amin)
     call max_across_pes(amax)
     amean = amean / real(n)
     if (is_root_pe()) call chk_sum_msg("u-point:",amean*scale,amin*scale,amax*scale,mesg)
   end subroutine substats
chksum_uv_2d()
subroutine mom_checksums::chksum_uv_2d (character(len=*), intent(in) mesg, real, dimension(hi%isdb:,hi%jsd:), intent(in) arrayU, real, dimension(hi%isd:,hi%jsdb:), intent(in) arrayV, type(hor_index_type), intent(in) HI, integer, intent(in), optional haloshift, logical, intent(in), optional symmetric, logical, intent(in), optional omit_corners, real, intent(in), optional scale) private
Parameters
[in] mesg Identifying messages
[in] hi A horizontal index type
[in] arrayu The u-component array to be checksummed
[in] arrayv The v-component array to be checksummed
[in] haloshift The width of halos to check (default 0)
[in] symmetric If true, do the checksums on the full symmetric computational domain.
[in] omit_corners If true, avoid checking diagonal shifts
[in] scale A scaling factor for these arrays.
Definition at line 409 of file MOM_checksums.F90.
References chksum_u_2d(), and chksum_v_2d().
   character(len=*),                  intent(in) :: mesg   !< Identifying messages
   type(hor_index_type),              intent(in) :: hi     !< A horizontal index type
   real, dimension(HI%IsdB:,HI%jsd:), intent(in) :: arrayu !< The u-component array to be checksummed
   real, dimension(HI%isd:,HI%JsdB:), intent(in) :: arrayv !< The v-component array to be checksummed
   integer,                 optional, intent(in) :: haloshift !< The width of halos to check (default 0)
   logical,                 optional, intent(in) :: symmetric !< If true, do the checksums on the full symmetric computational domain.
   logical,                 optional, intent(in) :: omit_corners !< If true, avoid checking diagonal shifts
   real,                    optional, intent(in) :: scale     !< A scaling factor for these arrays.
   if (present(haloshift)) then
     call chksum_u_2d(arrayu, 'u '//mesg, hi, haloshift, symmetric, omit_corners, scale)
     call chksum_v_2d(arrayv, 'v '//mesg, hi, haloshift, symmetric, omit_corners, scale)
   else
     call chksum_u_2d(arrayu, 'u '//mesg, hi, symmetric=symmetric)
     call chksum_v_2d(arrayv, 'v '//mesg, hi, symmetric=symmetric)
   endif
chksum_uv_3d()
subroutine mom_checksums::chksum_uv_3d (character(len=*), intent(in) mesg, real, dimension(hi%isdb:,hi%jsd:,:), intent(in) arrayU, real, dimension(hi%isd:,hi%jsdb:,:), intent(in) arrayV, type(hor_index_type), intent(in) HI, integer, intent(in), optional haloshift, logical, intent(in), optional symmetric, logical, intent(in), optional omit_corners, real, intent(in), optional scale) private
Parameters
[in] mesg Identifying messages
[in] hi A horizontal index type
[in] arrayu The u-component array to be checksummed
[in] arrayv The v-component array to be checksummed
[in] haloshift The width of halos to check (default 0)
[in] symmetric If true, do the checksums on the full symmetric computational domain.
[in] omit_corners If true, avoid checking diagonal shifts
[in] scale A scaling factor for these arrays.
Definition at line 429 of file MOM_checksums.F90.
References chksum_u_3d(), and chksum_v_3d().
   character(len=*),                    intent(in) :: mesg   !< Identifying messages
   type(hor_index_type),                intent(in) :: hi     !< A horizontal index type
   real, dimension(HI%IsdB:,HI%jsd:,:), intent(in) :: arrayu !< The u-component array to be checksummed
   real, dimension(HI%isd:,HI%JsdB:,:), intent(in) :: arrayv !< The v-component array to be checksummed
   integer,                   optional, intent(in) :: haloshift !< The width of halos to check (default 0)
   logical,                   optional, intent(in) :: symmetric !< If true, do the checksums on the full symmetric computational domain.
   logical,                   optional, intent(in) :: omit_corners !< If true, avoid checking diagonal shifts
   real,                      optional, intent(in) :: scale     !< A scaling factor for these arrays.
   if (present(haloshift)) then
     call chksum_u_3d(arrayu, 'u '//mesg, hi, haloshift, symmetric, omit_corners, scale)
     call chksum_v_3d(arrayv, 'v '//mesg, hi, haloshift, symmetric, omit_corners, scale)
   else
     call chksum_u_3d(arrayu, 'u '//mesg, hi, symmetric=symmetric)
     call chksum_v_3d(arrayv, 'v '//mesg, hi, symmetric=symmetric)
   endif
chksum_v_2d()
subroutine mom_checksums::chksum_v_2d (real, dimension(hi%isd:,hi%jsdb:), intent(in) array, character(len=*), intent(in) mesg, type(hor_index_type), intent(in) HI, integer, intent(in), optional haloshift, logical, intent(in), optional symmetric, logical, intent(in), optional omit_corners, real, intent(in), optional scale) private
chksum_v_2d performs checksums on a 2d array staggered at C-grid v points.
Parameters
[in] hi A horizontal index type
[in] array The array to be checksummed
[in] mesg An identifying message
[in] haloshift The width of halos to check (default 0)
[in] symmetric If true, do the checksums on the full symmetric computational domain.
[in] omit_corners If true, avoid checking diagonal shifts
[in] scale A scaling factor for this array.
Definition at line 578 of file MOM_checksums.F90.
References calculatestatistics, checkfornans, chk_sum_msg_nsew(), chk_sum_msg_s(), chksum_error(), default_shift, subchk(), substats(), and writechksums.
Referenced by chksum_uv_2d().
   type(hor_index_type),           intent(in) :: hi     !< A horizontal index type
   real, dimension(HI%isd:,HI%JsdB:), intent(in) :: array !< The array to be checksummed
   character(len=*),                intent(in) :: mesg  !< An identifying message
   integer,               optional, intent(in) :: haloshift !< The width of halos to check (default 0)
   logical,               optional, intent(in) :: symmetric !< If true, do the checksums on the full symmetric computational domain.
   logical,               optional, intent(in) :: omit_corners !< If true, avoid checking diagonal shifts
   real,                  optional, intent(in) :: scale     !< A scaling factor for this array.
   real :: scaling
   integer :: bc0, bcsw, bcse, bcnw, bcne, hshift
   integer :: bcn, bcs, bce, bcw
   logical :: do_corners, sym, sym_stats
   if (checkfornans) then
     if (is_nan(array(hi%isc:hi%iec,hi%JscB:hi%JecB))) &
       call chksum_error(fatal, 'NaN detected: '//trim(mesg))
 !   if (is_NaN(array)) &
 !     call chksum_error(FATAL, 'NaN detected in halo: '//trim(mesg))
   endif
   scaling = 1.0 ; if (present(scale)) scaling = scale
   sym_stats = .false. ; if (present(symmetric)) sym_stats = symmetric
   if (present(haloshift)) then ; if (haloshift > 0) sym_stats = .true. ; endif
   if (calculatestatistics) call substats(hi, array, mesg, sym_stats, scaling)
   if (.not.writechksums) return
   hshift = default_shift
   if (present(haloshift)) hshift = haloshift
   if (hshift<0) hshift = hi%ied-hi%iec
   if ( hi%isc-hshift<hi%isd .or. hi%iec+hshift>hi%ied .or. &
        hi%jscB-hshift<hi%jsdB .or. hi%jecB+hshift>hi%jedB ) then
     write(0,*) 'chksum_v_2d: haloshift =',hshift
     write(0,*) 'chksum_v_2d: isd,isc,iec,ied=',hi%isd,hi%isc,hi%iec,hi%ied
     write(0,*) 'chksum_v_2d: jsd,jsc,jec,jed=',hi%jsdB,hi%jscB,hi%jecB,hi%jedB
     call chksum_error(fatal,'Error in chksum_v_2d '//trim(mesg))
   endif
   bc0 = subchk(array, hi, 0, 0, scaling)
   sym = .false. ; if (present(symmetric)) sym = symmetric
   if ((hshift==0) .and. .not.sym) then
     if (is_root_pe()) call chk_sum_msg("v-point:",bc0,mesg)
     return
   endif
   do_corners = .true. ; if (present(omit_corners)) do_corners = .not.omit_corners
   if (hshift==0) then
     bcs = subchk(array, hi, 0, -hshift-1, scaling)
     if (is_root_pe()) call chk_sum_msg_s("v-point:",bc0,bcs,mesg)
   elseif (do_corners) then
     if (sym) then
       bcsw = subchk(array, hi, -hshift, -hshift-1, scaling)
       bcse = subchk(array, hi, hshift, -hshift-1, scaling)
     else
       bcsw = subchk(array, hi, -hshift, -hshift, scaling)
       bcse = subchk(array, hi, hshift, -hshift, scaling)
     endif
     bcnw = subchk(array, hi, -hshift, hshift, scaling)
     bcne = subchk(array, hi, hshift, hshift, scaling)
     if (is_root_pe()) call chk_sum_msg("v-point:",bc0,bcsw,bcse,bcnw,bcne,mesg)
   else
     if (sym) then
       bcs = subchk(array, hi, 0, -hshift-1, scaling)
     else
       bcs = subchk(array, hi, 0, -hshift, scaling)
     endif
     bce = subchk(array, hi, hshift, 0, scaling)
     bcw = subchk(array, hi, -hshift, 0, scaling)
     bcn = subchk(array, hi, 0, hshift, scaling)
     if (is_root_pe()) call chk_sum_msg_nsew("v-point:",bc0,bcn,bcs,bce,bcw,mesg)
   endif
   contains
   integer function subchk(array, HI, di, dj, scale)
     type(hor_index_type), intent(in) :: hi
     real, dimension(HI%isd:,HI%JsdB:), intent(in) :: array
     integer, intent(in) :: di, dj
     real, intent(in) :: scale
     integer :: bitcount, i, j, bc
     subchk = 0
     ! This line deliberately uses the h-point computational domain.
     do j=hi%jsc+dj,hi%jec+dj; do i=hi%isc+di,hi%iec+di
       bc = bitcount(abs(scale*array(i,j)))
       subchk = subchk + bc
     enddo; enddo
     call sum_across_pes(subchk)
     subchk=mod(subchk,1000000000)
   end function subchk
   subroutine substats(HI, array, mesg, sym_stats, scale)
     type(hor_index_type), intent(in) :: hi
     real, dimension(HI%isd:,HI%JsdB:), intent(in) :: array
     character(len=*), intent(in) :: mesg
     logical, intent(in) :: sym_stats
     real, intent(in) :: scale
     integer :: i, j, n, jsb
     real :: amean, amin, amax
     jsb = hi%jsc ; if (sym_stats) jsb = hi%jsc-1
     amin = array(hi%isc,hi%jsc) ; amax = amin
     do j=jsb,hi%JecB ; do i=hi%isc,hi%iec
       amin = min(amin, array(i,j))
       amax = max(amax, array(i,j))
     enddo ; enddo
     ! This line deliberately uses the h-computational domain.
     amean = reproducing_sum(array(hi%isc:hi%iec,hi%jsc:hi%jec))
     n = (1 + hi%jec - hi%jsc) * (1 + hi%iec - hi%isc)
     call sum_across_pes(n)
     call min_across_pes(amin)
     call max_across_pes(amax)
     amean = amean / real(n)
     if (is_root_pe()) call chk_sum_msg("v-point:",amean*scale,amin*scale,amax*scale,mesg)
   end subroutine substats
chksum_v_3d()
subroutine mom_checksums::chksum_v_3d (real, dimension(hi%isd:,hi%jsdb:,:), intent(in) array, character(len=*), intent(in) mesg, type(hor_index_type), intent(in) HI, integer, intent(in), optional haloshift, logical, intent(in), optional symmetric, logical, intent(in), optional omit_corners, real, intent(in), optional scale) private
chksum_v_3d performs checksums on a 3d array staggered at C-grid v points.
Parameters
[in] hi A horizontal index type
[in] array The array to be checksummed
[in] mesg An identifying message
[in] haloshift The width of halos to check (default 0)
[in] symmetric If true, do the checksums on the full symmetric computational domain.
[in] omit_corners If true, avoid checking diagonal shifts
[in] scale A scaling factor for this array.
Definition at line 1069 of file MOM_checksums.F90.
References calculatestatistics, checkfornans, chk_sum_msg_nsew(), chk_sum_msg_s(), chksum_error(), default_shift, subchk(), substats(), and writechksums.
Referenced by chksum_uv_3d().
   type(hor_index_type),             intent(in) :: hi !< A horizontal index type
   real, dimension(HI%isd:,HI%JsdB:,:), intent(in) :: array !< The array to be checksummed
   character(len=*),                  intent(in) :: mesg  !< An identifying message
   integer,                 optional, intent(in) :: haloshift !< The width of halos to check (default 0)
   logical,                 optional, intent(in) :: symmetric !< If true, do the checksums on the full symmetric computational domain.
   logical,                 optional, intent(in) :: omit_corners !< If true, avoid checking diagonal shifts
   real,                    optional, intent(in) :: scale     !< A scaling factor for this array.
   real :: scaling
   integer :: bc0, bcsw, bcse, bcnw, bcne, hshift
   integer :: bcn, bcs, bce, bcw
   logical :: do_corners, sym, sym_stats
   if (checkfornans) then
     if (is_nan(array(hi%isc:hi%iec,hi%JscB:hi%JecB,:))) &
       call chksum_error(fatal, 'NaN detected: '//trim(mesg))
 !   if (is_NaN(array)) &
 !     call chksum_error(FATAL, 'NaN detected in halo: '//trim(mesg))
   endif
   scaling = 1.0 ; if (present(scale)) scaling = scale
   sym_stats = .false. ; if (present(symmetric)) sym_stats = symmetric
   if (present(haloshift)) then ; if (haloshift > 0) sym_stats = .true. ; endif
   if (calculatestatistics) call substats(hi, array, mesg, sym_stats, scaling)
   if (.not.writechksums) return
   hshift = default_shift
   if (present(haloshift)) hshift = haloshift
   if (hshift<0) hshift = hi%ied-hi%iec
   if ( hi%isc-hshift<hi%isd .or. hi%iec+hshift>hi%ied .or. &
        hi%jsc-hshift<hi%jsd .or. hi%jec+hshift>hi%jed ) then
     write(0,*) 'chksum_v_3d: haloshift =',hshift
     write(0,*) 'chksum_v_3d: isd,isc,iec,ied=',hi%isd,hi%isc,hi%iec,hi%ied
     write(0,*) 'chksum_v_3d: jsd,jsc,jec,jed=',hi%jsd,hi%jsc,hi%jec,hi%jed
     call chksum_error(fatal,'Error in chksum_v_3d '//trim(mesg))
   endif
   bc0 = subchk(array, hi, 0, 0, scaling)
   sym = .false. ; if (present(symmetric)) sym = symmetric
   if ((hshift==0) .and. .not.sym) then
     if (is_root_pe()) call chk_sum_msg("v-point:",bc0,mesg)
     return
   endif
   do_corners = .true. ; if (present(omit_corners)) do_corners = .not.omit_corners
   if (hshift==0) then
     bcs = subchk(array, hi, 0, -hshift-1, scaling)
     if (is_root_pe()) call chk_sum_msg_s("v-point:",bc0,bcs,mesg)
   elseif (do_corners) then
     if (sym) then
       bcsw = subchk(array, hi, -hshift, -hshift-1, scaling)
       bcse = subchk(array, hi, hshift, -hshift-1, scaling)
     else
       bcsw = subchk(array, hi, -hshift, -hshift, scaling)
       bcse = subchk(array, hi, hshift, -hshift, scaling)
     endif
     bcnw = subchk(array, hi, -hshift, hshift, scaling)
     bcne = subchk(array, hi, hshift, hshift, scaling)
     if (is_root_pe()) call chk_sum_msg("v-point:",bc0,bcsw,bcse,bcnw,bcne,mesg)
   else
     if (sym) then
       bcs = subchk(array, hi, 0, -hshift-1, scaling)
     else
       bcs = subchk(array, hi, 0, -hshift, scaling)
     endif
     bce = subchk(array, hi, hshift, 0, scaling)
     bcw = subchk(array, hi, -hshift, 0, scaling)
     bcn = subchk(array, hi, 0, hshift, scaling)
     if (is_root_pe()) call chk_sum_msg_nsew("v-point:",bc0,bcn,bcs,bce,bcw,mesg)
   endif
   contains
   integer function subchk(array, HI, di, dj, scale)
     type(hor_index_type), intent(in) :: hi
     real, dimension(HI%isd:,HI%JsdB:,:), intent(in) :: array
     integer, intent(in) :: di, dj
     real, intent(in) :: scale
     integer :: bitcount, i, j, k, bc
     subchk = 0
     ! This line deliberately uses the h-point computational domain.
     do k=lbound(array,3),ubound(array,3) ; do j=hi%jsc+dj,hi%jec+dj ; do i=hi%isc+di,hi%iec+di
       bc = bitcount(abs(scale*array(i,j,k)))
       subchk = subchk + bc
     enddo ; enddo ; enddo
     call sum_across_pes(subchk)
     subchk=mod(subchk,1000000000)
   end function subchk
   subroutine substats(HI, array, mesg, sym_stats, scale)
     type(hor_index_type), intent(in) :: hi
     real, dimension(HI%isd:,HI%JsdB:,:), intent(in) :: array
     character(len=*), intent(in) :: mesg
     logical, intent(in) :: sym_stats
     real, intent(in) :: scale
     integer :: i, j, k, n, jsb
     real :: amean, amin, amax
     jsb = hi%jsc ; if (sym_stats) jsb = hi%jsc-1
     amin = array(hi%isc,hi%jsc,1) ; amax = amin
     do k=lbound(array,3),ubound(array,3) ; do j=jsb,hi%JecB ; do i=hi%isc,hi%iec
       amin = min(amin, array(i,j,k))
       amax = max(amax, array(i,j,k))
     enddo ; enddo ; enddo
     ! This line deliberately uses the h-point computational domain.
     amean = reproducing_sum(array(hi%isc:hi%iec,hi%jsc:hi%jec,:))
     n = (1 + hi%jec - hi%jsc) * (1 + hi%iec - hi%isc) * size(array,3)
     call sum_across_pes(n)
     call min_across_pes(amin)
     call max_across_pes(amax)
     amean = amean / real(n)
     if (is_root_pe()) call chk_sum_msg("v-point:",amean*scale,amin*scale,amax*scale,mesg)
   end subroutine substats
is_nan_0d()
logical function mom_checksums::is_nan_0d (real, intent(in) x) private
This function returns .true. if x is a NaN, and .false. otherwise.
Parameters
[in] x The value to be checked for NaNs.
Definition at line 1322 of file MOM_checksums.F90.
Referenced by is_nan_1d(), is_nan_2d(), and is_nan_3d().
   real, intent(in) :: x !< The value to be checked for NaNs.
   logical :: is_nan_0d
  !is_NaN_0d = (((x < 0.0) .and. (x >= 0.0)) .or. &
  !          (.not.(x < 0.0) .and. .not.(x >= 0.0)))
   if (((x < 0.0) .and. (x >= 0.0)) .or. &
             (.not.(x < 0.0) .and. .not.(x >= 0.0))) then
     is_nan_0d = .true.
   else
     is_nan_0d = .false.
   endif
is_nan_1d()
logical function mom_checksums::is_nan_1d (real, dimension(:), intent(in) x, logical, optional skip_mpp) private
This function returns .true. if any element of x is a NaN, and .false. otherwise.
Parameters
[in] x The array to be checked for NaNs.
skip_mpp If true, only check this array only on the local PE (default false).
Definition at line 1340 of file MOM_checksums.F90.
References is_nan_0d().
   real, dimension(:), intent(in) :: x !< The array to be checked for NaNs.
   logical :: is_nan_1d
   logical, optional :: skip_mpp  !< If true, only check this array only on the local PE (default false).
   integer :: i, n
   logical :: call_mpp
   n = 0
   do i = lbound(x,1), ubound(x,1)
     if (is_nan_0d(x(i))) n = n + 1
   enddo
   call_mpp = .true.
   if (present(skip_mpp)) call_mpp = .not.skip_mpp
   if (call_mpp) call sum_across_pes(n)
   is_nan_1d = .false.
   if (n>0) is_nan_1d = .true.
is_nan_2d()
logical function mom_checksums::is_nan_2d (real, dimension(:,:), intent(in) x) private
This function returns .true. if any element of x is a NaN, and .false. otherwise.
Parameters
[in] x The array to be checked for NaNs.
Definition at line 1364 of file MOM_checksums.F90.
References is_nan_0d().
   real, dimension(:,:), intent(in) :: x !< The array to be checked for NaNs.
   logical :: is_nan_2d
   integer :: i, j, n
   n = 0
   do j = lbound(x,2), ubound(x,2) ; do i = lbound(x,1), ubound(x,1)
     if (is_nan_0d(x(i,j))) n = n + 1
   enddo ; enddo
   call sum_across_pes(n)
   is_nan_2d = .false.
   if (n>0) is_nan_2d = .true.
is_nan_3d()
logical function mom_checksums::is_nan_3d (real, dimension(:,:,:), intent(in) x) private
This function returns .true. if any element of x is a NaN, and .false. otherwise.
Parameters
[in] x The array to be checked for NaNs.
Definition at line 1383 of file MOM_checksums.F90.
References is_nan_0d().
   real, dimension(:,:,:), intent(in) :: x !< The array to be checked for NaNs.
   logical :: is_nan_3d
   integer :: i, j, k, n
   n = 0
   do k = lbound(x,3), ubound(x,3)
     do j = lbound(x,2), ubound(x,2) ; do i = lbound(x,1), ubound(x,1)
       if (is_nan_0d(x(i,j,k))) n = n + 1
     enddo ; enddo
   enddo
   call sum_across_pes(n)
   is_nan_3d = .false.
   if (n>0) is_nan_3d = .true.
mom_checksums_init()
subroutine, public mom_checksums::mom_checksums_init (type(param_file_type), intent(in) param_file)
MOM_checksums_init initializes the MOM_checksums module. As it happens, the only thing that it does is to log the version of this module.
Parameters
[in] param_file A structure to parse for run-time parameters
Definition at line 1467 of file MOM_checksums.F90.
Referenced by mom_debugging::mom_debugging_init().
   type(param_file_type),   intent(in)    :: param_file !< A structure to parse for run-time parameters
 ! This include declares and sets the variable "version".
 #include "version_variable.h"
   character(len=40)  :: mdl = "MOM_checksums" ! This module's name.
   call log_version(param_file, mdl, version)
Variable Documentation
calculatestatistics
logical mom_checksums::calculatestatistics =.true. private
Definition at line 82 of file MOM_checksums.F90.
Referenced by chksum_b_2d(), chksum_b_3d(), chksum_h_2d(), chksum_h_3d(), chksum_u_2d(), chksum_u_3d(), chksum_v_2d(), and chksum_v_3d().
 logical :: calculatestatistics=.true. ! If true, report min, max and mean.
checkfornans
logical mom_checksums::checkfornans =.true. private
Definition at line 84 of file MOM_checksums.F90.
Referenced by chksum_b_2d(), chksum_b_3d(), chksum_h_2d(), chksum_h_3d(), chksum_u_2d(), chksum_u_3d(), chksum_v_2d(), and chksum_v_3d().
 logical :: checkfornans=.true. ! If true, checks array for NaNs and cause
default_shift
integer, parameter mom_checksums::default_shift =0 private
Definition at line 81 of file MOM_checksums.F90.
Referenced by chksum_b_2d(), chksum_b_3d(), chksum_h_2d(), chksum_h_3d(), chksum_u_2d(), chksum_u_3d(), chksum_v_2d(), and chksum_v_3d().
 integer, parameter :: default_shift=0
writechksums
logical mom_checksums::writechksums =.true. private
Definition at line 83 of file MOM_checksums.F90.
Referenced by chksum_b_2d(), chksum_b_3d(), chksum_h_2d(), chksum_h_3d(), chksum_u_2d(), chksum_u_3d(), chksum_v_2d(), and chksum_v_3d().
 logical :: writechksums=.true. ! If true, report the bitcount checksum