MOM6: mom_checksum_packages Module Reference
mom_checksum_packages Module Reference
Data Types
interface mom_state_chksum
type stats
Functions/Subroutines
subroutine mom_state_chksum_5arg (mesg, u, v, h, uh, vh, G, GV, haloshift, symmetric)
subroutine mom_state_chksum_3arg (mesg, u, v, h, G, GV, haloshift, symmetric)
subroutine, public mom_thermo_chksum (mesg, tv, G, haloshift)
subroutine, public mom_accel_chksum (mesg, CAu, CAv, PFu, PFv, diffu, diffv, G, GV, pbce, u_accel_bt, v_accel_bt, symmetric)
subroutine, public mom_state_stats (mesg, u, v, h, Temp, Salt, G, allowChange, permitDiminishing)
Function/Subroutine Documentation
mom_accel_chksum()
subroutine, public mom_checksum_packages::mom_accel_chksum (character(len=*), intent(in) mesg, real, dimension(szib_(g),szj_(g),szk_(g)), intent(in) CAu, real, dimension(szi_(g),szjb_(g),szk_(g)), intent(in) CAv, real, dimension(szib_(g),szj_(g),szk_(g)), intent(in) PFu, real, dimension(szi_(g),szjb_(g),szk_(g)), intent(in) PFv, real, dimension(szib_(g),szj_(g),szk_(g)), intent(in) diffu, real, dimension(szi_(g),szjb_(g),szk_(g)), intent(in) diffv, type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, real, dimension(szi_(g),szj_(g),szk_(g)), intent(in), optional pbce, real, dimension(szib_(g),szj_(g),szk_(g)), intent(in), optional u_accel_bt, real, dimension(szi_(g),szjb_(g),szk_(g)), intent(in), optional v_accel_bt, logical, intent(in), optional symmetric)
Parameters
[in] mesg A message that appears on the chksum lines.
[in] g The ocean's grid structure.
[in] gv The ocean's vertical grid structure.
[in] cau Zonal acceleration due to Coriolis
[in] cav Meridional acceleration due to Coriolis
[in] pfu Zonal acceleration due to pressure gradients
[in] pfv Meridional acceleration due to pressure gradients
[in] diffu Zonal acceleration due to convergence of the
[in] diffv Meridional acceleration due to convergence of
[in] pbce The baroclinic pressure anomaly in each layer
[in] u_accel_bt The zonal acceleration from terms in the
[in] v_accel_bt The meridional acceleration from terms in
Definition at line 161 of file MOM_checksum_packages.F90.
Referenced by mom_dynamics_legacy_split::step_mom_dyn_legacy_split(), mom_dynamics_split_rk2::step_mom_dyn_split_rk2(), mom_dynamics_unsplit::step_mom_dyn_unsplit(), and mom_dynamics_unsplit_rk2::step_mom_dyn_unsplit_rk2().
   character(len=*),         intent(in) :: mesg !< A message that appears on the chksum lines.
   type(ocean_grid_type),    intent(in) :: g    !< The ocean's grid structure.
   type(verticalgrid_type),  intent(in) :: gv   !< The ocean's vertical grid structure.
   real, dimension(SZIB_(G),SZJ_(G),SZK_(G)), &
                             intent(in) :: cau  !< Zonal acceleration due to Coriolis
                                                !! and momentum advection terms, in m s-2.
   real, dimension(SZI_(G),SZJB_(G),SZK_(G)), &
                             intent(in) :: cav  !< Meridional acceleration due to Coriolis
                                                !! and momentum advection terms, in m s-2.
   real, dimension(SZIB_(G),SZJ_(G),SZK_(G)), &
                             intent(in) :: pfu  !< Zonal acceleration due to pressure gradients
                                                !! (equal to -dM/dx) in m s-2.
   real, dimension(SZI_(G),SZJB_(G),SZK_(G)), &
                             intent(in) :: pfv  !< Meridional acceleration due to pressure gradients
                                                !! (equal to -dM/dy) in m s-2.
   real, dimension(SZIB_(G),SZJ_(G),SZK_(G)), &
                             intent(in) :: diffu !< Zonal acceleration due to convergence of the
                                                 !! along-isopycnal stress tensor, in m s-2.
   real, dimension(SZI_(G),SZJB_(G),SZK_(G)), &
                             intent(in) :: diffv !< Meridional acceleration due to convergence of
                                                 !! the along-isopycnal stress tensor, in m s-2.
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)),  &
                   optional, intent(in) :: pbce !< The baroclinic pressure anomaly in each layer
                                                !! due to free surface height anomalies, in
                                                !! m2 s-2 H-1.                                                                         !! NULL.
   real, dimension(SZIB_(G),SZJ_(G),SZK_(G)), &
                   optional, intent(in) :: u_accel_bt !< The zonal acceleration from terms in the
                                                      !! barotropic solver,in m s-2.
   real, dimension(SZI_(G),SZJB_(G),SZK_(G)), &
                   optional, intent(in) :: v_accel_bt !< The meridional acceleration from terms in
                                                      !! the barotropic solver,in m s-2.
   logical, optional,        intent(in) :: symmetric
 !   This subroutine writes out chksums for the model's accelerations.
 ! Arguments: mesg - A message that appears on the chksum lines.
 !  (in)      CAu - Zonal acceleration due to Coriolis and momentum
 !                  advection terms, in m s-2.
 !  (in)      CAv - Meridional acceleration due to Coriolis and
 !                  momentum advection terms, in m s-2.
 !  (in)      PFu - Zonal acceleration due to pressure gradients
 !                  (equal to -dM/dx) in m s-2.
 !  (in)      PFv - Meridional acceleration due to pressure
 !                  gradients (equal to -dM/dy) in m s-2.
 !  (in)      diffu - Zonal acceleration due to convergence of the
 !                    along-isopycnal stress tensor, in m s-2.
 !  (in)      diffv - Meridional acceleration due to convergence of
 !                    the along-isopycnal stress tensor, in m s-2.
 !  (in)      G - The ocean's grid structure.
 !  (in)      GV - The ocean's vertical grid structure.
 !  (in)      pbce - the baroclinic pressure anomaly in each layer
 !                   due to free surface height anomalies, in m2 s-2 H-1.
 !                   pbce points to a space with nz layers or NULL.
 !  (in)      u_accel_bt - The zonal acceleration from terms in the barotropic
 !                         solver, in m s-2.
 !  (in)      v_accel_bt - The meridional acceleration from terms in the
 !                         barotropic solver, in m s-2.
   integer :: is, ie, js, je, nz
   logical :: sym
   is = g%isc ; ie = g%iec ; js = g%jsc ; je = g%jec ; nz = g%ke
   sym=.false.; if (present(symmetric)) sym=symmetric
   ! Note that for the chksum calls to be useful for reproducing across PE
   ! counts, there must be no redundant points, so all variables use is..ie
   ! and js...je as their extent.
   call uvchksum(mesg//" CA[uv]", cau, cav, g%HI, haloshift=0, symmetric=sym)
   call uvchksum(mesg//" PF[uv]", pfu, pfv, g%HI, haloshift=0, symmetric=sym)
   call uvchksum(mesg//" diffu", diffu, diffv, g%HI,haloshift=0, symmetric=sym)
   if (present(pbce)) &
     call hchksum(pbce, mesg//" pbce",g%HI,haloshift=0, scale=gv%m_to_H)
   if (present(u_accel_bt) .and. present(v_accel_bt)) &
     call uvchksum(mesg//" [uv]_accel_bt", u_accel_bt, v_accel_bt, g%HI,haloshift=0, symmetric=sym)
mom_state_chksum_3arg()
subroutine mom_checksum_packages::mom_state_chksum_3arg (character(len=*), intent(in) mesg, real, dimension(szib_(g),szj_(g),szk_(g)), intent(in) u, real, dimension(szi_(g),szjb_(g),szk_(g)), intent(in) v, real, dimension(szi_(g),szj_(g),szk_(g)), intent(in) h, type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, integer, intent(in), optional haloshift, logical, intent(in), optional symmetric) private
Parameters
[in] mesg A message that appears on the chksum lines.
[in] g The ocean's grid structure.
[in] gv The ocean's vertical grid structure.
[in] u Zonal velocity, in m s-1.
[in] v Meridional velocity, in m s-1.
[in] h Layer thicknesses, in H (usually m or kg m-2).
Definition at line 99 of file MOM_checksum_packages.F90.
   character(len=*),        intent(in) :: mesg !< A message that appears on the chksum lines.
   type(ocean_grid_type),   intent(in) :: g    !< The ocean's grid structure.
   type(verticalgrid_type), intent(in) :: gv   !< The ocean's vertical grid structure.
   real, dimension(SZIB_(G),SZJ_(G),SZK_(G)), &
                            intent(in) :: u    !< Zonal velocity, in m s-1.
   real, dimension(SZI_(G),SZJB_(G),SZK_(G)), &
                            intent(in) :: v    !< Meridional velocity, in m s-1.
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)),  &
                            intent(in) :: h    !< Layer thicknesses, in H (usually m or kg m-2).
   integer, optional,       intent(in) :: haloshift
   logical, optional,       intent(in) :: symmetric
 !   This subroutine writes out chksums for the model's basic state variables.
 ! Arguments: mesg - A message that appears on the chksum lines.
 !  (in)      u - Zonal velocity, in m s-1.
 !  (in)      v - Meridional velocity, in m s-1.
 !  (in)      h - Layer thickness, in m.
 !  (in)      uh - Volume flux through zonal faces = u*h*dy, m3 s-1.
 !  (in)      vh - Volume flux through meridional faces = v*h*dx, in m3 s-1.
 !  (in)      G - The ocean's grid structure.
 !  (in)      GV - The ocean's vertical grid structure.
   integer :: is, ie, js, je, nz, hs
   logical :: sym
   is = g%isc ; ie = g%iec ; js = g%jsc ; je = g%jec ; nz = g%ke
   ! Note that for the chksum calls to be useful for reproducing across PE
   ! counts, there must be no redundant points, so all variables use is..ie
   ! and js...je as their extent.
   hs=1; if (present(haloshift)) hs=haloshift
   sym=.false.; if (present(symmetric)) sym=symmetric
   call uvchksum(mesg//" u", u, v, g%HI,haloshift=hs, symmetric=sym)
   call hchksum(h, mesg//" h",g%HI, haloshift=hs, scale=gv%H_to_m)
mom_state_chksum_5arg()
subroutine mom_checksum_packages::mom_state_chksum_5arg (character(len=*), intent(in) mesg, real, dimension(g %isdb: g %iedb, g %jsd: g %jed, g %ke), intent(in) u, real, dimension(g %isd: g %ied, g %jsdb: g %jedb, g %ke), intent(in) v, real, dimension(g %isd: g %ied, g %jsd: g %jed, g %ke), intent(in) h, real, dimension(g %isdb: g %iedb, g %jsd: g %jed, g %ke), intent(in) uh, real, dimension(g %isd: g %ied, g %jsdb: g %jedb, g %ke), intent(in) vh, type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, integer, intent(in), optional haloshift, logical, intent(in), optional symmetric) private
Parameters
[in] mesg A message that appears on the chksum lines.
[in] g The ocean's grid structure.
[in] gv The ocean's vertical grid structure.
[in] u The zonal velocity, in m s-1.
[in] v The meridional velocity, in m s-1.
[in] h Layer thicknesses, in H (usually m or kg m-2).
[in] uh Volume flux through zonal faces = u*h*dy, m3 s-1.
[in] vh Volume flux through meridional
Definition at line 55 of file MOM_checksum_packages.F90.
   character(len=*),                          &
                            intent(in) :: mesg !< A message that appears on the chksum lines.
   type(ocean_grid_type),   intent(in) :: g    !< The ocean's grid structure.
   type(verticalgrid_type), intent(in) :: gv   !< The ocean's vertical grid structure.
   real, dimension(SZIB_(G),SZJ_(G),SZK_(G)), &
                            intent(in) :: u    !< The zonal velocity, in m s-1.
   real, dimension(SZI_(G),SZJB_(G),SZK_(G)), &
                            intent(in) :: v    !< The meridional velocity, in m s-1.
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)),  &
                            intent(in) :: h    !< Layer thicknesses, in H (usually m or kg m-2).
   real, dimension(SZIB_(G),SZJ_(G),SZK_(G)), &
                            intent(in) :: uh   !< Volume flux through zonal faces = u*h*dy, m3 s-1.
   real, dimension(SZI_(G),SZJB_(G),SZK_(G)), &
                            intent(in) :: vh   !< Volume flux through meridional
                                               !! faces = v*h*dx, in m3 s-1.
   integer, optional,       intent(in) :: haloshift
   logical, optional,       intent(in) :: symmetric
 !   This subroutine writes out chksums for the model's basic state variables.
 ! Arguments: mesg - A message that appears on the chksum lines.
 !  (in)      u - Zonal velocity, in m s-1.
 !  (in)      v - Meridional velocity, in m s-1.
 !  (in)      h - Layer thickness, in m.
 !  (in)      uh - Volume flux through zonal faces = u*h*dy, m3 s-1.
 !  (in)      vh - Volume flux through meridional faces = v*h*dx, in m3 s-1.
 !  (in)      G - The ocean's grid structure.
 !  (in)      GV - The ocean's vertical grid structure.
   integer :: is, ie, js, je, nz, hs
   logical :: sym
   is = g%isc ; ie = g%iec ; js = g%jsc ; je = g%jec ; nz = g%ke
   ! Note that for the chksum calls to be useful for reproducing across PE
   ! counts, there must be no redundant points, so all variables use is..ie
   ! and js...je as their extent.
   hs=1; if (present(haloshift)) hs=haloshift
   sym=.false.; if (present(symmetric)) sym=symmetric
   call uvchksum(mesg//" [uv]", u, v, g%HI, haloshift=hs, symmetric=sym)
   call hchksum(h, mesg//" h", g%HI, haloshift=hs, scale=gv%H_to_m)
   call uvchksum(mesg//" [uv]h", uh, vh, g%HI, haloshift=hs, &
                 symmetric=sym, scale=gv%H_to_m)
mom_state_stats()
subroutine, public mom_checksum_packages::mom_state_stats (character(len=*), intent(in) mesg, real, dimension(szib_(g),szj_(g),szk_(g)), intent(in) u, real, dimension(szi_(g),szjb_(g),szk_(g)), intent(in) v, real, dimension(szi_(g),szj_(g),szk_(g)), intent(in) h, real, dimension(:,:,:), intent(in), pointer Temp, real, dimension(:,:,:), intent(in), pointer Salt, type(ocean_grid_type), intent(in) G, logical, intent(in), optional allowChange, logical, intent(in), optional permitDiminishing)
Parameters
[in] g The ocean's grid structure.
[in] mesg A message that appears on the chksum lines.
[in] u The zonal velocity, in m s-1.
[in] v The meridional velocity, in m s-1.
[in] h Layer thicknesses, in H (usually m or kg m-2).
[in] temp Temperature in degree C.
[in] salt Salinity, in ppt.
[in] allowchange do not flag an error if the statistics change.
[in] permitdiminishing do not flag error
Definition at line 238 of file MOM_checksum_packages.F90.
References mom_error_handler::is_root_pe(), and mom_error_handler::mom_mesg().
Referenced by mom_diabatic_driver::diabatic().
   type(ocean_grid_type),   intent(in) :: g    !< The ocean's grid structure.
   character(len=*),        intent(in) :: mesg !< A message that appears on the chksum lines.
   real, dimension(SZIB_(G),SZJ_(G),SZK_(G)), &
                            intent(in) :: u    !< The zonal velocity, in m s-1.
   real, dimension(SZI_(G),SZJB_(G),SZK_(G)), &
                            intent(in) :: v    !< The meridional velocity, in m s-1.
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)),  &
                            intent(in) :: h    !< Layer thicknesses, in H (usually m or kg m-2).
   real, pointer, dimension(:,:,:),           &
                            intent(in) :: temp !< Temperature in degree C.
   real, pointer, dimension(:,:,:),           &
                            intent(in) :: salt !< Salinity, in ppt.
   logical, optional,       intent(in) :: allowchange !< do not flag an error
                                                                        !! if the statistics change.
   logical, optional,                         &
                            intent(in) :: permitdiminishing !< do not flag error
                                                            !!if the extrema are diminishing.
 !   This subroutine monitors statistics for the model's state variables.
 ! Arguments: mesg - A message that appears on the chksum lines.
 !  (in) u - Zonal velocity, in m s-1.
 !  (in) v - Meridional velocity, in m s-1.
 !  (in) h - Layer thickness, in m.
 !  (in) T - Temperature, in degree C.
 !  (in) S - Salinity, in ppt.
 !  (in) G - The ocean's grid structure.
 !  (in) allowChange - do not flag an error if the statistics change
 !  (in) permitDiminishing - do not flag an error if the extrema are diminishing
   integer :: is, ie, js, je, nz, i, j, k
   real :: vol, dv, area, h_minimum
   type(stats) :: t, s, delt, dels
   type(stats), save :: oldt, olds     ! NOTE: save data is not normally allowed but
   logical, save :: firstcall = .true. ! we use it for debugging purposes here on the
   logical :: do_ts
   real, save :: oldvol                ! assumption we will not turn this on with threads
   character(len=80) :: lmsg
   is = g%isc ; ie = g%iec ; js = g%jsc ; je = g%jec ; nz = g%ke
   do_ts = associated(temp) .and. associated(salt)
   ! First collect local stats
   area = 0. ; vol = 0.
   do j = js, je ; do i = is, ie
     area = area + g%areaT(i,j)
   enddo ; enddo
   t%minimum = 1.e34 ; t%maximum = -1.e34 ; t%average = 0.
   s%minimum = 1.e34 ; s%maximum = -1.e34 ; s%average = 0.
   h_minimum = 1.e34
   do k = 1, nz ; do j = js, je ; do i = is, ie
     if (g%mask2dT(i,j)>0.) then
       dv = g%areaT(i,j)*h(i,j,k) ; vol = vol + dv
       if (do_ts .and. h(i,j,k)>0.) then
         t%minimum = min( t%minimum, temp(i,j,k) ) ; t%maximum = max( t%maximum, temp(i,j,k) )
         t%average = t%average + dv*temp(i,j,k)
         s%minimum = min( s%minimum, salt(i,j,k) ) ; s%maximum = max( s%maximum, salt(i,j,k) )
         s%average = s%average + dv*salt(i,j,k)
       endif
       if (h_minimum > h(i,j,k)) h_minimum = h(i,j,k)
     endif
   enddo ; enddo ; enddo
   call sum_across_pes( area ) ; call sum_across_pes( vol )
   if (do_ts) then
     call min_across_pes( t%minimum ) ; call max_across_pes( t%maximum ) ; call sum_across_pes( t%average )
     call min_across_pes( s%minimum ) ; call max_across_pes( s%maximum ) ; call sum_across_pes( s%average )
     t%average = t%average / vol ; s%average = s%average / vol
   endif
   if (is_root_pe()) then
     if (.not.firstcall) then
       dv = vol - oldvol
       delt%minimum = t%minimum - oldt%minimum ; delt%maximum = t%maximum - oldt%maximum
       delt%average = t%average - oldt%average
       dels%minimum = s%minimum - olds%minimum ; dels%maximum = s%maximum - olds%maximum
       dels%average = s%average - olds%average
       write(lmsg(1:80),'(2(a,es12.4))') 'Mean thickness =',vol/area,' frac. delta=',dv/vol
       call mom_mesg(lmsg//trim(mesg))
       if (do_ts) then
         write(lmsg(1:80),'(a,3es12.4)') 'Temp min/mean/max =',t%minimum,t%average,t%maximum
         call mom_mesg(lmsg//trim(mesg))
         write(lmsg(1:80),'(a,3es12.4)') 'delT min/mean/max =',delt%minimum,delt%average,delt%maximum
         call mom_mesg(lmsg//trim(mesg))
         write(lmsg(1:80),'(a,3es12.4)') 'Salt min/mean/max =',s%minimum,s%average,s%maximum
         call mom_mesg(lmsg//trim(mesg))
         write(lmsg(1:80),'(a,3es12.4)') 'delS min/mean/max =',dels%minimum,dels%average,dels%maximum
         call mom_mesg(lmsg//trim(mesg))
       endif
     else
       write(lmsg(1:80),'(a,es12.4)') 'Mean thickness =',vol/area
       call mom_mesg(lmsg//trim(mesg))
       if (do_ts) then
         write(lmsg(1:80),'(a,3es12.4)') 'Temp min/mean/max =',t%minimum,t%average,t%maximum
         call mom_mesg(lmsg//trim(mesg))
         write(lmsg(1:80),'(a,3es12.4)') 'Salt min/mean/max =',s%minimum,s%average,s%maximum
         call mom_mesg(lmsg//trim(mesg))
       endif
     endif
   endif
   firstcall = .false. ; oldvol = vol
   oldt%minimum = t%minimum ; oldt%maximum = t%maximum ; oldt%average = t%average
   olds%minimum = s%minimum ; olds%maximum = s%maximum ; olds%average = s%average
   if (do_ts .and. t%minimum<-5.0) then
     do j = js, je ; do i = is, ie
       if (minval(temp(i,j,:)) == t%minimum) then
         write(0,'(a,2f12.5)') 'x,y=',g%geoLonT(i,j),g%geoLatT(i,j)
         write(0,'(a3,3a12)') 'k','h','Temp','Salt'
         do k = 1, nz
           write(0,'(i3,3es12.4)') k,h(i,j,k),temp(i,j,k),salt(i,j,k)
         enddo
         stop 'Extremum detected'
       endif
     enddo ; enddo
   endif
   if (h_minimum<0.0) then
     do j = js, je ; do i = is, ie
       if (minval(h(i,j,:)) == h_minimum) then
         write(0,'(a,2f12.5)') 'x,y=',g%geoLonT(i,j),g%geoLatT(i,j)
         write(0,'(a3,3a12)') 'k','h','Temp','Salt'
         do k = 1, nz
           write(0,'(i3,3es12.4)') k,h(i,j,k),temp(i,j,k),salt(i,j,k)
         enddo
         stop 'Negative thickness detected'
       endif
     enddo ; enddo
   endif
mom_thermo_chksum()
subroutine, public mom_checksum_packages::mom_thermo_chksum (character(len=*), intent(in) mesg, type(thermo_var_ptrs), intent(in) tv, type(ocean_grid_type), intent(in) G, integer, intent(in), optional haloshift)
Parameters
[in] mesg A message that appears on the chksum lines.
[in] tv A structure pointing to various thermodynamic variables.
[in] g The ocean's grid structure.
Definition at line 135 of file MOM_checksum_packages.F90.
Referenced by mom::step_mom_thermo().
   character(len=*),         intent(in) :: mesg !< A message that appears on the chksum lines.
   type(thermo_var_ptrs),    intent(in) :: tv   !< A structure pointing to various
                                                !! thermodynamic variables.
   type(ocean_grid_type),    intent(in) :: g    !< The ocean's grid structure.
   integer, optional,        intent(in) :: haloshift
 !   This subroutine writes out chksums for the model's thermodynamic state
 ! variables.
 ! Arguments: mesg - A message that appears on the chksum lines.
 !  (in)      tv - A structure containing pointers to any thermodynamic
 !                 fields that are in use.
 !  (in)      G - The ocean's grid structure.
   integer :: is, ie, js, je, nz, hs
   is = g%isc ; ie = g%iec ; js = g%jsc ; je = g%jec ; nz = g%ke
   hs=1; if (present(haloshift)) hs=haloshift
   if (associated(tv%T)) call hchksum(tv%T, mesg//" T",g%HI,haloshift=hs)
   if (associated(tv%S)) call hchksum(tv%S, mesg//" S",g%HI,haloshift=hs)
   if (associated(tv%frazil)) call hchksum(tv%frazil, mesg//" frazil",g%HI,haloshift=hs)
   if (associated(tv%salt_deficit)) call hchksum(tv%salt_deficit, mesg//" salt deficit",g%HI,haloshift=hs)