MOM6: mom_obsolete_params Module Reference
mom_obsolete_params Module Reference
Detailed Description
Methods for testing for, and list of, obsolete run-time parameters.
Functions/Subroutines
subroutine, public find_obsolete_params (param_file)
Scans input parameter file for list obsolete parameters.
subroutine, public obsolete_logical (param_file, varname, warning_val, hint)
Test for presence of obsolete LOGICAL in parameter file.
subroutine, public obsolete_char (param_file, varname, hint)
Test for presence of obsolete STRING in parameter file.
subroutine, public obsolete_real (param_file, varname, warning_val, hint)
Test for presence of obsolete REAL in parameter file.
subroutine, public obsolete_int (param_file, varname, warning_val, hint)
Test for presence of obsolete INTEGER in parameter file.
Function/Subroutine Documentation
find_obsolete_params()
subroutine, public mom_obsolete_params::find_obsolete_params (type(param_file_type), intent(in) param_file)
Scans input parameter file for list obsolete parameters.
Parameters
[in] param_file Structure containing parameter file data.
Definition at line 21 of file MOM_obsolete_params.F90.
References mom_error_handler::is_root_pe(), mom_error_handler::mom_error(), obsolete_char(), obsolete_int(), obsolete_logical(), and obsolete_real().
Referenced by mom::initialize_mom().
   type(param_file_type), intent(in) :: param_file !< Structure containing parameter file data.
   ! Local variables
   character(len=40)  :: mdl = "find_obsolete_params" ! This module's name.
 ! This include declares and sets the variable "version".
 #include "version_variable.h"
   integer :: test_int
   logical :: test_logic, test_logic2, test_logic3, split
   if (.not.is_root_pe()) return
   call obsolete_int(param_file, "NTSTEP", &
        hint="Instead use DT_THERM to set the thermodynamic time-step.")
   call obsolete_logical(param_file, "JACOBIAN_PGF", .false., &
        hint="Instead use ANALYTIC_FV_PGF.")
   call obsolete_logical(param_file, "SADOURNY", &
        hint="Instead use CORIOLIS_SCHEME='SADOURNY'.")
   call obsolete_logical(param_file, "ARITHMETIC_BT_THICK", &
        hint="Instead use BT_THICK_SCHEME='ARITHMETIC'.")
   call obsolete_logical(param_file, "HYBRID_BT_THICK", &
        hint="Instead use BT_THICK_SCHEME='HYBRID'.")
   call obsolete_logical(param_file, "BT_CONT_BT_THICK", &
        hint="Instead use BT_THICK_SCHEME='FROM_BT_CONT'.")
   call obsolete_logical(param_file, "APPLY_OBC_U", &
        hint="Instead use OBC_NUMBER_SEGMENTS>0 and use the new segments protocol.")
   call obsolete_logical(param_file, "APPLY_OBC_V", &
        hint="Instead use OBC_NUMBER_SEGMENTS>0 and use the new segments protocol.")
   call obsolete_logical(param_file, "APPLY_OBC_V_FLATHER_NORTH", &
        hint="Instead use OBC_NUMBER_SEGMENTS>0 and use the new segments protocol.")
   call obsolete_logical(param_file, "APPLY_OBC_V_FLATHER_SOUTH", &
        hint="Instead use OBC_NUMBER_SEGMENTS>0 and use the new segments protocol.")
   call obsolete_logical(param_file, "APPLY_OBC_U_FLATHER_EAST", &
        hint="Instead use OBC_NUMBER_SEGMENTS>0 and use the new segments protocol.")
   call obsolete_logical(param_file, "APPLY_OBC_U_FLATHER_WEST", &
        hint="Instead use OBC_NUMBER_SEGMENTS>0 and use the new segments protocol.")
   call obsolete_char(param_file, "OBC_CONFIG", &
        hint="Instead use OBC_USER_CONFIG and use the new segments protocol.")
   call obsolete_char(param_file, "READ_OBC_ETA", &
        hint="Instead use OBC_SEGMENT_XXX_DATA.")
   call obsolete_char(param_file, "READ_OBC_UV", &
        hint="Instead use OBC_SEGMENT_XXX_DATA.")
   call obsolete_char(param_file, "READ_OBC_TS", &
        hint="Instead use OBC_SEGMENT_XXX_DATA.")
   test_logic3 = .true. ; call read_param(param_file,"ENABLE_THERMODYNAMICS",test_logic3)
   test_logic = .true. ; call read_param(param_file,"TEMPERATURE",test_logic)
   test_logic2 = .false. ; call read_param(param_file,"TEMPERATURE",test_logic2)
   if (test_logic .eqv. test_logic2) then ; if (test_logic .eqv. test_logic3) then
     call mom_error(warning, "find_obsolete_params: "// &
          "TEMPERATURE is an obsolete run-time flag, but is set consistently with \n"//&
          "  ENABLE_THERMODYNAMICS.")
   else
     call mom_error(fatal, "find_obsolete_params: "// &
          "TEMPERATURE is an obsolete run-time flag.  Use ENABLE_THERMODYNAMICS instead.")
   endif ; endif
   test_logic = test_logic3 ; call read_param(param_file,"NONLINEAR_EOS",test_logic)
   if (test_logic .neqv. test_logic3) then
     call mom_error(warning, "find_obsolete_params: "// &
           "NONLINEAR_EOS is an obsolete option.  Instead define " // &
           "USE_EOS to use an equation of state to calculate density.")
   endif
 ! test_logic = .true. ; call read_param(param_file,"USE_RIVER_HEAT_CONTENT",test_logic)
 ! test_logic2 = .false. ; call read_param(param_file,"USE_RIVER_HEAT_CONTENT",test_logic2)
 ! if (test_logic .eqv. test_logic2) call MOM_ERROR(FATAL, "find_obsolete_params: "// &
 !        "USE_RIVER_HEAT_CONTENT, is an obsolete run-time flag.")
 ! test_logic = .true. ; call read_param(param_file,"USE_CALVING_HEAT_CONTENT",test_logic)
 ! test_logic2 = .false. ; call read_param(param_file,"USE_CALVING_HEAT_CONTENT",test_logic2)
 ! if (test_logic .eqv. test_logic2) call MOM_ERROR(FATAL, "find_obsolete_params: "// &
 !        "USE_CALVING_HEAT_CONTENT, is an obsolete run-time flag.")
   call obsolete_int(param_file, "NXTOT")
   call obsolete_int(param_file, "NYTOT")
   call obsolete_int(param_file, "NZ")
   call obsolete_int(param_file, "NXPROC")
   call obsolete_int(param_file, "NYPROC")
   call obsolete_int(param_file, "NXPROC_IO")
   call obsolete_int(param_file, "NYPROC_IO")
   call obsolete_int(param_file, "NXHALO")
   call obsolete_int(param_file, "NYHALO")
   call obsolete_int(param_file, "ML_PRESORT_NZ_CONV_ADJ")
   call obsolete_int(param_file, "NIPROC_IO", hint="Use IO_LAYOUT=#,# instead.")
   call obsolete_int(param_file, "NJPROC_IO", hint="Use IO_LAYOUT=#,# instead.")
   call obsolete_real(param_file, "BT_COR_SLOW_RATE", 0.0)
   call obsolete_real(param_file, "BT_COR_FRAC", 1.0)
   call obsolete_logical(param_file, "BT_INCLUDE_UDHDT", .false.)
   call obsolete_logical(param_file, "RIGA_SET_DIFFUSIVITY", .false.)
   call obsolete_logical(param_file, "RIGA_ITIDE_BUGS", .false.)
   call obsolete_logical(param_file, "RIGA_ENTRAINMENT_FOIBLES", .false.)
   call obsolete_logical(param_file, "RIGA_TRACER_DIFFUSE_BUGS", .false.)
   call obsolete_logical(param_file, "RIGA_KAPPA_SHEAR_BUGS1", .false.)
   call obsolete_logical(param_file, "RIGA_KAPPA_SHEAR_BUGS2", .false.)
   call obsolete_logical(param_file, "CONT_PPM_RIGA_BUGS", .false.)
   call obsolete_logical(param_file, "USE_REPRODUCING_SUM", .true.)
   call obsolete_logical(param_file, "SLOW_BITWISE_GLOBAL_FORCING_SUMS", .false.)
   call obsolete_logical(param_file, "ALWAYS_WRITE_GEOM")
   call obsolete_real(param_file, "I_ZETA")
   call obsolete_logical(param_file, "REF_COMPRESS_3D")
   call obsolete_char(param_file, "COMPRESS_FILE")
   call obsolete_char(param_file, "REF_COMPRESS_FILE_TEMP")
   call obsolete_char(param_file, "REF_COMPRESS_FILE_SALT")
   call obsolete_char(param_file, "REF_COMPRESS_FILE_DEPTH")
   call obsolete_char(param_file, "DIAG_REMAP_Z_GRID_DEF", "Use NUM_DIAG_COORDS, DIAG_COORDS and DIAG_COORD_DEF_Z")
   call obsolete_logical(param_file, "OLD_RESTRAT_PARAM", .false.)
   call obsolete_real(param_file, "ML_RESTRAT_COEF", 0.0)
   call obsolete_logical(param_file, "FULL_THICKNESSDIFFUSE", .true.)
   call obsolete_logical(param_file, "DIFFUSE_ISOPYCNALS", .true.)
   call obsolete_logical(param_file, "MOREL_PEN_SW")
   call obsolete_logical(param_file, "MANIZZA_PEN_SW")
   call obsolete_logical(param_file, "USE_H2000_SHEAR_MIXING", .false.)
   call obsolete_real(param_file, "SHEARMIX_LAT_EQ", 0.0)
   call obsolete_real(param_file, "RINO_CRIT_EQ")
   call obsolete_real(param_file, "SHEARMIX_RATE_EQ")
   call obsolete_logical(param_file, "CONTINUITY_PPM", .true.)
   call obsolete_logical(param_file, "USE_LOCAL_PREF", .true.)
   call obsolete_logical(param_file, "USE_LOCAL_PREF_CORRECT", .true.)
   test_logic = .false. ; call read_param(param_file, "USE_JACKSON_PARAM", test_logic)
   call obsolete_logical(param_file, "RINOMIX", test_logic)
   call obsolete_logical(param_file, "NORMALIZED_SUM_OUT", .true.)
   call obsolete_real(param_file, "RLAY_RANGE")
   call obsolete_real(param_file, "RLAY_REF")
   call obsolete_real(param_file, "HMIX")
   call obsolete_real(param_file, "VSTAR_SCALE_COEF")
   call obsolete_real(param_file, "ZSTAR_RIGID_SURFACE_THRESHOLD")
   test_int = -1 ; call read_param(param_file,"ML_RADIATION_CODING",test_int)
   if (test_int == 1) call mom_error(fatal, "find_obsolete_params: "// &
     "ML_RADIATION_CODING is an obsolete option and the code previously "//&
     "used by setting it to 1 has been eliminated.")
   if (test_int /= -1) call mom_error(warning, "find_obsolete_params: "// &
     "ML_RADIATION_CODING is an obsolete option.")
   ! Test for inconsistent parameter settings.
   split = .true. ; test_logic = .false.
   call read_param(param_file,"SPLIT",split)
   call read_param(param_file,"DYNAMIC_SURFACE_PRESSURE",test_logic)
   if (test_logic .and. .not.split) call mom_error(fatal, &
     "find_obsolete_params: #define DYNAMIC_SURFACE_PRESSURE is not yet "//&
     "implemented without #define SPLIT.")
   call read_param(param_file,"USE_LEGACY_SPLIT",test_logic)
   if (.not.(split .and. test_logic)) then
     call obsolete_logical(param_file, "FLUX_BT_COUPLING", .false.)
     call obsolete_logical(param_file, "READJUST_BT_TRANS", .false.)
     call obsolete_logical(param_file, "RESCALE_BE_FACE_AREAS", .false.)
     call obsolete_logical(param_file, "APPLY_BT_DRAG", .true.)
   endif
   call obsolete_int(param_file, "SEAMOUNT_LENGTH_SCALE", hint="Use SEAMOUNT_X_LENGTH_SCALE instead.")
   call obsolete_logical(param_file, "MSTAR_FIXED", hint="Instead use MSTAR_MODE.")
   ! Write the file version number to the model log.
   call log_version(param_file, mdl, version)
obsolete_char()
subroutine, public mom_obsolete_params::obsolete_char (type(param_file_type), intent(in) param_file, character(len=*), intent(in) varname, character(len=*), intent(in), optional hint)
Test for presence of obsolete STRING in parameter file.
Parameters
[in] param_file Structure containing parameter file data.
[in] varname Name of obsolete STRING parameter.
[in] hint A hint to the user about what to do.
Definition at line 242 of file MOM_obsolete_params.F90.
References mom_error_handler::mom_error().
Referenced by find_obsolete_params().
   type(param_file_type), intent(in) :: param_file !< Structure containing parameter file data.
   character(len=*),      intent(in) :: varname    !< Name of obsolete STRING parameter.
   character(len=*), optional, intent(in) :: hint  !< A hint to the user about what to do.
   ! Local variables
   character(len=200) :: test_string, hint_msg
   test_string = ''; call read_param(param_file, varname, test_string)
   hint_msg = " " ; if (present(hint)) hint_msg = hint
   if (len_trim(test_string) > 0) call mom_error(fatal,                 &
            "MOM_obsolete_params: "//trim(varname)//                    &
            " is an obsolete run-time flag, and should not be used. "// &
            trim(hint_msg))
obsolete_int()
subroutine, public mom_obsolete_params::obsolete_int (type(param_file_type), intent(in) param_file, character(len=*), intent(in) varname, integer, intent(in), optional warning_val, character(len=*), intent(in), optional hint)
Test for presence of obsolete INTEGER in parameter file.
Parameters
[in] param_file Structure containing parameter file data.
[in] varname Name of obsolete INTEGER parameter.
[in] warning_val An allowed value that causes a warning instead of an error.
[in] hint A hint to the user about what to do.
Definition at line 286 of file MOM_obsolete_params.F90.
References mom_error_handler::mom_error().
Referenced by find_obsolete_params().
   type(param_file_type), intent(in) :: param_file  !< Structure containing parameter file data.
   character(len=*),      intent(in) :: varname     !< Name of obsolete INTEGER parameter.
   integer,     optional, intent(in) :: warning_val !< An allowed value that causes a warning instead of an error.
   character(len=*), optional, intent(in) :: hint   !< A hint to the user about what to do.
   ! Local variables
   integer :: test_val, warn_val
   character(len=128) :: hint_msg
   test_val = -123456788; call read_param(param_file, varname, test_val)
   warn_val = -123456788; if (present(warning_val)) warn_val = warning_val
   hint_msg = " " ; if (present(hint)) hint_msg = hint
   if (test_val /= -123456788) then
     if (test_val == warn_val) then
       call mom_error(warning, "MOM_obsolete_params: "//trim(varname)// &
          " is an obsolete run-time flag. "//trim(hint_msg))
     else
       call mom_error(fatal, "MOM_obsolete_params: "//trim(varname)//   &
            " is an obsolete run-time flag, and should not be used. "// &
            trim(hint_msg))
     endif
   endif
obsolete_logical()
subroutine, public mom_obsolete_params::obsolete_logical (type(param_file_type), intent(in) param_file, character(len=*), intent(in) varname, logical, intent(in), optional warning_val, character(len=*), intent(in), optional hint)
Test for presence of obsolete LOGICAL in parameter file.
Parameters
[in] param_file Structure containing parameter file data.
[in] varname Name of obsolete LOGICAL parameter.
[in] warning_val An allowed value that causes a warning instead of an error.
[in] hint A hint to the user about what to do.
Definition at line 199 of file MOM_obsolete_params.F90.
References mom_error_handler::mom_error().
Referenced by find_obsolete_params().
   type(param_file_type), intent(in) :: param_file  !< Structure containing parameter file data.
   character(len=*),      intent(in) :: varname     !< Name of obsolete LOGICAL parameter.
   logical,     optional, intent(in) :: warning_val !< An allowed value that causes a warning instead of an error.
   character(len=*), optional, intent(in) :: hint   !< A hint to the user about what to do.
   ! Local variables
   logical :: test_logic, fatal_err
   character(len=128) :: hint_msg
   test_logic = .false. ; call read_param(param_file, varname,test_logic)
   fatal_err = .true.
   if (present(warning_val)) fatal_err = (warning_val .neqv. .true.)
   hint_msg = " " ; if (present(hint)) hint_msg = hint
   if (test_logic) then
     if (fatal_err) then
       call mom_error(fatal, "MOM_obsolete_params: "//trim(varname)//   &
            " is an obsolete run-time flag, and should not be used. "// &
            trim(hint_msg))
     else
       call mom_error(warning, "MOM_obsolete_params: "//trim(varname)// &
            " is an obsolete run-time flag. "//trim(hint_msg))
     endif
   endif
   test_logic = .true. ; call read_param(param_file, varname, test_logic)
   fatal_err = .true.
   if (present(warning_val)) fatal_err = (warning_val .neqv. .false.)
   if (.not.test_logic) then
     if (fatal_err) then
       call mom_error(fatal, "MOM_obsolete_params: "//trim(varname)//   &
            " is an obsolete run-time flag, and should not be used. "// &
            trim(hint_msg))
     else
       call mom_error(warning, "MOM_obsolete_params: "//trim(varname)// &
            " is an obsolete run-time flag. "//trim(hint_msg))
     endif
   endif
obsolete_real()
subroutine, public mom_obsolete_params::obsolete_real (type(param_file_type), intent(in) param_file, character(len=*), intent(in) varname, real, intent(in), optional warning_val, character(len=*), intent(in), optional hint)
Test for presence of obsolete REAL in parameter file.
Parameters
[in] param_file Structure containing parameter file data.
[in] varname Name of obsolete REAL parameter.
[in] warning_val An allowed value that causes a warning instead of an error.
[in] hint A hint to the user about what to do.
Definition at line 260 of file MOM_obsolete_params.F90.
References mom_error_handler::mom_error().
Referenced by find_obsolete_params().
   type(param_file_type), intent(in) :: param_file  !< Structure containing parameter file data.
   character(len=*),      intent(in) :: varname     !< Name of obsolete REAL parameter.
   real,        optional, intent(in) :: warning_val !< An allowed value that causes a warning instead of an error.
   character(len=*), optional, intent(in) :: hint   !< A hint to the user about what to do.
   ! Local variables
   real :: test_val, warn_val
   character(len=128) :: hint_msg
   test_val = -9e35; call read_param(param_file, varname, test_val)
   warn_val = -9e35; if (present(warning_val)) warn_val = warning_val
   hint_msg = " " ; if (present(hint)) hint_msg = hint
   if (test_val /= -9e35) then
     if (test_val == warn_val) then
       call mom_error(warning, "MOM_obsolete_params: "//trim(varname)// &
          " is an obsolete run-time flag. "//trim(hint_msg))
     else
       call mom_error(fatal, "MOM_obsolete_params: "//trim(varname)//   &
            " is an obsolete run-time flag, and should not be used. "// &
            trim(hint_msg))
     endif
   endif