MOM6: coord_zlike Module Reference
coord_zlike Module Reference
Detailed Description
Regrid columns for a z-like coordinate (z-star, z-level)
Data Types
type zlike_cs
Control structure containing required parameters for a z-like coordinate.
Functions/Subroutines
subroutine, public init_coord_zlike (CS, nk, coordinateResolution)
Initialise a zlike_CS with pointers to parameters.
subroutine, public end_coord_zlike (CS)
subroutine, public set_zlike_params (CS, min_thickness)
subroutine, public build_zstar_column (CS, nz, depth, total_thickness, zInterface, z_rigid_top, eta_orig)
Builds a z* coordinate with a minimum thickness.
Function/Subroutine Documentation
build_zstar_column()
subroutine, public coord_zlike::build_zstar_column (type(zlike_cs), intent(in) CS, integer, intent(in) nz, real, intent(in) depth, real, intent(in) total_thickness, real, dimension(nz+1), intent(inout) zInterface, real, intent(in), optional z_rigid_top, real, intent(in), optional eta_orig)
Builds a z* coordinate with a minimum thickness.
Parameters
[in] cs Coordinate control structure
[in] nz Number of levels
[in] depth Depth of ocean bottom (positive in m)
[in] total_thickness Column thickness (positive in m)
[in,out] zinterface Absolute positions of interfaces
[in] z_rigid_top The height of a rigid top (negative in m)
[in] eta_orig The actual original height of the top (m)
Definition at line 60 of file coord_zlike.F90.
Referenced by mom_regridding::build_zstar_grid(), and mom_diag_remap::diag_remap_update().
   type(zlike_cs),        intent(in)    :: cs !< Coordinate control structure
   integer,               intent(in)    :: nz !< Number of levels
   real,                  intent(in)    :: depth !< Depth of ocean bottom (positive in m)
   real,                  intent(in)    :: total_thickness !< Column thickness (positive in m)
   real, dimension(nz+1), intent(inout) :: zinterface !< Absolute positions of interfaces
   real, optional,        intent(in)    :: z_rigid_top !< The height of a rigid top (negative in m)
   real, optional,        intent(in)    :: eta_orig !< The actual original height of the top (m)
   ! Local variables
   real :: eta, stretching, dh, min_thickness, z0_top, z_star
   integer :: k
   logical :: new_zstar_def
   new_zstar_def = .false.
   min_thickness = min( cs%min_thickness, total_thickness/real(nz) )
   z0_top = 0.
   if (present(z_rigid_top)) then
     z0_top = z_rigid_top
     new_zstar_def = .true.
   endif
   ! Position of free-surface (or the rigid top, for which eta ~ z0_top)
   eta = total_thickness - depth
   if (present(eta_orig)) eta = eta_orig
   ! Conventional z* coordinate:
   !   z* = (z-eta) / stretching   where stretching = (H+eta)/H
   !   z = eta + stretching * z*
   ! The above gives z*(z=eta) = 0, z*(z=-H) = -H.
   ! With a rigid top boundary at eta = z0_top then
   !   z* = z0 + (z-eta) / stretching   where stretching = (H+eta)/(H+z0)
   !   z = eta + stretching * (z*-z0) * stretching
   stretching = total_thickness / ( depth + z0_top )
   if (new_zstar_def) then
     ! z_star is the notional z* coordinate in absence of upper/lower topography
     z_star = 0. ! z*=0 at the free-surface
     zinterface(1) = eta ! The actual position of the top of the column
     do k = 2,nz
       z_star = z_star - cs%coordinateResolution(k-1)
       ! This ensures that z is below a rigid upper surface (ice shelf bottom)
       zinterface(k) = min( eta + stretching * ( z_star - z0_top ), z0_top )
       ! This ensures that the layer in inflated
       zinterface(k) = min( zinterface(k), zinterface(k-1) - min_thickness )
       ! This ensures that z is above or at the topography
       zinterface(k) = max( zinterface(k), -depth + real(nz+1-k) * min_thickness )
     enddo
     zinterface(nz+1) = -depth
   else
     ! Integrate down from the top for a notional new grid, ignoring topography
     ! The starting position is offset by z0_top which, if z0_top<0, will place
     ! interfaces above the rigid boundary.
     zinterface(1) = eta
     do k = 1,nz
       dh = stretching * cs%coordinateResolution(k) ! Notional grid spacing
       zinterface(k+1) = zinterface(k) - dh
     enddo
     ! Integrating up from the bottom adjusting interface position to accommodate
     ! inflating layers without disturbing the interface above
     zinterface(nz+1) = -depth
     do k = nz,1,-1
       if ( zinterface(k) < (zinterface(k+1) + min_thickness) ) then
         zinterface(k) = zinterface(k+1) + min_thickness
       endif
     enddo
   endif
end_coord_zlike()
subroutine, public coord_zlike::end_coord_zlike (type(zlike_cs), pointer CS)
Definition at line 41 of file coord_zlike.F90.
Referenced by mom_regridding::end_regridding().
   type(zlike_cs), pointer :: cs
   ! nothing to do
   if (.not. associated(cs)) return
   deallocate(cs%coordinateResolution)
   deallocate(cs)
init_coord_zlike()
subroutine, public coord_zlike::init_coord_zlike (type(zlike_cs), pointer CS, integer, intent(in) nk, real, dimension(:), intent(in) coordinateResolution)
Initialise a zlike_CS with pointers to parameters.
Parameters
cs Unassociated pointer to hold the control structure
Definition at line 28 of file coord_zlike.F90.
References mom_error_handler::mom_error().
   type(zlike_cs),     pointer    :: cs !< Unassociated pointer to hold the control structure
   integer,            intent(in) :: nk
   real, dimension(:), intent(in) :: coordinateresolution
   if (associated(cs)) call mom_error(fatal, "init_coord_zlike: CS already associated!")
   allocate(cs)
   allocate(cs%coordinateResolution(nk))
   cs%nk                   = nk
   cs%coordinateResolution = coordinateresolution
set_zlike_params()
subroutine, public coord_zlike::set_zlike_params (type(zlike_cs), pointer CS, real, intent(in), optional min_thickness)
Definition at line 50 of file coord_zlike.F90.
References mom_error_handler::mom_error().
   type(zlike_cs), pointer    :: cs
   real, optional, intent(in) :: min_thickness
   if (.not. associated(cs)) call mom_error(fatal, "set_zlike_params: CS not associated")
   if (present(min_thickness)) cs%min_thickness = min_thickness