MOM6: mom_ice_shelf_initialize Module Reference
mom_ice_shelf_initialize Module Reference
Functions/Subroutines
subroutine, public initialize_ice_thickness (h_shelf, area_shelf_h, hmask, G, PF)
subroutine initialize_ice_thickness_from_file (h_shelf, area_shelf_h, hmask, G, PF)
subroutine initialize_ice_thickness_channel (h_shelf, area_shelf_h, hmask, G, PF)
Function/Subroutine Documentation
initialize_ice_thickness()
subroutine, public mom_ice_shelf_initialize::initialize_ice_thickness (real, dimension(:,:), intent(inout) h_shelf, real, dimension(:,:), intent(inout) area_shelf_h, real, dimension(:,:), intent(inout) hmask, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) PF)
Parameters
[in] g The ocean's grid structure
Definition at line 52 of file MOM_ice_shelf_initialize.F90.
References initialize_ice_thickness_channel(), initialize_ice_thickness_from_file(), mom_error_handler::mom_error(), and user_shelf_init::user_init_ice_thickness().
   real, intent(inout), dimension(:,:)          :: h_shelf, area_shelf_h, hmask
   type(ocean_grid_type), intent(in)            :: g    !< The ocean's grid structure
   type(param_file_type), intent(in)            :: pf
   character(len=40)  :: mdl = "initialize_ice_thickness" ! This subroutine's name.
   character(len=200) :: config
   call get_param(pf, mdl, "ICE_PROFILE_CONFIG", config, &
                  "This specifies how the initial ice profile is specified. \n"//&
                  "Valid values are: CHANNEL, FILE, and USER.", &
                  fail_if_missing=.true.)
   select case ( trim(config) )
   case ("CHANNEL"); call initialize_ice_thickness_channel (h_shelf, area_shelf_h, hmask, g, pf)
   case ("FILE");  call initialize_ice_thickness_from_file (h_shelf, area_shelf_h, hmask, g, pf)
   case ("USER");  call user_init_ice_thickness (h_shelf, area_shelf_h, hmask, g, pf)
   case default ;  call mom_error(fatal,"MOM_initialize: "// &
     "Unrecognized ice profile setup "//trim(config))
   end select
initialize_ice_thickness_channel()
subroutine mom_ice_shelf_initialize::initialize_ice_thickness_channel (real, dimension(:,:), intent(inout) h_shelf, real, dimension(:,:), intent(inout) area_shelf_h, real, dimension(:,:), intent(inout) hmask, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) PF) private
Parameters
[in] g The ocean's grid structure
Definition at line 158 of file MOM_ice_shelf_initialize.F90.
References mom_error_handler::mom_mesg().
Referenced by initialize_ice_thickness().
   real, intent(inout), dimension(:,:)          :: h_shelf, area_shelf_h, hmask
   type(ocean_grid_type), intent(in)            :: g    !< The ocean's grid structure
   type(param_file_type), intent(in)            :: pf
   character(len=40)  :: mdl = "initialize_ice_shelf_thickness_channel" ! This subroutine's name.
   real :: max_draft, min_draft, flat_shelf_width, c1, slope_pos
   real :: edge_pos, shelf_slope_scale, rho_ocean
   integer :: i, j, jsc, jec, jsd, jed, jedg, nyh, isc, iec, isd, ied
   integer :: j_off
   jsc = g%jsc ; jec = g%jec ; isc = g%isc ; iec = g%iec
   jsd = g%jsd ; jed = g%jed ; isd = g%isd ; ied = g%ied
   nyh = g%domain%njhalo ; jedg = g%domain%njglobal+nyh
   j_off = g%jdg_offset
   call mom_mesg(mdl//": setting thickness")
   call get_param(pf, mdl, "SHELF_MAX_DRAFT", max_draft, &
                  units="m", default=1.0)
   call get_param(pf, mdl, "SHELF_MIN_DRAFT", min_draft, &
                  units="m", default=1.0)
   call get_param(pf, mdl, "FLAT_SHELF_WIDTH", flat_shelf_width, &
                  units="axis_units", default=0.0)
   call get_param(pf, mdl, "SHELF_SLOPE_SCALE", shelf_slope_scale, &
                  units="axis_units", default=0.0)
   call get_param(pf, mdl, "SHELF_EDGE_POS_0", edge_pos, &
                  units="axis_units", default=0.0)
   slope_pos = edge_pos - flat_shelf_width
   c1 = 0.0 ; if (shelf_slope_scale > 0.0) c1 = 1.0 / shelf_slope_scale
   do j=g%jsd,g%jed
   if (((j+j_off) <= jedg) .AND. ((j+j_off) >= nyh+1)) then
     do i=g%isc,g%iec
       if ((j.ge.jsc) .and. (j.le.jec)) then
         if (g%geoLonCu(i-1,j) >= edge_pos) then
         ! Everything past the edge is open ocean.
 !            mass_shelf(i,j) = 0.0
           area_shelf_h(i,j) = 0.0
           hmask(i,j) = 0.0
           h_shelf(i,j) = 0.0
         else
           if (g%geoLonCu(i,j) > edge_pos) then
             area_shelf_h(i,j) = g%areaT(i,j) * (edge_pos - g%geoLonCu(i-1,j)) / &
                             (g%geoLonCu(i,j) - g%geoLonCu(i-1,j))
             hmask(i,j) = 2.0
           else
             area_shelf_h(i,j) = g%areaT(i,j)
             hmask(i,j) = 1.0
           endif
           if (g%geoLonT(i,j) > slope_pos) then
             h_shelf(i,j) = min_draft
 !              mass_shelf(i,j) = Rho_ocean * min_draft
           else
 !              mass_shelf(i,j) = Rho_ocean * (min_draft + &
 !                 (CS%max_draft - CS%min_draft) * &
 !                 min(1.0, (c1*(slope_pos - G%geoLonT(i,j)))**2) )
             h_shelf(i,j) = (min_draft + &
                (max_draft - min_draft) * &
                min(1.0, (c1*(slope_pos - g%geoLonT(i,j)))**2) )
           endif
         endif
       endif
       if ((i+g%idg_offset) .eq. g%domain%nihalo+1) then
         hmask(i-1,j) = 3.0
       endif
     enddo
   endif ; enddo
initialize_ice_thickness_from_file()
subroutine mom_ice_shelf_initialize::initialize_ice_thickness_from_file (real, dimension(:,:), intent(inout) h_shelf, real, dimension(:,:), intent(inout) area_shelf_h, real, dimension(:,:), intent(inout) hmask, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) PF) private
Parameters
[in] g The ocean's grid structure
Definition at line 77 of file MOM_ice_shelf_initialize.F90.
References mom_error_handler::mom_error(), and mom_error_handler::mom_mesg().
Referenced by initialize_ice_thickness().
   real, intent(inout), dimension(:,:)          :: h_shelf, area_shelf_h, hmask
   type(ocean_grid_type), intent(in)            :: g    !< The ocean's grid structure
   type(param_file_type), intent(in)            :: pf
   !  This subroutine reads ice thickness and area from a file and puts it into
   !  h_shelf and area_shelf_h in m (and dimensionless) and updates hmask
   character(len=200) :: filename,thickness_file,inputdir ! Strings for file/path
   character(len=200) :: thickness_varname, area_varname! Variable name in file
   character(len=40)  :: mdl = "initialize_ice_thickness_from_file" ! This subroutine's name.
   integer :: i, j, isc, jsc, iec, jec
   real :: len_sidestress, mask, udh
   call mom_mesg("  MOM_ice_shelf_init_profile.F90, initialize_thickness_from_file: reading thickness")
   call get_param(pf, mdl, "INPUTDIR", inputdir, default=".")
   inputdir = slasher(inputdir)
   call get_param(pf, mdl, "ICE_THICKNESS_FILE", thickness_file, &
                  "The file from which the bathymetry is read.", &
                  default="ice_shelf_h.nc")
   call get_param(pf, mdl, "LEN_SIDE_STRESS", len_sidestress, &
                  "position past which shelf sides are stress free.", &
                  default=0.0, units="axis_units")
   filename = trim(inputdir)//trim(thickness_file)
   call log_param(pf, mdl, "INPUTDIR/THICKNESS_FILE", filename)
   call get_param(pf, mdl, "ICE_THICKNESS_VARNAME", thickness_varname, &
                  "The name of the thickness variable in ICE_THICKNESS_FILE.", &
                  default="h_shelf")
   call get_param(pf, mdl, "ICE_AREA_VARNAME", area_varname, &
                  "The name of the area variable in ICE_THICKNESS_FILE.", &
                  default="area_shelf_h")
   if (.not.file_exists(filename, g%Domain)) call mom_error(fatal, &
        " initialize_topography_from_file: Unable to open "//trim(filename))
   call read_data(filename,trim(thickness_varname),h_shelf,domain=g%Domain%mpp_domain)
   call read_data(filename,trim(area_varname),area_shelf_h,domain=g%Domain%mpp_domain)
 !  call get_param(PF, mdl, "ICE_BOUNDARY_CONFIG", config, &
 !                 "This specifies how the ice domain boundary is specified", &
 !                 fail_if_missing=.true.)
   isc = g%isc ; jsc = g%jsc ; iec = g%iec ; jec = g%jec
   do j=jsc,jec
     do i=isc,iec
       ! taper ice shelf in area where there is no sidestress -
       ! but do not interfere with hmask
       if ((g%geoLonCv(i,j) .gt. len_sidestress).and. &
           (len_sidestress .gt. 0.)) then
         udh = exp(-(g%geoLonCv(i,j)-len_sidestress)/5.0) * h_shelf(i,j)
         if (udh .le. 25.0) then
           h_shelf(i,j) = 0.0
           area_shelf_h(i,j) = 0.0
         else
           h_shelf(i,j) = udh
         endif
       endif
       ! update thickness mask
       if (area_shelf_h(i,j) .ge. g%areaT(i,j)) then
         hmask(i,j) = 1.
       elseif (area_shelf_h(i,j) .eq. 0.0) then
         hmask(i,j) = 0.
       elseif ((area_shelf_h(i,j) .gt. 0) .and. (area_shelf_h(i,j) .le. g%areaT(i,j))) then
         hmask(i,j) = 2.
       else
         call mom_error(fatal,mdl// " AREA IN CELL OUT OF RANGE")
       endif
     enddo
   enddo