MOM6: mom_get_input Module Reference
mom_get_input Module Reference
Data Types
type directories
Functions/Subroutines
subroutine, public get_mom_input (param_file, dirs, check_params)
Function/Subroutine Documentation
get_mom_input()
subroutine, public mom_get_input::get_mom_input (type(param_file_type), intent(out), optional param_file, type(directories), intent(out), optional dirs, logical, intent(in), optional check_params)
Parameters
[out] param_file A structure to parse for run-time parameters
Definition at line 55 of file MOM_get_input.F90.
References mom_error_handler::mom_error(), and mom_file_parser::open_param_file().
Referenced by mom::initialize_mom(), and ocean_model_mod::ocean_model_flux_init().
   type(param_file_type), optional, intent(out) :: param_file !< A structure to parse for run-time parameters
   type(directories),     optional, intent(out) :: dirs
   logical,               optional, intent(in)  :: check_params
 !    See if the run is to be started from saved conditions, and get  !
 !  the names of the I/O directories and initialization file.  This   !
 !  subroutine also calls the subroutine that allows run-time changes !
 !  in parameters.                                                    !
   integer, parameter :: npf = 5 ! Maximum number of parameter files
   character(len=240) :: &
     parameter_filename(npf) = ' ', & ! List of files containing parameters.
     output_directory = ' ', &   ! Directory to use to write the model output.
     restart_input_dir = ' ', &  ! Directory for reading restart and input files.
     restart_output_dir = ' ', & ! Directory into which to write restart files.
     input_filename  = ' '       ! A string that indicates the input files or how
                                 ! the run segment should be started.
   character(len=240) :: output_dir
   integer :: unit, io, ierr, valid_param_files
   namelist /mom_input_nml/ output_directory, input_filename, parameter_filename, &
                            restart_input_dir, restart_output_dir
   if (file_exists('input.nml')) then
     unit = open_namelist_file(file='input.nml')
   else
     call mom_error(fatal,'Required namelist file input.nml does not exist.')
   endif
   ierr=1 ; do while (ierr /= 0)
     read(unit, nml=mom_input_nml, iostat=io, end=10)
     ierr = check_nml_error(io, 'MOM_input_nml')
   enddo
 10 call close_file(unit)
   if (present(dirs)) then
     dirs%output_directory = slasher(ensembler(output_directory))
     dirs%restart_output_dir = slasher(ensembler(restart_output_dir))
     dirs%restart_input_dir = slasher(ensembler(restart_input_dir))
     dirs%input_filename = ensembler(input_filename)
   endif
   if (present(param_file)) then
     output_dir = slasher(ensembler(output_directory))
     valid_param_files = 0
     do io = 1, npf
       if (len_trim(trim(parameter_filename(io))) > 0) then
         call open_param_file(ensembler(parameter_filename(io)), param_file, &
                              check_params, doc_file_dir=output_dir)
         valid_param_files = valid_param_files + 1
       endif
     enddo
     if (valid_param_files == 0) call mom_error(fatal, "There must be at "//&
          "least 1 valid entry in input_filename in MOM_input_nml in input.nml.")
   endif