MOM6: mom_offline_main Module Reference
mom_offline_main Module Reference
Detailed Description
The routines here implement the offline tracer algorithm used in MOM6. These are called from step_offline Some routines called here can be found in the MOM_offline_aux module.
Offline Tracer Transport in MOM6
'Offline tracer modeling' uses physical fields (e.g. mass transports and layer thicknesses) saved from a previous integration of the physical model to transport passive tracers. These fields are accumulated or averaged over a period of time (in this test case, 1 day) and used to integrate portions of the MOM6 code base that handle the 3d advection and diffusion of passive tracers.
The distribution of tracers in the ocean modeled offline should not be expected to match an online simulation. Accumulating transports over more than one online model timestep implicitly assumes homogeneity over that time period and essentially aliases over processes that occur with higher frequency. For example, consider the case of a surface boundary layer with a strong diurnal cycle. An offline simulation with a 1 day timestep, captures the net transport into or out of that layer, but not the exact cycling. This effective aliasing may also complicate online model configurations which strongly-eddying regions. In this case, the offline model timestep must be limited to some fraction of the eddy correlation timescale. Lastly, the nonlinear advection scheme which applies limited mass-transports over a sequence of iterations means that tracers are not transported along exactly the same path as they are in the online model.
This capability has currently targeted the Baltic_ALE_z test case, though some work has also been done with the OM4 1/2 degree configuration. Work is ongoing to develop recommendations and best practices for investigators seeking to use MOM6 for offline tracer modeling.
Implementation of offline routine in MOM6
The subroutine step_tracers that coordinates this can be found in MOM.F90 and is only called using the solo ocean driver. This is to avoid issues with coupling to other climate components that may be relying on fluxes from the ocean to be coupled more often than the offline time step. Other routines related to offline tracer modeling can be found in tracers/MOM_offline_control.F90
As can also be seen in the comments for the step_tracers subroutine, an offline time step comprises the following steps:
Using the layer thicknesses and tracer concentrations from the previous timestep, half of the accumulated vertical mixing (eatr and ebtr) is applied in the call to tracer_column_fns. For tracers whose source/sink terms need dt, this value is set to 1/2 dt_offline
Half of the accumulated surface freshwater fluxes are applied START ITERATION
Accumulated mass fluxes are used to do horizontal transport. The number of iterations used in advect_tracer is limited to 2 (e.g x->y->x->y). The remaining mass fluxes are stored for later use and resulting layer thicknesses fed into the next step
Tracers and the h-grid are regridded and remapped in a call to ALE. This allows for layers which might 'vanish' because of horizontal mass transport to be 'reinflated' and essentially allows for the vertical transport of tracers
Check that transport is done if the remaining mass fluxes equals 0 or if the max number of iterations has been reached END ITERATION
Repeat steps 1 and 2
Redistribute any residual mass fluxes that remain after the advection iterations in a barotropic manner, progressively upward through the water column.
Force a remapping to the stored layer thicknesses that correspond to the snapshot of the online model at the end of an accumulation interval
Reset T/S and h to their stored snapshotted values to prevent model drift
Evaluating the utility of an offline tracer model
How well an offline tracer model can be used as an alternative to integrating tracers online with the prognostic model must be evaluated for each application. This efficacy may be related to the native coordinate of the online model, to the length of the offline timestep, and to the behavior of the tracer itself.
A framework for formally regression testing the offline capability still needs to be developed. However, as a simple way of testing whether the offline model is nominally behaving as expected, the total inventory of the advection test tracers (tr1, tr2, etc.) should be conserved between time steps except for the last 4 decimal places. As a general guideline, an offline timestep of 5 days or less.
Runtime parameters for offline tracers
OFFLINEDIR: Input directory where the offline fields can be found
OFF_SUM_FILE: Filename where the accumulated fields can be found (e.g. horizontal mass transports)
OFF_SNAP_FILE: Filename where snapshot fields can be found (e.g. end of timestep layer thickness)
START_INDEX: Which timelevel of the input files to read first
NUMTIME: How many timelevels to read before 'looping' back to 1
FIELDS_ARE_OFFSET: True if the time-averaged fields and snapshot fields are offset by one time level, probably not needed -NUM_OFF_ITER: Maximum number of iterations to do for the nonlinear advection scheme -REDISTRIBUTE_METHOD: Redistributes any remaining horizontal fluxes throughout the rest of water column. Options are 'barotropic' which "evenly distributes flux throughout the entire water column,'upwards' which adds the maximum of the remaining flux in each layer above, and 'none' which does no redistribution"
Data Types
type offline_transport_cs
Functions/Subroutines
subroutine, public offline_advection_ale (fluxes, Time_start, time_interval, CS, id_clock_ale, h_pre, uhtr, vhtr, converged)
3D advection is done by doing flux-limited nonlinear horizontal advection interspersed with an ALE regridding/remapping step. The loop in this routine is exited if remaining residual transports are below a runtime-specified value or a maximum number of iterations is reached.
subroutine, public offline_redistribute_residual (CS, h_pre, uhtr, vhtr, converged)
In the case where the main advection routine did not converge, something needs to be done with the remaining transport. Two different ways are offered, 'barotropic' means that the residual is distributed equally throughout the water column. 'upwards' attempts to redistribute the transport in the layers above and will eventually work down the entire water column.
real function remaining_transport_sum (CS, uhtr, vhtr)
Sums any non-negligible remaining transport to check for advection convergence.
subroutine, public offline_diabatic_ale (fluxes, Time_start, Time_end, CS, h_pre, eatr, ebtr)
The vertical/diabatic driver for offline tracers. First the eatr/ebtr associated with the interpolated vertical diffusivities are calculated and then any tracer column functions are done which can include vertical diffuvities and source/sink terms.
subroutine, public offline_fw_fluxes_into_ocean (G, GV, CS, fluxes, h, in_flux_optional)
Apply positive freshwater fluxes (into the ocean) and update netMassOut with only the negative (out of the ocean) fluxes.
subroutine, public offline_fw_fluxes_out_ocean (G, GV, CS, fluxes, h, out_flux_optional)
Apply negative freshwater fluxes (out of the ocean)
subroutine, public offline_advection_layer (fluxes, Time_start, time_interval, CS, h_pre, eatr, ebtr, uhtr, vhtr)
When in layer mode, 3D horizontal advection using stored mass fluxes must be used. Horizontal advection is done via tracer_advect, whereas the vertical component is actually handled by vertdiff in tracer_column_fns.
subroutine, public update_offline_fields (CS, h, fluxes, do_ale)
Update fields used in this round of offline transport. First fields are updated from files or from arrays read during initialization. Then if in an ALE-dependent coordinate, regrid/remap fields.
subroutine, public register_diags_offline_transport (Time, diag, CS)
Initialize additional diagnostics required for offline tracer transport.
subroutine, public post_offline_convergence_diags (CS, h_off, h_end, uhtr, vhtr)
Posts diagnostics related to offline convergence diagnostics.
subroutine, public extract_offline_main (CS, uhtr, vhtr, eatr, ebtr, h_end, accumulated_time, dt_offline, dt_offline_vertical, skip_diffusion)
Extracts members of the offline main control structure. All arguments are optional except the control structure itself.
subroutine, public insert_offline_main (CS, ALE_CSp, diabatic_CSp, diag, OBC, tracer_adv_CSp, tracer_flow_CSp, tracer_Reg, tv, G, GV, x_before_y, debug)
Inserts (assigns values to) members of the offline main control structure. All arguments are optional except for the CS itself.
subroutine, public offline_transport_init (param_file, CS, diabatic_CSp, G, GV)
Initializes the control structure for offline transport and reads in some of the.
subroutine read_all_input (CS)
Coordinates the allocation and reading in all time levels of uh, vh, hend, temp, and salt from files. Used when read_all_ts_uvh.
subroutine, public offline_transport_end (CS)
Deallocates (if necessary) arrays within the offline control structure.
Function/Subroutine Documentation
extract_offline_main()
subroutine, public mom_offline_main::extract_offline_main (type(offline_transport_cs), intent(in), target CS, real, dimension(:,:,:), intent(out), optional, pointer uhtr, real, dimension(:,:,:), intent(out), optional, pointer vhtr, real, dimension(:,:,:), intent(out), optional, pointer eatr, real, dimension(:,:,:), intent(out), optional, pointer ebtr, real, dimension(:,:,:), intent(out), optional, pointer h_end, integer, intent(out), optional, pointer accumulated_time, integer, intent(out), optional dt_offline, integer, intent(out), optional dt_offline_vertical, logical, intent(out), optional skip_diffusion)
Extracts members of the offline main control structure. All arguments are optional except the control structure itself.
Parameters
[in] cs Offline control structure
Definition at line 1151 of file MOM_offline_main.F90.
   type(offline_transport_cs), target, intent(in   )  :: cs !< Offline control structure
   ! Returned optional arguments
   real, dimension(:,:,:), pointer, optional, intent(  out) :: uhtr
   real, dimension(:,:,:), pointer, optional, intent(  out) :: vhtr
   real, dimension(:,:,:), pointer, optional, intent(  out) :: eatr
   real, dimension(:,:,:), pointer, optional, intent(  out) :: ebtr
   real, dimension(:,:,:), pointer, optional, intent(  out) :: h_end
   integer,                pointer, optional, intent(  out) :: accumulated_time
   integer,                         optional, intent(  out) :: dt_offline
   integer,                         optional, intent(  out) :: dt_offline_vertical
   logical,                         optional, intent(  out) :: skip_diffusion
   ! Pointers to 3d members
   if (present(uhtr)) uhtr => cs%uhtr
   if (present(vhtr)) vhtr => cs%vhtr
   if (present(eatr)) eatr => cs%eatr
   if (present(ebtr)) ebtr => cs%ebtr
   if (present(h_end)) h_end => cs%h_end
   ! Pointers to integer members which need to be modified
   if (present(accumulated_time)) accumulated_time => cs%accumulated_time
   ! Return value of non-modified integers
   if (present(dt_offline))  dt_offline = cs%dt_offline
   if (present(dt_offline_vertical)) dt_offline_vertical = cs%dt_offline_vertical
   if (present(skip_diffusion)) skip_diffusion = cs%skip_diffusion
insert_offline_main()
subroutine, public mom_offline_main::insert_offline_main (type(offline_transport_cs), intent(inout) CS, type(ale_cs), intent(in), optional, target ALE_CSp, type(diabatic_cs), intent(in), optional, target diabatic_CSp, type(diag_ctrl), intent(in), optional, target diag, type(ocean_obc_type), intent(in), optional, target OBC, type(tracer_advect_cs), intent(in), optional, target tracer_adv_CSp, type(tracer_flow_control_cs), intent(in), optional, target tracer_flow_CSp, type(tracer_registry_type), intent(in), optional, target tracer_Reg, type(thermo_var_ptrs), intent(in), optional, target tv, type(ocean_grid_type), intent(in), optional, target G, type(verticalgrid_type), intent(in), optional, target GV, logical, intent(in), optional x_before_y, logical, intent(in), optional debug)
Inserts (assigns values to) members of the offline main control structure. All arguments are optional except for the CS itself.
Definition at line 1184 of file MOM_offline_main.F90.
   type(offline_transport_cs), intent(inout) :: cs
   ! Inserted optional arguments
   type(ale_cs),                 target, optional, intent(in   ) :: ale_csp
   type(diabatic_cs),            target, optional, intent(in   ) :: diabatic_csp
   type(diag_ctrl),              target, optional, intent(in   ) :: diag
   type(ocean_obc_type),         target, optional, intent(in   ) :: obc
   type(tracer_advect_cs),       target, optional, intent(in   ) :: tracer_adv_csp
   type(tracer_flow_control_cs), target, optional, intent(in   ) :: tracer_flow_csp
   type(tracer_registry_type),   target, optional, intent(in   ) :: tracer_reg
   type(thermo_var_ptrs),        target, optional, intent(in   ) :: tv
   type(ocean_grid_type),        target, optional, intent(in   ) :: g
   type(verticalgrid_type),      target, optional, intent(in   ) :: gv
   logical,                              optional, intent(in   ) :: x_before_y
   logical,                              optional, intent(in   ) :: debug
   if (present(ale_csp))         cs%ALE_CSp => ale_csp
   if (present(diabatic_csp))    cs%diabatic_CSp => diabatic_csp
   if (present(diag))            cs%diag => diag
   if (present(obc))             cs%OBC => obc
   if (present(tracer_adv_csp))  cs%tracer_adv_CSp => tracer_adv_csp
   if (present(tracer_flow_csp)) cs%tracer_flow_CSp => tracer_flow_csp
   if (present(tracer_reg))      cs%tracer_Reg => tracer_reg
   if (present(tv))              cs%tv => tv
   if (present(g))               cs%G => g
   if (present(gv))              cs%GV => gv
   if (present(x_before_y))      cs%x_before_y = x_before_y
   if (present(debug))           cs%debug = debug
offline_advection_ale()
subroutine, public mom_offline_main::offline_advection_ale (type(forcing), intent(inout) fluxes, type(time_type), intent(in) Time_start, real, intent(in) time_interval, type(offline_transport_cs), pointer CS, integer, intent(in) id_clock_ale, real, dimension(cs%g %isd: cs%g %ied, cs%g %jsd: cs%g %jed, cs%g %ke), intent(inout) h_pre, real, dimension(cs%g %isdb: cs%g %iedb, cs%g %jsd: cs%g %jed, cs%g %ke), intent(inout) uhtr, real, dimension(cs%g %isd: cs%g %ied, cs%g %jsdb: cs%g %jedb, cs%g %ke), intent(inout) vhtr, logical, intent(out) converged)
3D advection is done by doing flux-limited nonlinear horizontal advection interspersed with an ALE regridding/remapping step. The loop in this routine is exited if remaining residual transports are below a runtime-specified value or a maximum number of iterations is reached.
Parameters
[in,out] fluxes pointers to forcing fields
[in] time_start starting time of a segment, as a time type
[in] time_interval time interval
cs control structure for offline module
[in] id_clock_ale Clock for ALE routines
[in,out] h_pre layer thicknesses before advection
[in,out] uhtr Zonal mass transport
[in,out] vhtr Meridional mass transport
Definition at line 181 of file MOM_offline_main.F90.
References mom_tracer_advect::advect_tracer(), mom_ale::ale_main_offline(), mom_tracer_registry::mom_tracer_chkinv(), and remaining_transport_sum().
   type(forcing),    intent(inout)      :: fluxes        !< pointers to forcing fields
   type(time_type),  intent(in)         :: time_start    !< starting time of a segment, as a time type
   real,             intent(in)         :: time_interval !< time interval
   type(offline_transport_cs), pointer  :: cs            !< control structure for offline module
   integer,          intent(in)         :: id_clock_ale  !< Clock for ALE routines
   real, dimension(SZI_(CS%G),SZJ_(CS%G),SZK_(CS%G)),  intent(inout)  :: h_pre !< layer thicknesses before advection
   real, dimension(SZIB_(CS%G),SZJ_(CS%G),SZK_(CS%G)), intent(inout)  :: uhtr  !< Zonal mass transport
   real, dimension(SZI_(CS%G),SZJB_(CS%G),SZK_(CS%G)), intent(inout)  :: vhtr  !< Meridional mass transport
   logical,                                            intent(  out)  :: converged
   ! Local pointers
   type(ocean_grid_type),      pointer :: g  => null() ! Pointer to a structure containing
                                                       ! metrics and related information
   type(verticalgrid_type),    pointer :: gv => null() ! Pointer to structure containing information
                                                       ! about the vertical grid
   ! Work arrays for mass transports
   real, dimension(SZIB_(CS%G),SZJ_(CS%G),SZK_(CS%G))   :: uhtr_sub
   ! Meridional mass transports
   real, dimension(SZI_(CS%G),SZJB_(CS%G),SZK_(CS%G))   :: vhtr_sub
   real :: prev_tot_residual, tot_residual  ! Used to keep track of how close to convergence we are
   ! Variables used to keep track of layer thicknesses at various points in the code
   real, dimension(SZI_(CS%G),SZJ_(CS%G),SZK_(CS%G)) :: &
       h_new, &
       h_vol
   ! Fields for eta_diff diagnostic
   real, dimension(SZI_(CS%G),SZJ_(CS%G))         :: eta_pre, eta_end
   integer                                        :: niter, iter
   real                                           :: inum_iter
   integer :: i, j, k, m, is, ie, js, je, isd, ied, jsd, jed, nz
   integer :: isv, iev, jsv, jev ! The valid range of the indices.
   integer :: isdb, iedb, jsdb, jedb
   logical :: z_first, x_before_y
   real :: evap_cfl_limit, minimum_forcing_depth, dt_iter, dt_offline
   integer :: nstocks
   real :: stock_values(max_fields_)
   character*20 :: debug_msg
   call cpu_clock_begin(cs%id_clock_offline_adv)
   ! Grid-related pointer assignments
   g => cs%G
   gv => cs%GV
   x_before_y = cs%x_before_y
   ! Initialize some shorthand variables from other structures
   is  = g%isc ; ie  = g%iec ; js  = g%jsc ; je  = g%jec ; nz = gv%ke
   isd = g%isd ; ied = g%ied ; jsd = g%jsd ; jed = g%jed
   isdb = g%IsdB ; iedb = g%IedB ; jsdb = g%JsdB ; jedb = g%JedB
   dt_offline = cs%dt_offline
   evap_cfl_limit = cs%evap_CFL_limit
   minimum_forcing_depth = cs%minimum_forcing_depth
   niter = cs%num_off_iter
   inum_iter = 1./real(niter)
   dt_iter = dt_offline*inum_iter
   ! Initialize working arrays
   h_new(:,:,:) = 0.0
   h_vol(:,:,:) = 0.0
   uhtr_sub(:,:,:) = 0.0
   vhtr_sub(:,:,:) = 0.0
   ! converged should only be true if there are no remaining mass fluxes
   converged = .false.
   ! Tracers are transported using the stored mass fluxes. Where possible, operators are Strang-split around
   ! the call to
   ! 1)  Using the layer thicknesses and tracer concentrations from the previous timestep,
   !     half of the accumulated vertical mixing (eatr and ebtr) is applied in the call to tracer_column_fns.
   !     For tracers whose source/sink terms need dt, this value is set to 1/2 dt_offline
   ! 2)  Half of the accumulated surface freshwater fluxes are applied
   !! START ITERATION
   ! 3)  Accumulated mass fluxes are used to do horizontal transport. The number of iterations used in
   !     advect_tracer is limited to 2 (e.g x->y->x->y). The remaining mass fluxes are stored for later use
   !     and resulting layer thicknesses fed into the next step
   ! 4)  Tracers and the h-grid are regridded and remapped in a call to ALE. This allows for layers which might
   !     'vanish' because of horizontal mass transport to be 'reinflated'
   ! 5)  Check that transport is done if the remaining mass fluxes equals 0 or if the max number of iterations
   !     has been reached
   !! END ITERATION
   ! 6)  Repeat steps 1 and 2
   ! 7)  Force a remapping to the stored layer thicknesses that correspond to the snapshot of the online model
   ! 8)  Reset T/S and h to their stored snapshotted values to prevent model drift
   ! Copy over the horizontal mass fluxes from the total mass fluxes
   do k=1,nz ; do j=jsd,jed ; do i=isdb,iedb
     uhtr_sub(i,j,k) = uhtr(i,j,k)
   enddo ; enddo ; enddo
   do k=1,nz ; do j=jsdb,jedb ; do i=isd,ied
     vhtr_sub(i,j,k) = vhtr(i,j,k)
   enddo ; enddo ; enddo
   do k=1,nz ; do j=js,je ; do i=is,ie
     h_new(i,j,k) = h_pre(i,j,k)
   enddo ; enddo ; enddo
   if (cs%debug) then
     call hchksum(h_pre,"h_pre before transport",g%HI)
     call uvchksum("[uv]htr_sub before transport", uhtr_sub, vhtr_sub, g%HI)
   endif
   tot_residual = remaining_transport_sum(cs, uhtr, vhtr)
   if (cs%print_adv_offline) then
     if (is_root_pe()) then
       write(*,'(A,ES24.16)') "Main advection starting transport: ", tot_residual
     endif
   endif
   ! This loop does essentially a flux-limited, nonlinear advection scheme until all mass fluxes
   ! are used. ALE is done after the horizontal advection.
   do iter=1,cs%num_off_iter
     do k=1,nz ; do j=js,je ; do i=is,ie
       h_vol(i,j,k) = h_new(i,j,k)*g%areaT(i,j)
       h_pre(i,j,k) = h_new(i,j,k)
     enddo ; enddo ; enddo
     if(cs%debug) then
       call hchksum(h_vol,"h_vol before advect",g%HI)
       call uvchksum("[uv]htr_sub before advect", uhtr_sub, vhtr_sub, g%HI)
       write(debug_msg, '(A,I4.4)') 'Before advect ', iter
       call mom_tracer_chkinv(debug_msg, g, h_pre, cs%tracer_reg%Tr, cs%tracer_reg%ntr)
     endif
     call advect_tracer(h_pre, uhtr_sub, vhtr_sub, cs%OBC, cs%dt_offline, g, gv, &
         cs%tracer_adv_CSp, cs%tracer_Reg, h_vol, max_iter_in=1, &
         uhr_out=uhtr, vhr_out=vhtr, h_out=h_new, x_first_in=x_before_y)
     ! Switch the direction every iteration
     x_before_y = .not. x_before_y
     ! Update the new layer thicknesses after one round of advection has happened
     do k=1,nz ; do j=js,je ; do i=is,ie
       h_new(i,j,k) = h_new(i,j,k)/g%areaT(i,j)
     enddo ; enddo ; enddo
     if (modulo(iter,cs%off_ale_mod)==0) then
       ! Do ALE remapping/regridding to allow for more advection to occur in the next iteration
       call pass_var(h_new,g%Domain)
       if (cs%debug) then
         call hchksum(h_new,"h_new before ALE",g%HI)
         write(debug_msg, '(A,I4.4)') 'Before ALE ', iter
         call mom_tracer_chkinv(debug_msg, g, h_new, cs%tracer_reg%Tr, cs%tracer_reg%ntr)
       endif
       call cpu_clock_begin(id_clock_ale)
       call ale_main_offline(g, gv, h_new, cs%tv, cs%tracer_Reg, cs%ALE_CSp, cs%dt_offline)
       call cpu_clock_end(id_clock_ale)
       if (cs%debug) then
         call hchksum(h_new,"h_new after ALE",g%HI)
         write(debug_msg, '(A,I4.4)') 'After ALE ', iter
         call mom_tracer_chkinv(debug_msg, g, h_new, cs%tracer_reg%Tr, cs%tracer_reg%ntr)
       endif
     endif
     do k=1,nz; do j=js,je ; do i=is,ie
       uhtr_sub(i,j,k) = uhtr(i,j,k)
       vhtr_sub(i,j,k) = vhtr(i,j,k)
     enddo ; enddo ; enddo
     call pass_var(h_new, g%Domain)
     call pass_vector(uhtr_sub,vhtr_sub,g%Domain)
     ! Check for whether we've used up all the advection, or if we need to move on because
     ! advection has stalled
     tot_residual = remaining_transport_sum(cs, uhtr, vhtr)
     if (cs%print_adv_offline) then
       if (is_root_pe()) then
         write(*,'(A,ES24.16)') "Main advection remaining transport: ", tot_residual
       endif
     endif
     ! If all the mass transports have been used u, then quit
     if (tot_residual == 0.0) then
       if (is_root_pe()) write(0,*) "Converged after iteration", iter
       converged = .true.
       exit
     endif
     ! If advection has stalled or the remaining residual is less than a specified amount, quit
     if ( (tot_residual == prev_tot_residual) .or. (tot_residual<cs%min_residual) ) then
       converged = .false.
       exit
     endif
     prev_tot_residual = tot_residual
   enddo
   ! Make sure that uhtr and vhtr halos are updated
   h_pre(:,:,:) = h_new(:,:,:)
   call pass_vector(uhtr,vhtr,g%Domain)
   if (cs%debug) then
     call hchksum(h_pre,"h after offline_advection_ale",g%HI)
     call uvchksum("[uv]htr after offline_advection_ale", uhtr, vhtr, g%HI)
     call mom_tracer_chkinv("After offline_advection_ale", g, h_pre, cs%tracer_reg%Tr, cs%tracer_reg%ntr)
   endif
   call cpu_clock_end(cs%id_clock_offline_adv)
offline_advection_layer()
subroutine, public mom_offline_main::offline_advection_layer (type(forcing), intent(inout) fluxes, type(time_type), intent(in) Time_start, real, intent(in) time_interval, type(offline_transport_cs), pointer CS, real, dimension(szi_(cs%g),szj_(cs%g),szk_(cs%g)), intent(inout) h_pre, real, dimension(szi_(cs%g),szj_(cs%g),szk_(cs%g)), intent(inout) eatr, real, dimension(szi_(cs%g),szj_(cs%g),szk_(cs%g)), intent(inout) ebtr, real, dimension(szib_(cs%g),szj_(cs%g),szk_(cs%g)), intent(inout) uhtr, real, dimension(szi_(cs%g),szjb_(cs%g),szk_(cs%g)), intent(inout) vhtr)
When in layer mode, 3D horizontal advection using stored mass fluxes must be used. Horizontal advection is done via tracer_advect, whereas the vertical component is actually handled by vertdiff in tracer_column_fns.
Parameters
[in,out] fluxes pointers to forcing fields
[in] time_start starting time of a segment, as a time type
[in] time_interval Offline transport time interval
cs control structure from initialize_MOM
[in,out] h_pre layer thicknesses before advection
[in,out] eatr Entrainment from layer above
[in,out] ebtr Entrainment from layer below
[in,out] uhtr Zonal mass transport
[in,out] vhtr Meridional mass transport
Definition at line 800 of file MOM_offline_main.F90.
Referenced by mom::step_offline().
   type(forcing),              intent(inout)    :: fluxes        !< pointers to forcing fields
   type(time_type),            intent(in)       :: time_start    !< starting time of a segment, as a time type
   real,                       intent(in)       :: time_interval !< Offline transport time interval
   type(offline_transport_cs), pointer  :: cs                    !< control structure from initialize_MOM
   real, dimension(SZI_(CS%G),SZJ_(CS%G),SZK_(CS%G)),  intent(inout) :: h_pre !< layer thicknesses before advection
   real, dimension(SZI_(CS%G),SZJ_(CS%G),SZK_(CS%G)),  intent(inout) :: eatr !< Entrainment from layer above
   real, dimension(SZI_(CS%G),SZJ_(CS%G),SZK_(CS%G)),  intent(inout) :: ebtr !< Entrainment from layer below
   real, dimension(SZIB_(CS%G),SZJ_(CS%G),SZK_(CS%G)), intent(inout) :: uhtr  !< Zonal mass transport
   real, dimension(SZI_(CS%G),SZJB_(CS%G),SZK_(CS%G)), intent(inout) :: vhtr  !< Meridional mass transport
   ! Local pointers
   type(ocean_grid_type),      pointer :: g  => null() ! Pointer to a structure containing
                                                       ! metrics and related information
   type(verticalgrid_type),    pointer :: gv => null() ! Pointer to structure containing information
                                                       ! about the vertical grid
   ! Remaining zonal mass transports
   real, dimension(SZIB_(CS%G),SZJ_(CS%G),SZK_(CS%G))   :: uhtr_sub
   ! Remaining meridional mass transports
   real, dimension(SZI_(CS%G),SZJB_(CS%G),SZK_(CS%G))   :: vhtr_sub
   real :: sum_abs_fluxes, sum_u, sum_v  ! Used to keep track of how close to convergence we are
   real :: dt_offline
   ! Local variables
   ! Vertical diffusion related variables
   real, dimension(SZI_(CS%G),SZJ_(CS%G),SZK_(CS%G)) :: &
       eatr_sub, &
       ebtr_sub
   ! Variables used to keep track of layer thicknesses at various points in the code
   real, dimension(SZI_(CS%G),SZJ_(CS%G),SZK_(CS%G)) :: &
       h_new, &
       h_vol
   ! Work arrays for temperature and salinity
   real, dimension(SZI_(CS%G),SZJ_(CS%G),SZK_(CS%G)) :: &
       temp_old, salt_old, &
       temp_mean, salt_mean, &
       zero_3dh     !
   integer                                        :: niter, iter
   real                                           :: inum_iter, dt_iter
   logical                                        :: converged
   integer :: i, j, k, m, is, ie, js, je, isd, ied, jsd, jed, nz
   integer :: isv, iev, jsv, jev ! The valid range of the indices.
   integer :: isdb, iedb, jsdb, jedb
   logical :: z_first, x_before_y
   is  = g%isc ; ie  = g%iec ; js  = g%jsc ; je  = g%jec ; nz = gv%ke
   isd = g%isd ; ied = g%ied ; jsd = g%jsd ; jed = g%jed
   isdb = g%IsdB ; iedb = g%IedB ; jsdb = g%JsdB ; jedb = g%JedB
   do iter=1,cs%num_off_iter
     do k = 1, nz ; do j=js-1,je+1 ; do i=is-1,ie+1
       eatr_sub(i,j,k) = eatr(i,j,k)
       ebtr_sub(i,j,k) = ebtr(i,j,k)
     enddo; enddo ; enddo
     do k = 1, nz ; do j=js-1,je+1 ; do i=is-2,ie+1
       uhtr_sub(i,j,k) = uhtr(i,j,k)
     enddo; enddo ; enddo
     do k = 1, nz ; do j=js-2,je+1 ; do i=is-1,ie+1
       vhtr_sub(i,j,k) = vhtr(i,j,k)
     enddo; enddo ; enddo
     ! Calculate 3d mass transports to be used in this iteration
     call limit_mass_flux_3d(g, gv, uhtr_sub, vhtr_sub, eatr_sub, ebtr_sub, h_pre)
     if (z_first) then
       ! First do vertical advection
       call update_h_vertical_flux(g, gv, eatr_sub, ebtr_sub, h_pre, h_new)
       call call_tracer_column_fns(h_pre, h_new, eatr_sub, ebtr_sub, &
           fluxes, cs%mld, dt_iter, g, gv, cs%tv, cs%optics, cs%tracer_flow_CSp, cs%debug)
       ! We are now done with the vertical mass transports, so now h_new is h_sub
       do k = 1, nz ; do j=js-1,je+1 ; do i=is-1,ie+1
         h_pre(i,j,k) = h_new(i,j,k)
       enddo ; enddo ; enddo
       call pass_var(h_pre,g%Domain)
       ! Second zonal and meridional advection
       call update_h_horizontal_flux(g, gv, uhtr_sub, vhtr_sub, h_pre, h_new)
       do k = 1, nz ; do i = is-1, ie+1 ; do j=js-1, je+1
         h_vol(i,j,k) = h_pre(i,j,k)*g%areaT(i,j)
       enddo; enddo; enddo
       call advect_tracer(h_pre, uhtr_sub, vhtr_sub, cs%OBC, dt_iter, g, gv, &
           cs%tracer_adv_CSp, cs%tracer_Reg, h_vol, max_iter_in=30, x_first_in=x_before_y)
       ! Done with horizontal so now h_pre should be h_new
       do k = 1, nz ; do i=is-1,ie+1 ; do j=js-1,je+1
           h_pre(i,j,k) = h_new(i,j,k)
       enddo ; enddo ; enddo
     endif
     if (.not. z_first) then
       ! First zonal and meridional advection
       call update_h_horizontal_flux(g, gv, uhtr_sub, vhtr_sub, h_pre, h_new)
       do k = 1, nz ; do i = is-1, ie+1 ; do j=js-1, je+1
         h_vol(i,j,k) = h_pre(i,j,k)*g%areaT(i,j)
       enddo; enddo; enddo
       call advect_tracer(h_pre, uhtr_sub, vhtr_sub, cs%OBC, dt_iter, g, gv, &
           cs%tracer_adv_CSp, cs%tracer_Reg, h_vol, max_iter_in=30, x_first_in=x_before_y)
       ! Done with horizontal so now h_pre should be h_new
       do k = 1, nz ; do i=is-1,ie+1 ; do j=js-1,je+1
           h_pre(i,j,k) = h_new(i,j,k)
       enddo ; enddo ; enddo
       ! Second vertical advection
       call update_h_vertical_flux(g, gv, eatr_sub, ebtr_sub, h_pre, h_new)
       call call_tracer_column_fns(h_pre, h_new, eatr_sub, ebtr_sub, &
           fluxes, cs%mld, dt_iter, g, gv, cs%tv, cs%optics, cs%tracer_flow_CSp, cs%debug)
       ! We are now done with the vertical mass transports, so now h_new is h_sub
       do k = 1, nz ; do i=is-1,ie+1 ; do j=js-1,je+1
         h_pre(i,j,k) = h_new(i,j,k)
       enddo ; enddo ; enddo
     endif
     ! Update remaining transports
     do k = 1, nz ; do j=js-1,je+1 ; do i=is-1,ie+1
       eatr(i,j,k) = eatr(i,j,k) - eatr_sub(i,j,k)
       ebtr(i,j,k) = ebtr(i,j,k) - ebtr_sub(i,j,k)
     enddo; enddo ; enddo
     do k = 1, nz ; do j=js-1,je+1 ; do i=is-2,ie+1
       uhtr(i,j,k) = uhtr(i,j,k) - uhtr_sub(i,j,k)
     enddo; enddo ; enddo
     do k = 1, nz ; do j=js-2,je+1 ; do i=is-1,ie+1
       vhtr(i,j,k) = vhtr(i,j,k) - vhtr_sub(i,j,k)
     enddo; enddo ; enddo
     call pass_var(eatr,g%Domain)
     call pass_var(ebtr,g%Domain)
     call pass_var(h_pre,g%Domain)
     call pass_vector(uhtr,vhtr,g%Domain)
   !
     ! Calculate how close we are to converging by summing the remaining fluxes at each point
     sum_abs_fluxes = 0.0
     sum_u = 0.0
     sum_v = 0.0
     do k=1,nz; do j=js,je; do i=is,ie
       sum_u = sum_u + abs(uhtr(i-1,j,k))+abs(uhtr(i,j,k))
       sum_v = sum_v + abs(vhtr(i,j-1,k))+abs(vhtr(i,j,k))
       sum_abs_fluxes = sum_abs_fluxes + abs(eatr(i,j,k)) + abs(ebtr(i,j,k)) + abs(uhtr(i-1,j,k)) + &
           abs(uhtr(i,j,k)) + abs(vhtr(i,j-1,k)) + abs(vhtr(i,j,k))
     enddo; enddo; enddo
     call sum_across_pes(sum_abs_fluxes)
     print *, "Remaining u-flux, v-flux:", sum_u, sum_v
     if (sum_abs_fluxes==0) then
       print *, 'Converged after iteration', iter
       exit
     endif
     ! Switch order of Strang split every iteration
     z_first = .not. z_first
     x_before_y = .not. x_before_y
   end do
offline_diabatic_ale()
subroutine, public mom_offline_main::offline_diabatic_ale (type(forcing), intent(inout) fluxes, type(time_type), intent(in) Time_start, type(time_type), intent(in) Time_end, type(offline_transport_cs), pointer CS, real, dimension(szi_(cs%g),szj_(cs%g),szk_(cs%g)), intent(inout) h_pre, real, dimension(szi_(cs%g),szj_(cs%g),szk_(cs%g)), intent(inout) eatr, real, dimension(szi_(cs%g),szj_(cs%g),szk_(cs%g)), intent(inout) ebtr)
The vertical/diabatic driver for offline tracers. First the eatr/ebtr associated with the interpolated vertical diffusivities are calculated and then any tracer column functions are done which can include vertical diffuvities and source/sink terms.
Parameters
[in,out] fluxes pointers to forcing fields
[in] time_start starting time of a segment, as a time type
[in] time_end time interval
cs control structure from initialize_MOM
[in,out] eatr Entrainment from layer above
[in,out] ebtr Entrainment from layer below
Definition at line 617 of file MOM_offline_main.F90.
   type(forcing),    intent(inout)      :: fluxes        !< pointers to forcing fields
   type(time_type),  intent(in)         :: time_start    !< starting time of a segment, as a time type
   type(time_type),  intent(in)         :: time_end      !< time interval
   type(offline_transport_cs), pointer  :: cs            !< control structure from initialize_MOM
   real, dimension(SZI_(CS%G),SZJ_(CS%G),SZK_(CS%G)), intent(inout) :: h_pre
   real, dimension(SZI_(CS%G),SZJ_(CS%G),SZK_(CS%G)), intent(inout) :: eatr !< Entrainment from layer above
   real, dimension(SZI_(CS%G),SZJ_(CS%G),SZK_(CS%G)), intent(inout) :: ebtr !< Entrainment from layer below
   real, dimension(SZI_(CS%G),SZJ_(CS%G))    :: sw, sw_vis, sw_nir !< Save old value of shortwave radiation
   real :: hval
   integer :: i,j,k
   integer :: is, ie, js, je, nz
   integer :: k_nonzero
   real :: stock_values(max_fields_)
   real :: kd_bot
   integer :: nstocks
   nz = cs%GV%ke
   is = cs%G%isc ; ie = cs%G%iec ; js = cs%G%jsc ; je = cs%G%jec
   call cpu_clock_begin(cs%id_clock_offline_diabatic)
   if (is_root_pe()) write (0,*) "Applying tracer source, sinks, and vertical mixing"
   if (cs%debug) then
     call hchksum(h_pre,"h_pre before offline_diabatic_ale",cs%G%HI)
     call hchksum(eatr,"eatr before offline_diabatic_ale",cs%G%HI)
     call hchksum(ebtr,"ebtr before offline_diabatic_ale",cs%G%HI)
     call mom_tracer_chkinv("Before offline_diabatic_ale", cs%G, h_pre, cs%tracer_reg%Tr, cs%tracer_reg%ntr)
   endif
   eatr(:,:,:) = 0.
   ebtr(:,:,:) = 0.
   ! Calculate eatr and ebtr if vertical diffusivity is read
   ! Because the saved remapped diagnostics from the online run assume a zero minimum thickness
   ! but ALE may have a minimum thickness. Flood the diffusivities for all layers with the value
   ! of Kd closest to the bottom which is non-zero
   do j=js,je ; do i=is,ie
     k_nonzero = nz+1
     ! Find the nonzero bottom Kd
     do k=nz+1,1,-1
       if (cs%Kd(i,j,k)>0.) then
         kd_bot = cs%Kd(i,j,k)
         k_nonzero = k
         exit
       endif
     enddo
     ! Flood the bottom interfaces
     do k=k_nonzero,nz+1
       cs%Kd(i,j,k) = kd_bot
     enddo
   enddo ; enddo
   do j=js,je ; do i=is,ie
     eatr(i,j,1) = 0.
   enddo ; enddo
   do k=2,nz ; do j=js,je ; do i=is,ie
     hval=1.0/(cs%GV%H_subroundoff + 0.5*(h_pre(i,j,k-1) + h_pre(i,j,k)))
     eatr(i,j,k) = (cs%GV%m_to_H**2) * cs%dt_offline_vertical * hval * cs%Kd(i,j,k)
     ebtr(i,j,k-1) = eatr(i,j,k)
   enddo ; enddo ; enddo
   do j=js,je ; do i=is,ie
     ebtr(i,j,nz) = 0.
   enddo ; enddo
   ! Add diurnal cycle for shortwave radiation (only used if run in ocean-only mode)
   if (cs%diurnal_SW .and. cs%read_sw) then
     sw(:,:) = fluxes%sw
     sw_vis(:,:) = fluxes%sw_vis_dir
     sw_nir(:,:) = fluxes%sw_nir_dir
     call offline_add_diurnal_sw(fluxes, cs%G, time_start, time_end)
   endif
   if (associated(cs%optics)) &
     call set_opacity(cs%optics, fluxes, cs%G, cs%GV, cs%opacity_CSp)
   ! Note that tracerBoundaryFluxesInOut within this subroutine should NOT be called
   ! as the freshwater fluxes have already been accounted for
   call call_tracer_column_fns(h_pre, h_pre, eatr, ebtr, fluxes, cs%MLD, cs%dt_offline_vertical, cs%G, cs%GV, &
                               cs%tv, cs%optics, cs%tracer_flow_CSp, cs%debug)
   if (cs%diurnal_SW .and. cs%read_sw) then
     fluxes%sw(:,:) = sw
     fluxes%sw_vis_dir(:,:) = sw_vis
     fluxes%sw_nir_dir(:,:) = sw_nir
   endif
   if (cs%debug) then
     call hchksum(h_pre,"h_pre after offline_diabatic_ale",cs%G%HI)
     call hchksum(eatr,"eatr after offline_diabatic_ale",cs%G%HI)
     call hchksum(ebtr,"ebtr after offline_diabatic_ale",cs%G%HI)
     call mom_tracer_chkinv("After offline_diabatic_ale", cs%G, h_pre, cs%tracer_reg%Tr, cs%tracer_reg%ntr)
   endif
   call cpu_clock_end(cs%id_clock_offline_diabatic)
offline_fw_fluxes_into_ocean()
subroutine, public mom_offline_main::offline_fw_fluxes_into_ocean (type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, type(offline_transport_cs), intent(inout) CS, type(forcing), intent(inout) fluxes, real, dimension(szi_(g),szj_(g),szk_(g)), intent(inout) h, real, dimension(szi_(g),szj_(g)), intent(in), optional in_flux_optional)
Apply positive freshwater fluxes (into the ocean) and update netMassOut with only the negative (out of the ocean) fluxes.
Parameters
[in,out] cs Offline control structure
[in] g Grid structure
[in] gv ocean vertical grid structure
[in,out] fluxes Surface fluxes container
[in,out] h Layer thickness in H units
[in] in_flux_optional The total time-integrated amount of tracer that leaves with freshwater
Definition at line 718 of file MOM_offline_main.F90.
   type(offline_transport_cs),                 intent(inout) :: cs !< Offline control structure
   type(ocean_grid_type),                      intent(in)    :: g  !< Grid structure
   type(verticalgrid_type),                    intent(in)    :: gv !< ocean vertical grid structure
   type(forcing),                              intent(inout) :: fluxes !< Surface fluxes container
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)),   intent(inout) :: h  !< Layer thickness in H units
   !> The total time-integrated amount of tracer that leaves with freshwater
   real, dimension(SZI_(G),SZJ_(G)), optional, intent(in)    :: in_flux_optional
   integer :: i, j, m
   real, dimension(SZI_(G),SZJ_(G)) :: negative_fw !< store all negative fluxes
   logical :: update_h !< Flag for whether h should be updated
   if ( present(in_flux_optional) ) &
     call mom_error(warning, "Positive freshwater fluxes with non-zero tracer concentration not supported yet")
   ! Set all fluxes to 0
   negative_fw(:,:) = 0.
   ! Sort fluxes into positive and negative
   do j=g%jsc,g%jec ; do i=g%isc,g%iec
     if (fluxes%netMassOut(i,j)<0.0) then
       negative_fw(i,j) = fluxes%netMassOut(i,j)
       fluxes%netMassOut(i,j) = 0.
     endif
   enddo ; enddo
   if (cs%debug) then
     call hchksum(h,"h before fluxes into ocean",g%HI)
     call mom_tracer_chkinv("Before fluxes into ocean", g, h, cs%tracer_reg%Tr, cs%tracer_reg%ntr)
   endif
   do m = 1,cs%tracer_reg%ntr
     ! Layer thicknesses should only be updated after the last tracer is finished
     update_h = ( m == cs%tracer_reg%ntr )
     call applytracerboundaryfluxesinout(g, gv, cs%tracer_reg%tr(m)%t, cs%dt_offline, fluxes, h, &
                                         cs%evap_CFL_limit, cs%minimum_forcing_depth, update_h_opt = update_h)
   enddo
   if (cs%debug) then
     call hchksum(h,"h after fluxes into ocean",g%HI)
     call mom_tracer_chkinv("After fluxes into ocean", g, h, cs%tracer_reg%Tr, cs%tracer_reg%ntr)
   endif
   ! Now that fluxes into the ocean are done, save the negative fluxes for later
   fluxes%netMassOut(:,:) = negative_fw(:,:)
offline_fw_fluxes_out_ocean()
subroutine, public mom_offline_main::offline_fw_fluxes_out_ocean (type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, type(offline_transport_cs), intent(inout) CS, type(forcing), intent(inout) fluxes, real, dimension(szi_(g),szj_(g),szk_(g)), intent(inout) h, real, dimension(szi_(g),szj_(g)), intent(in), optional out_flux_optional)
Apply negative freshwater fluxes (out of the ocean)
Parameters
[in,out] cs Offline control structure
[in] g Grid structure
[in] gv ocean vertical grid structure
[in,out] fluxes Surface fluxes container
[in,out] h Layer thickness in H units
[in] out_flux_optional The total time-integrated amount of tracer that leaves with freshwater
Definition at line 766 of file MOM_offline_main.F90.
   type(offline_transport_cs),                 intent(inout) :: cs !< Offline control structure
   type(ocean_grid_type),                      intent(in)    :: g  !< Grid structure
   type(verticalgrid_type),                    intent(in)    :: gv !< ocean vertical grid structure
   type(forcing),                              intent(inout) :: fluxes !< Surface fluxes container
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)),   intent(inout) :: h  !< Layer thickness in H units
   !> The total time-integrated amount of tracer that leaves with freshwater
   real, dimension(SZI_(G),SZJ_(G)), optional, intent(in)    :: out_flux_optional
   integer :: m
   logical :: update_h !< Flag for whether h should be updated
   if ( present(out_flux_optional) ) &
     call mom_error(warning, "Negative freshwater fluxes with non-zero tracer concentration not supported yet")
   if (cs%debug) then
     call hchksum(h,"h before fluxes out of ocean",g%HI)
     call mom_tracer_chkinv("Before fluxes out of ocean", g, h, cs%tracer_reg%Tr, cs%tracer_reg%ntr)
   endif
   do m = 1, cs%tracer_reg%ntr
     ! Layer thicknesses should only be updated after the last tracer is finished
     update_h = ( m == cs%tracer_reg%ntr )
     call applytracerboundaryfluxesinout(g, gv, cs%tracer_reg%tr(m)%t, cs%dt_offline, fluxes, h, &
                                         cs%evap_CFL_limit, cs%minimum_forcing_depth, update_h_opt = update_h)
   enddo
   if (cs%debug) then
     call hchksum(h,"h after fluxes out of ocean",g%HI)
     call mom_tracer_chkinv("Before fluxes out of ocean", g, h, cs%tracer_reg%Tr, cs%tracer_reg%ntr)
   endif
offline_redistribute_residual()
subroutine, public mom_offline_main::offline_redistribute_residual (type(offline_transport_cs), pointer CS, real, dimension(szi_(cs%g),szj_(cs%g),szk_(cs%g)), intent(inout) h_pre, real, dimension(szib_(cs%g),szj_(cs%g),szk_(cs%g)), intent(inout) uhtr, real, dimension(szi_(cs%g),szjb_(cs%g),szk_(cs%g)), intent(inout) vhtr, logical, intent(in) converged)
In the case where the main advection routine did not converge, something needs to be done with the remaining transport. Two different ways are offered, 'barotropic' means that the residual is distributed equally throughout the water column. 'upwards' attempts to redistribute the transport in the layers above and will eventually work down the entire water column.
Parameters
cs control structure from initialize_MOM
[in,out] h_pre layer thicknesses before advection
[in,out] uhtr Zonal mass transport
[in,out] vhtr Meridional mass transport
Definition at line 388 of file MOM_offline_main.F90.
References mom_tracer_advect::advect_tracer(), mom_offline_aux::distribute_residual_uh_upwards(), mom_offline_aux::distribute_residual_vh_upwards(), mom_tracer_registry::mom_tracer_chkinv(), mom_tracer_registry::mom_tracer_chksum(), and remaining_transport_sum().
   type(offline_transport_cs), pointer  :: cs           !< control structure from initialize_MOM
   real, dimension(SZI_(CS%G),SZJ_(CS%G),SZK_(CS%G)),  intent(inout)  :: h_pre !< layer thicknesses before advection
   real, dimension(SZIB_(CS%G),SZJ_(CS%G),SZK_(CS%G)), intent(inout)  :: uhtr  !< Zonal mass transport
   real, dimension(SZI_(CS%G),SZJB_(CS%G),SZK_(CS%G)), intent(inout)  :: vhtr  !< Meridional mass transport
   logical,                                            intent(in   )  :: converged
   type(ocean_grid_type),      pointer :: g  => null() ! Pointer to a structure containing
                                                       ! metrics and related information
   type(verticalgrid_type),    pointer :: gv => null() ! Pointer to structure containing information
                                                       ! about the vertical grid
   logical :: x_before_y
   ! Variables used to keep track of layer thicknesses at various points in the code
   real, dimension(SZI_(CS%G),SZJ_(CS%G),SZK_(CS%G)) :: &
       h_new, &
       h_vol
   ! Used to calculate the eta diagnostics
   real, dimension(SZI_(CS%G),SZJ_(CS%G)) :: eta_work
   real, dimension(SZIB_(CS%G),SZJ_(CS%G),SZK_(CS%G)) :: uhr  !< Zonal mass transport
   real, dimension(SZI_(CS%G),SZJB_(CS%G),SZK_(CS%G)) :: vhr  !< Meridional mass transport
   integer :: i, j, k, m, is, ie, js, je, isd, ied, jsd, jed, nz, iter
   real :: prev_tot_residual, tot_residual, stock_values(max_fields_)
   integer :: nstocks
   ! Assign grid pointers
   g  => cs%G
   gv => cs%GV
   is  = g%isc ; ie  = g%iec ; js  = g%jsc ; je  = g%jec ; nz = gv%ke
   isd = g%isd ; ied = g%ied ; jsd = g%jsd ; jed = g%jed
   x_before_y = cs%x_before_y
   if (cs%id_eta_pre_distribute>0) then
     eta_work(:,:) = 0.0
     do k=1,nz ; do j=js,je ; do i=is,ie
       if (h_pre(i,j,k)>gv%Angstrom) then
         eta_work(i,j) = eta_work(i,j) + h_pre(i,j,k)
       endif
     enddo ; enddo ; enddo
     call post_data(cs%id_eta_pre_distribute,eta_work,cs%diag)
   endif
   ! These are used to find out how much will be redistributed in this routine
   if (cs%id_h_redist>0) call post_data(cs%id_h_redist, h_pre, cs%diag)
   if (cs%id_uhr_redist>0) call post_data(cs%id_uhr_redist, uhtr, cs%diag)
   if (cs%id_vhr_redist>0) call post_data(cs%id_vhr_redist, vhtr, cs%diag)
   if (converged) return
   if (cs%debug) then
     call mom_tracer_chkinv("Before redistribute ", g, h_pre, cs%tracer_reg%Tr, cs%tracer_reg%ntr)
   endif
   call cpu_clock_begin(cs%id_clock_redistribute)
   if (cs%redistribute_upwards .or. cs%redistribute_barotropic) then
     do iter = 1, cs%num_off_iter
       ! Perform upwards redistribution
       if (cs%redistribute_upwards) then
         ! Calculate the layer volumes at beginning of redistribute
         do k=1,nz ; do j=js,je ; do i=is,ie
           h_vol(i,j,k) = h_pre(i,j,k)*g%areaT(i,j)
         enddo ; enddo ; enddo
         call pass_var(h_vol,g%Domain)
         call pass_vector(uhtr,vhtr,g%Domain)
         ! Store volumes for advect_tracer
         h_pre(:,:,:) = h_vol(:,:,:)
         if (cs%debug) then
           call mom_tracer_chksum("Before upwards redistribute ", cs%tracer_Reg%Tr, cs%tracer_Reg%ntr, g)
           call uvchksum("[uv]tr before upwards redistribute", uhtr, vhtr, g%HI)
         endif
         if (x_before_y) then
           call distribute_residual_uh_upwards(g, gv, h_vol, uhtr)
           call distribute_residual_vh_upwards(g, gv, h_vol, vhtr)
         else
           call distribute_residual_vh_upwards(g, gv, h_vol, vhtr)
           call distribute_residual_uh_upwards(g, gv, h_vol, uhtr)
         endif
         call advect_tracer(h_pre, uhtr, vhtr, cs%OBC, cs%dt_offline, g, gv, &
             cs%tracer_adv_CSp, cs%tracer_Reg, h_prev_opt = h_pre, max_iter_in=1, &
             h_out=h_new, uhr_out=uhr, vhr_out=vhr, x_first_in=x_before_y)
         if (cs%debug) then
           call mom_tracer_chksum("After upwards redistribute ", cs%tracer_Reg%Tr, cs%tracer_Reg%ntr, g)
         endif
         ! Convert h_new back to layer thickness for ALE remapping
         do k=1,nz ; do j=js,je ; do i=is,ie
           uhtr(i,j,k) = uhr(i,j,k)
           vhtr(i,j,k) = vhr(i,j,k)
           h_vol(i,j,k) = h_new(i,j,k)
           h_new(i,j,k) = h_new(i,j,k)/g%areaT(i,j)
           h_pre(i,j,k) = h_new(i,j,k)
         enddo ; enddo ; enddo
       endif ! redistribute upwards
       ! Perform barotropic redistribution
       if (cs%redistribute_barotropic) then
         ! Calculate the layer volumes at beginning of redistribute
         do k=1,nz ; do j=js,je ; do i=is,ie
           h_vol(i,j,k) = h_pre(i,j,k)*g%areaT(i,j)
         enddo ; enddo ; enddo
         call pass_var(h_vol,g%Domain)
         call pass_vector(uhtr,vhtr,g%Domain)
         ! Copy h_vol to h_pre for advect_tracer routine
         h_pre(:,:,:) = h_vol(:,:,:)
         if (cs%debug) then
           call mom_tracer_chksum("Before barotropic redistribute ", cs%tracer_Reg%Tr, cs%tracer_Reg%ntr, g)
           call uvchksum("[uv]tr before upwards redistribute", uhtr, vhtr, g%HI)
         endif
         if (x_before_y) then
           call distribute_residual_uh_barotropic(g, gv, h_vol, uhtr)
           call distribute_residual_vh_barotropic(g, gv, h_vol, vhtr)
         else
           call distribute_residual_vh_barotropic(g, gv, h_vol, vhtr)
           call distribute_residual_uh_barotropic(g, gv, h_vol, uhtr)
         endif
         call advect_tracer(h_pre, uhtr, vhtr, cs%OBC, cs%dt_offline, g, gv, &
             cs%tracer_adv_CSp, cs%tracer_Reg, h_prev_opt = h_pre, max_iter_in=1, &
             h_out=h_new, uhr_out=uhr, vhr_out=vhr, x_first_in=x_before_y)
         if (cs%debug) then
           call mom_tracer_chksum("After barotropic redistribute ", cs%tracer_Reg%Tr, cs%tracer_Reg%ntr, g)
         endif
         ! Convert h_new back to layer thickness for ALE remapping
         do k=1,nz ; do j=js,je ; do i=is,ie
           uhtr(i,j,k) = uhr(i,j,k)
           vhtr(i,j,k) = vhr(i,j,k)
           h_vol(i,j,k) = h_new(i,j,k)
           h_new(i,j,k) = h_new(i,j,k)/g%areaT(i,j)
           h_pre(i,j,k) = h_new(i,j,k)
         enddo ; enddo ; enddo
       endif ! redistribute barotropic
       ! Check to see if all transport has been exhausted
       tot_residual = remaining_transport_sum(cs, uhtr, vhtr)
       if (cs%print_adv_offline) then
         if (is_root_pe()) then
           write(*,'(A,ES24.16)') "Residual advection remaining transport: ", tot_residual
         endif
       endif
       ! If the remaining residual is 0, then this return is done
       if (tot_residual==0.0 ) then
         exit
       endif
       if ( (tot_residual == prev_tot_residual) .or. (tot_residual<cs%min_residual) ) exit
       prev_tot_residual = tot_residual
     enddo ! Redistribution iteration
   endif ! If one of the redistribution routines is requested
   if (cs%id_eta_post_distribute>0) then
     eta_work(:,:) = 0.0
     do k=1,nz ; do j=js,je ; do i=is,ie
       if (h_pre(i,j,k)>gv%Angstrom) then
         eta_work(i,j) = eta_work(i,j) + h_pre(i,j,k)
       endif
     enddo ; enddo ; enddo
     call post_data(cs%id_eta_post_distribute,eta_work,cs%diag)
   endif
   if (cs%id_uhr>0) call post_data(cs%id_uhr,uhtr,cs%diag)
   if (cs%id_vhr>0) call post_data(cs%id_vhr,vhtr,cs%diag)
   if (cs%debug) then
     call hchksum(h_pre,"h_pre after redistribute",g%HI)
     call uvchksum("uhtr after redistribute", uhtr, vhtr, g%HI)
     call mom_tracer_chkinv("after redistribute ", g, h_new, cs%tracer_Reg%Tr, cs%tracer_Reg%ntr)
   endif
   call cpu_clock_end(cs%id_clock_redistribute)
offline_transport_end()
subroutine, public mom_offline_main::offline_transport_end (type(offline_transport_cs), intent(inout), pointer CS)
Deallocates (if necessary) arrays within the offline control structure.
Definition at line 1430 of file MOM_offline_main.F90.
   type(offline_transport_cs), pointer, intent(inout)  :: cs
   ! Explicitly allocate all allocatable arrays
   deallocate(cs%uhtr)
   deallocate(cs%vhtr)
   deallocate(cs%eatr)
   deallocate(cs%ebtr)
   deallocate(cs%h_end)
   deallocate(cs%netMassOut)
   deallocate(cs%netMassIn)
   deallocate(cs%Kd)
   if (cs%read_mld) deallocate(cs%mld)
   if (cs%read_all_ts_uvh) then
     deallocate(cs%uhtr_all)
     deallocate(cs%vhtr_all)
     deallocate(cs%hend_all)
     deallocate(cs%temp_all)
     deallocate(cs%salt_all)
   endif
   deallocate(cs)
offline_transport_init()
subroutine, public mom_offline_main::offline_transport_init (type(param_file_type), intent(in) param_file, type(offline_transport_cs), intent(inout), pointer CS, type(diabatic_cs), intent(in), pointer diabatic_CSp, type(ocean_grid_type), intent(in), pointer G, type(verticalgrid_type), intent(in), pointer GV)
Initializes the control structure for offline transport and reads in some of the.
Definition at line 1218 of file MOM_offline_main.F90.
References read_all_input().
   type(param_file_type),               intent(in)     :: param_file
   type(offline_transport_cs), pointer, intent(inout)  :: cs
   type(diabatic_cs),          pointer, intent(in)     :: diabatic_csp
   type(ocean_grid_type),      pointer, intent(in)     :: g
   type(verticalgrid_type),    pointer, intent(in)     :: gv
   character(len=40)  :: mdl = "offline_transport"
   character(len=20)  :: redistribute_method
   integer :: i, j, k, is, ie, js, je, isd, ied, jsd, jed, nz
   integer :: isdb, iedb, jsdb, jedb
   is   = g%isc   ; ie   = g%iec  ; js   = g%jsc  ; je   = g%jec ; nz = gv%ke
   isd  = g%isd   ; ied  = g%ied  ; jsd  = g%jsd  ; jed  = g%jed
   isdb = g%IsdB  ; iedb = g%IedB ; jsdb = g%JsdB ; jedb = g%JedB
   call calltree_enter("offline_transport_init, MOM_offline_control.F90")
   if (associated(cs)) then
     call mom_error(warning, "offline_transport_init called with an associated "// &
       "control structure.")
     return
   endif
   allocate(cs)
   call log_version(param_file, mdl,version, "This module allows for tracers to be run offline")
   ! Parse MOM_input for offline control
   call get_param(param_file, mdl, "OFFLINEDIR", cs%offlinedir, &
     "Input directory where the offline fields can be found",  fail_if_missing = .true.)
   call get_param(param_file, mdl, "OFF_SUM_FILE", cs%sum_file, &
     "Filename where the accumulated fields can be found",     fail_if_missing = .true.)
   call get_param(param_file, mdl, "OFF_SNAP_FILE", cs%snap_file, &
     "Filename where snapshot fields can be found",            fail_if_missing = .true.)
   call get_param(param_file, mdl, "OFF_MEAN_FILE", cs%mean_file, &
     "Filename where averaged fields can be found",            fail_if_missing = .true.)
   call get_param(param_file, mdl, "OFF_SURF_FILE", cs%surf_file, &
     "Filename where averaged fields can be found",            fail_if_missing = .true.)
   call get_param(param_file, mdl, "NUMTIME", cs%numtime, &
     "Number of timelevels in offline input files",            fail_if_missing = .true.)
   call get_param(param_file, mdl, "NK_INPUT", cs%nk_input, &
     "Number of vertical levels in offline input files", default = nz)
   call get_param(param_file, mdl, "DT_OFFLINE", cs%dt_offline, &
     "Length of time between reading in of input fields",      fail_if_missing = .true.)
   call get_param(param_file, mdl, "DT_OFFLINE_VERTICAL", cs%dt_offline_vertical, &
     "Length of the offline timestep for tracer column sources/sinks\n" //&
     "This should be set to the length of the coupling timestep for \n" //&
     "tracers which need shortwave fluxes",                    fail_if_missing = .true.)
   call get_param(param_file, mdl, "START_INDEX", cs%start_index, &
     "Which time index to start from", default=1)
   call get_param(param_file, mdl, "FIELDS_ARE_OFFSET", cs%fields_are_offset, &
     "True if the time-averaged fields and snapshot fields\n"//&
     "are offset by one time level", default=.false.)
   call get_param(param_file, mdl, "REDISTRIBUTE_METHOD", redistribute_method, &
     "Redistributes any remaining horizontal fluxes throughout\n"    //&
     "the rest of water column. Options are 'barotropic' which\n"    //&
     "evenly distributes flux throughout the entire water column,\n" //&
     "'upwards' which adds the maximum of the remaining flux in\n"   //&
     "each layer above, both which first applies upwards and then\n" //&
     "barotropic, and 'none' which does no redistribution", &
     default='barotropic')
   call get_param(param_file, mdl, "NUM_OFF_ITER", cs%num_off_iter, &
     "Number of iterations to subdivide the offline tracer advection and diffusion", &
     default = 60)
   call get_param(param_file, mdl, "OFF_ALE_MOD", cs%off_ale_mod, &
     "Sets how many horizontal advection steps are taken before an ALE\n" //&
     "remapping step is done. 1 would be x->y->ALE, 2 would be"           //&
     "x->y->x->y->ALE", default = 1)
   call get_param(param_file, mdl, "PRINT_ADV_OFFLINE", cs%print_adv_offline, &
     "Print diagnostic output every advection subiteration",default=.false.)
   call get_param(param_file, mdl, "SKIP_DIFFUSION_OFFLINE", cs%skip_diffusion, &
     "Do not do horizontal diffusion",default=.false.)
   call get_param(param_file, mdl, "READ_SW", cs%read_sw, &
     "Read in shortwave radiation field instead of using values from the coupler"//&
     "when in offline tracer mode",default=.false.)
   call get_param(param_file, mdl, "READ_MLD", cs%read_mld, &
     "Read in mixed layer depths for tracers which exchange with the atmosphere"//&
     "when in offline tracer mode",default=.false.)
   call get_param(param_file, mdl, "MLD_VAR_NAME", cs%mld_var_name, &
     "Name of the variable containing the depth of active mixing",&
     default='ePBL_h_ML')
   call get_param(param_file, mdl, "OFFLINE_ADD_DIURNAL_SW", cs%diurnal_sw, &
     "Adds a synthetic diurnal cycle in the same way that the ice\n" // &
     "model would have when time-averaged fields of shortwave\n"    // &
     "radiation are read in", default=.false.)
   call get_param(param_file, mdl, "KD_MAX", cs%Kd_max, &
     "The maximum permitted increment for the diapycnal \n"//&
     "diffusivity from TKE-based parameterizations, or a \n"//&
     "negative value for no limit.", units="m2 s-1", default=-1.0)
   call get_param(param_file, mdl, "MIN_RESIDUAL_TRANSPORT", cs%min_residual, &
     "How much remaining transport before the main offline advection\n"// &
     "is exited. The default value corresponds to about 1 meter of\n"  // &
     "difference in a grid cell", default = 1.e9)
   call get_param(param_file, mdl, "READ_ALL_TS_UVH", cs%read_all_ts_uvh,  &
     "Reads all time levels of a subset of the fields necessary to run \n"    //      &
     "the model offline. This can require a large amount of memory\n"//      &
     "and will make initialization very slow. However, for offline\n"//      &
     "runs spanning more than a year this can reduce total I/O overhead",    &
     default = .false.)
   ! Concatenate offline directory and file names
   cs%snap_file = trim(cs%offlinedir)//trim(cs%snap_file)
   cs%mean_file = trim(cs%offlinedir)//trim(cs%mean_file)
   cs%sum_file = trim(cs%offlinedir)//trim(cs%sum_file)
   cs%surf_file = trim(cs%offlinedir)//trim(cs%surf_file)
   cs%num_vert_iter = cs%dt_offline/cs%dt_offline_vertical
   ! Map redistribute_method onto logicals in CS
   select case (redistribute_method)
     case ('barotropic')
       cs%redistribute_barotropic = .true.
       cs%redistribute_upwards    = .false.
     case ('upwards')
       cs%redistribute_barotropic = .false.
       cs%redistribute_upwards    = .true.
     case ('both')
       cs%redistribute_barotropic = .true.
       cs%redistribute_upwards    = .true.
     case ('none')
       cs%redistribute_barotropic = .false.
       cs%redistribute_upwards    = .false.
   end select
   ! Set the accumulated time to zero
   cs%accumulated_time = 0
   ! Set the starting read index for time-averaged and snapshotted fields
   cs%ridx_sum = cs%start_index
   if (cs%fields_are_offset) cs%ridx_snap = next_modulo_time(cs%start_index,cs%numtime)
   if (.not. cs%fields_are_offset) cs%ridx_snap = cs%start_index
   ! Copy members from other modules
   call extract_diabatic_member(diabatic_csp, opacity_csp=cs%opacity_CSp, optics_csp=cs%optics,&
                                evap_cfl_limit=cs%evap_CFL_limit, &
                                minimum_forcing_depth=cs%minimum_forcing_depth)
   ! Grid pointer assignments
   cs%G  => g
   cs%GV => gv
   ! Allocate arrays
   allocate(cs%uhtr(isdb:iedb,jsd:jed,nz))   ; cs%uhtr(:,:,:) = 0.0
   allocate(cs%vhtr(isd:ied,jsdb:jedb,nz))   ; cs%vhtr(:,:,:) = 0.0
   allocate(cs%eatr(isd:ied,jsd:jed,nz))          ; cs%eatr(:,:,:) = 0.0
   allocate(cs%ebtr(isd:ied,jsd:jed,nz))          ; cs%ebtr(:,:,:) = 0.0
   allocate(cs%h_end(isd:ied,jsd:jed,nz))         ; cs%h_end(:,:,:) = 0.0
   allocate(cs%netMassOut(g%isd:g%ied,g%jsd:g%jed)) ; cs%netMassOut(:,:) = 0.0
   allocate(cs%netMassIn(g%isd:g%ied,g%jsd:g%jed))  ; cs%netMassIn(:,:) = 0.0
   allocate(cs%Kd(isd:ied,jsd:jed,nz+1)) ; cs%Kd = 0.
   if (cs%read_mld) then
     allocate(cs%mld(g%isd:g%ied,g%jsd:g%jed)) ; cs%mld(:,:) = 0.0
   endif
   if (cs%read_all_ts_uvh) then
     call read_all_input(cs)
   endif
   ! Initialize ids for clocks used in offline routines
   cs%id_clock_read_fields =      cpu_clock_id('(Offline read fields)',grain=clock_module)
   cs%id_clock_offline_diabatic = cpu_clock_id('(Offline diabatic)',grain=clock_module)
   cs%id_clock_offline_adv =      cpu_clock_id('(Offline transport)',grain=clock_module)
   cs%id_clock_redistribute =     cpu_clock_id('(Offline redistribute)',grain=clock_module)
   call calltree_leave("offline_transport_init")
post_offline_convergence_diags()
subroutine, public mom_offline_main::post_offline_convergence_diags (type(offline_transport_cs), intent(in) CS, real, dimension(szi_(cs%g),szj_(cs%g),szk_(cs%g)), intent(inout) h_off, real, dimension(szi_(cs%g),szj_(cs%g),szk_(cs%g)), intent(inout) h_end, real, dimension(szib_(cs%g),szj_(cs%g),szk_(cs%g)), intent(inout) uhtr, real, dimension(szi_(cs%g),szjb_(cs%g),szk_(cs%g)), intent(inout) vhtr)
Posts diagnostics related to offline convergence diagnostics.
Parameters
[in] cs Offline control structure
[in,out] h_off Thicknesses at end of offline step
[in,out] h_end Stored thicknesses
[in,out] uhtr Remaining zonal mass transport
[in,out] vhtr Remaining meridional mass transport
Definition at line 1118 of file MOM_offline_main.F90.
   type(offline_transport_cs), intent(in   ) :: cs     !< Offline control structure
   real, dimension(SZI_(CS%G),SZJ_(CS%G),SZK_(CS%G)),  intent(inout) :: h_off  !< Thicknesses at end of offline step
   real, dimension(SZI_(CS%G),SZJ_(CS%G),SZK_(CS%G)),  intent(inout) :: h_end  !< Stored thicknesses
   real, dimension(SZIB_(CS%G),SZJ_(CS%G),SZK_(CS%G)), intent(inout) :: uhtr   !< Remaining zonal mass transport
   real, dimension(SZI_(CS%G),SZJB_(CS%G),SZK_(CS%G)), intent(inout) :: vhtr   !< Remaining meridional mass transport
   real, dimension(SZI_(CS%G),SZJ_(CS%G)) :: eta_diff
   integer :: i, j, k
   if (cs%id_eta_diff_end>0) then
     ! Calculate difference in column thickness
     eta_diff = 0.
     do k=1,cs%GV%ke ; do j=cs%G%jsc,cs%G%jec ; do i=cs%G%isc,cs%G%iec
       eta_diff(i,j) = eta_diff(i,j) + h_off(i,j,k)
     enddo ; enddo ; enddo
     do k=1,cs%GV%ke ; do j=cs%G%jsc,cs%G%jec ; do i=cs%G%isc,cs%G%iec
       eta_diff(i,j) = eta_diff(i,j) - h_end(i,j,k)
     enddo ; enddo ; enddo
     call post_data(cs%id_eta_diff_end, eta_diff, cs%diag)
   endif
   if (cs%id_hdiff>0) call post_data(cs%id_hdiff, h_off-h_end, cs%diag)
   if (cs%id_hr>0) call post_data(cs%id_hr, h_off, cs%diag)
   if (cs%id_uhr_end>0) call post_data(cs%id_uhr_end, uhtr, cs%diag)
   if (cs%id_vhr_end>0) call post_data(cs%id_vhr_end, vhtr, cs%diag)
read_all_input()
subroutine mom_offline_main::read_all_input (type(offline_transport_cs), intent(inout), pointer CS) private
Coordinates the allocation and reading in all time levels of uh, vh, hend, temp, and salt from files. Used when read_all_ts_uvh.
Definition at line 1388 of file MOM_offline_main.F90.
Referenced by offline_transport_init().
   type(offline_transport_cs), pointer, intent(inout)  :: cs
   integer :: is, ie, js, je, isd, ied, jsd, jed, nz, t, ntime
   integer :: isdb, iedb, jsdb, jedb
   nz = cs%GV%ke ; ntime = cs%numtime
   isd  = cs%G%isd   ; ied  = cs%G%ied  ; jsd  = cs%G%jsd  ; jed  = cs%G%jed
   isdb = cs%G%IsdB  ; iedb = cs%G%IedB ; jsdb = cs%G%JsdB ; jedb = cs%G%JedB
   ! Extra safety check that we're not going to overallocate any arrays
   if (cs%read_all_ts_uvh) then
     if (allocated(cs%uhtr_all)) call mom_error(fatal, "uhtr_all is already allocated")
     if (allocated(cs%vhtr_all)) call mom_error(fatal, "vhtr_all is already allocated")
     if (allocated(cs%hend_all)) call mom_error(fatal, "hend_all is already allocated")
     if (allocated(cs%temp_all)) call mom_error(fatal, "temp_all is already allocated")
     if (allocated(cs%salt_all)) call mom_error(fatal, "salt_all is already allocated")
     allocate(cs%uhtr_all(isdb:iedb,jsd:jed,nz,ntime))     ; cs%uhtr_all(:,:,:,:) = 0.0
     allocate(cs%vhtr_all(isd:ied,jsdb:jedb,nz,ntime))     ; cs%vhtr_all(:,:,:,:) = 0.0
     allocate(cs%hend_all(isd:ied,jsd:jed,nz,ntime))       ; cs%hend_all(:,:,:,:) = 0.0
     allocate(cs%temp_all(isd:ied,jsd:jed,nz,1:ntime))     ; cs%temp_all(:,:,:,:) = 0.0
     allocate(cs%salt_all(isd:ied,jsd:jed,nz,1:ntime))     ; cs%salt_all(:,:,:,:) = 0.0
     if (is_root_pe()) write (0,*) "Reading in uhtr, vhtr, h_start, h_end, temp, salt"
     do t = 1,ntime
       call read_data(cs%sum_file, 'uhtr_sum', cs%uhtr_all(:,:,1:cs%nk_input,t), domain=cs%G%Domain%mpp_domain, &
         timelevel=t, position=east)
       call read_data(cs%sum_file, 'vhtr_sum', cs%vhtr_all(:,:,1:cs%nk_input,t), domain=cs%G%Domain%mpp_domain, &
         timelevel=t, position=north)
       call read_data(cs%snap_file,'h_end', cs%hend_all(:,:,1:cs%nk_input,t), domain=cs%G%Domain%mpp_domain, &
         timelevel=t, position=center)
       call read_data(cs%mean_file,'temp', cs%temp_all(:,:,1:cs%nk_input,t), domain=cs%G%Domain%mpp_domain, &
         timelevel=t, position=center)
       call read_data(cs%mean_file,'salt', cs%salt_all(:,:,1:cs%nk_input,t), domain=cs%G%Domain%mpp_domain, &
         timelevel=t, position=center)
     enddo
   endif
register_diags_offline_transport()
subroutine, public mom_offline_main::register_diags_offline_transport (type(time_type), intent(in) Time, type(diag_ctrl) diag, type(offline_transport_cs), pointer CS)
Initialize additional diagnostics required for offline tracer transport.
Parameters
cs control structure for MOM
[in] time current model time
Definition at line 1061 of file MOM_offline_main.F90.
   type(offline_transport_cs), pointer :: cs         !< control structure for MOM
   type(time_type), intent(in) :: time               !< current model time
   type(diag_ctrl)             :: diag
   ! U-cell fields
   cs%id_uhr = register_diag_field('ocean_model', 'uhr', diag%axesCuL, time, &
     'Zonal thickness fluxes remaining at end of advection', 'kg')
   cs%id_uhr_redist = register_diag_field('ocean_model', 'uhr_redist', diag%axesCuL, time, &
     'Zonal thickness fluxes to be redistributed vertically', 'kg')
   cs%id_uhr_end = register_diag_field('ocean_model', 'uhr_end', diag%axesCuL, time, &
     'Zonal thickness fluxes at end of offline step', 'kg')
   ! V-cell fields
   cs%id_vhr = register_diag_field('ocean_model', 'vhr', diag%axesCvL, time, &
     'Meridional thickness fluxes remaining at end of advection', 'kg')
   cs%id_vhr_redist = register_diag_field('ocean_model', 'vhr_redist', diag%axesCvL, time, &
     'Meridional thickness to be redistributed vertically', 'kg')
   cs%id_vhr_end = register_diag_field('ocean_model', 'vhr_end', diag%axesCvL, time, &
     'Meridional thickness at end of offline step', 'kg')
   ! T-cell fields
   cs%id_hdiff  = register_diag_field('ocean_model', 'hdiff', diag%axesTL, time, &
     'Difference between the stored and calculated layer thickness', 'm')
   cs%id_hr  = register_diag_field('ocean_model', 'hr', diag%axesTL, time, &
     'Layer thickness at end of offline step', 'm')
   cs%id_ear  = register_diag_field('ocean_model', 'ear', diag%axesTL, time, &
     'Remaining thickness entrained from above', 'm')
   cs%id_ebr  = register_diag_field('ocean_model', 'ebr', diag%axesTL, time, &
     'Remaining thickness entrained from below', 'm')
   cs%id_eta_pre_distribute = register_diag_field('ocean_model','eta_pre_distribute', &
     diag%axesT1, time, 'Total water column height before residual transport redistribution','m')
   cs%id_eta_post_distribute = register_diag_field('ocean_model','eta_post_distribute', &
     diag%axesT1, time, 'Total water column height after residual transport redistribution','m')
   cs%id_eta_diff_end = register_diag_field('ocean_model','eta_diff_end', diag%axesT1, time, &
     'Difference in total water column height from online and offline ' // &
     'at the end of the offline timestep','m')
   cs%id_h_redist = register_diag_field('ocean_model','h_redist', diag%axesTL, time, &
     'Layer thicknesses before redistribution of mass fluxes','m')
   ! Regridded/remapped input fields
   cs%id_uhtr_regrid = register_diag_field('ocean_model', 'uhtr_regrid', diag%axesCuL, time, &
                                           'Zonal mass transport regridded/remapped onto offline grid','kg')
   cs%id_vhtr_regrid = register_diag_field('ocean_model', 'vhtr_regrid', diag%axesCvL, time, &
                                           'Meridional mass transport regridded/remapped onto offline grid','kg')
   cs%id_temp_regrid = register_diag_field('ocean_model', 'temp_regrid', diag%axesTL, time, &
                                           'Temperature regridded/remapped onto offline grid','C')
   cs%id_salt_regrid = register_diag_field('ocean_model', 'salt_regrid', diag%axesTL, time, &
                                           'Salinity regridded/remapped onto offline grid','g kg-1')
   cs%id_h_regrid = register_diag_field('ocean_model', 'h_regrid', diag%axesTL, time, &
                                           'Layer thicknesses regridded/remapped onto offline grid','m')
remaining_transport_sum()
real function mom_offline_main::remaining_transport_sum (type(offline_transport_cs), pointer CS, real, dimension(szib_(cs%g),szj_(cs%g),szk_(cs%g)), intent(in) uhtr, real, dimension(szi_(cs%g),szjb_(cs%g),szk_(cs%g)), intent(in) vhtr) private
Sums any non-negligible remaining transport to check for advection convergence.
Parameters
cs control structure for offline module
[in] uhtr Zonal mass transport
[in] vhtr Meridional mass transport
Definition at line 582 of file MOM_offline_main.F90.
Referenced by offline_advection_ale(), and offline_redistribute_residual().
   type(offline_transport_cs), pointer  :: cs !< control structure for offline module
   real, dimension(SZIB_(CS%G),SZJ_(CS%G),SZK_(CS%G)), intent(in   )  :: uhtr  !< Zonal mass transport
   real, dimension(SZI_(CS%G),SZJB_(CS%G),SZK_(CS%G)), intent(in   )  :: vhtr  !< Meridional mass transport
   ! Local variables
   integer :: i, j, k
   integer :: is, ie, js, je, nz
   real :: h_min !< A layer thickness below roundoff from GV type
   real :: uh_neglect !< A small value of zonal transport that effectively is below roundoff error
   real :: vh_neglect !< A small value of meridional transport that effectively is below roundoff error
   nz = cs%GV%ke
   is = cs%G%isc ; ie = cs%G%iec ; js = cs%G%jsc ; je = cs%G%jec
   h_min = cs%GV%H_subroundoff
   remaining_transport_sum = 0.
   do k=1,nz; do j=js,je ; do i=is,ie
     uh_neglect = h_min*min(cs%G%areaT(i,j),cs%G%areaT(i+1,j))
     vh_neglect = h_min*min(cs%G%areaT(i,j),cs%G%areaT(i,j+1))
     if (abs(uhtr(i,j,k))>uh_neglect) then
       remaining_transport_sum = remaining_transport_sum + abs(uhtr(i,j,k))
     endif
     if (abs(vhtr(i,j,k))>vh_neglect) then
       remaining_transport_sum = remaining_transport_sum + abs(vhtr(i,j,k))
     endif
   enddo; enddo; enddo
   call sum_across_pes(remaining_transport_sum)
update_offline_fields()
subroutine, public mom_offline_main::update_offline_fields (type(offline_transport_cs), pointer CS, real, dimension(szi_(cs%g),szj_(cs%g),szk_(cs%g)) h, type(forcing), intent(inout) fluxes, logical, intent(in) do_ale)
Update fields used in this round of offline transport. First fields are updated from files or from arrays read during initialization. Then if in an ALE-dependent coordinate, regrid/remap fields.
Parameters
cs Control structure for offline module
h The regridded layer thicknesses
[in,out] fluxes Pointers to forcing fields
[in] do_ale True if using ALE
Definition at line 966 of file MOM_offline_main.F90.
   type(offline_transport_cs), pointer               :: cs !< Control structure for offline module
   real, dimension(SZI_(CS%G),SZJ_(CS%G),SZK_(CS%G)) :: h !< The regridded layer thicknesses
   type(forcing),        intent(inout) :: fluxes !< Pointers to forcing fields
   logical,              intent(in   ) :: do_ale !< True if using ALE
   ! Local variables
   integer :: i, j, k, is, ie, js, je, nz
   real, dimension(SZI_(CS%G),SZJ_(CS%G),SZK_(CS%G)) :: h_start
   is = cs%G%isc ; ie = cs%G%iec ; js = cs%G%jsc ; je = cs%G%jec ; nz = cs%GV%ke
   call cpu_clock_begin(cs%id_clock_read_fields)
   call calltree_enter("update_offline_fields, MOM_offline_main.F90")
   ! Store a copy of the layer thicknesses before ALE regrid/remap
   h_start(:,:,:) = h(:,:,:)
   ! Most fields will be read in from files
   call update_offline_from_files( cs%G, cs%GV, cs%nk_input, cs%mean_file, cs%sum_file, cs%snap_file, cs%surf_file,    &
                                   cs%h_end, cs%uhtr, cs%vhtr, cs%tv%T, cs%tv%S, cs%mld, cs%Kd, fluxes,                &
                                   cs%ridx_sum, cs%ridx_snap, cs%read_mld, cs%read_sw, .not. cs%read_all_ts_uvh, do_ale)
   ! If uh, vh, h_end, temp, salt were read in at the beginning, fields are copied from those arrays
   if (cs%read_all_ts_uvh) then
       call update_offline_from_arrays(cs%G, cs%GV, cs%nk_input, cs%ridx_sum, cs%mean_file, cs%sum_file, cs%snap_file, &
         cs%uhtr, cs%vhtr, cs%h_end, cs%uhtr_all, cs%vhtr_all, cs%hend_all, cs%tv%T, cs%tv%S, cs%temp_all, cs%salt_all)
     endif
   if (cs%debug) then
     call uvchksum("[uv]h after update offline from files and arrays", cs%uhtr, cs%vhtr, cs%G%HI)
   endif
   ! If using an ALE-dependent vertical coordinate, fields will need to be remapped
   if (do_ale) then
     ! These halo passes are necessary because u, v fields will need information 1 step into the halo
     call pass_var(h, cs%G%Domain)
     call pass_var(cs%tv%T, cs%G%Domain)
     call pass_var(cs%tv%S, cs%G%Domain)
     call ale_offline_inputs(cs%ALE_CSp, cs%G, cs%GV, h, cs%tv, cs%tracer_Reg, cs%uhtr, cs%vhtr, cs%Kd, cs%debug)
     if (cs%id_temp_regrid>0) call post_data(cs%id_temp_regrid, cs%tv%T, cs%diag)
     if (cs%id_salt_regrid>0) call post_data(cs%id_salt_regrid, cs%tv%S, cs%diag)
     if (cs%id_uhtr_regrid>0) call post_data(cs%id_uhtr_regrid, cs%uhtr, cs%diag)
     if (cs%id_vhtr_regrid>0) call post_data(cs%id_vhtr_regrid, cs%vhtr, cs%diag)
     if (cs%id_h_regrid>0) call post_data(cs%id_h_regrid, h, cs%diag)
     if (cs%debug) then
       call uvchksum("[uv]h after ALE regridding/remapping of inputs", cs%uhtr, cs%vhtr, cs%G%HI)
       call hchksum(h_start,"h_start after update offline from files and arrays", cs%G%HI)
     endif
   endif
   ! Update halos for some
   call pass_var(cs%h_end, cs%G%Domain)
   call pass_var(cs%tv%T, cs%G%Domain)
   call pass_var(cs%tv%S, cs%G%Domain)
   ! Update the read indices
   cs%ridx_snap = next_modulo_time(cs%ridx_snap,cs%numtime)
   cs%ridx_sum = next_modulo_time(cs%ridx_sum,cs%numtime)
   ! Apply masks/factors at T, U, and V points
   do k=1,nz ; do j=js,je ; do i=is,ie
     if (cs%G%mask2dT(i,j)<1.0) then
       cs%h_end(i,j,k) = cs%GV%Angstrom
     endif
   enddo; enddo ; enddo
   do k=1,nz+1 ; do j=js,je ; do i=is,ie
     cs%Kd(i,j,k) = max(0.0, cs%Kd(i,j,k))
     if (cs%Kd_max>0.) then
       cs%Kd(i,j,k) = min(cs%Kd_max, cs%Kd(i,j,k))
     endif
   enddo ; enddo ; enddo ;
   do k=1,nz ; do j=js-1,je ; do i=is,ie
     if (cs%G%mask2dCv(i,j)<1.0) then
       cs%vhtr(i,j,k) = 0.0
     endif
   enddo; enddo ; enddo
   do k=1,nz ; do j=js,je ; do i=is-1,ie
     if (cs%G%mask2dCu(i,j)<1.0) then
       cs%uhtr(i,j,k) = 0.0
     endif
   enddo; enddo ; enddo
   if (cs%debug) then
     call uvchksum("[uv]htr_sub after update_offline_fields", cs%uhtr, cs%vhtr, cs%G%HI)
     call hchksum(cs%h_end, "h_end after update_offline_fields", cs%G%HI)
     call hchksum(cs%tv%T, "Temp after update_offline_fields", cs%G%HI)
     call hchksum(cs%tv%S, "Salt after update_offline_fields", cs%G%HI)
   endif
   call calltree_leave("update_offline_fields")
   call cpu_clock_end(cs%id_clock_read_fields)