MOM6: polynomial_functions Module Reference
polynomial_functions Module Reference
Functions/Subroutines
real function, public evaluation_polynomial (coefficients, nb_coefficients, x)
real function, public integration_polynomial (xi0, xi1, C, n)
Function/Subroutine Documentation
evaluation_polynomial()
real function, public polynomial_functions::evaluation_polynomial (real, dimension(:), intent(in) coefficients, integer, intent(in) nb_coefficients, real, intent(in) x)
Definition at line 26 of file polynomial_functions.F90.
Referenced by regrid_edge_slopes::edge_slopes_implicit_h3(), regrid_edge_slopes::edge_slopes_implicit_h5(), regrid_edge_values::edge_values_explicit_h4(), regrid_edge_values::edge_values_implicit_h4(), and regrid_edge_values::edge_values_implicit_h6().
 ! -----------------------------------------------------------------------------
 ! The polynomial is defined by the coefficients contained in the
 ! array of the same name, as follows: C(1) + C(2)x + C(3)x^2 + C(4)x^3 + ...
 ! where C refers to the array 'coefficients'.
 ! The number of coefficients is given by nb_coefficients and x
 ! is the coordinate where the polynomial is to be evaluated.
 !
 ! The function returns the value of the polynomial at x.
 ! -----------------------------------------------------------------------------
   ! Arguments
   real, dimension(:), intent(in)        :: coefficients
   integer, intent(in)                   :: nb_coefficients
   real, intent(in)                      :: x
   ! Local variables
   integer                               :: k
   real                                  :: f    ! value of polynomial at x
   f = 0.0
   do k = 1,nb_coefficients
     f = f + coefficients(k) * ( x**(k-1) )
   end do
   evaluation_polynomial = f
integration_polynomial()
real function, public polynomial_functions::integration_polynomial (real, intent(in) xi0, real, intent(in) xi1, real, dimension(:), intent(in) C, integer, intent(in) n)
Definition at line 58 of file polynomial_functions.F90.
 ! -----------------------------------------------------------------------------
 ! Exact integration of a polynomial of degree n over the interval [xi0,xi1].
 ! The array of coefficients (C) must be of size n+1, where n is the degree of
 ! the polynomial to integrate.
 ! -----------------------------------------------------------------------------
   ! Arguments
   real, intent(in)                  :: xi0, xi1
   real, dimension(:), intent(in)    :: c
   integer, intent(in)               :: n
   ! Local variables
   integer                           :: k
   real                              :: integral
   integral = 0.0
   do k = 1,(n+1)
     integral = integral + c(k) * (xi1**k - xi0**k) / real(k)
   end do
 !
 !One non-answer-changing way of unrolling the above is:
 !  k=1
 !  integral = integral + C(k) * (xi1**k - xi0**k) / real(k)
 !  if (n>=1) then
 !    k=2
 !    integral = integral + C(k) * (xi1**k - xi0**k) / real(k)
 !  endif
 !  if (n>=2) then
 !    k=3
 !    integral = integral + C(k) * (xi1**k - xi0**k) / real(k)
 !  endif
 !  if (n>=3) then
 !    k=4
 !    integral = integral + C(k) * (xi1**k - xi0**k) / real(k)
 !  endif
 !  if (n>=4) then
 !    k=5
 !    integral = integral + C(k) * (xi1**k - xi0**k) / real(k)
 !  endif
 !
   integration_polynomial = integral