MOM6: scm_cvmix_tests Module Reference
scm_cvmix_tests Module Reference
Detailed Description
Initial conditions and forcing for the single column model (SCM) CVmix test set.
Data Types
type scm_cvmix_tests_cs
Container for surface forcing parameters.
Functions/Subroutines
subroutine, public scm_cvmix_tests_ts_init (T, S, h, G, GV, param_file, just_read_params)
Initializes temperature and salinity for the SCM CVmix test example.
subroutine, public scm_cvmix_tests_surface_forcing_init (Time, G, param_file, CS)
Initializes surface forcing for the CVmix test case suite.
subroutine, public scm_cvmix_tests_wind_forcing (state, fluxes, day, G, CS)
subroutine, public scm_cvmix_tests_buoyancy_forcing (state, fluxes, day, G, CS)
Variables
character(len=40) mdl = "SCM_CVmix_tests"
Function/Subroutine Documentation
scm_cvmix_tests_buoyancy_forcing()
subroutine, public scm_cvmix_tests::scm_cvmix_tests_buoyancy_forcing (type(surface), intent(in) state, type(forcing), intent(inout) fluxes, type(time_type), intent(in) day, type(ocean_grid_type), intent(inout) G, type(scm_cvmix_tests_cs), pointer CS)
Parameters
[in] state Surface state structure
[in,out] fluxes Surface fluxes structure
[in] day Time in days (seconds?)
[in,out] g Grid structure
cs Container for SCM parameters
Definition at line 222 of file SCM_CVmix_tests.F90.
References mom_forcing_type::allocate_forcing_type().
   type(surface),                    intent(in)    :: state  !< Surface state structure
   type(forcing),                    intent(inout) :: fluxes !< Surface fluxes structure
   type(time_type),                  intent(in)    :: day    !< Time in days (seconds?)
   type(ocean_grid_type),            intent(inout) :: g      !< Grid structure
   type(scm_cvmix_tests_cs), pointer       :: cs     !< Container for SCM parameters
   ! Local variables
   integer :: i, j, is, ie, js, je, isq, ieq, jsq, jeq
   integer :: isd, ied, jsd, jed, isdb, iedb, jsdb, jedb
   real :: pi
   pi = 4.0*atan(1.0)
   ! Bounds for loops and memory allocation
   is = g%isc ; ie = g%iec ; js = g%jsc ; je = g%jec
   isq = g%IscB ; ieq = g%IecB ; jsq = g%JscB ; jeq = g%JecB
   isd = g%isd ; ied = g%ied ; jsd = g%jsd ; jed = g%jed
   isdb = g%IsdB ; iedb = g%IedB ; jsdb = g%JsdB ; jedb = g%JedB
   ! Allocate the forcing arrays, if necessary.
   call allocate_forcing_type(g, fluxes, water=.true., heat=.true. )
   if (cs%UseHeatFlux) then
     ! Note CVmix test inputs give Heat flux in [m K/s]
     ! therefore must convert to W/m2 by multiplying
     ! by Rho0*Cp
     do j=jsq,jeq ; do i=is,ie
       fluxes%sens(i,j) = cs%surf_HF * cs%Rho0 * fluxes%C_p
     enddo; enddo
   endif
   if (cs%UseEvaporation) then
     do j=jsq,jeq ; do i=is,ie
     ! Note CVmix test inputs give evaporation in m/s
     ! This therefore must be converted to mass flux
     ! by multiplying by density
       fluxes%evap(i,j) = cs%surf_evap * cs%Rho0
     enddo; enddo
   endif
   if (cs%UseDiurnalSW) then
     do j=jsq,jeq ; do i=is,ie
     ! Note CVmix test inputs give max sw rad in [m K/s]
     ! therefore must convert to W/m2 by multiplying
     ! by Rho0*Cp
     ! Note diurnal cycle peaks at Noon.
       fluxes%sw(i,j) = cs%Max_sw * max(0.0,cos(2*pi*     &
            (time_type_to_real(day)/86400.-0.5))) * cs%RHO0 * fluxes%C_p
     enddo; enddo
   endif
scm_cvmix_tests_surface_forcing_init()
subroutine, public scm_cvmix_tests::scm_cvmix_tests_surface_forcing_init (type(time_type), intent(in) Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(scm_cvmix_tests_cs), pointer CS)
Initializes surface forcing for the CVmix test case suite.
Parameters
[in] g Grid structure
[in] param_file Input parameter structure
cs Parameter container
Definition at line 124 of file SCM_CVmix_tests.F90.
References mdl, and mom_error_handler::mom_error().
   type(time_type),              intent(in) :: time       !< Time
   type(ocean_grid_type),        intent(in) :: g          !< Grid structure
   type(param_file_type),        intent(in) :: param_file !< Input parameter structure
   type(scm_cvmix_tests_cs), pointer    :: cs         !< Parameter container
 ! This include declares and sets the variable "version".
 #include "version_variable.h"
   if (associated(cs)) then
     call mom_error(fatal, "SCM_CVmix_tests_surface_forcing_init called with an associated "// &
                           "control structure.")
     return
   endif
   allocate(cs)
   ! Read all relevant parameters and write them to the model log.
   call log_version(param_file, mdl, version, "")
   call get_param(param_file, mdl, "SCM_USE_WIND_STRESS",              &
                  cs%UseWindStress, "Wind Stress switch "//            &
                  "used in the SCM CVmix surface forcing.",            &
                  units='', default=.false.)
   call get_param(param_file, mdl, "SCM_USE_HEAT_FLUX",                &
                  cs%UseHeatFlux, "Heat flux switch "//                &
                  "used in the SCM CVmix test surface forcing.",       &
                  units='', default=.false.)
   call get_param(param_file, mdl, "SCM_USE_EVAPORATION",              &
                  cs%UseEvaporation, "Evaporation switch "//           &
                  "used in the SCM CVmix test surface forcing.",       &
                  units='', default=.false.)
   call get_param(param_file, mdl, "SCM_USE_DIURNAL_SW",               &
                  cs%UseDiurnalSW, "Diurnal sw radation switch "//     &
                  "used in the SCM CVmix test surface forcing.",       &
                  units='', default=.false.)
   if (cs%UseWindStress) then
     call get_param(param_file, mdl, "SCM_TAU_X",                      &
                  cs%tau_x, "Constant X-dir wind stress "//            &
                  "used in the SCM CVmix test surface forcing.",       &
                  units='N/m2', fail_if_missing=.true.)
     call get_param(param_file, mdl, "SCM_TAU_Y",                      &
                  cs%tau_y, "Constant y-dir wind stress "//            &
                  "used in the SCM CVmix test surface forcing.",       &
                  units='N/m2', fail_if_missing=.true.)
   endif
   if (cs%UseHeatFlux) then
     call get_param(param_file, mdl, "SCM_HEAT_FLUX",                  &
                  cs%surf_HF, "Constant surface heat flux "//          &
                  "used in the SCM CVmix test surface forcing.",       &
                  units='m K/s', fail_if_missing=.true.)
   endif
   if (cs%UseEvaporation) then
     call get_param(param_file, mdl, "SCM_EVAPORATION",                &
                  cs%surf_evap, "Constant surface evaporation "//      &
                  "used in the SCM CVmix test surface forcing.",       &
                  units='m/s', fail_if_missing=.true.)
   endif
   if (cs%UseDiurnalSW) then
     call get_param(param_file, mdl, "SCM_DIURNAL_SW_MAX",             &
                  cs%Max_sw, "Maximum diurnal sw radiation "//         &
                  "used in the SCM CVmix test surface forcing.",       &
                  units='m K/s', fail_if_missing=.true.)
   endif
scm_cvmix_tests_ts_init()
subroutine, public scm_cvmix_tests::scm_cvmix_tests_ts_init (real, dimension(nimem_,njmem_, nkmem_), intent(out) T, real, dimension(nimem_,njmem_, nkmem_), intent(out) S, real, dimension(nimem_,njmem_, nkmem_), intent(in) h, type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, type(param_file_type), intent(in) param_file, logical, intent(in), optional just_read_params)
Initializes temperature and salinity for the SCM CVmix test example.
Parameters
[out] t Potential temperature (degC)
[out] s Salinity (psu)
[in] h Layer thickness (m or Pa)
[in] g Grid structure
[in] gv Vertical grid structure
[in] param_file Input parameter structure
[in] just_read_params If present and true, this call will only read parameters without changing h.
Definition at line 50 of file SCM_CVmix_tests.F90.
References mdl.
Referenced by mom_state_initialization::mom_initialize_state().
   real, dimension(NIMEM_,NJMEM_, NKMEM_), intent(out) :: t !< Potential temperature (degC)
   real, dimension(NIMEM_,NJMEM_, NKMEM_), intent(out) :: s !< Salinity (psu)
   real, dimension(NIMEM_,NJMEM_, NKMEM_), intent(in)  :: h !< Layer thickness (m or Pa)
   type(ocean_grid_type),                  intent(in)  :: g !< Grid structure
   type(verticalgrid_type),                intent(in)  :: gv!< Vertical grid structure
   type(param_file_type),                  intent(in)  :: param_file !< Input parameter structure
   logical,       optional, intent(in)  :: just_read_params !< If present and true, this call will
                                                       !! only read parameters without changing h.
   ! Local variables
   real :: eta(szk_(g)+1) ! The 1-d nominal positions of the interfaces.
   real :: upperlayertempmld !< Upper layer Temp MLD thickness (m)
   real :: upperlayersaltmld !< Upper layer Salt MLD thickness (m)
   real :: upperlayertemp !< Upper layer temperature (SST if thickness 0) (deg C)
   real :: upperlayersalt !< Upper layer salinity (SSS if thickness 0) (PPT)
   real :: lowerlayertemp !< Temp at top of lower layer (deg C)
   real :: lowerlayersalt !< Salt at top of lower layer (PPT)
   real :: lowerlayerdtdz !< Temp gradient in lower layer (deg C m^{-1})
   real :: lowerlayerdsdz !< Salt gradient in lower layer (PPT m^{-1})
   real :: zc, dz
   logical :: just_read    ! If true, just read parameters but set nothing.
   integer :: i, j, k, is, ie, js, je, isd, ied, jsd, jed, nz
   is = g%isc ; ie = g%iec ; js = g%jsc ; je = g%jec ; nz = g%ke
   isd = g%isd ; ied = g%ied ; jsd = g%jsd ; jed = g%jed
   just_read = .false. ; if (present(just_read_params)) just_read = just_read_params
   if (.not.just_read) call log_version(param_file, mdl, version)
   call get_param(param_file, mdl,"SCM_TEMP_MLD",upperlayertempmld, &
                  'Initial temp mixed layer depth', units='m',default=0.0, do_not_log=just_read)
   call get_param(param_file, mdl,"SCM_SALT_MLD",upperlayersaltmld, &
                  'Initial salt mixed layer depth', units='m',default=0.0, do_not_log=just_read)
   call get_param(param_file, mdl,"SCM_L1_SALT",upperlayersalt, &
                  'Layer 2 surface salinity', units='1e-3',default=35.0, do_not_log=just_read)
   call get_param(param_file, mdl,"SCM_L1_TEMP",upperlayertemp, &
                  'Layer 1 surface temperature', units='C', default=20.0, do_not_log=just_read)
   call get_param(param_file, mdl,"SCM_L2_SALT",lowerlayersalt, &
                  'Layer 2 surface salinity', units='1e-3',default=35.0, do_not_log=just_read)
   call get_param(param_file, mdl,"SCM_L2_TEMP",lowerlayertemp, &
                  'Layer 2 surface temperature', units='C', default=20.0, do_not_log=just_read)
   call get_param(param_file, mdl,"SCM_L2_DTDZ",lowerlayerdtdz,     &
                  'Initial temperature stratification in layer 2', &
                  units='C/m', default=0.00, do_not_log=just_read)
   call get_param(param_file, mdl,"SCM_L2_DSDZ",lowerlayerdsdz,  &
                  'Initial salinity stratification in layer 2', &
                  units='PPT/m', default=0.00, do_not_log=just_read)
   if (just_read) return ! All run-time parameters have been read, so return.
   do j=js,je ; do i=is,ie
     eta(1) = 0. ! Reference to surface
     do k=1,nz
       eta(k+1) = eta(k) - h(i,j,k)*gv%H_to_m ! Interface below layer (in m)
       zc = 0.5*( eta(k) + eta(k+1) )        ! Z of middle of layer (in m)
       dz = min(0., zc+upperlayertempmld)
       if (dz.ge.0.0) then ! in Layer 1
         t(i,j,k) = upperlayertemp
       else ! in Layer 2
         t(i,j,k) = lowerlayertemp + lowerlayerdtdz * dz
       endif
       dz = min(0., zc+upperlayersaltmld)
       if (dz.ge.0.0) then ! in Layer 1
         s(i,j,k) = upperlayersalt
       else ! in Layer 2
         s(i,j,k) = lowerlayersalt + lowerlayerdsdz * dz
       endif
     enddo ! k
   enddo ; enddo
scm_cvmix_tests_wind_forcing()
subroutine, public scm_cvmix_tests::scm_cvmix_tests_wind_forcing (type(surface), intent(in) state, type(forcing), intent(inout) fluxes, type(time_type), intent(in) day, type(ocean_grid_type), intent(inout) G, type(scm_cvmix_tests_cs), pointer CS)
Parameters
[in] state Surface state structure
[in,out] fluxes Surface fluxes structure
[in] day Time in days
[in,out] g Grid structure
cs Container for SCM parameters
Definition at line 189 of file SCM_CVmix_tests.F90.
References mom_forcing_type::allocate_forcing_type().
   type(surface),                    intent(in)    :: state  !< Surface state structure
   type(forcing),                    intent(inout) :: fluxes !< Surface fluxes structure
   type(time_type),                  intent(in)    :: day    !< Time in days
   type(ocean_grid_type),            intent(inout) :: g      !< Grid structure
   type(scm_cvmix_tests_cs), pointer       :: cs     !< Container for SCM parameters
   ! Local variables
   integer :: i, j, is, ie, js, je, isq, ieq, jsq, jeq
   integer :: isd, ied, jsd, jed, isdb, iedb, jsdb, jedb
   real    :: mag_tau
   ! Bounds for loops and memory allocation
   is = g%isc ; ie = g%iec ; js = g%jsc ; je = g%jec
   isq = g%IscB ; ieq = g%IecB ; jsq = g%JscB ; jeq = g%JecB
   isd = g%isd ; ied = g%ied ; jsd = g%jsd ; jed = g%jed
   isdb = g%IsdB ; iedb = g%IedB ; jsdb = g%JsdB ; jedb = g%JedB
   ! Allocate the forcing arrays, if necessary.
   call allocate_forcing_type(g, fluxes, stress=.true., ustar=.true. )
   do j=js,je ; do i=isq,ieq
     fluxes%taux(i,j) = cs%tau_x
   enddo ; enddo
   do j=jsq,jeq ; do i=is,ie
     fluxes%tauy(i,j) = cs%tau_y
   enddo ; enddo
   mag_tau = sqrt(cs%tau_x*cs%tau_x + cs%tau_y*cs%tau_y)
   if (associated(fluxes%ustar)) then ; do j=js,je ; do i=is,ie
     fluxes%ustar(i,j) = sqrt(  mag_tau / cs%Rho0 )
   enddo ; enddo ; endif
Variable Documentation
mdl
character(len=40) scm_cvmix_tests::mdl = "SCM_CVmix_tests" private
Definition at line 44 of file SCM_CVmix_tests.F90.
Referenced by scm_cvmix_tests_surface_forcing_init(), and scm_cvmix_tests_ts_init().
 character(len=40)  :: mdl = "SCM_CVmix_tests" ! This module's name.