MOM6: mom_debugging Module Reference
mom_debugging Module Reference
Data Types
interface check_redundant
interface check_redundant_b
interface check_redundant_c
interface check_redundant_t
interface vec_chksum
interface vec_chksum_a
interface vec_chksum_b
interface vec_chksum_c
Functions/Subroutines
subroutine, public mom_debugging_init (param_file)
MOM_debugging_init initializes the MOM_debugging module, and sets the parameterts that control which checks are active for MOM6.
subroutine check_redundant_vc3d (mesg, u_comp, v_comp, G, is, ie, js, je, direction)
subroutine check_redundant_vc2d (mesg, u_comp, v_comp, G, is, ie, js, je, direction)
subroutine check_redundant_sb3d (mesg, array, G, is, ie, js, je)
subroutine check_redundant_sb2d (mesg, array, G, is, ie, js, je)
subroutine check_redundant_vb3d (mesg, u_comp, v_comp, G, is, ie, js, je, direction)
subroutine check_redundant_vb2d (mesg, u_comp, v_comp, G, is, ie, js, je, direction)
subroutine check_redundant_st3d (mesg, array, G, is, ie, js, je)
subroutine check_redundant_st2d (mesg, array, G, is, ie, js, je)
subroutine check_redundant_vt3d (mesg, u_comp, v_comp, G, is, ie, js, je, direction)
subroutine check_redundant_vt2d (mesg, u_comp, v_comp, G, is, ie, js, je, direction)
subroutine chksum_vec_c3d (mesg, u_comp, v_comp, G, halos, scalars)
subroutine chksum_vec_c2d (mesg, u_comp, v_comp, G, halos, scalars)
subroutine chksum_vec_b3d (mesg, u_comp, v_comp, G, halos, scalars)
subroutine chksum_vec_b2d (mesg, u_comp, v_comp, G, halos, scalars, symmetric)
subroutine chksum_vec_a3d (mesg, u_comp, v_comp, G, halos, scalars)
subroutine chksum_vec_a2d (mesg, u_comp, v_comp, G, halos, scalars)
real function, public totalstuff (HI, hThick, areaT, stuff)
This function returns the sum over computational domain of all processors of hThick*stuff, where stuff is a 3-d array at tracer points.
subroutine, public totaltands (HI, hThick, areaT, temperature, salinity, mesg)
This subroutine display the total thickness, temperature and salinity as well as the change since the last call. NOTE: This subroutine uses "save" data which is not thread safe and is purely for extreme debugging without a proper debugger.
logical function, public check_column_integral (nk, field, known_answer)
Returns false if the column integral of a given quantity is within roundoff.
logical function, public check_column_integrals (nk_1, field_1, nk_2, field_2, missing_value)
Returns false if the column integrals of two given quantities are within roundoff of each other.
Variables
integer max_redundant_prints = 100
integer, dimension(3) redundant_prints = 0
logical debug = .false.
logical debug_chksums = .true.
logical debug_redundant = .true.
Function/Subroutine Documentation
check_column_integral()
logical function, public mom_debugging::check_column_integral (integer, intent(in) nk, real, dimension(nk), intent(in) field, real, intent(in), optional known_answer)
Returns false if the column integral of a given quantity is within roundoff.
Parameters
[in] nk Number of levels in column
[in] field Field to be summed
[in] known_answer If present is the expected sum, If missing, assumed zero
Definition at line 803 of file MOM_debugging.F90.
   integer,             intent(in) :: nk           !< Number of levels in column
   real, dimension(nk), intent(in) :: field        !< Field to be summed
   real, optional,      intent(in) :: known_answer !< If present is the expected sum,
                                                   !! If missing, assumed zero
   ! Local variables
   real    :: u_sum, error, expected
   integer :: k
   u_sum = field(1)
   error = 0.
   ! Reintegrate and sum roundoff errors
   do k=2,nk
     u_sum = u_sum + field(k)
     error = error + epsilon(u_sum)*max(abs(u_sum),abs(field(k)))
   enddo
   ! Assign expected answer to either the optional input or 0
   if (present(known_answer)) then
     expected = known_answer
   else
     expected = 0.
   endif
   ! Compare the column integrals against calculated roundoff error
   if (abs(u_sum-expected) > error) then
     check_column_integral = .true.
   else
     check_column_integral = .false.
   endif
check_column_integrals()
logical function, public mom_debugging::check_column_integrals (integer, intent(in) nk_1, real, dimension(nk_1), intent(in) field_1, integer, intent(in) nk_2, real, dimension(nk_2), intent(in) field_2, real, intent(in), optional missing_value)
Returns false if the column integrals of two given quantities are within roundoff of each other.
Parameters
[in] nk_1 Number of levels in field 1
[in] nk_2 Number of levels in field 2
[in] field_1 First field to be summed
[in] field_2 Second field to be summed
[in] missing_value If column contains missing values, mask them from the sum
Definition at line 838 of file MOM_debugging.F90.
Referenced by mom_ale::ale_offline_inputs().
   integer,               intent(in) :: nk_1           !< Number of levels in field 1
   integer,               intent(in) :: nk_2           !< Number of levels in field 2
   real, dimension(nk_1), intent(in) :: field_1        !< First field to be summed
   real, dimension(nk_2), intent(in) :: field_2        !< Second field to be summed
   real, optional,        intent(in) :: missing_value  !< If column contains missing values,
                                                       !! mask them from the sum
   ! Local variables
   real    :: u1_sum, error1, u2_sum, error2, misval
   integer :: k
   ! Assign missing value
   if (present(missing_value)) then
     misval = missing_value
   else
     misval = 0.
   endif
   u1_sum = field_1(1)
   error1 = 0.
   ! Reintegrate and sum roundoff errors
   do k=2,nk_1
     if (field_1(k)/=misval) then
       u1_sum = u1_sum + field_1(k)
       error1 = error1 + epsilon(u1_sum)*max(abs(u1_sum),abs(field_1(k)))
     endif
   enddo
   u2_sum = field_2(1)
   error2 = 0.
   ! Reintegrate and sum roundoff errors
   do k=2,nk_2
     if (field_2(k)/=misval) then
       u2_sum = u2_sum + field_2(k)
       error2 = error2 + epsilon(u2_sum)*max(abs(u2_sum),abs(field_2(k)))
     endif
   enddo
   ! Compare the column integrals against calculated roundoff error
   if (abs(u1_sum-u2_sum) > (error1+error2)) then
     check_column_integrals = .true.
   else
     check_column_integrals = .false.
   endif
check_redundant_sb2d()
subroutine mom_debugging::check_redundant_sb2d (character(len=*), intent(in) mesg, real, dimension(g%isdb:,g%jsdb:), intent(in) array, type(ocean_grid_type), intent(inout) G, integer, intent(in), optional is, integer, intent(in), optional ie, integer, intent(in), optional js, integer, intent(in), optional je) private
Parameters
[in,out] g The ocean's grid structure
Definition at line 242 of file MOM_debugging.F90.
References max_redundant_prints, mom_error_handler::mom_error(), redundant_prints, and mom_domains::to_all.
Referenced by check_redundant_sb3d().
   character(len=*),                 intent(in)    :: mesg
   type(ocean_grid_type),            intent(inout) :: g    !< The ocean's grid structure
   real, dimension(G%IsdB:,G%JsdB:), intent(in)    :: array
   integer,                optional, intent(in)    :: is, ie, js, je
 ! Arguments: array - The array being checked.
 !  (in)      mesg - A message indicating what is being checked.
 !  (in)      G - The ocean's grid structure.
 !  (in/opt)  is, ie, js, je - the i- and j- range of indices to check.
   real :: a_nonsym(g%isd:g%ied,g%jsd:g%jed)
   real :: a_resym(g%isdb:g%iedb,g%jsdb:g%jedb)
   character(len=128) :: mesg2
   integer :: i, j, is_ch, ie_ch, js_ch, je_ch
   integer :: isq, ieq, jsq, jeq, isd, ied, jsd, jed, isdb, iedb, jsdb, jedb
   isq = g%IscB ; ieq = g%IecB ; jsq = g%JscB ; jeq = g%JecB
   isd = g%isd ; ied = g%ied ; jsd = g%jsd ; jed = g%jed
   isdb = g%IsdB ; iedb = g%IedB ; jsdb = g%JsdB ; jedb = g%JedB
   if (.not.(present(is) .or. present(ie) .or. present(js) .or. present(je))) then
     ! This only works with symmetric memory, so otherwise return.
     if ((isd == isdb) .and. (jsd == jsdb)) return
   endif
   do i=isd,ied ; do j=jsd,jed
     a_nonsym(i,j) = array(i,j)
   enddo ; enddo
   if (.not.associated(g%Domain_aux)) call mom_error(fatal," check_redundant"//&
     " called with a non-associated auxiliary domain the grid type.")
   call pass_vector(a_nonsym, a_nonsym, g%Domain_aux, &
                    direction=to_all+scalar_pair, stagger=bgrid_ne)
   do i=isdb,iedb ; do j=jsdb,jedb ; a_resym(i,j) = array(i,j) ; enddo ; enddo
   do i=isd,ied ; do j=jsd,jed
     a_resym(i,j) = a_nonsym(i,j)
   enddo ; enddo
   call pass_vector(a_resym, a_resym, g%Domain, direction=to_all+scalar_pair, &
                    stagger=bgrid_ne)
   is_ch = isq ; ie_ch = ieq ; js_ch = jsq ; je_ch = jeq
   if (present(is)) is_ch = is ; if (present(ie)) ie_ch = ie
   if (present(js)) js_ch = js ; if (present(js)) je_ch = je
   do i=is_ch,ie_ch ; do j=js_ch,je_ch
     if (a_resym(i,j) /= array(i,j) .and. &
         redundant_prints(2) < max_redundant_prints) then
       write(mesg2,'(" Redundant points",2(1pe12.4)," differ by ", &
                     & 1pe12.4," at i,j = ",2i4," on pe ",i4)') &
            array(i,j), a_resym(i,j),array(i,j)-a_resym(i,j),i,j,pe_here()
       write(0,'(A130)') trim(mesg)//trim(mesg2)
       redundant_prints(2) = redundant_prints(2) + 1
     endif
   enddo ; enddo
check_redundant_sb3d()
subroutine mom_debugging::check_redundant_sb3d (character(len=*), intent(in) mesg, real, dimension(g%isdb:,g%jsdb:,:), intent(in) array, type(ocean_grid_type), intent(inout) G, integer, intent(in), optional is, integer, intent(in), optional ie, integer, intent(in), optional js, integer, intent(in), optional je) private
Parameters
[in,out] g The ocean's grid structure
Definition at line 217 of file MOM_debugging.F90.
References check_redundant_sb2d().
   character(len=*),                     intent(in)    :: mesg
   type(ocean_grid_type),                intent(inout) :: g    !< The ocean's grid structure
   real, dimension(G%IsdB:,G%JsdB:,:),   intent(in)    :: array
   integer,                    optional, intent(in)    :: is, ie, js, je
 ! Arguments: array - The array being checked.
 !  (in)      mesg - A message indicating what is being checked.
 !  (in)      G - The ocean's grid structure.
 !  (in/opt)  is, ie, js, je - the i- and j- range of indices to check.
   character(len=24) :: mesg_k
   integer :: k
   do k=1,size(array,3)
     if (k < 10) then ; write(mesg_k,'(" Layer",i2," ")') k
     elseif (k < 100) then ; write(mesg_k,'(" Layer",i3," ")') k
     elseif (k < 1000) then ; write(mesg_k,'(" Layer",i4," ")') k
     else ; write(mesg_k,'(" Layer",i9," ")') k ; endif
     call check_redundant_sb2d(trim(mesg)//trim(mesg_k), array(:,:,k), &
                               g, is, ie, js, je)
   enddo
check_redundant_st2d()
subroutine mom_debugging::check_redundant_st2d (character(len=*), intent(in) mesg, real, dimension(g%isd:,g%jsd:), intent(in) array, type(ocean_grid_type), intent(inout) G, integer, intent(in), optional is, integer, intent(in), optional ie, integer, intent(in), optional js, integer, intent(in), optional je) private
Parameters
[in,out] g The ocean's grid structure
Definition at line 431 of file MOM_debugging.F90.
References max_redundant_prints, and redundant_prints.
Referenced by check_redundant_st3d().
   character(len=*),                 intent(in)    :: mesg
   type(ocean_grid_type),            intent(inout) :: g    !< The ocean's grid structure
   real, dimension(G%isd:,G%jsd:),   intent(in)    :: array
   integer,                optional, intent(in)    :: is, ie, js, je
 ! Arguments: array - The array being checked.
 !  (in)      mesg - A message indicating what is being checked.
 !  (in)      G - The ocean's grid structure.
 !  (in/opt)  is, ie, js, je - the i- and j- range of indices to check.
   real :: a_nonsym(g%isd:g%ied,g%jsd:g%jed)
   character(len=128) :: mesg2
   integer :: i, j, is_ch, ie_ch, js_ch, je_ch
   integer :: isq, ieq, jsq, jeq, isd, ied, jsd, jed
   isd = g%isd ; ied = g%ied ; jsd = g%jsd ; jed = g%jed
   is_ch = g%isc ; ie_ch = g%iec ; js_ch = g%jsc ; je_ch = g%jec
   if (present(is)) is_ch = is ; if (present(ie)) ie_ch = ie
   if (present(js)) js_ch = js ; if (present(js)) je_ch = je
   ! This only works on points outside of the standard computational domain.
   if ((is_ch == g%isc) .and. (ie_ch == g%iec) .and. &
       (js_ch == g%jsc) .and. (je_ch == g%jec)) return
   do i=isd,ied ; do j=jsd,jed
     a_nonsym(i,j) = array(i,j)
   enddo ; enddo
   call pass_var(a_nonsym, g%Domain)
   do i=is_ch,ie_ch ; do j=js_ch,je_ch
     if (a_nonsym(i,j) /= array(i,j) .and. &
         redundant_prints(1) < max_redundant_prints) then
       write(mesg2,'(" Redundant points",2(1pe12.4)," differ by ", &
                     & 1pe12.4," at i,j = ",2i4," on pe ",i4)') &
            array(i,j), a_nonsym(i,j),array(i,j)-a_nonsym(i,j),i,j,pe_here()
       write(0,'(A130)') trim(mesg)//trim(mesg2)
      redundant_prints(1) = redundant_prints(1) + 1
    endif
   enddo ; enddo
check_redundant_st3d()
subroutine mom_debugging::check_redundant_st3d (character(len=*), intent(in) mesg, real, dimension(g%isd:,g%jsd:,:), intent(in) array, type(ocean_grid_type), intent(inout) G, integer, intent(in), optional is, integer, intent(in), optional ie, integer, intent(in), optional js, integer, intent(in), optional je) private
Parameters
[in,out] g The ocean's grid structure
Definition at line 406 of file MOM_debugging.F90.
References check_redundant_st2d().
   character(len=*),                     intent(in)    :: mesg
   type(ocean_grid_type),                intent(inout) :: g    !< The ocean's grid structure
   real, dimension(G%isd:,G%jsd:,:),     intent(in)    :: array
   integer,                    optional, intent(in)    :: is, ie, js, je
 ! Arguments: array - The array being checked.
 !  (in)      mesg - A message indicating what is being checked.
 !  (in)      G - The ocean's grid structure.
 !  (in/opt)  is, ie, js, je - the i- and j- range of indices to check.
   character(len=24) :: mesg_k
   integer :: k
   do k=1,size(array,3)
     if (k < 10) then ; write(mesg_k,'(" Layer",i2," ")') k
     elseif (k < 100) then ; write(mesg_k,'(" Layer",i3," ")') k
     elseif (k < 1000) then ; write(mesg_k,'(" Layer",i4," ")') k
     else ; write(mesg_k,'(" Layer",i9," ")') k ; endif
     call check_redundant_st2d(trim(mesg)//trim(mesg_k), array(:,:,k), &
                               g, is, ie, js, je)
   enddo
check_redundant_vb2d()
subroutine mom_debugging::check_redundant_vb2d (character(len=*), intent(in) mesg, real, dimension(g%isdb:,g%jsdb:), intent(in) u_comp, real, dimension(g%isdb:,g%jsdb:), intent(in) v_comp, type(ocean_grid_type), intent(inout) G, integer, intent(in), optional is, integer, intent(in), optional ie, integer, intent(in), optional js, integer, intent(in), optional je, integer, intent(in), optional direction) private
Parameters
[in,out] g The ocean's grid structure
Definition at line 331 of file MOM_debugging.F90.
References max_redundant_prints, mom_error_handler::mom_error(), and redundant_prints.
Referenced by check_redundant_vb3d().
   character(len=*),                intent(in)    :: mesg
   type(ocean_grid_type),            intent(inout) :: g    !< The ocean's grid structure
   real, dimension(G%IsdB:,G%JsdB:), intent(in)   :: u_comp
   real, dimension(G%IsdB:,G%JsdB:), intent(in)   :: v_comp
   integer,               optional, intent(in)    :: is, ie, js, je
   integer,               optional, intent(in)    :: direction
 ! Arguments: u_comp - The u-component of the vector being checked.
 !  (in)      v_comp - The v-component of the vector being checked.
 !  (in)      mesg - A message indicating what is being checked.
 !  (in)      G - The ocean's grid structure.
 !  (in/opt)  is, ie, js, je - the i- and j- range of indices to check.
 !  (in/opt)  direction - the direction flag to be passed to pass_vector.
   real :: u_nonsym(g%isd:g%ied,g%jsd:g%jed)
   real :: v_nonsym(g%isd:g%ied,g%jsd:g%jed)
   real :: u_resym(g%isdb:g%iedb,g%jsdb:g%jedb)
   real :: v_resym(g%isdb:g%iedb,g%jsdb:g%jedb)
   character(len=128) :: mesg2
   integer :: i, j, is_ch, ie_ch, js_ch, je_ch
   integer :: isq, ieq, jsq, jeq, isd, ied, jsd, jed, isdb, iedb, jsdb, jedb
   isq = g%IscB ; ieq = g%IecB ; jsq = g%JscB ; jeq = g%JecB
   isd = g%isd ; ied = g%ied ; jsd = g%jsd ; jed = g%jed
   isdb = g%IsdB ; iedb = g%IedB ; jsdb = g%JsdB ; jedb = g%JedB
   if (.not.(present(is) .or. present(ie) .or. present(js) .or. present(je))) then
     ! This only works with symmetric memory, so otherwise return.
     if ((isd == isdb) .and. (jsd == jsdb)) return
   endif
   do i=isd,ied ; do j=jsd,jed
     u_nonsym(i,j) = u_comp(i,j) ; v_nonsym(i,j) = v_comp(i,j)
   enddo ; enddo
   if (.not.associated(g%Domain_aux)) call mom_error(fatal," check_redundant"//&
     " called with a non-associated auxiliary domain the grid type.")
   call pass_vector(u_nonsym, v_nonsym, g%Domain_aux, direction, stagger=bgrid_ne)
   do i=isdb,iedb ; do j=jsdb,jedb
     u_resym(i,j) = u_comp(i,j) ; v_resym(i,j) = v_comp(i,j)
   enddo ; enddo
   do i=isd,ied ; do j=jsd,jed
     u_resym(i,j) = u_nonsym(i,j) ; v_resym(i,j) = v_nonsym(i,j)
   enddo ; enddo
   call pass_vector(u_resym, v_resym, g%Domain, direction, stagger=bgrid_ne)
   is_ch = isq ; ie_ch = ieq ; js_ch = jsq ; je_ch = jeq
   if (present(is)) is_ch = is ; if (present(ie)) ie_ch = ie
   if (present(js)) js_ch = js ; if (present(js)) je_ch = je
   do i=is_ch,ie_ch ; do j=js_ch,je_ch
     if (u_resym(i,j) /= u_comp(i,j) .and. &
         redundant_prints(2) < max_redundant_prints) then
       write(mesg2,'(" redundant u-components",2(1pe12.4)," differ by ", &
                     & 1pe12.4," at i,j = ",2i4," on pe ",i4)') &
            u_comp(i,j), u_resym(i,j),u_comp(i,j)-u_resym(i,j),i,j,pe_here()
       write(0,'(A130)') trim(mesg)//trim(mesg2)
       redundant_prints(2) = redundant_prints(2) + 1
     endif
   enddo ; enddo
   do i=is_ch,ie_ch ; do j=js_ch,je_ch
     if (v_resym(i,j) /= v_comp(i,j) .and. &
         redundant_prints(2) < max_redundant_prints) then
       write(mesg2,'(" redundant v-comps",2(1pe12.4)," differ by ", &
                     & 1pe12.4," at i,j = ",2i4," x,y = ",2(1pe12.4)" on pe ",i4)') &
            v_comp(i,j), v_resym(i,j),v_comp(i,j)-v_resym(i,j),i,j, &
            g%geoLonBu(i,j), g%geoLatBu(i,j), pe_here()
       write(0,'(A155)') trim(mesg)//trim(mesg2)
       redundant_prints(2) = redundant_prints(2) + 1
     endif
   enddo ; enddo
check_redundant_vb3d()
subroutine mom_debugging::check_redundant_vb3d (character(len=*), intent(in) mesg, real, dimension(g%isdb:,g%jsdb:,:), intent(in) u_comp, real, dimension(g%isdb:,g%jsdb:,:), intent(in) v_comp, type(ocean_grid_type), intent(inout) G, integer, intent(in), optional is, integer, intent(in), optional ie, integer, intent(in), optional js, integer, intent(in), optional je, integer, intent(in), optional direction) private
Parameters
[in,out] g The ocean's grid structure
Definition at line 302 of file MOM_debugging.F90.
References check_redundant_vb2d().
   character(len=*),                    intent(in)    :: mesg
   type(ocean_grid_type),               intent(inout) :: g    !< The ocean's grid structure
   real, dimension(G%IsdB:,G%JsdB:,:),  intent(in)    :: u_comp
   real, dimension(G%IsdB:,G%JsdB:,:),  intent(in)    :: v_comp
   integer,                   optional, intent(in)    :: is, ie, js, je
   integer,                   optional, intent(in)    :: direction
 ! Arguments: u_comp - The u-component of the vector being checked.
 !  (in)      v_comp - The v-component of the vector being checked.
 !  (in)      mesg - A message indicating what is being checked.
 !  (in)      G - The ocean's grid structure.
 !  (in/opt)  is, ie, js, je - the i- and j- range of indices to check.
 !  (in/opt)  direction - the direction flag to be passed to pass_vector.
   character(len=24) :: mesg_k
   integer :: k
   do k=1,size(u_comp,3)
     if (k < 10) then ; write(mesg_k,'(" Layer",i2," ")') k
     elseif (k < 100) then ; write(mesg_k,'(" Layer",i3," ")') k
     elseif (k < 1000) then ; write(mesg_k,'(" Layer",i4," ")') k
     else ; write(mesg_k,'(" Layer",i9," ")') k ; endif
     call check_redundant_vb2d(trim(mesg)//trim(mesg_k), u_comp(:,:,k), &
              v_comp(:,:,k), g, is, ie, js, je, direction)
   enddo
check_redundant_vc2d()
subroutine mom_debugging::check_redundant_vc2d (character(len=*), intent(in) mesg, real, dimension(g%isdb:,g%jsd:), intent(in) u_comp, real, dimension(g%isd:,g%jsdb:), intent(in) v_comp, type(ocean_grid_type), intent(inout) G, integer, intent(in), optional is, integer, intent(in), optional ie, integer, intent(in), optional js, integer, intent(in), optional je, integer, intent(in), optional direction) private
Parameters
[in,out] g The ocean's grid structure
Definition at line 143 of file MOM_debugging.F90.
References max_redundant_prints, mom_error_handler::mom_error(), and redundant_prints.
Referenced by check_redundant_vc3d().
   character(len=*),                intent(in)    :: mesg
   type(ocean_grid_type),           intent(inout) :: g    !< The ocean's grid structure
   real, dimension(G%IsdB:,G%jsd:), intent(in)    :: u_comp
   real, dimension(G%isd:,G%JsdB:), intent(in)    :: v_comp
   integer,               optional, intent(in)    :: is, ie, js, je
   integer,               optional, intent(in)    :: direction
 ! Arguments: u_comp - The u-component of the vector being checked.
 !  (in)      v_comp - The v-component of the vector being checked.
 !  (in)      mesg - A message indicating what is being checked.
 !  (in)      G - The ocean's grid structure.
 !  (in/opt)  is, ie, js, je - the i- and j- range of indices to check.
 !  (in/opt)  direction - the direction flag to be passed to pass_vector.
   real :: u_nonsym(g%isd:g%ied,g%jsd:g%jed)
   real :: v_nonsym(g%isd:g%ied,g%jsd:g%jed)
   real :: u_resym(g%isdb:g%iedb,g%jsd:g%jed)
   real :: v_resym(g%isd:g%ied,g%jsdb:g%jedb)
   character(len=128) :: mesg2
   integer :: i, j, is_ch, ie_ch, js_ch, je_ch
   integer :: isq, ieq, jsq, jeq, isd, ied, jsd, jed, isdb, iedb, jsdb, jedb
   isq = g%IscB ; ieq = g%IecB ; jsq = g%JscB ; jeq = g%JecB
   isd = g%isd ; ied = g%ied ; jsd = g%jsd ; jed = g%jed
   isdb = g%IsdB ; iedb = g%IedB ; jsdb = g%JsdB ; jedb = g%JedB
   if (.not.(present(is) .or. present(ie) .or. present(js) .or. present(je))) then
     ! This only works with symmetric memory, so otherwise return.
     if ((isd == isdb) .and. (jsd == jsdb)) return
   endif
   do i=isd,ied ; do j=jsd,jed
     u_nonsym(i,j) = u_comp(i,j) ; v_nonsym(i,j) = v_comp(i,j)
   enddo ; enddo
   if (.not.associated(g%Domain_aux)) call mom_error(fatal," check_redundant"//&
     " called with a non-associated auxiliary domain the grid type.")
   call pass_vector(u_nonsym, v_nonsym, g%Domain_aux, direction)
   do i=isdb,iedb ; do j=jsd,jed ; u_resym(i,j) = u_comp(i,j) ; enddo ; enddo
   do i=isd,ied ; do j=jsdb,jedb ; v_resym(i,j) = v_comp(i,j) ; enddo ; enddo
   do i=isd,ied ; do j=jsd,jed
     u_resym(i,j) = u_nonsym(i,j) ; v_resym(i,j) = v_nonsym(i,j)
   enddo ; enddo
   call pass_vector(u_resym, v_resym, g%Domain, direction)
   is_ch = isq ; ie_ch = ieq ; js_ch = jsq ; je_ch = jeq
   if (present(is)) is_ch = is ; if (present(ie)) ie_ch = ie
   if (present(js)) js_ch = js ; if (present(js)) je_ch = je
   do i=is_ch,ie_ch ; do j=js_ch+1,je_ch
     if (u_resym(i,j) /= u_comp(i,j) .and. &
         redundant_prints(3) < max_redundant_prints) then
       write(mesg2,'(" redundant u-components",2(1pe12.4)," differ by ", &
                     & 1pe12.4," at i,j = ",2i4," on pe ",i4)') &
            u_comp(i,j), u_resym(i,j),u_comp(i,j)-u_resym(i,j),i,j,pe_here()
       write(0,'(A130)') trim(mesg)//trim(mesg2)
       redundant_prints(3) = redundant_prints(3) + 1
     endif
   enddo ; enddo
   do i=is_ch+1,ie_ch ; do j=js_ch,je_ch
     if (v_resym(i,j) /= v_comp(i,j) .and. &
         redundant_prints(3) < max_redundant_prints) then
       write(mesg2,'(" redundant v-comps",2(1pe12.4)," differ by ", &
                     & 1pe12.4," at i,j = ",2i4," x,y = ",2(1pe12.4)" on pe ",i4)') &
            v_comp(i,j), v_resym(i,j),v_comp(i,j)-v_resym(i,j),i,j, &
            g%geoLonBu(i,j), g%geoLatBu(i,j), pe_here()
       write(0,'(A155)') trim(mesg)//trim(mesg2)
       redundant_prints(3) = redundant_prints(3) + 1
     endif
   enddo ; enddo
check_redundant_vc3d()
subroutine mom_debugging::check_redundant_vc3d (character(len=*), intent(in) mesg, real, dimension(g%isdb:,g%jsd:,:), intent(in) u_comp, real, dimension(g%isd:,g%jsdb:,:), intent(in) v_comp, type(ocean_grid_type), intent(inout) G, integer, intent(in), optional is, integer, intent(in), optional ie, integer, intent(in), optional js, integer, intent(in), optional je, integer, intent(in), optional direction) private
Parameters
[in,out] g The ocean's grid structure
Definition at line 114 of file MOM_debugging.F90.
References check_redundant_vc2d().
   character(len=*),                    intent(in)    :: mesg
   type(ocean_grid_type),               intent(inout) :: g    !< The ocean's grid structure
   real, dimension(G%IsdB:,G%jsd:,:),   intent(in)    :: u_comp
   real, dimension(G%isd:,G%JsdB:,:),   intent(in)    :: v_comp
   integer,                   optional, intent(in)    :: is, ie, js, je
   integer,                   optional, intent(in)    :: direction
 ! Arguments: u_comp - The u-component of the vector being checked.
 !  (in)      v_comp - The v-component of the vector being checked.
 !  (in)      mesg - A message indicating what is being checked.
 !  (in)      G - The ocean's grid structure.
 !  (in/opt)  is, ie, js, je - the i- and j- range of indices to check.
 !  (in/opt)  direction - the direction flag to be passed to pass_vector.
   character(len=24) :: mesg_k
   integer :: k
   do k=1,size(u_comp,3)
     if (k < 10) then ; write(mesg_k,'(" Layer",i2," ")') k
     elseif (k < 100) then ; write(mesg_k,'(" Layer",i3," ")') k
     elseif (k < 1000) then ; write(mesg_k,'(" Layer",i4," ")') k
     else ; write(mesg_k,'(" Layer",i9," ")') k ; endif
     call check_redundant_vc2d(trim(mesg)//trim(mesg_k), u_comp(:,:,k), &
              v_comp(:,:,k), g, is, ie, js, je, direction)
   enddo
check_redundant_vt2d()
subroutine mom_debugging::check_redundant_vt2d (character(len=*), intent(in) mesg, real, dimension(g%isd:,g%jsd:), intent(in) u_comp, real, dimension(g%isd:,g%jsd:), intent(in) v_comp, type(ocean_grid_type), intent(inout) G, integer, intent(in), optional is, integer, intent(in), optional ie, integer, intent(in), optional js, integer, intent(in), optional je, integer, intent(in), optional direction) private
Parameters
[in,out] g The ocean's grid structure
Definition at line 506 of file MOM_debugging.F90.
References max_redundant_prints, and redundant_prints.
Referenced by check_redundant_vt3d().
   character(len=*),                intent(in)    :: mesg
   type(ocean_grid_type),           intent(inout) :: g    !< The ocean's grid structure
   real, dimension(G%isd:,G%jsd:),  intent(in)    :: u_comp
   real, dimension(G%isd:,G%jsd:),  intent(in)    :: v_comp
   integer,               optional, intent(in)    :: is, ie, js, je
   integer,               optional, intent(in)    :: direction
 ! Arguments: u_comp - The u-component of the vector being checked.
 !  (in)      v_comp - The v-component of the vector being checked.
 !  (in)      mesg - A message indicating what is being checked.
 !  (in)      G - The ocean's grid structure.
 !  (in/opt)  is, ie, js, je - the i- and j- range of indices to check.
 !  (in/opt)  direction - the direction flag to be passed to pass_vector.
   real :: u_nonsym(g%isd:g%ied,g%jsd:g%jed)
   real :: v_nonsym(g%isd:g%ied,g%jsd:g%jed)
   character(len=128) :: mesg2
   integer :: i, j, is_ch, ie_ch, js_ch, je_ch
   integer :: isq, ieq, jsq, jeq, isd, ied, jsd, jed, isdb, iedb, jsdb, jedb
   isq = g%IscB ; ieq = g%IecB ; jsq = g%JscB ; jeq = g%JecB
   isd = g%isd ; ied = g%ied ; jsd = g%jsd ; jed = g%jed
   isdb = g%IsdB ; iedb = g%IedB ; jsdb = g%JsdB ; jedb = g%JedB
   is_ch = g%isc ; ie_ch = g%iec ; js_ch = g%jsc ; je_ch = g%jec
   if (present(is)) is_ch = is ; if (present(ie)) ie_ch = ie
   if (present(js)) js_ch = js ; if (present(js)) je_ch = je
   ! This only works on points outside of the standard computational domain.
   if ((is_ch == g%isc) .and. (ie_ch == g%iec) .and. &
       (js_ch == g%jsc) .and. (je_ch == g%jec)) return
   do i=isd,ied ; do j=jsd,jed
     u_nonsym(i,j) = u_comp(i,j) ; v_nonsym(i,j) = v_comp(i,j)
   enddo ; enddo
   call pass_vector(u_nonsym, v_nonsym, g%Domain, direction, stagger=agrid)
   do i=is_ch,ie_ch ; do j=js_ch+1,je_ch
     if (u_nonsym(i,j) /= u_comp(i,j) .and. &
         redundant_prints(1) < max_redundant_prints) then
       write(mesg2,'(" redundant u-components",2(1pe12.4)," differ by ", &
                     & 1pe12.4," at i,j = ",2i4," on pe ",i4)') &
            u_comp(i,j), u_nonsym(i,j),u_comp(i,j)-u_nonsym(i,j),i,j,pe_here()
       write(0,'(A130)') trim(mesg)//trim(mesg2)
       redundant_prints(1) = redundant_prints(1) + 1
     endif
   enddo ; enddo
   do i=is_ch+1,ie_ch ; do j=js_ch,je_ch
     if (v_nonsym(i,j) /= v_comp(i,j) .and. &
         redundant_prints(1) < max_redundant_prints) then
       write(mesg2,'(" redundant v-comps",2(1pe12.4)," differ by ", &
                     & 1pe12.4," at i,j = ",2i4," x,y = ",2(1pe12.4)" on pe ",i4)') &
            v_comp(i,j), v_nonsym(i,j),v_comp(i,j)-v_nonsym(i,j),i,j, &
            g%geoLonBu(i,j), g%geoLatBu(i,j), pe_here()
       write(0,'(A155)') trim(mesg)//trim(mesg2)
       redundant_prints(1) = redundant_prints(1) + 1
     endif
   enddo ; enddo
check_redundant_vt3d()
subroutine mom_debugging::check_redundant_vt3d (character(len=*), intent(in) mesg, real, dimension(g%isd:,g%jsd:,:), intent(in) u_comp, real, dimension(g%isd:,g%jsd:,:), intent(in) v_comp, type(ocean_grid_type), intent(inout) G, integer, intent(in), optional is, integer, intent(in), optional ie, integer, intent(in), optional js, integer, intent(in), optional je, integer, intent(in), optional direction) private
Parameters
[in,out] g The ocean's grid structure
Definition at line 477 of file MOM_debugging.F90.
References check_redundant_vt2d().
   character(len=*),                    intent(in)    :: mesg
   type(ocean_grid_type),               intent(inout) :: g    !< The ocean's grid structure
   real, dimension(G%isd:,G%jsd:,:),    intent(in)    :: u_comp
   real, dimension(G%isd:,G%jsd:,:),    intent(in)    :: v_comp
   integer,                   optional, intent(in)    :: is, ie, js, je
   integer,                   optional, intent(in)    :: direction
 ! Arguments: u_comp - The u-component of the vector being checked.
 !  (in)      v_comp - The v-component of the vector being checked.
 !  (in)      mesg - A message indicating what is being checked.
 !  (in)      G - The ocean's grid structure.
 !  (in/opt)  is, ie, js, je - the i- and j- range of indices to check.
 !  (in/opt)  direction - the direction flag to be passed to pass_vector.
   character(len=24) :: mesg_k
   integer :: k
   do k=1,size(u_comp,3)
     if (k < 10) then ; write(mesg_k,'(" Layer",i2," ")') k
     elseif (k < 100) then ; write(mesg_k,'(" Layer",i3," ")') k
     elseif (k < 1000) then ; write(mesg_k,'(" Layer",i4," ")') k
     else ; write(mesg_k,'(" Layer",i9," ")') k ; endif
     call check_redundant_vt2d(trim(mesg)//trim(mesg_k), u_comp(:,:,k), &
              v_comp(:,:,k), g, is, ie, js, je, direction)
   enddo
chksum_vec_a2d()
subroutine mom_debugging::chksum_vec_a2d (character(len=*), intent(in) mesg, real, dimension(g%isd:,g%jsd:), intent(in) u_comp, real, dimension(g%isd:,g%jsd:), intent(in) v_comp, type(ocean_grid_type), intent(inout) G, integer, intent(in), optional halos, logical, intent(in), optional scalars) private
Parameters
[in] mesg An identifying message
[in,out] g The ocean's grid structure
[in] u_comp The u-component of the vector
[in] v_comp The v-component of the vector
[in] halos The width of halos to check (default 0)
[in] scalars If true this is a pair of scalars that are being checked.
Definition at line 707 of file MOM_debugging.F90.
References debug_chksums, debug_redundant, and mom_domains::to_all.
   character(len=*),               intent(in)    :: mesg   !< An identifying message
   type(ocean_grid_type),          intent(inout) :: g      !< The ocean's grid structure
   real, dimension(G%isd:,G%jsd:), intent(in)    :: u_comp !< The u-component of the vector
   real, dimension(G%isd:,G%jsd:), intent(in)    :: v_comp !< The v-component of the vector
   integer,              optional, intent(in)    :: halos  !< The width of halos to check (default 0)
   logical,              optional, intent(in)    :: scalars !< If true this is a pair of
                                                            !! scalars that are being checked.
   logical :: are_scalars
   are_scalars = .false. ; if (present(scalars)) are_scalars = scalars
   if (debug_chksums) then
     call hchksum(u_comp, mesg//"(u)", g%HI, halos)
     call hchksum(v_comp, mesg//"(v)", g%HI, halos)
   endif
   if (debug_redundant) then
     if (are_scalars) then
       call check_redundant_t(mesg, u_comp, v_comp, g, direction=to_all+scalar_pair)
     else
       call check_redundant_t(mesg, u_comp, v_comp, g)
     endif
   endif
chksum_vec_a3d()
subroutine mom_debugging::chksum_vec_a3d (character(len=*), intent(in) mesg, real, dimension(g%isd:,g%jsd:,:), intent(in) u_comp, real, dimension(g%isd:,g%jsd:,:), intent(in) v_comp, type(ocean_grid_type), intent(inout) G, integer, intent(in), optional halos, logical, intent(in), optional scalars) private
Parameters
[in] mesg An identifying message
[in,out] g The ocean's grid structure
[in] u_comp The u-component of the vector
[in] v_comp The v-component of the vector
[in] halos The width of halos to check (default 0)
[in] scalars If true this is a pair of scalars that are being checked.
Definition at line 679 of file MOM_debugging.F90.
References debug_chksums, debug_redundant, and mom_domains::to_all.
   character(len=*),                 intent(in)    :: mesg   !< An identifying message
   type(ocean_grid_type),            intent(inout) :: g      !< The ocean's grid structure
   real, dimension(G%isd:,G%jsd:,:), intent(in)    :: u_comp !< The u-component of the vector
   real, dimension(G%isd:,G%jsd:,:), intent(in)    :: v_comp !< The v-component of the vector
   integer,                optional, intent(in)    :: halos  !< The width of halos to check (default 0)
   logical,                optional, intent(in)    :: scalars !< If true this is a pair of
                                                              !! scalars that are being checked.
   logical :: are_scalars
   are_scalars = .false. ; if (present(scalars)) are_scalars = scalars
   if (debug_chksums) then
     call hchksum(u_comp, mesg//"(u)", g%HI, halos)
     call hchksum(v_comp, mesg//"(v)", g%HI, halos)
   endif
   if (debug_redundant) then
     if (are_scalars) then
       call check_redundant_t(mesg, u_comp, v_comp, g, direction=to_all+scalar_pair)
     else
       call check_redundant_t(mesg, u_comp, v_comp, g)
     endif
   endif
chksum_vec_b2d()
subroutine mom_debugging::chksum_vec_b2d (character(len=*), intent(in) mesg, real, dimension(g%isdb:,g%jsdb:), intent(in) u_comp, real, dimension(g%isdb:,g%jsdb:), intent(in) v_comp, type(ocean_grid_type), intent(inout) G, integer, intent(in), optional halos, logical, intent(in), optional scalars, logical, intent(in), optional symmetric) private
Parameters
[in] mesg An identifying message
[in,out] g The ocean's grid structure
[in] u_comp The u-component of the vector
[in] v_comp The v-component of the vector
[in] halos The width of halos to check (default 0)
[in] scalars If true this is a pair of scalars that are being checked.
[in] symmetric If true, do the checksums on the full symmetric computational domain.
Definition at line 650 of file MOM_debugging.F90.
References debug_chksums, debug_redundant, and mom_domains::to_all.
   character(len=*),                 intent(in)    :: mesg   !< An identifying message
   type(ocean_grid_type),            intent(inout) :: g      !< The ocean's grid structure
   real, dimension(G%IsdB:,G%JsdB:), intent(in)    :: u_comp !< The u-component of the vector
   real, dimension(G%IsdB:,G%JsdB:), intent(in)    :: v_comp !< The v-component of the vector
   integer,                optional, intent(in)    :: halos  !< The width of halos to check (default 0)
   logical,                optional, intent(in)    :: scalars !< If true this is a pair of
                                                              !! scalars that are being checked.
   logical,                optional, intent(in)    :: symmetric !< If true, do the checksums on the
                                                                !! full symmetric computational domain.
   logical :: are_scalars
   are_scalars = .false. ; if (present(scalars)) are_scalars = scalars
   if (debug_chksums) then
     call bchksum(u_comp, mesg//"(u)", g%HI, halos, symmetric=symmetric)
     call bchksum(v_comp, mesg//"(v)", g%HI, halos, symmetric=symmetric)
   endif
   if (debug_redundant) then
     if (are_scalars) then
       call check_redundant_b(mesg, u_comp, v_comp, g, direction=to_all+scalar_pair)
     else
       call check_redundant_b(mesg, u_comp, v_comp, g)
     endif
   endif
chksum_vec_b3d()
subroutine mom_debugging::chksum_vec_b3d (character(len=*), intent(in) mesg, real, dimension(g%isdb:,g%jsdb:,:), intent(in) u_comp, real, dimension(g%isdb:,g%jsdb:,:), intent(in) v_comp, type(ocean_grid_type), intent(inout) G, integer, intent(in), optional halos, logical, intent(in), optional scalars) private
Parameters
[in] mesg An identifying message
[in,out] g The ocean's grid structure
[in] u_comp The u-component of the vector
[in] v_comp The v-component of the vector
[in] halos The width of halos to check (default 0)
[in] scalars If true this is a pair of scalars that are being checked.
Definition at line 623 of file MOM_debugging.F90.
References debug_chksums, debug_redundant, and mom_domains::to_all.
   character(len=*),                   intent(in)    :: mesg   !< An identifying message
   type(ocean_grid_type),              intent(inout) :: g      !< The ocean's grid structure
   real, dimension(G%IsdB:,G%JsdB:,:), intent(in)    :: u_comp !< The u-component of the vector
   real, dimension(G%IsdB:,G%JsdB:,:), intent(in)    :: v_comp !< The v-component of the vector
   integer,                  optional, intent(in)    :: halos  !< The width of halos to check (default 0)
   logical,                  optional, intent(in)    :: scalars !< If true this is a pair of
                                                                !! scalars that are being checked.
   logical :: are_scalars
   are_scalars = .false. ; if (present(scalars)) are_scalars = scalars
   if (debug_chksums) then
     call bchksum(u_comp, mesg//"(u)", g%HI, halos)
     call bchksum(v_comp, mesg//"(v)", g%HI, halos)
   endif
   if (debug_redundant) then
     if (are_scalars) then
       call check_redundant_b(mesg, u_comp, v_comp, g, direction=to_all+scalar_pair)
     else
       call check_redundant_b(mesg, u_comp, v_comp, g)
     endif
   endif
chksum_vec_c2d()
subroutine mom_debugging::chksum_vec_c2d (character(len=*), intent(in) mesg, real, dimension(g%isdb:,g%jsd:), intent(in) u_comp, real, dimension(g%isd:,g%jsdb:), intent(in) v_comp, type(ocean_grid_type), intent(inout) G, integer, intent(in), optional halos, logical, intent(in), optional scalars) private
Parameters
[in] mesg An identifying message
[in,out] g The ocean's grid structure
[in] u_comp The u-component of the vector
[in] v_comp The v-component of the vector
[in] halos The width of halos to check (default 0)
[in] scalars If true this is a pair of scalars that are being checked.
Definition at line 597 of file MOM_debugging.F90.
References debug_chksums, debug_redundant, and mom_domains::to_all.
   character(len=*),                intent(in)    :: mesg   !< An identifying message
   type(ocean_grid_type),           intent(inout) :: g      !< The ocean's grid structure
   real, dimension(G%IsdB:,G%jsd:), intent(in)    :: u_comp !< The u-component of the vector
   real, dimension(G%isd:,G%JsdB:), intent(in)    :: v_comp !< The v-component of the vector
   integer,               optional, intent(in)    :: halos  !< The width of halos to check (default 0)
   logical,               optional, intent(in)    :: scalars !< If true this is a pair of
                                                             !! scalars that are being checked.
   logical :: are_scalars
   are_scalars = .false. ; if (present(scalars)) are_scalars = scalars
   if (debug_chksums) then
     call uvchksum(mesg, u_comp, v_comp, g%HI, halos)
   endif
   if (debug_redundant) then
     if (are_scalars) then
       call check_redundant_c(mesg, u_comp, v_comp, g, direction=to_all+scalar_pair)
     else
       call check_redundant_c(mesg, u_comp, v_comp, g)
     endif
   endif
chksum_vec_c3d()
subroutine mom_debugging::chksum_vec_c3d (character(len=*), intent(in) mesg, real, dimension(g%isdb:,g%jsd:,:), intent(in) u_comp, real, dimension(g%isd:,g%jsdb:,:), intent(in) v_comp, type(ocean_grid_type), intent(inout) G, integer, intent(in), optional halos, logical, intent(in), optional scalars) private
Parameters
[in] mesg An identifying message
[in,out] g The ocean's grid structure
[in] u_comp The u-component of the vector
[in] v_comp The v-component of the vector
[in] halos The width of halos to check (default 0)
[in] scalars If true this is a pair of scalars that are being checked.
Definition at line 571 of file MOM_debugging.F90.
References debug_chksums, debug_redundant, and mom_domains::to_all.
   character(len=*),                  intent(in)    :: mesg   !< An identifying message
   type(ocean_grid_type),             intent(inout) :: g      !< The ocean's grid structure
   real, dimension(G%IsdB:,G%jsd:,:), intent(in)    :: u_comp !< The u-component of the vector
   real, dimension(G%isd:,G%JsdB:,:), intent(in)    :: v_comp !< The v-component of the vector
   integer,                 optional, intent(in)    :: halos  !< The width of halos to check (default 0)
   logical,                 optional, intent(in)    :: scalars !< If true this is a pair of
                                                               !! scalars that are being checked.
   logical :: are_scalars
   are_scalars = .false. ; if (present(scalars)) are_scalars = scalars
   if (debug_chksums) then
     call uvchksum(mesg, u_comp, v_comp, g%HI, halos)
   endif
   if (debug_redundant) then
     if (are_scalars) then
       call check_redundant_c(mesg, u_comp, v_comp, g, direction=to_all+scalar_pair)
     else
       call check_redundant_c(mesg, u_comp, v_comp, g)
     endif
   endif
mom_debugging_init()
subroutine, public mom_debugging::mom_debugging_init (type(param_file_type), intent(in) param_file)
MOM_debugging_init initializes the MOM_debugging module, and sets the parameterts that control which checks are active for MOM6.
Parameters
[in] param_file A structure to parse for run-time parameters
Definition at line 93 of file MOM_debugging.F90.
References debug, debug_chksums, debug_redundant, and mom_checksums::mom_checksums_init().
   type(param_file_type),   intent(in)    :: param_file !< A structure to parse for run-time parameters
 ! This include declares and sets the variable "version".
 #include "version_variable.h"
   character(len=40)  :: mdl = "MOM_debugging" ! This module's name.
   call log_version(param_file, mdl, version)
   call get_param(param_file, mdl, "DEBUG", debug, &
                  "If true, write out verbose debugging data.", default=.false.)
   call get_param(param_file, mdl, "DEBUG_CHKSUMS", debug_chksums, &
                  "If true, checksums are performed on arrays in the \n"//&
                  "various vec_chksum routines.", default=debug)
   call get_param(param_file, mdl, "DEBUG_REDUNDANT", debug_redundant, &
                  "If true, debug redundant data points during calls to \n"//&
                  "the various vec_chksum routines.", default=debug)
   call mom_checksums_init(param_file)
totalstuff()
real function, public mom_debugging::totalstuff (type(hor_index_type), intent(in) HI, real, dimension(hi%isd:,hi%jsd:,:), intent(in) hThick, real, dimension(hi%isd:,hi%jsd:), intent(in) areaT, real, dimension(hi%isd:,hi%jsd:,:), intent(in) stuff)
This function returns the sum over computational domain of all processors of hThick*stuff, where stuff is a 3-d array at tracer points.
Parameters
[in] hi A horizontal index type
[in] hthick The array of thicknesses to use as weights
[in] areat The array of cell areas in m2
[in] stuff The array of stuff to be summed
Definition at line 738 of file MOM_debugging.F90.
Referenced by totaltands().
   type(hor_index_type),               intent(in) :: hi     !< A horizontal index type
   real, dimension(HI%isd:,HI%jsd:,:), intent(in) :: hthick !< The array of thicknesses to use as weights
   real, dimension(HI%isd:,HI%jsd:),   intent(in) :: areat  !< The array of cell areas in m2
   real, dimension(HI%isd:,HI%jsd:,:), intent(in) :: stuff  !< The array of stuff to be summed
   real                                         :: totalstuff
   integer :: i, j, k, nz
   nz = size(hthick,3)
   totalstuff = 0.
   do k = 1, nz ; do j = hi%jsc, hi%jec ; do i = hi%isc, hi%iec
     totalstuff = totalstuff + hthick(i,j,k) * stuff(i,j,k) * areat(i,j)
   enddo ; enddo ; enddo
   call sum_across_pes(totalstuff)
totaltands()
subroutine, public mom_debugging::totaltands (type(hor_index_type), intent(in) HI, real, dimension(hi%isd:,hi%jsd:,:), intent(in) hThick, real, dimension(hi%isd:,hi%jsd:), intent(in) areaT, real, dimension(hi%isd:,hi%jsd:,:), intent(in) temperature, real, dimension(hi%isd:,hi%jsd:,:), intent(in) salinity, character(len=*), intent(in) mesg)
This subroutine display the total thickness, temperature and salinity as well as the change since the last call. NOTE: This subroutine uses "save" data which is not thread safe and is purely for extreme debugging without a proper debugger.
Parameters
[in] hi A horizontal index type
[in] hthick The array of thicknesses to use as weights
[in] areat The array of cell areas in m2
[in] temperature The temperature field to sum
[in] salinity The salinity field to sum
[in] mesg An identifying message
Definition at line 761 of file MOM_debugging.F90.
References mom_error_handler::is_root_pe(), and totalstuff().
   type(hor_index_type),               intent(in) :: hi     !< A horizontal index type
   real, dimension(HI%isd:,HI%jsd:,:), intent(in) :: hthick !< The array of thicknesses to use as weights
   real, dimension(HI%isd:,HI%jsd:),   intent(in) :: areat  !< The array of cell areas in m2
   real, dimension(HI%isd:,HI%jsd:,:), intent(in) :: temperature !< The temperature field to sum
   real, dimension(HI%isd:,HI%jsd:,:), intent(in) :: salinity    !< The salinity field to sum
   character(len=*),                   intent(in) :: mesg        !< An identifying message
   ! NOTE: This subroutine uses "save" data which is not thread safe and is purely for
   ! extreme debugging without a proper debugger.
   real, save :: totalh = 0., totalt = 0., totals = 0.
   logical, save :: firstcall = .true.
   real :: thish, thist, thiss, delh, delt, dels
   integer :: i, j, k, nz
   nz = size(hthick,3)
   thish = 0.
   do k = 1, nz ; do j = hi%jsc, hi%jec ; do i = hi%isc, hi%iec
     thish = thish + hthick(i,j,k) * areat(i,j)
   enddo ; enddo ; enddo
   call sum_across_pes(thish)
   thist = totalstuff(hi, hthick, areat, temperature)
   thiss = totalstuff(hi, hthick, areat, salinity)
   if (is_root_pe()) then
     if (firstcall) then
       totalh = thish ; totalt = thist ; totals = thiss
       write(0,*) 'Totals H,T,S:',thish,thist,thiss,' ',mesg
       firstcall = .false.
     else
       delh = thish - totalh
       delt = thist - totalt
       dels = thiss - totals
       totalh = thish ; totalt = thist ; totals = thiss
       write(0,*) 'Tot/del H,T,S:',thish,thist,thiss,delh,delt,dels,' ',mesg
     endif
   endif
Variable Documentation
debug
logical mom_debugging::debug = .false. private
Definition at line 82 of file MOM_debugging.F90.
Referenced by mom_debugging_init().
 logical :: debug = .false.
debug_chksums
logical mom_debugging::debug_chksums = .true. private
Definition at line 83 of file MOM_debugging.F90.
Referenced by chksum_vec_a2d(), chksum_vec_a3d(), chksum_vec_b2d(), chksum_vec_b3d(), chksum_vec_c2d(), chksum_vec_c3d(), and mom_debugging_init().
 logical :: debug_chksums = .true.
debug_redundant
logical mom_debugging::debug_redundant = .true. private
Definition at line 84 of file MOM_debugging.F90.
Referenced by chksum_vec_a2d(), chksum_vec_a3d(), chksum_vec_b2d(), chksum_vec_b3d(), chksum_vec_c2d(), chksum_vec_c3d(), and mom_debugging_init().
 logical :: debug_redundant = .true.
max_redundant_prints
integer mom_debugging::max_redundant_prints = 100 private
Definition at line 80 of file MOM_debugging.F90.
Referenced by check_redundant_sb2d(), check_redundant_st2d(), check_redundant_vb2d(), check_redundant_vc2d(), and check_redundant_vt2d().
 integer :: max_redundant_prints = 100
redundant_prints
integer, dimension(3) mom_debugging::redundant_prints = 0 private
Definition at line 81 of file MOM_debugging.F90.
Referenced by check_redundant_sb2d(), check_redundant_st2d(), check_redundant_vb2d(), check_redundant_vc2d(), and check_redundant_vt2d().
 integer :: redundant_prints(3) = 0