MOM6: mom_eos Module Reference
mom_eos Module Reference
Detailed Description
Provides subroutines for quantities specific to the equation of state.
The MOM_EOS module is a wrapper for various equations of state (e.g. Linear, Wright, UNESCO) and provides a uniform interface to the rest of the model independent of which equation of state is being used.
Data Types
interface calculate_density
Calculates density of sea water from T, S and P.
interface calculate_tfreeze
Calculates the freezing point of sea water from T, S and P.
type eos_type
A control structure for the equation of state.
Functions/Subroutines
subroutine calculate_density_scalar (T, S, pressure, rho, EOS)
Calls the appropriate subroutine to calculate density of sea water for scalar inputs.
subroutine calculate_density_array (T, S, pressure, rho, start, npts, EOS)
Calls the appropriate subroutine to calculate the density of sea water for 1-D array inputs.
subroutine calculate_tfreeze_scalar (S, pressure, T_fr, EOS)
Calls the appropriate subroutine to calculate the freezing point for scalar inputs.
subroutine calculate_tfreeze_array (S, pressure, T_fr, start, npts, EOS)
Calls the appropriate subroutine to calculate the freezing point for a 1-D array.
subroutine, public calculate_density_derivs (T, S, pressure, drho_dT, drho_dS, start, npts, EOS)
Calls the appropriate subroutine to calculate density derivatives for 1-D array inputs.
subroutine, public calculate_specific_vol_derivs (T, S, pressure, dSV_dT, dSV_dS, start, npts, EOS)
Calls the appropriate subroutine to calculate specific volume derivatives for an array.
subroutine, public calculate_compress (T, S, pressure, rho, drho_dp, start, npts, EOS)
Calls the appropriate subroutine to calculate the density and compressibility for 1-D array inputs.
subroutine, public int_specific_vol_dp (T, S, p_t, p_b, alpha_ref, HI, EOS, dza, intp_dza, intx_dza, inty_dza, halo_size)
Calls the appropriate subroutine to alculate analytical and nearly-analytical integrals in pressure across layers of geopotential anomalies, which are required for calculating the finite-volume form pressure accelerations in a non-Boussinesq model. There are essentially no free assumptions, apart from the use of Bode's rule to do the horizontal integrals, and from a truncation in the series for log(1-eps/1+eps) that assumes that |eps| < .
subroutine, public int_density_dz (T, S, z_t, z_b, rho_ref, rho_0, G_e, HII, HIO, EOS, dpa, intz_dpa, intx_dpa, inty_dpa)
This subroutine calculates analytical and nearly-analytical integrals of pressure anomalies across layers, which are required for calculating the finite-volume form pressure accelerations in a Boussinesq model. The one potentially dodgy assumtion here is that rho_0 is used both in the denominator of the accelerations, and in the pressure used to calculated density (the latter being -z*rho_0*G_e). These two uses could be separated if need be.
logical function, public query_compressible (EOS)
Returns true if the equation of state is compressible (i.e. has pressure dependence)
subroutine, public eos_init (param_file, EOS)
Initializes EOS_type by allocating and reading parameters.
subroutine, public eos_allocate (EOS)
Allocates EOS_type.
subroutine, public eos_end (EOS)
Deallocates EOS_type.
subroutine, public eos_use_linear (Rho_T0_S0, dRho_dT, dRho_dS, EOS, use_quadrature)
Set equation of state structure (EOS) to linear with given coefficients.
subroutine int_density_dz_generic (T, S, z_t, z_b, rho_ref, rho_0, G_e, HII, HIO, EOS, dpa, intz_dpa, intx_dpa, inty_dpa)
subroutine int_density_dz_generic_cell (T_t_arg, T_b_arg, S_t_arg, S_b_arg, z_t_arg, z_b_arg, depth, rho_ref, rho_0, G_e, EOS, dpa, intz_dpa, intx_dpa, inty_dpa)
subroutine, public int_density_dz_generic_plm (T_t, T_b, S_t, S_b, z_t, z_b, rho_ref, rho_0, G_e, H_subroundoff, bathyT, HII, HIO, EOS, dpa, intz_dpa, intx_dpa, inty_dpa, useMassWghtInterp)
subroutine, public find_depth_of_pressure_in_cell (T_t, T_b, S_t, S_b, z_t, z_b, P_t, P_tgt, rho_ref, G_e, EOS, P_b, z_out)
Find the depth at which the reconstructed pressure matches P_tgt.
real function frac_dp_at_pos (T_t, T_b, S_t, S_b, z_t, z_b, rho_ref, G_e, pos, EOS)
Returns change in anomalous pressure change from top to non-dimensional position pos between z_t and z_b.
subroutine, public int_density_dz_generic_ppm (T, T_t, T_b, S, S_t, S_b, z_t, z_b, rho_ref, rho_0, G_e, HII, HIO, EOS, dpa, intz_dpa, intx_dpa, inty_dpa)
subroutine, public int_density_dz_generic_plm_analytic (T_t, T_b, S_t, S_b, z_t, z_b, rho_ref, rho_0, G_e, HI, EOS, dpa, intz_dpa, intx_dpa, inty_dpa)
subroutine compute_integral_bilinear (x, y, f, integral)
subroutine compute_integral_quadratic (x, y, f, integral)
subroutine evaluate_shape_bilinear (xi, eta, phi, dphidxi, dphideta)
subroutine evaluate_shape_quadratic (xi, eta, phi, dphidxi, dphideta)
subroutine int_spec_vol_dp_generic (T, S, p_t, p_b, alpha_ref, HI, EOS, dza, intp_dza, intx_dza, inty_dza, halo_size)
subroutine, public convert_temp_salt_for_teos10 (T, S, press, G, kd, mask_z, EOS)
Convert T&S to Absolute Salinity and Conservative Temperature if using TEOS10.
Variables
integer, parameter eos_linear = 1
integer, parameter eos_unesco = 2
integer, parameter eos_wright = 3
integer, parameter eos_teos10 = 4
integer, parameter eos_nemo = 5
character *(10), parameter eos_linear_string = "LINEAR"
character *(10), parameter eos_unesco_string = "UNESCO"
character *(10), parameter eos_wright_string = "WRIGHT"
character *(10), parameter eos_teos10_string = "TEOS10"
character *(10), parameter eos_nemo_string = "NEMO"
character *(10), parameter eos_default = EOS_WRIGHT_STRING
integer, parameter tfreeze_linear = 1
integer, parameter tfreeze_millero = 2
integer, parameter tfreeze_teos10 = 3
character *(10), parameter tfreeze_linear_string = "LINEAR"
character *(10), parameter tfreeze_millero_string = "MILLERO_78"
character *(10), parameter tfreeze_teos10_string = "TEOS10"
character *(10), parameter tfreeze_default = TFREEZE_LINEAR_STRING
Function/Subroutine Documentation
calculate_compress()
subroutine, public mom_eos::calculate_compress (real, dimension(:), intent(in) T, real, dimension(:), intent(in) S, real, dimension(:), intent(in) pressure, real, dimension(:), intent(out) rho, real, dimension(:), intent(out) drho_dp, integer, intent(in) start, integer, intent(in) npts, type(eos_type), pointer EOS)
Calls the appropriate subroutine to calculate the density and compressibility for 1-D array inputs.
Parameters
[in] t Potential temperature referenced to the surface (degC)
[in] s Salinity (PSU)
[in] pressure Pressure (Pa)
[out] rho In situ density in kg m-3.
[out] drho_dp The partial derivative of density with pressure (also the inverse of the square of sound speed) in s2 m-2.
[in] start Starting index within the array
[in] npts The number of values to calculate
eos Equation of state structure
Definition at line 293 of file MOM_EOS.F90.
References mom_eos_linear::calculate_compress_linear(), mom_eos_nemo::calculate_compress_nemo(), mom_eos_unesco::calculate_compress_unesco(), mom_eos_wright::calculate_compress_wright(), eos_linear, eos_nemo, eos_teos10, eos_unesco, eos_wright, and mom_error_handler::mom_error().
   real, dimension(:), intent(in)  :: t !< Potential temperature referenced to the surface (degC)
   real, dimension(:), intent(in)  :: s !< Salinity (PSU)
   real, dimension(:), intent(in)  :: pressure !< Pressure (Pa)
   real, dimension(:), intent(out) :: rho !< In situ density in kg m-3.
   real, dimension(:), intent(out) :: drho_dp !< The partial derivative of density with pressure
                                      !! (also the inverse of the square of sound speed) in s2 m-2.
   integer,            intent(in)  :: start !< Starting index within the array
   integer,            intent(in)  :: npts !< The number of values to calculate
   type(eos_type),     pointer     :: eos !< Equation of state structure
   if (.not.associated(eos)) call mom_error(fatal, &
     "calculate_compress called with an unassociated EOS_type EOS.")
   select case (eos%form_of_EOS)
     case (eos_linear)
       call calculate_compress_linear(t, s, pressure, rho, drho_dp, start, npts, &
                                      eos%Rho_T0_S0, eos%dRho_dT, eos%dRho_dS)
     case (eos_unesco)
       call calculate_compress_unesco(t, s, pressure, rho, drho_dp, start, npts)
     case (eos_wright)
       call calculate_compress_wright(t, s, pressure, rho, drho_dp, start, npts)
     case (eos_teos10)
       call calculate_compress_teos10(t, s, pressure, rho, drho_dp, start, npts)
     case (eos_nemo)
       call calculate_compress_nemo(t, s, pressure, rho, drho_dp, start, npts)
     case default
       call mom_error(fatal, &
            "calculate_compress: EOS%form_of_EOS is not valid.")
   end select
calculate_density_array()
subroutine mom_eos::calculate_density_array (real, dimension(:), intent(in) T, real, dimension(:), intent(in) S, real, dimension(:), intent(in) pressure, real, dimension(:), intent(out) rho, integer, intent(in) start, integer, intent(in) npts, type(eos_type), pointer EOS) private
Calls the appropriate subroutine to calculate the density of sea water for 1-D array inputs.
Parameters
[in] t Potential temperature referenced to the surface (degC)
[in] s Salinity (PSU)
[in] pressure Pressure (Pa)
[out] rho Density (in-situ if pressure is local) (kg m-3)
[in] start Start index for computation
[in] npts Number of point to compute
eos Equation of state structure
Definition at line 130 of file MOM_EOS.F90.
References eos_linear, eos_nemo, eos_teos10, eos_unesco, eos_wright, and mom_error_handler::mom_error().
Referenced by frac_dp_at_pos(), and int_density_dz_generic_plm().
   real, dimension(:), intent(in)  :: t !< Potential temperature referenced to the surface (degC)
   real, dimension(:), intent(in)  :: s !< Salinity (PSU)
   real, dimension(:), intent(in)  :: pressure !< Pressure (Pa)
   real, dimension(:), intent(out) :: rho !< Density (in-situ if pressure is local) (kg m-3)
   integer,            intent(in)  :: start !< Start index for computation
   integer,            intent(in)  :: npts !< Number of point to compute
   type(eos_type),     pointer     :: eos !< Equation of state structure
   if (.not.associated(eos)) call mom_error(fatal, &
     "calculate_density_array called with an unassociated EOS_type EOS.")
   select case (eos%form_of_EOS)
     case (eos_linear)
       call calculate_density_array_linear(t, s, pressure, rho, start, npts, &
                                       eos%Rho_T0_S0, eos%dRho_dT, eos%dRho_dS)
     case (eos_unesco)
       call calculate_density_array_unesco(t, s, pressure, rho, start, npts)
     case (eos_wright)
       call calculate_density_array_wright(t, s, pressure, rho, start, npts)
     case (eos_teos10)
       call calculate_density_array_teos10(t, s, pressure, rho, start, npts)
     case (eos_nemo)
       call calculate_density_array_nemo  (t, s, pressure, rho, start, npts)
     case default
       call mom_error(fatal, &
            "calculate_density_array: EOS%form_of_EOS is not valid.")
   end select
calculate_density_derivs()
subroutine, public mom_eos::calculate_density_derivs (real, dimension(:), intent(in) T, real, dimension(:), intent(in) S, real, dimension(:), intent(in) pressure, real, dimension(:), intent(out) drho_dT, real, dimension(:), intent(out) drho_dS, integer, intent(in) start, integer, intent(in) npts, type(eos_type), pointer EOS)
Calls the appropriate subroutine to calculate density derivatives for 1-D array inputs.
Parameters
[in] t Potential temperature referenced to the surface (degC)
[in] s Salinity (PSU)
[in] pressure Pressure (Pa)
[out] drho_dt The partial derivative of density with potential tempetature, in kg m-3 K-1.
[out] drho_ds The partial derivative of density with salinity, in kg m-3 psu-1.
[in] start Starting index within the array
[in] npts The number of values to calculate
eos Equation of state structure
Definition at line 214 of file MOM_EOS.F90.
References eos_linear, eos_nemo, eos_teos10, eos_unesco, eos_wright, and mom_error_handler::mom_error().
Referenced by mom_diabatic_aux::applyboundaryfluxesinout(), benchmark_initialization::benchmark_init_temperature_salinity(), benchmark_initialization::benchmark_initialize_thickness(), coord_adapt::build_adapt_column(), coord_slight::build_slight_column(), mom_bulk_mixed_layer::bulkmixedlayer(), mom_isopycnal_slopes::calc_isoneutral_slopes(), mom_kappa_shear::calculate_kappa_shear(), mom_forcing_type::calculatebuoyancyflux1d(), midas_vertmap::determine_temperature(), dome_initialization::dome_set_obc_data(), mom_entrain_diffusive::entrainment_diffusive(), mom_int_tide_input::find_n2_bottom(), mom_geothermal::geothermal(), isomip_initialization::isomip_initialize_temperature_salinity(), mom_neutral_diffusion::neutral_diffusion_calc_coeffs(), mom_set_visc::set_viscous_bbl(), mom_set_visc::set_viscous_ml(), mom_thickness_diffuse::thickness_diffuse_full(), mom_wave_speed::wave_speed(), and mom_wave_structure::wave_structure().
   real, dimension(:), intent(in)  :: t !< Potential temperature referenced to the surface (degC)
   real, dimension(:), intent(in)  :: s !< Salinity (PSU)
   real, dimension(:), intent(in)  :: pressure !< Pressure (Pa)
   real, dimension(:), intent(out) :: drho_dt !< The partial derivative of density with potential tempetature, in kg m-3 K-1.
   real, dimension(:), intent(out) :: drho_ds !< The partial derivative of density with salinity, in kg m-3 psu-1.
   integer,            intent(in)  :: start !< Starting index within the array
   integer,            intent(in)  :: npts !< The number of values to calculate
   type(eos_type),     pointer     :: eos !< Equation of state structure
   !!
   if (.not.associated(eos)) call mom_error(fatal, &
     "calculate_density_derivs called with an unassociated EOS_type EOS.")
   select case (eos%form_of_EOS)
     case (eos_linear)
       call calculate_density_derivs_linear(t, s, pressure, drho_dt, drho_ds, start, &
                                            npts, eos%Rho_T0_S0, eos%dRho_dT, eos%dRho_dS)
     case (eos_unesco)
       call calculate_density_derivs_unesco(t, s, pressure, drho_dt, drho_ds, start, npts)
     case (eos_wright)
       call calculate_density_derivs_wright(t, s, pressure, drho_dt, drho_ds, start, npts)
     case (eos_teos10)
       call calculate_density_derivs_teos10(t, s, pressure, drho_dt, drho_ds, start, npts)
     case (eos_nemo)
       call calculate_density_derivs_nemo(t, s, pressure, drho_dt, drho_ds, start, npts)
     case default
       call mom_error(fatal, &
            "calculate_density_derivs: EOS%form_of_EOS is not valid.")
   end select
calculate_density_scalar()
subroutine mom_eos::calculate_density_scalar (real, intent(in) T, real, intent(in) S, real, intent(in) pressure, real, intent(out) rho, type(eos_type), pointer EOS) private
Calls the appropriate subroutine to calculate density of sea water for scalar inputs.
Parameters
[in] t Potential temperature referenced to the surface (degC)
[in] s Salinity (PSU)
[in] pressure Pressure (Pa)
[out] rho Density (in-situ if pressure is local) (kg m-3)
eos Equation of state structure
Definition at line 100 of file MOM_EOS.F90.
References eos_linear, eos_nemo, eos_teos10, eos_unesco, eos_wright, and mom_error_handler::mom_error().
   real,           intent(in)  :: t !< Potential temperature referenced to the surface (degC)
   real,           intent(in)  :: s !< Salinity (PSU)
   real,           intent(in)  :: pressure !< Pressure (Pa)
   real,           intent(out) :: rho !< Density (in-situ if pressure is local) (kg m-3)
   type(eos_type), pointer     :: eos !< Equation of state structure
   if (.not.associated(eos)) call mom_error(fatal, &
     "calculate_density_scalar called with an unassociated EOS_type EOS.")
   select case (eos%form_of_EOS)
     case (eos_linear)
       call calculate_density_scalar_linear(t, s, pressure, rho, &
                                       eos%Rho_T0_S0, eos%dRho_dT, eos%dRho_dS)
     case (eos_unesco)
       call calculate_density_scalar_unesco(t, s, pressure, rho)
     case (eos_wright)
       call calculate_density_scalar_wright(t, s, pressure, rho)
     case (eos_teos10)
       call calculate_density_scalar_teos10(t, s, pressure, rho)
     case (eos_nemo)
       call calculate_density_scalar_nemo(t, s, pressure, rho)
     case default
       call mom_error(fatal, &
            "calculate_density_scalar: EOS is not valid.")
   end select
calculate_specific_vol_derivs()
subroutine, public mom_eos::calculate_specific_vol_derivs (real, dimension(:), intent(in) T, real, dimension(:), intent(in) S, real, dimension(:), intent(in) pressure, real, dimension(:), intent(out) dSV_dT, real, dimension(:), intent(out) dSV_dS, integer, intent(in) start, integer, intent(in) npts, type(eos_type), pointer EOS)
Calls the appropriate subroutine to calculate specific volume derivatives for an array.
Parameters
[in] t Potential temperature referenced to the surface (degC)
[in] s Salinity (PSU)
[in] pressure Pressure (Pa)
[out] dsv_dt The partial derivative of specific volume with potential temperature, in m3 kg-1 K-1.
[out] dsv_ds The partial derivative of specific volume with salinity, in m3 kg-1 / (g/kg).
[in] start Starting index within the array
[in] npts The number of values to calculate
eos Equation of state structure
Definition at line 247 of file MOM_EOS.F90.
References eos_linear, eos_nemo, eos_teos10, eos_unesco, eos_wright, and mom_error_handler::mom_error().
Referenced by mom_diabatic_aux::applyboundaryfluxesinout(), and mom_diapyc_energy_req::diapyc_energy_req_calc().
   real, dimension(:), intent(in)  :: t !< Potential temperature referenced to the surface (degC)
   real, dimension(:), intent(in)  :: s !< Salinity (PSU)
   real, dimension(:), intent(in)  :: pressure !< Pressure (Pa)
   real, dimension(:), intent(out) :: dsv_dt !< The partial derivative of specific volume with potential temperature, in m3 kg-1 K-1.
   real, dimension(:), intent(out) :: dsv_ds !< The partial derivative of specific volume with salinity, in m3 kg-1 / (g/kg).
   integer,            intent(in)  :: start !< Starting index within the array
   integer,            intent(in)  :: npts !< The number of values to calculate
   type(eos_type),     pointer     :: eos !< Equation of state structure
   ! Local variables
   real, dimension(size(T)) :: drho_dt, drho_ds, rho
   integer :: j
   if (.not.associated(eos)) call mom_error(fatal, &
     "calculate_density_derivs called with an unassociated EOS_type EOS.")
   select case (eos%form_of_EOS)
     case (eos_linear)
       call calculate_specvol_derivs_linear(t, s, pressure, dsv_dt, dsv_ds, start, &
                                            npts, eos%Rho_T0_S0, eos%dRho_dT, eos%dRho_dS)
     case (eos_unesco)
       call calculate_density_unesco(t, s, pressure, rho, start, npts)
       call calculate_density_derivs_unesco(t, s, pressure, drho_dt, drho_ds, start, npts)
       do j=start,start+npts-1
         dsv_dt(j) = -drho_dt(j)/(rho(j)**2)
         dsv_ds(j) = -drho_ds(j)/(rho(j)**2)
       enddo
     case (eos_wright)
       call calculate_specvol_derivs_wright(t, s, pressure, dsv_dt, dsv_ds, start, npts)
     case (eos_teos10)
       call calculate_specvol_derivs_teos10(t, s, pressure, dsv_dt, dsv_ds, start, npts)
     case (eos_nemo)
       call calculate_density_nemo(t, s, pressure, rho, start, npts)
       call calculate_density_derivs_nemo(t, s, pressure, drho_dt, drho_ds, start, npts)
       do j=start,start+npts-1
         dsv_dt(j) = -drho_dt(j)/(rho(j)**2)
         dsv_ds(j) = -drho_ds(j)/(rho(j)**2)
       enddo
     case default
       call mom_error(fatal, &
            "calculate_density_derivs: EOS%form_of_EOS is not valid.")
   end select
calculate_tfreeze_array()
subroutine mom_eos::calculate_tfreeze_array (real, dimension(:), intent(in) S, real, dimension(:), intent(in) pressure, real, dimension(:), intent(out) T_fr, integer, intent(in) start, integer, intent(in) npts, type(eos_type), pointer EOS) private
Calls the appropriate subroutine to calculate the freezing point for a 1-D array.
Parameters
[in] s Salinity (PSU)
[in] pressure Pressure (Pa)
[out] t_fr Freezing point potential temperature referenced to the surface (degC)
[in] start Starting index within the array
[in] npts The number of values to calculate
eos Equation of state structure
Definition at line 187 of file MOM_EOS.F90.
References mom_error_handler::mom_error(), tfreeze_linear, tfreeze_millero, and tfreeze_teos10.
   real, dimension(:), intent(in)  :: s !< Salinity (PSU)
   real, dimension(:), intent(in)  :: pressure !< Pressure (Pa)
   real, dimension(:), intent(out) :: t_fr !< Freezing point potential temperature referenced to the surface (degC)
   integer,            intent(in)  :: start !< Starting index within the array
   integer,            intent(in)  :: npts !< The number of values to calculate
   type(eos_type),     pointer     :: eos !< Equation of state structure
   if (.not.associated(eos)) call mom_error(fatal, &
     "calculate_TFreeze_scalar called with an unassociated EOS_type EOS.")
   select case (eos%form_of_TFreeze)
     case (tfreeze_linear)
       call calculate_tfreeze_linear(s, pressure, t_fr, start, npts, &
                                     eos%TFr_S0_P0, eos%dTFr_dS, eos%dTFr_dp)
     case (tfreeze_millero)
       call calculate_tfreeze_millero(s, pressure, t_fr, start, npts)
     case (tfreeze_teos10)
       call calculate_tfreeze_teos10(s, pressure, t_fr, start, npts)
     case default
       call mom_error(fatal, &
            "calculate_TFreeze_scalar: form_of_TFreeze is not valid.")
   end select
calculate_tfreeze_scalar()
subroutine mom_eos::calculate_tfreeze_scalar (real, intent(in) S, real, intent(in) pressure, real, intent(out) T_fr, type(eos_type), pointer EOS) private
Calls the appropriate subroutine to calculate the freezing point for scalar inputs.
Parameters
[in] s Salinity (PSU)
[in] pressure Pressure (Pa)
[out] t_fr Freezing point potential temperature referenced to the surface (degC)
eos Equation of state structure
Definition at line 162 of file MOM_EOS.F90.
References mom_error_handler::mom_error(), tfreeze_linear, tfreeze_millero, and tfreeze_teos10.
   real,           intent(in)  :: s !< Salinity (PSU)
   real,           intent(in)  :: pressure !< Pressure (Pa)
   real,           intent(out) :: t_fr !< Freezing point potential temperature referenced to the surface (degC)
   type(eos_type), pointer     :: eos !< Equation of state structure
   if (.not.associated(eos)) call mom_error(fatal, &
     "calculate_TFreeze_scalar called with an unassociated EOS_type EOS.")
   select case (eos%form_of_TFreeze)
     case (tfreeze_linear)
       call calculate_tfreeze_linear(s, pressure, t_fr, eos%TFr_S0_P0, &
                                     eos%dTFr_dS, eos%dTFr_dp)
     case (tfreeze_millero)
       call calculate_tfreeze_millero(s, pressure, t_fr)
     case (tfreeze_teos10)
       call calculate_tfreeze_teos10(s, pressure, t_fr)
     case default
       call mom_error(fatal, &
            "calculate_TFreeze_scalar: form_of_TFreeze is not valid.")
   end select
compute_integral_bilinear()
subroutine mom_eos::compute_integral_bilinear (real, dimension(4), intent(in) x, real, dimension(4), intent(in) y, real, dimension(4), intent(in) f, real, intent(out) integral) private
Definition at line 1756 of file MOM_EOS.F90.
References evaluate_shape_bilinear().
Referenced by int_density_dz_generic_plm_analytic().
   ! Arguments
   real, intent(in), dimension(4)    :: x, y, f
   real, intent(out)                 :: integral
   ! Local variables
   integer               :: i, k
   real, dimension(4)    :: weight, xi, eta          ! integration points
   real                  :: f_k
   real                  :: dxdxi, dxdeta
   real                  :: dydxi, dydeta
   real, dimension(4)    :: phi, dphidxi, dphideta
   real                  :: jacobian_k
   ! Quadrature rule
   weight(:) = 1.0
   xi(1) = - sqrt(3.0) / 3.0
   xi(2) = sqrt(3.0) / 3.0
   xi(3) = sqrt(3.0) / 3.0
   xi(4) = - sqrt(3.0) / 3.0
   eta(1) = - sqrt(3.0) / 3.0
   eta(2) = - sqrt(3.0) / 3.0
   eta(3) = sqrt(3.0) / 3.0
   eta(4) = sqrt(3.0) / 3.0
   integral = 0.0
   ! Integration loop
   do k = 1,4
     ! Evaluate shape functions and gradients
     call evaluate_shape_bilinear ( xi(k), eta(k), phi, dphidxi, dphideta )
     ! Determine gradient of global coordinate at integration point
     dxdxi  = 0.0
     dxdeta = 0.0
     dydxi  = 0.0
     dydeta = 0.0
     do i = 1,4
       dxdxi  = dxdxi  + x(i) * dphidxi(i)
       dxdeta = dxdeta + x(i) * dphideta(i)
       dydxi  = dydxi  + y(i) * dphidxi(i)
       dydeta = dydeta + y(i) * dphideta(i)
     enddo
     ! Evaluate Jacobian at integration point
     jacobian_k = dxdxi*dydeta - dydxi*dxdeta
     ! Evaluate function at integration point
     f_k = 0.0
     do i = 1,4
       f_k = f_k + f(i) * phi(i)
     enddo
     integral = integral + weight(k) * f_k * jacobian_k
   enddo ! end integration loop
compute_integral_quadratic()
subroutine mom_eos::compute_integral_quadratic (real, dimension(4), intent(in) x, real, dimension(4), intent(in) y, real, dimension(9), intent(in) f, real, intent(out) integral) private
Definition at line 1822 of file MOM_EOS.F90.
References evaluate_shape_bilinear(), and evaluate_shape_quadratic().
Referenced by int_density_dz_generic_ppm().
   ! Arguments
   real, intent(in), dimension(4)    :: x, y
   real, intent(in), dimension(9)    :: f
   real, intent(out)                 :: integral
   ! Local variables
   integer               :: i, k
   real, dimension(9)    :: weight, xi, eta          ! integration points
   real                  :: f_k
   real                  :: dxdxi, dxdeta
   real                  :: dydxi, dydeta
   real, dimension(4)    :: phiiso, dphiisodxi, dphiisodeta
   real, dimension(9)    :: phi, dphidxi, dphideta
   real                  :: jacobian_k
   real                  :: t
   ! Quadrature rule (4 points)
   !weight(:) = 1.0
   !xi(1) = - sqrt(3.0) / 3.0
   !xi(2) = sqrt(3.0) / 3.0
   !xi(3) = sqrt(3.0) / 3.0
   !xi(4) = - sqrt(3.0) / 3.0
   !eta(1) = - sqrt(3.0) / 3.0
   !eta(2) = - sqrt(3.0) / 3.0
   !eta(3) = sqrt(3.0) / 3.0
   !eta(4) = sqrt(3.0) / 3.0
   ! Quadrature rule (9 points)
   t = sqrt(3.0/5.0)
   weight(1) = 25.0/81.0 ; xi(1) = -t ; eta(1) = t
   weight(2) = 40.0/81.0 ; xi(2) = .0 ; eta(2) = t
   weight(3) = 25.0/81.0 ; xi(3) =  t ; eta(3) = t
   weight(4) = 40.0/81.0 ; xi(4) = -t ; eta(4) = .0
   weight(5) = 64.0/81.0 ; xi(5) = .0 ; eta(5) = .0
   weight(6) = 40.0/81.0 ; xi(6) =  t ; eta(6) = .0
   weight(7) = 25.0/81.0 ; xi(7) = -t ; eta(7) = -t
   weight(8) = 40.0/81.0 ; xi(8) = .0 ; eta(8) = -t
   weight(9) = 25.0/81.0 ; xi(9) =  t ; eta(9) = -t
   integral = 0.0
   ! Integration loop
   do k = 1,9
     ! Evaluate shape functions and gradients for isomorphism
     call evaluate_shape_bilinear ( xi(k), eta(k), phiiso, &
                                    dphiisodxi, dphiisodeta )
     ! Determine gradient of global coordinate at integration point
     dxdxi  = 0.0
     dxdeta = 0.0
     dydxi  = 0.0
     dydeta = 0.0
     do i = 1,4
       dxdxi  = dxdxi  + x(i) * dphiisodxi(i)
       dxdeta = dxdeta + x(i) * dphiisodeta(i)
       dydxi  = dydxi  + y(i) * dphiisodxi(i)
       dydeta = dydeta + y(i) * dphiisodeta(i)
     enddo
     ! Evaluate Jacobian at integration point
     jacobian_k = dxdxi*dydeta - dydxi*dxdeta
     ! Evaluate shape functions for interpolation
     call evaluate_shape_quadratic ( xi(k), eta(k), phi, dphidxi, dphideta )
     ! Evaluate function at integration point
     f_k = 0.0
     do i = 1,9
       f_k = f_k + f(i) * phi(i)
     enddo
     integral = integral + weight(k) * f_k * jacobian_k
   enddo ! end integration loop
convert_temp_salt_for_teos10()
subroutine, public mom_eos::convert_temp_salt_for_teos10 (real, dimension(g %isd: g %ied, g %jsd: g %jed, g %ke), intent(inout) T, real, dimension(g %isd: g %ied, g %jsd: g %jed, g %ke), intent(inout) S, real, dimension(:), intent(in) press, type(ocean_grid_type), intent(in) G, integer, intent(in) kd, real, dimension(g %isd: g %ied, g %jsd: g %jed, g %ke), intent(in) mask_z, type(eos_type), pointer EOS)
Convert T&S to Absolute Salinity and Conservative Temperature if using TEOS10.
Parameters
[in] g The horizontal index structure
[in] g The ocean's grid structure
[in,out] t Potential temperature referenced to the surface (degC)
[in,out] s Salinity (PSU)
[in] press Pressure at the top of the layer in Pa.
eos Equation of state structure
[in] mask_z 3d mask
Definition at line 2129 of file MOM_EOS.F90.
References eos_nemo, eos_teos10, and mom_error_handler::mom_error().
Referenced by mom_state_initialization::mom_temp_salt_initialize_from_z().
   use mom_grid, only : ocean_grid_type
   !> The horizontal index structure
   type(ocean_grid_type),                      intent(in)  :: g    !< The ocean's grid structure
   !> Potential temperature referenced to the surface (degC)
   real, dimension(SZI_(G),SZJ_(G), SZK_(G)),  intent(inout)  :: t
   !> Salinity (PSU)
   real, dimension(SZI_(G),SZJ_(G), SZK_(G)),  intent(inout)  :: s
   !> Pressure at the top of the layer in Pa.
   real, dimension(:),                            intent(in)  :: press
   !> Equation of state structure
   type(eos_type), pointer                                 :: eos
   !> 3d mask
   real, dimension(SZI_(G),SZJ_(G), SZK_(G)),  intent(in)  :: mask_z
   integer,                                    intent(in)  :: kd
   !
   integer :: i,j,k
   real :: gsw_sr_from_sp, gsw_ct_from_pt, gsw_sa_from_sp
   real :: p
   if (.not.associated(eos)) call mom_error(fatal, &
     "convert_temp_salt_to_TEOS10 called with an unassociated EOS_type EOS.")
   if ((eos%form_of_EOS .ne. eos_teos10) .and. (eos%form_of_EOS .ne. eos_nemo)) return
   do k=1,kd ; do j=g%jsc,g%jec ; do i=g%isc,g%iec
     if (mask_z(i,j,k) .ge. 1.0) then
      s(i,j,k) = gsw_sr_from_sp(s(i,j,k))
 !     p=press(k)/10000. !convert pascal to dbar
 !     S(i,j,k) = gsw_sa_from_sp(S(i,j,k),p,G%geoLonT(i,j),G%geoLatT(i,j))
      t(i,j,k) = gsw_ct_from_pt(s(i,j,k),t(i,j,k))
     endif
   enddo; enddo; enddo
eos_allocate()
subroutine, public mom_eos::eos_allocate (type(eos_type), pointer EOS)
Allocates EOS_type.
Parameters
eos Equation of state structure
Definition at line 558 of file MOM_EOS.F90.
Referenced by eos_init().
   type(eos_type), pointer :: eos !< Equation of state structure
   if (.not.associated(eos)) allocate(eos)
eos_end()
subroutine, public mom_eos::eos_end (type(eos_type), pointer EOS)
Deallocates EOS_type.
Parameters
eos Equation of state structure
Definition at line 565 of file MOM_EOS.F90.
   type(eos_type), pointer :: eos !< Equation of state structure
   if (associated(eos)) deallocate(eos)
eos_init()
subroutine, public mom_eos::eos_init (type(param_file_type), intent(in) param_file, type(eos_type), pointer EOS)
Initializes EOS_type by allocating and reading parameters.
Parameters
[in] param_file Parameter file structure
eos Equation of state structure
Definition at line 459 of file MOM_EOS.F90.
References eos_allocate(), eos_default, eos_linear, eos_linear_string, eos_nemo, eos_nemo_string, eos_teos10, eos_teos10_string, eos_unesco, eos_unesco_string, eos_wright, eos_wright_string, mom_error_handler::mom_error(), mom_error_handler::mom_mesg(), tfreeze_default, tfreeze_linear, tfreeze_linear_string, tfreeze_millero, tfreeze_millero_string, tfreeze_teos10, tfreeze_teos10_string, and mom_string_functions::uppercase().
   type(param_file_type), intent(in) :: param_file !< Parameter file structure
   type(eos_type),        pointer    :: eos !< Equation of state structure
   ! Local variables
 #include "version_variable.h"
   character(len=40)  :: mdl = "MOM_EOS" ! This module's name.
   character(len=40)  :: tmpstr
   if (.not.associated(eos)) call eos_allocate(eos)
   ! Read all relevant parameters and write them to the model log.
   call log_version(param_file, mdl, version, "")
   call get_param(param_file, mdl, "EQN_OF_STATE", tmpstr, &
                  "EQN_OF_STATE determines which ocean equation of state \n"//&
                  "should be used.  Currently, the valid choices are \n"//&
                  '"LINEAR", "UNESCO", "WRIGHT", "NEMO" and "TEOS10". \n'//&
                  "This is only used if USE_EOS is true.", default=eos_default)
   select case (uppercase(tmpstr))
     case (eos_linear_string)
       eos%form_of_EOS = eos_linear
     case (eos_unesco_string)
       eos%form_of_EOS = eos_unesco
     case (eos_wright_string)
       eos%form_of_EOS = eos_wright
     case (eos_teos10_string)
       eos%form_of_EOS = eos_teos10
     case (eos_nemo_string)
       eos%form_of_EOS = eos_nemo
     case default
       call mom_error(fatal, "interpret_eos_selection: EQN_OF_STATE "//&
                               trim(tmpstr) // "in input file is invalid.")
   end select
   call mom_mesg('interpret_eos_selection: equation of state set to "' // &
                 trim(tmpstr)//'"', 5)
   if (eos%form_of_EOS == eos_linear) then
     eos%Compressible = .false.
     call get_param(param_file, mdl, "RHO_T0_S0", eos%Rho_T0_S0, &
                  "When EQN_OF_STATE="//trim(eos_linear_string)//", \n"//&
                  "this is the density at T=0, S=0.", units="kg m-3", &
                  default=1000.0)
     call get_param(param_file, mdl, "DRHO_DT", eos%dRho_dT, &
                  "When EQN_OF_STATE="//trim(eos_linear_string)//", \n"//&
                  "this is the partial derivative of density with \n"//&
                  "temperature.", units="kg m-3 K-1", default=-0.2)
     call get_param(param_file, mdl, "DRHO_DS", eos%dRho_dS, &
                  "When EQN_OF_STATE="//trim(eos_linear_string)//", \n"//&
                  "this is the partial derivative of density with \n"//&
                  "salinity.", units="kg m-3 PSU-1", default=0.8)
   endif
   call get_param(param_file, mdl, "EOS_QUADRATURE", eos%EOS_quadrature, &
                  "If true, always use the generic (quadrature) code \n"//&
                  "code for the integrals of density.", default=.false.)
   call get_param(param_file, mdl, "TFREEZE_FORM", tmpstr, &
                  "TFREEZE_FORM determines which expression should be \n"//&
                  "used for the freezing point.  Currently, the valid \n"//&
                  'choices are "LINEAR", "MILLERO_78", "TEOS10"', &
                  default=tfreeze_default)
   select case (uppercase(tmpstr))
     case (tfreeze_linear_string)
       eos%form_of_TFreeze = tfreeze_linear
     case (tfreeze_millero_string)
       eos%form_of_TFreeze = tfreeze_millero
     case (tfreeze_teos10_string)
       eos%form_of_TFreeze = tfreeze_teos10
     case default
       call mom_error(fatal, "interpret_eos_selection:  TFREEZE_FORM "//&
                               trim(tmpstr) // "in input file is invalid.")
   end select
   if (eos%form_of_TFreeze == tfreeze_linear) then
     call get_param(param_file, mdl, "TFREEZE_S0_P0",eos%TFr_S0_P0, &
                  "When TFREEZE_FORM="//trim(tfreeze_linear_string)//", \n"//&
                  "this is the freezing potential temperature at \n"//&
                  "S=0, P=0.", units="deg C", default=0.0)
     call get_param(param_file, mdl, "DTFREEZE_DS",eos%dTFr_dS, &
                  "When TFREEZE_FORM="//trim(tfreeze_linear_string)//", \n"//&
                  "this is the derivative of the freezing potential \n"//&
                  "temperature with salinity.", &
                  units="deg C PSU-1", default=-0.054)
     call get_param(param_file, mdl, "DTFREEZE_DP",eos%dTFr_dP, &
                  "When TFREEZE_FORM="//trim(tfreeze_linear_string)//", \n"//&
                  "this is the derivative of the freezing potential \n"//&
                  "temperature with pressure.", &
                  units="deg C Pa-1", default=0.0)
   endif
   if (eos%form_of_EOS == eos_teos10 .OR. eos%form_of_EOS == eos_nemo .AND. eos%form_of_TFreeze /= tfreeze_teos10) then
       call mom_error(fatal, "interpret_eos_selection:  EOS_TEOS10 or EOS_NEMO \n" //&
       "should only be used along with TFREEZE_FORM = TFREEZE_TEOS10 .")
   endif
eos_use_linear()
subroutine, public mom_eos::eos_use_linear (real, intent(in) Rho_T0_S0, real, intent(in) dRho_dT, real, intent(in) dRho_dS, type(eos_type), pointer EOS, logical, intent(in), optional use_quadrature)
Set equation of state structure (EOS) to linear with given coefficients.
Note
This routine is primarily for testing and allows a local copy of the EOS_type (EOS argument) to be set to use the linear equation of state independent from the rest of the model.
Parameters
[in] rho_t0_s0 Density at T=0 degC and S=0 ppt (kg m-3)
[in] drho_dt Partial derivative of density with temperature (kg m-3 degC-1)
[in] drho_ds Partial derivative of density with salinity (kg m-3 ppt-1)
[in] use_quadrature Partial derivative of density with salinity (kg m-3 ppt-1)
eos Equation of state structure
Definition at line 576 of file MOM_EOS.F90.
References eos_linear, and mom_error_handler::mom_error().
   real,              intent(in) :: rho_t0_s0 !< Density at T=0 degC and S=0 ppt (kg m-3)
   real,              intent(in) :: drho_dt   !< Partial derivative of density with temperature (kg m-3 degC-1)
   real,              intent(in) :: drho_ds   !< Partial derivative of density with salinity (kg m-3 ppt-1)
   logical, optional, intent(in) :: use_quadrature !< Partial derivative of density with salinity (kg m-3 ppt-1)
   type(eos_type),    pointer    :: eos       !< Equation of state structure
   if (.not.associated(eos)) call mom_error(fatal, &
     "MOM_EOS.F90: EOS_use_linear() called with an unassociated EOS_type EOS.")
   eos%form_of_EOS = eos_linear
   eos%Compressible = .false.
   eos%Rho_T0_S0 = rho_t0_s0
   eos%dRho_dT = drho_dt
   eos%dRho_dS = drho_ds
   eos%EOS_quadrature = .false.
   if (present(use_quadrature)) eos%EOS_quadrature = use_quadrature
evaluate_shape_bilinear()
subroutine mom_eos::evaluate_shape_bilinear (real, intent(in) xi, real, intent(in) eta, real, dimension(4), intent(out) phi, real, dimension(4), intent(out) dphidxi, real, dimension(4), intent(out) dphideta) private
Definition at line 1907 of file MOM_EOS.F90.
Referenced by compute_integral_bilinear(), and compute_integral_quadratic().
   ! Arguments
   real, intent(in)                  :: xi, eta
   real, dimension(4), intent(out)   :: phi, dphidxi, dphideta
   ! The shape functions within the parent element are defined as shown
   ! here:
   !
   !    (-1,1) 2 o------------o 1 (1,1)
   !             |            |
   !             |            |
   !             |            |
   !             |            |
   !   (-1,-1) 3 o------------o 4 (1,-1)
   !
   phi(1) = 0.25 * ( 1 + xi ) * ( 1 + eta )
   phi(2) = 0.25 * ( 1 - xi ) * ( 1 + eta )
   phi(3) = 0.25 * ( 1 - xi ) * ( 1 - eta )
   phi(4) = 0.25 * ( 1 + xi ) * ( 1 - eta )
   dphidxi(1) = 0.25 * ( 1 + eta )
   dphidxi(2) = - 0.25 * ( 1 + eta )
   dphidxi(3) = - 0.25 * ( 1 - eta )
   dphidxi(4) = 0.25 * ( 1 - eta )
   dphideta(1) = 0.25 * ( 1 + xi )
   dphideta(2) = 0.25 * ( 1 - xi )
   dphideta(3) = - 0.25 * ( 1 - xi )
   dphideta(4) = - 0.25 * ( 1 + xi )
evaluate_shape_quadratic()
subroutine mom_eos::evaluate_shape_quadratic (real, intent(in) xi, real, intent(in) eta, real, dimension(9), intent(out) phi, real, dimension(9), intent(out) dphidxi, real, dimension(9), intent(out) dphideta) private
Definition at line 1945 of file MOM_EOS.F90.
Referenced by compute_integral_quadratic().
   ! Arguments
   real, intent(in)                  :: xi, eta
   real, dimension(9), intent(out)   :: phi, dphidxi, dphideta
   ! The quadratic shape functions within the parent element are
   ! defined as shown here:
   !
   !                 5 (0,1)
   !    (-1,1) 2 o------o------o 1 (1,1)
   !             |             |
   !             |   9 (0,0)   |
   !    (-1,0) 6 o      o      o 8 (1,0)
   !             |             |
   !             |             |
   !   (-1,-1) 3 o------o------o 4 (1,-1)
   !                 7 (0,-1)
   !
   phi      = 0.0
   dphidxi  = 0.0
   dphideta = 0.0
   phi(1) = 0.25 * xi * ( 1 + xi ) * eta * ( 1 + eta )
   phi(2) = - 0.25 * xi * ( 1 - xi ) * eta * ( 1 + eta )
   phi(3) = 0.25 * xi * ( 1 - xi ) * eta * ( 1 - eta )
   phi(4) = - 0.25 * xi * ( 1 + xi ) * eta * ( 1 - eta )
   phi(5) = 0.5 * ( 1 + xi ) * ( 1 - xi ) * eta * ( 1 + eta )
   phi(6) = - 0.5 * xi * ( 1 - xi ) * ( 1 - eta ) * ( 1 + eta )
   phi(7) = - 0.5 * ( 1 - xi ) * ( 1 + xi ) * eta * ( 1 - eta )
   phi(8) = 0.5 * xi * ( 1 + xi ) * ( 1 - eta ) * ( 1 + eta )
   phi(9) = ( 1 - xi ) * ( 1 + xi ) * ( 1 - eta ) * ( 1 + eta )
   !dphidxi(1) = 0.25 * ( 1 + 2*xi ) * eta * ( 1 + eta )
   !dphidxi(2) = - 0.25 * ( 1 - 2*xi ) * eta * ( 1 + eta )
   !dphidxi(3) = 0.25 * ( 1 - 2*xi ) * eta * ( 1 - eta )
   !dphidxi(4) = - 0.25 * ( 1 + 2*xi ) * eta * ( 1 - eta )
   !dphidxi(5) = - xi * eta * ( 1 + eta )
   !dphidxi(6) = - 0.5 * ( 1 - 2*xi ) * ( 1 - eta ) * ( 1 + eta )
   !dphidxi(7) = xi * eta * ( 1 - eta )
   !dphidxi(8) = 0.5 * ( 1 + 2*xi ) * ( 1 - eta ) * ( 1 + eta )
   !dphidxi(9) = - 2 * xi * ( 1 - eta ) * ( 1 + eta )
   !dphideta(1) = 0.25 * xi * ( 1 + xi ) * ( 1 + 2*eta )
   !dphideta(2) = - 0.25 * xi * ( 1 - xi ) * ( 1 + 2*eta )
   !dphideta(3) = 0.25 * xi * ( 1 - xi ) * ( 1 - 2*eta )
   !dphideta(4) = - 0.25 * xi * ( 1 + xi ) * ( 1 - 2*eta )
   !dphideta(5) = 0.5 * ( 1 + xi ) * ( 1 - xi ) * ( 1 + 2*eta )
   !dphideta(6) = xi * ( 1 - xi ) * eta
   !dphideta(7) = - 0.5 * ( 1 - xi ) * ( 1 + xi ) * ( 1 - 2*eta )
   !dphideta(8) = - xi * ( 1 + xi ) * eta
   !dphideta(9) = - 2 * ( 1 - xi ) * ( 1 + xi ) * eta
find_depth_of_pressure_in_cell()
subroutine, public mom_eos::find_depth_of_pressure_in_cell (real, intent(in) T_t, real, intent(in) T_b, real, intent(in) S_t, real, intent(in) S_b, real, intent(in) z_t, real, intent(in) z_b, real, intent(in) P_t, real, intent(in) P_tgt, real, intent(in) rho_ref, real, intent(in) G_e, type(eos_type), pointer EOS, real, intent(out) P_b, real, intent(out) z_out)
Find the depth at which the reconstructed pressure matches P_tgt.
Parameters
[in] t_t Potential temperatue at the cell top (degC)
[in] t_b Potential temperatue at the cell bottom (degC)
[in] s_t Salinity at the cell top (ppt)
[in] s_b Salinity at the cell bottom (ppt)
[in] z_t Absolute height of top of cell (m) (Boussinesq ????)
[in] z_b Absolute height of bottom of cell (m)
[in] p_t Anomalous pressure of top of cell, relative to g*rho_ref*z_t (Pa)
[in] p_tgt Target pressure at height z_out, relative to g*rho_ref*z_out (Pa)
[in] rho_ref Reference density with which calculation are anomalous to
[in] g_e Gravitational acceleration (m/s2)
eos Equation of state structure
[out] p_b Pressure at the bottom of the cell (Pa)
[out] z_out Absolute depth at which anomalous pressure = p_tgt (m)
Definition at line 1235 of file MOM_EOS.F90.
References frac_dp_at_pos().
   real,           intent(in)  :: t_t !< Potential temperatue at the cell top (degC)
   real,           intent(in)  :: t_b !< Potential temperatue at the cell bottom (degC)
   real,           intent(in)  :: s_t !< Salinity at the cell top (ppt)
   real,           intent(in)  :: s_b !< Salinity at the cell bottom (ppt)
   real,           intent(in)  :: z_t !< Absolute height of top of cell (m)   (Boussinesq ????)
   real,           intent(in)  :: z_b !< Absolute height of bottom of cell (m)
   real,           intent(in)  :: p_t !< Anomalous pressure of top of cell, relative to g*rho_ref*z_t (Pa)
   real,           intent(in)  :: p_tgt !< Target pressure at height z_out, relative to g*rho_ref*z_out (Pa)
   real,           intent(in)  :: rho_ref !< Reference density with which calculation are anomalous to
   real,           intent(in)  :: g_e !< Gravitational acceleration (m/s2)
   type(eos_type), pointer     :: eos !< Equation of state structure
   real,           intent(out) :: p_b !< Pressure at the bottom of the cell (Pa)
   real,           intent(out) :: z_out !< Absolute depth at which anomalous pressure = p_tgt (m)
   ! Local variables
   real :: top_weight, bottom_weight, rho_anom, w_left, w_right, gxrho, dz, dp, f_guess, f_l, f_r
   real :: pa, pa_left, pa_right, pa_tol ! Pressure anomalies, P = integral of g*(rho-rho_ref) dz
   gxrho = g_e * rho_ref
   ! Anomalous pressure difference across whole cell
   dp = frac_dp_at_pos(t_t, t_b, s_t, s_b, z_t, z_b, rho_ref, g_e, 1.0, eos)
   p_b = p_t + dp ! Anomalous pressure at bottom of cell
   if (p_tgt < p_t ) then
     z_out = z_t
     return
   endif
   if (p_tgt > p_b) then
     z_out = z_b
     return
   endif
   f_l = 0.
   pa_left = p_t - p_tgt ! Pa_left < 0
   f_r = 1.
   pa_right = p_b - p_tgt ! Pa_right > 0
   pa_tol = gxrho * 1.e-5
   f_guess = f_l - pa_left / ( pa_right -pa_left ) * ( f_r - f_l )
   pa = pa_right - pa_left ! To get into iterative loop
   do while ( abs(pa) > pa_tol )
     z_out = z_t + ( z_b - z_t ) * f_guess
     pa = frac_dp_at_pos(t_t, t_b, s_t, s_b, z_t, z_b, rho_ref, g_e, f_guess, eos) - ( p_tgt - p_t )
     if (pa<pa_left) then
       write(0,*) pa_left,pa,pa_right,p_t-p_tgt,p_b-p_tgt
       stop 'Blurgh! Too negative'
     elseif (pa<0.) then
       pa_left = pa
       f_l = f_guess
     elseif (pa>pa_right) then
       write(0,*) pa_left,pa,pa_right,p_t-p_tgt,p_b-p_tgt
       stop 'Blurgh! Too positive'
     elseif (pa>0.) then
       pa_right = pa
       f_r = f_guess
     else ! Pa == 0
       return
     endif
     f_guess = f_l - pa_left / ( pa_right -pa_left ) * ( f_r - f_l )
   enddo
frac_dp_at_pos()
real function mom_eos::frac_dp_at_pos (real, intent(in) T_t, real, intent(in) T_b, real, intent(in) S_t, real, intent(in) S_b, real, intent(in) z_t, real, intent(in) z_b, real, intent(in) rho_ref, real, intent(in) G_e, real, intent(in) pos, type(eos_type), pointer EOS) private
Returns change in anomalous pressure change from top to non-dimensional position pos between z_t and z_b.
Parameters
eos Equation of state structure
Definition at line 1304 of file MOM_EOS.F90.
References calculate_density_array().
Referenced by find_depth_of_pressure_in_cell().
   real,           intent(in) :: t_t, t_b, s_t, s_b, z_t, z_b, rho_ref, g_e, pos
   type(eos_type), pointer    :: eos !< Equation of state structure
   ! Local variables
   real, parameter :: c1_90 = 1.0/90.0  ! Rational constants.
   real :: dz, top_weight, bottom_weight, rho_ave
   real, dimension(5) :: t5, s5, p5, rho5
   integer :: n
   do n=1,5
     ! Evalute density at five quadrature points
     bottom_weight = 0.25*real(n-1) * pos
     top_weight = 1.0 - bottom_weight
     ! Salinity and temperature points are linearly interpolated
     s5(n) = top_weight * s_t + bottom_weight * s_b
     t5(n) = top_weight * t_t + bottom_weight * t_b
     p5(n) = ( top_weight * z_t + bottom_weight * z_b ) * ( g_e * rho_ref )
   enddo
   call calculate_density_array(t5, s5, p5, rho5, 1, 5, eos)
   rho5(:) = rho5(:) !- rho_ref ! Work with anomalies relative to rho_ref
   ! Use Boole's rule to estimate the average density
   rho_ave = c1_90*(7.0*(rho5(1)+rho5(5)) + 32.0*(rho5(2)+rho5(4)) + 12.0*rho5(3))
   dz = ( z_t - z_b ) * pos
   frac_dp_at_pos = g_e * dz * rho_ave
int_density_dz()
subroutine, public mom_eos::int_density_dz (real, dimension(hii%isd:hii%ied,hii%jsd:hii%jed), intent(in) T, real, dimension(hii%isd:hii%ied,hii%jsd:hii%jed), intent(in) S, real, dimension(hii%isd:hii%ied,hii%jsd:hii%jed), intent(in) z_t, real, dimension(hii%isd:hii%ied,hii%jsd:hii%jed), intent(in) z_b, real, intent(in) rho_ref, real, intent(in) rho_0, real, intent(in) G_e, type(hor_index_type), intent(in) HII, type(hor_index_type), intent(in) HIO, type(eos_type), pointer EOS, real, dimension(hio%isd:hio%ied,hio%jsd:hio%jed), intent(out) dpa, real, dimension(hio%isd:hio%ied,hio%jsd:hio%jed), intent(out), optional intz_dpa, real, dimension(hio%isdb:hio%iedb,hio%jsd:hio%jed), intent(out), optional intx_dpa, real, dimension(hio%isd:hio%ied,hio%jsdb:hio%jedb), intent(out), optional inty_dpa)
This subroutine calculates analytical and nearly-analytical integrals of pressure anomalies across layers, which are required for calculating the finite-volume form pressure accelerations in a Boussinesq model. The one potentially dodgy assumtion here is that rho_0 is used both in the denominator of the accelerations, and in the pressure used to calculated density (the latter being -z*rho_0*G_e). These two uses could be separated if need be.
Parameters
[in] hii Ocean horizontal index structures for the input arrays
[in] hio Ocean horizontal index structures for the output arrays
[in] t Potential temperature referenced to the surface (degC)
[in] s Salinity (PSU)
[in] z_t Height at the top of the layer in m.
[in] z_b Height at the bottom of the layer in m.
[in] rho_ref A mean density, in kg m-3, that is subtracted out to reduce the magnitude of each of the integrals. (The pressure is calculated as p~=-z*rho_0*G_e.)
[in] rho_0 A density, in kg m-3, that is used to calculate the pressure (as p~=-z*rho_0*G_e) used in the equation of state.
[in] g_e The Earth's gravitational acceleration, in m s-2.
eos Equation of state structure
[out] dpa The change in the pressure anomaly across the layer, in Pa.
[out] intz_dpa The integral through the thickness of the layer of the pressure anomaly relative to the anomaly at the top of the layer, in Pa m.
[out] intx_dpa The integral in x of the difference between the pressure anomaly at the top and bottom of the layer divided by the x grid spacing, in Pa.
[out] inty_dpa The integral in y of the difference between the pressure anomaly at the top and bottom of the layer divided by the y grid spacing, in Pa.
Definition at line 392 of file MOM_EOS.F90.
References eos_linear, eos_wright, int_density_dz_generic(), and mom_error_handler::mom_error().
Referenced by mom_diagnostics::calculate_vertical_integrals().
   !> Ocean horizontal index structures for the input arrays
     type(hor_index_type),            intent(in)  :: hii
   !> Ocean horizontal index structures for the output arrays
     type(hor_index_type),            intent(in)  :: hio
   !> Potential temperature referenced to the surface (degC)
     real, dimension(HII%isd:HII%ied,HII%jsd:HII%jed), intent(in)  :: t
   !> Salinity (PSU)
     real, dimension(HII%isd:HII%ied,HII%jsd:HII%jed), intent(in)  :: s
   !> Height at the top of the layer in m.
     real, dimension(HII%isd:HII%ied,HII%jsd:HII%jed), intent(in)  :: z_t
   !> Height at the bottom of the layer in m.
     real, dimension(HII%isd:HII%ied,HII%jsd:HII%jed), intent(in)  :: z_b
   !> A mean density, in kg m-3, that is subtracted out to reduce the magnitude
   !! of each of the integrals. (The pressure is calculated as p~=-z*rho_0*G_e.)
     real,                            intent(in)  :: rho_ref
   !> A density, in kg m-3, that is used to calculate the pressure
   !! (as p~=-z*rho_0*G_e) used in the equation of state.
     real,                            intent(in)  :: rho_0
   !> The Earth's gravitational acceleration, in m s-2.
     real,                            intent(in)  :: g_e
   !> Equation of state structure
     type(eos_type),                  pointer     :: eos
   !> The change in the pressure anomaly across the layer, in Pa.
     real, dimension(HIO%isd:HIO%ied,HIO%jsd:HIO%jed), intent(out) :: dpa
   !> The integral through the thickness of the layer of the pressure anomaly
   !! relative to the anomaly at the top of the layer, in Pa m.
     real, dimension(HIO%isd:HIO%ied,HIO%jsd:HIO%jed),  optional, intent(out) :: intz_dpa
   !> The integral in x of the difference between the pressure anomaly at the
   !! top and bottom of the layer divided by the x grid spacing, in Pa.
     real, dimension(HIO%IsdB:HIO%IedB,HIO%jsd:HIO%jed), optional, intent(out) :: intx_dpa
   !> The integral in y of the difference between the pressure anomaly at the
   !! top and bottom of the layer divided by the y grid spacing, in Pa.
     real, dimension(HIO%isd:HIO%ied,HIO%JsdB:HIO%JedB), optional, intent(out) :: inty_dpa
   if (.not.associated(eos)) call mom_error(fatal, &
     "int_density_dz called with an unassociated EOS_type EOS.")
   if (eos%EOS_quadrature) then
     call int_density_dz_generic(t, s, z_t, z_b, rho_ref, rho_0, g_e, hii, hio, &
                                 eos, dpa, intz_dpa, intx_dpa, inty_dpa)
   else ; select case (eos%form_of_EOS)
     case (eos_linear)
       call int_density_dz_linear(t, s, z_t, z_b, rho_ref, rho_0, g_e, hii, hio,  &
                                  eos%Rho_T0_S0, eos%dRho_dT, eos%dRho_dS, &
                                  dpa, intz_dpa, intx_dpa, inty_dpa)
     case (eos_wright)
       call int_density_dz_wright(t, s, z_t, z_b, rho_ref, rho_0, g_e, hii, hio,  &
                                        dpa, intz_dpa, intx_dpa, inty_dpa)
     case default
       call int_density_dz_generic(t, s, z_t, z_b, rho_ref, rho_0, g_e, hii, hio,  &
                                   eos, dpa, intz_dpa, intx_dpa, inty_dpa)
   end select ; endif
int_density_dz_generic()
subroutine mom_eos::int_density_dz_generic (real, dimension(hii%isd:hii%ied,hii%jsd:hii%jed), intent(in) T, real, dimension(hii%isd:hii%ied,hii%jsd:hii%jed), intent(in) S, real, dimension(hii%isd:hii%ied,hii%jsd:hii%jed), intent(in) z_t, real, dimension(hii%isd:hii%ied,hii%jsd:hii%jed), intent(in) z_b, real, intent(in) rho_ref, real, intent(in) rho_0, real, intent(in) G_e, type(hor_index_type), intent(in) HII, type(hor_index_type), intent(in) HIO, type(eos_type), pointer EOS, real, dimension(hio%isd:hio%ied,hio%jsd:hio%jed), intent(out) dpa, real, dimension(hio%isd:hio%ied,hio%jsd:hio%jed), intent(out), optional intz_dpa, real, dimension(hio%isdb:hio%iedb,hio%jsd:hio%jed), intent(out), optional intx_dpa, real, dimension(hio%isd:hio%ied,hio%jsdb:hio%jedb), intent(out), optional inty_dpa) private
Parameters
eos Equation of state structure
Definition at line 597 of file MOM_EOS.F90.
Referenced by int_density_dz().
   type(hor_index_type), intent(in)  :: hii, hio
   real, dimension(HII%isd:HII%ied,HII%jsd:HII%jed), &
                         intent(in)  :: t, s, z_t, z_b
   real,                 intent(in)  :: rho_ref, rho_0, g_e
   type(eos_type),       pointer     :: eos !< Equation of state structure
   real, dimension(HIO%isd:HIO%ied,HIO%jsd:HIO%jed), &
                         intent(out) :: dpa
   real, dimension(HIO%isd:HIO%ied,HIO%jsd:HIO%jed), &
               optional, intent(out) :: intz_dpa
   real, dimension(HIO%IsdB:HIO%IedB,HIO%jsd:HIO%jed), &
               optional, intent(out) :: intx_dpa
   real, dimension(HIO%isd:HIO%ied,HIO%JsdB:HIO%JedB), &
               optional, intent(out) :: inty_dpa
 !   This subroutine calculates (by numerical quadrature) integrals of
 ! pressure anomalies across layers, which are required for calculating the
 ! finite-volume form pressure accelerations in a Boussinesq model.  The one
 ! potentially dodgy assumtion here is that rho_0 is used both in the denominator
 ! of the accelerations, and in the pressure used to calculated density (the
 ! latter being -z*rho_0*G_e).  These two uses could be separated if need be.
 !
 ! Arguments: T - potential temperature relative to the surface in C.
 !  (in)      S - salinity in PSU.
 !  (in)      z_t - height at the top of the layer in m.
 !  (in)      z_b - height at the top of the layer in m.
 !  (in)      rho_ref - A mean density, in kg m-3, that is subtracted out to reduce
 !                    the magnitude of each of the integrals.
 !                    (The pressure is calucated as p~=-z*rho_0*G_e.)
 !  (in)      rho_0 - A density, in kg m-3, that is used to calculate the pressure
 !                    (as p~=-z*rho_0*G_e) used in the equation of state.
 !  (in)      G_e - The Earth's gravitational acceleration, in m s-2.
 !  (in)      G - The ocean's grid structure.
 !  (in)      EOS - type that selects the eqn of state.
 !  (out)     dpa - The change in the pressure anomaly across the layer,
 !                  in Pa.
 !  (out,opt) intz_dpa - The integral through the thickness of the layer of the
 !                       pressure anomaly relative to the anomaly at the top of
 !                       the layer, in Pa m.
 !  (out,opt) intx_dpa - The integral in x of the difference between the
 !                       pressure anomaly at the top and bottom of the layer
 !                       divided by the x grid spacing, in Pa.
 !  (out,opt) inty_dpa - The integral in y of the difference between the
 !                       pressure anomaly at the top and bottom of the layer
 !                       divided by the y grid spacing, in Pa.
   real :: t5(5), s5(5), p5(5), r5(5)
   real :: rho_anom
   real :: w_left, w_right, intz(5)
   real, parameter :: c1_90 = 1.0/90.0  ! Rational constants.
   real :: gxrho, i_rho
   real :: dz
   integer :: is, ie, js, je, isq, ieq, jsq, jeq, i, j, m, n, ioff, joff
   ioff = hio%idg_offset - hii%idg_offset
   joff = hio%jdg_offset - hii%jdg_offset
   ! These array bounds work for the indexing convention of the input arrays, but
   ! on the computational domain defined for the output arrays.
   isq = hio%IscB + ioff ; ieq = hio%IecB + ioff
   jsq = hio%JscB + joff ; jeq = hio%JecB + joff
   is = hio%isc + ioff ; ie = hio%iec + ioff
   js = hio%jsc + joff ; je = hio%jec + joff
   gxrho = g_e * rho_0
   i_rho = 1.0 / rho_0
   do j=jsq,jeq+1 ; do i=isq,ieq+1
     dz = z_t(i,j) - z_b(i,j)
     do n=1,5
       t5(n) = t(i,j) ; s5(n) = s(i,j)
       p5(n) = -gxrho*(z_t(i,j) - 0.25*real(n-1)*dz)
     enddo
     call calculate_density(t5, s5, p5, r5, 1, 5, eos)
     ! Use Bode's rule to estimate the pressure anomaly change.
     rho_anom = c1_90*(7.0*(r5(1)+r5(5)) + 32.0*(r5(2)+r5(4)) + 12.0*r5(3)) - &
                rho_ref
     dpa(i-ioff,j-joff) = g_e*dz*rho_anom
     ! Use a Bode's-rule-like fifth-order accurate estimate of the double integral of
     ! the pressure anomaly.
     if (present(intz_dpa)) intz_dpa(i-ioff,j-joff) = 0.5*g_e*dz**2 * &
           (rho_anom - c1_90*(16.0*(r5(4)-r5(2)) + 7.0*(r5(5)-r5(1))) )
   enddo ; enddo
   if (present(intx_dpa)) then ; do j=js,je ; do i=isq,ieq
     intz(1) = dpa(i-ioff,j-joff) ; intz(5) = dpa(i+1-ioff,j-joff)
     do m=2,4
       w_left = 0.25*real(5-m) ; w_right = 1.0-w_left
       dz = w_left*(z_t(i,j) - z_b(i,j)) + w_right*(z_t(i+1,j) - z_b(i+1,j))
       t5(1) = w_left*t(i,j) + w_right*t(i+1,j)
       s5(1) = w_left*s(i,j) + w_right*s(i+1,j)
       p5(1) = -gxrho*(w_left*z_t(i,j) + w_right*z_t(i+1,j))
       do n=2,5
         t5(n) = t5(1) ; s5(n) = s5(1)
         p5(n) = p5(n-1) + gxrho*0.25*dz
       enddo
       call calculate_density(t5, s5, p5, r5, 1, 5, eos)
     ! Use Bode's rule to estimate the pressure anomaly change.
       intz(m) = g_e*dz*( c1_90*(7.0*(r5(1)+r5(5)) + 32.0*(r5(2)+r5(4)) + &
                                 12.0*r5(3)) - rho_ref)
     enddo
     ! Use Bode's rule to integrate the bottom pressure anomaly values in x.
     intx_dpa(i-ioff,j-joff) = c1_90*(7.0*(intz(1)+intz(5)) + 32.0*(intz(2)+intz(4)) + &
                            12.0*intz(3))
   enddo ; enddo ; endif
   if (present(inty_dpa)) then ; do j=jsq,jeq ; do i=is,ie
     intz(1) = dpa(i-ioff,j-joff) ; intz(5) = dpa(i-ioff,j-joff+1)
     do m=2,4
       w_left = 0.25*real(5-m) ; w_right = 1.0-w_left
       dz = w_left*(z_t(i,j) - z_b(i,j)) + w_right*(z_t(i,j+1) - z_b(i,j+1))
       t5(1) = w_left*t(i,j) + w_right*t(i,j+1)
       s5(1) = w_left*s(i,j) + w_right*s(i,j+1)
       p5(1) = -gxrho*(w_left*z_t(i,j) + w_right*z_t(i,j+1))
       do n=2,5
         t5(n) = t5(1) ; s5(n) = s5(1)
         p5(n) = p5(n-1) + gxrho*0.25*dz
       enddo
       call calculate_density(t5, s5, p5, r5, 1, 5, eos)
     ! Use Bode's rule to estimate the pressure anomaly change.
       intz(m) = g_e*dz*( c1_90*(7.0*(r5(1)+r5(5)) + 32.0*(r5(2)+r5(4)) + &
                                 12.0*r5(3)) - rho_ref)
     enddo
     ! Use Bode's rule to integrate the values.
     inty_dpa(i-ioff,j-joff) = c1_90*(7.0*(intz(1)+intz(5)) + 32.0*(intz(2)+intz(4)) + &
                            12.0*intz(3))
   enddo ; enddo ; endif
int_density_dz_generic_cell()
subroutine mom_eos::int_density_dz_generic_cell (real, dimension(2), intent(in) T_t_arg, real, dimension(2), intent(in) T_b_arg, real, dimension(2), intent(in) S_t_arg, real, dimension(2), intent(in) S_b_arg, real, dimension(2), intent(inout) z_t_arg, real, dimension(2), intent(inout) z_b_arg, real, dimension(2), intent(in) depth, real, intent(in) rho_ref, real, intent(in) rho_0, real, intent(in) G_e, type(eos_type), pointer EOS, real, dimension(2), intent(out) dpa, real, dimension(2), intent(out) intz_dpa, real, intent(out) intx_dpa, real, intent(out) inty_dpa) private
Parameters
eos Equation of state structure
Definition at line 733 of file MOM_EOS.F90.
   ! Arguments
   real, dimension(2), intent(in)     :: t_t_arg, t_b_arg, s_t_arg, s_b_arg
   real, dimension(2), intent(inout)  :: z_t_arg, z_b_arg
   real, dimension(2), intent(in)     :: depth
   real, intent(in)                   :: rho_ref, rho_0, g_e
   type(eos_type), pointer            :: eos !< Equation of state structure
   real, dimension(2), intent(out)    :: dpa
   real, dimension(2), intent(out)    :: intz_dpa
   real, intent(out)                  :: intx_dpa
   real, intent(out)                  :: inty_dpa
   ! Local variables
   real    :: t_t(2), t_b(2)             ! top and bottom temperatures
   real    :: s_t(2), s_b(2)             ! top and bottom salinities
   real    :: z_t(2), z_b(2)             ! top and bottom heights
   real    :: h1, h2                     ! cell thicknesses
   real    :: t5(5), s5(5), p5(5), r5(5) ! temperature, salinity, pressure and
                                         ! density at quadrature points
   real    :: rho_anom
   real    :: w_left, w_right, intz(5)
   real    :: gxrho
   real    :: dz
   real    :: weight_t, weight_b
   real    :: dmin ! minimum depth
   integer :: n, m
   real, parameter :: c1_90 = 1.0/90.0 ! Rational constants
   gxrho = g_e * rho_0
   ! -------------------------------------------------------
   ! 0. Modify cell geometry to take topography into account
   ! -------------------------------------------------------
   dmin = min( depth(1), depth(2) )
   z_b(1) = max( z_b_arg(1), -dmin )
   z_b(2) = max( z_b_arg(2), -dmin )
   if ( z_b(1) .GT. z_t_arg(1) ) z_b(1) = z_t_arg(1)
   if ( z_b(2) .GT. z_t_arg(2) ) z_b(2) = z_t_arg(2)
   ! We do not modify the heights at the top of the cell
   z_t = z_t_arg
   h1 = z_t(1) - z_b(1)
   h2 = z_t(2) - z_b(2)
   ! Compute new salinities and temperatures at the bottom
   s_b(1) = s_t_arg(1) + (s_b_arg(1)-s_t_arg(1)) * (h1 / (z_t_arg(1)-z_b_arg(1)))
   s_b(2) = s_t_arg(2) + (s_b_arg(2)-s_t_arg(2)) * (h2 / (z_t_arg(2)-z_b_arg(2)))
   t_b(1) = t_t_arg(1) + (t_b_arg(1)-t_t_arg(1)) * (h1 / (z_t_arg(1)-z_b_arg(1)))
   t_b(2) = t_t_arg(2) + (t_b_arg(2)-t_t_arg(2)) * (h2 / (z_t_arg(2)-z_b_arg(2)))
   ! Temperatures and salinities at the top remain the same
   s_t = s_t_arg
   t_t = t_t_arg
   ! Save layer bottom interface heights for use outside this routine
   z_b_arg = z_b
   ! ----------------------------------------
   ! 1. Compute left side (vertical) integral
   ! ----------------------------------------
   dz = z_t(1) - z_b(1)
   do n = 1,5
     weight_t = 0.25 * real(5-n)
     weight_b = 1.0 - weight_t
     s5(n) = weight_t * s_t(1) + weight_b * s_b(1)
     t5(n) = weight_t * t_t(1) + weight_b * t_b(1)
     p5(n) = -gxrho*(z_t(1) - 0.25*real(n-1)*dz)
   enddo
   call calculate_density(t5, s5, p5, r5, 1, 5, eos)
   ! Use Boole's rule to estimate the pressure anomaly change.
   rho_anom = c1_90*(7.0*(r5(1)+r5(5)) + 32.0*(r5(2)+r5(4)) + 12.0*r5(3)) - rho_ref
   dpa(1) = g_e*dz*rho_anom
   ! Use a Bode's-rule-like fifth-order accurate estimate of the
   ! double integral of the pressure anomaly.
   r5 = r5 - rho_ref
   intz_dpa(1) = 0.5*g_e*dz**2 * &
   (rho_anom - c1_90*(16.0*(r5(4)-r5(2)) + 7.0*(r5(5)-r5(1))) )
   ! -----------------------------------------
   ! 2. Compute right side (vertical) integral
   ! -----------------------------------------
   dz = z_t(2) - z_b(2)
   do n = 1,5
     weight_t = 0.25 * real(5-n)
     weight_b = 1.0 - weight_t
     s5(n) = weight_t * s_t(2) + weight_b * s_b(2)
     t5(n) = weight_t * t_t(2) + weight_b * t_b(2)
     p5(n) = -gxrho*(z_t(2) - 0.25*real(n-1)*dz)
   enddo
   call calculate_density(t5, s5, p5, r5, 1, 5, eos)
   ! Use Boole's rule to estimate the pressure anomaly change.
   rho_anom = c1_90*(7.0*(r5(1)+r5(5)) + 32.0*(r5(2)+r5(4)) + 12.0*r5(3)) - rho_ref
   dpa(2) = g_e*dz*rho_anom
   ! Use a Bode's-rule-like fifth-order accurate estimate of the
   ! double integral of the pressure anomaly.
   r5 = r5 - rho_ref
   intz_dpa(2) = 0.5*g_e*dz**2 * &
   (rho_anom - c1_90*(16.0*(r5(4)-r5(2)) + 7.0*(r5(5)-r5(1))) )
   ! ----------------------
   ! 3. Compute x-intergral
   ! ----------------------
   !if (present(intx_dpa)) then
     intz(1) = dpa(1)
     intz(5) = dpa(2)
     do m = 2,4
       w_left = 0.25*real(5-m)
       w_right = 1.0-w_left
       dz = w_left*(z_t(1) - z_b(1)) + w_right*(z_t(2) - z_b(2))
       t5(1) = w_left*t_t(1) + w_right*t_t(2)
       t5(5) = w_left*t_b(1) + w_right*t_b(2)
       s5(1) = w_left*s_t(1) + w_right*s_t(2)
       s5(5) = w_left*s_b(1) + w_right*s_b(2)
       p5(1) = -gxrho*(w_left*z_t(1) + w_right*z_t(2))
       do n=2,5
         p5(n) = p5(n-1) + gxrho*0.25*dz
       enddo
       do n = 1,5
         weight_t = 0.25 * real(5-n)
         weight_b = 1.0 - weight_t
         s5(n) = weight_t * s5(1) + weight_b * s5(5)
       enddo
       call calculate_density (t5, s5, p5, r5, 1, 5, eos)
       ! Use Bode's rule to estimate the pressure anomaly change.
       intz(m) = g_e*dz*( c1_90*(7.0*(r5(1)+r5(5)) + 32.0*(r5(2)+r5(4)) + &
                                 12.0*r5(3)) - rho_ref)
     enddo
     ! Use Bode's rule to integrate the bottom pressure anomaly values in x.
     intx_dpa = c1_90*(7.0*(intz(1)+intz(5)) + 32.0*(intz(2)+intz(4)) + &
                       12.0*intz(3))
   !end if ! check if intx_dpa is present
   ! ---------------------
   ! 4. Compute y-intergal
   ! ---------------------
   !if (present(inty_dpa)) then
     intz(1) = dpa(1)
     intz(5) = dpa(2)
     do m=2,4
       w_left = 0.25*real(5-m)
       w_right = 1.0-w_left
       dz = w_left*(z_t(1) - z_b(2)) + w_right*(z_t(1) - z_b(2))
       s5(1) = w_left*s_t(1) + w_right*s_t(2)
       s5(5) = w_left*s_b(1) + w_right*s_b(2)
       s5(1) = w_left*s_t(1) + w_right*s_t(2)
       s5(5) = w_left*s_b(1) + w_right*s_b(2)
       p5(1) = -gxrho*(w_left*z_t(1) + w_right*z_t(2))
       do n=2,5
         p5(n) = p5(n-1) + gxrho*0.25*dz
       enddo
       do n=1,5
         weight_t = 0.25 * real(5-n)
         weight_b = 1.0 - weight_t
         s5(n) = weight_t * s5(1) + weight_b * s5(5)
       enddo
       call calculate_density(t5, s5, p5, r5, 1, 5, eos)
       ! Use Bode's rule to estimate the pressure anomaly change.
       intz(m) = g_e*dz*( c1_90*(7.0*(r5(1)+r5(5)) + 32.0*(r5(2)+r5(4)) + &
                          12.0*r5(3)) - rho_ref)
       enddo
       ! Use Bode's rule to integrate the values.
       inty_dpa = c1_90*(7.0*(intz(1)+intz(5)) + 32.0*(intz(2)+intz(4)) + &
                         12.0*intz(3))
   !end if ! check if inty_dpa is present
int_density_dz_generic_plm()
subroutine, public mom_eos::int_density_dz_generic_plm (real, dimension(hii%isd:hii%ied,hii%jsd:hii%jed), intent(in) T_t, real, dimension(hii%isd:hii%ied,hii%jsd:hii%jed), intent(in) T_b, real, dimension(hii%isd:hii%ied,hii%jsd:hii%jed), intent(in) S_t, real, dimension(hii%isd:hii%ied,hii%jsd:hii%jed), intent(in) S_b, real, dimension(hii%isd:hii%ied,hii%jsd:hii%jed), intent(in) z_t, real, dimension(hii%isd:hii%ied,hii%jsd:hii%jed), intent(in) z_b, real, intent(in) rho_ref, real, intent(in) rho_0, real, intent(in) G_e, real, intent(in) H_subroundoff, real, dimension(hii%isd:hii%ied,hii%jsd:hii%jed), intent(in) bathyT, type(hor_index_type), intent(in) HII, type(hor_index_type), intent(in) HIO, type(eos_type), pointer EOS, real, dimension(hio%isd:hio%ied,hio%jsd:hio%jed), intent(out) dpa, real, dimension(hio%isd:hio%ied,hio%jsd:hio%jed), intent(out), optional intz_dpa, real, dimension(hio%isdb:hio%iedb,hio%jsd:hio%jed), intent(out), optional intx_dpa, real, dimension(hio%isd:hio%ied,hio%jsdb:hio%jedb), intent(out), optional inty_dpa, logical, intent(in), optional useMassWghtInterp)
Parameters
eos Equation of state structure
Definition at line 938 of file MOM_EOS.F90.
References calculate_density_array().
   type(hor_index_type),   intent(in)  :: hii, hio
   real, dimension(HII%isd:HII%ied,HII%jsd:HII%jed), &
                           intent(in)  :: t_t, t_b, s_t, s_b, z_t, z_b
   real,                   intent(in)  :: rho_ref, rho_0, g_e, h_subroundoff
   real, dimension(HII%isd:HII%ied,HII%jsd:HII%jed),  intent(in)  :: bathyt
   type(eos_type),         pointer     :: eos !< Equation of state structure
   real, dimension(HIO%isd:HIO%ied,HIO%jsd:HIO%jed), &
                           intent(out) :: dpa
   real, dimension(HIO%isd:HIO%ied,HIO%jsd:HIO%jed), &
                 optional, intent(out) :: intz_dpa
   real, dimension(HIO%IsdB:HIO%IedB,HIO%jsd:HIO%jed), &
                 optional, intent(out) :: intx_dpa
   real, dimension(HIO%isd:HIO%ied,HIO%JsdB:HIO%JedB), &
                 optional, intent(out) :: inty_dpa
   logical,      optional, intent(in)  :: usemasswghtinterp
 ! This subroutine calculates (by numerical quadrature) integrals of
 ! pressure anomalies across layers, which are required for calculating the
 ! finite-volume form pressure accelerations in a Boussinesq model.  The one
 ! potentially dodgy assumtion here is that rho_0 is used both in the denominator
 ! of the accelerations, and in the pressure used to calculated density (the
 ! latter being -z*rho_0*G_e).  These two uses could be separated if need be.
 !
 ! It is assumed that the salinity and temperature profiles are linear in the
 ! vertical. The top and bottom values within each layer are provided and
 ! a linear interpolation is used to compute intermediate values.
 !
 ! Arguments: T - potential temperature relative to the surface in C
 !                (the 't' and 'b' subscripts refer to the values at
 !                 the top and the bottom of each layer)
 !  (in)      S - salinity in PSU.
 !                (the 't' and 'b' subscripts refer to the values at
 !                 the top and the bottom of each layer)
 !  (in)      z_t - height at the top of the layer in m.
 !  (in)      z_b - height at the top of the layer in m.
 !  (in)      rho_ref - A mean density, in kg m-3, that is subtracted out to reduce
 !                    the magnitude of each of the integrals.
 !                    (The pressure is calucated as p~=-z*rho_0*G_e.)
 !  (in)      rho_0 - A density, in kg m-3, that is used to calculate the pressure
 !                    (as p~=-z*rho_0*G_e) used in the equation of state.
 !  (in)      G_e - The Earth's gravitational acceleration, in m s-2.
 !  (in)      G - The ocean's grid structure.
 !  (in)      form_of_eos - integer that selects the eqn of state.
 !  (out)     dpa - The change in the pressure anomaly across the layer,
 !                  in Pa.
 !  (out,opt) intz_dpa - The integral through the thickness of the layer of the
 !                       pressure anomaly relative to the anomaly at the top of
 !                       the layer, in Pa m.
 !  (out,opt) intx_dpa - The integral in x of the difference between the
 !                       pressure anomaly at the top and bottom of the layer
 !                       divided by the x grid spacing, in Pa.
 !  (out,opt) inty_dpa - The integral in y of the difference between the
 !                       pressure anomaly at the top and bottom of the layer
 !                       divided by the y grid spacing, in Pa.
 !  (in,opt) useMassWghtInterp - If true, uses mass weighting to interpolate
 !                       T/S for top and bottom integrals.
   real :: t5((5*hio%iscb+1):(5*(hio%iecb+2)))
   real :: s5((5*hio%iscb+1):(5*(hio%iecb+2)))
   real :: p5((5*hio%iscb+1):(5*(hio%iecb+2)))
   real :: r5((5*hio%iscb+1):(5*(hio%iecb+2)))
   real :: u5((5*hio%iscb+1):(5*(hio%iecb+2)))
   real :: t15((15*hio%iscb+1):(15*(hio%iecb+1)))
   real :: s15((15*hio%iscb+1):(15*(hio%iecb+1)))
   real :: p15((15*hio%iscb+1):(15*(hio%iecb+1)))
   real :: r15((15*hio%iscb+1):(15*(hio%iecb+1)))
   real :: wt_t(5), wt_b(5)
   real :: rho_anom
   real :: w_left, w_right, intz(5)
   real, parameter :: c1_90 = 1.0/90.0  ! Rational constants.
   real :: gxrho, i_rho
   real :: dz(hio%iscb:hio%iecb+1), dz_x(5,hio%iscb:hio%iecb), dz_y(5,hio%isc:hio%iec)
   real :: weight_t, weight_b, hwght, massweightingtoggle
   real :: ttl, tbl, ttr, tbr, stl, sbl, str, sbr, hl, hr, idenom
   integer :: isq, ieq, jsq, jeq, i, j, m, n
   integer :: iin, jin, ioff, joff
   integer :: pos
   ioff = hio%idg_offset - hii%idg_offset
   joff = hio%jdg_offset - hii%jdg_offset
   isq = hio%IscB ; ieq = hio%IecB ; jsq = hio%JscB ; jeq = hio%JecB
   gxrho = g_e * rho_0
   i_rho = 1.0 / rho_0
   massweightingtoggle = 0.
   if (present(usemasswghtinterp)) then
     if (usemasswghtinterp) massweightingtoggle = 1.
   endif
   do n = 1, 5
     wt_t(n) = 0.25 * real(5-n)
     wt_b(n) = 1.0 - wt_t(n)
   enddo
   ! =============================
   ! 1. Compute vertical integrals
   ! =============================
   do j=jsq,jeq+1
     jin = j+joff
     do i = isq,ieq+1 ; iin = i+ioff
       dz(i) = z_t(iin,jin) - z_b(iin,jin)
       do n=1,5
         p5(i*5+n) = -gxrho*(z_t(iin,jin) - 0.25*real(n-1)*dz(i))
         ! Salinity and temperature points are linearly interpolated
         s5(i*5+n) = wt_t(n) * s_t(iin,jin) + wt_b(n) * s_b(iin,jin)
         t5(i*5+n) = wt_t(n) * t_t(iin,jin) + wt_b(n) * t_b(iin,jin)
       enddo
     enddo
     call calculate_density_array(t5, s5, p5, r5, 1, (ieq-isq+2)*5, eos )
     u5 = r5 - rho_ref
     do i=isq,ieq+1 ; iin = i+ioff
     ! Use Bode's rule to estimate the pressure anomaly change.
       rho_anom = c1_90*(7.0*(r5(i*5+1)+r5(i*5+5)) + 32.0*(r5(i*5+2)+r5(i*5+4)) + 12.0*r5(i*5+3)) - &
            rho_ref
       dpa(i,j) = g_e*dz(i)*rho_anom
       if (present(intz_dpa)) then
       ! Use a Bode's-rule-like fifth-order accurate estimate of
       ! the double integral of the pressure anomaly.
         intz_dpa(i,j) = 0.5*g_e*dz(i)**2 * &
                 (rho_anom - c1_90*(16.0*(u5(i*5+4)-u5(i*5+2)) + 7.0*(u5(i*5+5)-u5(i*5+1))) )
       endif
     enddo
   enddo ! end loops on j
   ! ==================================================
   ! 2. Compute horizontal integrals in the x direction
   ! ==================================================
   if (present(intx_dpa)) then ; do j=hio%jsc,hio%jec ; jin = j+joff
      do i=isq,ieq ; iin = i+ioff
     ! Corner values of T and S
     ! hWght is the distance measure by which the cell is violation of
     ! hydrostatic consistency. For large hWght we bias the interpolation
     ! of T,S along the top and bottom integrals, almost like thickness
     ! weighting.
     ! Note: To work in terrain following coordinates we could offset
     ! this distance by the layer thickness to replicate other models.
     hwght = massweightingtoggle * &
             max(0., -bathyt(iin,jin)-z_t(iin+1,jin), -bathyt(iin+1,jin)-z_t(iin,jin))
     if (hwght > 0.) then
       hl = (z_t(iin,jin) - z_b(iin,jin)) + h_subroundoff
       hr = (z_t(iin+1,jin) - z_b(iin+1,jin)) + h_subroundoff
       hwght = hwght * ( (hl-hr)/(hl+hr) )**2
       idenom = 1./( hwght*(hr + hl) + hl*hr )
       ttl = ( (hwght*hr)*t_t(iin+1,jin) + (hwght*hl + hr*hl)*t_t(iin,jin) ) * idenom
       ttr = ( (hwght*hl)*t_t(iin,jin) + (hwght*hr + hr*hl)*t_t(iin+1,jin) ) * idenom
       tbl = ( (hwght*hr)*t_b(iin+1,jin) + (hwght*hl + hr*hl)*t_b(iin,jin) ) * idenom
       tbr = ( (hwght*hl)*t_b(iin,jin) + (hwght*hr + hr*hl)*t_b(iin+1,jin) ) * idenom
       stl = ( (hwght*hr)*s_t(iin+1,jin) + (hwght*hl + hr*hl)*s_t(iin,jin) ) * idenom
       str = ( (hwght*hl)*s_t(iin,jin) + (hwght*hr + hr*hl)*s_t(iin+1,jin) ) * idenom
       sbl = ( (hwght*hr)*s_b(iin+1,jin) + (hwght*hl + hr*hl)*s_b(iin,jin) ) * idenom
       sbr = ( (hwght*hl)*s_b(iin,jin) + (hwght*hr + hr*hl)*s_b(iin+1,jin) ) * idenom
     else
       ttl = t_t(iin,jin); tbl = t_b(iin,jin); ttr = t_t(iin+1,jin); tbr = t_b(iin+1,jin)
       stl = s_t(iin,jin); sbl = s_b(iin,jin); str = s_t(iin+1,jin); sbr = s_b(iin+1,jin)
     endif
     do m=2,4
            w_left = 0.25*real(5-m) ; w_right = 1.0-w_left
            dz_x(m,i) = w_left*(z_t(iin,jin) - z_b(iin,jin)) + w_right*(z_t(iin+1,jin) - z_b(iin+1,jin))
       ! Salinity and temperature points are linearly interpolated in
       ! the horizontal. The subscript (1) refers to the top value in
       ! the vertical profile while subscript (5) refers to the bottom
       ! value in the vertical profile.
            pos = i*15+(m-2)*5
       t15(pos+1) = w_left*ttl + w_right*ttr
       t15(pos+5) = w_left*tbl + w_right*tbr
       s15(pos+1) = w_left*stl + w_right*str
       s15(pos+5) = w_left*sbl + w_right*sbr
       p15(pos+1) = -gxrho*(w_left*z_t(iin,jin) + w_right*z_t(iin+1,jin))
       ! Pressure
       do n=2,5
               p15(pos+n) = p15(pos+n-1) + gxrho*0.25*dz_x(m,i)
       enddo
       ! Salinity and temperature (linear interpolation in the vertical)
            do n=2,4
         weight_t = 0.25 * real(5-n)
         weight_b = 1.0 - weight_t
         s15(pos+n) = weight_t * s15(pos+1) + weight_b * s15(pos+5)
         t15(pos+n) = weight_t * t15(pos+1) + weight_b * t15(pos+5)
       enddo
     enddo
     enddo
     call calculate_density(t15, s15, p15, r15, 1, 15*(ieq-isq+1), eos)
     do i=isq,ieq ; iin = i+ioff
        intz(1) = dpa(i,j) ; intz(5) = dpa(i+1,j)
       ! Use Bode's rule to estimate the pressure anomaly change.
       do m = 2,4
           pos = i*15+(m-2)*5
           intz(m) = g_e*dz_x(m,i)*( c1_90*(7.0*(r15(pos+1)+r15(pos+5)) + 32.0*(r15(pos+2)+r15(pos+4)) + &
                             12.0*r15(pos+3)) - rho_ref)
       enddo
       ! Use Bode's rule to integrate the bottom pressure anomaly values in x.
       intx_dpa(i,j) = c1_90*(7.0*(intz(1)+intz(5)) + 32.0*(intz(2)+intz(4)) + &
                              12.0*intz(3))
     enddo
   enddo ; endif
   ! ==================================================
   ! 3. Compute horizontal integrals in the y direction
   ! ==================================================
   if (present(inty_dpa)) then ; do j=jsq,jeq ; jin = j+joff
     do i=hio%isc,hio%iec ; iin = i+ioff
     ! Corner values of T and S
     ! hWght is the distance measure by which the cell is violation of
     ! hydrostatic consistency. For large hWght we bias the interpolation
     ! of T,S along the top and bottom integrals, almost like thickness
     ! weighting.
     ! Note: To work in terrain following coordinates we could offset
     ! this distance by the layer thickness to replicate other models.
       hwght = massweightingtoggle * &
               max(0., -bathyt(i,j)-z_t(iin,jin+1), -bathyt(i,j+1)-z_t(iin,jin))
       if (hwght > 0.) then
         hl = (z_t(iin,jin) - z_b(iin,jin)) + h_subroundoff
         hr = (z_t(iin,jin+1) - z_b(iin,jin+1)) + h_subroundoff
         hwght = hwght * ( (hl-hr)/(hl+hr) )**2
         idenom = 1./( hwght*(hr + hl) + hl*hr )
         ttl = ( (hwght*hr)*t_t(iin,jin+1) + (hwght*hl + hr*hl)*t_t(iin,jin) ) * idenom
         ttr = ( (hwght*hl)*t_t(iin,jin) + (hwght*hr + hr*hl)*t_t(iin,jin+1) ) * idenom
         tbl = ( (hwght*hr)*t_b(iin,jin+1) + (hwght*hl + hr*hl)*t_b(iin,jin) ) * idenom
         tbr = ( (hwght*hl)*t_b(iin,jin) + (hwght*hr + hr*hl)*t_b(iin,jin+1) ) * idenom
         stl = ( (hwght*hr)*s_t(iin,jin+1) + (hwght*hl + hr*hl)*s_t(iin,jin) ) * idenom
         str = ( (hwght*hl)*s_t(iin,jin) + (hwght*hr + hr*hl)*s_t(iin,jin+1) ) * idenom
         sbl = ( (hwght*hr)*s_b(iin,jin+1) + (hwght*hl + hr*hl)*s_b(iin,jin) ) * idenom
         sbr = ( (hwght*hl)*s_b(iin,jin) + (hwght*hr + hr*hl)*s_b(iin,jin+1) ) * idenom
       else
         ttl = t_t(iin,jin); tbl = t_b(iin,jin); ttr = t_t(iin,jin+1); tbr = t_b(iin,jin+1)
         stl = s_t(iin,jin); sbl = s_b(iin,jin); str = s_t(iin,jin+1); sbr = s_b(iin,jin+1)
       endif
       do m=2,4
         w_left = 0.25*real(5-m) ; w_right = 1.0-w_left
         dz_y(m,i) = w_left*(z_t(iin,jin) - z_b(iin,jin)) + w_right*(z_t(iin,jin+1) - z_b(iin,jin+1))
         ! Salinity and temperature points are linearly interpolated in
         ! the horizontal. The subscript (1) refers to the top value in
         ! the vertical profile while subscript (5) refers to the bottom
         ! value in the vertical profile.
         pos = i*15+(m-2)*5
         t15(pos+1) = w_left*ttl + w_right*ttr
         t15(pos+5) = w_left*tbl + w_right*tbr
         s15(pos+1) = w_left*stl + w_right*str
         s15(pos+5) = w_left*sbl + w_right*sbr
         p15(pos+1) = -gxrho*(w_left*z_t(iin,jin) + w_right*z_t(iin,jin+1))
         ! Pressure
         do n=2,5 ; p15(pos+n) = p15(pos+n-1) + gxrho*0.25*dz_y(m,i) ; enddo
         ! Salinity and temperature (linear interpolation in the vertical)
         do n=2,4
           weight_t = 0.25 * real(5-n)
           weight_b = 1.0 - weight_t
           s15(pos+n) = weight_t * s15(pos+1) + weight_b * s15(pos+5)
           t15(pos+n) = weight_t * t15(pos+1) + weight_b * t15(pos+5)
         enddo
       enddo
     enddo
     call calculate_density_array(t15(15*hio%isc+1:), s15(15*hio%isc+1:), p15(15*hio%isc+1:), &
                                  r15(15*hio%isc+1:), 1, 15*(hio%iec-hio%isc+1), eos)
     do i=hio%isc,hio%iec ; iin = i+ioff
       intz(1) = dpa(i,j) ; intz(5) = dpa(i,j+1)
       ! Use Bode's rule to estimate the pressure anomaly change.
       do m = 2,4
         pos = i*15+(m-2)*5
         intz(m) = g_e*dz_y(m,i)*( c1_90*(7.0*(r15(pos+1)+r15(pos+5)) + &
                                          32.0*(r15(pos+2)+r15(pos+4)) + &
                                          12.0*r15(pos+3)) - rho_ref)
       enddo
       ! Use Bode's rule to integrate the values.
       inty_dpa(i,j) = c1_90*(7.0*(intz(1)+intz(5)) + 32.0*(intz(2)+intz(4)) + &
                              12.0*intz(3))
     enddo
   enddo ; endif
int_density_dz_generic_plm_analytic()
subroutine, public mom_eos::int_density_dz_generic_plm_analytic (real, dimension(hi%isd:hi%ied,hi%jsd:hi%jed), intent(in) T_t, real, dimension(hi%isd:hi%ied,hi%jsd:hi%jed), intent(in) T_b, real, dimension(hi%isd:hi%ied,hi%jsd:hi%jed), intent(in) S_t, real, dimension(hi%isd:hi%ied,hi%jsd:hi%jed), intent(in) S_b, real, dimension(hi%isd:hi%ied,hi%jsd:hi%jed), intent(in) z_t, real, dimension(hi%isd:hi%ied,hi%jsd:hi%jed), intent(in) z_b, real, intent(in) rho_ref, real, intent(in) rho_0, real, intent(in) G_e, type(hor_index_type), intent(in) HI, type(eos_type), pointer EOS, real, dimension(hi%isd:hi%ied,hi%jsd:hi%jed), intent(out) dpa, real, dimension(hi%isd:hi%ied,hi%jsd:hi%jed), intent(out), optional intz_dpa, real, dimension(hi%isdb:hi%iedb,hi%jsd:hi%jed), intent(out), optional intx_dpa, real, dimension(hi%isd:hi%ied,hi%jsdb:hi%jedb), intent(out), optional inty_dpa)
Parameters
eos Equation of state structure
Definition at line 1591 of file MOM_EOS.F90.
References compute_integral_bilinear().
   type(hor_index_type), intent(in)  :: hi
   real, dimension(HI%isd:HI%ied,HI%jsd:HI%jed), &
                         intent(in)  :: t_t, t_b, s_t, s_b, z_t, z_b
   real,                 intent(in)  :: rho_ref, rho_0, g_e
   type(eos_type),       pointer     :: eos !< Equation of state structure
   real, dimension(HI%isd:HI%ied,HI%jsd:HI%jed), &
                         intent(out) :: dpa
   real, dimension(HI%isd:HI%ied,HI%jsd:HI%jed), &
               optional, intent(out) :: intz_dpa
   real, dimension(HI%IsdB:HI%IedB,HI%jsd:HI%jed), &
               optional, intent(out) :: intx_dpa
   real, dimension(HI%isd:HI%ied,HI%JsdB:HI%JedB), &
               optional, intent(out) :: inty_dpa
 ! This subroutine calculates (by numerical quadrature) integrals of
 ! pressure anomalies across layers, which are required for calculating the
 ! finite-volume form pressure accelerations in a Boussinesq model.  The one
 ! potentially dodgy assumtion here is that rho_0 is used both in the denominator
 ! of the accelerations, and in the pressure used to calculated density (the
 ! latter being -z*rho_0*G_e).  These two uses could be separated if need be.
 !
 ! It is assumed that the salinity and temperature profiles are linear in the
 ! vertical. The top and bottom values within each layer are provided and
 ! a linear interpolation is used to compute intermediate values.
 !
 ! Arguments: T - potential temperature relative to the surface in C
 !                (the 't' and 'b' subscripts refer to the values at
 !                 the top and the bottom of each layer)
 !  (in)      S - salinity in PSU.
 !                (the 't' and 'b' subscripts refer to the values at
 !                 the top and the bottom of each layer)
 !  (in)      z_t - height at the top of the layer in m.
 !  (in)      z_b - height at the top of the layer in m.
 !  (in)      rho_ref - A mean density, in kg m-3, that is subtracted out to reduce
 !                    the magnitude of each of the integrals.
 !                    (The pressure is calucated as p~=-z*rho_0*G_e.)
 !  (in)      rho_0 - A density, in kg m-3, that is used to calculate the pressure
 !                    (as p~=-z*rho_0*G_e) used in the equation of state.
 !  (in)      G_e - The Earth's gravitational acceleration, in m s-2.
 !  (in)      HI - The ocean's horizontal index structure.
 !  (in)      form_of_eos - integer that selects the eqn of state.
 !  (out)     dpa - The change in the pressure anomaly across the layer,
 !                  in Pa.
 !  (out,opt) intz_dpa - The integral through the thickness of the layer of the
 !                       pressure anomaly relative to the anomaly at the top of
 !                       the layer, in Pa m.
 !  (out,opt) intx_dpa - The integral in x of the difference between the
 !                       pressure anomaly at the top and bottom of the layer
 !                       divided by the x grid spacing, in Pa.
 !  (out,opt) inty_dpa - The integral in y of the difference between the
 !                       pressure anomaly at the top and bottom of the layer
 !                       divided by the y grid spacing, in Pa.
   real :: t5(5), s5(5), p5(5), r5(5)
   real :: rho_anom
   real :: w_left, w_right, intz(5)
   real, parameter :: c1_90 = 1.0/90.0  ! Rational constants.
   real :: gxrho, i_rho
   real :: dz, ds
   real :: weight_t, weight_b
   integer :: isq, ieq, jsq, jeq, i, j, m, n
   real, dimension(4) :: x, y, f
   isq = hi%IscB ; ieq = hi%IecB ; jsq = hi%JscB ; jeq = hi%JecB
   gxrho = g_e * rho_0
   i_rho = 1.0 / rho_0
   ! =============================
   ! 1. Compute vertical integrals
   ! =============================
   do j=jsq,jeq+1 ; do i=isq,ieq+1
     dz = z_t(i,j) - z_b(i,j)
     ds = s_t(i,j) - s_b(i,j)
     do n=1,5
       weight_t = 0.25 * real(5-n)
       weight_b = 1.0 - weight_t
       p5(n) = -gxrho*(z_t(i,j) - 0.25*real(n-1)*dz)
       ! Salinity and temperature points are linearly interpolated
       s5(n) = weight_t * s_t(i,j) + weight_b * s_b(i,j)
       t5(n) = weight_t * t_t(i,j) + weight_b * t_b(i,j)
     enddo
     call calculate_density(t5, s5, p5, r5, 1, 5, eos)
     ! Use Bode's rule to estimate the pressure anomaly change.
     rho_anom = c1_90*(7.0*(r5(1)+r5(5)) + 32.0*(r5(2)+r5(4)) + 12.0*r5(3)) - &
            rho_ref
     dpa(i,j) = g_e*dz*rho_anom
     ! Pressure anomaly change (computed analytically based on linear EOS)
     rho_anom = 1000.0 + s_b(i,j) + 0.5 * ds - rho_ref
     dpa(i,j) = g_e * dz * rho_anom
     ! Use a Bode's-rule-like fifth-order accurate estimate of
     ! the double integral of the pressure anomaly.
     r5 = r5 - rho_ref
     if (present(intz_dpa)) intz_dpa(i,j) = 0.5*g_e*dz**2 * &
           (rho_anom - c1_90*(16.0*(r5(4)-r5(2)) + 7.0*(r5(5)-r5(1))) )
     intz_dpa(i,j) = ( 0.5 * (s_b(i,j)+1000.0-rho_ref) + &
                       (1.0/3.0) * ds ) * g_e * dz**2
   enddo ; enddo ! end loops on j and i
   ! ==================================================
   ! 2. Compute horizontal integrals in the x direction
   ! ==================================================
   if (present(intx_dpa)) then ; do j=hi%jsc,hi%jec ; do i=isq,ieq
     ! Use Gauss quadrature rule to compute integral
     x(1) = 1.0
     x(2) = 0.0
     x(3) = 0.0
     x(4) = 1.0
     y(1) = z_t(i+1,j)
     y(2) = z_t(i,j)
     y(3) = z_b(i,j)
     y(4) = z_b(i+1,j)
     f(1) = 1000.0 + s_t(i+1,j) - rho_ref
     f(2) = 1000.0 + s_t(i,j) - rho_ref
     f(3) = 1000.0 + s_b(i,j) - rho_ref
     f(4) = 1000.0 + s_b(i+1,j) - rho_ref
     call compute_integral_bilinear ( x, y, f, intx_dpa(i,j) )
     intx_dpa(i,j) = intx_dpa(i,j) * g_e
   enddo ; enddo ; endif
   ! ==================================================
   ! 3. Compute horizontal integrals in the y direction
   ! ==================================================
   if (present(inty_dpa)) then ; do j=jsq,jeq ; do i=hi%isc,hi%iec
     ! Use Gauss quadrature rule to compute integral
     x(1) = 1.0
     x(2) = 0.0
     x(3) = 0.0
     x(4) = 1.0
     y(1) = z_t(i,j+1)
     y(2) = z_t(i,j)
     y(3) = z_b(i,j)
     y(4) = z_b(i,j+1)
     f(1) = 1000.0 + s_t(i,j+1) - rho_ref
     f(2) = 1000.0 + s_t(i,j) - rho_ref
     f(3) = 1000.0 + s_b(i,j) - rho_ref
     f(4) = 1000.0 + s_b(i,j+1) - rho_ref
     call compute_integral_bilinear ( x, y, f, inty_dpa(i,j) )
     inty_dpa(i,j) = inty_dpa(i,j) * g_e
   enddo ; enddo ; endif
int_density_dz_generic_ppm()
subroutine, public mom_eos::int_density_dz_generic_ppm (real, dimension(hii%isd:hii%ied,hii%jsd:hii%jed), intent(in) T, real, dimension(hii%isd:hii%ied,hii%jsd:hii%jed), intent(in) T_t, real, dimension(hii%isd:hii%ied,hii%jsd:hii%jed), intent(in) T_b, real, dimension(hii%isd:hii%ied,hii%jsd:hii%jed), intent(in) S, real, dimension(hii%isd:hii%ied,hii%jsd:hii%jed), intent(in) S_t, real, dimension(hii%isd:hii%ied,hii%jsd:hii%jed), intent(in) S_b, real, dimension(hii%isd:hii%ied,hii%jsd:hii%jed), intent(in) z_t, real, dimension(hii%isd:hii%ied,hii%jsd:hii%jed), intent(in) z_b, real, intent(in) rho_ref, real, intent(in) rho_0, real, intent(in) G_e, type(hor_index_type), intent(in) HII, type(hor_index_type), intent(in) HIO, type(eos_type), pointer EOS, real, dimension(hio%isd:hio%ied,hio%jsd:hio%jed), intent(out) dpa, real, dimension(hio%isd:hio%ied,hio%jsd:hio%jed), intent(out), optional intz_dpa, real, dimension(hio%isdb:hio%iedb,hio%jsdb:hio%jedb), intent(out), optional intx_dpa, real, dimension(hio%isd:hio%ied,hio%jsdb:hio%jedb), intent(out), optional inty_dpa)
Parameters
eos Equation of state structure
Definition at line 1339 of file MOM_EOS.F90.
References compute_integral_quadratic(), and mom_error_handler::mom_error().
   type(hor_index_type), intent(in)  :: hii, hio
   real, dimension(HII%isd:HII%ied,HII%jsd:HII%jed), &
                         intent(in)  :: t, t_t, t_b, s, s_t, s_b, z_t, z_b
   real,                                    intent(in)  :: rho_ref, rho_0, g_e
   type(eos_type),       pointer     :: eos !< Equation of state structure
   real, dimension(HIO%isd:HIO%ied,HIO%jsd:HIO%jed), &
                         intent(out) :: dpa
   real, dimension(HIO%isd:HIO%ied,HIO%jsd:HIO%jed), &
               optional, intent(out) :: intz_dpa
   real, dimension(HIO%IsdB:HIO%IedB,HIO%JsdB:HIO%JedB), &
               optional, intent(out) :: intx_dpa
   real, dimension(HIO%isd:HIO%ied,HIO%JsdB:HIO%JedB), &
               optional, intent(out) :: inty_dpa
 ! This subroutine calculates (by numerical quadrature) integrals of
 ! pressure anomalies across layers, which are required for calculating the
 ! finite-volume form pressure accelerations in a Boussinesq model.  The one
 ! potentially dodgy assumtion here is that rho_0 is used both in the denominator
 ! of the accelerations, and in the pressure used to calculated density (the
 ! latter being -z*rho_0*G_e).  These two uses could be separated if need be.
 !
 ! It is assumed that the salinity and temperature profiles are linear in the
 ! vertical. The top and bottom values within each layer are provided and
 ! a linear interpolation is used to compute intermediate values.
 !
 ! Arguments: T - potential temperature relative to the surface in C
 !                (the 't' and 'b' subscripts refer to the values at
 !                 the top and the bottom of each layer)
 !  (in)      S - salinity in PSU.
 !                (the 't' and 'b' subscripts refer to the values at
 !                 the top and the bottom of each layer)
 !  (in)      z_t - height at the top of the layer in m.
 !  (in)      z_b - height at the top of the layer in m.
 !  (in)      rho_ref - A mean density, in kg m-3, that is subtracted out to reduce
 !                    the magnitude of each of the integrals.
 !                    (The pressure is calucated as p~=-z*rho_0*G_e.)
 !  (in)      rho_0 - A density, in kg m-3, that is used to calculate the pressure
 !                    (as p~=-z*rho_0*G_e) used in the equation of state.
 !  (in)      G_e - The Earth's gravitational acceleration, in m s-2.
 !  (in)      G - The ocean's grid structure.
 !  (in)      form_of_eos - integer that selects the eqn of state.
 !  (out)     dpa - The change in the pressure anomaly across the layer,
 !                  in Pa.
 !  (out,opt) intz_dpa - The integral through the thickness of the layer of the
 !                       pressure anomaly relative to the anomaly at the top of
 !                       the layer, in Pa m.
 !  (out,opt) intx_dpa - The integral in x of the difference between the
 !                       pressure anomaly at the top and bottom of the layer
 !                       divided by the x grid spacing, in Pa.
 !  (out,opt) inty_dpa - The integral in y of the difference between the
 !                       pressure anomaly at the top and bottom of the layer
 !                       divided by the y grid spacing, in Pa.
   real :: t5(5), s5(5), p5(5), r5(5)
   real :: rho_anom
   real :: w_left, w_right, intz(5)
   real, parameter :: c1_90 = 1.0/90.0  ! Rational constants.
   real :: gxrho, i_rho
   real :: dz
   real :: weight_t, weight_b
   real :: s0, s1, s2                   ! parabola coefficients for S
   real :: t0, t1, t2                   ! parabola coefficients for T
   real :: xi                           ! normalized coordinate
   real :: t_top, t_mid, t_bot
   real :: s_top, s_mid, s_bot
   integer :: is, ie, js, je, isq, ieq, jsq, jeq, i, j, m, n, ioff, joff
   real, dimension(4) :: x, y
   real, dimension(9) :: s_node, t_node, p_node, r_node
   call mom_error(fatal, &
     "int_density_dz_generic_ppm: the implementation is not done yet, contact developer")
   ioff = hio%idg_offset - hii%idg_offset
   joff = hio%jdg_offset - hii%jdg_offset
   ! These array bounds work for the indexing convention of the input arrays, but
   ! on the computational domain defined for the output arrays.
   isq = hio%IscB + ioff ; ieq = hio%IecB + ioff
   jsq = hio%JscB + joff ; jeq = hio%JecB + joff
   is = hio%isc + ioff ; ie = hio%iec + ioff
   js = hio%jsc + joff ; je = hio%jec + joff
   gxrho = g_e * rho_0
   i_rho = 1.0 / rho_0
   ! =============================
   ! 1. Compute vertical integrals
   ! =============================
   do j=jsq,jeq+1 ; do i=isq,ieq+1
     dz = z_t(i,j) - z_b(i,j)
     ! Coefficients of the parabola for S
     s0 = s_t(i,j)
     s1 = 6.0 * s(i,j) - 4.0 * s_t(i,j) - 2.0 * s_b(i,j)
     s2 = 3.0 * ( s_t(i,j) + s_b(i,j) - 2.0*s(i,j) )
     ! Coefficients of the parabola for T
     t0 = t_t(i,j)
     t1 = 6.0 * t(i,j) - 4.0 * t_t(i,j) - 2.0 * t_b(i,j)
     t2 = 3.0 * ( t_t(i,j) + t_b(i,j) - 2.0*t(i,j) )
     do n=1,5
       p5(n) = -gxrho*(z_t(i,j) - 0.25*real(n-1)*dz)
       ! Parabolic reconstruction for T and S
       xi = 0.25 * ( n - 1 )
       s5(n) = s0 + s1 * xi + s2 * xi**2
       t5(n) = t0 + t1 * xi + t2 * xi**2
     enddo
     call calculate_density(t5, s5, p5, r5, 1, 5, eos)
     ! Use Bode's rule to estimate the pressure anomaly change.
     !rho_anom = C1_90*(7.0*(r5(1)+r5(5)) + 32.0*(r5(2)+r5(4)) + 12.0*r5(3)) - &
     !       rho_ref
     rho_anom = 1000.0 + s(i,j) - rho_ref;
     dpa(i-ioff,j-joff) = g_e*dz*rho_anom
     ! Use a Bode's-rule-like fifth-order accurate estimate of
     ! the double integral of the pressure anomaly.
     !r5 = r5 - rho_ref
     !if (present(intz_dpa)) intz_dpa(i,j) = 0.5*G_e*dz**2 * &
     !      (rho_anom - C1_90*(16.0*(r5(4)-r5(2)) + 7.0*(r5(5)-r5(1))) )
     intz_dpa(i-ioff,j-joff) = 0.5 * g_e * dz**2 * ( 1000.0 - rho_ref + s0 + s1/3.0 + &
                                     s2/6.0 )
   enddo ; enddo ! end loops on j and i
   ! ==================================================
   ! 2. Compute horizontal integrals in the x direction
   ! ==================================================
   if (present(intx_dpa)) then ; do j=js,je ; do i=isq,ieq
     intz(1) = dpa(i-ioff,j-joff) ; intz(5) = dpa(i+1-ioff,j-joff)
     do m=2,4
       w_left = 0.25*real(5-m) ; w_right = 1.0-w_left
       dz = w_left*(z_t(i,j) - z_b(i,j)) + w_right*(z_t(i+1,j) - z_b(i+1,j))
       ! Salinity and temperature points are linearly interpolated in
       ! the horizontal. The subscript (1) refers to the top value in
       ! the vertical profile while subscript (5) refers to the bottom
       ! value in the vertical profile.
       t_top = w_left*t_t(i,j) + w_right*t_t(i+1,j)
       t_mid = w_left*t(i,j)   + w_right*t(i+1,j)
       t_bot = w_left*t_b(i,j) + w_right*t_b(i+1,j)
       s_top = w_left*s_t(i,j) + w_right*s_t(i+1,j)
       s_mid = w_left*s(i,j)   + w_right*s(i+1,j)
       s_bot = w_left*s_b(i,j) + w_right*s_b(i+1,j)
       p5(1) = -gxrho*(w_left*z_t(i,j) + w_right*z_t(i+1,j))
       ! Pressure
       do n=2,5
         p5(n) = p5(n-1) + gxrho*0.25*dz
       enddo
       ! Coefficients of the parabola for S
       s0 = s_top
       s1 = 6.0 * s_mid - 4.0 * s_top - 2.0 * s_bot
       s2 = 3.0 * ( s_top + s_bot - 2.0*s_mid )
       ! Coefficients of the parabola for T
       t0 = t_top
       t1 = 6.0 * t_mid - 4.0 * t_top - 2.0 * t_bot
       t2 = 3.0 * ( t_top + t_bot - 2.0*t_mid )
       do n=1,5
         ! Parabolic reconstruction for T and S
         xi = 0.25 * ( n - 1 )
         s5(n) = s0 + s1 * xi + s2 * xi**2
         t5(n) = t0 + t1 * xi + t2 * xi**2
       enddo
       call calculate_density(t5, s5, p5, r5, 1, 5, eos)
     ! Use Bode's rule to estimate the pressure anomaly change.
       intz(m) = g_e*dz*( c1_90*(7.0*(r5(1)+r5(5)) + 32.0*(r5(2)+r5(4)) + &
                             12.0*r5(3)) - rho_ref)
     enddo
     intx_dpa(i-ioff,j-joff) = c1_90*(7.0*(intz(1)+intz(5)) + 32.0*(intz(2)+intz(4)) + &
                            12.0*intz(3))
     ! Use Gauss quadrature rule to compute integral
     ! The following coordinates define the quadrilateral on which the integral
     ! is computed
     x(1) = 1.0
     x(2) = 0.0
     x(3) = 0.0
     x(4) = 1.0
     y(1) = z_t(i+1,j)
     y(2) = z_t(i,j)
     y(3) = z_b(i,j)
     y(4) = z_b(i+1,j)
     t_node = 0.0
     p_node = 0.0
     ! Nodal values for S
     ! Parabolic reconstruction on the left
     s0 = s_t(i,j)
     s1 = 6.0 * s(i,j) - 4.0 * s_t(i,j) - 2.0 * s_b(i,j)
     s2 = 3.0 * ( s_t(i,j) + s_b(i,j) - 2.0 * s(i,j) )
     s_node(2) = s0
     s_node(6) = s0 + 0.5 * s1 + 0.25 * s2
     s_node(3) = s0 + s1 + s2
     ! Parabolic reconstruction on the left
     s0 = s_t(i+1,j)
     s1 = 6.0 * s(i+1,j) - 4.0 * s_t(i+1,j) - 2.0 * s_b(i+1,j)
     s2 = 3.0 * ( s_t(i+1,j) + s_b(i+1,j) - 2.0 * s(i+1,j) )
     s_node(1) = s0
     s_node(8) = s0 + 0.5 * s1 + 0.25 * s2
     s_node(4) = s0 + s1 + s2
     s_node(5) = 0.5 * ( s_node(2) + s_node(1) )
     s_node(9) = 0.5 * ( s_node(6) + s_node(8) )
     s_node(7) = 0.5 * ( s_node(3) + s_node(4) )
     call calculate_density ( t_node, s_node, p_node, r_node, 1, 9, eos )
     r_node = r_node - rho_ref
     call compute_integral_quadratic ( x, y, r_node, intx_dpa(i-ioff,j-joff) )
     intx_dpa(i-ioff,j-joff) = intx_dpa(i-ioff,j-joff) * g_e
   enddo ; enddo ; endif
   ! ==================================================
   ! 3. Compute horizontal integrals in the y direction
   ! ==================================================
   if (present(inty_dpa)) then
     call mom_error(warning, "int_density_dz_generic_ppm still needs to be written for inty_dpa!")
     do j=jsq,jeq ; do i=is,ie
       inty_dpa(i-ioff,j-joff) = 0.0
     enddo ; enddo
   endif
int_spec_vol_dp_generic()
subroutine mom_eos::int_spec_vol_dp_generic (real, dimension(hi%isd:hi%ied,hi%jsd:hi%jed), intent(in) T, real, dimension(hi%isd:hi%ied,hi%jsd:hi%jed), intent(in) S, real, dimension(hi%isd:hi%ied,hi%jsd:hi%jed), intent(in) p_t, real, dimension(hi%isd:hi%ied,hi%jsd:hi%jed), intent(in) p_b, real, intent(in) alpha_ref, type(hor_index_type), intent(in) HI, type(eos_type), pointer EOS, real, dimension(hi%isd:hi%ied,hi%jsd:hi%jed), intent(out) dza, real, dimension(hi%isd:hi%ied,hi%jsd:hi%jed), intent(out), optional intp_dza, real, dimension(hi%isdb:hi%iedb,hi%jsd:hi%jed), intent(out), optional intx_dza, real, dimension(hi%isd:hi%ied,hi%jsdb:hi%jedb), intent(out), optional inty_dza, integer, intent(in), optional halo_size) private
Parameters
eos Equation of state structure
Definition at line 2003 of file MOM_EOS.F90.
Referenced by int_specific_vol_dp().
   type(hor_index_type), intent(in)  :: hi
   real, dimension(HI%isd:HI%ied,HI%jsd:HI%jed), &
                         intent(in)  :: t, s, p_t, p_b
   real,                 intent(in)  :: alpha_ref
   type(eos_type),       pointer     :: eos !< Equation of state structure
   real, dimension(HI%isd:HI%ied,HI%jsd:HI%jed), &
                         intent(out) :: dza
   real, dimension(HI%isd:HI%ied,HI%jsd:HI%jed), &
               optional, intent(out) :: intp_dza
   real, dimension(HI%IsdB:HI%IedB,HI%jsd:HI%jed), &
               optional, intent(out) :: intx_dza
   real, dimension(HI%isd:HI%ied,HI%JsdB:HI%JedB), &
               optional, intent(out) :: inty_dza
   integer,    optional, intent(in)  :: halo_size
 !   This subroutine calculates analytical and nearly-analytical integrals in
 ! pressure across layers of geopotential anomalies, which are required for
 ! calculating the finite-volume form pressure accelerations in a non-Boussinesq
 ! model.  There are essentially no free assumptions, apart from the use of
 ! Bode's rule to do the horizontal integrals, and from a truncation in the
 ! series for log(1-eps/1+eps) that assumes that |eps| < 0.34.
 !
 ! Arguments: T - potential temperature relative to the surface in C.
 !  (in)      S - salinity in PSU.
 !  (in)      p_t - pressure at the top of the layer in Pa.
 !  (in)      p_b - pressure at the top of the layer in Pa.
 !  (in)      alpha_ref - A mean specific volume that is subtracted out to reduce
 !                        the magnitude of each of the integrals, m3 kg-1.
 !                        The calculation is mathematically identical with
 !                        different values of alpha_ref, but this reduces the
 !                        effects of roundoff.
 !  (in)      HI - The ocean's horizontal index structure.
 !  (in)      EOS - type that selects the eqn of state.
 !  (out)     dza - The change in the geopotential anomaly across the layer,
 !                  in m2 s-2.
 !  (out,opt) intp_dza - The integral in pressure through the layer of the
 !                       geopotential anomaly relative to the anomaly at the
 !                       bottom of the layer, in Pa m2 s-2.
 !  (out,opt) intx_dza - The integral in x of the difference between the
 !                       geopotential anomaly at the top and bottom of the layer
 !                       divided by the x grid spacing, in m2 s-2.
 !  (out,opt) inty_dza - The integral in y of the difference between the
 !                       geopotential anomaly at the top and bottom of the layer
 !                       divided by the y grid spacing, in m2 s-2.
 !  (in,opt)  halo_size - The width of halo points on which to calculate dza.
   real :: t5(5), s5(5), p5(5), r5(5), a5(5)
   real :: alpha_anom
   real :: w_left, w_right, intp(5)
   real, parameter :: c1_90 = 1.0/90.0  ! Rational constants.
   real :: dp         ! The pressure change through each layer, in Pa.
   integer :: isq, ieq, jsq, jeq, ish, ieh, jsh, jeh, i, j, m, n, halo
   isq = hi%IscB ; ieq = hi%IecB ; jsq = hi%JscB ; jeq = hi%JecB
   halo = 0 ; if (present(halo_size)) halo = max(halo_size,0)
   ish = hi%isc-halo ; ieh = hi%iec+halo ; jsh = hi%jsc-halo ; jeh = hi%jec+halo
   if (present(intx_dza)) then ; ish = min(isq,ish) ; ieh = max(ieq+1,ieh); endif
   if (present(inty_dza)) then ; jsh = min(jsq,jsh) ; jeh = max(jeq+1,jeh); endif
   do j=jsh,jeh ; do i=ish,ieh
     dp = p_b(i,j) - p_t(i,j)
     do n=1,5
       t5(n) = t(i,j) ; s5(n) = s(i,j)
       p5(n) = p_b(i,j) - 0.25*real(n-1)*dp
     enddo
     call calculate_density(t5, s5, p5, r5, 1, 5, eos)
     do n=1,5 ; a5(n) = 1.0 / r5(n) ; enddo
     ! Use Bode's rule to estimate the pressure anomaly change.
     alpha_anom = c1_90*(7.0*(a5(1)+a5(5)) + 32.0*(a5(2)+a5(4)) + 12.0*a5(3)) - &
                  alpha_ref
     dza(i,j) = dp*alpha_anom
     ! Use a Bode's-rule-like fifth-order accurate estimate of the double integral of
     ! the pressure anomaly.
     if (present(intp_dza)) intp_dza(i,j) = 0.5*dp**2 * &
           (alpha_anom - c1_90*(16.0*(a5(4)-a5(2)) + 7.0*(a5(5)-a5(1))) )
   enddo ; enddo
   if (present(intx_dza)) then ; do j=hi%jsc,hi%jec ; do i=isq,ieq
     intp(1) = dza(i,j) ; intp(5) = dza(i+1,j)
     do m=2,4
       w_left = 0.25*real(5-m) ; w_right = 1.0-w_left
       dp = w_left*(p_b(i,j) - p_t(i,j)) + w_right*(p_b(i+1,j) - p_t(i+1,j))
       t5(1) = w_left*t(i,j) + w_right*t(i+1,j)
       s5(1) = w_left*s(i,j) + w_right*s(i+1,j)
       p5(1) = w_left*p_b(i,j) + w_right*p_b(i+1,j)
       do n=2,5
         t5(n) = t5(1) ; s5(n) = s5(1) ; p5(n) = p5(n-1) - 0.25*dp
       enddo
       call calculate_density(t5, s5, p5, r5, 1, 5, eos)
       do n=1,5 ; a5(n) = 1.0 / r5(n) ; enddo
     ! Use Bode's rule to estimate the pressure anomaly change.
       intp(m) = dp*( c1_90*(7.0*(a5(1)+a5(5)) + 32.0*(a5(2)+a5(4)) + &
                                 12.0*a5(3)) - alpha_ref)
     enddo
     ! Use Bode's rule to integrate the bottom pressure anomaly values in x.
     intx_dza(i,j) = c1_90*(7.0*(intp(1)+intp(5)) + 32.0*(intp(2)+intp(4)) + &
                            12.0*intp(3))
   enddo ; enddo ; endif
   if (present(inty_dza)) then ; do j=jsq,jeq ; do i=hi%isc,hi%iec
     intp(1) = dza(i,j) ; intp(5) = dza(i,j+1)
     do m=2,4
       w_left = 0.25*real(5-m) ; w_right = 1.0-w_left
       dp = w_left*(p_b(i,j) - p_t(i,j)) + w_right*(p_b(i,j+1) - p_t(i,j+1))
       t5(1) = w_left*t(i,j) + w_right*t(i,j+1)
       s5(1) = w_left*s(i,j) + w_right*s(i,j+1)
       p5(1) = w_left*p_b(i,j) + w_right*p_b(i,j+1)
       do n=2,5
         t5(n) = t5(1) ; s5(n) = s5(1) ; p5(n) = p5(n-1) - 0.25*dp
       enddo
       call calculate_density(t5, s5, p5, r5, 1, 5, eos)
       do n=1,5 ; a5(n) = 1.0 / r5(n) ; enddo
     ! Use Bode's rule to estimate the pressure anomaly change.
       intp(m) = dp*( c1_90*(7.0*(a5(1)+a5(5)) + 32.0*(a5(2)+a5(4)) + &
                                 12.0*a5(3)) - alpha_ref)
     enddo
     ! Use Bode's rule to integrate the bottom pressure anomaly values in y.
     inty_dza(i,j) = c1_90*(7.0*(intp(1)+intp(5)) + 32.0*(intp(2)+intp(4)) + &
                            12.0*intp(3))
   enddo ; enddo ; endif
int_specific_vol_dp()
subroutine, public mom_eos::int_specific_vol_dp (real, dimension(hi%isd:hi%ied,hi%jsd:hi%jed), intent(in) T, real, dimension(hi%isd:hi%ied,hi%jsd:hi%jed), intent(in) S, real, dimension(hi%isd:hi%ied,hi%jsd:hi%jed), intent(in) p_t, real, dimension(hi%isd:hi%ied,hi%jsd:hi%jed), intent(in) p_b, real, intent(in) alpha_ref, type(hor_index_type), intent(in) HI, type(eos_type), pointer EOS, real, dimension(hi%isd:hi%ied,hi%jsd:hi%jed), intent(out) dza, real, dimension(hi%isd:hi%ied,hi%jsd:hi%jed), intent(out), optional intp_dza, real, dimension(hi%isdb:hi%iedb,hi%jsd:hi%jed), intent(out), optional intx_dza, real, dimension(hi%isd:hi%ied,hi%jsdb:hi%jedb), intent(out), optional inty_dza, integer, intent(in), optional halo_size)
Calls the appropriate subroutine to alculate analytical and nearly-analytical integrals in pressure across layers of geopotential anomalies, which are required for calculating the finite-volume form pressure accelerations in a non-Boussinesq model. There are essentially no free assumptions, apart from the use of Bode's rule to do the horizontal integrals, and from a truncation in the series for log(1-eps/1+eps) that assumes that |eps| < .
Parameters
[in] hi The horizontal index structure
[in] t Potential temperature referenced to the surface (degC)
[in] s Salinity (PSU)
[in] p_t Pressure at the top of the layer in Pa.
[in] p_b Pressure at the bottom of the layer in Pa.
[in] alpha_ref A mean specific volume that is subtracted out to reduce the magnitude of each of the integrals, m3 kg-1. The calculation is mathematically identical with different values of alpha_ref, but this reduces the effects of roundoff.
eos Equation of state structure
[out] dza The change in the geopotential anomaly across the layer, in m2 s-2.
[out] intp_dza The integral in pressure through the layer of the geopotential anomaly relative to the anomaly at the bottom of the layer, in Pa m2 s-2.
[out] intx_dza The integral in x of the difference between the geopotential anomaly at the top and bottom of the layer divided by the x grid spacing, in m2 s-2.
[out] inty_dza The integral in y of the difference between the geopotential anomaly at the top and bottom of the layer divided by the y grid spacing, in m2 s-2.
[in] halo_size The width of halo points on which to calculate dza.
Definition at line 333 of file MOM_EOS.F90.
References eos_linear, eos_wright, int_spec_vol_dp_generic(), mom_eos_linear::int_spec_vol_dp_linear(), mom_eos_wright::int_spec_vol_dp_wright(), and mom_error_handler::mom_error().
Referenced by mom_state_initialization::convert_thickness(), mom_interface_heights::find_eta_2d(), mom_interface_heights::find_eta_3d(), and mom_pressureforce_mont::pressureforce_mont_nonbouss().
   !> The horizontal index structure
     type(hor_index_type),                          intent(in)  :: hi
   !> Potential temperature referenced to the surface (degC)
     real, dimension(HI%isd:HI%ied,HI%jsd:HI%jed),  intent(in)  :: t
   !> Salinity (PSU)
     real, dimension(HI%isd:HI%ied,HI%jsd:HI%jed),  intent(in)  :: s
   !> Pressure at the top of the layer in Pa.
     real, dimension(HI%isd:HI%ied,HI%jsd:HI%jed),  intent(in)  :: p_t
   !> Pressure at the bottom of the layer in Pa.
     real, dimension(HI%isd:HI%ied,HI%jsd:HI%jed),  intent(in)  :: p_b
   !> A mean specific volume that is subtracted out to reduce the magnitude of
   !! each of the integrals, m3 kg-1. The calculation is mathematically identical
   !! with different values of alpha_ref, but this reduces the effects of roundoff.
     real,                                          intent(in)  :: alpha_ref
   !> Equation of state structure
     type(eos_type),                                pointer     :: eos
   !> The change in the geopotential anomaly across the layer, in m2 s-2.
     real, dimension(HI%isd:HI%ied,HI%jsd:HI%jed),  intent(out) :: dza
   !> The integral in pressure through the layer of the geopotential anomaly
   !! relative to the anomaly at the bottom of the layer, in Pa m2 s-2.
     real, dimension(HI%isd:HI%ied,HI%jsd:HI%jed),  optional, intent(out) :: intp_dza
   !> The integral in x of the difference between the geopotential anomaly at the
   !! top and bottom of the layer divided by the x grid spacing, in m2 s-2.
     real, dimension(HI%IsdB:HI%IedB,HI%jsd:HI%jed), optional, intent(out) :: intx_dza
   !> The integral in y of the difference between the geopotential anomaly at the
   !! top and bottom of the layer divided by the y grid spacing, in m2 s-2.
     real, dimension(HI%isd:HI%ied,HI%JsdB:HI%JedB), optional, intent(out) :: inty_dza
   !> The width of halo points on which to calculate dza.
     integer,                             optional, intent(in)  :: halo_size
   if (.not.associated(eos)) call mom_error(fatal, &
     "int_specific_vol_dp called with an unassociated EOS_type EOS.")
   if (eos%EOS_quadrature) then
     call int_spec_vol_dp_generic(t, s, p_t, p_b, alpha_ref, hi, eos, &
                                  dza, intp_dza, intx_dza, inty_dza, halo_size)
   else ; select case (eos%form_of_EOS)
     case (eos_linear)
       call int_spec_vol_dp_linear(t, s, p_t, p_b, alpha_ref, hi, eos%Rho_T0_S0, &
                                   eos%dRho_dT, eos%dRho_dS, dza, intp_dza, &
                                   intx_dza, inty_dza, halo_size)
     case (eos_wright)
       call int_spec_vol_dp_wright(t, s, p_t, p_b, alpha_ref, hi, dza, &
                                   intp_dza, intx_dza, inty_dza, halo_size)
     case default
       call int_spec_vol_dp_generic(t, s, p_t, p_b, alpha_ref, hi, eos, &
                                    dza, intp_dza, intx_dza, inty_dza, halo_size)
   end select ; endif
query_compressible()
logical function, public mom_eos::query_compressible (type(eos_type), pointer EOS)
Returns true if the equation of state is compressible (i.e. has pressure dependence)
Parameters
eos Equation of state structure
Definition at line 449 of file MOM_EOS.F90.
References mom_error_handler::mom_error().
Referenced by mom_pressureforce_mont::pressureforce_mont_bouss(), and mom_pressureforce_mont::pressureforce_mont_nonbouss().
   type(eos_type), pointer :: eos !< Equation of state structure
   if (.not.associated(eos)) call mom_error(fatal, &
     "query_compressible called with an unassociated EOS_type EOS.")
   query_compressible = eos%compressible
Variable Documentation
eos_default
character*(10), parameter mom_eos::eos_default = EOS_WRIGHT_STRING private
Definition at line 86 of file MOM_EOS.F90.
Referenced by eos_init().
 character*(10), parameter :: EOS_DEFAULT = EOS_WRIGHT_STRING
eos_linear
integer, parameter mom_eos::eos_linear = 1
Definition at line 75 of file MOM_EOS.F90.
Referenced by calculate_compress(), calculate_density_array(), calculate_density_derivs(), calculate_density_scalar(), calculate_specific_vol_derivs(), eos_init(), eos_use_linear(), int_density_dz(), and int_specific_vol_dp().
 integer, parameter :: eos_linear = 1
eos_linear_string
character*(10), parameter mom_eos::eos_linear_string = "LINEAR" private
Definition at line 81 of file MOM_EOS.F90.
Referenced by eos_init().
 character*(10), parameter :: EOS_LINEAR_STRING = "LINEAR"
eos_nemo
integer, parameter mom_eos::eos_nemo = 5 private
Definition at line 79 of file MOM_EOS.F90.
Referenced by calculate_compress(), calculate_density_array(), calculate_density_derivs(), calculate_density_scalar(), calculate_specific_vol_derivs(), convert_temp_salt_for_teos10(), and eos_init().
 integer, parameter :: eos_nemo   = 5
eos_nemo_string
character*(10), parameter mom_eos::eos_nemo_string = "NEMO" private
Definition at line 85 of file MOM_EOS.F90.
Referenced by eos_init().
 character*(10), parameter :: EOS_NEMO_STRING   = "NEMO"
eos_teos10
integer, parameter mom_eos::eos_teos10 = 4 private
Definition at line 78 of file MOM_EOS.F90.
Referenced by calculate_compress(), calculate_density_array(), calculate_density_derivs(), calculate_density_scalar(), calculate_specific_vol_derivs(), convert_temp_salt_for_teos10(), and eos_init().
 integer, parameter :: eos_teos10 = 4
eos_teos10_string
character*(10), parameter mom_eos::eos_teos10_string = "TEOS10" private
Definition at line 84 of file MOM_EOS.F90.
Referenced by eos_init().
 character*(10), parameter :: EOS_TEOS10_STRING = "TEOS10"
eos_unesco
integer, parameter mom_eos::eos_unesco = 2 private
Definition at line 76 of file MOM_EOS.F90.
Referenced by calculate_compress(), calculate_density_array(), calculate_density_derivs(), calculate_density_scalar(), calculate_specific_vol_derivs(), and eos_init().
 integer, parameter :: eos_unesco = 2
eos_unesco_string
character*(10), parameter mom_eos::eos_unesco_string = "UNESCO" private
Definition at line 82 of file MOM_EOS.F90.
Referenced by eos_init().
 character*(10), parameter :: EOS_UNESCO_STRING = "UNESCO"
eos_wright
integer, parameter mom_eos::eos_wright = 3 private
Definition at line 77 of file MOM_EOS.F90.
Referenced by calculate_compress(), calculate_density_array(), calculate_density_derivs(), calculate_density_scalar(), calculate_specific_vol_derivs(), eos_init(), int_density_dz(), and int_specific_vol_dp().
 integer, parameter :: eos_wright = 3
eos_wright_string
character*(10), parameter mom_eos::eos_wright_string = "WRIGHT" private
Definition at line 83 of file MOM_EOS.F90.
Referenced by eos_init().
 character*(10), parameter :: EOS_WRIGHT_STRING = "WRIGHT"
tfreeze_default
character*(10), parameter mom_eos::tfreeze_default = TFREEZE_LINEAR_STRING private
Definition at line 94 of file MOM_EOS.F90.
Referenced by eos_init().
 character*(10), parameter :: TFREEZE_DEFAULT = TFREEZE_LINEAR_STRING
tfreeze_linear
integer, parameter mom_eos::tfreeze_linear = 1 private
Definition at line 88 of file MOM_EOS.F90.
Referenced by calculate_tfreeze_array(), calculate_tfreeze_scalar(), and eos_init().
 integer, parameter :: tfreeze_linear = 1
tfreeze_linear_string
character*(10), parameter mom_eos::tfreeze_linear_string = "LINEAR" private
Definition at line 91 of file MOM_EOS.F90.
Referenced by eos_init().
 character*(10), parameter :: TFREEZE_LINEAR_STRING = "LINEAR"
tfreeze_millero
integer, parameter mom_eos::tfreeze_millero = 2 private
Definition at line 89 of file MOM_EOS.F90.
Referenced by calculate_tfreeze_array(), calculate_tfreeze_scalar(), and eos_init().
 integer, parameter :: tfreeze_millero = 2
tfreeze_millero_string
character*(10), parameter mom_eos::tfreeze_millero_string = "MILLERO_78" private
Definition at line 92 of file MOM_EOS.F90.
Referenced by eos_init().
 character*(10), parameter :: TFREEZE_MILLERO_STRING = "MILLERO_78"
tfreeze_teos10
integer, parameter mom_eos::tfreeze_teos10 = 3 private
Definition at line 90 of file MOM_EOS.F90.
Referenced by calculate_tfreeze_array(), calculate_tfreeze_scalar(), and eos_init().
 integer, parameter :: tfreeze_teos10 = 3
tfreeze_teos10_string
character*(10), parameter mom_eos::tfreeze_teos10_string = "TEOS10" private
Definition at line 93 of file MOM_EOS.F90.
Referenced by eos_init().
 character*(10), parameter :: TFREEZE_TEOS10_STRING = "TEOS10"