MOM6: user_initialization Module Reference
user_initialization Module Reference
Detailed Description
By Robert Hallberg, April 1994 - June 2002 *
This subroutine initializes the fields for the simulations. * The one argument passed to initialize, Time, is set to the * current time of the simulation. The fields which are initialized * here are: * u - Zonal velocity in m s-1. * v - Meridional velocity in m s-1. * h - Layer thickness in m. (Must be positive.) * GbathyT - Basin depth in m. (Must be positive.) * GCoriolisBu - The Coriolis parameter, in s-1. * GVg_prime - The reduced gravity at each interface, in m s-2. * GVRlay - Layer potential density (coordinate variable), kg m-3. * If ENABLE_THERMODYNAMICS is defined: * T - Temperature in C. * S - Salinity in psu. * If BULKMIXEDLAYER is defined: * Rml - Mixed layer and buffer layer potential densities in * units of kg m-3. * If SPONGE is defined: * A series of subroutine calls are made to set up the damping * rates and reference profiles for all variables that are damped * in the sponge. * Any user provided tracer code is also first linked through this * subroutine. *
Forcing-related fields (taux, tauy, buoy, ustar, etc.) are set * in MOM_surface_forcing.F90. *
These variables are all set in the set of subroutines (in this * file) USER_initialize_bottom_depth, USER_initialize_thickness, * USER_initialize_velocity, USER_initialize_temperature_salinity, * USER_initialize_mixed_layer_density, USER_initialize_sponges, * USER_set_coord, and USER_set_ref_profile. *
The names of these subroutines should be self-explanatory. They * start with "USER_" to indicate that they will likely have to be * modified for each simulation to set the initial conditions and * boundary conditions. Most of these take two arguments: an integer * argument specifying whether the fields are to be calculated * internally or read from a NetCDF file; and a string giving the * path to that file. If the field is initialized internally, the * path is ignored. *
Macros written all in capital letters are defined in MOM_memory.h. *
A small fragment of the grid is shown below: *
j+1 x ^ x ^ x At x: q, CoriolisBu * j+1 > o > o > At ^: v, tauy * j x ^ x ^ x At >: u, taux * j > o > o > At o: h, bathyT, buoy, tr, T, S, Rml, ustar * j-1 x ^ x ^ x * i-1 i i+1 At x & ^: * i i+1 At > & o: *
The boundaries always run through q grid points (x). *.
Functions/Subroutines
subroutine, public user_set_coord (Rlay, g_prime, GV, param_file, eqn_of_state)
Set vertical coordinates.
subroutine, public user_initialize_topography (D, G, param_file, max_depth)
Initialize topography.
subroutine, public user_initialize_thickness (h, G, param_file, T, just_read_params)
initialize thicknesses.
subroutine, public user_initialize_velocity (u, v, G, param_file, just_read_params)
initialize velocities.
subroutine, public user_init_temperature_salinity (T, S, G, param_file, eqn_of_state, just_read_params)
This function puts the initial layer temperatures and salinities into T(:,:,:) and S(:,:,:).
subroutine, public user_initialize_sponges (G, use_temperature, tv, param_file, CSp, h)
Set up the sponges.
subroutine, public user_set_obc_data (OBC, tv, G, param_file, tr_Reg)
This subroutine sets the properties of flow at open boundary conditions.
subroutine, public user_set_rotation (G, param_file)
subroutine write_user_log (param_file)
Write output about the parameter values being used.
Variables
logical first_call = .true.
Function/Subroutine Documentation
user_init_temperature_salinity()
subroutine, public user_initialization::user_init_temperature_salinity (real, dimension(g %isd: g %ied, g %jsd: g %jed, g %ke), intent(out) T, real, dimension(g %isd: g %ied, g %jsd: g %jed, g %ke), intent(out) S, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(eos_type), pointer eqn_of_state, logical, intent(in), optional just_read_params)
This function puts the initial layer temperatures and salinities into T(:,:,:) and S(:,:,:).
Parameters
[in] g Ocean grid structure.
[out] t Potential temperature (degC).
[out] s Salinity (ppt).
[in] param_file A structure indicating the open file to parse for model parameter values.
eqn_of_state Integer that selects the equation of state.
[in] just_read_params If present and true, this call will only read parameters without changing h.
Definition at line 150 of file user_initialization.F90.
References first_call, mom_error_handler::mom_error(), and write_user_log().
   type(ocean_grid_type),                     intent(in)  :: g !< Ocean grid structure.
   real, dimension(SZI_(G),SZJ_(G), SZK_(G)), intent(out) :: t !< Potential temperature (degC).
   real, dimension(SZI_(G),SZJ_(G), SZK_(G)), intent(out) :: s !< Salinity (ppt).
   type(param_file_type),                     intent(in)  :: param_file !< A structure indicating the
                                                             !! open file to parse for model
                                                             !! parameter values.
   type(eos_type),                            pointer     :: eqn_of_state !< Integer that selects the
                                                             !! equation of state.
   logical,       optional, intent(in)  :: just_read_params !< If present and true, this call will
                                                       !! only read parameters without changing h.
   logical :: just_read    ! If true, just read parameters but set nothing.
   call mom_error(fatal, &
    "USER_initialization.F90, USER_init_temperature_salinity: " // &
    "Unmodified user routine called - you must edit the routine to use it")
   just_read = .false. ; if (present(just_read_params)) just_read = just_read_params
   if (just_read) return ! All run-time parameters have been read, so return.
   t(:,:,1) = 0.0
   s(:,:,1) = 0.0
   if (first_call) call write_user_log(param_file)
user_initialize_sponges()
subroutine, public user_initialization::user_initialize_sponges (type(ocean_grid_type), intent(in) G, logical, intent(in) use_temperature, type(thermo_var_ptrs), intent(in) tv, type(param_file_type), intent(in) param_file, type(sponge_cs), pointer CSp, real, dimension(g %isd: g %ied, g %jsd: g %jed, g %ke), intent(in) h)
Set up the sponges.
Parameters
[in] g Ocean grid structure.
[in] use_temperature Whether to use potential temperature.
[in] tv A structure containing pointers to any available thermodynamic fields, potential temperature and salinity or mixed layer density. Absent fields have NULL ptrs.
[in] param_file A structure indicating the open file to parse for model parameter values.
csp A pointer to the sponge control structure.
[in] h Layer thicknesses.
Definition at line 180 of file user_initialization.F90.
References first_call, mom_error_handler::mom_error(), and write_user_log().
Referenced by mom_state_initialization::mom_initialize_state().
   type(ocean_grid_type), intent(in) :: g               !< Ocean grid structure.
   logical,               intent(in) :: use_temperature !< Whether to use potential
                                                        !! temperature.
   type(thermo_var_ptrs), intent(in) :: tv              !< A structure containing pointers
                                                        !! to any available thermodynamic
                                                        !! fields, potential temperature and
                                                        !! salinity or mixed layer density.
                                                        !! Absent fields have NULL ptrs.
   type(param_file_type), intent(in) :: param_file      !< A structure indicating the
                                                        !! open file to parse for model
                                                        !! parameter values.
   type(sponge_cs),       pointer    :: csp             !< A pointer to the sponge control
                                                        !! structure.
   real, dimension(SZI_(G), SZJ_(G), SZK_(G)), intent(in) :: h !< Layer thicknesses.
   call mom_error(fatal, &
    "USER_initialization.F90, USER_initialize_sponges: " // &
    "Unmodified user routine called - you must edit the routine to use it")
   if (first_call) call write_user_log(param_file)
user_initialize_thickness()
subroutine, public user_initialization::user_initialize_thickness (real, dimension(g %isd: g %ied, g %jsd: g %jed, g %ke), intent(out) h, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, real, dimension(g %isd: g %ied, g %jsd: g %jed, g %ke), intent(in) T, logical, intent(in), optional just_read_params)
initialize thicknesses.
Parameters
[in] g The ocean's grid structure.
[out] h The thicknesses being initialized.
[in] param_file A structure indicating the open file to parse for model parameter values.
[in] t Potential temperature.
[in] just_read_params If present and true, this call will only read parameters without changing h.
Definition at line 93 of file user_initialization.F90.
References first_call, mom_error_handler::mom_error(), and write_user_log().
   type(ocean_grid_type), intent(in)           :: g          !< The ocean's grid structure.
   real, intent(out), dimension(SZI_(G),SZJ_(G),SZK_(G)) :: h !< The thicknesses being
                                                             !! initialized.
   type(param_file_type), intent(in)           :: param_file !< A structure indicating the
                                                             !! open file to parse for model
                                                             !! parameter values.
   real, intent(in), dimension(SZI_(G),SZJ_(G), SZK_(G))  :: t !< Potential temperature.
   logical,       optional, intent(in)  :: just_read_params !< If present and true, this call will
                                                       !! only read parameters without changing h.
   logical :: just_read    ! If true, just read parameters but set nothing.
   call mom_error(fatal, &
    "USER_initialization.F90, USER_initialize_thickness: " // &
    "Unmodified user routine called - you must edit the routine to use it")
   just_read = .false. ; if (present(just_read_params)) just_read = just_read_params
   if (just_read) return ! All run-time parameters have been read, so return.
   h(:,:,1) = 0.0
   if (first_call) call write_user_log(param_file)
user_initialize_topography()
subroutine, public user_initialization::user_initialize_topography (real, dimension(g%isd:g%ied,g%jsd:g%jed), intent(out) D, type(dyn_horgrid_type), intent(in) G, type(param_file_type), intent(in) param_file, real, intent(in) max_depth)
Initialize topography.
Parameters
[in] g The dynamic horizontal grid type
[out] d Ocean bottom depth in m
[in] param_file Parameter file structure
[in] max_depth Maximum depth of model in m
Definition at line 75 of file user_initialization.F90.
References first_call, mom_error_handler::mom_error(), and write_user_log().
Referenced by mom_fixed_initialization::mom_initialize_topography().
   type(dyn_horgrid_type),             intent(in)  :: g !< The dynamic horizontal grid type
   real, dimension(G%isd:G%ied,G%jsd:G%jed), &
                                       intent(out) :: d !< Ocean bottom depth in m
   type(param_file_type),              intent(in)  :: param_file !< Parameter file structure
   real,                               intent(in)  :: max_depth  !< Maximum depth of model in m
   call mom_error(fatal, &
    "USER_initialization.F90, USER_initialize_topography: " // &
    "Unmodified user routine called - you must edit the routine to use it")
   d(:,:) = 0.0
   if (first_call) call write_user_log(param_file)
user_initialize_velocity()
subroutine, public user_initialization::user_initialize_velocity (real, dimension(g %isdb: g %iedb, g %jsd: g %jed, g %ke), intent(out) u, real, dimension(g %isd: g %ied, g %jsdb: g %jedb, g %ke), intent(out) v, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, logical, intent(in), optional just_read_params)
initialize velocities.
Parameters
[in] g Ocean grid structure.
[out] u i-component of velocity [m/s]
[out] v j-component of velocity [m/s]
[in] param_file A structure indicating the open file to parse for model parameter values.
[in] just_read_params If present and true, this call will only read parameters without changing h.
Definition at line 121 of file user_initialization.F90.
References first_call, mom_error_handler::mom_error(), and write_user_log().
   type(ocean_grid_type),                       intent(in)  :: g !< Ocean grid structure.
   real, dimension(SZIB_(G), SZJ_(G), SZK_(G)), intent(out) :: u !< i-component of velocity [m/s]
   real, dimension(SZI_(G), SZJB_(G), SZK_(G)), intent(out) :: v !< j-component of velocity [m/s]
   type(param_file_type),                       intent(in)  :: param_file !< A structure indicating the
                                                             !! open file to parse for model
                                                             !! parameter values.
   logical,       optional, intent(in)  :: just_read_params !< If present and true, this call will
                                                       !! only read parameters without changing h.
   logical :: just_read    ! If true, just read parameters but set nothing.
   call mom_error(fatal, &
    "USER_initialization.F90, USER_initialize_velocity: " // &
    "Unmodified user routine called - you must edit the routine to use it")
   just_read = .false. ; if (present(just_read_params)) just_read = just_read_params
   if (just_read) return ! All run-time parameters have been read, so return.
   u(:,:,1) = 0.0
   v(:,:,1) = 0.0
   if (first_call) call write_user_log(param_file)
user_set_coord()
subroutine, public user_initialization::user_set_coord (real, dimension(:), intent(out) Rlay, real, dimension(:), intent(out) g_prime, type(verticalgrid_type), intent(in) GV, type(param_file_type), intent(in) param_file, type(eos_type), pointer eqn_of_state)
Set vertical coordinates.
Parameters
[in] gv The ocean's vertical grid structure.
[out] rlay Layer potential density.
[out] g_prime The reduced gravity at each interface, in m s-2.
[in] param_file A structure indicating the open file to parse for model parameter values.
eqn_of_state Integer that selects the equation of state.
Definition at line 52 of file user_initialization.F90.
References first_call, mom_error_handler::mom_error(), and write_user_log().
Referenced by mom_coord_initialization::mom_initialize_coord().
   type(verticalgrid_type), intent(in)  :: gv         !< The ocean's vertical grid
                                                      !! structure.
   real, dimension(:),      intent(out) :: rlay       !< Layer potential density.
   real, dimension(:),      intent(out) :: g_prime    !< The reduced gravity at
                                                      !! each interface, in m s-2.
   type(param_file_type),   intent(in)  :: param_file !< A structure indicating the
                                                      !! open file to parse for model
                                                      !! parameter values.
   type(eos_type),          pointer     :: eqn_of_state !< Integer that selects the
                                                      !! equation of state.
   call mom_error(fatal, &
    "USER_initialization.F90, USER_set_coord: " // &
    "Unmodified user routine called - you must edit the routine to use it")
   rlay(:) = 0.0
   g_prime(:) = 0.0
   if (first_call) call write_user_log(param_file)
user_set_obc_data()
subroutine, public user_initialization::user_set_obc_data (type(ocean_obc_type), pointer OBC, type(thermo_var_ptrs), intent(in) tv, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(tracer_registry_type), pointer tr_Reg)
This subroutine sets the properties of flow at open boundary conditions.
Parameters
obc This open boundary condition type specifies whether, where, and what open boundary conditions are used.
[in] tv A structure containing pointers to any available thermodynamic fields, including potential temperature and salinity or mixed layer density. Absent fields have NULL ptrs.
[in] g The ocean's grid structure.
[in] param_file A structure indicating the open file to parse for model parameter values.
tr_reg Tracer registry.
Definition at line 204 of file user_initialization.F90.
References first_call, and write_user_log().
   type(ocean_obc_type),       pointer    :: obc   !< This open boundary condition type specifies
                                                   !! whether, where, and what open boundary
                                                   !! conditions are used.
   type(thermo_var_ptrs),      intent(in) :: tv    !< A structure containing pointers to any
                                        !! available thermodynamic fields, including potential
                                        !! temperature and salinity or mixed layer density. Absent
                                        !! fields have NULL ptrs.
   type(ocean_grid_type),      intent(in) :: g     !< The ocean's grid structure.
   type(param_file_type),      intent(in) :: param_file !< A structure indicating the
                                                   !! open file to parse for model
                                                   !! parameter values.
   type(tracer_registry_type), pointer    :: tr_reg !< Tracer registry.
 !  call MOM_error(FATAL, &
 !   "USER_initialization.F90, USER_set_OBC_data: " // &
 !   "Unmodified user routine called - you must edit the routine to use it")
   if (first_call) call write_user_log(param_file)
user_set_rotation()
subroutine, public user_initialization::user_set_rotation (type(ocean_grid_type), intent(inout) G, type(param_file_type), intent(in) param_file)
Parameters
[in,out] g The ocean's grid structure
[in] param_file A structure to parse for run-time parameters
Definition at line 225 of file user_initialization.F90.
References first_call, mom_error_handler::mom_error(), and write_user_log().
   type(ocean_grid_type), intent(inout) :: g    !< The ocean's grid structure
   type(param_file_type), intent(in)    :: param_file !< A structure to parse for run-time parameters
   call mom_error(fatal, &
    "USER_initialization.F90, USER_set_rotation: " // &
    "Unmodified user routine called - you must edit the routine to use it")
   if (first_call) call write_user_log(param_file)
write_user_log()
subroutine user_initialization::write_user_log (type(param_file_type), intent(in) param_file) private
Write output about the parameter values being used.
Parameters
[in] param_file A structure indicating the open file to parse for model parameter values.
Definition at line 237 of file user_initialization.F90.
References first_call.
Referenced by user_init_temperature_salinity(), user_initialize_sponges(), user_initialize_thickness(), user_initialize_topography(), user_initialize_velocity(), user_set_coord(), user_set_obc_data(), and user_set_rotation().
   type(param_file_type), intent(in) :: param_file !< A structure indicating the
                                                   !! open file to parse for model
                                                   !! parameter values.
 ! This include declares and sets the variable "version".
 #include "version_variable.h"
   character(len=40)  :: mdl = "user_initialization" ! This module's name.
   call log_version(param_file, mdl, version)
   first_call = .false.
Variable Documentation
first_call
logical user_initialization::first_call = .true. private
Definition at line 46 of file user_initialization.F90.
Referenced by user_init_temperature_salinity(), user_initialize_sponges(), user_initialize_thickness(), user_initialize_topography(), user_initialize_velocity(), user_set_coord(), user_set_obc_data(), user_set_rotation(), and write_user_log().
 logical :: first_call = .true.