MOM6: mom_boundary_update Module Reference
mom_boundary_update Module Reference
Detailed Description
Controls where open boundary conditions are applied.
This module updates the open boundary arrays when time-varying. It caused a circular dependency with the tidal_bay setup when MOM_open_boundary.
A small fragment of the grid is shown below:
j+1 x ^ x ^ x At x: q, CoriolisBu j+1 > o > o > At ^: v, tauy j x ^ x ^ x At >: u, taux j > o > o > At o: h, bathyT, buoy, tr, T, S, Rml, ustar j-1 x ^ x ^ x i-1 i i+1 At x & ^: i i+1 At > & o:
The boundaries always run through q grid points (x).
Data Types
type update_obc_cs
Functions/Subroutines
subroutine, public call_obc_register (param_file, CS, OBC)
The following subroutines and associated definitions provide the machinery to register and call the subroutines that initialize open boundary conditions.
subroutine, public update_obc_data (OBC, G, GV, tv, h, CS, Time)
Calls appropriate routine to update the open boundary conditions.
subroutine, public obc_register_end (CS)
Clean up the OBC registry.
Variables
integer id_clock_pass
character(len=40) mdl = "MOM_boundary_update"
Function/Subroutine Documentation
call_obc_register()
subroutine, public mom_boundary_update::call_obc_register (type(param_file_type), intent(in) param_file, type(update_obc_cs), pointer CS, type(ocean_obc_type), pointer OBC)
The following subroutines and associated definitions provide the machinery to register and call the subroutines that initialize open boundary conditions.
Parameters
[in] param_file Parameter file to parse
cs Control structure for OBCs
obc Open boundary structure
Definition at line 56 of file MOM_boundary_update.F90.
References mom_error_handler::mom_error(), and mom_open_boundary::register_file_obc().
Referenced by mom::initialize_mom().
   type(param_file_type),     intent(in) :: param_file !< Parameter file to parse
   type(update_obc_cs),       pointer    :: cs         !< Control structure for OBCs
   type(ocean_obc_type),      pointer    :: obc        !< Open boundary structure
   character(len=40)  :: mdl = "MOM_boundary_update" ! This module's name.
   if (associated(cs)) then
     call mom_error(warning, "call_OBC_register called with an associated "// &
                             "control structure.")
     return
   else ; allocate(cs) ; endif
   call log_version(param_file, mdl, version, "")
   call get_param(param_file, mdl, "USE_FILE_OBC", cs%use_files, &
                  "If true, use external files for the open boundary.", &
                  default=.false.)
   call get_param(param_file, mdl, "USE_TIDAL_BAY_OBC", cs%use_tidal_bay, &
                  "If true, use the tidal_bay open boundary.", &
                  default=.false.)
   call get_param(param_file, mdl, "USE_KELVIN_WAVE_OBC", cs%use_Kelvin, &
                  "If true, use the Kelvin wave open boundary.", &
                  default=.false.)
   call get_param(param_file, mdl, "USE_SHELFWAVE_OBC", cs%use_shelfwave, &
                  "If true, use the shelfwave open boundary.", &
                  default=.false.)
   if (cs%use_files) cs%use_files = &
     register_file_obc(param_file, cs%file_OBC_CSp, &
                obc%OBC_Reg)
   if (cs%use_tidal_bay) cs%use_tidal_bay = &
     register_tidal_bay_obc(param_file, cs%tidal_bay_OBC_CSp, &
                obc%OBC_Reg)
   if (cs%use_Kelvin) cs%use_Kelvin = &
     register_kelvin_obc(param_file, cs%Kelvin_OBC_CSp, &
                obc%OBC_Reg)
   if (cs%use_shelfwave) cs%use_shelfwave = &
     register_shelfwave_obc(param_file, cs%shelfwave_OBC_CSp, &
                obc%OBC_Reg)
obc_register_end()
subroutine, public mom_boundary_update::obc_register_end (type(update_obc_cs), pointer CS)
Clean up the OBC registry.
Parameters
cs Control structure for OBCs
Definition at line 136 of file MOM_boundary_update.F90.
References mom_open_boundary::file_obc_end(), kelvin_initialization::kelvin_obc_end(), and tidal_bay_initialization::tidal_bay_obc_end().
   type(update_obc_cs),       pointer    :: cs !< Control structure for OBCs
   if (cs%use_files) call file_obc_end(cs%file_OBC_CSp)
   if (cs%use_tidal_bay) call tidal_bay_obc_end(cs%tidal_bay_OBC_CSp)
   if (cs%use_Kelvin) call kelvin_obc_end(cs%Kelvin_OBC_CSp)
   if (associated(cs)) deallocate(cs)
update_obc_data()
subroutine, public mom_boundary_update::update_obc_data (type(ocean_obc_type), pointer OBC, type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, type(thermo_var_ptrs), intent(in) tv, real, dimension(g %isd: g %ied, g %jsd: g %jed, g %ke), intent(inout) h, type(update_obc_cs), pointer CS, type(time_type), intent(in) Time)
Calls appropriate routine to update the open boundary conditions.
Parameters
[in] g Ocean grid structure
[in] gv Ocean vertical grid structure
[in] tv Thermodynamics structure
[in,out] h layer thickness
obc Open boundary structure
cs Control structure for OBCs
[in] time Model time
Definition at line 99 of file MOM_boundary_update.F90.
Referenced by mom_dynamics_legacy_split::step_mom_dyn_legacy_split(), mom_dynamics_split_rk2::step_mom_dyn_split_rk2(), mom_dynamics_unsplit::step_mom_dyn_unsplit(), and mom_dynamics_unsplit_rk2::step_mom_dyn_unsplit_rk2().
   type(ocean_grid_type),                    intent(in) :: g     !< Ocean grid structure
   type(verticalgrid_type),                  intent(in)    :: gv !< Ocean vertical grid structure
   type(thermo_var_ptrs),                    intent(in)    :: tv !< Thermodynamics structure
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)), intent(inout) :: h  !< layer thickness
   type(ocean_obc_type),                     pointer    :: obc   !< Open boundary structure
   type(update_obc_cs),                      pointer    :: cs    !< Control structure for OBCs
   type(time_type),                          intent(in) :: time  !< Model time
   ! Local variables
   logical :: read_obc_eta = .false.
   logical :: read_obc_uv = .false.
   logical :: read_obc_ts = .false.
   integer :: i, j, k, itt, is, ie, js, je, isd, ied, jsd, jed, nz
   integer :: isd_off, jsd_off
   integer :: isdb, iedb, jsdb, jedb
   character(len=40)  :: mdl = "update_OBC_data" ! This subroutine's name.
   character(len=200) :: filename, obc_file, inputdir ! Strings for file/path
   is = g%isc ; ie = g%iec ; js = g%jsc ; je = g%jec ; nz = g%ke
   isd = g%isd ; ied = g%ied ; jsd = g%jsd ; jed = g%jed
   isdb = g%IsdB ; iedb = g%IedB ; jsdb = g%JsdB ; jedb = g%JedB
 ! Something here... with CS%file_OBC_CSp?
 ! if (CS%use_files) &
 !     call update_OBC_segment_data(G, GV, OBC, tv, h, Time)
   if (cs%use_tidal_bay) &
       call tidal_bay_set_obc_data(obc, cs%tidal_bay_OBC_CSp, g, h, time)
   if (cs%use_Kelvin)  &
       call kelvin_set_obc_data(obc, cs%Kelvin_OBC_CSp, g, h, time)
   if (cs%use_shelfwave) &
       call shelfwave_set_obc_data(obc, cs%shelfwave_OBC_CSp, g, h, time)
   if (obc%needs_IO_for_data)  &
       call update_obc_segment_data(g, gv, obc, tv, h, time)
Variable Documentation
id_clock_pass
integer mom_boundary_update::id_clock_pass
Definition at line 44 of file MOM_boundary_update.F90.
 integer :: id_clock_pass
mdl
character(len=40) mom_boundary_update::mdl = "MOM_boundary_update" private
Definition at line 46 of file MOM_boundary_update.F90.
 character(len=40)  :: mdl = "MOM_boundary_update" ! This module's name.