MOM6: mom_vert_friction Module Reference
mom_vert_friction Module Reference
Detailed Description
Implements vertical viscosity (vertvisc)
Author
Robert Hallberg
Date
April 1994 - October 2006
The vertical diffusion of momentum is fully implicit. This is necessary to allow for vanishingly small layers. The coupling is based on the distance between the centers of adjacent layers, except where a layer is close to the bottom compared with a bottom boundary layer thickness when a bottom drag law is used. A stress top b.c. and a no slip bottom b.c. are used. There is no limit on the time step for vertvisc.
Near the bottom, the horizontal thickness interpolation scheme changes to an upwind biased estimate to control the effect of spurious Montgomery potential gradients at the bottom where nearly massless layers layers ride over the topography. Within a few boundary layer depths of the bottom, the harmonic mean thickness (i.e. (2 h+ h-) / (h+ + h-)) is used if the velocity is from the thinner side and the arithmetic mean thickness (i.e. (h+ + h-)/2) is used if the velocity is from the thicker side. Both of these thickness estimates are second order accurate. Above this the arithmetic mean thickness is used.
In addition, vertvisc truncates any velocity component that exceeds maxvel to truncvel. This basically keeps instabilities spatially localized. The number of times the velocity is truncated is reported each time the energies are saved, and if exceeds CSMaxtrunc the model will stop itself and change the time to a large value. This has proven very useful in (1) diagnosing model failures and (2) letting the model settle down to a meaningful integration from a poorly specified initial condition.
The same code is used for the two velocity components, by indirectly referencing the velocities and defining a handful of direction-specific defined variables.
Macros written all in capital letters are defined in MOM_memory.h.
A small fragment of the grid is shown below:
    j+1  x ^ x ^ x   At x:  q
    j+1  > o > o >   At ^:  v, frhatv, tauy
    j    x ^ x ^ x   At >:  u, frhatu, taux
    j    > o > o >   At o:  h
    j-1  x ^ x ^ x
        i-1  i  i+1  At x & ^:
           i  i+1    At > & o:
The boundaries always run through q grid points (x).
Data Types
type vertvisc_cs
Functions/Subroutines
subroutine, public vertvisc (u, v, h, fluxes, visc, dt, OBC, ADp, CDp, G, GV, CS, taux_bot, tauy_bot)
Perform a fully implicit vertical diffusion of momentum. Stress top and bottom boundary conditions are used.
subroutine, public vertvisc_remnant (visc, visc_rem_u, visc_rem_v, dt, G, GV, CS)
Calculate the fraction of momentum originally in a layer that remains after a time-step of viscosity, and the fraction of a time-step's worth of barotropic acceleration that a layer experiences after viscosity is applied.
subroutine, public vertvisc_coef (u, v, h, fluxes, visc, dt, G, GV, CS, OBC)
Calculate the coupling coefficients (CSa_u and CSa_v) and effective layer thicknesses (CSh_u and CSh_v) for later use in the applying the implicit vertical viscosity via vertvisc().
subroutine find_coupling_coef (a, hvel, do_i, h_harm, bbl_thick, kv_bbl, z_i, h_ml, dt, j, G, GV, CS, visc, fluxes, work_on_u, OBC, shelf)
Calculate the 'coupling coefficient' (a[k]) at the interfaces. If BOTTOMDRAGLAW is defined, the minimum of Hbbl and half the adjacent layer thicknesses are used to calculate a[k] near the bottom.
subroutine, public vertvisc_limit_vel (u, v, h, ADp, CDp, fluxes, visc, dt, G, GV, CS)
Velocity components which exceed a threshold for physically reasonable values are truncated. Optionally, any column with excessive velocities may be sent to a diagnostic reporting subroutine.
subroutine, public vertvisc_init (MIS, Time, G, GV, param_file, diag, ADp, dirs, ntrunc, CS)
Initialise the vertical friction module.
subroutine, public updatecfltruncationvalue (Time, CS, activate)
Update the CFL truncation value as a function of time. If called with the optional argument activate=.true., record the value of Time as the beginning of the ramp period.
subroutine, public vertvisc_end (CS)
Clean up and deallocate the vertical friction module.
Function/Subroutine Documentation
find_coupling_coef()
subroutine mom_vert_friction::find_coupling_coef (real, dimension(g %isdb: g %iedb, gv %ke+1), intent(out) a, real, dimension(g %isdb: g %iedb, gv %ke), intent(in) hvel, logical, dimension(g %isdb: g %iedb), intent(in) do_i, real, dimension(g %isdb: g %iedb, gv %ke), intent(in) h_harm, real, dimension(g %isdb: g %iedb), intent(in) bbl_thick, real, dimension(g %isdb: g %iedb), intent(in) kv_bbl, real, dimension(g %isdb: g %iedb, gv %ke+1), intent(in) z_i, real, dimension(g %isdb: g %iedb), intent(out) h_ml, real, intent(in) dt, integer, intent(in) j, type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, type(vertvisc_cs), pointer CS, type(vertvisc_type), intent(in) visc, type(forcing), intent(in) fluxes, logical, intent(in) work_on_u, type(ocean_obc_type), pointer OBC, logical, intent(in), optional shelf) private
Calculate the 'coupling coefficient' (a[k]) at the interfaces. If BOTTOMDRAGLAW is defined, the minimum of Hbbl and half the adjacent layer thicknesses are used to calculate a[k] near the bottom.
Parameters
[in] g Ocean grid structure
[in] gv Ocean vertical grid structure
[out] a Coupling coefficient across interfaces, in m s-1
[in] hvel Thickness at velocity points, in H
[in] do_i If true, determine coupling coefficient for a column
[in] h_harm Harmonic mean of thicknesses around a velocity grid point, in H
[in] bbl_thick Bottom boundary layer thickness, in H
[in] kv_bbl Bottom boundary layer viscosity, in m2 s-1
[in] z_i Estimate of interface heights above the bottom, normalised by the bottom boundary layer thickness
[out] h_ml Mixed layer depth, in H
[in] j j-index to find coupling coefficient for
[in] dt Time increment, in s
cs Vertical viscosity control structure
[in] visc Structure containing viscosities and bottom drag
[in] fluxes Structure containing forcing fields
[in] work_on_u If true, u-points are being calculated, otherwise v-points
obc Open boundary condition structure
[in] shelf If present and true, use a surface boundary condition appropriate for an ice shelf.
Definition at line 981 of file MOM_vert_friction.F90.
References mom_open_boundary::obc_direction_n, mom_open_boundary::obc_direction_s, and mom_open_boundary::obc_direction_w.
Referenced by vertvisc_coef().
   type(ocean_grid_type), intent(in)                 :: g  !< Ocean grid structure
   type(verticalgrid_type),               intent(in) :: gv !< Ocean vertical grid structure
   !> Coupling coefficient across interfaces, in m s-1
   real,    dimension(SZIB_(G),SZK_(GV)+1), intent(out) :: a
   !> Thickness at velocity points, in H
   real,    dimension(SZIB_(G),SZK_(GV)),   intent(in)  :: hvel
   !> If true, determine coupling coefficient for a column
   logical, dimension(SZIB_(G)),            intent(in)  :: do_i
   !> Harmonic mean of thicknesses around a velocity grid point, in H
   real,    dimension(SZIB_(G),SZK_(GV)),   intent(in)  :: h_harm
   !> Bottom boundary layer thickness, in H
   real,    dimension(SZIB_(G)),            intent(in)  :: bbl_thick
   !> Bottom boundary layer viscosity, in m2 s-1
   real,    dimension(SZIB_(G)),            intent(in)  :: kv_bbl
   !> Estimate of interface heights above the bottom,
   !! normalised by the bottom boundary layer thickness
   real,    dimension(SZIB_(G),SZK_(GV)+1), intent(in)  :: z_i
   !> Mixed layer depth, in H
   real,    dimension(SZIB_(G)),         intent(out) :: h_ml
   !> j-index to find coupling coefficient for
   integer,                              intent(in)  :: j
   !> Time increment, in s
   real,                                 intent(in)  :: dt
   !> Vertical viscosity control structure
   type(vertvisc_cs), pointer                        :: cs
   !> Structure containing viscosities and bottom drag
   type(vertvisc_type), intent(in)                   :: visc
   !> Structure containing forcing fields
   type(forcing), intent(in)                         :: fluxes
   !> If true, u-points are being calculated, otherwise v-points
   logical,                              intent(in)  :: work_on_u
   !> Open boundary condition structure
   type(ocean_obc_type),  pointer         :: obc
   !> If present and true, use a surface boundary condition
   !! appropriate for an ice shelf.
   logical, optional,                    intent(in)  :: shelf
   ! Local variables
   real, dimension(SZIB_(G)) :: &
     u_star, &   ! ustar at a velocity point, in m s-1.
     absf, &     ! The average of the neighboring absolute values of f, in s-1.
 !      h_ml, &     ! The mixed layer depth, in m or kg m-2.
     nk_visc, &  ! The (real) interface index of the base of mixed layer.
     z_t, &      ! The distance from the top, sometimes normalized
                 ! by Hmix, in m or nondimensional.
     kv_tbl, &
     tbl_thick
   real, dimension(SZIB_(G),SZK_(GV)) :: &
     kv_add      ! A viscosity to add, in m2 s-1.
   real :: h_shear ! The distance over which shears occur, m or kg m-2.
   real :: r       ! A thickness to compare with Hbbl, in m or kg m-2.
   real :: visc_ml ! The mixed layer viscosity, in m2 s-1.
   real :: i_hmix  ! The inverse of the mixed layer thickness, in m-1 or m2 kg-1.
   real :: a_ml    ! The layer coupling coefficient across an interface in
                   ! the mixed layer, in m s-1.
   real :: temp1   ! A temporary variable in m2 s-1.
   real :: h_neglect   ! A thickness that is so small it is usually lost
                       ! in roundoff and can be neglected, in H.
   real :: dz_neglect  ! A thickness in m that is so small it is usually lost
                       ! in roundoff and can be neglected, in m.
   real :: z2      ! A copy of z_i, nondim.
   real :: h_to_m, m_to_h ! Unit conversion factors.
   real :: topfn
   real :: a_top
   logical :: do_shelf, do_obcs
   integer :: i, k, is, ie, max_nk
   integer :: nz
   real    :: botfn
   a(:,:) = 0.0
   if (work_on_u) then ; is = g%IscB ; ie = g%IecB
   else ; is = g%isc ; ie = g%iec ; endif
   nz = g%ke
   h_neglect = gv%H_subroundoff
   h_to_m = gv%H_to_m ; m_to_h = gv%m_to_H
   dz_neglect = gv%H_subroundoff*gv%H_to_m
   do_shelf = .false. ; if (present(shelf)) do_shelf = shelf
   do_obcs = .false.
   if (associated(obc)) then ; do_obcs = (obc%number_of_segments > 0) ; endif
   h_ml(:) = 0.0
 !    The following loop calculates the vertical average velocity and
 !  surface mixed layer contributions to the vertical viscosity.
   do i=is,ie ; a(i,1) = 0.0 ; enddo
   if ((gv%nkml>0) .or. do_shelf) then ; do k=2,nz ; do i=is,ie
     if (do_i(i)) a(i,k) = 2.0*cs%Kv
   enddo ; enddo ; else
     i_hmix = 1.0 / (cs%Hmix * m_to_h + h_neglect)
     do i=is,ie ; z_t(i) = h_neglect*i_hmix ; enddo
     do k=2,nz ; do i=is,ie ; if (do_i(i)) then
       z_t(i) = z_t(i) + h_harm(i,k-1)*i_hmix
       a(i,k) = 2.0*cs%Kv + 2.0*cs%Kvml / ((z_t(i)*z_t(i)) *  &
                (1.0 + 0.09*z_t(i)*z_t(i)*z_t(i)*z_t(i)*z_t(i)*z_t(i)))
     endif ; enddo ; enddo
   endif
   do i=is,ie ; if (do_i(i)) then
     if (cs%bottomdraglaw) then
       r = hvel(i,nz)*0.5
       if (r < bbl_thick(i)) then
         a(i,nz+1) = 1.0*kv_bbl(i) / (1e-10*dt*kv_bbl(i) + r*h_to_m)
       else
         a(i,nz+1) = 1.0*kv_bbl(i) / (1e-10*dt*kv_bbl(i) + bbl_thick(i)*h_to_m)
       endif
     else
       a(i,nz+1) = 2.0*cs%Kvbbl / (hvel(i,nz)*h_to_m + 2.0e-10*dt*cs%Kvbbl)
     endif
   endif ; enddo
   if (associated(visc%Kv_turb)) then
      ! BGR/ Add factor of 2. * the averaged Kv_turb.
      !      this is needed to reproduce the analytical solution to
      !      a simple diffusion problem, likely due to h_shear being
      !      equal to 2 x \delta z
     if (work_on_u) then
       do k=2,nz ; do i=is,ie ; if (do_i(i)) then
         kv_add(i,k) = (2.*0.5)*(visc%Kv_turb(i,j,k) + visc%Kv_turb(i+1,j,k))
       endif ; enddo ; enddo
       if (do_obcs) then
         do i=is,ie ; if (do_i(i) .and. (obc%segnum_u(i,j) /= obc_none)) then
           if (obc%segment(obc%segnum_u(i,j))%direction == obc_direction_e) then
             do k=2,nz ; kv_add(i,k) = 2.*visc%Kv_turb(i,j,k) ; enddo
           elseif (obc%segment(obc%segnum_u(i,j))%direction == obc_direction_w) then
             do k=2,nz ; kv_add(i,k) = 2.*visc%Kv_turb(i+1,j,k) ; enddo
           endif
         endif ; enddo
       endif
       do k=2,nz ; do i=is,ie ; if (do_i(i)) then
         a(i,k) = a(i,k) + kv_add(i,k)
       endif ; enddo ; enddo
     else
       do k=2,nz ; do i=is,ie ; if (do_i(i)) then
         kv_add(i,k) = (2.*0.5)*(visc%Kv_turb(i,j,k) + visc%Kv_turb(i,j+1,k))
       endif ; enddo ; enddo
       if (do_obcs) then
         do i=is,ie ; if (do_i(i) .and. (obc%segnum_v(i,j) /= obc_none)) then
           if (obc%segment(obc%segnum_v(i,j))%direction == obc_direction_n) then
             do k=2,nz ; kv_add(i,k) = 2.*visc%Kv_turb(i,j,k) ; enddo
           elseif (obc%segment(obc%segnum_v(i,j))%direction == obc_direction_s) then
             do k=2,nz ; kv_add(i,k) = 2.*visc%Kv_turb(i,j+1,k) ; enddo
           endif
         endif ; enddo
       endif
       do k=2,nz ; do i=is,ie ; if (do_i(i)) then
         a(i,k) = a(i,k) + kv_add(i,k)
       endif ; enddo ; enddo
     endif
   endif
   do k=nz,2,-1 ; do i=is,ie ; if (do_i(i)) then
     !    botfn determines when a point is within the influence of the bottom
     !  boundary layer, going from 1 at the bottom to 0 in the interior.
     z2 = z_i(i,k)
     botfn = 1.0 / (1.0 + 0.09*z2*z2*z2*z2*z2*z2)
     if (cs%bottomdraglaw) then
       a(i,k) = a(i,k) + 2.0*(kv_bbl(i)-cs%Kv)*botfn
       r = (hvel(i,k)+hvel(i,k-1))
       if (r > 2.0*bbl_thick(i)) then
         h_shear = ((1.0 - botfn) * r + botfn*2.0*bbl_thick(i))
       else
         h_shear = r
       endif
     else
       a(i,k) = a(i,k) + 2.0*(cs%Kvbbl-cs%Kv)*botfn
       h_shear = hvel(i,k) + hvel(i,k-1) + h_neglect
     endif
     !   Up to this point a has units of m2 s-1, but now is converted to m s-1.
     !   The term including 1e-10 in the denominators is here to avoid
     ! truncation error problems in the tridiagonal solver. Effectively, this
     ! sets the maximum coupling coefficient at 1e10 m.
     a(i,k) = a(i,k) / (h_shear*h_to_m + 1.0e-10*dt*a(i,k))
   endif ; enddo ; enddo ! i & k loops
   if (do_shelf) then
     ! Set the coefficients to include the no-slip surface stress.
     do i=is,ie ; if (do_i(i)) then
       if (work_on_u) then
         kv_tbl(i) = visc%kv_tbl_shelf_u(i,j)
         tbl_thick(i) = visc%tbl_thick_shelf_u(i,j) * m_to_h
       else
         kv_tbl(i) = visc%kv_tbl_shelf_v(i,j)
         tbl_thick(i) = visc%tbl_thick_shelf_v(i,j) * m_to_h
       endif
       z_t(i) = 0.0
       ! If a(i,1) were not already 0, it would be added here.
       if (0.5*hvel(i,1) > tbl_thick(i)) then
         a(i,1) = kv_tbl(i) / (tbl_thick(i) *h_to_m + (1.0e-10*dt)*kv_tbl(i))
       else
         a(i,1) = kv_tbl(i) / (0.5*hvel(i,1)*h_to_m + (1.0e-10*dt)*kv_tbl(i))
       endif
     endif ; enddo
     do k=2,nz ; do i=is,ie ;  if (do_i(i)) then
       z_t(i) = z_t(i) + hvel(i,k-1) / tbl_thick(i)
       topfn = 1.0 / (1.0 + 0.09 * z_t(i)**6)
       r = (hvel(i,k)+hvel(i,k-1))
       if (r > 2.0*tbl_thick(i)) then
         h_shear = ((1.0 - topfn) * r + topfn*2.0*tbl_thick(i))
       else
         h_shear = r
       endif
     !   The term including 1e-10 in the denominators is here to avoid
     ! truncation error problems in the tridiagonal solver. Effectively, this
     ! sets the maximum coupling coefficient increment to 1e10 m.
       a_top = 2.0 * topfn * kv_tbl(i)
       a(i,k) = a(i,k) + a_top / (h_shear*h_to_m + 1.0e-10*dt*a_top)
     endif ; enddo ; enddo
   elseif (cs%dynamic_viscous_ML .or. (gv%nkml>0)) then
     max_nk = 0
     do i=is,ie ; if (do_i(i)) then
       if (gv%nkml>0) nk_visc(i) = real(gv%nkml+1)
       if (work_on_u) then
         u_star(i) = 0.5*(fluxes%ustar(i,j) + fluxes%ustar(i+1,j))
         absf(i) = 0.5*(abs(g%CoriolisBu(i,j-1)) + abs(g%CoriolisBu(i,j)))
         if (cs%dynamic_viscous_ML) nk_visc(i) = visc%nkml_visc_u(i,j) + 1
       else
         u_star(i) = 0.5*(fluxes%ustar(i,j) + fluxes%ustar(i,j+1))
         absf(i) = 0.5*(abs(g%CoriolisBu(i-1,j)) + abs(g%CoriolisBu(i,j)))
         if (cs%dynamic_viscous_ML) nk_visc(i) = visc%nkml_visc_v(i,j) + 1
       endif
       h_ml(i) = h_neglect ; z_t(i) = 0.0
       max_nk = max(max_nk,ceiling(nk_visc(i) - 1.0))
     endif ; enddo
     if (do_obcs) then ; if (work_on_u) then
       do i=is,ie ; if (do_i(i) .and. (obc%segnum_u(i,j) /= obc_none)) then
         if (obc%segment(obc%segnum_u(i,j))%direction == obc_direction_e) &
           u_star(i) = fluxes%ustar(i,j)
         if (obc%segment(obc%segnum_u(i,j))%direction == obc_direction_w) &
           u_star(i) = fluxes%ustar(i+1,j)
       endif ; enddo
     else
       do i=is,ie ; if (do_i(i) .and. (obc%segnum_v(i,j) /= obc_none)) then
         if (obc%segment(obc%segnum_v(i,j))%direction == obc_direction_n) &
           u_star(i) = fluxes%ustar(i,j)
         if (obc%segment(obc%segnum_v(i,j))%direction == obc_direction_s) &
           u_star(i) = fluxes%ustar(i,j+1)
       endif ; enddo
     endif ; endif
     do k=1,max_nk ; do i=is,ie ; if (do_i(i)) then
       if (k+1 <= nk_visc(i)) then ! This layer is all in the ML.
         h_ml(i) = h_ml(i) + hvel(i,k)
       elseif (k < nk_visc(i)) then ! Part of this layer is in the ML.
         h_ml(i) = h_ml(i) + (nk_visc(i) - k) * hvel(i,k)
       endif
     endif ; enddo ; enddo
     do k=2,max_nk ; do i=is,ie ; if (do_i(i)) then ; if (k < nk_visc(i)) then
       ! Set the viscosity at the interfaces.
       z_t(i) = z_t(i) + hvel(i,k-1)
       temp1 = (z_t(i)*h_ml(i) - z_t(i)*z_t(i)) * h_to_m
       !   This viscosity is set to go to 0 at the mixed layer top and bottom
       ! (in a log-layer) and be further limited by rotation to give the
       ! natural Ekman length.
       visc_ml = u_star(i) * 0.41 * (temp1*u_star(i)) / &
                      (absf(i)*temp1 + h_ml(i)*u_star(i))
       a_ml = 4.0*visc_ml / ((hvel(i,k)+hvel(i,k-1) + h_neglect) * h_to_m + &
                             2.0e-10*dt*visc_ml)
       ! Choose the largest estimate of a.
       if (a_ml > a(i,k)) a(i,k) = a_ml
     endif ; endif ; enddo ; enddo
   endif
updatecfltruncationvalue()
subroutine, public mom_vert_friction::updatecfltruncationvalue (type(time_type), intent(in), target Time, type(vertvisc_cs), pointer CS, logical, intent(in), optional activate)
Update the CFL truncation value as a function of time. If called with the optional argument activate=.true., record the value of Time as the beginning of the ramp period.
Parameters
[in] time Current model time
cs Vertical viscosity control structure
[in] activate Whether to record the value of Time as the beginning of the ramp period
Definition at line 1637 of file MOM_vert_friction.F90.
References mom_error_handler::mom_error().
Referenced by mom_dynamics_split_rk2::step_mom_dyn_split_rk2().
   type(time_type), target, intent(in)    :: time     !< Current model time
   type(vertvisc_cs),       pointer       :: cs       !< Vertical viscosity control structure
   !> Whether to record the value of Time as the beginning of the ramp period
   logical, optional,       intent(in)    :: activate
   ! Local variables
   real :: deltatime, wghta
   character(len=12) :: msg
   if (cs%truncRampTime==0.) return ! This indicates to ramping is turned off
   ! We use the optional argument to indicate this Time should be recorded as the
   ! beginning of the ramp-up period.
   if (present(activate)) then
     if (activate) then
       cs%rampStartTime = time ! Record the current time
       cs%CFLrampingIsActivated = .true.
     endif
   endif
   if (.not.cs%CFLrampingIsActivated) return
   deltatime = max( 0., time_type_to_real( time - cs%rampStartTime ) )
   if (deltatime >= cs%truncRampTime) then
     cs%CFL_trunc = cs%CFL_truncE
     cs%truncRampTime = 0. ! This turns off ramping after this call
   else
     wghta = min( 1., deltatime / cs%truncRampTime ) ! Linear profile in time
     !wghtA = wghtA*wghtA ! Convert linear profile to parabolic profile in time
     !wghtA = wghtA*wghtA*(3. - 2.*wghtA) ! Convert linear profile to cosine profile
     wghta = 1. - ( (1. - wghta)**2 ) ! Convert linear profiel to nverted parabolic profile
     cs%CFL_trunc = cs%CFL_truncS + wghta * ( cs%CFL_truncE - cs%CFL_truncS )
   endif
   write(msg(1:12),'(es12.3)') cs%CFL_trunc
   call mom_error(note, "MOM_vert_friction: updateCFLtruncationValue set CFL"// &
                        " limit to "//trim(msg))
vertvisc()
subroutine, public mom_vert_friction::vertvisc (real, dimension(szib_(g),szj_(g),szk_(gv)), intent(inout) u, real, dimension(szi_(g),szjb_(g),szk_(gv)), intent(inout) v, real, dimension(szi_(g),szj_(g),szk_(gv)), intent(in) h, type(forcing), intent(in) fluxes, type(vertvisc_type), intent(inout) visc, real, intent(in) dt, type(ocean_obc_type), pointer OBC, type(accel_diag_ptrs), intent(inout) ADp, type(cont_diag_ptrs), intent(inout) CDp, type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, type(vertvisc_cs), pointer CS, real, dimension(szib_(g),szj_(g)), intent(out), optional taux_bot, real, dimension(szi_(g),szjb_(g)), intent(out), optional tauy_bot)
Perform a fully implicit vertical diffusion of momentum. Stress top and bottom boundary conditions are used.
This is solving the tridiagonal system
\[ \left(h_k + a_{k + 1/2} + a_{k - 1/2} + r_k\right) u_k^{n+1} = h_k u_k^n + a_{k + 1/2} u_{k+1}^{n+1} + a_{k - 1/2} u_{k-1}^{n+1} \]
where \(a_{k + 1/2} = \Delta t \nu_{k + 1/2} / h_{k + 1/2}\) is the interfacial coupling thickness per time step, encompassing background viscosity as well as contributions from enhanced mixed and bottom layer viscosities. $r_k$ is a Rayleight drag term due to channel drag. There is an additional stress term on the right-hand side if DIRECT_STRESS is true, applied to the surface layer.
Parameters
[in] g Ocean grid structure
[in] gv Ocean vertical grid structure
[in,out] u Zonal velocity in m s-1
[in,out] v Meridional velocity in m s-1
[in] h Layer thickness in H
[in] fluxes Structure containing forcing fields
[in,out] visc Viscosities and bottom drag
[in] dt Time increment in s
obc Open boundary condition structure
[in,out] adp Accelerations in the momentum equations for diagnostics
[in,out] cdp Continuity equation terms
cs Vertical viscosity control structure
[out] taux_bot Zonal bottom stress from ocean to rock in Pa
[out] tauy_bot Meridional bottom stress from ocean to rock in Pa
Definition at line 140 of file MOM_vert_friction.F90.
References mom_error_handler::mom_error(), and vertvisc_limit_vel().
   type(ocean_grid_type),   intent(in)    :: g      !< Ocean grid structure
   type(verticalgrid_type), intent(in)    :: gv     !< Ocean vertical grid structure
   real, intent(inout), &
     dimension(SZIB_(G),SZJ_(G),SZK_(GV)) :: u      !< Zonal velocity in m s-1
   real, intent(inout), &
     dimension(SZI_(G),SZJB_(G),SZK_(GV)) :: v      !< Meridional velocity in m s-1
   real, intent(in), &
     dimension(SZI_(G),SZJ_(G),SZK_(GV))  :: h      !< Layer thickness in H
   type(forcing),         intent(in)      :: fluxes !< Structure containing forcing fields
   type(vertvisc_type),   intent(inout)   :: visc   !< Viscosities and bottom drag
   real,                  intent(in)      :: dt     !< Time increment in s
   type(ocean_obc_type),  pointer         :: obc    !< Open boundary condition structure
   type(accel_diag_ptrs), intent(inout)   :: adp    !< Accelerations in the momentum
                                                    !! equations for diagnostics
   type(cont_diag_ptrs),  intent(inout)   :: cdp    !< Continuity equation terms
   type(vertvisc_cs),     pointer         :: cs     !< Vertical viscosity control structure
   !> Zonal bottom stress from ocean to rock in Pa
   real, optional, intent(out), dimension(SZIB_(G),SZJ_(G)) :: taux_bot
   !> Meridional bottom stress from ocean to rock in Pa
   real, optional, intent(out), dimension(SZI_(G),SZJB_(G)) :: tauy_bot
   ! Fields from fluxes used in this subroutine:
   !   taux: Zonal wind stress in Pa.
   !   tauy: Meridional wind stress in Pa.
   ! Local variables
   real :: b1(szib_(g))          ! b1 and c1 are variables used by the
   real :: c1(szib_(g),szk_(g))  ! tridiagonal solver.  c1 is nondimensional,
                                 ! while b1 has units of inverse thickness.
   real :: d1(szib_(g))          ! d1=1-c1 is used by the tridiagonal solver, ND.
   real :: ray(szib_(g),szk_(g)) ! Ray is the Rayleigh-drag velocity in m s-1
   real :: b_denom_1             ! The first term in the denominator of b1, in H.
   real :: hmix             ! The mixed layer thickness over which stress
                            ! is applied with direct_stress, translated into
                            ! thickness units - either m or kg m-2.
   real :: i_hmix           ! The inverse of Hmix, in m-1 or m2 kg-1.
   real :: idt              ! The inverse of the time step, in s-1.
   real :: dt_rho0          ! The time step divided by the mean
                            ! density, in s m3 kg-1.
   real :: rho0             ! A density used to convert drag laws into stress in
                            ! Pa, in kg m-3.
   real :: dt_m_to_h        ! The time step times the conversion from m to the
                            ! units of thickness - either s or s m3 kg-1.
   real :: h_neglect        ! A thickness that is so small it is usually lost
                            ! in roundoff and can be neglected, in m or kg m-2.
   real :: stress           !   The surface stress times the time step, divided
                            ! by the density, in units of m2 s-1.
   real :: zds, hfr, h_a    ! Temporary variables used with direct_stress.
   real :: surface_stress(szib_(g))! The same as stress, unless the wind
                            ! stress is applied as a body force, in
                            ! units of m2 s-1.
   logical :: do_i(szib_(g))
   integer :: i, j, k, is, ie, isq, ieq, jsq, jeq, nz, n
   is = g%isc ; ie = g%iec
   isq = g%IscB ; ieq = g%IecB ; jsq = g%JscB ; jeq = g%JecB ; nz = g%ke
   if (.not.associated(cs)) call mom_error(fatal,"MOM_vert_friction(visc): "// &
          "Module must be initialized before it is used.")
   if (cs%direct_stress) then
     hmix = cs%Hmix_stress*gv%m_to_H
     i_hmix = 1.0 / hmix
   endif
   dt_rho0 = dt/gv%H_to_kg_m2
   dt_m_to_h = dt*gv%m_to_H
   rho0 = gv%Rho0
   h_neglect = gv%H_subroundoff
   idt = 1.0 / dt
   do k=1,nz ; do i=isq,ieq ; ray(i,k) = 0.0 ; enddo ; enddo
   !   Update the zonal velocity component using a modification of a standard
   ! tridagonal solver.
 !$OMP parallel do default(none) shared(G,Isq,Ieq,ADp,nz,u,CS,dt_Rho0,fluxes,h, &
 !$OMP                                  h_neglect,Hmix,I_Hmix,visc,dt_m_to_H,   &
 !$OMP                                  Idt,taux_bot,Rho0)                      &
 !$OMP                     firstprivate(Ray)                                    &
 !$OMP                          private(do_i,surface_stress,zDS,stress,h_a,hfr, &
 !$OMP                                     b_denom_1,b1,d1,c1)
   do j=g%jsc,g%jec
     do i=isq,ieq ; do_i(i) = (g%mask2dCu(i,j) > 0) ; enddo
     if (ASSOCIATED(adp%du_dt_visc)) then ; do k=1,nz ; do i=isq,ieq
       adp%du_dt_visc(i,j,k) = u(i,j,k)
     enddo ; enddo ; endif
 !   One option is to have the wind stress applied as a body force
 ! over the topmost Hmix fluid.  If DIRECT_STRESS is not defined,
 ! the wind stress is applied as a stress boundary condition.
     if (cs%direct_stress) then
       do i=isq,ieq ; if (do_i(i)) then
         surface_stress(i) = 0.0
         zds = 0.0
         stress = dt_rho0 * fluxes%taux(i,j)
         do k=1,nz
           h_a = 0.5 * (h(i,j,k) + h(i+1,j,k)) + h_neglect
           hfr = 1.0 ; if ((zds+h_a) > hmix) hfr = (hmix - zds) / h_a
           u(i,j,k) = u(i,j,k) + i_hmix * hfr * stress
           zds = zds + h_a ; if (zds >= hmix) exit
         enddo
       endif ; enddo ! end of i loop
     else ; do i=isq,ieq
       surface_stress(i) = dt_rho0 * (g%mask2dCu(i,j)*fluxes%taux(i,j))
     enddo ; endif ! direct_stress
     if (cs%Channel_drag) then ; do k=1,nz ; do i=isq,ieq
       ray(i,k) = visc%Ray_u(i,j,k)
     enddo ; enddo ; endif
     ! perform forward elimination on the tridiagonal system
     !
     ! denote the diagonal of the system as b_k, the subdiagonal as a_k
     ! and the superdiagonal as c_k. The right-hand side terms are d_k.
     !
     ! ignoring the rayleigh drag contribution,
     ! we have a_k = -dt_m_to_H * a_u(k)
     !         b_k = h_u(k) + dt_m_to_H * (a_u(k) + a_u(k+1))
     !         c_k = -dt_m_to_H * a_u(k+1)
     !
     ! for forward elimination, we want to:
     ! calculate c'_k = - c_k                / (b_k + a_k c'_(k-1))
     ! and       d'_k = (d_k - a_k d'_(k-1)) / (b_k + a_k c'_(k-1))
     ! where c'_1 = c_1/b_1 and d'_1 = d_1/b_1
     ! (see Thomas' tridiagonal matrix algorithm)
     !
     ! b1 is the denominator term 1 / (b_k + a_k c'_(k-1))
     ! b_denom_1 is (b_k + a_k + c_k) - a_k(1 - c'_(k-1))
     !            = (b_k + c_k + c'_(k-1))
     ! this is done so that d1 = b1 * b_denom_1 = 1 - c'_(k-1)
     ! c1(k) is -c'_(k - 1)
     ! and the right-hand-side is destructively updated to be d'_k
     !
     do i=isq,ieq ; if (do_i(i)) then
       b_denom_1 = cs%h_u(i,j,1) + dt_m_to_h * (ray(i,1) + cs%a_u(i,j,1))
       b1(i) = 1.0 / (b_denom_1 + dt_m_to_h*cs%a_u(i,j,2))
       d1(i) = b_denom_1 * b1(i)
       u(i,j,1) = b1(i) * (cs%h_u(i,j,1) * u(i,j,1) + surface_stress(i))
     endif ; enddo
     do k=2,nz ; do i=isq,ieq ; if (do_i(i)) then
       c1(i,k) = dt_m_to_h * cs%a_u(i,j,k) * b1(i)
       b_denom_1 = cs%h_u(i,j,k) + dt_m_to_h * (ray(i,k) + cs%a_u(i,j,k)*d1(i))
       b1(i) = 1.0 / (b_denom_1 + dt_m_to_h * cs%a_u(i,j,k+1))
       d1(i) = b_denom_1 * b1(i)
       u(i,j,k) = (cs%h_u(i,j,k) * u(i,j,k) + &
                   dt_m_to_h * cs%a_u(i,j,k) * u(i,j,k-1)) * b1(i)
     endif ; enddo ; enddo
     ! back substitute to solve for the new velocities
     ! u_k = d'_k - c'_k x_(k+1)
     do k=nz-1,1,-1 ; do i=isq,ieq ; if (do_i(i)) then
       u(i,j,k) = u(i,j,k) + c1(i,k+1) * u(i,j,k+1)
     endif ; enddo ; enddo ! i and k loops
     if (ASSOCIATED(adp%du_dt_visc)) then ; do k=1,nz ; do i=isq,ieq
       adp%du_dt_visc(i,j,k) = (u(i,j,k) - adp%du_dt_visc(i,j,k))*idt
     enddo ; enddo ; endif
     if (ASSOCIATED(visc%taux_shelf)) then ; do i=isq,ieq
       visc%taux_shelf(i,j) = -rho0*cs%a1_shelf_u(i,j)*u(i,j,1) ! - u_shelf?
     enddo ; endif
     if (PRESENT(taux_bot)) then
       do i=isq,ieq
         taux_bot(i,j) = rho0 * (u(i,j,nz)*cs%a_u(i,j,nz+1))
       enddo
       if (cs%Channel_drag) then ; do k=1,nz ; do i=isq,ieq
         taux_bot(i,j) = taux_bot(i,j) + rho0 * (ray(i,k)*u(i,j,k))
       enddo ; enddo ; endif
     endif
   enddo ! end u-component j loop
   ! Now work on the meridional velocity component.
 !$OMP parallel do default(none) shared(G,Jsq,Jeq,ADp,nz,v,CS,dt_Rho0,fluxes,h, &
 !$OMP                                  Hmix,I_Hmix,visc,dt_m_to_H,Idt,Rho0,    &
 !$OMP                                  tauy_bot,is,ie)                         &
 !$OMP                     firstprivate(Ray)                                    &
 !$OMP                          private(do_i,surface_stress,zDS,stress,h_a,hfr, &
 !$OMP                                  b_denom_1,b1,d1,c1)
   do j=jsq,jeq
     do i=is,ie ; do_i(i) = (g%mask2dCv(i,j) > 0) ; enddo
     if (ASSOCIATED(adp%dv_dt_visc)) then ; do k=1,nz ; do i=is,ie
       adp%dv_dt_visc(i,j,k) = v(i,j,k)
     enddo ; enddo ; endif
 !   One option is to have the wind stress applied as a body force
 ! over the topmost Hmix fluid.  If DIRECT_STRESS is not defined,
 ! the wind stress is applied as a stress boundary condition.
     if (cs%direct_stress) then
       do i=is,ie ; if (do_i(i)) then
         surface_stress(i) = 0.0
         zds = 0.0
         stress = dt_rho0 * fluxes%tauy(i,j)
         do k=1,nz
           h_a = 0.5 * (h(i,j,k) + h(i,j+1,k))
           hfr = 1.0 ; if ((zds+h_a) > hmix) hfr = (hmix - zds) / h_a
           v(i,j,k) = v(i,j,k) + i_hmix * hfr * stress
           zds = zds + h_a ; if (zds >= hmix) exit
         enddo
       endif ; enddo ! end of i loop
     else ; do i=is,ie
       surface_stress(i) = dt_rho0 * (g%mask2dCv(i,j)*fluxes%tauy(i,j))
     enddo ; endif ! direct_stress
     if (cs%Channel_drag) then ; do k=1,nz ; do i=is,ie
       ray(i,k) = visc%Ray_v(i,j,k)
     enddo ; enddo ; endif
     do i=is,ie ; if (do_i(i)) then
       b_denom_1 = cs%h_v(i,j,1) + dt_m_to_h * (ray(i,1) + cs%a_v(i,j,1))
       b1(i) = 1.0 / (b_denom_1 + dt_m_to_h*cs%a_v(i,j,2))
       d1(i) = b_denom_1 * b1(i)
       v(i,j,1) = b1(i) * (cs%h_v(i,j,1) * v(i,j,1) + surface_stress(i))
     endif ; enddo
     do k=2,nz ; do i=is,ie ; if (do_i(i)) then
       c1(i,k) = dt_m_to_h * cs%a_v(i,j,k) * b1(i)
       b_denom_1 = cs%h_v(i,j,k) + dt_m_to_h *  (ray(i,k) + cs%a_v(i,j,k)*d1(i))
       b1(i) = 1.0 / (b_denom_1 + dt_m_to_h * cs%a_v(i,j,k+1))
       d1(i) = b_denom_1 * b1(i)
       v(i,j,k) = (cs%h_v(i,j,k) * v(i,j,k) + dt_m_to_h * &
                   cs%a_v(i,j,k) * v(i,j,k-1)) * b1(i)
     endif ; enddo ; enddo
     do k=nz-1,1,-1 ; do i=is,ie ; if (do_i(i)) then
       v(i,j,k) = v(i,j,k) + c1(i,k+1) * v(i,j,k+1)
     endif ; enddo ; enddo ! i and k loops
     if (ASSOCIATED(adp%dv_dt_visc)) then ; do k=1,nz ; do i=is,ie
       adp%dv_dt_visc(i,j,k) = (v(i,j,k) - adp%dv_dt_visc(i,j,k))*idt
     enddo ; enddo ; endif
     if (ASSOCIATED(visc%tauy_shelf)) then ; do i=is,ie
       visc%tauy_shelf(i,j) = -rho0*cs%a1_shelf_v(i,j)*v(i,j,1) ! - v_shelf?
     enddo ; endif
     if (present(tauy_bot)) then
       do i=is,ie
         tauy_bot(i,j) = rho0 * (v(i,j,nz)*cs%a_v(i,j,nz+1))
       enddo
       if (cs%Channel_drag) then ; do k=1,nz ; do i=is,ie
         tauy_bot(i,j) = tauy_bot(i,j) + rho0 * (ray(i,k)*v(i,j,k))
       enddo ; enddo ; endif
     endif
   enddo ! end of v-component J loop
   call vertvisc_limit_vel(u, v, h, adp, cdp, fluxes, visc, dt, g, gv, cs)
   ! Here the velocities associated with open boundary conditions are applied.
   if (associated(obc)) then
     do n=1,obc%number_of_segments
       if (obc%segment(n)%specified) then
         if (obc%segment(n)%is_N_or_S) then
           j = obc%segment(n)%HI%JsdB
           do k=1,nz ; do i=obc%segment(n)%HI%isd,obc%segment(n)%HI%ied
             v(i,j,k) = obc%segment(n)%normal_vel(i,j,k)
           enddo ; enddo
         elseif (obc%segment(n)%is_E_or_W) then
           i = obc%segment(n)%HI%IsdB
           do k=1,nz ; do j=obc%segment(n)%HI%jsd,obc%segment(n)%HI%jed
             u(i,j,k) = obc%segment(n)%normal_vel(i,j,k)
           enddo ; enddo
         endif
       endif
     enddo
   endif
 ! Offer diagnostic fields for averaging.
   if (cs%id_du_dt_visc > 0) &
     call post_data(cs%id_du_dt_visc, adp%du_dt_visc, cs%diag)
   if (cs%id_dv_dt_visc > 0) &
     call post_data(cs%id_dv_dt_visc, adp%dv_dt_visc, cs%diag)
   if (present(taux_bot) .and. (cs%id_taux_bot > 0)) &
     call post_data(cs%id_taux_bot, taux_bot, cs%diag)
   if (present(tauy_bot) .and. (cs%id_tauy_bot > 0)) &
     call post_data(cs%id_tauy_bot, tauy_bot, cs%diag)
vertvisc_coef()
subroutine, public mom_vert_friction::vertvisc_coef (real, dimension(g %isdb: g %iedb, g %jsd: g %jed, gv %ke), intent(in) u, real, dimension(g %isd: g %ied, g %jsdb: g %jedb, gv %ke), intent(in) v, real, dimension(g %isd: g %ied, g %jsd: g %jed, gv %ke), intent(in) h, type(forcing), intent(in) fluxes, type(vertvisc_type), intent(in) visc, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, type(vertvisc_cs), pointer CS, type(ocean_obc_type), pointer OBC)
Calculate the coupling coefficients (CSa_u and CSa_v) and effective layer thicknesses (CSh_u and CSh_v) for later use in the applying the implicit vertical viscosity via vertvisc().
Parameters
[in] g Ocean grid structure
[in] gv Ocean vertical grid structure
[in] u Zonal velocity in m s-1
[in] v Meridional velocity in m s-1
[in] h Layer thickness in H
[in] fluxes Structure containing forcing fields
[in] visc Viscosities and bottom drag
[in] dt Time increment in s
cs Vertical viscosity control structure
obc Open boundary condition structure
Definition at line 534 of file MOM_vert_friction.F90.
References find_coupling_coef(), mom_error_handler::mom_error(), mom_open_boundary::obc_direction_n, mom_open_boundary::obc_direction_s, and mom_open_boundary::obc_direction_w.
   type(ocean_grid_type), intent(in)      :: g      !< Ocean grid structure
   type(verticalgrid_type), intent(in)    :: gv     !< Ocean vertical grid structure
   real, intent(in), &
     dimension(SZIB_(G),SZJ_(G),SZK_(GV)) :: u      !< Zonal velocity in m s-1
   real, intent(in), &
     dimension(SZI_(G),SZJB_(G),SZK_(GV)) :: v      !< Meridional velocity in m s-1
   real, intent(in), &
     dimension(SZI_(G),SZJ_(G),SZK_(GV))  :: h      !< Layer thickness in H
   type(forcing), intent(in)              :: fluxes !< Structure containing forcing fields
   type(vertvisc_type), intent(in)        :: visc   !< Viscosities and bottom drag
   real, intent(in)                       :: dt     !< Time increment in s
   type(vertvisc_cs), pointer             :: cs     !< Vertical viscosity control structure
   type(ocean_obc_type),  pointer         :: obc    !< Open boundary condition structure
   ! Field from fluxes used in this subroutine:
   !   ustar: the friction velocity in m s-1, used here as the mixing
   !     velocity in the mixed layer if NKML > 1 in a bulk mixed layer.
   ! Local variables
   real, dimension(SZIB_(G),SZK_(G)) :: &
     h_harm, &   ! Harmonic mean of the thicknesses around a velocity grid point,
                 ! given by 2*(h+ * h-)/(h+ + h-), in m or kg m-2 (H for short).
     h_arith, &  ! The arithmetic mean thickness, in m or kg m-2.
     hvel, &     ! hvel is the thickness used at a velocity grid point, in H.
     hvel_shelf  ! The equivalent of hvel under shelves, in H.
   real, dimension(SZIB_(G),SZK_(G)+1) :: &
     a, &        ! The drag coefficients across interfaces, in m s-1.  a times
                 ! the velocity difference gives the stress across an interface.
     a_shelf, &  ! The drag coefficients across interfaces in water columns under
                 ! ice shelves, in m s-1.
     z_i         ! An estimate of each interface's height above the bottom,
                 ! normalized by the bottom boundary layer thickness, nondim.
   real, dimension(SZIB_(G)) :: &
     kv_bbl, &     ! The bottom boundary layer viscosity in m2 s-1.
     bbl_thick, &  ! The bottom boundary layer thickness in m or kg m-2.
     i_hbbl, &     ! The inverse of the bottom boundary layer thickness, in units
                   ! of H-1 (i.e., m-1 or m2 kg-1).
     i_htbl, &     ! The inverse of the top boundary layer thickness, in units
                   ! of H-1 (i.e., m-1 or m2 kg-1).
     zcol1, &      ! The height of the interfaces to the north and south of a
     zcol2, &      ! v-point, in m or kg m-2.
     ztop_min, &   ! The deeper of the two adjacent surface heights, in H.
     dmin, &       ! The shallower of the two adjacent bottom depths converted to
                   ! thickness units, in m or kg m-2.
     zh, &         ! An estimate of the interface's distance from the bottom
                   ! based on harmonic mean thicknesses, in m or kg m-2.
     h_ml          ! The mixed layer depth, in m or kg m-2.
   real, allocatable, dimension(:,:) :: hml_u, hml_v
   real :: zcol(szi_(g)) ! The height of an interface at h-points, in m or kg m-2.
   real :: botfn   ! A function which goes from 1 at the bottom to 0 much more
                   ! than Hbbl into the interior.
   real :: topfn   ! A function which goes from 1 at the top to 0 much more
                   ! than Htbl into the interior.
   real :: z2      ! The distance from the bottom, normalized by Hbbl, nondim.
   real :: z2_wt   ! A nondimensional (0-1) weight used when calculating z2.
   real :: z_clear ! The clearance of an interface above the surrounding topography, in H.
   real :: h_neglect     ! A thickness that is so small it is usually lost
                         ! in roundoff and can be neglected, in H.
   real :: h_to_m, m_to_h ! Unit conversion factors.
   real :: i_valbl ! The inverse of a scaling factor determining when water is
                   ! still within the boundary layer, as determined by the sum
                   ! of the harmonic mean thicknesses.
   logical, dimension(SZIB_(G)) :: do_i, do_i_shelf
   logical :: do_any_shelf
   integer, dimension(SZIB_(G)) :: &
     zi_dir   !  A trinary logical array indicating which thicknesses to use for
              !  finding z_clear.
   integer :: i, j, k, is, ie, js, je, isq, ieq, jsq, jeq, nz
   is = g%isc ; ie = g%iec ; js = g%jsc ; je = g%jec
   isq = g%IscB ; ieq = g%IecB ; jsq = g%JscB ; jeq = g%JecB ; nz = g%ke
   if (.not.associated(cs)) call mom_error(fatal,"MOM_vert_friction(coef): "// &
          "Module must be initialized before it is used.")
   h_neglect = gv%H_subroundoff
   h_to_m = gv%H_to_m ; m_to_h = gv%m_to_H
   i_hbbl(:) = 1.0 / (cs%Hbbl * gv%m_to_H + h_neglect)
   i_valbl = 0.0 ; if (cs%harm_BL_val > 0.0) i_valbl = 1.0 / cs%harm_BL_val
   if (cs%debug .or. (cs%id_hML_u > 0)) then
     allocate(hml_u(g%IsdB:g%IedB,g%jsd:g%jed)) ; hml_u(:,:) = 0.0
   endif
   if (cs%debug .or. (cs%id_hML_v > 0)) then
     allocate(hml_v(g%isd:g%ied,g%JsdB:g%JedB)) ; hml_v(:,:) = 0.0
   endif
   if ((associated(visc%taux_shelf) .or. associated(fluxes%frac_shelf_u)) .and. &
       .not.associated(cs%a1_shelf_u)) then
     allocate(cs%a1_shelf_u(g%IsdB:g%IedB,g%jsd:g%jed)) ; cs%a1_shelf_u(:,:)=0.0
   endif
   if ((associated(visc%tauy_shelf) .or. associated(fluxes%frac_shelf_u)) .and. &
       .not.associated(cs%a1_shelf_v)) then
     allocate(cs%a1_shelf_v(g%isd:g%ied,g%JsdB:g%JedB)) ; cs%a1_shelf_v(:,:)=0.0
   endif
 !$OMP parallel do default(none) shared(G,GV,CS,visc,Isq,ieq,nz,u,h,fluxes,hML_u, &
 !$OMP                                  OBC,h_neglect,dt,m_to_H,I_valBL) &
 !$OMP                     firstprivate(i_hbbl)                                             &
 !$OMP                          private(do_i,kv_bbl,bbl_thick,z_i,h_harm,h_arith,hvel,z2,   &
 !$OMP                                  botfn,zh,Dmin,zcol,a,do_any_shelf,do_i_shelf,zi_dir, &
 !$OMP                                  a_shelf,Ztop_min,I_HTbl,hvel_shelf,topfn,h_ml,z2_wt,z_clear)
   do j=g%Jsc,g%Jec
     do i=isq,ieq ; do_i(i) = (g%mask2dCu(i,j) > 0) ; enddo
     if (cs%bottomdraglaw) then ; do i=isq,ieq
       kv_bbl(i) = visc%kv_bbl_u(i,j)
       bbl_thick(i) = visc%bbl_thick_u(i,j) * m_to_h
       if (do_i(i)) i_hbbl(i) = 1.0 / (bbl_thick(i) + h_neglect)
     enddo ; endif
     do k=1,nz ; do i=isq,ieq ; if (do_i(i)) then
       h_harm(i,k) = 2.0*h(i,j,k)*h(i+1,j,k) / (h(i,j,k)+h(i+1,j,k)+h_neglect)
       h_arith(i,k) = 0.5*(h(i+1,j,k)+h(i,j,k))
     endif ; enddo ; enddo
     do i=isq,ieq
       dmin(i) = min(g%bathyT(i,j), g%bathyT(i+1,j)) * m_to_h
       zi_dir(i) = 0
     enddo
     ! Project thickness outward across OBCs using a zero-gradient condition.
     if (associated(obc)) then ; if (obc%number_of_segments > 0) then
       do i=isq,ieq ; if (do_i(i) .and. (obc%segnum_u(i,j) /= obc_none)) then
         if (obc%segment(obc%segnum_u(i,j))%direction == obc_direction_e) then
           do k=1,nz ; h_harm(i,k) = h(i,j,k) ; h_arith(i,k) = h(i,j,k) ; enddo
           dmin(i) = g%bathyT(i,j) * m_to_h
           zi_dir(i) = -1
         elseif (obc%segment(obc%segnum_u(i,j))%direction == obc_direction_w) then
           do k=1,nz ; h_harm(i,k) = h(i+1,j,k) ; h_arith(i,k) = h(i+1,j,k) ; enddo
           dmin(i) = g%bathyT(i+1,j) * m_to_h
           zi_dir(i) = 1
         endif
       endif ; enddo
     endif ; endif
 !    The following block calculates the thicknesses at velocity
 !  grid points for the vertical viscosity (hvel[k]).  Near the
 !  bottom an upwind biased thickness is used to control the effect
 !  of spurious Montgomery potential gradients at the bottom where
 !  nearly massless layers layers ride over the topography.
     if (cs%harmonic_visc) then
       do i=isq,ieq ; z_i(i,nz+1) = 0.0 ; enddo
       do k=nz,1,-1 ; do i=isq,ieq ; if (do_i(i)) then
         hvel(i,k) = h_harm(i,k)
         if (u(i,j,k) * (h(i+1,j,k)-h(i,j,k)) < 0) then
           z2 = z_i(i,k+1) ; botfn = 1.0 / (1.0 + 0.09*z2*z2*z2*z2*z2*z2)
           hvel(i,k) = (1.0-botfn)*h_harm(i,k) + botfn*h_arith(i,k)
         endif
         z_i(i,k) =  z_i(i,k+1) + h_harm(i,k)*i_hbbl(i)
       endif ; enddo ; enddo ! i & k loops
     else ! Not harmonic_visc
       do i=isq,ieq ; zh(i) = 0.0 ; z_i(i,nz+1) = 0.0 ; enddo
       do i=isq,ieq+1 ; zcol(i) = -g%bathyT(i,j) * m_to_h ; enddo
       do k=nz,1,-1
         do i=isq,ieq+1 ; zcol(i) = zcol(i) + h(i,j,k) ; enddo
         do i=isq,ieq ; if (do_i(i)) then
           zh(i) = zh(i) + h_harm(i,k)
           z_clear = max(zcol(i),zcol(i+1)) + dmin(i)
           if (zi_dir(i) < 0) z_clear = zcol(i) + dmin(i)
           if (zi_dir(i) > 0) z_clear = zcol(i+1) + dmin(i)
           z_i(i,k) = max(zh(i), z_clear) * i_hbbl(i)
           hvel(i,k) = h_arith(i,k)
           if (u(i,j,k) * (h(i+1,j,k)-h(i,j,k)) > 0) then
             if (zh(i) * i_hbbl(i) < cs%harm_BL_val) then
               hvel(i,k) = h_harm(i,k)
             else
               z2_wt = 1.0  ; if (zh(i) * i_hbbl(i) < 2.0*cs%harm_BL_val) &
                 z2_wt = max(0.0, min(1.0, zh(i) * i_hbbl(i) * i_valbl - 1.0))
               z2 = z2_wt * (max(zh(i), z_clear) * i_hbbl(i))
               botfn = 1.0 / (1.0 + 0.09*z2*z2*z2*z2*z2*z2)
               hvel(i,k) = (1.0-botfn)*h_arith(i,k) + botfn*h_harm(i,k)
             endif
           endif
         endif ; enddo ! i  loop
       enddo ! k loop
     endif
     call find_coupling_coef(a, hvel, do_i, h_harm, bbl_thick, kv_bbl, z_i, h_ml, &
                             dt, j, g, gv, cs, visc, fluxes, work_on_u=.true., obc=obc)
     if (allocated(hml_u)) then
       do i=isq,ieq ; if (do_i(i)) then ; hml_u(i,j) = h_ml(i) ; endif ; enddo
     endif
     do_any_shelf = .false.
     if (associated(fluxes%frac_shelf_u)) then
       do i=isq,ieq
         cs%a1_shelf_u(i,j) = 0.0
         do_i_shelf(i) = (do_i(i) .and. fluxes%frac_shelf_u(i,j) > 0.0)
         if (do_i_shelf(i)) do_any_shelf = .true.
       enddo
       if (do_any_shelf) then
         if (cs%harmonic_visc) then
           call find_coupling_coef(a_shelf, hvel, do_i_shelf, h_harm, bbl_thick, &
                                   kv_bbl, z_i, h_ml, dt, j, g, gv, cs, &
                                   visc, fluxes, work_on_u=.true., obc=obc, shelf=.true.)
         else  ! Find upwind-biased thickness near the surface.
           ! Perhaps this needs to be done more carefully, via find_eta.
           do i=isq,ieq ; if (do_i_shelf(i)) then
             zh(i) = 0.0 ; ztop_min(i) = min(zcol(i), zcol(i+1))
             i_htbl(i) = 1.0 / (visc%tbl_thick_shelf_u(i,j)*m_to_h + h_neglect)
           endif ; enddo
           do k=1,nz
             do i=isq,ieq+1 ; zcol(i) = zcol(i) - h(i,j,k) ; enddo
             do i=isq,ieq ; if (do_i_shelf(i)) then
               zh(i) = zh(i) + h_harm(i,k)
               hvel_shelf(i,k) = hvel(i,k)
               if (u(i,j,k) * (h(i+1,j,k)-h(i,j,k)) > 0) then
                 if (zh(i) * i_htbl(i) < cs%harm_BL_val) then
                   hvel_shelf(i,k) = min(hvel(i,k), h_harm(i,k))
                 else
                   z2_wt = 1.0  ; if (zh(i) * i_htbl(i) < 2.0*cs%harm_BL_val) &
                     z2_wt = max(0.0, min(1.0, zh(i) * i_htbl(i) * i_valbl - 1.0))
                   z2 = z2_wt * (max(zh(i), ztop_min(i) - min(zcol(i),zcol(i+1))) * i_htbl(i))
                   topfn = 1.0 / (1.0 + 0.09*z2**6)
                   hvel_shelf(i,k) = min(hvel(i,k), (1.0-topfn)*h_arith(i,k) + topfn*h_harm(i,k))
                 endif
               endif
             endif ; enddo
           enddo
           call find_coupling_coef(a_shelf, hvel_shelf, do_i_shelf, h_harm, &
                                   bbl_thick, kv_bbl, z_i, h_ml, dt, j, g, gv, cs, &
                                   visc, fluxes, work_on_u=.true., obc=obc, shelf=.true.)
         endif
         do i=isq,ieq ; if (do_i_shelf(i)) cs%a1_shelf_u(i,j) = a_shelf(i,1) ; enddo
       endif
     endif
     if (do_any_shelf) then
       do k=1,nz+1 ; do i=isq,ieq ; if (do_i_shelf(i)) then
         cs%a_u(i,j,k) = fluxes%frac_shelf_u(i,j)  * a_shelf(i,k) + &
                    (1.0-fluxes%frac_shelf_u(i,j)) * a(i,k)
 ! This is Alistair's suggestion, but it destabilizes the model. I do not know why. RWH
 !        CS%a_u(I,j,K) = fluxes%frac_shelf_u(I,j)  * max(a_shelf(I,K), a(I,K)) + &
 !                   (1.0-fluxes%frac_shelf_u(I,j)) * a(I,K)
       elseif (do_i(i)) then
         cs%a_u(i,j,k) = a(i,k)
       endif ; enddo ; enddo
       do k=1,nz ; do i=isq,ieq ; if (do_i_shelf(i)) then
         ! Should we instead take the inverse of the average of the inverses?
         cs%h_u(i,j,k) = fluxes%frac_shelf_u(i,j)  * hvel_shelf(i,k) + &
                    (1.0-fluxes%frac_shelf_u(i,j)) * hvel(i,k)
       elseif (do_i(i)) then
         cs%h_u(i,j,k) = hvel(i,k)
       endif ; enddo ; enddo
     else
       do k=1,nz+1 ; do i=isq,ieq ; if (do_i(i)) cs%a_u(i,j,k) = a(i,k) ; enddo ; enddo
       do k=1,nz ; do i=isq,ieq ; if (do_i(i)) cs%h_u(i,j,k) = hvel(i,k) ; enddo ; enddo
     endif
   enddo
   ! Now work on v-points.
 !$OMP parallel do default(none) shared(G,GV,CS,visc,is,ie,Jsq,Jeq,nz,v,h,fluxes,hML_v, &
 !$OMP                                  OBC,h_neglect,dt,m_to_H,I_valBL) &
 !$OMP                     firstprivate(i_hbbl)                                                &
 !$OMP                          private(do_i,kv_bbl,bbl_thick,z_i,h_harm,h_arith,hvel,z2,zi_dir, &
 !$OMP                                  botfn,zh,Dmin,zcol1,zcol2,a,do_any_shelf,do_i_shelf,  &
 !$OMP                                  a_shelf,Ztop_min,I_HTbl,hvel_shelf,topfn,h_ml,z2_wt,z_clear)
   do j=jsq,jeq
     do i=is,ie ; do_i(i) = (g%mask2dCv(i,j) > 0) ; enddo
     if (cs%bottomdraglaw) then ; do i=is,ie
       kv_bbl(i) = visc%kv_bbl_v(i,j)
       bbl_thick(i) = visc%bbl_thick_v(i,j) * m_to_h
       if (do_i(i)) i_hbbl(i) = 1.0 / bbl_thick(i)
     enddo ; endif
     do k=1,nz ; do i=is,ie ; if (do_i(i)) then
       h_harm(i,k) = 2.0*h(i,j,k)*h(i,j+1,k) / (h(i,j,k)+h(i,j+1,k)+h_neglect)
       h_arith(i,k) = 0.5*(h(i,j+1,k)+h(i,j,k))
     endif ; enddo ; enddo
     do i=is,ie
       dmin(i) = min(g%bathyT(i,j), g%bathyT(i,j+1)) * m_to_h
       zi_dir(i) = 0
     enddo
     ! Project thickness outward across OBCs using a zero-gradient condition.
     if (associated(obc)) then ; if (obc%number_of_segments > 0) then
       do i=is,ie ; if (do_i(i) .and. (obc%segnum_v(i,j) /= obc_none)) then
         if (obc%segment(obc%segnum_v(i,j))%direction == obc_direction_n) then
           do k=1,nz ; h_harm(i,k) = h(i,j,k) ; h_arith(i,k) = h(i,j,k) ; enddo
           dmin(i) = g%bathyT(i,j) * m_to_h
           zi_dir(i) = -1
         elseif (obc%segment(obc%segnum_v(i,j))%direction == obc_direction_s) then
           do k=1,nz ; h_harm(i,k) = h(i,j+1,k) ; h_arith(i,k) = h(i,j+1,k) ; enddo
           dmin(i) = g%bathyT(i,j+1) * m_to_h
           zi_dir(i) = 1
         endif
       endif ; enddo
     endif ; endif
 !    The following block calculates the thicknesses at velocity
 !  grid points for the vertical viscosity (hvel[k]).  Near the
 !  bottom an upwind biased thickness is used to control the effect
 !  of spurious Montgomery potential gradients at the bottom where
 !  nearly massless layers layers ride over the topography.
     if (cs%harmonic_visc) then
       do i=is,ie ; z_i(i,nz+1) = 0.0 ; enddo
       do k=nz,1,-1 ; do i=is,ie ; if (do_i(i)) then
         hvel(i,k) = h_harm(i,k)
         if (v(i,j,k) * (h(i,j+1,k)-h(i,j,k)) < 0) then
           z2 = z_i(i,k+1) ; botfn = 1.0 / (1.0 + 0.09*z2*z2*z2*z2*z2*z2)
           hvel(i,k) = (1.0-botfn)*h_harm(i,k) + botfn*h_arith(i,k)
         endif
         z_i(i,k) = z_i(i,k+1)  + h_harm(i,k)*i_hbbl(i)
       endif ; enddo ; enddo ! i & k loops
     else ! Not harmonic_visc
       do i=is,ie
         zh(i) = 0.0 ; z_i(i,nz+1) = 0.0
         zcol1(i) = -g%bathyT(i,j) * m_to_h
         zcol2(i) = -g%bathyT(i,j+1) * m_to_h
       enddo
       do k=nz,1,-1 ; do i=is,ie ; if (do_i(i)) then
         zh(i) = zh(i) + h_harm(i,k)
         zcol1(i) = zcol1(i) + h(i,j,k) ; zcol2(i) = zcol2(i) + h(i,j+1,k)
         z_clear = max(zcol1(i),zcol2(i)) + dmin(i)
         if (zi_dir(i) < 0) z_clear = zcol1(i) + dmin(i)
         if (zi_dir(i) > 0) z_clear = zcol2(i) + dmin(i)
         z_i(i,k) = max(zh(i), z_clear) * i_hbbl(i)
         hvel(i,k) = h_arith(i,k)
         if (v(i,j,k) * (h(i,j+1,k)-h(i,j,k)) > 0) then
           if (zh(i) * i_hbbl(i) < cs%harm_BL_val) then
             hvel(i,k) = h_harm(i,k)
           else
             z2_wt = 1.0  ; if (zh(i) * i_hbbl(i) < 2.0*cs%harm_BL_val) &
               z2_wt = max(0.0, min(1.0, zh(i) * i_hbbl(i) * i_valbl - 1.0))
             z2 = z2_wt * (max(zh(i), max(zcol1(i),zcol2(i)) + dmin(i)) * i_hbbl(i))
             botfn = 1.0 / (1.0 + 0.09*z2*z2*z2*z2*z2*z2)
             hvel(i,k) = (1.0-botfn)*h_arith(i,k) + botfn*h_harm(i,k)
           endif
        endif
       endif ; enddo ; enddo ! i & k loops
     endif
     call find_coupling_coef(a, hvel, do_i, h_harm, bbl_thick, kv_bbl, z_i, h_ml, &
                             dt, j, g, gv, cs, visc, fluxes, work_on_u=.false., obc=obc)
     if ( allocated(hml_v)) then
        do i=is,ie ; if (do_i(i)) then ; hml_v(i,j) = h_ml(i) ; endif ; enddo
     endif
     do_any_shelf = .false.
     if (associated(fluxes%frac_shelf_v)) then
       do i=is,ie
         cs%a1_shelf_v(i,j) = 0.0
         do_i_shelf(i) = (do_i(i) .and. fluxes%frac_shelf_v(i,j) > 0.0)
         if (do_i_shelf(i)) do_any_shelf = .true.
       enddo
       if (do_any_shelf) then
         if (cs%harmonic_visc) then
           call find_coupling_coef(a_shelf, hvel, do_i_shelf, h_harm, bbl_thick, &
                                   kv_bbl, z_i, h_ml, dt, j, g, gv, cs, visc, &
                                   fluxes, work_on_u=.false., obc=obc, shelf=.true.)
         else  ! Find upwind-biased thickness near the surface.
           ! Perhaps this needs to be done more carefully, via find_eta.
           do i=is,ie ; if (do_i_shelf(i)) then
             zh(i) = 0.0 ; ztop_min(i) = min(zcol1(i), zcol2(i))
             i_htbl(i) = 1.0 / (visc%tbl_thick_shelf_v(i,j)*m_to_h + h_neglect)
           endif ; enddo
           do k=1,nz
             do i=is,ie ; if (do_i_shelf(i)) then
               zcol1(i) = zcol1(i) - h(i,j,k) ; zcol2(i) = zcol2(i) - h(i,j+1,k)
               zh(i) = zh(i) + h_harm(i,k)
               hvel_shelf(i,k) = hvel(i,k)
               if (v(i,j,k) * (h(i,j+1,k)-h(i,j,k)) > 0) then
                 if (zh(i) * i_htbl(i) < cs%harm_BL_val) then
                   hvel_shelf(i,k) = min(hvel(i,k), h_harm(i,k))
                 else
                   z2_wt = 1.0  ; if (zh(i) * i_htbl(i) < 2.0*cs%harm_BL_val) &
                     z2_wt = max(0.0, min(1.0, zh(i) * i_htbl(i) * i_valbl - 1.0))
                   z2 = z2_wt * (max(zh(i), ztop_min(i) - min(zcol1(i),zcol2(i))) * i_htbl(i))
                   topfn = 1.0 / (1.0 + 0.09*z2**6)
                   hvel_shelf(i,k) = min(hvel(i,k), (1.0-topfn)*h_arith(i,k) + topfn*h_harm(i,k))
                 endif
              endif
             endif ; enddo
           enddo
           call find_coupling_coef(a_shelf, hvel_shelf, do_i_shelf, h_harm, &
                                   bbl_thick, kv_bbl, z_i, h_ml, dt, j, g, gv, cs, &
                                   visc, fluxes, work_on_u=.false., obc=obc, shelf=.true.)
         endif
         do i=is,ie ; if (do_i_shelf(i)) cs%a1_shelf_v(i,j) = a_shelf(i,1) ; enddo
       endif
     endif
     if (do_any_shelf) then
       do k=1,nz+1 ; do i=is,ie ; if (do_i_shelf(i)) then
         cs%a_v(i,j,k) = fluxes%frac_shelf_v(i,j)  * a_shelf(i,k) + &
                    (1.0-fluxes%frac_shelf_v(i,j)) * a(i,k)
 ! This is Alistair's suggestion, but it destabilizes the model. I do not know why. RWH
 !        CS%a_v(i,J,K) = fluxes%frac_shelf_v(i,J)  * max(a_shelf(i,K), a(i,K)) + &
 !                   (1.0-fluxes%frac_shelf_v(i,J)) * a(i,K)
       elseif (do_i(i)) then
         cs%a_v(i,j,k) = a(i,k)
       endif ; enddo ; enddo
       do k=1,nz ; do i=is,ie ; if (do_i_shelf(i)) then
         ! Should we instead take the inverse of the average of the inverses?
         cs%h_v(i,j,k) = fluxes%frac_shelf_v(i,j)  * hvel_shelf(i,k) + &
                    (1.0-fluxes%frac_shelf_v(i,j)) * hvel(i,k)
       elseif (do_i(i)) then
         cs%h_v(i,j,k) = hvel(i,k)
       endif ; enddo ; enddo
     else
       do k=1,nz+1 ; do i=is,ie ; if (do_i(i)) cs%a_v(i,j,k) = a(i,k) ; enddo ; enddo
       do k=1,nz ; do i=is,ie ; if (do_i(i)) cs%h_v(i,j,k) = hvel(i,k) ; enddo ; enddo
     endif
   enddo ! end of v-point j loop
   if (cs%debug) then
     call uvchksum("vertvisc_coef h_[uv]", cs%h_u, &
                   cs%h_v, g%HI,haloshift=0, scale=gv%H_to_m)
     call uvchksum("vertvisc_coef a_[uv]", cs%a_u, &
                   cs%a_v, g%HI, haloshift=0)
     if (allocated(hml_u) .and. allocated(hml_v)) &
       call uvchksum("vertvisc_coef hML_[uv]", hml_u, hml_v, &
                     g%HI, haloshift=0, scale=gv%H_to_m)
   endif
 ! Offer diagnostic fields for averaging.
   if (cs%id_au_vv > 0) call post_data(cs%id_au_vv, cs%a_u, cs%diag)
   if (cs%id_av_vv > 0) call post_data(cs%id_av_vv, cs%a_v, cs%diag)
   if (cs%id_h_u > 0) call post_data(cs%id_h_u, cs%h_u, cs%diag)
   if (cs%id_h_v > 0) call post_data(cs%id_h_v, cs%h_v, cs%diag)
   if (cs%id_hML_u > 0) call post_data(cs%id_hML_u, hml_u, cs%diag)
   if (cs%id_hML_v > 0) call post_data(cs%id_hML_v, hml_v, cs%diag)
   if (allocated(hml_u)) deallocate(hml_u)
   if (allocated(hml_v)) deallocate(hml_v)
vertvisc_end()
subroutine, public mom_vert_friction::vertvisc_end (type(vertvisc_cs), pointer CS)
Clean up and deallocate the vertical friction module.
Definition at line 1675 of file MOM_vert_friction.F90.
   type(vertvisc_cs),   pointer       :: cs
   dealloc_(cs%a_u) ; dealloc_(cs%h_u)
   dealloc_(cs%a_v) ; dealloc_(cs%h_v)
   if (associated(cs%a1_shelf_u)) deallocate(cs%a1_shelf_u)
   if (associated(cs%a1_shelf_v)) deallocate(cs%a1_shelf_v)
   deallocate(cs)
vertvisc_init()
subroutine, public mom_vert_friction::vertvisc_init (type(ocean_internal_state), intent(in), target MIS, type(time_type), intent(in), target Time, type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(accel_diag_ptrs), intent(inout) ADp, type(directories), intent(in) dirs, integer, intent(inout), target ntrunc, type(vertvisc_cs), pointer CS)
Initialise the vertical friction module.
Parameters
[in] mis "MOM Internal State", a set of pointers to the fields and accelerations that make up the ocean's physical state
[in] time Current model time
[in] g Ocean grid structure
[in] gv Ocean vertical grid structure
[in] param_file File to parse for parameters
[in,out] diag Diagnostic control structure
[in,out] adp Acceleration diagnostic pointers
[in] dirs Relevant directory paths
[in,out] ntrunc Number of velocity truncations
cs Vertical viscosity control structure
Definition at line 1458 of file MOM_vert_friction.F90.
References mom_error_handler::mom_error().
   !> "MOM Internal State", a set of pointers to the fields and accelerations
   !! that make up the ocean's physical state
   type(ocean_internal_state), target, intent(in) :: mis
   type(time_type), target, intent(in)    :: time       !< Current model time
   type(ocean_grid_type),   intent(in)    :: g          !< Ocean grid structure
   type(verticalgrid_type), intent(in)    :: gv         !< Ocean vertical grid structure
   type(param_file_type),   intent(in)    :: param_file !< File to parse for parameters
   type(diag_ctrl), target, intent(inout) :: diag       !< Diagnostic control structure
   type(accel_diag_ptrs),   intent(inout) :: adp        !< Acceleration diagnostic pointers
   type(directories),       intent(in)    :: dirs       !< Relevant directory paths
   integer, target,         intent(inout) :: ntrunc     !< Number of velocity truncations
   type(vertvisc_cs),       pointer       :: cs         !< Vertical viscosity control structure
   ! Local variables
   real :: hmix_str_dflt
   integer :: isd, ied, jsd, jed, isdb, iedb, jsdb, jedb, nz
 ! This include declares and sets the variable "version".
 #include "version_variable.h"
   character(len=40)  :: mdl = "MOM_vert_friction" ! This module's name.
   character(len=40)  :: thickness_units = "meters or kg m-2"
   if (associated(cs)) then
     call mom_error(warning, "vertvisc_init called with an associated "// &
                             "control structure.")
     return
   endif
   allocate(cs)
   isd = g%isd ; ied = g%ied ; jsd = g%jsd ; jed = g%jed ; nz = g%ke
   isdb = g%IsdB ; iedb = g%IedB ; jsdb = g%JsdB ; jedb = g%JedB
   cs%diag => diag ; cs%ntrunc => ntrunc ; ntrunc = 0
 ! Default, read and log parameters
   call log_version(param_file, mdl, version, "")
   call get_param(param_file, mdl, "BOTTOMDRAGLAW", cs%bottomdraglaw, &
                  "If true, the bottom stress is calculated with a drag \n"//&
                  "law of the form c_drag*|u|*u. The velocity magnitude \n"//&
                  "may be an assumed value or it may be based on the \n"//&
                  "actual velocity in the bottommost HBBL, depending on \n"//&
                  "LINEAR_DRAG.", default=.true.)
   call get_param(param_file, mdl, "CHANNEL_DRAG", cs%Channel_drag, &
                  "If true, the bottom drag is exerted directly on each \n"//&
                  "layer proportional to the fraction of the bottom it \n"//&
                  "overlies.", default=.false.)
   call get_param(param_file, mdl, "DIRECT_STRESS", cs%direct_stress, &
                  "If true, the wind stress is distributed over the \n"//&
                  "topmost HMIX_STRESS of fluid (like in HYCOM), and KVML \n"//&
                  "may be set to a very small value.", default=.false.)
   call get_param(param_file, mdl, "DYNAMIC_VISCOUS_ML", cs%dynamic_viscous_ML, &
                  "If true, use a bulk Richardson number criterion to \n"//&
                  "determine the mixed layer thickness for viscosity.", &
                  default=.false.)
   call get_param(param_file, mdl, "U_TRUNC_FILE", cs%u_trunc_file, &
                  "The absolute path to a file into which the accelerations \n"//&
                  "leading to zonal velocity truncations are written.  \n"//&
                  "Undefine this for efficiency if this diagnostic is not \n"//&
                  "needed.", default=" ")
   call get_param(param_file, mdl, "V_TRUNC_FILE", cs%v_trunc_file, &
                  "The absolute path to a file into which the accelerations \n"//&
                  "leading to meridional velocity truncations are written. \n"//&
                  "Undefine this for efficiency if this diagnostic is not \n"//&
                  "needed.", default=" ")
   call get_param(param_file, mdl, "HARMONIC_VISC", cs%harmonic_visc, &
                  "If true, use the harmonic mean thicknesses for \n"//&
                  "calculating the vertical viscosity.", default=.false.)
   call get_param(param_file, mdl, "HARMONIC_BL_SCALE", cs%harm_BL_val, &
                  "A scale to determine when water is in the boundary \n"//&
                  "layers based solely on harmonic mean thicknesses for \n"//&
                  "the purpose of determining the extent to which the \n"//&
                  "thicknesses used in the viscosities are upwinded.", &
                  default=0.0, units="nondim")
   call get_param(param_file, mdl, "DEBUG", cs%debug, default=.false.)
   if (gv%nkml < 1) &
     call get_param(param_file, mdl, "HMIX_FIXED", cs%Hmix, &
                  "The prescribed depth over which the near-surface \n"//&
                  "viscosity and diffusivity are elevated when the bulk \n"//&
                  "mixed layer is not used.", units="m", fail_if_missing=.true.)
   if (cs%direct_stress) then
     if (gv%nkml < 1) then
       call get_param(param_file, mdl, "HMIX_STRESS", cs%Hmix_stress, &
                  "The depth over which the wind stress is applied if \n"//&
                  "DIRECT_STRESS is true.", units="m", default=cs%Hmix)
     else
       call get_param(param_file, mdl, "HMIX_STRESS", cs%Hmix_stress, &
                  "The depth over which the wind stress is applied if \n"//&
                  "DIRECT_STRESS is true.", units="m", fail_if_missing=.true.)
     endif
     if (cs%Hmix_stress <= 0.0) call mom_error(fatal, "vertvisc_init: " // &
        "HMIX_STRESS must be set to a positive value if DIRECT_STRESS is true.")
   endif
   call get_param(param_file, mdl, "KV", cs%Kv, &
                  "The background kinematic viscosity in the interior. \n"//&
                  "The molecular value, ~1e-6 m2 s-1, may be used.", &
                  units="m2 s-1", fail_if_missing=.true.)
 ! CS%Kvml = CS%Kv ; CS%Kvbbl = CS%Kv ! Needed? -AJA
   if (gv%nkml < 1) call get_param(param_file, mdl, "KVML", cs%Kvml, &
                  "The kinematic viscosity in the mixed layer.  A typical \n"//&
                  "value is ~1e-2 m2 s-1. KVML is not used if \n"//&
                  "BULKMIXEDLAYER is true.  The default is set by KV.", &
                  units="m2 s-1", default=cs%Kv)
   if (.not.cs%bottomdraglaw) call get_param(param_file, mdl, "KVBBL", cs%Kvbbl, &
                  "The kinematic viscosity in the benthic boundary layer. \n"//&
                  "A typical value is ~1e-2 m2 s-1. KVBBL is not used if \n"//&
                  "BOTTOMDRAGLAW is true.  The default is set by KV.", &
                  units="m2 s-1", default=cs%Kv)
   call get_param(param_file, mdl, "HBBL", cs%Hbbl, &
                  "The thickness of a bottom boundary layer with a \n"//&
                  "viscosity of KVBBL if BOTTOMDRAGLAW is not defined, or \n"//&
                  "the thickness over which near-bottom velocities are \n"//&
                  "averaged for the drag law if BOTTOMDRAGLAW is defined \n"//&
                  "but LINEAR_DRAG is not.", units="m", fail_if_missing=.true.)
   call get_param(param_file, mdl, "MAXVEL", cs%maxvel, &
                  "The maximum velocity allowed before the velocity \n"//&
                  "components are truncated.", units="m s-1", default=3.0e8)
   call get_param(param_file, mdl, "CFL_BASED_TRUNCATIONS", cs%CFL_based_trunc, &
                  "If true, base truncations on the CFL number, and not an \n"//&
                  "absolute speed.", default=.true.)
   call get_param(param_file, mdl, "CFL_TRUNCATE", cs%CFL_trunc, &
                  "The value of the CFL number that will cause velocity \n"//&
                  "components to be truncated; instability can occur past 0.5.", &
                  units="nondim", default=0.5)
   call get_param(param_file, mdl, "CFL_REPORT", cs%CFL_report, &
                  "The value of the CFL number that causes accelerations \n"//&
                  "to be reported; the default is CFL_TRUNCATE.", &
                  units="nondim", default=cs%CFL_trunc)
   call get_param(param_file, mdl, "CFL_TRUNCATE_RAMP_TIME", cs%truncRampTime, &
                  "The time over which the CFL trunction value is ramped\n"//&
                  "up at the beginning of the run.", &
                  units="s", default=0.)
   cs%CFL_truncE = cs%CFL_trunc
   call get_param(param_file, mdl, "CFL_TRUNCATE_START", cs%CFL_truncS, &
                  "The start value of the truncation CFL number used when\n"//&
                  "ramping up CFL_TRUNC.", &
                  units="nondim", default=0.)
   alloc_(cs%a_u(isdb:iedb,jsd:jed,nz+1)) ; cs%a_u(:,:,:) = 0.0
   alloc_(cs%h_u(isdb:iedb,jsd:jed,nz))   ; cs%h_u(:,:,:) = 0.0
   alloc_(cs%a_v(isd:ied,jsdb:jedb,nz+1)) ; cs%a_v(:,:,:) = 0.0
   alloc_(cs%h_v(isd:ied,jsdb:jedb,nz))   ; cs%h_v(:,:,:) = 0.0
   cs%id_au_vv = register_diag_field('ocean_model', 'au_visc', diag%axesCui, time, &
      'Zonal Viscous Vertical Coupling Coefficient', 'meter second-1')
   cs%id_av_vv = register_diag_field('ocean_model', 'av_visc', diag%axesCvi, time, &
      'Meridional Viscous Vertical Coupling Coefficient', 'meter second-1')
   cs%id_h_u = register_diag_field('ocean_model', 'Hu_visc', diag%axesCuL, time, &
      'Thickness at Zonal Velocity Points for Viscosity', thickness_units)
   cs%id_h_v = register_diag_field('ocean_model', 'Hv_visc', diag%axesCvL, time, &
      'Thickness at Meridional Velocity Points for Viscosity', thickness_units)
   cs%id_hML_u = register_diag_field('ocean_model', 'HMLu_visc', diag%axesCu1, time, &
      'Mixed Layer Thickness at Zonal Velocity Points for Viscosity', thickness_units)
   cs%id_hML_v = register_diag_field('ocean_model', 'HMLv_visc', diag%axesCv1, time, &
      'Mixed Layer Thickness at Meridional Velocity Points for Viscosity', thickness_units)
   cs%id_du_dt_visc = register_diag_field('ocean_model', 'du_dt_visc', diag%axesCuL, &
      time, 'Zonal Acceleration from Vertical Viscosity', 'meter second-2')
   if (cs%id_du_dt_visc > 0) call safe_alloc_ptr(adp%du_dt_visc,isdb,iedb,jsd,jed,nz)
   cs%id_dv_dt_visc = register_diag_field('ocean_model', 'dv_dt_visc', diag%axesCvL, &
      time, 'Meridional Acceleration from Vertical Viscosity', 'meter second-2')
   if (cs%id_dv_dt_visc > 0) call safe_alloc_ptr(adp%dv_dt_visc,isd,ied,jsdb,jedb,nz)
   cs%id_taux_bot = register_diag_field('ocean_model', 'taux_bot', diag%axesCu1, &
      time, 'Zonal Bottom Stress from Ocean to Earth', 'Pa')
   cs%id_tauy_bot = register_diag_field('ocean_model', 'tauy_bot', diag%axesCv1, &
      time, 'Meridional Bottom Stress from Ocean to Earth', 'Pa')
   if ((len_trim(cs%u_trunc_file) > 0) .or. (len_trim(cs%v_trunc_file) > 0)) &
     call pointaccel_init(mis, time, g, param_file, diag, dirs, cs%PointAccel_CSp)
vertvisc_limit_vel()
subroutine, public mom_vert_friction::vertvisc_limit_vel (real, dimension(g %isdb: g %iedb, g %jsd: g %jed, gv %ke), intent(inout) u, real, dimension(g %isd: g %ied, g %jsdb: g %jedb, gv %ke), intent(inout) v, real, dimension(g %isd: g %ied, g %jsd: g %jed, gv %ke), intent(in) h, type(accel_diag_ptrs), intent(in) ADp, type(cont_diag_ptrs), intent(in) CDp, type(forcing), intent(in) fluxes, type(vertvisc_type), intent(in) visc, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, type(vertvisc_cs), pointer CS)
Velocity components which exceed a threshold for physically reasonable values are truncated. Optionally, any column with excessive velocities may be sent to a diagnostic reporting subroutine.
Parameters
[in] g Ocean grid structure
[in] gv Ocean vertical grid structure
[in,out] u Zonal velocity in m s-1
[in,out] v Meridional velocity in m s-1
[in] h Layer thickness in H
[in] adp Acceleration diagnostic pointers
[in] cdp Continuity diagnostic pointers
[in] fluxes Forcing fields
[in] visc Viscosities and bottom drag
[in] dt Time increment in s
cs Vertical viscosity control structure
Definition at line 1258 of file MOM_vert_friction.F90.
Referenced by vertvisc().
   type(ocean_grid_type),   intent(in)    :: g      !< Ocean grid structure
   type(verticalgrid_type), intent(in)    :: gv     !< Ocean vertical grid structure
   real, intent(inout), &
     dimension(SZIB_(G),SZJ_(G),SZK_(GV)) :: u      !< Zonal velocity in m s-1
   real, intent(inout), &
     dimension(SZI_(G),SZJB_(G),SZK_(GV)) :: v      !< Meridional velocity in m s-1
   real, intent(in), &
     dimension(SZI_(G),SZJ_(G),SZK_(GV))  :: h      !< Layer thickness in H
   type(accel_diag_ptrs), intent(in)      :: adp    !< Acceleration diagnostic pointers
   type(cont_diag_ptrs),  intent(in)      :: cdp    !< Continuity diagnostic pointers
   type(forcing),         intent(in)      :: fluxes !< Forcing fields
   type(vertvisc_type),   intent(in)      :: visc   !< Viscosities and bottom drag
   real,                  intent(in)      :: dt     !< Time increment in s
   type(vertvisc_cs),     pointer         :: cs     !< Vertical viscosity control structure
   ! Local variables
   real :: maxvel           ! Velocities components greater than maxvel
   real :: truncvel         ! are truncated to truncvel, both in m s-1.
   real :: cfl              ! The local CFL number.
   real :: h_report         ! A thickness below which not to report truncations.
   real :: dt_rho0          ! The timestep divided by the Boussinesq density, in dt m3 kg-1.
   real :: vel_report(szib_(g),szjb_(g))
   real :: u_old(szib_(g),szj_(g),szk_(g))
   real :: v_old(szi_(g),szjb_(g),szk_(g))
   logical :: trunc_any, dowrite(szib_(g),szjb_(g))
   integer :: i, j, k, is, ie, js, je, isq, ieq, jsq, jeq, nz
   is = g%isc ; ie = g%iec ; js = g%jsc ; je = g%jec ; nz = g%ke
   isq = g%IscB ; ieq = g%IecB ; jsq = g%JscB ; jeq = g%JecB
   maxvel = cs%maxvel
   truncvel = 0.9*maxvel
   h_report = 6.0 * gv%Angstrom
   dt_rho0 = dt / gv%Rho0
   if (len_trim(cs%u_trunc_file) > 0) then
 !$OMP parallel do default(none) shared(js,je,Isq,Ieq,nz,CS,G,fluxes,u,h,dt,maxvel,ADp,CDp,truncvel, &
 !$OMP                                  u_old,vel_report,dowrite,H_report) &
 !$OMP                          private(trunc_any,CFL)
     do j=js,je
       trunc_any = .false.
       do i=isq,ieq ; dowrite(i,j) = .false. ; enddo
       if (cs%CFL_based_trunc) then
         do i=isq,ieq ; vel_report(i,j) = 3.0e8 ; enddo ! Speed of light default.
         do k=1,nz ; do i=isq,ieq
           if (u(i,j,k) < 0.0) then
             cfl = (-u(i,j,k) * dt) * (g%dy_Cu(i,j) * g%IareaT(i+1,j))
           else
             cfl = (u(i,j,k) * dt) * (g%dy_Cu(i,j) * g%IareaT(i,j))
           endif
           if (cfl > cs%CFL_trunc) trunc_any = .true.
           if (cfl > cs%CFL_report) then
             dowrite(i,j) = .true.
             vel_report(i,j) = min(vel_report(i,j), abs(u(i,j,k)))
           endif
         enddo ; enddo
       else
         do i=isq,ieq; vel_report(i,j) = maxvel; enddo
         do k=1,nz ; do i=isq,ieq ; if (abs(u(i,j,k)) > maxvel) then
           dowrite(i,j) = .true. ; trunc_any = .true.
         endif ;enddo ; enddo
       endif
       do i=isq,ieq ; if (dowrite(i,j)) then
         u_old(i,j,:) = u(i,j,:)
       endif ; enddo
       if (trunc_any) then ; if (cs%CFL_based_trunc) then
         do k=1,nz ; do i=isq,ieq
           if ((u(i,j,k) * (dt * g%dy_Cu(i,j))) * g%IareaT(i+1,j) < -cs%CFL_trunc) then
             u(i,j,k) = (-0.9*cs%CFL_trunc) * (g%areaT(i+1,j) / (dt * g%dy_Cu(i,j)))
             if (h(i,j,k) + h(i+1,j,k) > h_report) cs%ntrunc = cs%ntrunc + 1
           elseif ((u(i,j,k) * (dt * g%dy_Cu(i,j))) * g%IareaT(i,j) > cs%CFL_trunc) then
             u(i,j,k) = (0.9*cs%CFL_trunc) * (g%areaT(i,j) / (dt * g%dy_Cu(i,j)))
             if (h(i,j,k) + h(i+1,j,k) > h_report) cs%ntrunc = cs%ntrunc + 1
           endif
         enddo ; enddo
       else
         do k=1,nz ; do i=isq,ieq ; if (abs(u(i,j,k)) > maxvel) then
           u(i,j,k) = sign(truncvel,u(i,j,k))
           if (h(i,j,k) + h(i+1,j,k) > h_report) cs%ntrunc = cs%ntrunc + 1
         endif ; enddo ;  enddo
       endif ; endif
     enddo ! j-loop
   else
     if (cs%CFL_based_trunc) then
 !$OMP parallel do default(none) shared(nz,js,je,Isq,Ieq,u,dt,G,CS,h,H_report)
       do k=1,nz ; do j=js,je ; do i=isq,ieq
         if ((u(i,j,k) * (dt * g%dy_Cu(i,j))) * g%IareaT(i+1,j) < -cs%CFL_trunc) then
           u(i,j,k) = (-0.9*cs%CFL_trunc) * (g%areaT(i+1,j) / (dt * g%dy_Cu(i,j)))
           if (h(i,j,k) + h(i+1,j,k) > h_report) cs%ntrunc = cs%ntrunc + 1
         elseif ((u(i,j,k) * (dt * g%dy_Cu(i,j))) * g%IareaT(i,j) > cs%CFL_trunc) then
           u(i,j,k) = (0.9*cs%CFL_trunc) * (g%areaT(i,j) / (dt * g%dy_Cu(i,j)))
           if (h(i,j,k) + h(i+1,j,k) > h_report) cs%ntrunc = cs%ntrunc + 1
         endif
       enddo ; enddo ; enddo
     else
 !$OMP parallel do default(none) shared(nz,js,je,Isq,Ieq,u,G,CS,truncvel,maxvel,h,H_report)
       do k=1,nz ; do j=js,je ; do i=isq,ieq ; if (abs(u(i,j,k)) > maxvel) then
         u(i,j,k) = sign(truncvel,u(i,j,k))
         if (h(i,j,k) + h(i+1,j,k) > h_report) cs%ntrunc = cs%ntrunc + 1
       endif ; enddo ; enddo ; enddo
     endif
   endif
   if (len_trim(cs%u_trunc_file) > 0) then
     do j=js,je; do i=isq,ieq ; if (dowrite(i,j)) then
 !   Here the diagnostic reporting subroutines are called if
 ! unphysically large values were found.
       call write_u_accel(i, j, u_old, h, adp, cdp, dt, g, gv, cs%PointAccel_CSp, &
                vel_report(i,j), -vel_report(i,j), fluxes%taux(i,j)*dt_rho0, &
                a=cs%a_u(:,j,:), hv=cs%h_u(:,j,:))
     endif ; enddo; enddo
   endif
   if (len_trim(cs%v_trunc_file) > 0) then
 !$OMP parallel do default(none) shared(Jsq,Jeq,is,ie,nz,CS,G,fluxes,v,h,dt,maxvel,ADp,CDp,truncvel, &
 !$OMP                                  v_old,vel_report,dowrite,H_report)                           &
 !$OMP                          private(trunc_any,CFL)
     do j=jsq,jeq
       trunc_any = .false.
       do i=is,ie ; dowrite(i,j) = .false. ; enddo
       if (cs%CFL_based_trunc) then
         do i=is,ie ; vel_report(i,j) = 3.0e8 ; enddo ! Speed of light default.
         do k=1,nz ; do i=is,ie
           if (v(i,j,k) < 0.0) then
             cfl = (-v(i,j,k) * dt) * (g%dx_Cv(i,j) * g%IareaT(i,j+1))
           else
             cfl = (v(i,j,k) * dt) * (g%dx_Cv(i,j) * g%IareaT(i,j))
           endif
           if (cfl > cs%CFL_trunc) trunc_any = .true.
           if (cfl > cs%CFL_report) then
             dowrite(i,j) = .true.
             vel_report(i,j) = min(vel_report(i,j), abs(v(i,j,k)))
           endif
         enddo ; enddo
       else
         do i=is,ie ; vel_report(i,j) = maxvel ; enddo
         do k=1,nz ; do i=is,ie ; if (abs(v(i,j,k)) > maxvel) then
           dowrite(i,j) = .true. ; trunc_any = .true.
         endif ; enddo ; enddo
       endif
       do i=is,ie ; if (dowrite(i,j)) then
         v_old(i,j,:) = v(i,j,:)
       endif ; enddo
       if (trunc_any) then ; if (cs%CFL_based_trunc) then
         do k=1,nz; do i=is,ie
           if ((v(i,j,k) * (dt * g%dx_Cv(i,j))) * g%IareaT(i,j+1) < -cs%CFL_trunc) then
             v(i,j,k) = (-0.9*cs%CFL_trunc) * (g%areaT(i,j+1) / (dt * g%dx_Cv(i,j)))
             if (h(i,j,k) + h(i,j+1,k) > h_report) cs%ntrunc = cs%ntrunc + 1
           elseif ((v(i,j,k) * (dt * g%dx_Cv(i,j))) * g%IareaT(i,j) > cs%CFL_trunc) then
             v(i,j,k) = (0.9*cs%CFL_trunc) * (g%areaT(i,j) / (dt * g%dx_Cv(i,j)))
             if (h(i,j,k) + h(i,j+1,k) > h_report) cs%ntrunc = cs%ntrunc + 1
           endif
         enddo ; enddo
       else
         do k=1,nz ; do i=is,ie ; if (abs(v(i,j,k)) > maxvel) then
           v(i,j,k) = sign(truncvel,v(i,j,k))
           if (h(i,j,k) + h(i,j+1,k) > h_report) cs%ntrunc = cs%ntrunc + 1
         endif ; enddo ;  enddo
       endif ; endif
     enddo ! J-loop
   else
     if (cs%CFL_based_trunc) then
 !$OMP parallel do default(none) shared(is,ie,Jsq,Jeq,nz,v,dt,G,CS,h,H_report)
       do k=1,nz ; do j=jsq,jeq ; do i=is,ie
         if ((v(i,j,k) * (dt * g%dx_Cv(i,j))) * g%IareaT(i,j+1) < -cs%CFL_trunc) then
           v(i,j,k) = (-0.9*cs%CFL_trunc) * (g%areaT(i,j+1) / (dt * g%dx_Cv(i,j)))
           if (h(i,j,k) + h(i,j+1,k) > h_report) cs%ntrunc = cs%ntrunc + 1
         elseif ((v(i,j,k) * (dt * g%dx_Cv(i,j))) * g%IareaT(i,j) > cs%CFL_trunc) then
           v(i,j,k) = (0.9*cs%CFL_trunc) * (g%areaT(i,j) / (dt * g%dx_Cv(i,j)))
           if (h(i,j,k) + h(i,j+1,k) > h_report) cs%ntrunc = cs%ntrunc + 1
         endif
       enddo ; enddo ; enddo
     else
 !$OMP parallel do default(none) shared(is,ie,Jsq,Jeq,nz,v,G,CS,h,truncvel,maxvel,H_report)
       do k=1,nz ; do j=jsq,jeq ; do i=is,ie ; if (abs(v(i,j,k)) > maxvel) then
         v(i,j,k) = sign(truncvel,v(i,j,k))
         if (h(i,j,k) + h(i,j+1,k) > h_report) cs%ntrunc = cs%ntrunc + 1
       endif ; enddo ; enddo ; enddo
     endif
   endif
   if (len_trim(cs%v_trunc_file) > 0) then
     do j=jsq,jeq; do i=is,ie ; if (dowrite(i,j)) then
 !   Here the diagnostic reporting subroutines are called if
 ! unphysically large values were found.
       call write_v_accel(i, j, v_old, h, adp, cdp, dt, g, gv, cs%PointAccel_CSp, &
                vel_report(i,j), -vel_report(i,j), fluxes%tauy(i,j)*dt_rho0, &
                a=cs%a_v(:,j,:),hv=cs%h_v(:,j,:))
     endif ; enddo; enddo
   endif
vertvisc_remnant()
subroutine, public mom_vert_friction::vertvisc_remnant (type(vertvisc_type), intent(in) visc, real, dimension(szib_(g),szj_(g),szk_(gv)), intent(inout) visc_rem_u, real, dimension(g %isd: g %ied, g %jsdb: g %jedb, gv %ke), intent(inout) visc_rem_v, real, intent(in) dt, type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, type(vertvisc_cs), pointer CS)
Calculate the fraction of momentum originally in a layer that remains after a time-step of viscosity, and the fraction of a time-step's worth of barotropic acceleration that a layer experiences after viscosity is applied.
Parameters
[in] g Ocean grid structure
[in] gv Ocean vertical grid structure
[in] visc Viscosities and bottom drag
[in,out] visc_rem_u Fraction of a time-step's worth of a barotopic acceleration that a layer experiences after viscosity is applied in the zonal direction
[in,out] visc_rem_v Fraction of a time-step's worth of a barotopic acceleration that a layer experiences after viscosity is applied in the meridional direction
[in] dt Time increment in s
cs Vertical viscosity control structure
Definition at line 427 of file MOM_vert_friction.F90.
References mom_error_handler::mom_error().
   type(ocean_grid_type), intent(in)   :: g    !< Ocean grid structure
   type(verticalgrid_type), intent(in) :: gv   !< Ocean vertical grid structure
   type(vertvisc_type), intent(in)     :: visc !< Viscosities and bottom drag
   !> Fraction of a time-step's worth of a barotopic acceleration that
   !! a layer experiences after viscosity is applied in the zonal direction
   real, dimension(SZIB_(G),SZJ_(G),SZK_(GV)), intent(inout) :: visc_rem_u
   !> Fraction of a time-step's worth of a barotopic acceleration that
   !! a layer experiences after viscosity is applied in the meridional direction
   real, dimension(SZI_(G),SZJB_(G),SZK_(GV)), intent(inout) :: visc_rem_v
   real, intent(in)           :: dt !< Time increment in s
   type(vertvisc_cs), pointer :: cs !< Vertical viscosity control structure
   ! Local variables
   real :: b1(szib_(g))          ! b1 and c1 are variables used by the
   real :: c1(szib_(g),szk_(g))  ! tridiagonal solver.  c1 is nondimensional,
                                 ! while b1 has units of inverse thickness.
   real :: d1(szib_(g))          ! d1=1-c1 is used by the tridiagonal solver, ND.
   real :: ray(szib_(g),szk_(g)) ! Ray is the Rayleigh-drag velocity times the
                                 ! time step, in m.
   real :: b_denom_1   ! The first term in the denominator of b1, in m or kg m-2.
   real :: dt_m_to_h        ! The time step times the conversion from m to the
                            ! units of thickness - either s or s m3 kg-1.
   logical :: do_i(szib_(g))
   integer :: i, j, k, is, ie, isq, ieq, jsq, jeq, nz
   is = g%isc ; ie = g%iec
   isq = g%IscB ; ieq = g%IecB ; jsq = g%JscB ; jeq = g%JecB ; nz = g%ke
   if (.not.associated(cs)) call mom_error(fatal,"MOM_vert_friction(visc): "// &
          "Module must be initialized before it is used.")
   dt_m_to_h = dt*gv%m_to_H
   do k=1,nz ; do i=isq,ieq ; ray(i,k) = 0.0 ; enddo ; enddo
   ! Find the zonal viscous using a modification of a standard tridagonal solver.
 !$OMP parallel do default(none) shared(G,Isq,Ieq,CS,nz,visc,dt_m_to_H,visc_rem_u) &
 !$OMP                     firstprivate(Ray)                                       &
 !$OMP                          private(do_i,b_denom_1,b1,d1,c1)
   do j=g%jsc,g%jec
     do i=isq,ieq ; do_i(i) = (g%mask2dCu(i,j) > 0) ; enddo
     if (cs%Channel_drag) then ; do k=1,nz ; do i=isq,ieq
       ray(i,k) = visc%Ray_u(i,j,k)
     enddo ; enddo ; endif
     do i=isq,ieq ; if (do_i(i)) then
       b_denom_1 = cs%h_u(i,j,1) + dt_m_to_h * (ray(i,1) + cs%a_u(i,j,1))
       b1(i) = 1.0 / (b_denom_1 + dt_m_to_h*cs%a_u(i,j,2))
       d1(i) = b_denom_1 * b1(i)
       visc_rem_u(i,j,1) = b1(i) * cs%h_u(i,j,1)
     endif ; enddo
     do k=2,nz ; do i=isq,ieq ; if (do_i(i)) then
       c1(i,k) = dt_m_to_h * cs%a_u(i,j,k)*b1(i)
       b_denom_1 = cs%h_u(i,j,k) + dt_m_to_h * (ray(i,k) + cs%a_u(i,j,k)*d1(i))
       b1(i) = 1.0 / (b_denom_1 + dt_m_to_h * cs%a_u(i,j,k+1))
       d1(i) = b_denom_1 * b1(i)
       visc_rem_u(i,j,k) = (cs%h_u(i,j,k) + dt_m_to_h * cs%a_u(i,j,k) * visc_rem_u(i,j,k-1)) * b1(i)
     endif ; enddo ; enddo
     do k=nz-1,1,-1 ; do i=isq,ieq ; if (do_i(i)) then
       visc_rem_u(i,j,k) = visc_rem_u(i,j,k) + c1(i,k+1)*visc_rem_u(i,j,k+1)
     endif ; enddo ; enddo ! i and k loops
   enddo ! end u-component j loop
   ! Now find the meridional viscous using a modification.
 !$OMP parallel do default(none) shared(Jsq,Jeq,is,ie,G,CS,visc,dt_m_to_H,visc_rem_v,nz) &
 !$OMP                     firstprivate(Ray)                                             &
 !$OMP                          private(do_i,b_denom_1,b1,d1,c1)
   do j=jsq,jeq
     do i=is,ie ; do_i(i) = (g%mask2dCv(i,j) > 0) ; enddo
     if (cs%Channel_drag) then ; do k=1,nz ; do i=is,ie
       ray(i,k) = visc%Ray_v(i,j,k)
     enddo ; enddo ; endif
     do i=is,ie ; if (do_i(i)) then
       b_denom_1 = cs%h_v(i,j,1) + dt_m_to_h * (ray(i,1) + cs%a_v(i,j,1))
       b1(i) = 1.0 / (b_denom_1 + dt_m_to_h*cs%a_v(i,j,2))
       d1(i) = b_denom_1 * b1(i)
       visc_rem_v(i,j,1) = b1(i) * cs%h_v(i,j,1)
     endif ; enddo
     do k=2,nz ; do i=is,ie ; if (do_i(i)) then
       c1(i,k) = dt_m_to_h * cs%a_v(i,j,k)*b1(i)
       b_denom_1 = cs%h_v(i,j,k) + dt_m_to_h *  (ray(i,k) + cs%a_v(i,j,k)*d1(i))
       b1(i) = 1.0 / (b_denom_1 + dt_m_to_h * cs%a_v(i,j,k+1))
       d1(i) = b_denom_1 * b1(i)
       visc_rem_v(i,j,k) = (cs%h_v(i,j,k) + dt_m_to_h * cs%a_v(i,j,k) * visc_rem_v(i,j,k-1)) * b1(i)
     endif ; enddo ; enddo
     do k=nz-1,1,-1 ; do i=is,ie ; if (do_i(i)) then
       visc_rem_v(i,j,k) = visc_rem_v(i,j,k) + c1(i,k+1)*visc_rem_v(i,j,k+1)
     endif ; enddo ; enddo ! i and k loops
   enddo ! end of v-component J loop
   if (cs%debug) then
     call uvchksum("visc_rem_[uv]", visc_rem_u, visc_rem_v, g%HI,haloshift=0)
   endif