# Copyright ACCESS-NRI and contributors. See the top-level LICENSE file for details.

add_fortran_target(mom6shared LIB mod STATIC)

target_link_libraries(mom6shared PUBLIC 
  FMS::fms_r8 
  GFDLGTracers::gtracers
)

if(OpenMP_Fortran_FOUND)
    target_link_libraries(mom6shared PRIVATE OpenMP::OpenMP_Fortran)
endif()

target_include_directories(mom6shared PUBLIC
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/framework>
  $<BUILD_INTERFACE:$<IF:$<BOOL:${MOM6_ASYMMETRIC}>,
    ${CMAKE_CURRENT_SOURCE_DIR}/../config_src/memory/dynamic_nonsymmetric,
    ${CMAKE_CURRENT_SOURCE_DIR}/../config_src/memory/dynamic_symmetric>>
)

target_sources(mom6shared PRIVATE
  ALE/coord_adapt.F90
  ALE/coord_hycom.F90
  ALE/coord_rho.F90
  ALE/coord_sigma.F90
  ALE/coord_zlike.F90
  ALE/MOM_ALE.F90
  ALE/MOM_hybgen_regrid.F90
  ALE/MOM_hybgen_remap.F90
  ALE/MOM_hybgen_unmix.F90
  ALE/MOM_regridding.F90
  ALE/MOM_remapping.F90
  ALE/P1M_functions.F90
  ALE/P3M_functions.F90
  ALE/PCM_functions.F90
  ALE/PLM_functions.F90
  ALE/polynomial_functions.F90
  ALE/PPM_functions.F90
  ALE/PQM_functions.F90
  ALE/Recon1d_EMPLM_CWK.F90
  ALE/Recon1d_EMPLM_WA.F90
  ALE/Recon1d_EMPLM_WA_poly.F90
  ALE/Recon1d_EPPM_CWK.F90
  ALE/Recon1d_MPLM_CWK.F90
  ALE/Recon1d_MPLM_WA.F90
  ALE/Recon1d_MPLM_WA_poly.F90
  ALE/Recon1d_PCM.F90
  ALE/Recon1d_PLM_CW.F90
  ALE/Recon1d_PLM_CWK.F90
  ALE/Recon1d_PLM_hybgen.F90
  ALE/Recon1d_PPM_CW.F90
  ALE/Recon1d_PPM_CWK.F90
  ALE/Recon1d_PPM_H4_2018.F90
  ALE/Recon1d_PPM_H4_2019.F90
  ALE/Recon1d_PPM_hybgen.F90
  ALE/Recon1d_type.F90
  ALE/regrid_consts.F90
  ALE/regrid_edge_values.F90
  ALE/regrid_interp.F90
  ALE/regrid_solvers.F90

  core/MOM_barotropic.F90
  core/MOM_boundary_update.F90
  core/MOM_check_scaling.F90
  core/MOM_checksum_packages.F90
  core/MOM_continuity.F90
  core/MOM_continuity_PPM.F90
  core/MOM_CoriolisAdv.F90
  core/MOM_density_integrals.F90
  core/MOM_dynamics_split_RK2.F90
  core/MOM_dynamics_split_RK2b.F90
  core/MOM_dynamics_unsplit.F90
  core/MOM_dynamics_unsplit_RK2.F90
  core/MOM.F90
  core/MOM_grid.F90
  core/MOM_interface_heights.F90
  core/MOM_isopycnal_slopes.F90
  core/MOM_open_boundary.F90
  core/MOM_porous_barriers.F90
  core/MOM_PressureForce.F90
  core/MOM_PressureForce_FV.F90
  core/MOM_PressureForce_Montgomery.F90
  core/MOM_stoch_eos.F90
  core/MOM_transcribe_grid.F90
  core/MOM_unit_tests.F90
  core/MOM_variables.F90
  core/MOM_verticalGrid.F90
  core/MOM_forcing_type.F90

  diagnostics/MOM_debugging.F90
  diagnostics/MOM_diagnose_KdWork.F90
  diagnostics/MOM_diagnose_MLD.F90
  diagnostics/MOM_diagnostics.F90
  diagnostics/MOM_harmonic_analysis.F90
  diagnostics/MOM_obsolete_diagnostics.F90
  diagnostics/MOM_obsolete_params.F90
  diagnostics/MOM_PointAccel.F90
  diagnostics/MOM_spatial_means.F90
  diagnostics/MOM_sum_output.F90
  diagnostics/MOM_wave_speed.F90

  equation_of_state/MOM_EOS.F90
  equation_of_state/MOM_EOS_base_type.F90
  equation_of_state/MOM_EOS_Jackett06.F90
  equation_of_state/MOM_EOS_linear.F90
  equation_of_state/MOM_EOS_Roquet_rho.F90
  equation_of_state/MOM_EOS_Roquet_SpV.F90
  equation_of_state/MOM_EOS_TEOS10.F90
  equation_of_state/MOM_EOS_UNESCO.F90
  equation_of_state/MOM_EOS_Wright.F90
  equation_of_state/MOM_EOS_Wright_full.F90
  equation_of_state/MOM_EOS_Wright_red.F90
  equation_of_state/MOM_temperature_convert.F90
  equation_of_state/MOM_TFreeze.F90

  equation_of_state/TEOS10/gsw_chem_potential_water_t_exact.f90
  equation_of_state/TEOS10/gsw_ct_freezing_exact.f90
  equation_of_state/TEOS10/gsw_ct_freezing_poly.f90
  equation_of_state/TEOS10/gsw_ct_from_pt.f90
  equation_of_state/TEOS10/gsw_ct_from_t.f90
  equation_of_state/TEOS10/gsw_entropy_part.f90
  equation_of_state/TEOS10/gsw_entropy_part_zerop.f90
  equation_of_state/TEOS10/gsw_gibbs.f90
  equation_of_state/TEOS10/gsw_gibbs_ice.f90
  equation_of_state/TEOS10/gsw_gibbs_pt0_pt0.f90
  equation_of_state/TEOS10/gsw_mod_error_functions.f90
  equation_of_state/TEOS10/gsw_mod_freezing_poly_coefficients.f90
  equation_of_state/TEOS10/gsw_mod_gibbs_ice_coefficients.f90
  equation_of_state/TEOS10/gsw_mod_kinds.f90
  equation_of_state/TEOS10/gsw_mod_specvol_coefficients.f90
  equation_of_state/TEOS10/gsw_mod_teos10_constants.f90
  equation_of_state/TEOS10/gsw_mod_toolbox.f90
  equation_of_state/TEOS10/gsw_pt0_from_t.f90
  equation_of_state/TEOS10/gsw_pt_from_ct.f90
  equation_of_state/TEOS10/gsw_pt_from_t.f90
  equation_of_state/TEOS10/gsw_rho.f90
  equation_of_state/TEOS10/gsw_rho_first_derivatives.f90
  equation_of_state/TEOS10/gsw_rho_second_derivatives.f90
  equation_of_state/TEOS10/gsw_sp_from_sr.f90
  equation_of_state/TEOS10/gsw_sr_from_sp.f90
  equation_of_state/TEOS10/gsw_specvol.f90
  equation_of_state/TEOS10/gsw_specvol_first_derivatives.f90
  equation_of_state/TEOS10/gsw_specvol_second_derivatives.f90
  equation_of_state/TEOS10/gsw_t_deriv_chem_potential_water_t_exact.f90
  equation_of_state/TEOS10/gsw_t_freezing_exact.f90
  equation_of_state/TEOS10/gsw_t_freezing_poly.f90
  equation_of_state/TEOS10/gsw_t_from_ct.f90

  framework/MOM_ANN.F90
  framework/MOM_array_transform.F90
  framework/MOM_checksums.F90
  framework/MOM_coms.F90
  framework/MOM_cpu_clock.F90
  framework/MOM_data_override.F90
  framework/MOM_diag_mediator.F90
  framework/MOM_diag_remap.F90
  framework/MOM_document.F90
  framework/MOM_domains.F90
  framework/MOM_dyn_horgrid.F90
  framework/MOM_ensemble_manager.F90
  framework/MOM_error_handler.F90
  framework/MOM_file_parser.F90
  framework/MOM_get_input.F90
  framework/MOM_hor_index.F90
  framework/MOM_horizontal_regridding.F90
  framework/MOM_interpolate.F90
  framework/MOM_intrinsic_functions.F90
  framework/MOM_io.F90
  framework/MOM_io_file.F90
  framework/MOM_memory_macros.h
  framework/MOM_murmur_hash.F90
  framework/MOM_netcdf.F90
  framework/numerical_testing_type.F90
  framework/MOM_random.F90
  framework/MOM_restart.F90
  framework/MOM_safe_alloc.F90
  framework/MOM_string_functions.F90
  framework/MOM_unique_scales.F90
  framework/MOM_unit_scaling.F90
  framework/MOM_write_cputime.F90
  framework/posix.F90
  framework/MOM_coupler_types.F90

  ice_shelf/MOM_ice_shelf_diag_mediator.F90
  ice_shelf/MOM_ice_shelf_dynamics.F90
  ice_shelf/MOM_ice_shelf.F90
  ice_shelf/MOM_ice_shelf_initialize.F90
  ice_shelf/MOM_ice_shelf_state.F90
  ice_shelf/MOM_marine_ice.F90
  ice_shelf/user_shelf_init.F90

  initialization/MOM_coord_initialization.F90
  initialization/MOM_fixed_initialization.F90
  initialization/MOM_grid_initialize.F90
  initialization/MOM_shared_initialization.F90
  initialization/MOM_state_initialization.F90
  initialization/MOM_tracer_initialization_from_Z.F90

  ocean_data_assim/MOM_oda_driver.F90
  ocean_data_assim/MOM_oda_incupd.F90

  parameterizations/CVmix/cvmix_background.F90
  parameterizations/CVmix/cvmix_convection.F90
  parameterizations/CVmix/cvmix_ddiff.F90
  parameterizations/CVmix/cvmix_kinds_and_types.F90
  parameterizations/CVmix/cvmix_kpp.F90
  parameterizations/CVmix/cvmix_math.F90
  parameterizations/CVmix/cvmix_put_get.F90
  parameterizations/CVmix/cvmix_shear.F90
  parameterizations/CVmix/cvmix_tidal.F90
  parameterizations/CVmix/cvmix_utils.F90

  parameterizations/lateral/MOM_hor_visc.F90
  parameterizations/lateral/MOM_interface_filter.F90
  parameterizations/lateral/MOM_internal_tides.F90
  parameterizations/lateral/MOM_lateral_mixing_coeffs.F90
  parameterizations/lateral/MOM_load_love_numbers.F90
  parameterizations/lateral/MOM_MEKE.F90
  parameterizations/lateral/MOM_MEKE_types.F90
  parameterizations/lateral/MOM_mixed_layer_restrat.F90
  parameterizations/lateral/MOM_spherical_harmonics.F90
  parameterizations/lateral/MOM_streaming_filter.F90
  parameterizations/lateral/MOM_self_attr_load.F90
  parameterizations/lateral/MOM_thickness_diffuse.F90
  parameterizations/lateral/MOM_tidal_forcing.F90
  parameterizations/lateral/MOM_wave_drag.F90
  parameterizations/lateral/MOM_Zanna_Bolton.F90

  parameterizations/stochastic/MOM_stochastics.F90

  parameterizations/vertical/MOM_ALE_sponge.F90
  parameterizations/vertical/MOM_bkgnd_mixing.F90
  parameterizations/vertical/MOM_bulk_mixed_layer.F90
  parameterizations/vertical/MOM_CVMix_conv.F90
  parameterizations/vertical/MOM_CVMix_ddiff.F90
  parameterizations/vertical/MOM_CVMix_KPP.F90
  parameterizations/vertical/MOM_CVMix_shear.F90
  parameterizations/vertical/MOM_diabatic_aux.F90
  parameterizations/vertical/MOM_diabatic_driver.F90
  parameterizations/vertical/MOM_diapyc_energy_req.F90
  parameterizations/vertical/MOM_energetic_PBL.F90
  parameterizations/vertical/MOM_entrain_diffusive.F90
  parameterizations/vertical/MOM_full_convection.F90
  parameterizations/vertical/MOM_geothermal.F90
  parameterizations/vertical/MOM_internal_tide_input.F90
  parameterizations/vertical/MOM_kappa_shear.F90
  parameterizations/vertical/MOM_opacity.F90
  parameterizations/vertical/MOM_regularize_layers.F90
  parameterizations/vertical/MOM_set_diffusivity.F90
  parameterizations/vertical/MOM_set_viscosity.F90
  parameterizations/vertical/MOM_sponge.F90
  parameterizations/vertical/MOM_tidal_mixing.F90
  parameterizations/vertical/MOM_vert_friction.F90

  tracer/advection_test_tracer.F90
  tracer/boundary_impulse_tracer.F90
  tracer/DOME_tracer.F90
  tracer/dyed_obc_tracer.F90
  tracer/dye_example.F90
  tracer/file_dye_tracer.F90
  tracer/ideal_age_example.F90
  tracer/ISOMIP_tracer.F90
  tracer/MOM_CFC_cap.F90
  tracer/MOM_generic_tracer.F90
  tracer/MOM_hor_bnd_diffusion.F90
  tracer/MARBL_forcing_mod.F90
  tracer/MARBL_tracers.F90
  tracer/MOM_neutral_diffusion.F90
  tracer/MOM_OCMIP2_CFC.F90
  tracer/MOM_offline_aux.F90
  tracer/MOM_offline_main.F90
  tracer/MOM_tracer_advect.F90
  tracer/MOM_tracer_advect_schemes.F90
  tracer/MOM_tracer_diabatic.F90
  tracer/MOM_tracer_flow_control.F90
  tracer/MOM_tracer_hor_diff.F90
  tracer/MOM_tracer_registry.F90
  tracer/MOM_tracer_types.F90
  tracer/MOM_tracer_Z_init.F90
  tracer/nw2_tracers.F90
  tracer/oil_tracer.F90
  tracer/pseudo_salt_tracer.F90
  tracer/RGC_tracer.F90
  tracer/tracer_example.F90

  user/adjustment_initialization.F90
  user/baroclinic_zone_initialization.F90
  user/basin_builder.F90
  user/benchmark_initialization.F90
  user/BFB_initialization.F90
  user/BFB_surface_forcing.F90
  user/circle_obcs_initialization.F90
  user/dense_water_initialization.F90
  user/DOME2d_initialization.F90
  user/DOME_initialization.F90
  user/dumbbell_initialization.F90
  user/dumbbell_surface_forcing.F90
  user/dyed_channel_initialization.F90
  user/dyed_obcs_initialization.F90
  user/external_gwave_initialization.F90
  user/Idealized_Hurricane.F90
  user/ISOMIP_initialization.F90
  user/Kelvin_initialization.F90
  user/lock_exchange_initialization.F90
  user/MOM_controlled_forcing.F90
  user/MOM_wave_interface.F90
  user/Neverworld_initialization.F90
  user/Phillips_initialization.F90
  user/RGC_initialization.F90
  user/Rossby_front_2d_initialization.F90
  user/SCM_CVMix_tests.F90
  user/seamount_initialization.F90
  user/shelfwave_initialization.F90
  user/sloshing_initialization.F90
  user/soliton_initialization.F90
  user/supercritical_initialization.F90
  user/tidal_bay_initialization.F90
  user/user_change_diffusivity.F90
  user/user_initialization.F90
  user/user_revise_forcing.F90

  ../config_src/external/database_comms/MOM_database_comms.F90
  ../config_src/external/database_comms/database_client_interface.F90

  ../config_src/external/drifters/MOM_particles.F90
  ../config_src/external/drifters/MOM_particles_types.F90

  ../config_src/external/ODA_hooks/kdtree.f90
  ../config_src/external/ODA_hooks/ocean_da_core.F90
  ../config_src/external/ODA_hooks/ocean_da_types.F90
  ../config_src/external/ODA_hooks/write_ocean_obs.F90

  ../config_src/external/stochastic_physics/get_stochy_pattern.F90
  ../config_src/external/stochastic_physics/stochastic_physics.F90

  ../config_src/infra/FMS2/MOM_coms_infra.F90
  ../config_src/infra/FMS2/MOM_constants.F90
  ../config_src/infra/FMS2/MOM_couplertype_infra.F90
  ../config_src/infra/FMS2/MOM_cpu_clock_infra.F90
  ../config_src/infra/FMS2/MOM_data_override_infra.F90
  ../config_src/infra/FMS2/MOM_diag_manager_infra.F90
  ../config_src/infra/FMS2/MOM_domain_infra.F90
  ../config_src/infra/FMS2/MOM_ensemble_manager_infra.F90
  ../config_src/infra/FMS2/MOM_error_infra.F90
  ../config_src/infra/FMS2/MOM_interp_infra.F90
  ../config_src/infra/FMS2/MOM_io_infra.F90
  ../config_src/infra/FMS2/MOM_time_manager.F90

  ../config_src/external/MARBL/marbl_constants_mod.F90
  ../config_src/external/MARBL/marbl_interface.F90
  ../config_src/external/MARBL/marbl_interface_public_types.F90
  ../config_src/external/MARBL/marbl_logging.F90
)
