name: Code coverage

on: [push, pull_request]

jobs:
  build-coverage:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .testing

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: ./.github/actions/ubuntu-setup

    - uses: ./.github/actions/testing-setup

    - name: Compile unit tests
      run: make -j build.unit

    - name: Run unit tests
      run: make run.cov.unit

    - name: Report unit test coverage to CI
      run: make report.cov.unit
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Compile ocean-only MOM6 with code coverage
      run: make -j build/cov/MOM6

    - name: Run coverage tests
      run: make -k run.cov

    - name: Report coverage to CI
      run: make report.cov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
