name: MacOS regression

on: [pull_request]

jobs:
  test-macos-regression:

    runs-on: macOS-latest

    env:
      CC: gcc
      FC: gfortran
      FMS_COMMIT: 2019.01.03

    defaults:
      run:
        working-directory: .testing

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: ./.github/actions/macos-setup

    - uses: ./.github/actions/testing-setup

    - name: Compile reference model
      run: make build.regressions MOM_TARGET_SLUG=$GITHUB_REPOSITORY MOM_TARGET_LOCAL_BRANCH=$GITHUB_BASE_REF DO_REGRESSION_TESTS=true -j

    - name: Create validation data
      run: make run.symmetric -k -s

    - name: Regression test
      run: make test.regression DO_REGRESSION_TESTS=true -k -s
